### ISSUE TITLE
Error with jupyter-core requirement while building from source (python3)

### ISSUE THREAD

**Issue by payamr** [isl-org/Open3D#1049]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
When I try to build open3d from source on Mac, I get an error at the `make install-pip-package` stage. I followed the 5 steps laid out in the documentation.

**To Reproduce**
I followed the 5 steps laid out in the documentation. At the end of step 5, I get an error.

**Error message**
This is the last part, which seems to be the relevant part of the error message.
```
Collecting jupyter-core>=4.4.0 (from notebook->open3d==0.7.0.0)
  ERROR: Could not find a version that satisfies the requirement jupyter-core>=4.4.0 (from notebook->open3d==0.7.0.0) (from versions: none)
ERROR: No matching distribution found for jupyter-core>=4.4.0 (from notebook->open3d==0.7.0.0)
[100%] Built target install-pip-package
```
**Environment (please complete the following information):**
 - OS: OSX High-Sierra
 - Python version: 3.6
 - Open3D version: 0.7.0.0
 - Is this remote workstation?:  no
 - How did you install Open3D?: build_from_source (using cmake)

**Comment by syncle** [comment]
Have you checked out [this document](http://www.open3d.org/docs/release/compilation.html#jupyter-visualization-widgets-support-experimental)? You would need to install npm to Jupyter visualization working.

**Comment by reyanshsolis** [comment]
Closing this issue, due to inactivity. Please try the latest release and refer to the documentation. Feel free to re-open the issue, if any help is required. Thanks.
