### ISSUE TITLE
order in add_geometry

### ISSUE THREAD

**Issue by sherwoac** [isl-org/Open3D#1050]
I want to render multiple point clouds on top of an image in python.

At the moment, to do this, I use vis.add_geometry(<item>) to each item and then the image last. This normally works, but about 1/3 frames drops one or more of the point clouds from the end of the list. By removing the image from the list, I discovered that this is because the missing item(s) is _behind_ the image.

So, this is a bug, and or feature request. Either the ordering of the list should be strict ordering, so that each item is rendered on top of the others (depending on position in the image), so the most recent items are in the foreground - or the opposite order - but a strict and documented order.

reproduction is something like:

where you have to populate the list with your own pcds and image.

    def render_scene(self, geom_list):
        for geom in geom_list:
            self.vis.add_geometry(geom)
        self.change_view_to_origin()
        self.vis.update_geometry()
        self.vis.poll_events()
        self.vis.update_renderer()
        rendered_open3d_image = self.vis.capture_screen_float_buffer()
        rendered_rgb_image = np.array(np.asarray(rendered_open3d_image) * 255, dtype=np.uint8)
        for geom in geom_list:
            self.vis.remove_geometry(geom)
        return rendered_rgb_image

        object_pcds = []
        for pcd in pcds:
            object_pcds.append(pcd)
        object_pcds.append(open3d.geometry.Image(image_data))

        render_scene(object_pcds)

Screen shots, please ignore LH window pane, this is the original image.

It works intermittently:
![image](https://user-images.githubusercontent.com/11062064/60400114-cf1d7480-9b6f-11e9-823b-111ceeab5106.png)
Example of not working
![image](https://user-images.githubusercontent.com/11062064/60400116-d775af80-9b6f-11e9-833a-37128d9f7545.png)

**Environment (please complete the following information):**
 - OS: ubuntu 18.04
 - Python version: 3.6.8 
 - Open3D version: 0.7.0.0
from conda open3d-admin

**Comment by germanros1987** [comment]
I think this is possibly an issue even in today's visualizer. Can we load images in the background in the new visualizer @errissa ?

**Comment by germanros1987** [comment]
This is now possible in the new visualizer.
