### ISSUE TITLE
Painting faces instead of vertices for meshes

### ISSUE THREAD

**Issue by lucabergamini** [isl-org/Open3D#1087]
**Is your feature request related to a problem? Please describe.**
Currently, it's only possible to colour meshes via the ```vertex_colors``` attribute. However, this may introduces artifacts due to interpolation between the 3 points of a face if the colour source is related to faces instead of vertices (as a Blender's material).

![ScreenCapture_2019-07-23-19-13-39](https://user-images.githubusercontent.com/27865235/61736440-056c9f00-ad7e-11e9-9b5d-13de7eeddfe4.png)
  
![ScreenCapture_2019-07-23-19-19-25](https://user-images.githubusercontent.com/27865235/61736804-d0148100-ad7e-11e9-95aa-e3ed99974866.png)

**Describe the solution you'd like**
It would be great to have the possibility to set the colour for faces along with vertices (two different modes maybe?).  

**Describe alternatives you've considered**
As the issue is related with the size of the faces, subdividing the mesh's triangles reduces its magnitude but also increases computation.

**Comment by yxlao** [comment]
Mesh is colored by vertices in open3d. To support "pure-color face", we can create 3 vertices for each triangle, and assign the same color to all 3 vertices for each triangle. That is, we'll end up with `N` triangles and exactly `3N` vertices.

**Comment by griegler** [comment]
@yxlao The problem with this approach is that it then isn't a triangle mesh anymore, but a triangle soup. Hence, algorithms like filtering will not work as expected. We should consider facet colors in our new design of the geometry classes.

**Comment by lucabergamini** [comment]
What @yxlao proposes does work in fact, but as @griegler points out the mesh's triangles are no longer connected.

![ScreenCapture_2019-07-24-12-13-13](https://user-images.githubusercontent.com/27865235/61789381-7d81a600-ae0c-11e9-8437-ac8fcdda43f6.png)

Still, it's the only fix at the moment and should be enough for what I'm trying to do. 
Here is a quick implementation to convert a mesh in independent triangles apt to be colourised as faces:

```
def split_triangles(mesh: o3d.TriangleMesh) -> o3d.TriangleMesh:
    """
    Split the mesh in independent triangles    
    """
    triangles = np.asarray(mesh.triangles).copy()
    vertices = np.asarray(mesh.vertices).copy()

    triangles_3 = np.zeros_like(triangles)
    vertices_3 = np.zeros((len(triangles) * 3, 3), dtype=vertices.dtype)

    for index_triangle, t in enumerate(triangles):
        index_vertex = index_triangle * 3
        vertices_3[index_vertex] = vertices[t[0]]
        vertices_3[index_vertex + 1] = vertices[t[1]]
        vertices_3[index_vertex + 2] = vertices[t[2]]

        triangles_3[index_triangle] = np.arange(index_vertex, index_vertex + 3)

    mesh_return = deepcopy(mesh)
    mesh_return.triangles = o3d.Vector3iVector(triangles_3)
    mesh_return.vertices = o3d.Vector3dVector(vertices_3)
    return mesh_return
```

**Comment by yxlao** [comment]
@griegler Right, this will become a triangle soup. So it's a temporary workaround.

**Comment by errissa** [comment]
This feature is planned for 0.12 release.

**Comment by rubenverhack** [comment]
> This feature is planned for 0.12 release.

Is there any news on this? For me this makes open3d unusable for my use case.

**Comment by germanros1987** [comment]
@errissa is this available now?

**Comment by errissa** [comment]
This is available now. The visualizer supports per-face colors. However, only `t::geometry::TriangleMesh` supports setting colors per-face using `Set/GetTriangleColors`. Also, if a `TriangleMesh` has both vertex and triangle colors the visualizer will use the vertex colors.

**Comment by andy-beer** [comment]
@errissa, Is there a python binding for SetTriangleColours?

**Comment by errissa** [comment]
@andy-beer `SetTriangleColors` is a convenience function in C++ that isn't really necessary in Python. In Python the following is the exact equivalent of using `SetTriangleColors`:
```
mesh.triangle["colors"] = o3d.core.Tensor(...)
```

**Comment by Jerrypiglet** [comment]
@errissa Thanks for the info! However I found _open3d.geometry.TriangleMesh_ has no property named _'triangle'_ as indicated here http://www.open3d.org/docs/release/python_api/open3d.geometry.TriangleMesh.html# Any ideas?
