### ISSUE TITLE
Does the FLANN version matter?

### ISSUE THREAD

**Issue by Andreachen0707** [isl-org/Open3D#1090]
Hi,
I run into a weird problem here. I'm using flann-1.9.1, instead of 1.8.x. 

This is the error I got from the output:
*** Aborted at 1563998138 (unix time) try "date -d @1563998138" if you are using GNU date ***
PC: @     0x557a80d449c1 flann::create_index_by_type<>()
*** SIGSEGV (@0x9) received by PID 30123 (TID 0x7f64523dd700) from PID 9; stack trace: ***
    @     0x7f646270c0e0 (unknown)
    @     0x557a80d449c1 flann::create_index_by_type<>()
    @     0x557a80d44f70 flann::Index<>::Index()
    @     0x557a80d3c9ce open3d::geometry::KDTreeFlann::SetRawData()
    @     0x557a80d3cd62 open3d::geometry::KDTreeFlann::SetGeometry()
    @     0x557a80d38278 open3d::geometry::PointCloud::EstimateNormals()
Segmentation fault

Any hint will be grateful!
Many thanks!

Best
Andrea

**Comment by kings-landing** [comment]
@Open3D maintainers: 
maybe upgrading flann version can fix the memory leak issue as reported in https://github.com/intel-isl/Open3D/issues/1103?

**Comment by germanros1987** [comment]
@syncle could you please comment on this?

**Comment by reyanshsolis** [comment]
Closing this outdated issue, as we are no longer using FLANN.
Thanks.
