### ISSUE TITLE
Remove ground using 2 point clouds

### ISSUE THREAD

**Issue by JoshMB8** [isl-org/Open3D#1114]
Hello,

I have 2 point clouds; Point Cloud 1 is mainly ground. Point Cloud 2 is the exact same area but after flowers have grown.

My question is, is there a way I can remove points from cloud 2 that match with points in cloud 1 AFTER I have done manual registration on the clouds?

Thank you.

**Comment by germanros1987** [comment]
@JoshMB8 are you still interested in this question?

**Comment by reyanshsolis** [comment]
Hi @JoshMB8, sorry for the delay.
You may try the following:
- You can get correspondences between two point cloud (refer the ICP function, GetRegistrationResultAndCorrespondences) function to understand how to get the correspondence set and use it). [Set search radius to a small value].
- Remove points at these indices from the second pointcloud.

Thanks!
