### ISSUE TITLE
Wrapping C++ code to python

### ISSUE THREAD

**Issue by HndsmJohn** [isl-org/Open3D#1137]
Hello,

I am currently working on a Server/Client project that use Open3D and Librealsense in C++. Basically the client is reconstructing a point cloud from the data sent by the server. Though i would like the client's methods to be accessible from a python script.
I have the Open3D libraries built in my C++ project directory and a python build in my conda environment.
I'm using SWIG in order to wrap my client class.

I got two questions about this :

- Has someone already tried to wrap C++ code using Open3D with SWIG ? If yes how can I link
  the Open3D library dependencies (like Eigen) to my code during the compilation with distutils.

- How are the objects managed in that case ? Can I interface an C++ object using the C++ libraries with a python object using the python module without copying the data inside (the points vector from a point cloud for example) ?

Thanks you in advance for your help.

**Comment by germanros1987** [comment]
@HndsmJohn sorry for the delay. Are you still interested in this issue?

Have you tried using pybind11?

**Comment by reyanshsolis** [comment]
Closing the issue due to inactivity.

One may refer to the methods used in open3d to wrap C++ objects using pybind.
Thanks.
