### ISSUE TITLE
Making open3d flann faster: open3d KDTreeFlann seems slower than scipy.spatial.cKDTree

### ISSUE THREAD

**Issue by chrischoy** [isl-org/Open3D#1159]
```python
import open3d as o3d
from time import time
import numpy as np

from scipy.spatial import cKDTree

k = 1
for N0 in [1e4]:
  for N1 in [1e4]:
    for D in [16, 32, 64, 128]:

      N0, N1 = int(N0), int(N1)
      D = int(D)
      feat0 = np.random.rand(N0, D)
      feat1 = np.random.rand(N1, D)

      print(N0, N1, D)
      # Open3D
      t = time()
      feat1tree = o3d.KDTreeFlann(feat1.T)
      print(time() - t)

      t = time()
      for i in range(len(feat0)):
        _, idx1, dist = feat1tree.search_knn_vector_xd(feat0[i], k)
      print(time() - t)

      # cKDTree
      t = time()
      feat1tree = cKDTree(feat1)
      print(time() - t)

      t = time()
      feat1tree.query(feat0, k, n_jobs=-1)
      print(time() - t)
```

The above code gives me the following results on my laptop with Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz.

```
10000 10000 16
0.009177207946777344
1.0807807445526123
0.004488468170166016
0.404787540435791

10000 10000 32
0.031982421875
2.3513145446777344
0.005837202072143555
0.9437735080718994

10000 10000 64
0.016597509384155273
4.255510330200195
0.009362936019897461
2.3426921367645264

10000 10000 128
0.05002927780151367
7.94594669342041
0.01823258399963379
5.438387393951416
```

First two numbers for Open3D KDTree creation and query, second half for the scipy kdtree creation and query.

For D=32
KDTree construction of open3d is ~6x slower than cKDTree construction.
For qeuries, open3d is ~2.5x slower.

I think it is not using all threads effectively and when it queries, it passes the features one-by-one rather than passing it in a batch mode resulting in overhead.

I think it would be nice to have at least a batch mode for queries to remove unnecessary pybind communication overheads.

**Comment by yangninghua** [comment]
@yxlao 
Hello, I have the same question. Why can't it be the nearest neighbor of point cloud? Python-pcl is supported. I don't know if open3d can support it in the future?

```
import pcl
import numpy as np

def get_min_dist(cloud1, cloud2, K=1):
    kdtree = cloud2.make_kdtree_flann()
    indices, sqr_distances = kdtree.nearest_k_search_for_cloud(cloud1, K)
    return np.squeeze(sqr_distances), np.squeeze(indices)
```

**Comment by yangninghua** [comment]
This is similar to what he said

```
import scipy.spatial
import numpy as np

def get_min_dist(cloud1, cloud2, K=1):
    kdtree = scipy.spatial.cKDTree(np.array(cloud2))
    sqr_distances, indices = kdtree.query(np.array(cloud1), k=K)
    te = np.square(sqr_distances)
    return te, indices
```

**Comment by germanros1987** [comment]
I know we haven't commented on this issue in a long while (sorry about that). However, I am here to bring some hope. We are actively working on a new NeighborSearch module with support for high-performance algorithms. This should really help with the issues experienced in past versions of Open3D. Please, stay tune.

**Comment by tetterl** [comment]
@germanros1987 Is there any update on this? Aka is this still work in progress?

**Comment by reyanshsolis** [comment]
Flann is removed from Open3D. Closing Issue as Depreciated.
