### ISSUE TITLE
Viewer and camera height and width issue

### ISSUE THREAD

**Issue by arunmallya** [isl-org/Open3D#1164]
**Describe the bug**
`[ViewControl] ConvertFromPinholeCameraParameters() failed because window height and width do not match.`
Setting the view to a specified camera fails even when the window height and width of the viewer and the camera match.

**To Reproduce**
https://gist.github.com/arunmallya/41374d7eed6a52923b6ca2eb864b420a
Data file: https://uofi.box.com/s/spqlqx6c6tggpedv6ehs6muz0deyogy0

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04
 - Python version: 3.5.2
 - Open3D version: 0.7.0.0
 - Is this remote workstation?: no
 - How did you install Open3D?: pip

**Comment by syncle** [comment]
Could you check [these lines](https://github.com/intel-isl/Open3D/blob/80915c28353286868849f8b6fcd122bd0e62b826/src/Open3D/Visualization/Visualizer/ViewControl.cpp#L173-L182)? You may need to replace
```
K = [[focal * width, 0, width / 2],
     [0, focal * width, height / 2],
     [0, 0, 1]]
```
as
```
K = [[focal * width, 0, width / 2 - 0.5],
     [0, focal * width, height / 2 - 0.5],
     [0, 0, 1]]
```

**Comment by germanros1987** [comment]
@errissa we will take care of this after the 0.11 release...

**Comment by tfy14esa** [comment]
@germanros1987 So there is still not solution to this problem? Adding -0.5 as suggested above did not work for me. I am trying to run the example script customized_visualization.py

**Comment by Zumbalamambo** [comment]
@germanros1987 so curious... Stuck with this issue for a week

**Comment by gonultasbu** [comment]
Interesting issue, I have also noticed that when you capture an image by pressing "P" (or "D" for depth). The intrinsic matrix centers and camera resolution (H and W) do not agree. Which is probably caused by this check.

`	"intrinsic" : 
	{
		"height" : 499,
		"intrinsic_matrix" : 
		[
			432.14667648843493,
			0.0,
			0.0,
			0.0,
			432.14667648843493,
			0.0,
			549.5,
			249.0,
			1.0
		],
		"width" : 1100
	},`

**Comment by gonultasbu** [comment]
@tfy14esa thank you for your effort!

Adding -0.5 as suggested above did not solve the problem for me either. Turns out the window size also has to match with the intrinsic parameters and resolution. As follows:

`viewer.create_window(width=width, height=height)`

**Comment by hanjiangrui** [comment]
> @tfy14esa thank you for your effort!
> 
> Adding -0.5 as suggested above did not solve the problem for me either. Turns out the window size also has to match with the intrinsic parameters and resolution. As follows:
> 
> `viewer.create_window(width=width, height=height)`
it's right

**Comment by theNded** [comment]
Should have been supported in #2564.

**Comment by RuipingL** [comment]
in current version, you should set the parameter allow_arbitrary=True, i.e.,
view_control.convert_from_pinhole_camera_parameters(cam_params, allow_arbitrary=True)

**Comment by Paullfx** [comment]
> in current version, you should set the parameter allow_arbitrary=True, i.e., view_control.convert_from_pinhole_camera_parameters(cam_params, allow_arbitrary=True)

This works! Saves my day :)

**Comment by zhaoruifeng1211** [comment]
> in current version, you should set the parameter allow_arbitrary=True, i.e., **view_control.convert_from_pinhole_camera_parameters(cam_params, _allow_arbitrary=True_)**

Thank you, this is the best solution!
