### ISSUE TITLE
Read/Write pcds in XYZI format

### ISSUE THREAD

**Issue by michael-yang2** [isl-org/Open3D#1166]
Currently, there's no way to read and write pcd files with format [x, y, z, i]. It would be nice to be able to do this in Open3D, instead of having to use a different library.

**Comment by syncle** [comment]
Could you put [x,y,z,i] example file here?

**Comment by jonra1993** [comment]
Hello @syncle I found a bug after cropping pointcloud it can not write pcd file. I Attached example code. It opens original_pcd and after choosing 4 points it crops it and it try to write result pointcloud into pcd file (cloud_crop.pcd) with not success.


[code.zip](https://github.com/intel-isl/Open3D/files/4339825/code.zip)

**Comment by germanros1987** [comment]
We haven't forgotten about this feature request. It will happen.

**Comment by cattaneod** [comment]
Any news on this?

**Comment by xyaoab** [comment]
Updates?

**Comment by Zanderzt** [comment]
How to read a [x y z i] format .pcd file?

**Comment by reyanshsolis** [comment]
`XYZI` format is now supported in our `Tensor` based pipeline. [`open3d.t.io.read_point_cloud("test_file.xyzi")`]
PCD and PLY formats support in `Tensor` based pipeline now allows for custom data attributes including `intensity`. 
Refer examples in our cpp unit tests at: `Open3d > cpp > tests > t > io > PointCloudIO.cpp`. 

Follow up if any further assistance is required. 
Thanks!
