### ISSUE TITLE
registration_icp report the number of iterations in the result set?

### ISSUE THREAD

**Issue by apiszcz** [isl-org/Open3D#1257]
How can one acquire the number of iterations required for the solution of registration.registration_icp ?
If it iterations_required is not available perhaps it can be added.

Another question for the same attribute from
https://stackoverflow.com/questions/55673035/how-to-get-number-of-spent-iterations-from-icp-registration-method-of-open3d-lib

Is it possible to suppress the following message 
"Access transformation to get result."

Thank you

**Comment by germanros1987** [comment]
@theNded is there a way to access this information?

**Comment by reyanshsolis** [comment]
Yes, now there is. 
Added a PR that includes this feature: #4271.
This also includes the tutorial documentation for tensor-based icp, including how to save and use the `loss_log`. 

Thanks!
