### ISSUE TITLE
Deterministic behavior for Registration

### ISSUE THREAD

**Issue by VinceDT** [isl-org/Open3D#1263]
Hey,

I am using registration_fast_based_on_feature_matching and registration_ransac_based_on_feature_matching (Python Binding) and would like to have deterministic behavior, by for instance passing / setting the seed. Is there an easy way to achieve this?

This question is related with https://github.com/intel-isl/Open3D/issues/288

Thanks for the great work!

Vince

**Comment by germanros1987** [comment]
@theNded do you know any way to achieve this?

**Comment by theNded** [comment]
It will be good to add an open3d set seed function in a separate PR. I will put it in the todo list.

**Comment by agporto** [comment]
I just wanted to say that this is a feature that would be appreciated by others in the community as well (I mean the 'set seed' function).

**Comment by theNded** [comment]
@yxlao @ssheorey we need to prioritize this functionality, random algorithms will be prevalent in the next phase.

**Comment by RMeli** [comment]
> It will be good to add an open3d set seed function [...]

I second this. Having a deterministic behavior would be extremely helpful for testing, debugging and comparison with other software.

**Comment by theNded** [comment]
Should have been addressed in #3737.
