### ISSUE TITLE
Cygwin 64 build broken, with fix

### ISSUE THREAD

**Issue by mattj23** [isl-org/Open3D#1300]
Environment:
* OS: Windows 10 Pro, 64 Bit
* Cygwin: 3.0.7(0.338/5/3)
* Compiler: c++ (GCC) 7.4.0
* CMake: cmake version 3.14.5
* Open3D Commit: e6568ea3 

When compiling on Windows 10 using Cygwin, a number of errors come up preventing a successful build. They fall under the following three categores:

1. Use of the `M_PI` constant in several places
1. Use of `strdup` in the pybind11 dependency
1. Files becoming too large for the linker

They can be resolved by changing some compiler flags at line 155 in CMakeLists.txt

```
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_GNU_SOURCE -std=gnu++0x -Wa,-mbig-obj")
```

In context:

```
elseif (CYGWIN)
    SET(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)
    message(STATUS "Compiling on Cygwin")
    # enable c++11
    # set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11") REPLACE WITH LINE BELOW
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_GNU_SOURCE -std=gnu++0x -Wa,-mbig-obj")
    add_definitions(-DCYGWIN)

```

I'm happy to create a pull request, I just don't know if this has any unintended consequences for anyone else.

**Comment by syncle** [comment]
@mattj23 Please submit. We will be happy to review it.

**Comment by germanros1987** [comment]
@mattj23 are you still interested in this?

**Comment by mattj23** [comment]
I apologize for missing these messages.  I ended up going in a different direction and compiling under visual studio.  If it would still be helpful I can reinstall cygwin and try to recreate and fix the bug, but I'm no C++ expert.
