### ISSUE TITLE
Support of floating point precision in ply write

### ISSUE THREAD

**Issue by cosama** [isl-org/Open3D#1325]
Some point clouds can be quite large, by storing them with floating point precision it would be possible to reduce the file size to half without losing much relevant information. Many other tools, such as `pcl` also simply can not read a point-cloud stored in `double` precision and use `float` by default.

There is a `compressed` flag included in the `WritePointCloudToPLY` method (see https://github.com/intel-isl/Open3D/blob/master/src/Open3D/IO/FileFormat/FilePLY.cpp) which seems to do nothing at this point. It would be easy to leverage this flag to instead store the point cloud as `float`. The changes required to add this would be minimal.

**Comment by griegler** [comment]
Thanks for the feature request. I agree, that this would be a very useful option. We are right now rewriting the backend of the geometry classes such that those will also support different data types for their members. Once this is finished, we can have a look at this.

**Comment by ozgucbertug** [comment]
Are there any immediate solutions to this problem?

**Comment by lakshmipathyarjun6** [comment]
For a quick and dirty workaround I just re-exported written point cloud in Meshlab - slightly inconvenient, but does the job

**Comment by tatsy** [comment]
How about using [`plyfile`](https://pypi.org/project/plyfile/) just to write point cloud, while the point cloud processing is performed by Open3D?

**Comment by cosama** [comment]
@ozgucbertug Yeah I agree with @tatsy. `plyfile` is a very good solution. We did some benchmarking a while back and it outperformed open3ds solution by about a factor of 3.

@griegler Was the rewrite of the backend of geometry class completed? I guess using plyfile in open3d is not an option because of the C++ api?

**Comment by ozgucbertug** [comment]
Thank you! I'll make sure to give it a try.

**Comment by wangjksjtu** [comment]
Any updates for this? Writing pcd and mesh in ply using `float` is an important feature. Currently, I am considering the Draco to compress the pcd/mesh saved by open3d, but current `double` precision is not supported.

**Comment by ssheorey** [comment]
Writing ply files with arbitrary data types is supported in the tensor based point cloud IO:
http://www.open3d.org/docs/latest/python_api/open3d.t.io.write_point_cloud.html#open3d.t.io.write_point_cloud

Please test and let us know if this works for you.

**Comment by TheExDeus** [comment]
How could this be done in c++ api? If there isn't an option like this, then the issue shouldn't be closed.

**Comment by andreabonvini** [comment]
If anyone is interested in a temporary working solution you can use [meshio](https://github.com/nschloe/meshio):

```
import meshio
import numpy as np

mesh_path = "path/to/mesh/exported/by/open3d.ply"  # double
mesh = meshio.read(mesh_path)
mesh.points = mesh.points.astype(np.float32)
mesh.write("mesh-float.ply")
```
