### ISSUE TITLE
j_visualizer.py

### ISSUE THREAD

**Issue by zhxd050946** [isl-org/Open3D#1348]
**Describe the bug**
J_visualizer.py, line 37, in geometry_to_json  if isinstance(geometry, o3.PointCloud)   should be 
if isinstance(geometry, o3.geometry.PointCloud)

**To Reproduce**
1. cd '...'
2. python 'import numpy as np
import open3d as o3
from open3d import JVisualizer

pts_path = "D:/MyVSProject/Open3D-master/examples/TestData/fragmment.ply"
fragment = o3.io.read_point_cloud(pts_path)
visualizer = JVisualizer()
visualizer.add_geometry(fragment)
visualizer.show()'
3. AttributeError: module 'open3d' has no attribute 'PointCloud'

**Environment (please complete the following information):**
 - Windows 7.0
 - Python 3.7:
 - Open3D 0.8.0.0:
 - Is this remote workstation?:  no
 - How did you install Open3D?: pip

**Comment by syncle** [comment]
I am not sure whether this issue still persists. @yxlao could you have a look?

**Comment by AND2797** [comment]
It is still there.

**Comment by yxlao** [comment]
@AND2797 @zhxd050946 Jupyter support has been upgraded to WebRTC-based. See: http://www.open3d.org/docs/latest/tutorial/visualization/web_visualizer.html
