### ISSUE TITLE
Error importing open3d on ubuntu 18.04 (amd64)

### ISSUE THREAD

**Issue by ParikaGoel** [isl-org/Open3D#1350]
**Describe the bug**
I am building the open3d from source on my ubuntu 18.04 (amd64) system. It compiles and builds successfully. 
Installing C++ library using below commands also runs successfully :
cd build
make install

But when I install python package using "make install-pip-package", it does not work. 
In the end, it gives the info "open3d-0.8.0.0-cp36-cp36m-linux_x86_64.whl is not a supported wheel on this platform". 
Below I have attached screenshot of the output.

**Screenshots**
![image](https://user-images.githubusercontent.com/35452780/69563729-eee78600-0fb1-11ea-9793-e29507718b68.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04 (amd64)
 - Python version: Python 3.6.8
 - Open3D version: Compiling from source (master branch)
 - Is this remote workstation?: no
 - How did you install Open3D?: build_from_source (steps as mentioned at http://www.open3d.org/docs/release/compilation.html)

**Comment by camile666** [comment]
Hi,I face the same problem, I tried install python package through " sudo make python-package" since I used the system’s default Python, and I add " -DPYTHON_EXECUTABLE=/usr/bin/python ..". I wonder if you have fix this ,thx.

**Comment by EmilyJrxx** [comment]
@ParikaGoel Hi! I have run into the same problem recently, the error messages is as below.

> `adding 'open3d-0.10.1.0.data/purelib/open3d/resources/park_skybox.ktx'
> adding 'open3d-0.10.1.0.data/purelib/open3d/resources/pillars_ibl.ktx'
> adding 'open3d-0.10.1.0.data/purelib/open3d/resources/pillars_skybox.ktx'
> adding 'open3d-0.10.1.0.data/purelib/open3d/resources/pointcloud.filamat'
> adding 'open3d-0.10.1.0.data/purelib/open3d/resources/streetlamp_ibl.ktx'
> adding 'open3d-0.10.1.0.data/purelib/open3d/resources/streetlamp_skybox.ktx'
> adding 'open3d-0.10.1.0.data/purelib/open3d/resources/ubermaterial.filamat'
> adding 'open3d-0.10.1.0.data/purelib/open3d/resources/ui_blit.filamat'
> adding 'open3d-0.10.1.0.data/purelib/open3d/visualization/__init__.py'
> adding 'open3d-0.10.1.0.data/purelib/open3d/visualization/gui/__init__.py'
> adding 'open3d-0.10.1.0.dist-info/LICENSE.txt'
> adding 'open3d-0.10.1.0.dist-info/METADATA'
> adding 'open3d-0.10.1.0.dist-info/WHEEL'
> adding 'open3d-0.10.1.0.dist-info/top_level.txt'
> adding 'open3d-0.10.1.0.dist-info/RECORD'
> removing build/bdist.linux-x86_64/wheel
> pip wheel created at /home/emilyjr/Packages/Open3D/build/lib/python_package/pip_package
> [100%] Built target pip-package
> WARNING: The directory '/home/emilyjr/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> ERROR: open3d-0.10.1.0-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform.
> [100%] Built target install-pip-package`


At first i was wondering if it's about naming rules of pip, that this .whl has a illegal name so it could not be processed by pip, but i didn't make further attempts about that. Then I managed to solve this problem by manually installing `open3d-0.10.1.0-cp37-cp37m-linux_x86_64.whl` with `pip install ./lib/python_package/pip_package/open3d-0.10.1.0-cp37-cp37m-linux_x86_64.whl`. It succeeded and I could import open3d in python shell.

> 
> Successfully built tornado pandocfilters pyrsistent
> Installing collected packages: ptyprocess, pexpect, pygments, backcall, decorator, wcwidth, prompt-toolkit, six, ipython-genutils, traitlets, parso, jedi, pickleshare, ipython, zipp, importlib-metadata, attrs, pyrsistent, jsonschema, jupyter-core, nbformat, pyzmq, python-dateutil, tornado, jupyter-client, ipykernel, MarkupSafe, jinja2, webencodings, pyparsing, packaging, bleach, mistune, entrypoints, testpath, defusedxml, pandocfilters, nbconvert, Send2Trash, terminado, prometheus-client, notebook, widgetsnbextension, ipywidgets, pillow, cycler, kiwisolver, matplotlib, open3d
> Successfully installed MarkupSafe-1.1.1 Send2Trash-1.5.0 attrs-19.3.0 backcall-0.2.0 bleach-3.1.5 cycler-0.10.0 decorator-4.4.2 defusedxml-0.6.0 entrypoints-0.3 importlib-metadata-1.7.0 ipykernel-5.3.4 ipython-7.16.1 ipython-genutils-0.2.0 ipywidgets-7.5.1 jedi-0.17.2 jinja2-2.11.2 jsonschema-3.2.0 jupyter-client-6.1.6 jupyter-core-4.6.3 kiwisolver-1.2.0 matplotlib-3.3.0 mistune-0.8.4 nbconvert-5.6.1 nbformat-5.0.7 notebook-6.0.3 open3d-0.10.1.0 packaging-20.4 pandocfilters-1.4.2 parso-0.7.1 pexpect-4.8.0 pickleshare-0.7.5 pillow-7.2.0 prometheus-client-0.8.0 prompt-toolkit-3.0.5 ptyprocess-0.6.0 pygments-2.6.1 pyparsing-2.4.7 pyrsistent-0.16.0 python-dateutil-2.8.1 pyzmq-19.0.1 six-1.15.0 terminado-0.8.3 testpath-0.4.4 tornado-6.0.4 traitlets-4.3.3 wcwidth-0.2.5 webencodings-0.5.1 widgetsnbextension-3.5.1 zipp-3.1.0 

Before doing this I once tried running `pip install open3d-0.10.1.0-cp37-cp37m-linux_x86_64.whl` and it failed of course, giving the same error message 

> ERROR: open3d-0.10.1.0-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform.

So I'm wondering if this is a naming bug in the `make pip-install-packages` scripts, making pip try to install `open3d-0.10.1.0-cp37-cp37m-linux_x86_64.whl` from internet instead of installing the pre-built wheel.

Hoping it helps.

**Comment by ssheorey** [comment]
Closing this since user reported success. Please open a new issue if you have this problem with the latest (master / v0.13+) version of Open3D.

**Comment by FPSychotic** [comment]
```
adding 'open3d-0.15.1+fbf549b23.dist-info/WHEEL'
adding 'open3d-0.15.1+fbf549b23.dist-info/entry_points.txt'
adding 'open3d-0.15.1+fbf549b23.dist-info/top_level.txt'
adding 'open3d-0.15.1+fbf549b23.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
pip wheel created at /home/igcs/Open3D/build/lib/python_package/pip_package
[100%] Built target pip-package
WARNING: Skipping open3d as it is not installed.
ERROR: open3d-0.15.1+fbf549b23-cp38-cp38-manylinux_2_31_x86_64.whl is not a supported wheel on this platform.
[100%] Built target install-pip-package
igcs@igcs-Legion-5-15ACH6H:~/Open3D/build$ python3
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import open3d
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'open3d'
>>> 

```
same issue, I could install the cpp version from source with the guide, but when 
# Install the python wheel with pip
make -j install-pip-package
it sends that error , I have CUDA 1.6 installed and compiled properly. the gui can be launched.

**Comment by ssheorey** [comment]
@FPSychotic please update your `pip` to the latest first. Open a new issue if you still have problems.
