### ISSUE TITLE
No rule to make target '3rdparty_install/lib/libturbojpeg.a', needed by 'lib/libOpen3D.so'. 

### ISSUE THREAD

**Issue by hzxie** [isl-org/Open3D#1369]
**Describe the bug**
I cannot build the Open3D library following the [document](http://www.open3d.org/docs/release/compilation.html).

**To Reproduce**
1. mkdir build
2. cd build
3. cmake ..

**Screenshots**
![Screenshot from 2019-12-02 20-19-36](https://user-images.githubusercontent.com/1730504/69959016-11911600-1541-11ea-9f39-e2de62c06390.png)

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Python version: 3.8.0
 - Open3D version: 0.8.0
 - Is this remote workstation?: no
 - How did you install Open3D?: build_from_source

**Comment by reyanshsolis** [comment]
may you please try the latest version and let us know if you are still facing the same problem?
Meanwhile, I am closing this issue, as It seems to be working fine on my system and Github CI.

**Comment by journeylee** [comment]
same error here on tag v0.12.0, cause libturbojpeg.a in 3rdparty_install/lib64 folder, link or rename the directory will solve it.
