### ISSUE TITLE
o3d.io.write_point_cloud output too large

### ISSUE THREAD

**Issue by eddienewton** [isl-org/Open3D#1375]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
I'm noticing the o3d.io.write_point_cloud output is about double the size it should be.  I'm comparing this to similar Meshlab binary pointcloud PLY files with XYZ, RGB, and vertex normals.

**To Reproduce**

In python, run:
pcd =  o3d.io.read_point_cloud('input.ply')
o3d.io.write_point_cloud('out.ply', pcd, compressed = True)

For my case, my input pointcloud is 80MB, and the output PLY is 150 MB.  I have confirmed both files are binary, and have the same data.  Changing the flag 'compressed' has no effect.

For comparison, setting 'write_ascii=True' produces a PLY ascii file of size 190MB.

I installed Open3D via pip.  Pip states its version 0.8.0.

**Expected behavior**
Output of o3d.io.write_point_cloud should be compressed further.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. OSX Mojave, Ubuntu 16.04, Windows 10.0]
 - Python version: Python 3.75
 - Open3D version: 0.8.0
 - Is this remote workstation?: NO
 - How did you install Open3D?: pip

**Comment by eddienewton** [comment]
Thinking about it more, I believe Open3D is writing out the PLY binary files as Float64 instead of Float32.  This is occurring on OS X Catalina, which no longer supports 32-bit applications.

**Comment by tsattler** [comment]
I was running into the same issue. I was wondering if there is any interested in a PR that would make the accuracy (float32 vs. float64) a parameter? I might give it a shot if I find time.

**Comment by griegler** [comment]
@tsattler a PR would be great!

**Comment by tsattler** [comment]
@griegler I guess the right way to approach this would be to make this a variable of the function and then also include the option to save as float32 for the other possible file formats? Are data loaders affected by this as well?

**Comment by griegler** [comment]
@tsattler  yes, that seems like a good way. 
For `PointCloud`, there is also `pcd` that is affected. For `TriangleMesh` it could also affect `gltf`, but I am not sure at the moment, if we support binary for that format at all.
However, this discussion surfaces a different issue with the current API. We have some global parameters that are not applicable for all formats.

**Comment by tsattler** [comment]
@griegler Thanks for the quick answer. I will try to have a look at it as soon as possible, but it might take some time until I get there. Will open a PR then.

**Comment by griegler** [comment]
@tsattler Thanks, looking forward to it!

**Comment by wilsonmichaelc** [comment]
Since this does not appear to be resolved yet, I'll add my experience.

I'm reading in a pointcloud from ply file of ~120MB, then using the "crop" feature to remove all but a **very small** number of points and writing the new pointcloud out to a new ply file... its now ~160MB. 

IMHO: probably has little or nothing to do with float32/float64

@tsattler did you get a chance to look into this?

**Comment by reyanshsolis** [comment]
We have added new IO support for tensor-based geometry (`open3d.t.io`), which might resolve these issues.
Please try and let me know if you are still facing the problem.

https://github.com/isl-org/Open3D/pull/3978
https://github.com/isl-org/Open3D/pull/3978

Meanwhile, I am closing this issue, feel free to re-open the same if required. 
Thanks
