### ISSUE TITLE
Can you set the  view control of the visualizer?

### ISSUE THREAD

**Issue by nickponline** [isl-org/Open3D#1389]
I'm trying to set the view control of the visualizer to be a specific pinhole camera. I would like to specify the *intrinsics* and *extrinsics* of the camera and view the scene as if looking through that camera. It appears that the relevant classes are available but the constructors in the docs are unclear.  

```
vis = o3d.visualization.Visualizer()
vis.create_window()
vis.add_geometry(my_pointcloud)

ctr = vis.get_view_control()

# Not sure what to do here ...
parameter = ?
parameter.instintics = ?
parameter.extrinsitcs = ?
ctr.convert_from_pinhole_camera_parameters(parameter)

opt = vis.get_render_option()
opt.background_color = np.asarray([0, 168/255., 1.0])
vis.run()
vis.destroy_window()
```

**Comment by nickponline** [comment]
I made some progress and the extrinsics work but I get the following error after setting the intrinsics:

```
[Open3D WARNING] [ViewControl] ConvertFromPinholeCameraParameters() failed because window height and width do not match.
```

```
# K = 3x3 intrinsics
    # P = 4x4 pose
    ctr = vis.get_view_control()
    init_param = ctr.convert_to_pinhole_camera_parameters()
    w, h = 4000, 3000
    fx = K[0,0]
    fy = K[1,1]
    cx = K[0,2]
    cy = K[1,2]
    init_param.intrinsic.width = w
    init_param.intrinsic.height = h
    init_param.intrinsic.set_intrinsics(init_param.intrinsic.width, init_param.intrinsic.height, fx, fy, cx, cy)
    init_param.extrinsic = P
    ctr.convert_from_pinhole_camera_parameters(init_param)
```

**Comment by prerakmody** [comment]
I believe you may need to do the following

- `vis.create_window(window_name='myname', visible=True, width=cam_intrinsic.width, height=cam_intrinsic.height)`

**Comment by germanros1987** [comment]
Hi! In the Open3D team, we take your question very seriously. In order to provide better assistance to our users, we are implementing new policies. Now general questions should be asked in our forum: https://forum.open3d.org

Github issues will remain in use for bug reports and feature requests.

We are looking forward to answering your question in our forum!

Best regards.
