### ISSUE TITLE
Python API on Windows fails on some functions

### ISSUE THREAD

**Issue by cpocol** [isl-org/Open3D#1395]
Trying to use o3d.geometry.RGBDImage.create_from_color_and_depth() I get the error "module 'open3d.open3d.visualization' has no attribute 'create_from_color_and_depth'". In Linux does work perfectly. How should I use it on Windows?

To Reproduce:
run https://github.com/intel-isl/Open3D/blob/master/examples/Python/Advanced/rgbd_integration.py

Environment: Windows 10, Python 3.6, Open3D 0.8.0 (installed with pip)

**Comment by yogeshhk** [comment]
File missing. Can't reproduce
