### ISSUE TITLE
How to convert the open3d.geometry.VoxelGrid into a NumPy array?

### ISSUE THREAD

**Issue by liminle** [isl-org/Open3D#1418]
Hi everyone,
How to convert the open3d.geometry.VoxelGrid into a NumPy array? 
I have a open3d.geometry.VoxelGrid, and now I wonder is there any way to convert it to a numpy 3d cube containing voxels data.

**Comment by germanros1987** [comment]
Hi! In the Open3D team, we take your question very seriously. In order to provide better assistance to our users, we are implementing new policies. Now general questions should be asked in our forum: https://forum.open3d.org

Github issues will remain in use for bug reports and feature requests.

We are looking forward to answering your question in our forum!

Best regards.

**Comment by bharadwajdhornala** [comment]
Hi @liminle Have you found any way to convert to numpy array?

**Comment by THHHomas** [comment]
@liminle Do you know how to convert open3d voxel to numpy array?

**Comment by Leong1230** [comment]
@germanros1987 
Hi! I think more interpretations and examples of functions in open3d.geometry.VoxelGrid and open3d.geometry.Voxel are supposed, for example, how to convert open3d.geometry.VoxelGrid into a NumPy array, how to get the color given indices.... They make VoxelGrid unfriendly to use.
The forum is not as active as this repo, so could you please give some suggestions to these questions?
Thank you!

**Comment by Txeki** [comment]
Hi! 
Does anyone find a way to do it?

**Comment by Leong1230** [comment]
@Txeki 
Hi, I think there is one way to do so (maybe not the optimal way, but it works):
1. First initalize a zero array with the same shape (get 'shape' by finding the bounds of the voxel)
2. Then enumerate the VoxelGrid object to get each index and corespounding value. Assign the value the the indexed voxel.

**Comment by Txeki** [comment]
@Leong1230 
Thank you for your answer! But what do you refer with the enumerate the VoxelGrid object? I mean, I got a Voxelgrid with nearly 10 thousand voxels and I don't understand your method to assign them to an array.

**Comment by ssheorey** [comment]
You can get the voxel indices and colors as Numpy arrays like this:
```py
voxels = voxel_grid.get_voxels()  # returns list of voxels
indices = np.stack(list(vx.grid_index for vx in voxels))
colors = np.stack(list(vx.color for vx in voxels))
```
To get the color of a point given its coordinates, use this function:

http://www.open3d.org/docs/latest/python_api/open3d.geometry.VoxelGrid.html#open3d.geometry.VoxelGrid.get_voxel

The returned voxel has `grid_index` and `color` fields. If you directly have the voxel index, you will need to convert it to the coordinates of the center of the voxel first.

**Comment by hello-jo** [comment]
But now that I have the voxel index values, how can I output which points are in this voxel?
