### ISSUE TITLE
UniformTSDFVolume and Numpy

### ISSUE THREAD

**Issue by sam598** [isl-org/Open3D#1419]
I need to directly edit the TSDF values of a UniformTSDFVolume in Numpy.

I understand that this is a difficult problem with the ScalableTSDFVolume as it is an unordered map. But my understanding is that the UniformTSDFVolume is an X^3 float array.

If the entire volume is already stored in memory I would assume it would be straightforward to  convert the array to and from Numpy. There should be no need for a sparse representation or an array of index keys.

**Comment by reyanshsolis** [comment]
Added.https://github.com/isl-org/Open3D/pull/3423
