### ISSUE TITLE
Texture mapping multiple geometries does not work after redraw

### ISSUE THREAD

**Issue by bradleynull** [isl-org/Open3D#1424]
**Describe the bug**
I'm using Open3D 0.9 and texture mapping a single triangle mesh seems to be working as expected. However, when I try to render multiple geometries, they appear to use the same texture after the first redraw. 

When applying a new coloring method (e.g. hitting `1`, `2`, `3`, etc.) The textures are reapplied correctly until the next redraw.

**To Reproduce**
The below python code first draws a single mesh and everything works as expected. This is followed by drawing multiple meshes that do not work when redrawn due to mouse/key presses:

```python
import os
import open3d as o3d

meshes = []
tile_dir = "path/to/my/meshes/"
for file in os.listdir(tile_dir):
    if file.endswith(".obj"):
        meshes.append(o3d.io.read_triangle_mesh(os.path.join(tile_dir, file)))
o3d.visualization.draw_geometries([meshes[0]]) # Draws as expected with texture
o3d.visualization.draw_geometries(meshes[0:2]) # Draws fine on first draw, redraws use same texture
```

**Expected behavior**
Each mesh should maintain their appropriate texture while interacting with the visualization.

**Screenshots**
Below is an image of two meshes when they are first loaded without moving anything:

![unknown](https://user-images.githubusercontent.com/6026642/71745368-8650bc00-2e2f-11ea-8ab8-0292e0c81a23.png)

After moving the meshes with the mouse, it appears the left mesh is using the right meshes texture:

![unknown (2)](https://user-images.githubusercontent.com/6026642/71745415-abddc580-2e2f-11ea-8fab-dd2e0ee0ae5d.png)

**Environment (please complete the following information):**
 - OS: Windows 10.0
 - Python version: 3.6
 - Open3D version: 0.9
 - Is this remote workstation?: no
 - How did you install Open3D?: pip 

**Additional context**
Looking through the code in the key callback, it appears that the major difference is a call to `UpdateGeometries()` for the recoloring methods that is not present for the other callbacks (see https://github.com/intel-isl/Open3D/blob/master/src/Open3D/Visualization/Visualizer/VisualizerCallback.cpp#L255). I'm not sure what the implications of calling this function are, but for textured meshes it seems like it would fix the issue.

**Update/Workaround**

I've found a quick and dirty way to get the texture mapping working by forcing a call to the visualizer's `update_geometry()`. This definitely slows the rendering down, but at least it gets the job done for now:

```python
def fix_bug(v):
    v.update_geometry(None)
    return False

o3d.visualization.draw_geometries_with_animation_callback(meshes, fix_bug)
```

**Comment by griegler** [comment]
@theNded @yxlao any idea?

**Comment by germanros1987** [comment]
@bradleynull does this work for you in 0.11, using the new rendering API?

**Comment by bradleynull** [comment]
@germanros1987 It looks like 0.10 fixed the issue. I have not tested with 0.11.

**Comment by sharoseali** [comment]
> @germanros1987 It looks like 0.10 fixed the issue. I have not tested with 0.11.

I have a texture as a png file [(Data here)](https://drive.google.com/file/d/1x-j5vv77B73YYsZ5smWFabvQrFg5ZkSX/view?usp=sharing)   and a corresponding mesh. I didn't find any UV mapping code in open 3D documentation that render mesh with texture. Any help to map png file on a mesh thanks @bradleynull
