### ISSUE TITLE
Removing o3d.utility.VectorXXX o3d.utility.XXXVector

### ISSUE THREAD

**Issue by chrischoy** [isl-org/Open3D#1454]
Currently, to create a point cloud, open3d requires a rather complex logic

```python
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(points)
pcd.colors = o3d.utility.Vector3dVector(colors)
```

This is rather complex and not pythonic. This requires modifying attributes of an instance directly. Rather, it would be nice to have a function like

```python
points, colors = np.random.rand(N, 3), np.random.rand(N, 3)
pcd = o3d.geometry.PointCloud(points, colors)
```

The dimension checks or assertions could be done inside the cpp file to prevent invalid arrays.

The eigen natively supports converting a numpy array into an eigen through pybind11 so if you are using Eigen, then this can be done nicely without converting a numpy array into an eigen matrix. For example, https://github.com/chrischoy/PybindNumpyExample/blob/master/code.cpp#L48, `Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor>` automatically forwards a numpy array.

Similarly, when generating a point cloud, it requires another layer of complexity.

```python
rec_mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_ball_pivoting(
            pcd, o3d.utility.DoubleVector([1, 2]))
```

o3d.utility.DoubleVector is simply wrapping a list, which is natively forwarded with pybind11 as `std::vector`, this could have been.

```python
rec_mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_ball_pivoting(
            pcd, [1, 2])
```

I think it's quite tedious and even unnecessary as there’s no need to convert a list to an Eigen vector and to an std vector. It is automatically converted to std vector natively. Also, it requires looking up the documentation everytime I use the function, and quite unintuitive when I first got to use open3d.

**Comment by syncle** [comment]
I think this request is being addressed in ``ml-module`` branch. @yxlao could you confirm and share the status?

**Comment by theNded** [comment]
It is now supported with the new [Tensor API](http://www.open3d.org/docs/latest/python_api/open3d.t.geometry.PointCloud.html).
