### ISSUE TITLE
Poisson reconstruction

### ISSUE THREAD

**Issue by mashalahmad** [isl-org/Open3D#1522]
Hi

Im trying to use the open3d for scene reconstruction with poisson reconstruction. the paramter I set are this
mesh, densities = o3d.geometry.TriangleMesh.create_from_point_cloud_poisson(downpcd, depth=10, width=0, scale=1.5, linear_fit=True)
My pointcloud was very large so I downsample it before the poisson recon like this
downpcd.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.012824, max_nn=50))
Im uploading the mesh as well. Could you please tell how can I improve this?
![mesh_open3d](https://user-images.githubusercontent.com/31829812/74727520-312f0500-5239-11ea-9c16-dcb12dcee987.png)

**Comment by syncle** [comment]
I think the downsampling procedure was too harsh and not even for the point sets. As a result, 10 levels of Poisson Recon would not help since the input point cloud was very sparse. Consider voxel downsampling to uniformly downsample and preserve the structures.

**Comment by mashalahmad** [comment]
thanks for the reply. I applied the downsampling becuase the pointcloud was very large. even I skipped the downsampling or set the voxel size very small let say 0.01 I got the same result. Im attaching the images with no down sampling or small size voxel.
![without-smpling](https://user-images.githubusercontent.com/31829812/74827585-94866900-5305-11ea-836e-0b9dcc94702a.png)

Im not sure how to make a uniform downsample or to improve it. Its basically a scan of bridge. I was using the cloudcompare too and in that we got an option of setting the boundary as free , neumann and Dirichlet. I saw that open3d is actually getting the poisson recon from third party so I dnt know if there is any such option or not

**Comment by germanros1987** [comment]
@griegler do you have any ideas?

**Comment by mashalahmad** [comment]
well I inspect the source code of open3d poisson recon file and found that the default paramters are similar to cloud compare
here is link of file
https://github.com/intel-isl/Open3D-PoissonRecon/blob/fd273ea8c77a36973d6565a495c9969ccfb12d3b/Src/PoissonRecon.cpp

and these are parameters that I compare
sample per node 1.5
full depth 5
point weight 2
Boundary Neuman
the only difference I found is point weight. which is 4 in cloudcompare so I change it to 2 in cloud compre but still the mesh created through cloud compare is much better.

**Comment by griegler** [comment]
@mashalahmad Are you removing vertices with low density values? See this [example](https://github.com/intel-isl/Open3D/blob/master/examples/Python/Advanced/surface_reconstruction_poisson.py#L43) from line 43 onwards. Also, how did you derive the normals of your point cloud?

**Comment by mashalahmad** [comment]
no Im not removing any vertices and I computed the normals like this
pcd.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.0123, max_nn=30))

I change the value of radius as well and try to see the difference but its more or less the same

**Comment by griegler** [comment]
Ok, removing low density vertices will definitely help in the areas where the reconstruction is extrapolating and where little to no points are.

Further, the normals might be another problem. `estimate_normals` does not orient the normals. That means, neighboring normals might point into the opposite direction, which is problematic for Poisson surface reconstruction. I think @syncle is working on a method to orient the normals.

**Comment by mashalahmad** [comment]
ok so it means I had to wait. I see in cloud compare the options are with the minimum spanning tree or orientation in preferred axis(z,x,y). are you implementing something similar too?
and how can I remove the low density vertices?

**Comment by griegler** [comment]
@mashalahmad that is exactly what is planned. Maybe @syncle already has some more information on that.

```python
vertices_to_remove = densities < np.quantile(densities, 0.1)
mesh.remove_vertices_by_mask(vertices_to_remove)
```
where you have to adapt the threshold in the first line to fit your needs.

**Comment by mashalahmad** [comment]
ok great and thanks alot for the quick responses. waiting anxiously :dancer:

**Comment by mashalahmad** [comment]
Ok I found it that problem is actually the normal orientation. I ran the test in cloudcompare by computing the normals with no orientation (I did previously through the spanning tree) and resulting mesh was exactly like the open3d one.

**Comment by mashalahmad** [comment]
on open3d documentation I found this 

estimate_normals(self, search_param=geometry::KDTreeSearchParamKNN with knn = 30, fast_normal_computation=True)
Function to compute the normals of a point cloud. Normals are oriented with respect to the input point cloud if normals exist

it clearly says that normals are oriented :( why is that

**Comment by griegler** [comment]
What the doc is saying (not in a clear way): If the point cloud already has normals and `EstimateNormals` is called, then the normals are oriented according to the already existent normals.

**Comment by mashalahmad** [comment]
I tried running the surface reconstruction by importing a point cloud with normals but in this case I got the error

RuntimeError: [Open3D ERROR] [CreateFromPointCloudPoisson] pcd has no normals

I even tried with estimate_normals but getting the same error.

**Comment by syncle** [comment]
Umm, that's weird. Please double-check if your point cloud has the valid normals.

**Comment by mashalahmad** [comment]
Here is some sample of data points

```
//X Y Z Scalar_field Rf Gf Bf Nx Ny Nz
83734413
509697.39659882 590961.39780045 113.99569702 -1583.000000 0.176471 0.176471 0.0509804 0.371561 -0.853503 0.365343
509697.39040375 590961.41780090 114.14150238 -1599.000000 0.121569 0.137255 0.0784314 0.722159 0.598267 0.347223
509697.36380005 590961.45000076 114.14160156 -1503.000000 0.156863 0.192157 0.0705882 0.722159 0.598267 0.347223
```

I computed the normals with another software

**Comment by griegler** [comment]
@mashalahmad What is the file format and can you provide a code snippet that you used to load the point cloud?

**Comment by mashalahmad** [comment]
Actually my point cloud format is .pts and it have no normals with it so I computed the normal and then reconstruct the surface with Poisson but it didn't came very well here is the snippet 
```
pcd = o3d.io.read_point_cloud("/..//03_BeheenaghBridge_Kerry/KYN_N72_009_Beheenagh_PTS.pts")
print("Downsample the point cloud with a voxel of 0.03")

downpcd = pcd.voxel_down_sample(voxel_size=0.03)
downpcd.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.0104,max_nn=12))
print('run Poisson surface reconstruction')
mesh, densities = o3d.geometry.TriangleMesh.create_from_point_cloud_poisson(downpcd, depth=10, width=0, scale=1.1, linear_fit=True)
o3d.visualization.draw_geometries([mesh])
```

So I computed the normals fro a software and I provided the sample above and try to import it like the this and then compute the normals because one of you pointed out that if a pointcloud already have normals then it try to orient it with already computed normals. (I know there is a function that we can you to orient the normlas along camera or some direction like this o3d.open3d.geometry.PointCloud.orient_normals_towards_camera_location(downpcd, np.array([0., 0., 0.])))
pcd = o3d.io.read_point_cloud(".../03_BeheenaghBridge_Kerry/cloudcompare-work/experiment/experiment.pts")
pcd.estimate_normals()
print(pcd)

**Comment by griegler** [comment]
@mashalahmad If you import the point cloud that already has normals (from another software), why the need to re-compute? As sanity check, have you verified the normals from the point cloud? E.g., you could visualize them with open3d.

**Comment by germanros1987** [comment]
Hi! In the Open3D team, we take your question very seriously. In order to provide better assistance to our users, we are implementing new policies. Now general questions should be asked in our forum: https://forum.open3d.org

Github issues will remain in use for bug reports and feature requests.

We are looking forward to answering your question in our forum!

Best regards.

**Comment by szx0112** [comment]
I can confirm the similar issue when uses Poisson surface reconstruction. It seems the estimate_normals function provide different normal orientation compared to the orientation computed by other software (e.g. CloudCompare).

**Comment by germanros1987** [comment]
Issue closed due to lack of activity. Feel free to open a new issue if you still consider this is a critical matter.
