### ISSUE TITLE
using Open3D with RGB images and depth calculated by MVS

### ISSUE THREAD

**Issue by elliestath** [isl-org/Open3D#1523]
I am trying to use my RGB+depth images that I already have generated using MVS procedures and not a depth sensor. I have converted the depth to 16 bit and to me it looks correct as values. However, the reconstruction using Open3D is erroneous, reconstructing the object in parts of different depth ![Screenshot from 2020-02-18 14-23-00](https://user-images.githubusercontent.com/11046400/74739985-46685b80-525a-11ea-88a9-62084768841e.png). 
Please see also an example RGB image and a depth map.
![Screenshot from 2020-02-18 14-25-09](https://user-images.githubusercontent.com/11046400/74740170-a959f280-525a-11ea-875e-585ce3e36311.png)
![Screenshot from 2020-02-18 14-25-48](https://user-images.githubusercontent.com/11046400/74740181-aeb73d00-525a-11ea-8269-ffd92f143233.png)

Could you provide me some standards on how the depth maps should be? Looking on the benchmark datasets that you use in the documentation didn't help.

**Comment by syncle** [comment]
Does the depth map is a disparity map? It looks like a highly quantized disparity map. [If so, consider transforming disparity map to depth map.](https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_calib3d/py_depthmap/py_depthmap.html#depth-map-from-stereo-images) and save the metric depth into 16bit png image.

**Comment by elliestath** [comment]
I generated these maps using OpenMVS, so I supposed they are depth maps. Then, I inverted the colors so that black is the closest and then transform it to 16 bit using ImageMagik.

**Comment by elliestath** [comment]
any news on that issue? could it the problem be that my model is not scaled to real world? how should an adequate depth map be structured?

**Comment by syncle** [comment]
It seems that you would need to know the correct camera intrinsics.

**Comment by elliestath** [comment]
I have inserted the correct intrinsics in the .json file, if this is what you mean.
I have all info for camera geometry, internal and external.

**Comment by syncle** [comment]
Pick the depth values and check that values are valid. Another reason I think is quantization. The depth images were weirdly quantized for some reason (maybe during saving and loading images?)

**Comment by germanros1987** [comment]
Hi! In the Open3D team, we take your question very seriously. In order to provide better assistance to our users, we are implementing new policies. Now general questions should be asked in our forum: https://forum.open3d.org

Github issues will remain in use for bug reports and feature requests.

We are looking forward to answering your question in our forum!

Best regards.
