### ISSUE TITLE
SLAM visualizations similar to Pangolin

### ISSUE THREAD

**Issue by tfy14esa** [isl-org/Open3D#1524]
This issue is similar to issue[ #220](https://github.com/intel-isl/Open3D/issues/220), but this post asks more concretely about the visualization tools of Open3D, rather than performance.

**Is your feature request related to a problem? Please describe.**
I would like a streamlined platform in python where one can develop a slam gui similar to e.g. the one used by [LSD SLAM](https://www.youtube.com/watch?v=GnuQzP3gty4) and [DSO](https://www.youtube.com/watch?v=C6-xwSOOdqQ&t=55s). These systems are traditionally based on C++ code written with Pangolin as the viewer. I know that pangolin has python bindings, but the documentation of pangolin for python is not very good.

**Describe the solution you'd like**
The solution would look similar to DSO - Direct Sparse Odometry. Here is a screenshot
![Screenshot from 2020-02-18 17-44-28](https://user-images.githubusercontent.com/33764884/74757525-6574e680-5276-11ea-8097-5f690bb0188f.png)

Via the interface, you can change parameters at runtime e.g. change whether you want to e.g. visualize the rgb stream, sparse depth, the camera pose and trajectory etc.

**Describe alternatives you've considered**
I have considered taking the code from [DSO - Direct Sparse Odometry](https://github.com/JakobEngel/dso) and adapt it to my own needs. This is, however, done purely in C++ and I would like to have a system that can be coupled at runtime to a deep learning framework like pytorch.

**Additional context**
With the current state of Open3D, is it possible to build a visualizer of this kind, given the proper input and output streams?

**Comment by germanros1987** [comment]
Hi @tfy14esa. We are currently working on a new GUI API that will allow users to create ad hoc user interfaces on top of Open3D, including visualization and rendering. I think that could be a good starting point to create the SLAM viewer.

**Comment by tfy14esa** [comment]
Thank you for your response @germanros1987. Currently, there is not a direct way to construct such a visualizer then so would you suggest I use e.g. Pangolin as my starting point for now?

In that case, I look forward to when it is finished! Good luck! :)

**Comment by syncle** [comment]
FYI, there is an [active branch for the new GUI support](https://github.com/intel-isl/Open3D/tree/gui). Check it out if you want to try early.

**Comment by tfy14esa** [comment]
Thanks a lot @syncle. I look forward to when this is finished.

**Comment by germanros1987** [comment]
Probably right now is a good time to have a look at what we did for 0.10. There are new GUI classes that should give you the tools that you need to make such a UI.
