### ISSUE TITLE
Compile issue in debug in visual studio 2019

### ISSUE THREAD

**Issue by ShiwenH** [isl-org/Open3D#1544]
Hi I directly succeeded to compile release version in visual studio in 2019 but when I tried to compile debug version, the compiler showed that /bigobj was needed in compiline Geometry module.

**Comment by syncle** [comment]
Could you provide more detail so that we can get more information?

**Comment by ShiwenH** [comment]
![Capture](https://user-images.githubusercontent.com/15124336/75621941-c0430200-5bd5-11ea-8c7c-974f5531196f.PNG)
![Capture1](https://user-images.githubusercontent.com/15124336/75621942-c20cc580-5bd5-11ea-8f89-beb5e5535ed1.PNG)

This 1st pic shows the issue and the 2nd pic shows the solution.
It seems that there is a limit in compiled obj file size.
In release mode, the obj is small but in debug mode, the obj exceeds the limit.
The tag /bigobj allow a higher obj size.

**Comment by syncle** [comment]
@ShiwenH Thanks for sharing your solution. @griegler could you comment on why PoissionRecon makes a large obj file?

**Comment by ssheorey** [comment]
Hi @ShiwenH do you still have this issue with the latest release? We don't see this issue in our CI pipelines when compiling in DEBUG mode. If you do, please share the `cmake` options used for compilation.
