### ISSUE TITLE
Support reading and writing file-like objects

### ISSUE THREAD

**Issue by chrisranderson** [isl-org/Open3D#1560]
**Is your feature request related to a problem? Please describe.**
I would like to write .ply bytes to a file-like object without a filename. I can't do that with the current API. I'm trying to avoid using the disk when unnecessary - my particular use case is sending a ply file over HTTP.

**Describe the solution you'd like**
Adjusting the API to work with either filenames or file-like objects, like so:
```python
point_cloud = open3d.geometry.PointCloud()
point_cloud_bytes = io.BytesIO()
open3d.io.write_point_cloud(point_cloud_bytes, point_cloud)
decoded_point_cloud = open3d.io.read_point_cloud(point_cloud_bytes)
# point_cloud and decoded_point_cloud should be identical
```

**Describe alternatives you've considered**
I tried `tempfile.NamedTemporaryFile`, but was unable to get it to work. I also could write it to disk and read the bytes directly, but I'd prefer to keep things in memory.

**Additional context**
None.

**Comment by syncle** [comment]
@chrisranderson Thanks for the suggestion. We are currently working for the next roadmap and not enough to have the bandwidth for this. It would be great if you are willing to contribute to add such a feature. :)

**Comment by johnthagen** [comment]
`tempfile.NamedTemporaryFile` works, but it would be much more efficient to be able to keep operations like this fully in memory.

**Comment by johnthagen** [comment]
As a reference, Pillow has a nice API for this:

- https://github.com/python-pillow/Pillow/blob/46ba6b51de0ed81edbcf2bbf507ff2eb9ee349f5/src/PIL/Image.py#L2183


```py
    def save(self, fp, format=None, **params):
        """
        ...
        :param fp: A filename (string), pathlib.Path object or file object.
        ...
        """

        filename = ""
        open_fp = False
        if isinstance(fp, Path):
            filename = str(fp)
            open_fp = True
        elif is_path(fp):
            filename = fp
            open_fp = True
        elif fp == sys.stdout:
            try:
                fp = sys.stdout.buffer
            except AttributeError:
                pass
        if not filename and hasattr(fp, "name") and is_path(fp.name):
            # only set the name for metadata purposes
            filename = fp.name

        ...
        created = False
        if open_fp:
            created = not os.path.exists(filename)
            if params.get("append", False):
                # Open also for reading ("+"), because TIFF save_all
                # writer needs to go back and edit the written data.
                fp = builtins.open(filename, "r+b")
            else:
                fp = builtins.open(filename, "w+b")

        try:
            save_handler(self, fp, filename)
        except Exception:
            if open_fp:
                fp.close()
            if created:
                try:
                    os.remove(filename)
                except PermissionError:
                    pass
            raise
        if open_fp:
            fp.close()
```

**Comment by johnthagen** [comment]
I was going to take a look at trying to implement this, but I see that these functions are implemented in C++ from best I can tell

https://github.com/isl-org/Open3D/blob/0b3098c254b59ff27534f5ea3d4ba9feeeb2a8ba/cpp/pybind/t/io/class_io.cpp#L134-L140

For our use case, we'd really like both `open3d.io.read_point_cloud` and `open3d.io.write_point_cloud` to support file-like paramaters such as an open file or `BytesIO`.

**Comment by johnthagen** [comment]
@yxlao Since it's been a couple years, is this feature still something the Open3D team is supportive of? It would help in the case of server-based / headless processing of data through APIs where the data is already in memory.

**Comment by pjoneja** [comment]
I agree a BytesIO interface would be better! But in the absence of that, if anyone needs help with NamedTemporaryFile, here's how to do it:

```python
pcd = open3d.geometry.PointCloud()
pcd.points = open3d.utility.Vector3dVector(xyz)
with NamedTemporaryFile(mode="w+b", suffix=".pcd") as f:
    open3d.io.write_point_cloud(f.name, pcd)
    f.seek(0)
    pcd_bytes = f.read()
```
