### ISSUE TITLE
Group identically colored vertices in connected components.

### ISSUE THREAD

**Issue by sunilkumargit** [isl-org/Open3D#1568]
Making a list of identically colored vertices in a connected components. If made this list, display application can show the vertices for a color selected by user.

Find the connected components. Find all colors used in the object. Group vertices in each connected component to group for it's color.

**Describe alternatives you've considered**
-None.

**Additional context**
When the object is displayed, the display application can list all colors used, so that if user selects a color, those vertices with that color could be highlighted.

Tested Implementation (not documented):
Usage:
mesh->Identically_colored_vertices_connected_sorted();

TriangleMesh.cpp
---------------------------
/// Function object with an operator
/// To collect all neighbors in all triangles, supplied as parameter, for a
/// given vertex_index
Collect_connected_vertices::Collect_connected_vertices(int _vertex_index)
    : vertex_index_(_vertex_index) {}
void Collect_connected_vertices::operator()(
        const Eigen::Vector3i &triangle_vertex_indices) {
    int nbr_1_vertex_index = -1;
    int nbr_2_vertex_index = -1;
    /// Check if the vertex, with which initialized, is a member of
    /// triangle_vertex_indices
    ///  means, vertex of this triangle
    auto is_vertex =
            TriangleMesh::isAVertex(triangle_vertex_indices, vertex_index_,
                                    nbr_1_vertex_index, nbr_2_vertex_index);
    if (!is_vertex) return;
    connected_vertices.insert(nbr_1_vertex_index);
    connected_vertices.insert(nbr_2_vertex_index);
}
/**
/// process each vertex, not explored yet
/// set the visit status to true, to not to explore again
/// Iterate through all the triangles in the mesh and collect all vertices
reachable
///  from the vertex given as parameter.
/// Recurse
**/
bool TriangleMesh::find_connected_vertices(
        int vertex_index,
        std::vector<bool> &vertex_visit_status,
        std::set<int> &connected_vertices) {
    if (vertex_visit_status[vertex_index] == true)
        return true;                           // explored earlier
    vertex_visit_status[vertex_index] = true;  // explore never again
    connected_vertices.insert(vertex_index);
    auto Next_connected_vertices =
            for_each(triangles_.begin(), triangles_.end(),
                     Collect_connected_vertices(vertex_index));
    for (auto next_vertex : Next_connected_vertices.connected_vertices)
        find_connected_vertices(next_vertex, vertex_visit_status,
                                connected_vertices);
    return true;
}
/**
///
/// Find connected components - driver function
/// std::set, if needed, can be replaced by
/// std::vector + remove duplicates + sort
**/
bool TriangleMesh::Find_connected_components(
        std::vector<bool> &vertex_visit_status,
        std::set<std::set<int>> &connected_components) {
    for (int index = 0; index < vertices_.size(); index++) {
        if (!vertex_visit_status[index]) {
            std::set<int> connected_vertices;
            find_connected_vertices(index, vertex_visit_status,
                                    connected_vertices);
            auto result = connected_components.insert(connected_vertices);
            if (result.second == false)
                throw std::logic_error(
                        "duplication in connected components, Implementation "
                        "of algorithm failed");
        }
    }
    /// Cross check if components are disjoint,
    /// else algorithm implementation failed
    std::set<int> major_set;
    for (auto index_set : connected_components) {
        for (auto index : index_set) {
            if (major_set.insert(index).second == false) {
                {
                    std::ostringstream oss;
                    oss << "connected components are not disjoint, "
                           "Implementation of algorithm failed"
                        << std::endl;
                    utility::LogError(oss.str().c_str());
                    throw std::logic_error(oss.str().c_str());
                }
            }
        }
    }
    return true;
}

/// Driver function to find identically colored sorted connected vertices
/// params : none
///
std::vector<std::vector<std::set<int>>>
TriangleMesh::Identically_colored_vertices_connected_sorted() {
    utility::SetVerbosityLevel(utility::VerbosityLevel::Debug);
    utility::LogDebug(
            "Starting to find identically colored vertices connected and "
            " sorted");
    std::vector<
            /*groups*/ std::vector</* unique color */ std::set<int>>>
            idc_vertices_cs;

    /// connected_components will be populated by sets of connected vertices
    std::set<std::set<int>> connected_components;
    std::vector<bool> vertex_visit_status;
    vertex_visit_status.resize(vertices_.size(),
                               false);  // No vertices explored

    /// Find connected components
    utility::LogDebug(
            "Finding connected components, starting driver function ");
    if (!Find_connected_components(vertex_visit_status, connected_components)) {
        utility::LogError("Find_connected_components failed, returning...");
    }

    /// Check for empty sets inside connected_components, case is rare
    for (auto comp : connected_components) {
        if (comp.empty()) {
            {
                std::ostringstream oss;
                oss << "Empty set in connected components, implementation of "
                       "algorithm failed"
                    << std::endl;
                utility::LogError(oss.str().c_str());
                throw std::logic_error(oss.str().c_str());
            }
        }
    }
    unsigned long long total_index = 0;
    for (auto component : connected_components) {
        for (auto index : component) {
            ++total_index;
        }
    }
    if (total_index != vertices_.size()) {
        {
            std::ostringstream oss;
            oss << vertices_.size() - total_index
                << " : vertices missing in final set of connected components"
                << std::endl;
            utility::LogError(oss.str().c_str());
            throw std::logic_error(oss.str().c_str());
        }
    }

    utility::LogInfo("Number of connected components: {:d} ",
                     connected_components.size());

    /// Sort connected_components in ascending order
    /// sorted_connected_components will store each same component inside
    /// connected_components, but in ascending order of length of components
    std::vector<std::set<int>> sorted_connected_components{
            connected_components.begin(), connected_components.end()};
    utility::LogDebug(
            "Sorting connected components in descending order on length of "
            "components ");
    // length first
    std::sort(sorted_connected_components.begin(),
              sorted_connected_components.end(),
              [](const std::set<int> &comp_1, const std::set<int> &comp_2) {
                  return comp_1.size() > comp_2.size();
              });

    utility::LogDebug("Finding unique colors");
    /// Find unique colors
    std::vector<Eigen::Vector3d> unique_colors;

    /// no sort/ordering can be done on matrices, except test for equality
    /// check if two colors are same
    auto is_same_color = [](const Eigen::Vector3d &col_1,
                            const Eigen::Vector3d &col_2) {
        return (col_1[0] == col_2[0] && col_1[1] == col_2[1] &&
                col_1[2] == col_2[2]);
    };

    for (auto vertex_col : vertex_colors_) {
        bool is_unique = true;
        for (auto col : unique_colors) {
            if (is_same_color(vertex_col, col)) {
                is_unique = false;
                break;
            }
        }
        if (is_unique) unique_colors.push_back(vertex_col);
    }
    utility::LogInfo("Unique colors: ");
    utility::LogInfo("Number of unique colors: {:d} ", unique_colors.size());
    for (auto col : unique_colors) {
        utility::LogDebug("[ {:f}, {:f} ,{:f} ]", col[0], col[1], col[2]);
    }
    /// Each vertex from each component will fall in to one of the
    /// set for a unique color
    utility::LogInfo(
            "Each vertex from each component will fall in to one of the"
            " set for a unique color");

    idc_vertices_cs.resize(sorted_connected_components.size());
    int pos = -1;

    for (auto component : sorted_connected_components) {
        pos++;
        std::vector<std::set<int>> component_paritions;
        component_paritions.resize(unique_colors.size());

        /// Now partition each component in to groups for unique color
        for (auto index : component) {
            bool bInserted = false;
            for (int i = 0; i < unique_colors.size(); i++) {
                if (is_same_color(vertex_colors_[index], unique_colors[i])) {
                    component_paritions[i].insert(index);
                    bInserted = true;
                    break;
                }
            }
            if (!bInserted) {
                {
                    std::ostringstream oss;
                    oss << "Grouping colors failed: " << std::endl;
                    oss << "color of vertex of index: " << index
                        << "did not found in unique colors" << std::endl;

                    utility::LogError(oss.str().c_str());
                    throw std::logic_error(oss.str().c_str());
                }
            }
        }
        utility::LogDebug("Color groups");
        utility::LogDebug("[");
        for (auto col_group : component_paritions) {
            utility::LogDebug(" size{:d}:,", col_group.size());
            utility::LogDebug("[");
            for (auto index : col_group) {
                utility::LogDebug("{:d},", index);
            }
            utility::LogDebug("],");
        }
        utility::LogDebug("]");
        /// Remove empty sets for unique color
        utility::LogDebug("Copying non-empty sets of unique colors to temp");
        std::vector<std::set<int>> temp_paritions;
        std::copy_if(component_paritions.begin(), component_paritions.end(),
                     std::back_inserter(temp_paritions),
                     [](const std::set<int> &color_group) {
                         return !color_group.empty();
                     });
        // idc_vertices_cs[pos].resize(temp_paritions.size());
        std::copy(temp_paritions.begin(), temp_paritions.end(),
                  std::back_inserter(idc_vertices_cs[pos]));
    }

    total_index = 0;
    utility::LogDebug("[");
    for (auto component : idc_vertices_cs) {
        utility::LogDebug("\n[");
        for (auto color_group : component) {
            utility::LogDebug("[");
            for (auto index : color_group) {
                utility::LogDebug("{:d},", index);
                ++total_index;
            }
            utility::LogDebug("],\n");
        }
        utility::LogDebug("],\n");
    }
    utility::LogDebug("]");
    if (total_index != vertices_.size()) {
        if (total_index < vertices_.size()) {
            {
                std::ostringstream oss;
                oss << vertices_.size() - total_index
                    << " vertices missing in"
                       " final set of identically colored connected "
                       "components"
                    << std::endl;
                utility::LogError(oss.str().c_str());
                throw std::logic_error(oss.str().c_str());
            }

        } else if (total_index > vertices_.size()) {
            {
                std::ostringstream oss;
                oss << total_index - vertices_.size()
                    << " vertices extra in"
                       " final set of identically colored connected components"
                    << std::endl;
                utility::LogError(oss.str().c_str());
                throw std::logic_error(oss.str().c_str());
            }
        }
    }
    return idc_vertices_cs;
}

bool TriangleMesh::isAVertex(const Eigen::Vector3i &triangle_vertex_indices,
                             const int &vertex_index,
                             int &nbr_1_vertex_index,
                             int &nbr_2_vertex_index) {
    bool result = false;
    nbr_1_vertex_index = nbr_2_vertex_index = -1;
    if (triangle_vertex_indices[0] ==
        vertex_index) {  // first vertex_index is a vertex_index of this
                         // triangle
        nbr_1_vertex_index = triangle_vertex_indices[1];  // set neighbors
        nbr_2_vertex_index = triangle_vertex_indices[2];
        result = true;
        return result;

    } else if (triangle_vertex_indices[1] == vertex_index) {
        nbr_1_vertex_index = triangle_vertex_indices[0];
        nbr_2_vertex_index = triangle_vertex_indices[2];
        result = true;
        return result;

    } else if (triangle_vertex_indices[2] == vertex_index) {
        nbr_1_vertex_index = triangle_vertex_indices[0];
        nbr_2_vertex_index = triangle_vertex_indices[1];
        result = true;
        return result;

    } else
        return result;  // not a vertex of this triangle, neighbors are
                        // invalid.
}

}  // namespace geometry
}  // namespace open3d

**Comment by syncle** [comment]
@sunilkumargit I am not quite sure about the attached code snippet. Could you explain on the code more?

**Comment by sunilkumargit** [comment]
@syncle : 
1. Find out the colors used in object and for each color create a container (set in c++) for vertices of this color. There will be N containers for the N colors.
2. Insert each vertex in to the container for it's color. Each vertex will fall in to one of the N containers.
3. If needed higher level grouping based on connected components, find the connected components. There will be M containers, one for each connected components and all vertices will be in one of these M containers. For each of these M containers, do step 2, so there will be M*N containers.
Is this logic clear now?

**Comment by sunilkumargit** [comment]
@ @syncle : 
1. Find out the colors used in object(s) : vector<color_t> _colors; // all colors.
2. Declare a set for each color in the above _colors; i.e. vector<set<vertex_t>> _identically_colored_vertices; // vertices of same color.

3. Take each vertex and insert it in to the set corresponding to it's color. If vertex i has color j, i will be inserted to the set _identically_colored_vertices[j].
4. Remove empty sets from _identically_colored_vertices, i.e. no vertex has got that color. It is a rare case.
----------------
1. If needed a higher level grouping based on connected components, find the connected components. set<vertex_t> : _connected_component; // Single connected component.
set<set<vertex_t>> : _connected_components; // All connected components. set is used rather than vector to test for duplication at the time of insertion.
 
2. For each connected component, declare a vector of colors, to group vertices belonging to this connected component with a particular color. i.e. vector<set<vertex_t>> : _color_groups_for_connected_component;. So vector<vector<set<vertex_t>>> _color_groups_for_connected_components; // color groups for all connected components.
3. Pick each vertex from _connected_components and insert it in to color group (set) corresponding to it's color. i.e. vertex i in j'th connected component is of color k,
it will be inserted in to the set _color_groups_for_connected_components[j][k].

Please see the attached image.
![logic](https://user-images.githubusercontent.com/8074691/76894492-42107c00-68b4-11ea-8dee-8af7b7303c58.jpg)

Is the logic clear now?
