### ISSUE TITLE
Registration Issue

### ISSUE THREAD

**Issue by easterngarden** [isl-org/Open3D#1571]
Hi,

I try to use RegistrationRANSAC example to align two face point clouds (global regsitration) but it does not work as expect.  The output always shows "RANSAC: Fitness 0.000000e+00, RMSE 0.000000e+00"  even I changed correspondence_checker_distance. Do I miss something? Thanks!
[registration.zip](https://github.com/intel-isl/Open3D/files/4300829/registration.zip)
[registration.zip](https://github.com/intel-isl/Open3D/files/4300833/registration.zip)

OS: Windows 10
C++ compiler is Visual C++ 2017
Open3D is 0.9.0

Format = auto
Extension = pcd
[Open3D DEBUG] PCD header indicates 8 fields, 32 bytes per point, and 5000 points in total.
[Open3D DEBUG] x, F, 4, 1, 0
[Open3D DEBUG] y, F, 4, 1, 4
[Open3D DEBUG] z, F, 4, 1, 8
[Open3D DEBUG] rgb, U, 4, 1, 12
[Open3D DEBUG] normal_x, F, 4, 1, 16
[Open3D DEBUG] normal_y, F, 4, 1, 20
[Open3D DEBUG] normal_z, F, 4, 1, 24
[Open3D DEBUG] curvature, F, 4, 1, 28
[Open3D DEBUG] Compression method is 2.
[Open3D DEBUG] Points: yes;  normals: yes;  colors: yes
[Open3D DEBUG] PCD data with 121857 compressed size, and 160000 uncompressed size.
[Open3D DEBUG] Read geometry::PointCloud: 5000 vertices.
[Open3D DEBUG] [RemoveNoneFinitePoints] 0 nan points have been removed.
[Open3D DEBUG] Pointcloud down sampled from 5000 points to 4999 points.
Format = auto
Extension = pcd
[Open3D DEBUG] PCD header indicates 8 fields, 32 bytes per point, and 5000 points in total.
[Open3D DEBUG] x, F, 4, 1, 0
[Open3D DEBUG] y, F, 4, 1, 4
[Open3D DEBUG] z, F, 4, 1, 8
[Open3D DEBUG] rgb, U, 4, 1, 12
[Open3D DEBUG] normal_x, F, 4, 1, 16
[Open3D DEBUG] normal_y, F, 4, 1, 20
[Open3D DEBUG] normal_z, F, 4, 1, 24
[Open3D DEBUG] curvature, F, 4, 1, 28
[Open3D DEBUG] Compression method is 2.
[Open3D DEBUG] Points: yes;  normals: yes;  colors: yes
[Open3D DEBUG] PCD data with 121754 compressed size, and 160000 uncompressed size.
[Open3D DEBUG] Read geometry::PointCloud: 5000 vertices.
[Open3D DEBUG] [RemoveNoneFinitePoints] 0 nan points have been removed.
[Open3D DEBUG] Pointcloud down sampled from 5000 points to 4999 points.
[Open3D DEBUG] total_validation : 0
[Open3D DEBUG] RANSAC: Fitness 0.000000e+00, RMSE 0.000000e+00
[Open3D DEBUG] GLFW init.
[Open3D DEBUG] Add geometry and update bounding box to [(29.4587, 62.4023, 1.1534) - (177.0252, 185.4884, 185.3205)]
[Open3D DEBUG] Add geometry and update bounding box to [(29.4587, 62.4023, 1.1534) - (187.3337, 219.3251, 185.3205)]
[Open3D DEBUG] Global colormap init.
[Open3D DEBUG] Global colormap destruct.
[Open3D DEBUG] GLFW destruct.

**Comment by germanros1987** [comment]
@syncle could you follow up?

**Comment by syncle** [comment]
Could you check the parameters used for the geometric feature extraction?

**Comment by easterngarden** [comment]
I used PCL uniform sampling to create PCD files which is basic the same face with different tranformation. The total sampling points are 5000 as shown in attached picture. Running the command shown below
![cloundpts](https://user-images.githubusercontent.com/36804327/76997859-3d2de580-6911-11ea-96ab-3ac4c6145d91.png)
:
 RegistrationRANSAC.exe object_5000.pcd object_tr1_5000.pcd --visualize

**Comment by germanros1987** [comment]
Hi! In the Open3D team, we take your question very seriously. In order to provide better assistance to our users, we are implementing new policies. Now general questions should be asked in our forum: https://forum.open3d.org

Github issues will remain in use for bug reports and feature requests.

We are looking forward to answering your question in our forum!

Best regards.
