### ISSUE TITLE
Intersection / Union / Difference of 3D meshes

### ISSUE THREAD

**Issue by ychechik** [isl-org/Open3D#1578]
Is it possible to add intersection / union / difference operators to o3d?

**Comment by germanros1987** [comment]
Hi @ychechik and thanks for the feature request. Would you be interested in working on an implementation of this feature with our advice?

**Comment by ychechik** [comment]
@germanros1987 I can give it a go, although I'm rusty in CPP (Python is my main). how do we continue from here?

**Comment by madvn** [comment]
In the meantime, how would one go about doing an intersection or union of two meshes?

**Comment by mjaein** [comment]
Any update or progress on this? I might be also able to do something here.

**Comment by benjaminum** [comment]
No update or progress on this. @mjaein please reopen if there is interest in working on this.

**Comment by benjaminum** [comment]
We added boolean operations in #5257
