### ISSUE TITLE
Registration issue

### ISSUE THREAD

**Issue by mastrogiorgis** [isl-org/Open3D#1646]
Hello everyone and thanks for your time producing this new PC library.

@germanros1987 this is Georgios. 

I have an issue with registration using RegistrationRANSAC from the examples in cpp.
Without changing any of the parameters, I observe a high error in registration of the two attached pcd (pcds.zip) pointclouds. The error is not the same every time I run the RegistrationRANSAC with the same set of images. Please see attached images below.

0.90 version, Win10, build from source, VS2019.

These PCs are very similar and I would expect registration to be fairly accurate.

Please advice.

Many thanks,

G

[pcds.zip](https://github.com/intel-isl/Open3D/files/4370992/pcds.zip)
![screenshot-1584984360](https://user-images.githubusercontent.com/23278410/77345354-66dd7700-6d2c-11ea-8a1a-264368c26433.png)
![screenshot-1584984588](https://user-images.githubusercontent.com/23278410/77345376-6cd35800-6d2c-11ea-9fdc-e9f605d00533.png)

**Comment by syncle** [comment]
RANSAC utilizes geometric features, but the underlying geometric feature of the point set you shared would be too similar. It is because the geometry is just a planar scene or some points on the line. In this case, RANSAC would confuse if the match is correct or not. I would like to recommend to use local registration methods such as ICP.

**Comment by mastrogiorgis** [comment]
Many thanks @syncle 

I replied to this on the other forum as well. Here is my response:

Thank you for your answer. I understand that this is a random process, but is it possible to run RANSAC on a nested loop to make sure that the successful case is selected?
Also, the downsampling is based on min and max values and would return the same PC every time. Is there a method already implemented to select edge points only?

Finally, in terms of ICP registration, this is only available in python not as a c++ in the examples. Is this part of the c++ code somewhere else please?

Many thanks,

G

**Comment by theNded** [comment]
You can run RANSAC with a customized outer loop, but it still doesn't guarantee that you have a successful case.

We don't have `edge` selection for point clouds yet, please feel free to contribute.

cpp examples for ICP are [available](https://github.com/isl-org/Open3D/blob/master/examples/cpp/TICPOdometry.cpp) now.
