### ISSUE TITLE
crop the crop

### ISSUE THREAD

**Issue by xuexiaoxiaohu** [isl-org/Open3D#1651]
I find  the code for cropping the point cloud as follows
print("Load a polygon volume and use it to crop the original point cloud")    
 vol = o3d.visualization.read_selection_polygon_volume(  "../../TestData/Crop/cropped.json")     chair = vol.crop_point_cloud(pcd)     
o3d.visualization.draw_geometries([chair])     
But I have no  polygon volume and cropped.json ,I just have a 3d face point cloud with neck, i want to get the face only ,remove the neck and other noise, how can I do?
Thank you very much !

**Comment by tfy14esa** [comment]
Hi!
My question is very related to the question above. To be specific: How can I generate a cropped.json file given that I only have the pointcloud? According to issue #404 at [https://github.com/intel-isl/Open3D/issues/404](url), there is supposed to be a GUI at bin/ManuallyCropPointCloud. I can not find this executable. I installed open3D with Conda.

Thanks.

**Comment by xuexiaoxiaohu** [comment]
I have found the pcd.crop(bbox) ,and I solved.

**Comment by tfy14esa** [comment]
Yes, I also found that. Thanks for sharing. I would like to know the answer to where I can find the "bin/ManuallyCropPointCloud" though.

**Comment by reyanshsolis** [comment]
http://www.open3d.org/docs/release/tutorial/visualization/interactive_visualization.html?highlight=crop

When you build from source, you will find it from build directory.
Open3D/build/bin/CropPointCloud.

Building from source: http://www.open3d.org/docs/release/compilation.html
