### ISSUE TITLE
Linker fails to find FLANN library

### ISSUE THREAD

**Issue by jrlagrone** [isl-org/Open3D#1654]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
Building from `master` fails with `ld: library not found for -lflann`

**To Reproduce**
1. pull master from git
2. make build directory
3. run cmake from build directory and then build (it doesn't matter if `BUILD_FLANN` is on or off)

**Expected behavior**
Build will complete successfully

**Environment (please complete the following information):**
 - OS: OSX Catalina 10.15.3
 - Python version:
 - Open3D version: 0.9.0 (up to date with master on github repo)
 - Is this remote workstation?: no
 - How did you install Open3D?: build from source. Tried Apple Clang, LLVM Clang, GCC. Using make files

**Additional context**
This appears to be caused by this change: https://github.com/intel-isl/Open3D/commit/867c4c2d693a72f59a63de87ff2a811162f3e10a#diff-4ab6a51f53d196629781726c6e33c678

I seem to have been able to fix this by adding `${FLANN_LIBRARY_DIRS}` here:
https://github.com/intel-isl/Open3D/blob/master/3rdparty/CMakeLists.txt#L344-L351

**Comment by pmkalshetti** [comment]
@jrlagrone thank you for the fix :)

**Comment by reyanshsolis** [comment]
FLANN is not used anymore in Open3D. Closing PR as depreciated. Please use the latest release.
