### ISSUE TITLE
quad mesh support

### ISSUE THREAD

**Issue by orgicus** [isl-org/Open3D#1692]
**Is your feature request related to a problem? Please describe.**
Open3D has brilliant support for `TriangleMesh`. It would be great to be able to use quad meshes as well (e.g. load quad .obj and process adjacency / compute half-edges mesh, etc.) without going back forth between triangle and quad face index juggling

**Describe the solution you'd like**

- An implementation of a `open3d.geometry.QuadMesh` class: very similar to `TriangleMesh` supporting quads
- An implementation of a `open3d.geometry.HalfEdgeQuadMesh`: very similar to `HalfEdgeTriangleMesh` supporting quads
- An implementation of a `open3d.io.read_quad_mesh` function: loads an .obj file and returns a QuadMesh
- An implementation of a `open3d.io.write_quad_mesh` function: writes a quads .obj file
- An implementation of a `open3d.io.quads_to_triangles` function: triangulates a quad mesh (input is a `QuadMesh`, output is a `TriangleMesh`) when possible (similar to Blender's Triangulate Faces `Ctrl+T` / Tris to Quads `Alt+J` option)
- An implementation of a `open3d.io.triangles_to_quads` function: converts a `TriangleMesh` to a `QuadMesh` when possible. (this could be useful with the `open3d.integration` module)

**Describe alternatives you've considered**
Converting a quad mesh to a triangle mesh in an external editor like Blender, working with Open3D's `TriangleMesh` class through out (including half-edge), write triangle mesh to file then convert back to quads in Blender.

**Additional context**
Good first ticket ? :)

**Comment by syncle** [comment]
Thanks for the request. Our team is working on new branches, so the request may not be addressed in the near future. We are always welcome if you are willing to contribute to this feature. :)

**Comment by ssheorey** [comment]
This is partially implemented in `open3d.geometry.TetraMesh`.
http://www.open3d.org/docs/latest/python_api/open3d.geometry.TetraMesh.html

**Comment by orgicus** [comment]
Thank you @ssheorey I'll give that a go :)

**Comment by TneitaP** [comment]
[meshio](https://github.com/nschloe/meshio) seems to be a library for more diverse mesh type inputs
