### ISSUE TITLE
EvaluateFeatureMatch compile error

### ISSUE THREAD

**Issue by femust** [isl-org/Open3D#1706]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
During compilation:

```
Built target DepthCapture
/home/femust/Libraries/Open3D/examples/Cpp/EvaluateFeatureMatch.cpp:232:21: error: loop variable 'feature' of type 'const std::basic_string<char>' creates a copy from type 'const std::basic_string<char>' [-Werror,-Wrange-loop-construct]
    for (const auto feature : features) {
                    ^

```

**To Reproduce**
```
Steps to reproduce the behavior:
git clone --recursive https://github.com/intel-isl/Open3D
cd Open3D && mkdir build && cd build
cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release ..
make -j
```

**Expected behavior**
Compiled project :) 

**Environment (please complete the following information):**
 - OS:Ubuntu 18.04
 - Python version:3
 - Open3D version: master branch
 - Is this remote workstation?: yes

**How to solve**
Go to **EvaluateFeatureMatch.cpp**
line **232**, and should be:

` for (const auto &feature : features) {`

**Comment by syncle** [comment]
Thanks for reporting issue @femust. Could you submit PR to fix this?

**Comment by theNded** [comment]
File has been removed from the project, closed for now.
