### ISSUE TITLE
select_down_sample vertex weirdness

### ISSUE THREAD

**Issue by AlbertoMQ** [isl-org/Open3D#1719]
select_down_sample seems to be reordering vertices, when I did on a large mesh the first value was not where it was supposed to be but the lengths are the same, but when I do the following I get different length arrays. It makes sense to me that they might be different when the length is different, but why should they be different when lengths are equal?

```
import open3d as o3d
import numpy as np

selection = np.arange(10)
print((np.asarray(meshObj.mesh.vertices)[selection,:])[:,:])
mesh = meshObj.mesh.select_down_sample(selection)
print(np.asarray(mesh.vertices)[:,:])
```

[[ 0.43408489 -1.40728104 -0.6802243 ]
 [ 0.43408489 -1.40620863 -0.68097824]
 [ 0.43408489 -1.40728104 -0.68130934]
 [ 0.43422258 -1.3952812  -0.67497826]
 [ 0.43408489 -1.39394438 -0.67497826]
 [ 0.43408489 -1.3952812  -0.67575407]
 [ 0.43408489 -1.39828122 -0.67556375]
 [ 0.43420064 -1.39828122 -0.67497826]
 [ 0.43360984 -1.39863026 -0.6746527 ]
 [ 0.43442219 -1.3952812  -0.67197824]]

[[ 0.43408489 -1.40728104 -0.6802243 ]
 [ 0.43408489 -1.40620863 -0.68097824]
 [ 0.43408489 -1.40728104 -0.68130934]
 [ 0.43422258 -1.3952812  -0.67497826]
 [ 0.43408489 -1.39394438 -0.67497826]
 [ 0.43408489 -1.3952812  -0.67575407]
 [ 0.43408489 -1.39828122 -0.67556375]
 [ 0.43420064 -1.39828122 -0.67497826]
 [ 0.43360984 -1.39863026 -0.6746527 ]]

 - OS: Ubuntu 18
 - Python version: 3.7- Open3D version: 0.9.0
 - Is this remote workstation?:no
 - How did you install Open3D?: conda

if you'd like me to upload a mesh let me know

**Comment by syncle** [comment]
@AlbertoMQ Yes, that would be great if you provide more input for us.

**Comment by theNded** [comment]
Closed due to the dormant state. Feel free to reopen.
