### ISSUE TITLE
glb is missed in fileio documentation

### ISSUE THREAD

**Issue by JasonQSY** [isl-org/Open3D#1724]
**Describe the bug**
In the documentation (https://github.com/intel-isl/Open3D/blob/master/docs/tutorial/Basic/file_io.rst#mesh), the mesh file io only supports `gltf`. However, `glb` is also supported according to #1082. `glb` is just the binary version of `gltf`, but the file extension is different.

**To Reproduce**
Since it's about documentation, there is no need to reproduce it.

**Expected behavior**
In order to have a better documentation, I suggest adding `glb` into formats supported by Open3D in https://github.com/intel-isl/Open3D/blob/master/docs/tutorial/Basic/file_io.rst#mesh and mention draco compression is not supported.

As far as I know, Open3D use [tinygitf](https://github.com/syoyo/tinygltf) to read and write gltf/glb files. It supports reading draco-compressed files but does not support draco mesh encoding.

**Screenshots**
N/A

**Environment (please complete the following information):**
Open3D master branch.

**Additional context**
N/A

**Comment by ytyfeng** [comment]
Can you still get face color of the mesh after it is converted from gltf to glb? For me, it removed the color of the gltf mesh after converting it to glb.

**Comment by benjaminum** [comment]
The documentation now mentions `.glb`. @ytyfeng please open a new issue if there is a problem with the imoprt.
