### ISSUE TITLE
Debianization of Open3D

### ISSUE THREAD

**Issue by roehling** [isl-org/Open3D#1770]
I'm currently working on bringing Open3D into Debian, and I found a number of improvements to the build system which make it easier to build Open3D for a (Linux) distribution. Are you generally interested in receiving these patches as PRs?

Also, I noticed that you do not explicitly set an SONAME for the shared library. For the current release, I'm leaning towards 0.9 as SOVERSION, but it would be good to have an "official" ABI version attached to each release.

**Comment by griegler** [comment]
In my opinion, our cmake scripts are a bit messy at the moment. So yes, it would be great if you could contribute a PR to improve them.

There exists `src/Open3D/version.txt`, but I think @yxlao could provide more information for the second question/request.

**Comment by roehling** [comment]
I'll start with a few simple PRs and work my way up to the more complex changes I made to the CMake scripts (which you will want to review more thoroughly first)

**Comment by roehling** [comment]
I was a bit work to turn my "make this Debian friendly" tweaks to the CMake scripts into something platform-independent, but I think I got it.

**Comment by ssheorey** [comment]
@roehling now that we have a Debian package, is it OK to close this issue? Please let us know / submit PRs if any updates are needed for future Open3D versions.

**Comment by roehling** [comment]
Yes, we can close this
