### ISSUE TITLE
Hi, how could I get the area of a set of points which can be fit to a plane?

### ISSUE THREAD

**Issue by JimXu1989** [isl-org/Open3D#1785]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when I want to get the area of a set of dense 3D points, which can be fit into a plane

**Describe the solution you'd like**
I want a API, which takes the 3D points as input, and directly give the fitted plane and the area of the points on the fitted plane

**Describe alternatives you've considered**

**Additional context**
![QQ截图20200503123552](https://user-images.githubusercontent.com/7732706/80898841-fe29e700-8d3a-11ea-9374-51931c425dd1.png)

**Comment by syncle** [comment]
To fit a point set to a plane, consider use [segment_plane](http://www.open3d.org/docs/release/python_api/open3d.geometry.PointCloud.html#open3d.geometry.PointCloud.segment_plane), [here is an example](https://github.com/intel-isl/Open3D/pull/1287#issue-334509856)
I don't fully understand how to compute area... Could you describe the way to compute the point set area?

**Comment by JimXu1989** [comment]
> To fit a point set to a plane, consider use [segment_plane](http://www.open3d.org/docs/release/python_api/open3d.geometry.PointCloud.html#open3d.geometry.PointCloud.segment_plane), [here is an example](https://github.com/intel-isl/Open3D/pull/1287#issue-334509856)
> I don't fully understand how to compute area... Could you describe the way to compute the point set area?

I use intel realsense sensor to capture the RGB-D image of a planar object, and I want get the area of the planar object by the 3D points, which means the area of contour that composed by the border points of the 3D points

**Comment by syncle** [comment]
There is no function for such a purpose. How about fit your point set with a plane, and voxelize the point sets? The number of voxels would indicate an approximate area of the contour. It would be better to orient the voxels along with the normal vector of the plane.

**Comment by JimXu1989** [comment]
> There is no function for such a purpose. How about fit your point set with a plane, and voxelize the point sets? The number of voxels would indicate an approximate area of the contour. It would be better to orient the voxels along with the normal vector of the plane.

Thanks a lot for reply !! Could you tell how the get the voxelize points sets? Is there any example?
Thanks a lot !!

**Comment by theNded** [comment]
Voxelization can be done by `pointcloud.voxel_down_sample(voxel_size)`.
