### ISSUE TITLE
From 3D scan to watertight mesh

### ISSUE THREAD

**Issue by kezkabarra** [isl-org/Open3D#1846]
This library seems pretty mature for my workflow (congrats, by the way :)): 3D scan --> various clouds of points --> alignment/registration --> downsampling --> mesh generation --> healing --> watertight mesh --> 3D print/anticollision systems... I hope I am wrong but after reading the docs I haven't found any tool for healing or functions to get watertight meshes. I consider that a pity, as the rest of the chain seems quite solid.
Again, I really hope Im wrong. Workarounds, tips, compatible tools are more than welcome ;). Keep it up!

**Comment by griegler** [comment]
Yes, it seems Open3D does not have any healing algorithms for 3D meshes. Do you have a particular algorithm in mind?

**Comment by GnnrMrkr** [comment]
I'm new to working with meshes but I have a similar problem. I came across [this answer](https://scicomp.stackexchange.com/a/20598) that might be helpful.

**Comment by benjaminum** [comment]
Please reopen if there is interest in integrating tools as mentioned in the comment above.
