### ISSUE TITLE
Crop meshes with multiple textures

### ISSUE THREAD

**Issue by nickponline** [isl-org/Open3D#1870]
It doesn't seem to be possible to crop meshes with mutple textures. Is there a workaround?

**Comment by nickponline** [comment]
Can I sponsor development of this feature?

**Comment by benjaminum** [comment]
@nickponline Let me know if there is still interest in this. 
Can you give a specific example of the workflow and expected output?

**Comment by nickponline** [comment]
@benjaminum I just would like existing `crop_triangle_mesh` function to work with meshes with multiple textures.

**Comment by nickponline** [comment]
@benjaminum @theNded 

I would like to do this:
```
mesh = o3d.io.read_triangle_mesh(f"House.obj", True)
bbox = o3d.geometry.AxisAlignedBoundingBox(min_bound=(-20, -20, -2000), max_bound=(20, 20, 2000))
mesh = mesh.crop(bbox)
```

However it removes all the textures, in the process.

**Comment by nickponline** [comment]
I was able to work around needing this with `mesh.triangle_material_ids = o3d.utility.IntVector(..)`
