### ISSUE TITLE
Different Keys in Visualizer to set FoV for qwertz Keyboards

### ISSUE THREAD

**Issue by GnnrMrkr** [isl-org/Open3D#1893]
**Is your feature request related to a problem? Please describe.**
Usually, the field of view can be changed by pressing the keys of the squared brackets (`[` and `]`). 
However, on qwertz keyboards  (standard layout e.g. in Germany), they placed on the `8` and `9` and are accessed with the `Alt Gr` key. Instead of pressing them, you need to use the `ü` and the `+` key (which are placed right to the `P` key; exactly in the `[` / `]` position on the qwerty keyboard) right now.

**Describe the solution you'd like**
Either just edit the help (easy to implement but inconvenient to use), or change the standard key, or add a secondary key (like implemented for _Exit Window_ and _Take a screen capture_) to change the field of view. My suggestions would be:

- Page Up and Page Down
- K and L
- C and V

But any solution would be better than the current situation.

**Edit**
The same problem occurs for changing the point size (`+` and `-` on qwerty, `ß` and `´` on qwertz).

**Comment by prewettg** [comment]
We will be working on a revamped visualizer architecture using the new GUI for 0.12. Would the solution described in #2320 work for you? (See the `examples/python/gui` directory for examples)
