### ISSUE TITLE
open3d 0.10.0: ImportError: /lib64/libm.so.6: version 'GLIBC_2.27' not found 

### ISSUE THREAD

**Issue by bigsheep2018** [isl-org/Open3D#1898]
Describe the bug
After update open3d to 0.10.0, once import open3d shows the error as the title.
I uninstall open3d 0.10.0 and get the 0.9.0 back, this error disappeared.

**To Reproduce**
1. conda install -c open3d-admin open3d
2. python -c "import open3d as o3d"
3. See error

**Expected behavior**
no errors

**Environment (please complete the following information):**
- Operating system: Ubuntu 16.04
- Python version: Python 3.6
- Open3D version: 0.10.0
- Is this remote workstation?:  no
- How did you install Open3D?: anaconda

**Comment by euivmar** [comment]
Ubuntu 16.04 seems to not be supported anymore.  Ubuntu 16.04 use only [glibc 2.23](https://launchpad.net/ubuntu/xenial/+source/glibc)

**Comment by StartAt24** [comment]
@bigsheep2018 have you solved this problem? Same thing happened to me.

**Comment by bigsheep2018** [comment]
hi @StartAt24 
As @euivmar  said, I searched a lot, and found the safe solution is to update your ubuntu 16.04 to 18.04 +. Manually change glibc lib is not suggested.

**Comment by xuexiaoxiaohu** [comment]
> Describe the bug
> After update open3d to 0.10.0, once import open3d shows the error as the title.
> I uninstall open3d 0.10.0 and get the 0.9.0 back, this error disappeared.
> 
> **To Reproduce**
> 
> 1. conda install -c open3d-admin open3d
> 2. python -c "import open3d as o3d"
> 3. See error
> 
> **Expected behavior**
> no errors
> 
> **Environment (please complete the following information):**
> 
> * Operating system: Ubuntu 16.04
> * Python version: Python 3.6
> * Open3D version: 0.10.0
> * Is this remote workstation?:  no
> * How did you install Open3D?: anaconda

It's OK

**Comment by asurada404** [comment]
Hi, I met the same question and solved by `pip install --user open3d`.

**Comment by EricWiener** [comment]
I'm also running into this issue. I'm using Travis CI and every build I ran fails:

On Xenial with Python 3.6, 3.7, or 3.8 I get:
```
E   OSError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/travis/build/EricWiener/bbox-utils/.tox/default/lib/python3.8/site-packages/open3d/cpu/pybind.cpython-38-x86_64-linux-gnu.so)
```

On Xenial with Python 3.9 I get:
```
ERROR: No matching distribution found for open3d
```

**Comment by RahulSajnani** [comment]
Hey everyone, is this issue resolved?

**Comment by EricWiener** [comment]
Not at all @RahulSajnani - we’re all just posting work-around

**Comment by ssheorey** [comment]
Sorry, Ubuntu 16.04 is not supported any more.
