### ISSUE TITLE
Object gets darker when moving camera forward/backward (mousewheel)

### ISSUE THREAD

**Issue by andreas-geiger** [isl-org/Open3D#1905]
**Describe the bug**

Dear Open3D, I am Andreas, working with Vladlen and my team on BRDF estimation and we like to use the Open3D viewer for visualizing our results. However, I encounter a strange behavior that other users seemingly don't have:

When opening the girl.obj file from this archive http://www.cvlibs.net/shared/girl.zip with open3d, rotating the object such that it faces the camera and then moving forward using the mouse wheel, the object becomes darker:

![bug1](https://user-images.githubusercontent.com/22158431/83112671-d114ee00-a0c6-11ea-9ce4-ec18025dae35.jpg)
![bug2](https://user-images.githubusercontent.com/22158431/83112672-d2461b00-a0c6-11ea-8716-e131e348f876.jpg)
![bug3](https://user-images.githubusercontent.com/22158431/83112677-d2461b00-a0c6-11ea-9289-b040066de3f8.jpg)

However, I only moved forward, I didn't change any lighting settings. It also happens in fly mode when pressing "W" for moving forward".

**To Reproduce**

1. start Open3D
2. open girl.obj from the zip file above
3. rotate to face towards the camera
4. use mouse wheel

**Expected behavior**
I would expect the light / shadows not to change if the camera moves closer.

**Screenshots**
Screenshots are attached and in the zip (bug1-3.jpg).

**Environment (please complete the following information):**

- Operating system: Ubuntu 18.04
- Python version: not relevant
- Open3D version: 0.10.1.0 (newest master version from yesterday build from source)
- Is this remote workstation?: no, its my local Dell XPS 13 laptop with Intel graphics
- How did you install Open3D?: build from source (cloned master version from yesterday)
- Compiler version: gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04)

Would be great to get your help with this. Happy to give more info if needed.
Thanks a lot. Great tool by the way - it will help us a lot in our research!

Prof. Andreas Geiger
Autonomous Vision Group
University & MPI-IS Tübingen
andreas.geiger@tue.mpg.de

**Comment by germanros1987** [comment]
Thanks @andreas-geiger, we are looking into it. We are trying to reproduce the error, which seems to require Intel graphics in Linux.

We will solve it soon!

**Comment by prewettg** [comment]
I can reproduce the problem with stock Ubuntu 18.04 and Intel Iris+ 655 integrated video. It appears to be related to SSAO, as commenting out FilamentView.cpp:84 (the line about SSAO) eliminates the symptoms, as does turning off environment mapping. I have attached a video. I am not sure that this is our bug, as there are reports of it happening in Valve's Source engine and on Windows as well as Linux:
    https://github.com/ValveSoftware/Source-1-Games/issues/2523
One solution with Left 4 Dead was to enable stenciling for tonemapped occlusions in the game's settings (maybe this is a hint as to the cause?):
   https://www.reddit.com/r/l4d2/comments/4rm90g/darkness_bug/
The same report mentions that it happened with an old nVidia card, too.

I have attached a video, in case it helps further troubleshooting.
[bug.mp4.zip](https://github.com/intel-isl/Open3D/files/4698828/bug.mp4.zip)

**Comment by prewettg** [comment]
Problem appears to be the Intel driver in Ubuntu 18.04. I booted using the Ubuntu 20.04 Live CD and it did not show the problem.

**Comment by errissa** [comment]
@andreas-geiger Did the solution suggested by @prewettg work for you or has the problem persisted?

**Comment by andreas-geiger** [comment]
Hi Rene,

I didn't have time to setup my laptop anew, but I found that (at least with
the latest version) the problem is mainly caused by the HDR environment
map. I don't need this, and if I disable it, the problem goes away, so its
fine for me.

It would actually be nice if there is a way to keep settings for future
launches to the program, such that (for instance) HDR maps don't need to be
disabled or sun intensity doesn't need to be increased whenever starting
the program. Or maybe some config file or parameter options..

Anyways, the tool is a great help for us.

Best,
Andreas

**Comment by germanros1987** [comment]
Hi @andreas-geiger we will add your request. This should be doable.
