### ISSUE TITLE
open3d::geometry::PointCloud:: voxel_down_sample output different result in different platform (windows 10 and ubuntu18.04)   (open3d 0.10.0 python API) 

### ISSUE THREAD

**Issue by Asher-1** [isl-org/Open3D#1906]
very wired!
maybe flann library bug?

**Comment by yxlao** [comment]
Can you provide a demo code that can recreate the problem?

**Comment by Asher-1** [comment]
sorry for late reply.
test code as follows:
 points = pc[:, :3].astype(np.float32)
    features = pc[:, 3:6].astype(np.uint8)
    cloud = o3d.geometry.PointCloud()
    cloud.points = o3d.utility.Vector3dVector(points)
    if features is not None:
        if np.max(features) > 20:
            cloud.colors = o3d.utility.Vector3dVector(features / 255.)
        else:
            cloud.colors = o3d.utility.Vector3dVector(features)
    down_cloud = cloud.voxel_down_sample(0.02)

    print(np.asarray(down_cloud.points))

windows 10 output:
open3D vision: 0.10.0.1
D:/raw.xyz
pc shape: (5286147, 6)
down sampling shape: (3347455, 3)
[[ -4.00413179 -18.78449059   6.3356781 ]
 [-41.82093811 -14.77951574   7.48934054]
 [-30.15839386 -18.28213882   6.5516181 ]
 ...
 [ 34.69234467 -18.59087563  18.70890617]
 [ 34.70071411 -18.59944344  18.37340927]
 [ 34.7130394  -18.60586357  18.07719994]]

ubuntu18.04 output:
open3D vision: 0.10.0.0
/media/yons/data/raw.xyz
pc shape (5286147, 6)
down sampling shape (3347455, 3)
[[ 34.75310898 -18.59763908  18.44279289]
 [ 34.71894073 -18.604105    18.11159134]
 [ 34.69597244 -18.60556793  18.07032013]
 ...
 [  0.78072101 -17.07873344  31.23420334]
 [  0.780743   -18.08837318  21.14915466]
 [  0.78498301 -18.05509663  22.70410156]]

**Comment by yxlao** [comment]
Looks like the downsampled shapes are the same `(3347455, 3)`. Are they the same points just in different orders? Could you sort the points and compare?

**Comment by Asher-1** [comment]
sorry for late reply.
yes, the test data in windows and ubuntu platform are same, so the points in different platform should be in the same orders. I guess that the input points order may be changed in open3d::geometry::PointCloud:: voxel_down_sample method.
the full scripts as follows:
`import numpy as np
    import pandas as pd
    import open3d as o3d

    filename = "raw.xyz"
    pc_pd = pd.read_csv(filename, header=None, delim_whitespace=True, dtype=np.float32)
    pc = pc_pd.values
    print("pc shape: {}".format(pc.shape))
    points = pc[:, :3].astype(np.float32)
    features = pc[:, 3:6].astype(np.uint8)
    cloud = o3d.geometry.PointCloud()
    cloud.points = o3d.utility.Vector3dVector(points)
    if features is not None:
        if np.max(features) > 20:
            cloud.colors = o3d.utility.Vector3dVector(features / 255.)
        else:
            cloud.colors = o3d.utility.Vector3dVector(features)
    down_cloud = cloud.voxel_down_sample(0.02)

    down_cloud = np.asarray(down_cloud.points)
    print("down sampling shape: {}".format(down_cloud.shape))
    print(down_cloud)`

Additionally, you can test any large point cloud with using above scripts and should get similar results.
By the way, test data can be found  as follows:
linker：https://pan.baidu.com/s/1eeR8niZBPsBD62txJxKc1A 
passwd：ttfx

Thank you for your help in advance!

**Comment by reyanshsolis** [comment]
The process runs in parallel, so the order might be different. The pointcloud is unorganised, therefore the order does not matter anyways.
