### ISSUE TITLE
Headless mode verifiable flag from software

### ISSUE THREAD

**Issue by ManuelZ** [isl-org/Open3D#1911]
**Is your feature request related to a problem? Please describe.**
I want a way to know from software if my Open3D installation has been compiled in headless mode or not, because if I call the .run() method of open3d.visualization.Visualizer() when in headless, the program will not finish running.
I want to do this because I have a Linux Machine with a Docker with the headless compilation and a Windows machine with the normal pip installation. I'd like to work on it on Windows and be able to see the mesh and interact with it and then deploy it in Docker, but currently I need to do all in only one side (either Win or Docker), otherwise I'd need to add or remove the .run() call.

**Describe the solution you'd like**
Bein able to call from python something like `open3d.is_headless()`

**Describe alternatives you've considered**
None yet.

**Additional context**
None.

**Comment by yxlao** [comment]
Good suggestion.

**Comment by germanros1987** [comment]
@errissa it seems you will be able to close this issue tomorrow. Please, remember to link the PR.
