### ISSUE TITLE
pip installation error: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by bigeyesung** [isl-org/Open3D#1934]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
I was compiling from the source code and everything went well but after "make install-pip-package", I got the error message as below: 
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/home/user/anaconda3/envs/py37/lib/python3.7/site-packages/MarkupSafe-1.1.1.dist-info/METADATA'

**To Reproduce**
1. conda activate py37
2. git clone --recursive https://github.com/intel-isl/Open3D
3. cd ~/Open3D/
4. mkdir build && cd build
5. cmake -DENABLE_HEADLESS_RENDERING=ON \
                 -DENABLE_GUI=OFF \
                 -DBUILD_GLEW=ON \
                 -DBUILD_GLFW=ON \
                 ..
6. make -j$(nproc)
7. make install-pip-package
8. See error

**Expected behavior**

**Screenshots**
![Screenshot from 2020-06-07 23-06-14](https://user-images.githubusercontent.com/17064093/83981264-41680e80-a914-11ea-86d5-79808598166d.png)

**Environment (please complete the following information):**

- Operating system: Linux Mint 19.1 Tessa
- Python version: Python 3.7
- Open3D version: 0.10.1.0
- Is this remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): gcc version 7.4.0

**Additional context**

**Comment by yxlao** [comment]
My guess is that this is not a specific problem related to Open3D, could you either 1) try to start from scratch from a fresh virtual environment, or, 2) try the workarounds mentioned in https://github.com/googleapis/google-cloud-python/issues/6647 ?
