### ISSUE TITLE
anyway for drawing boundingbox with confidence？

### ISSUE THREAD

**Issue by shouldnotfail** [isl-org/Open3D#1977]
thanks for your work, open3d is a pretty nice tool for 3D research! right now I want to draw the bbox with confidence that gets from the output of whatever 3D detection framework, is there already API for this usage? I tried to find it, but it fails, any hints are appreciated.

**Comment by shouldnotfail** [comment]
btw, now I draw the bbox with different colors according to the confidence, but the values are so closed.

**Comment by griegler** [comment]
You could set the color based on your confidence (`bbox.color = (1,0,0)`)?
