### ISSUE TITLE
Visualizing SLAM poses in the same window.

### ISSUE THREAD

**Issue by DrDumbenstein** [isl-org/Open3D#2015]
Hello guy! I have data with is a point could and i wanna Visualizer them while they are updating (SLAM poses). The problem is that when using a visualizer i have to click on exit so that the window closes and regenerated with new added points. I want the point to be visualized in the same Visualizer window. It is possible?!
![Screenshot at 2020-06-26 22-59-00](https://user-images.githubusercontent.com/40032759/85905004-16315a80-b802-11ea-8b4a-f2ed838f990b.png)
 [Code containing Open3d visualization ](https://github.com/DrDumbenstein/SLAM/blob/master/slam.py)

**Comment by griegler** [comment]
@DrDumbenstein did you have a look at this http://www.open3d.org/docs/release/tutorial/Advanced/interactive_visualization.html ?

**Comment by griegler** [comment]
I don't think there is a satisfactory solution right now. You could add a textured mesh in the corner of your window, but that will not stay in place as you navigate the scene. You can also visualize `Image`, but I do not think there a lot of controls on how it is visualized unfortunately.

**Comment by Zumbalamambo** [comment]
@griegler thanks! Is it possible to interface open3d with qt or any other gui creators?

**Comment by griegler** [comment]
No, unfortunately not.

**Comment by theNded** [comment]
It is now supported for the Dense SLAM system, but we are not planning to work on feature-based SLAM due to the workload. Closed for now.
