### ISSUE TITLE
I can't use mouse to change view when i visualize point cloud sequentially 

### ISSUE THREAD

**Issue by liuchangji** [isl-org/Open3D#2021]
i have some point cloud sequential
i want to show them in visualizer
so i use 
```
while(True):
     vis.add_geometry(pcd)
     vis.poll_events()
     vis.update_renderer()
     vis.clear_geometries()
```
to refresh the visualizer all the time.

it works 

but i can't use mouse change view to see point cloud in different angle

How can i solve these problem??

**Comment by Me817** [comment]
Hi,

how do you show you point clouds sequentially. Do you have any event to refresh the visualizer with a new point cloud?
I used the script provided by @g2ragrawal in #1961. 
With this I am able to use mouse change view to see the point cloud in different angles.
Hope it helps a bit.

**Comment by liuchangji** [comment]
> Hi,
> 
> how do you show you point clouds sequentially. Do you have any event to refresh the visualizer with a new point cloud?
> I used the script provided by @g2ragrawal in #1961.
> With this I am able to use mouse change view to see the point cloud in different angles.
> Hope it helps a bit.

thank you very much!!!!

i have  pointcloud point clouds sequential in hard disk like pcd001.pcd  pcd002.pcd pcd003.pcd ........pcd100.pcd
then i load them one by one 

```
vis = Visualizer()
vis.create_window()

for i in range(100):
   pcd = o3d.io.read_point_cloud("../../TestData/ pcd00"+"i"+".pcd")
   vis.add_geometry(pcd)
   vis.poll_events()
   vis.update_renderer()
   vis.clear_geometries()
```

so i can show the pointcloud one by one in vis.Visualizer()
during this period but i can't use mouse until for-loop is over..

**Comment by Me817** [comment]
I think you need vis.run() in your code. Without this, you are not able to change the viewpoint angle using the mouse. 
And you can see the different point clouds? When I try running your script I only can see a white Visualizer. I thinks because of the clear_geometries. How long do you display each point cloud?

**Comment by liuchangji** [comment]
> I think you need vis.run() in your code. Without this, you are not able to change the viewpoint angle using the mouse.
> And you can see the different point clouds? When I try running your script I only can see a white Visualizer. I thinks because of the clear_geometries. How long do you display each point cloud?

thank you very much!
you can try to set a wait time in every frame.

`cv2.waitKey(delay=100)`

I read point cloud frame from kinect or realsense d435i

I may try vis.run(),thank u very much!!!

**Comment by liuchangji** [comment]
> I think you need vis.run() in your code. Without this, you are not able to change the viewpoint angle using the mouse.
> And you can see the different point clouds? When I try running your script I only can see a white Visualizer. I thinks because of the clear_geometries. How long do you display each point cloud?

I display point clouds all the time read from kinect.... so maybe frame is endless

**Comment by B-urb** [comment]
I had the same problem. I think you need to set rest_view_point to false by using
``   vis.add_geometry(pcd,false);

Otherwise it is gonna reset every iteration. Maybe you have to do the same in clear_geometries as well.
I think this should be added to the docs, for use cases were you have to add/remove geometries during non-blocking rendering such as bounding boxes for new objects.

**Comment by liuchangji** [comment]
> I had the same problem. I think you need to set rest_view_point to false by using
> `` vis.add_geometry(pcd,false);
> 
> Otherwise it is gonna reset every iteration. Maybe you have to do the same in clear_geometries as well.
> I think this should be added to the docs, for use cases were you have to add/remove geometries during non-blocking rendering such as bounding boxes for new objects.

thank u ,it really works!!!!!

**Comment by andrearama** [comment]
The above solution did not work for me. 
Adding `vis.run()` at the end made it work
