### ISSUE TITLE
orient_normal_consistent_tangent_plane uses too much memory and time

### ISSUE THREAD

**Issue by ytyfeng** [isl-org/Open3D#2043]
**Is your feature request related to a problem? Please describe.**
I appreciate that the orient_normal_consistent_tangent_plane() method was implemented to address the normal orientation issue. In practice, however, the orient_normal_consistent_tangent_plane function uses too much memory and time that made it virtually impossible for me to use. When I ran the function in my Python interpreter, it took a long time and eventually it was killed due to the lack of memory. I also used it in an HPC cluster and despite requesting 48GB of memory the job was killed too. I set k=8 and there were 130,000,000 points in my point cloud. 

**Describe the solution you'd like**
Is it possible to optimize the MST implementation?

**Comment by griegler** [comment]
Memory consumption and performance is directly related to the parameter `k` used to construct the graph. Did you try to reduce it? As an alternative, is it feasible to subsample the point cloud, only orient normals on the smaller point cloud and then orient accordingly.

**Comment by ytyfeng** [comment]
> Memory consumption and performance is directly related to the parameter `k` used to construct the graph. Did you try to reduce it? As an alternative, is it feasible to subsample the point cloud, only orient normals on the smaller point cloud and then orient accordingly.

Yes, I reduced `k` all the way down to 1 but I was still not able to run the function on 130M points. How would you interpolate the results from orienting a subsample of the point cloud?

**Comment by griegler** [comment]
I think there is no convenient way at the moment. You could overload the `voxel_down_sample` method (https://github.com/intel-isl/Open3D/blob/master/cpp/open3d/geometry/PointCloud.cpp#L305) to also return the indices per voxel and use this information to orient all points in a voxel in the same direction.

**Comment by caniko** [comment]
@griegler how would you do this?

**Comment by ytyfeng** [comment]
@caniko One solution was to chunk the large point clouds into smaller manageable chunks before computing the normals for each chunk.

**Comment by caniko** [comment]
But how do you know that you are not chunking points that are neighbours into separate groups?
