### ISSUE TITLE
Saving point cloud as txt (add a file format argument to write_point_cloud())

### ISSUE THREAD

**Issue by ytyfeng** [isl-org/Open3D#2069]
**Is your feature request related to a problem? Please describe.**
Currently saving point clouds as `txt` is not supported, but saving as `xyz/xyzrgb/xyzn` is supported. I'd like to save my point clouds as `txt` ascii files but then I would have to save as `xyzrgb` and then rename them. 

**Describe the solution you'd like**
Is it possible to force saving point clouds using a specific extension in the filename string while using a `format` argument to specify the file format like in `open3d.io.read_point_cloud("point_cloud.txt", format="xyzrgb")`?   
It'd be great to have a `format` argument in `open3d.io.write_point_cloud()` too instead of inferring from the filename string.

**Comment by griegler** [comment]
Good suggestion. @ytyfeng would it be possible for you to contribute this feature with our aid?

**Comment by ytyfeng** [comment]
> Good suggestion. @ytyfeng would it be possible for you to contribute this feature with our aid?

Yes, I'd be happy to!

**Comment by griegler** [comment]
That is great! Let us know if you have any questions.
