### ISSUE TITLE
Open3D not run

### ISSUE THREAD

**Issue by jftmames** [isl-org/Open3D#2092]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
Open3D app not open in Ubuntu
**To Reproduce**

1. Download Open3DApp-0.10.1.0-linux.deb
2. Install
3. Open3D not run

**Expected behavior**
Run

**Environment (please complete the following information):**

- Operating system: Ubuntu 18.04
- Python version: Python 3.6
- Open3D version: 10.0
- Is this remote workstation?: no
- How did you install Open3D?: Open3DApp-0.10.1.0-linux.deb

**Additional context**
/

**Comment by jftmames** [comment]
sudo dpkg -i Open3DApp-0.10.1.0-linux.deb 
can't find the resource

**Comment by griegler** [comment]
@errissa can you have a look at this please.

**Comment by errissa** [comment]
@jftmames do you see the 'can't find resource' message when installing the Debian package or when attempting to run Open3D?

**Comment by brccabral** [comment]
I just had the same problem.
To fix it, need to change files `/usr/local/bin/Open3D` and `/usr/share/applications/Open3D.desktop`
Originally they are pointing to wrong locations.

File `/usr/local/bin/Open3D` is missing `local`, and `/usr/share/applications/Open3D.desktop` has double `Open3D/Open3D` in Exec command.

Final files should contain:

`/usr/local/bin/Open3D`
```
#!/bin/bash
exec /usr/local/share/Open3D/bin/Open3D "$@"
```

`/usr/share/applications/Open3D.desktop`
```
[Desktop Entry]
Type=Application
Name=Open3D
Icon=Open3D
Comment=Viewer for triangle meshes and point clouds
Exec=/usr/local/bin/Open3D %f
Terminal=false
Categories=Graphics
MimeType=model/stl;model/obj;model/fbx;model/gltf-binary;model/gltf+json;model/x.stl-ascii;model/x.stl-binary;model/x-ply;application/x-off;application/x-xyz;application/x-xyzn;application/x-xyzrgb;application/x-pcd;application/x-pts
```

**Comment by wpddmcmc** [comment]
> I just had the same problem. To fix it, need to change files `/usr/local/bin/Open3D` and `/usr/share/applications/Open3D.desktop` Originally they are pointing to wrong locations.
> 
> File `/usr/local/bin/Open3D` is missing `local`, and `/usr/share/applications/Open3D.desktop` has double `Open3D/Open3D` in Exec command.
> 
> Final files should contain:
> 
> `/usr/local/bin/Open3D`
> 
> ```
> #!/bin/bash
> exec /usr/local/share/Open3D/bin/Open3D "$@"
> ```
> 
> `/usr/share/applications/Open3D.desktop`
> 
> ```
> [Desktop Entry]
> Type=Application
> Name=Open3D
> Icon=Open3D
> Comment=Viewer for triangle meshes and point clouds
> Exec=/usr/local/bin/Open3D %f
> Terminal=false
> Categories=Graphics
> MimeType=model/stl;model/obj;model/fbx;model/gltf-binary;model/gltf+json;model/x.stl-ascii;model/x.stl-binary;model/x-ply;application/x-off;application/x-xyz;application/x-xyzn;application/x-xyzrgb;application/x-pcd;application/x-pts
> ```

Thank you @brccabral, edit ```/usr/share/applications/Open3D.desktop``` can solve this problem.
