### ISSUE TITLE
Release C++ for ROS

### ISSUE THREAD

**Issue by SteveMacenski** [isl-org/Open3D#2110]
Can Open3D be released for ROS both in python and C++? I see in rosdistro the pip install setup for open3d to install but nothing for the C++ version.

**Comment by SteveMacenski** [comment]
Necessary for support for ROS conversions to and from open3D https://github.com/ros-perception/perception_open3d

**Comment by griegler** [comment]
@germanros1987 should be able to comment on this.

**Comment by lwohlhart** [comment]
can one somehow contribute to making this happen?
I'd really love to have a simple integration of the amazing Open3D lib for ROS

**Comment by xkaraman** [comment]
Any updates on this?

**Comment by ssheorey** [comment]
Related (Debian package for libopen3d) : #1770

**Comment by ssheorey** [comment]
We are providing C++ binary packages (`tar.gz`) since PR #4647 (v0.15+). Does that solve your issue? @SteveMacenski @roncapat @xkaraman

**Comment by xkaraman** [comment]
I am not exactly sure to be honest. I just wanted to be able to install open3d within ROS Ecosystem. I believe it's a first step but someone need to integrate it now in ROS distro i guess.

**Comment by ppdr** [comment]
I am using open3d libraries in my C++ code with ROS melodic. After building open3d from source as shown in http://www.open3d.org/docs/release/compilation.html, I added this in my CMakeLists.txt

set(Open3D_DIR /usr/local/lib/cmake/Open3D)
find_package(catkin REQUIRED Open3D)

`/usr/local/lib/cmake/Open3D` is where I founded the file `Open3DConfig.cmake`.

**Comment by ssheorey** [comment]
Thanks @ppdr for the resolution. You can also download pre-built Open3D binaries from GitHub releases (instead of building from source).

Please re-open if anything else is required.

**Comment by xkaraman** [comment]
Using it from source was always possible with ros.
What i think this issue is for, is for Open3D to be available as a ros package, and installable as `ros-$(distro)-open3d`. As i said though on a comment above, binaries are a welcome addition though.

**Comment by wep21** [comment]
@ssheorey To release open3d as a ros package, it is necessary to add `package.xml` like https://github.com/wep21/perception_open3d/blob/open3d-vendor/open3d_vendor/package.xml into the project root. Is it acceptable for open3d?

**Comment by wep21** [comment]
I found the apt package for open3d in jammy. I will try to use it.
```
❯ apt-cache policy libopen3d-dev
libopen3d-dev:
  Installed: 0.14.1+dfsg-7build3
  Candidate: 0.14.1+dfsg-7build3
  Version table:
 *** 0.14.1+dfsg-7build3 500
        500 http://jp.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
        100 /var/lib/dpkg/status
```
