### ISSUE TITLE
Setting the extrinsic matrix for ViewControl

### ISSUE THREAD

**Issue by seann999** [isl-org/Open3D#2121]
Hi, this is probably more of a question than a bug.
I am having trouble setting the extrinsic matrix for visualization.
I am using the bottom method described in [this page](http://ksimek.github.io/2012/08/22/extrinsic/) (same output as gluLookAt, I believe) to derive the extrinsic matrix, but setting the ViewControl's extrinsic to this is not working for me (getting an undesired viewpoint).
I have tried its inverse, but that did not work.
What might I be doing incorrectly?

**Comment by seann999** [comment]
As additional information, what I'm trying to do is to programmatically render a point cloud from a different viewpoint.
I thought using the Visualizer might work.

**Comment by griegler** [comment]
Maybe this code snippets is of help (`Rs` and `ts` are camera rotations and translations; from world to camera coordinate system).

```python
        vis = o3d.visualization.Visualizer()
        vis.create_window(window_name="Playback", visible=True)
        ctr = vis.get_view_control()
        cam = ctr.convert_to_pinhole_camera_parameters()
        for view_idx, R, t in zip(itertools.count(), Rs, ts):
            T = np.eye(4)
            T[:3, :3] = R
            T[:3, 3] = t
            cam.extrinsic = T
            ctr.convert_from_pinhole_camera_parameters(cam)
            vis.poll_events()
            vis.update_renderer()
            time.sleep(0.1)
        vis.destroy_window()
```
