### ISSUE TITLE
Mesh Conversion

### ISSUE THREAD

**Issue by XiaoSong9905** [isl-org/Open3D#2124]
Hi, 

Thanks a lot for this amazing package. 

I've loaded a `.obj` file with texture to mesh `o3d.io.read_triangle_mesh("%s/%s.obj" % (output_folder, sample_ID))`. I'm trying to convert this mesh to a `.glb` file. Is there any way I can convert the texture to vertex_color? 

Thanks.

**Comment by griegler** [comment]
No, unfortunately not at the moment. But if you like we could aid you contributing this feature.
