### ISSUE TITLE
Question: Retrieving optimized camera poses and images from Color Map Optimization

### ISSUE THREAD

**Issue by bsespede** [isl-org/Open3D#2158]
Hi there,

First of all, thanks for such a great implementation of this algorithm. I was experimenting with it it and got amazing results on the color mapped mesh, nevertheless, I need the resulting poses/warped images for an image-based rendering technique. 

Would it be possible to retrieve the optimized poses/images somehow? I printed the poses used as input to the algorithm, but they are not changed after running the algorithm (same thing for the input images).

(I'm using the Python API by the way).

Thanks!

**Comment by yxlao** [comment]
You're right that this is not possible through the python interface right now. For the time being, you'll need to modify the C++ code do achieve that.

We were working on a refactoring of the color map optimization (https://github.com/intel-isl/Open3D/pull/2026), where we could consider adding the functionality you requested.

**Comment by theNded** [comment]
Supported after the color map optimization update.
