### ISSUE TITLE
Disable warning option

### ISSUE THREAD

**Issue by Leerw** [isl-org/Open3D#2169]
**Is your feature request related to a problem? Please describe.**
https://github.com/intel-isl/Open3D/issues/1259#issue-509954034
When I read a mesh from obj file, though the mtl and jpeg files exist, open3d could not read them and give me warnings, it seemed annoying.

**Describe the solution you'd like**
I want to have an option so that I can disable these warnings.

**Additional context**
My environment:
open3d==0.10.0.0
Ubuntu 18.04.5 LTS
Linux  5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by yxlao** [comment]
@errissa could you take a look?

**Comment by errissa** [comment]
@Leerw In the current master, Open3D will no longer issue a warning when there is no mtl file for the obj file. It will still issue warnings if an image file referenced in a valid mtl file cannot be loaded.

**Comment by Leerw** [comment]
OK, thanks

**Comment by Leerw** [comment]
It's really annoying! I just read point clouds with ".pcd" extension.
![image](https://user-images.githubusercontent.com/29098373/94251684-73e65780-ff55-11ea-8b2a-8fc4a0a9f004.png)

**Comment by theNded** [comment]
The redundant io log should have been fixed.
