### ISSUE TITLE
Questions about " std::tuple<std::shared_ptr<TriangleMesh>, std::vector<double>>" and "pcl::PolygonMesh::Ptr"

### ISSUE THREAD

**Issue by zengletian1491** [isl-org/Open3D#2174]
After screened poisson surface reconstruction, the data structure of the output is " std::tuple<std::shared_ptr<TriangleMesh>, std::vector<double>>". How does this data structure correspond to "pcl::PolygonMesh::Ptr" in pcl? I need to make a texture map using data with "pcl::PolygonMesh::Ptr" structure as input. Thank you.

**Comment by yxlao** [comment]
@griegler could you take a look at this?
