### ISSUE TITLE
Vertices Count in STL File

### ISSUE THREAD

**Issue by dhirajsuvarna** [isl-org/Open3D#2198]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
Number of Vertices in STL File in the `mesh` object after reading it using `o3d.io.read_triangle_mesh(stlFile)` 
is different when compared to other tools like CloudCompare or MeshLab

**Expected behavior**
Number of Vertices in STL file should be same as those shown in other tools

**Environment (please complete the following information):**

- Operating system: Windows 10 64-bit)
- Python version:  Python 3.6
- Open3D version: 0.10.0.1
- Is this remote workstation?: no
- How did you install Open3D?: pip

**Additional context**
Let me know if any other information is needed.

**Comment by griegler** [comment]
@dhirajsuvarna could you please share an `stl` file where this happens.

**Comment by dhirajsuvarna** [comment]
@griegler how do I share the file?

**Comment by griegler** [comment]
GitHub gist, or temporarily upload it to Dropbox, Google Drive, etc?

**Comment by dhirajsuvarna** [comment]
@griegler Uploaded [here] (https://drive.google.com/file/d/1M4e76TgAUVbS3g59X1rXpJivijsD3z94/view?usp=sharing)

**Comment by griegler** [comment]
The file contains the duplicate vertices, but you get your expected result like this

```Python
mesh = o3d.io.read_triangle_mesh('./tilted_rectangle.stl')
mesh.remove_duplicated_vertices()
```
