### ISSUE TITLE
A slice of 3D point cloud

### ISSUE THREAD

**Issue by hduonggithub** [isl-org/Open3D#2210]
Hi All,

I am wondering if there is a function to take a slice of point cloud and visualize it.  Or how to visualize a floorplan of 3D point cloud (XY plane), front view (XZ plane) and side view (YZ plane)?

For example, take a slice of point cloud at a given Z value, so I can have points selected within [Z-d, Z+d], d can be any number). 

I really appreciate if anyone can help. Thanks!

**Comment by yxlao** [comment]
Would `PointCloud::Crop` serve this purpose? https://github.com/intel-isl/Open3D/blob/master/cpp/open3d/geometry/PointCloud.h#L174

**Comment by hduonggithub** [comment]
@yxlao I will give it a try. Thanks
