### ISSUE TITLE
Calculated normal's do not match the given for shapenet dataset 

### ISSUE THREAD

**Issue by ShettyHarapanahalli** [isl-org/Open3D#2217]
I am calculating the normals for the shape net dataset [I want to add new classes later], I see that the calculated normals do not match the given normals in dataset.

1. Download the data set with the script share here - [https://github.com/mit-han-lab/pvcnn/blob/master/data/shapenet/download.sh](url)
2. run the below code 
    #!/usr/bin/env python
    import sys
    import numpy as np
    import open3d as o3d 
    import glob

    src_dir = "/shapenetcore_partanno_segmentation_benchmark_v0_normal/02691156/*.txt"

    def main():
        fl_list = glob.glob(src_dir)
        count = match = 0
        for f in fl_list:
            fp  = np.loadtxt(f).astype(np.float32)
            xyz = fp[:,:3] #XYZ coordinates 
            xyz_nor = fp[:,3:6] #normals of XYZ coordinates 
            label   = fp[:,:-1] #labels
            pcd  =  o3d.geometry.PointCloud() 
            pcd.points = o3d.utility.Vector3dVector(xyz)
            pcd.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=5))
           o3d.geometry.PointCloud.orient_normals_to_align_with_direction(pcd,orientation_reference=np.array([0., 0., 1.]))
            count = count + 1
            comparison = pcd.normals == xyz_nor
            if comparison.all():
                print(f"Normals match for file {f}")
                match = match + 1
            else:
                print(f"Normals do not match")
        print(f"Match {match/count}%")

    if __name__ == "__main__":
        main()

**Expected behavior**
Calculated normals to match the given normals 

**Environment (please complete the following information):**

- Operating system:Ubuntu 18.04
- Python version: Python 3.6
- Open3D version:
- Is this remote workstation?: no
- How did you install Open3D?:  pip
- Compiler version (if built from source): (e.g. gcc 7.5, clang 7.0)

**Additional context**

**Comment by ShettyHarapanahalli** [comment]
I am planning to add a new object class to the dataset [basically need to perform a custom 3d object detection].
To verify the dataset with the new class I have been trying to validate the process on the given data first.

**Comment by griegler** [comment]
I get that, but why should estimated normals (from `estimate_normals`) be the same as the normals of some loaded object (where the normals can be arbitrarily created)?

**Comment by ShettyHarapanahalli** [comment]
The dataset is created in a specific format/logic it will be better if we retain the same for the newly added object.
As this is a proven logic if changed not sure what could be the outcome from the algorithm.

**Comment by Marigod98** [comment]
hello, I have the similar problem, I want to estimate normals of some other object model, I hope the estimated results is similar to the shapenet dataset, so can you tell me how did you estimate the normals?

**Comment by reyanshsolis** [comment]
The open3d `estimate_normals` algorithm, computes covariances, and then use PCA to estimate normals. 
It is natural that the normals will not exactly match. The normals estimated with different parameters in Open3D, like by using the number of neighbours, and search radius, will also not be the same.
