### ISSUE TITLE
The parameter documentation for o3d.geometry.TriangleMesh.scale() has duplicates

### ISSUE THREAD

**Issue by benjaminum** [isl-org/Open3D#2220]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
The parameter documentation for o3d.geometry.TriangleMesh.scale() has duplicates.

**Expected behavior**
Doc with actual signature

**Environment (please complete the following information):**

- Open3D version: master

**Comment by griegler** [comment]
Also `rotate`.
@yxlao I guess this is caused by how overloaded methods are handled?

**Comment by ssheorey** [comment]
Fixed by PR #3373
