### ISSUE TITLE
How do we get OBB rotation without being centered?

### ISSUE THREAD

**Issue by richardrl** [isl-org/Open3D#2227]
If you create an object-oriented bounding box object `obb`, then `obb.R` gives you the rotation centered at the obb center.

How do you get the rotation centered at the origin?

**Comment by griegler** [comment]
I am not really sure what you mean with rotation centered at the origin. Could you please elaborate.

**Comment by richardrl** [comment]
Hi,
I have two obbs:
source_obb
target_obb

I both of them are centered at the origin.

I want to find the relative rotation from source_obb to target_obb.

However, this does not work:
```
import numpy as np
from scipy.spatial.transform import Rotation as R
relative_rot = R.from_matrix(target_obb.R) * R.from_matrix(source_obb.R).inv()
```

I am trying to understand why.

**Comment by griegler** [comment]
Why is your code snippet not working? What is your expected result and what are you getting?

**Comment by benjaminum** [comment]
@richardrl Please let me know if this question is still relevant.
