### ISSUE TITLE
OBJ colors are flipped , How To Fix? 

### ISSUE THREAD

**Issue by alexspace360** [isl-org/Open3D#2261]
**Describe the bug**
as export OBJ the colors are flipped , the colors in the front become in the back , so kindly help me to invert the colors

python

**Expected behavior**
i expect to see normal colors of 3D model at the front as it should be, but the opposite happens 
as you see in the screenshot , the colors should be in the front but you see it in the back :( 
**Screenshots**
[<a href="https://ibb.co/5nQFtKB"><img src="https://i.ibb.co/5nQFtKB/test58.jpg" alt="test58" border="0"></a>](url)

**another screenshots before and after invert with meshlab**

[<a href="https://ibb.co/d7V3Syr"><img src="https://i.ibb.co/d7V3Syr/before-and-after-invert.jpg" alt="before-and-after-invert" border="0"></a>](url)

**Environment (please complete the following information):**

- Operating system: Windows 10 64-bit
- Python version:  Python 3.6
- Open3D version:
- Is this remote workstation?: no
- How did you install Open3D?:pip

**Comment by alexspace360** [comment]
so how can i invert normals i am using 
 `    mesh.compute_vertex_normals()
    mesh.compute_triangle_normals()
    mesh.normalize_normals()
    mesh.triangle_normals = o3d.utility.Vector3dVector(np.asarray(mesh.triangle_normals)*-1)`

**Comment by germanros1987** [comment]
@errissa could you check if this is still a problem?

**Comment by errissa** [comment]
@alexspace360 I am looking into this issue. Would you please share the screenshots again? They are no longer available.
