### ISSUE TITLE
Converting Point Cloud to RGB-D data or extract associated 

### ISSUE THREAD

**Issue by Jaxi83** [isl-org/Open3D#2276]
I had 4 or 5 point cloud data and merge them together. But now, I am trying to extract RGB_D data from it. 
I can extract RGB data by **data.colors** and point data by **data.points** from the file, but how I can flat it to an RGB image.
```
data= o3d.io.read_point_cloud("...\\points.ply")
np.asarray(data.colors)
np.asarray(data.points)
```
My problem is the above function give me a (1250459,3) array and I have to convert it to (A,B,3) array, which A and B are my image size. and the 3 represent R,G and B.

**Comment by griegler** [comment]
You can use the [Visualizer](http://www.open3d.org/docs/release/tutorial/Advanced/customized_visualization.html) to render the pointcloud and then use [`capture_depth_float_buffer`](http://www.open3d.org/docs/release/python_api/open3d.visualization.Visualizer.html#open3d.visualization.Visualizer.capture_depth_float_buffer) to retrieve the depth map.

**Comment by Barath19** [comment]
@griegler Is there any other way to generate depth image from point cloud, which does not require visualization?

**Comment by griegler** [comment]
Rendering is definitely the fastest. As alternative you can project the points yourself, but you would need to implement it yourself (preferable in native code to get it fast). If `K` is your camera projection matrix, then `(u, v, d).T = K @ (x, y, z).T` and you have to keep track of the minimum depth `d` at the pixel locations `u/d, v/d`, `(x, y, z)` are the 3D points.
