### ISSUE TITLE
deterministic results of statistical outlier filter?

### ISSUE THREAD

**Issue by pgehring** [isl-org/Open3D#2344]
Hello,

I want to filter my point cloud for statistical outlier with the implemented filter in python. While using the `remove_statistical_outlier` with constant parameters on the same point cloud, I observed that the returned point cloud size is not deterministic.
For later steps in my processing pipeline it's really important that the filter is deterministic.

Is my understanding of the algorithm wrong or it possible that there are issues with the filtering?

regards
phil

**Comment by Zumbalamambo** [comment]
+@

**Comment by Zumbalamambo** [comment]
+1

**Comment by griegler** [comment]
The method `RemoveStatisticalOutlier` (https://github.com/intel-isl/Open3D/blob/master/cpp/open3d/geometry/PointCloud.cpp#L482) is deterministic itself. However, it uses a `KDTreeFlann` for the nearest neighbor search. I assume that this explains the non-deterministic behavior. @yxlao @benjaminum do you know something more about this?

**Comment by phil4991** [comment]
thanks for your first look on it gernot! 
Does anyone observed similar behaviour or could it be reproduced? This would be also interesting for me becauase I use the KDTree for a clustering algorithm.

thanks in advance
philipp

**Comment by liwind** [comment]
The statistical outlier removal algorithm of [PCL](https://github.com/PointCloudLibrary/pcl) is deterministic and robust. It can be borrowed.

**Comment by ophilar** [comment]
I observe similar behaviour with my code. Running the same code line containing remove_statistical_outlier several times results in slightly different outputs.

**Comment by reyanshsolis** [comment]
The only `non-deterministic` part of the algorithm is the `KNN` search. 
I verified with [PCL implementation of `radius_outlier_removal`](https://github.com/PointCloudLibrary/pcl/blob/master/filters/include/pcl/filters/impl/radius_outlier_removal.hpp), it is similar to the Open3D implementation. Only, KD-Tree based KNN search output might differ. Open3D uses nanoflann on CPU for KNN Search.

**Comment by FrankBlabu** [comment]
#7538 claims that this is not correct and instead the OMP implementation comes with a race condition. Evidence against the KD-Tree hypothesis is claimed as: Querying `KDTreeFlann.search_radius_vector_3d` serially for all 50 points of the reproducer returns a neighbour count of exactly 50 every time. So the KD-Tree as such is exact.

Setting `OMP_NUM_THREADS=1` with the linked  issues reproducer makes the function exact, which is what a race predicts and what a non-deterministic KD-tree would not.
