### ISSUE TITLE
Creating a mesh from a 3D point cloud from inside a tunnel

### ISSUE THREAD

**Issue by shakasaki** [isl-org/Open3D#2346]
This is probably not a bug, but more of a wrong implementation of the code. Nevertheless, I would very much appreciate your feedback.

What I am trying to do is to create a mesh from a 3D point cloud. The point cloud is a laser scan from inside a tunnel. The laser points are spaced 10 cm apart. The problem is that the resulting mesh, using the ball pivoting method, appears very scattered. I have played around with the ball radius and could not figure out a good solution.

**To Reproduce**
The point cloud is attached as a zipped numpy array. To reproduce you can just run the following code after unzipping

```
import numpy as np
import open3d as o3d
# import the point cloud using numpy and store as 03d object
point_cloud = np.load('point_cloud.npz')['arr_0'].T
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(point_cloud)
# Downsample with a voxel size of 10 cm
voxel_down_pcd = pcd.voxel_down_sample(voxel_size=0.1)
# estimate normals of points
voxel_down_pcd.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30))
# plot the point cloud
o3d.visualization.draw_geometries([voxel_down_pcd])
radii = [0.25, 0.5]
rec_mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_ball_pivoting(voxel_down_pcd, o3d.utility.DoubleVector(radii))
# plot the mesh
o3d.visualization.draw_geometries([rec_mesh])
```

**Expected behavior**
I expect a mesh that is connected, and forms a cylinder-like object (the tunnel). The resulting mesh consists of many disconnected pieces.

**Screenshots**
Screenshots attached

![screenshot_tunnel](https://user-images.githubusercontent.com/7264182/93333878-4a764f00-f824-11ea-8fed-256140b5ad49.png)

**Environment (please complete the following information):**

- Operating system: Ubuntu 18.04
- Python version: Python 3.7.6
- Open3D version: '0.10.0.0'
- Is this remote workstation?:  no
- How did you install Open3D?: conda

[point_cloud.zip](https://github.com/intel-isl/Open3D/files/5231955/point_cloud.zip)

**Comment by griegler** [comment]
The problem is most likely due to the normals. You use `estimate_normals` to, well, estimate the normals, but they are not oriented towards the same direction. You can verify this by visualizing the normals of `voxel_down_pcd`. You can have a look [here](http://www.open3d.org/docs/release/python_api/open3d.geometry.PointCloud.html#open3d.geometry.PointCloud.orient_normals_to_align_with_direction) and [here](http://www.open3d.org/docs/latest/python_api/open3d.geometry.PointCloud.html#open3d.geometry.PointCloud.orient_normals_consistent_tangent_plane) to fix this.

**Comment by shakasaki** [comment]
Hello @griegler and thank you for the response. Indeed, the problem seems to be due to the normals. I attach a screenshot of the normals computed on the given geometry (with the point cloud at full volume of 10cm spacing, and also scaled down to 2m spacing for visibility). Actually the full scale image does not look so bad (very hairy tunnel indeed but it seems like the normals face in the right direction). These are attached as screenshots. Nevertheless, I could not fix it with the suggested solutions. Specifically,

orient_normals_to_align_with_direction : This does not work because I am trying to mesh a tunnel. So more-or-less a long rough cylinder. So orienting the normals with any given direction will be inconsistent, since the orientation should be roughly outwards from the axis of the tunnel.

orient_normals_towards_camera_location : This does not work either, for the same arguments as stated above.

orient_normals_consistent_tangent_plane : While the two above methods can be executed, this method does not seem to run on my version of open3d. I get the following error:
Traceback (most recent call last):

  File "<ipython-input-2-299eba381970>", line 1, in <module>
    pcd.orient_normals_consistent_tangent_plane(10)

AttributeError: 'open3d.open3d_pybind.geometry.PointCloud' object has no attribute 'orient_normals_consistent_tangent_plane'


Thank you again for your time!


![dense_normals](https://user-images.githubusercontent.com/7264182/93595650-690d4f00-f9b8-11ea-8352-d42996683a7c.png)
![sparse_normals](https://user-images.githubusercontent.com/7264182/93595662-6f033000-f9b8-11ea-8e38-7dc60a49ef2b.png)

**Comment by griegler** [comment]
`orient_normals_consistent_tangent_plane` is not available in `v0.10`, you will need to build open3d from source. 
But your tunnel looks kinda straight, so you could compute the center of the tunnel and then orient all normals towards the center via `orient_normals_towards_camera_location`?

**Comment by shakasaki** [comment]
Yes that's an option but I think that still the normals should be pointing along a line, that runs through the tunnel.

**Comment by griegler** [comment]
Note that `orient_normals_towards_camera_location` does not bend the normals such that they point towards the camera center, but just flip the sign if they point away. The code is [here](https://github.com/intel-isl/Open3D/blob/master/cpp/open3d/geometry/EstimateNormals.cpp#L369).

**Comment by Sea421** [comment]
Hi @shakasaki,

I have faced with same issue. If you solved the issue, can you please give me advice?

Thanks

**Comment by shakasaki** [comment]
hi @Sea421,
Finally, I could not figure out a solution using open3D alone, so I combined it with pyvista.

Assuming you have a numpy array called "point_cloud" that has 3 columns (xyz) and rows for entries, this worked for me:

```
import o3d
import pyvista as pv
import numpy as np

pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(point_cloud)
downpcd = pcd.voxel_down_sample(voxel_size=0.2)
downsampled_point_cloud = np.asarray(downpcd.points)
cloud = pv.PolyData(downsampled_point_cloud).extract_geometry().triangulate()
volume = cloud.delaunay_3d(alpha=.3)
```

**Comment by Sea421** [comment]
Thank you very much
