### ISSUE TITLE
Downsample to a certain number of points from a point cloud.

### ISSUE THREAD

**Issue by ghost** [isl-org/Open3D#2359]
Currently, I think there is an option to voxel down sample by a certain decimal, but not  an option to downsample to a certain number of points. I think this would be useful for creating point cloud datasets, all with the same number of points.

**Comment by griegler** [comment]
Voxel down sampling to a certain number of points is tricky. What I could imagine is Poisson sampling. Could you describe your use case?

**Comment by itisyeetimetoday** [comment]
Sorry if I worded this badly, but I meant taken a point cloud(not voxel) with n-points, and sampling every x point until only z points are left, then creating a new point cloud.

**Comment by griegler** [comment]
Did you have a look at http://www.open3d.org/docs/release/python_api/open3d.geometry.PointCloud.html#open3d.geometry.PointCloud.uniform_down_sample ?
That said, it might also be interesting to bring Poisson sampling to the `PointCloud`.
