### ISSUE TITLE
How can i complie Fast_Global_registration

### ISSUE THREAD

**Issue by Hyeon-Hoo** [isl-org/Open3D#2386]
I have succeeded in build and I am trying to test fast_global_registration. but i got this error.
![Screenshot from 2020-09-29 05-21-53](https://user-images.githubusercontent.com/72046068/94482117-c2287e80-0213-11eb-93f8-d2e984679095.png)

I wrote [ g++ -std=gnu++11 FastGlobalRegistration.cpp ] in the terminal and changed #include <Eigen/Dense> to #include <eigen3/Eigen/Dense>.

**Comment by griegler** [comment]
You can not simply use `g++` to compile. 1) The compiler does not know where to look for the header files and you will also miss the libraries for linking. 2) The file you try to compile does not have a main function, what are you trying to achieve?

**Comment by Hyeon-Hoo** [comment]
I just want to run C/C++ files using g++/gcc, not using  build.

**Comment by griegler** [comment]
Then you have to provide all the libraries and include directories to the compiler. But that might be cumbersome.
