### ISSUE TITLE
AttributeError: module 'open3d' has no attribute 'compute_point_cloud_to_point_cloud_distance'

### ISSUE THREAD

**Issue by MengHao666** [isl-org/Open3D#2389]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
using open3d 0.9.0 and got such errors

**Comment by griegler** [comment]
You are looking for http://www.open3d.org/docs/release/python_api/open3d.geometry.PointCloud.html#open3d.geometry.PointCloud.compute_point_cloud_distance

You can use it like `dists = src.compute_point_cloud_distance(tgt)` where `src` and `tgt` are `PointCloud` objects.

**Comment by MengHao666** [comment]
is that also the cloest distance as before？




            
            
                
                    
                            
                                
                            
                            
                                sy1907502
                            
                    
                        
                            
                                    邮箱：sy1907502@buaa.edu.cn
                            
                        
                
            
        Signature is customized by Netease Mail Master


On 09/29/2020 15:23, Gernot wrote: 
You are looking for http://www.open3d.org/docs/release/python_api/open3d.geometry.PointCloud.html#open3d.geometry.PointCloud.compute_point_cloud_distance
You can use it like dists = src.compute_point_cloud_distance(tgt) where src and tgt are PointCloud objects.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/intel-isl/Open3D/issues/2389#issuecomment-700503859",
"url": "https://github.com/intel-isl/Open3D/issues/2389#issuecomment-700503859",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by griegler** [comment]
yes
