### ISSUE TITLE
Hole filling (also for large holes) and volume calculation

### ISSUE THREAD

**Issue by HollowHeartNet** [isl-org/Open3D#2399]
Hi,

I suggest to add the features 'close holes' (also for large holes, without losing detail) and 'calculate volume' since it is also possible to calculate the area of the mesh. Many would benefit from these features. A closed model is necessary in order to determine the volume. 

Thank you !
Best,
AR

**Comment by kongsgard** [comment]
Seems like a pretty neat way of calculating the volume of a mesh is explained here:
https://stackoverflow.com/questions/1406029/how-to-calculate-the-volume-of-a-3d-mesh-object-the-surface-of-which-is-made-up
I could give it a try to implement it in Open3D!

**Comment by AmarR91** [comment]
@kongsgard I have also found this 'easy' formula. I would be more than happy if you could try to implement it. However, I don't know if this approach is also valid for arbitrary surfaces / bodies. Nevertheless, implementing this formula for volume calculation would be great. But as I mentioned, a closed surface is required. Therefore, I would be nice to have a feature that is able to close (large) holes without losing model quality.

**Comment by griegler** [comment]
@AmarR91 do you have a specific algorithm in mind?

**Comment by AmarR91** [comment]
@griegler regarding hole filling algorithm I was thinking about this paper: http://www.cad.zju.edu.cn/home/hwlin/pdf_files/A-robust-hole-filling-algorithm-for-triangular-mesh.pdf
regarding volume calculation, in this paper a simple algorithm is proposed: http://chenlab.ece.cornell.edu/Publication/Cha/icip01_Cha.pdf

To be honest, I don't have the required programming skills in order to implement these algorithms in open3d. That's why I am asking the experts here. I hope you can do it. Open3D is great. Adding these features would make it even more awesome ;)

**Comment by griegler** [comment]
Thanks for the pointers @AmarR91 . We will keep them in mind and target them as soon as we have resources available.

**Comment by AmarR91** [comment]
Your are welcome! Thanks for the effort. I am looking forward to it. 👍

**Comment by kongsgard** [comment]
I could try to implement the hole filling algorithm too, if that's ok?
Seems like a fun challenge.

**Comment by AmarR91** [comment]
@kongsgard that would be awesome!

**Comment by kongsgard** [comment]
I encountered a problem on step 2 in the initial patch mesh generation:
"Step 2. Calculate the angle θi between two adjacent boundary edges(ei and ei+1) at each vertex vi on the front."

The smallest angle between the edges can be calculated with the dot product. However, the inner angle might be +180 degrees of that result if it is concave. Do you know of a method to solve this problem?

**Comment by griegler** [comment]
Do I understand your problem correctly? You want to get the angle between two edges that is opposite to the triangles, but the dot product is ambiguous, because you don't know if it is the angle within the triangles, or outside. If yes, [this](https://math.stackexchange.com/questions/15164/find-the-angle-as-measured-in-counter-clock-wise-direction-between-two-edges?noredirect=1) might maybe help.

**Comment by kongsgard** [comment]
Yes, that's right. 
The reference seems to only be valid in the 2D case (unless I'm missing something), so some sort of projection is needed (e.g. https://stackoverflow.com/questions/23814234/convert-3d-plane-to-2d). However, computing the normal of the plane spanned by the two edges also seems to be ambiguous. Is there a projection that doesn't require computation of the normal?

I'm using `HalfEdgeTriangleMesh::GetBoundaries()` to get the boundaries, so the edges are always ordered counter-clockwise. Perhaps this order could be used in some way?

**Comment by griegler** [comment]
This should be helpful: https://stackoverflow.com/questions/63373785/how-to-calculate-the-inner-angles-of-a-3d-polygon

**Comment by kongsgard** [comment]
That seemed promising, but I think the projection to the plane defined by the edge vertices is still ambiguous ([this](https://stackoverflow.com/a/23822086/14091969) is the best resource I've found, and it requires the plane vector as part of the computation).

An alternative approach could be to estimate the normal of the hole in the same manner as done for triangulation by ear clipping (the average of each cross product between adjacent edges of the boundary), and using [this](https://math.stackexchange.com/a/2141067) approach to calculate each angle. I think that would work under the assumption that no triangle normal in the hole is rotated more than 180 degrees from the averaged hole normal.

I'm not sure what's the best way to proceed?

**Comment by griegler** [comment]
I do not think you need a projection to a plane? Imagine the plane (u_0, u_1, u_2) of the three vertices. Now you could construct a plane that is orthogonal to this plane and contains u_0 and u_2. Then, you can simply check on which side of the latter plane u_1 is to decide the angle. But if one of your proposes methods seems easier, then let's implement them. You can always create a couple of unit tests to verify.

**Comment by RamyBebawy** [comment]
I am new to 3d models and surface reconstruction. I wonder if there is an algorithm for hole filling and volume calculation in python? 
Thanks

**Comment by sebinefrancis** [comment]
Yes. It would be very useful if there is a function to close holes like the one in meshlab (In meshlab first it is necessary to remove non manifold vertices if any, before applying close holes, other wise I got errors)

**Comment by benjaminum** [comment]
Please see #5285
