### ISSUE TITLE
How to Calculate the pixel in the camera view which a vertex in space project on

### ISSUE THREAD

**Issue by tianty** [isl-org/Open3D#2402]
Hello and thank you for the library!

I 'm quite new to using Open3d, and the library has so powerful functions. Now, I have a mesh of human face and I markered some vertices on it.  And I can set a camera to see it . Then I want to kown what can i do to put a texture image on the mesh and visualize it to save a new image.

Furthmore, How can I calculate the pixel in the image which correspond the vertex on the mesh(the 3D coordinate of the vertex and camera params is fixed). PS:Maybe the second question is hard to me.

Thank you.

**Comment by griegler** [comment]
You can use textured meshes, eg. loading a obj with associated textures.
If you know already the 3D position of your vertex, you need to project it to 2D. [This](http://www.open3d.org/docs/release/python_api/open3d.visualization.ViewControl.html#open3d.visualization.ViewControl.convert_to_pinhole_camera_parameters) and [this](http://www.open3d.org/docs/release/python_api/open3d.camera.html#) should help you to get the necessary camera parameters for your visualizer.

**Comment by tianty** [comment]
> You can use textured meshes, eg. loading a obj with associated textures.
> If you know already the 3D position of your vertex, you need to project it to 2D. [This](http://www.open3d.org/docs/release/python_api/open3d.visualization.ViewControl.html#open3d.visualization.ViewControl.convert_to_pinhole_camera_parameters) and [this](http://www.open3d.org/docs/release/python_api/open3d.camera.html#) should help you to get the necessary camera parameters for your visualizer.

Thank you for your quickly and useful answer!
I already kown the camera imaging principle. I ask this want to make sure the intrinsic matrix K and the rotation-translation matrix [R|t] is correct to projection. Because the rotation-translation matrix in trimesh is wrong in the world coordinate space. 
And by the way, I want to kown the index of vertices in the obj file is same to the mesh in Open3D, when the obj file loaded.

**Comment by griegler** [comment]
The camera parameters that you get from the visualizer are valid. You can use [this](http://www.open3d.org/docs/release/python_api/open3d.camera.PinholeCameraParameters.html#open3d.camera.PinholeCameraParameters.intrinsic) to get the intrinsic parameters [object](http://www.open3d.org/docs/release/python_api/open3d.camera.PinholeCameraIntrinsic.html) to query principal point and focal length to setup the camera intrinsic matrix `K`. Further, you can use [this](http://www.open3d.org/docs/release/python_api/open3d.camera.PinholeCameraParameters.html#open3d.camera.PinholeCameraParameters.extrinsic) to get the transformation matrix from world coordinate system to camera coordinate system (which is just `[R | t]`). 

Regarding index. There was a recent change in `io`. I think @errissa should be able to answer this question.
