### ISSUE TITLE
[question] set estimation and convergence criteria parametes (python API)

### ISSUE THREAD

**Issue by raphael2692** [isl-org/Open3D#2405]
Hello, 

i would like to change the last two parameters of the method `o3d.registration.registration_icp()`. 

How do i set different values from those set in `open3d.registration.ICPConvergenceCriteria` and `open3d.registration.TransformationEstimatio`?

Thanks!

**Comment by reyanshsolis** [comment]
It is explained in the upgraded ICP tutorials:
http://www.open3d.org/docs/latest/tutorial/t_pipelines/t_icp_registration.html#Parameters
