### ISSUE TITLE
Volume calculation (m³) of mesh 

### ISSUE THREAD

**Issue by EvaKrassnig** [isl-org/Open3D#2439]
I want to calculate the volume in cubic meters of an object, either directly from the point cloud or after creating a mesh (see example. Currently I use the pyntcloud library which has the possibility to create a convex hull and calculate the volume out of it: 

#CONVERT OPEN3D TO PYNTCLOUD
cloud = PyntCloud.from_instance("open3d", mesh) #mesh is the mesh created by function TriangleMesh.create_from_point_cloud_poisson 

#CALCULATE VOLUME FROM PYNTCLOUD
convex_hull_id = cloud.add_structure("convex_hull")
convex_hull = cloud.structures[convex_hull_id]
print(convex_hull.volume)

However, the result is not satisfying. I have no options in manipulating the convex_hull and cannot see how the algorithm changes the data before calculating volume. So I wonder if there is a possibility to do this in Open3D (calculating volume in m³ out of a mesh)? 

Further, if I have an object on the floor, how can I close the mesh on the backside? I assume this is necessary to get the volume.

Thank you in advance,
BR,
Eva

![Mesh](https://user-images.githubusercontent.com/71384423/95348084-f22feb80-08bd-11eb-8ccc-623478af1a82.PNG)

**Comment by griegler** [comment]
I have no idea about `pyntcloud`. You can compute the convex hull of a point cloud with open3d using this [function](http://www.open3d.org/docs/release/python_api/open3d.geometry.PointCloud.html#open3d.geometry.PointCloud.compute_convex_hull).
The volume of a watertight mesh (which the convex hull will be) can be computed with the recently merged method #2407 (note that you have to build open3d from source, it is not included in the pip/conda package).

**Comment by EvaKrassnig** [comment]
Hi, thank you for your help. 
I am using Windows 10 and Visual Studio 2019, Python 3.8. I followed the steps to build from source for windows described here: http://www.open3d.org/docs/release/compilation.html#compilation-ubuntu-install
And could proceed with build and install until the step as shown in picture attached. By the way: I am using librealsense and if I try to build the CMake file with the librealsense library I get an error message. 
After compiling from source, how can I use these libraries in my own project? My apologies if the question is stupid, but up to now I only used pip packages which I could use in my own python projects by "Import...."

![BuildfromSource](https://user-images.githubusercontent.com/71384423/95855106-3147bc00-0d58-11eb-8b3f-89de5acbcfe5.PNG)

BR,
Eva

**Comment by griegler** [comment]
@EvaKrassnig could you please open a new issue and flag it as build / install issue. Thanks.

**Comment by EvaKrassnig** [comment]
Ok, I will. Please leave this threat open in the meanwhile

**Comment by EvaKrassnig** [comment]
@griegler Is there a possibility to create a watertight mesh out of poisson? Convex hull is too unprecise and I was looking for a function that closes a mesh with holes but could not find anything.

**Comment by griegler** [comment]
The mesh that you get from `create_from_point_cloud_poisson` should be watertight if you do not remove triangles with low densities?

**Comment by EvaKrassnig** [comment]
Yes, it is watertight on the top, but I have an open Bottom which I do not know how to close. As shown in my example above I have the upper Shell, but if I turn it, the Bottom is open. 
![Mesh_below](https://user-images.githubusercontent.com/71384423/96091219-9bcc3980-0ec9-11eb-80ee-3c8eaaa7a848.PNG)

**Comment by griegler** [comment]
@kongsgard is currently working on a hole filling algorithm #2460 that might be useful in that case.

**Comment by akanksh2kb** [comment]
Is volume calculated using **convex hull** in **cubic meters**( real volume)?
if **not** what parameters should be **multiplied or divided** to convert to real-time?

**Comment by ssheorey** [comment]
The  volume will depend on the length units of the input mesh. If the vertices of the input mesh are in meters, then the volume will be in m^3.

**Comment by ssheorey** [comment]
Hole filling is now supported: https://github.com/isl-org/Open3D/pull/2460#issuecomment-1398162756
