### ISSUE TITLE
Sample points from textured mesh

### ISSUE THREAD

**Issue by sebaFP** [isl-org/Open3D#2483]
Hi,
I need to generate a point cloud from a textured obj, I can generate it but without colors. 
Can I generate a sample but getting vertex color from texture?
Thanks!

**Comment by griegler** [comment]
Textures are not considered yet in `sample_point_cloud_*`. It shouldn't be hard to implement. Would you be interested in contributing a PR with our guidance?

**Comment by Xelawk** [comment]
> Textures are not considered yet in `sample_point_cloud_*`. It shouldn't be hard to implement. Would you be interested in contributing a PR with our guidance?

I also really need this feature

**Comment by ShougangShen** [comment]
> Hi,
> I need to generate a point cloud from a textured obj, I can generate it but without colors.
> Can I generate a sample but getting vertex color from texture?
> Thanks!

Hello, I have the same requirement as you. Have you realized this feature?

**Comment by Xelawk** [comment]
I have done
*Best Regards，*
*Ruisheng Lei*


ShougangShen ***@***.***> 于2021年4月4日周日 下午2:47写道：

**Comment by Xelawk** [comment]
> > Hi,
> > I need to generate a point cloud from a textured obj, I can generate it but without colors.
> > Can I generate a sample but getting vertex color from texture?
> > Thanks!
> 
> Hello, I have the same requirement as you. Have you realized this feature?

Yep, I have the code to do this operation. If you need it, please contact me :-)

**Comment by MaybeOjbk** [comment]
> > > Hi,
> > > I need to generate a point cloud from a textured obj, I can generate it but without colors.
> > > Can I generate a sample but getting vertex color from texture?
> > > Thanks!
> > 
> > 
> > Hello, I have the same requirement as you. Have you realized this feature?
> 
> Yep, I have the code to do this operation. If you need it, please contact me :-)
can you give me your code ?

**Comment by Xelawk** [comment]
> > > Hi,
> > > I need to generate a point cloud from a textured obj, I can generate it but without colors.
> > > Can I generate a sample but getting vertex color from texture?
> > > Thanks!
> > 
> > 
> > Hello, I have the same requirement as you. Have you realized this feature?
> 
> Yep, I have the code to do this operation. If you need it, please contact me :-)
> can you give me your code ?

OK, Tell me you email

**Comment by cr139139** [comment]
> > > Hi,
> > > I need to generate a point cloud from a textured obj, I can generate it but without colors.
> > > Can I generate a sample but getting vertex color from texture?
> > > Thanks!
> > 
> > 
> > Hello, I have the same requirement as you. Have you realized this feature?
> 
> Yep, I have the code to do this operation. If you need it, please contact me :-)

Can I also get the code for the operation? Here's my email:
cr139139@naver.com

**Comment by cr139139** [comment]
> > > Hi,
> > > I need to generate a point cloud from a textured obj, I can generate it but without colors.
> > > Can I generate a sample but getting vertex color from texture?
> > > Thanks!
> > 
> > 
> > Hello, I have the same requirement as you. Have you realized this feature?
> 
> Yep, I have the code to do this operation. If you need it, please contact me :-)

Can I also get the code for the operation? I'll send a note to your gmail address.

**Comment by Xelawk** [comment]
Feel free to the repo: https://github.com/Xelawk/mesh_utils
If it does help you, pls star it, Thanks

**Comment by cr139139** [comment]
Of course! Thanks a lot!
By the way, I have one more question. I saw your code and didn't find out
how to use it.
Can you show me a sample usage if possible? I'm really sorry for asking
this. I'm not a coding guru...

**Comment by benjaminum** [comment]
Thanks for sharing a solution.

**Comment by NiuCY** [comment]
I think this way is better:
mesh = trimesh.load_mesh(mesh_path)
samples, face_idx, colors = trimesh.sample.sample_surface(mesh, 30000, sample_color=True)

**Comment by nikste** [comment]
It seems @Xelawk solution does not work anymore with the new version of Open3d (or I am doing something wrong)
@benjaminum @griegler can we reopen this and do you have some pointers how this could be implemented for open3d?

**Comment by nikste** [comment]
so I guess I can put it there:
https://github.com/isl-org/Open3D/blob/fcf98ee454df1ccb62be01e011449856ccc10c15/cpp/open3d/geometry/TriangleMesh.cpp#L476

check if there `has_textures()` returns true and then read the color from the texture.
how to arrive at the right pixel coordinate though to read the color and add to the resulting point cloud color?
what does `triangle_uvs[triangle_idx]` ?

**Comment by benjaminum** [comment]
Hi @nikste 
The steps to implement this would be
1. Remember triangle idx for each point
2. Compute triangle barycentric coordinates for the sampled point from the point xyz and the triangle vertices xyz
3. Compute UV coordinates using the triangle_uvs with the weights from the barycentric coordinates
4. Look up the color values in the texture at the respective UV coordinates
