### ISSUE TITLE
Alpha/Opacity channel?

### ISSUE THREAD

**Issue by ItayKishon** [isl-org/Open3D#2528]
Hi,

Is there a way to use an alpha (opacity) channel? 

Specifically, I have _complete_ 3D raster data of a volume (i.e. all x*y*z voxels) , where each voxel has some intensity level. I want to visualize it using some sort of transparency channel, as using simple RGB values would practically block everything but the outside facets.
Alternatively, is it possible to use the voxel's radius for that?

Thanks,
Itay

**Comment by germanros1987** [comment]
Is this data given as a VoxelGrid?

**Comment by HaFred** [comment]
> 

Hi, do you happen to know how to set the alpha/opacity for a voxel grid? Thanks a lot.

**Comment by rtviii** [comment]
Bump. Need this too. I don't think it's possible atm. RGB class has only 3 channels
