### ISSUE TITLE
Accessing the values of the the RGBD image

### ISSUE THREAD

**Issue by Zumbalamambo** [isl-org/Open3D#2540]
I have used the following code to create an RGBD image,

```
import cv2
import open3d as o3d

depth_img = cv2.imread("assets/dataset/depth/21.png", cv2.IMREAD_ANYDEPTH)

depth_img =  cv2.resize(depth_img, (depth_img.shape[1] * 4, depth_img.shape[0] * 4))
cv2.imwrite("assets/depth_image.png", depth_img)

color_raw = o3d.io.read_image("assets/dataset/rgb/21.png")
depth_raw = o3d.io.read_image("assets/depth_image.png")

#create rgbd image
rgbd_image = o3d.geometry.RGBDImage.create_from_color_and_depth(
    color_raw, depth_raw)
```

How do I access the value at a specific coordinate in the RGB-D image?

For example, I would like to access the 3D coordinates at the coordinate `(308,124)` in the RGB-D image

**Comment by theNded** [comment]
You may use `np.asarray(color_raw.data)` to obtain the underlying numpy array, and access by their coordinates.
