### ISSUE TITLE
Q: How to set min/max for colormap when rendering a pointcloud?

### ISSUE THREAD

**Issue by maxfreu** [isl-org/Open3D#2545]
Hi! I would like to set the range of the colormap when rendering a pointcloud; I only want a color gradient from e.g. z=0 to z=1 although there are points above and below that region. Is this currently possible? If yes, how?
Edit: I am using v0.9.0 btw

**Comment by germanros1987** [comment]
This is possible using the new API. @errissa could you please provide an example?

**Comment by ssheorey** [comment]
Hi @maxfreu please upgrade to the latest Open3D v0.14.1. Here is sample code for using the color gradient with the new API:

```python
import open3d as o3d
from open3d.core import Tensor, concatenate
from open3d.visualization import rendering, draw
from open3d.ml.vis import Colormap

values = Tensor.arange(start=0.0, stop=1.0, step=0.001).reshape((-1, 1))
period = 0.2
xyz = concatenate(
    ((6.28 / period * values).sin(), (6.28 / period * values).cos(), values), 1)
pcd = o3d.t.geometry.PointCloud(xyz)
pcd.point['__visualization_scalar'] = values
colormap = Colormap.make_rainbow()
colormap = list(
    rendering.Gradient.Point(pt.value, pt.color + [1.0])
    for pt in colormap.points)
material = rendering.MaterialRecord()
material.shader = "unlitGradient"
material.gradient = rendering.Gradient(colormap)
material.gradient.mode = rendering.Gradient.GRADIENT
material.scalar_min = 0.0
material.scalar_max = 1.0

draw({
    'name': 'helix',
    'geometry': pcd,
    'material': material
},
     point_size=3,
     show_skybox=False)
```
<img width="804" alt="Screenshot 2021-12-06 at 11 35 27 AM" src="https://user-images.githubusercontent.com/41028320/144910944-c2071635-5579-4891-b646-e1b9ef885498.png">

**Comment by maxfreu** [comment]
Thanks! It will take a while until I come around to trying it out, but good to know it works now. I leave it at your descretion to close the issue.

**Comment by MeyerBuaharon** [comment]
> 
Hello @ssheorey and thanks for the snippet.
How would you recommend to do it on an existing pcd?
im trying to replicate your code, but I get weird colors...
Like after I read the pcd, I get the max and min Z and use them as a guidence on how to get the gradient.
`
       pcd = o3d.io.read_point_cloud('./cropped_1.ply')

        self._scalar_min = np.array(pcd.points)[:,2].min()
        self._scalar_max = np.array(pcd.points)[:,2].max()

        cmap = self._colormaps[self.RAINBOW_NAME] 
      
        self.settings.material = self._get_material()

        from open3d.core import Tensor, concatenate

        xyz = Tensor(np.array(pcd.points))
        pcd = o3d.t.geometry.PointCloud(xyz)
        pcd.point['__visualization_scalar'] = xyz[:,2]
        material = rendering.MaterialRecord()
        material.shader = "unlitGradient"
        material.gradient = rendering.Gradient(colormap)
        material.gradient.mode = rendering.Gradient.GRADIENT
        material.scalar_min = self._scalar_min
        material.scalar_max = self._scalar_max
        draw({
    'name': 'gradient',
    'geometry': pcd,
    'material': material
},
     point_size=3,
     show_skybox=False)

`
