### ISSUE TITLE
Some functions of TriangleMesh are very slow

### ISSUE THREAD

**Issue by Sea421** [isl-org/Open3D#2555]
**Some functions of TriangleMesh are very slow - is_watertight, get_volume**
Hi team,
I would like to calculate **volume** of **watertight** triangle mesh. But these functions are very slow. My mesh has 13.5k faces, 6.7k vertices. But each function elapsed **>30 seconds**.
Following is my code and the result. Please advice me.

**To Reproduce**

Code:
```
import open3d as o3d
import time

if __name__ == '__main__':
    mesh = o3d.io.read_triangle_mesh("screwdriver.ply")

    tstart = time.time()
    print("is watertight? " + str(mesh.is_watertight()))
    print('Elapsed: %.3f' % (time.time() - tstart))

    tstart = time.time()
    print("volume: " + str(mesh.get_volume()))
    print('Elapsed: %.3f' % (time.time() - tstart))

```

Result:
```
is watertight? True
Elapsed: 35.357
volume: 1.390739457349182e-05
Elapsed: 34.806
```

**Expected behavior**
Please advice me

**Environment (please complete the following information):**

- Operating system: **Windows 10 64-bit** - **Processor**: Intel(R) Xeon(R) Bronze 3104 CPU @ 1.70GHz (6 CPUs), ~1.7GHz, **Ram**: 32GB
(also tested on Ubuntu 20.04 virtual machine -each function elapsed ~13 seconds)
- Python version: Python 3.8
- Open3D version: v0.11.1
- Is this remote workstation?: no
- How did you install Open3D?: using pip in conda environment

**Additional context**
Attached is the Triangle mesh file that used on code: [screwdriver.zip](https://github.com/intel-isl/Open3D/files/5457126/screwdriver.zip)

**Comment by benjaminum** [comment]
We have improved the runtime efficiency in #4525 .
