### ISSUE TITLE
functions not recognized e.g. AxisAlignedBoundingBox()

### ISSUE THREAD

**Issue by aycameric** [isl-org/Open3D#2559]
Hi,
I am using functions like AxisAlignedBoundingBox() for initialization. In the documentation it says that I can input the bounding vectors, however I get this error message below. I tried to install from source again, but this didn't help. 
Also I get the error message that an attribute is not found, even though prior it worked. Thanks!

AttributeError: 'open3d.open3d.geometry.PointCloud' object has no attribute 'get_rotation_matrix_from_xyz'

[ERROR] [1604002038.054544]: bad callback: <bound method Matcher.cb_getobjectpose of <__main__.Matcher instance at 0x7faca9641518>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./findgoal.py", line 69, in cb_getobjectpose
    max_bound=(10, 20, 10))
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. open3d.open3d.geometry.AxisAlignedBoundingBox()
    2. open3d.open3d.geometry.AxisAlignedBoundingBox(arg0: open3d.open3d.geometry.AxisAlignedBoundingBox)

Invoked with: kwargs: max_bound=(10, 20, 10), min_bound=(-30, 0, -10)

**Comment by sanskar107** [comment]
`get_rotation_matrix_from_xyz` works for me. Which version of Open3D are you using ?

**Comment by aycameric** [comment]
I am using Version: 0.8.0.0

**Comment by aycameric** [comment]
when I try to compile from source I get this error message:
**CMake Error at CMakeLists.txt:10 (cmake_minimum_required):
 CMake 3.15 or higher is required.  You are running version 3.5.1


-- Configuring incomplete, errors occurred!**


I tried to fix it with these commands:
export PATH=$HOME/cmake-install/bin:$PATH
export CMAKE_PREFIX_PATH=$HOME/cmake-install:$CMAKE_PREFIX_PATH

but it's not working, I still get the same error.

**Comment by sanskar107** [comment]
You can install the latest version with `pip install open3d==0.11.1` for python functionality.
for building from source, can you post the output of your CMake ?

**Comment by aycameric** [comment]
with pip install open3d==0.11.1 I get this Error: 
ERROR: Could not find a version that satisfies the requirement open3d==0.11.1 (from versions: 0.8.0.0, 0.9.0.0)
ERROR: No matching distribution found for open3d==0.11.1

after "cmake ..", I get:

-- THIRD_PARTY_DOWNLOAD_DIR is not specified, will download directly.
-- No CMAKE_BUILD_TYPE specified, default to RelWithDebInfo
-- Open3D 0.11.1+b1423e1
-- Using python from PYTHON_EXECUTABLE variable: /usr/bin/python
-- (PYTHON_EXECUTABLE matches python from PATH)
-- Building library Assimp from source
-- Building with OpenMP
-- Building library 3rdparty_eigen3 from source
-- Building library 3rdparty_flann from source
-- Building library 3rdparty_nanoflann from source
-- Building library 3rdparty_glew from source
-- Building library 3rdparty_glfw3 from source
-- Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR) 
-- Using X11 for window creation
-- Building third-party library JPEG from source
-- NASM assembler not found - libjpeg-turbo performance may suffer
-- libturbojpeg: WITH_CRT_DLL=OFF
-- Building library 3rdparty_jsoncpp from source
-- Building library 3rdparty_lzf from source
-- Building library 3rdparty_tritriintersect from source
-- Building third-party library zlib from source
-- Building third-party library libpng from source
-- Building library 3rdparty_rply from source
-- Building library 3rdparty_tinyfiledialogs from source
-- Building library 3rdparty_tinygltf from source
-- Building library 3rdparty_tinyobjloader from source
-- Building library 3rdparty_qhull_r from source
-- Building library 3rdparty_qhullcpp from source
-- Building library 3rdparty_fmt from source
-- pybind11 v2.5.0
-- Building library 3rdparty_poisson from source
-- Building library 3rdparty_imgui from source
-- Using prebuilt third-party library Filament
-- GLIBC version 2.23-0 found: Downloading Google Filament binary.
-- Filament is located at /usr/Open3D/build/filament/src/ext_filament
CMake Error at 3rdparty/find_dependencies.cmake:917 (find_library):
  Could not find CPPABI_LIBRARY using the following names: c++abi
Call Stack (most recent call first):
  CMakeLists.txt:445 (include)


-- Configuring incomplete, errors occurred!
See also "/usr/Open3D/build/CMakeFiles/CMakeOutput.log".
See also "/usr/Open3D/build/CMakeFiles/CMakeError.log".

**Comment by a78239636** [comment]
I also meet it.  I'm using centos7.4, try to compile Open3d from source.  
Although, I  use "git submodule update --init --recursive " to init submodule,  Filament dictory exist only two cmake file.

Eroor: 
CMake Error at 3rdparty/find_dependencies.cmake:917 (find_library):
Could not find CPPABI_LIBRARY using the following names: c++abi

**Comment by qsisi** [comment]
I meet the same error too,tried to build from source on ubuntu 16.04.

CMake Error at 3rdparty/find_dependencies.cmake:934 (find_library):
Could not find CPPABI_LIBRARY using the following names: c++abi
Call Stack (most recent call first):
CMakeLists.txt:445 (include)

**Comment by HananiJia** [comment]
I meet the same error too,tried to build from source on ubuntu 16.04

-- Filament is located at /home/code/Open3D/build/filament/src/ext_filament
CMake Error at 3rdparty/find_dependencies.cmake:934 (find_library):
  Could not find CPPABI_LIBRARY using the following names: c++abi
Call Stack (most recent call first):
  CMakeLists.txt:448 (include)

**Comment by HananiJia** [comment]
> I meet the same error too,tried to build from source on ubuntu 16.04.
> 
> CMake Error at 3rdparty/find_dependencies.cmake:934 (find_library):
> Could not find CPPABI_LIBRARY using the following names: c++abi
> Call Stack (most recent call first):
> CMakeLists.txt:445 (include)



I tried the following usage and it looks like it might work
sudo apt-get install  libc++-7-dev
sudo apt-get install  libc++abi-7-dev
or libc++-8-dev  libc++abi-8-dev

**Comment by reyanshsolis** [comment]
> > I meet the same error too,tried to build from source on ubuntu 16.04.
> > CMake Error at 3rdparty/find_dependencies.cmake:934 (find_library):
> > Could not find CPPABI_LIBRARY using the following names: c++abi
> > Call Stack (most recent call first):
> > CMakeLists.txt:445 (include)
> 
> I tried the following usage and it looks like it might work
> sudo apt-get install libc++-7-dev
> sudo apt-get install libc++abi-7-dev
> or libc++-8-dev libc++abi-8-dev

Thanks. This resolves the issue of `Could not find CPPABI_LIBRARY using the following names: c++abi`.
@aycameric we support cmake >= 3.18. 

@sanskar107 may we close this issue?
