### ISSUE TITLE
open3d.geometry.Geometry3D.translate(relative=False) using the mesh origin instead of center

### ISSUE THREAD

**Issue by EllingEye** [isl-org/Open3D#2569]
When you load a new mesh and visualize it, the mesh is placed so that its own coordinate system origin is placed at origin of the viewer. However, when using translate(relative=False) the center of the mesh is used instead. 

I would like the possibility to keep using the mesh's own origin when placing the object with translate(relative=False)
For some applications we place the origin of the mesh (i.e. the gripping point of a robot gripper) in a way that make the mesh more user friendly later on. It would be easier if we didn't have to keep track of the offset between this point and the center of the mesh while rotating and scaling and that this information where incorporated in open3d.

**Comment by reyanshsolis** [comment]
I think you can keep a track of the offset easily, in very few lines of code. I am closing this issue for now, feel free to reopen, if there is any related requests/bugs.
