### ISSUE TITLE
simplify_quadric_decimation works horrible

### ISSUE THREAD

**Issue by mganglb** [isl-org/Open3D#2581]
Hello, i struggle with the "simplify_quadric_decimation" method. And i think one of the reason is the use of "subdivide_midpoint".
_____

**Describe the bug**
i am using simplify_quadric_decimation on a triangle mesh what is 
*   created by create_box()
*   up sampled by subdivide_midpoint()

**Expected behavior**
a better result, then i get. -> img2 right picture
On **Img1** you can see that open3d, as also meshlab struggle to apply the algorithm.

On the meshes, seen on **img2**, first an random rotation got applied. That seems to fix the problems for meshlab, but open3d still behaves badly. 

**Additional context**
*  i am not an Expert in that matter
*  possibly this is the expected behaviour. But specially after the rotation mehslab performs way better

**Environment**
- Operating system: Windows
- Python version: (e.g. Python 3.8)
- Open3D version: 0.11.0
- How did you install Open3D?: pip

**IMG1**
![no_rotation](https://user-images.githubusercontent.com/43035491/98262384-d899c680-1f85-11eb-8816-578fbbeb66f1.png)
**IMG2**
![rotation](https://user-images.githubusercontent.com/43035491/98262397-dcc5e400-1f85-11eb-893d-2cbf168fdee5.png)

**Comment by benjaminum** [comment]
We added a different algorithm in #5199
