### ISSUE TITLE
Ability to initialize a TSDFVolume with an existing TSDF in Python

### ISSUE THREAD

**Issue by meder-yembo** [isl-org/Open3D#2583]
**Is your feature request related to a problem? Please describe.**

I would like to be able to provide initial values to a TSDFVolume or ScalableTSDFVolume via the Python interface. There is currently no way to do it.

Additionally, the options to specify non-uniform dimensions would be nice as well. In many cases, I may want a voxel grid over a rectangular region instead of a cube.

**Describe the solution you'd like**

A constructor that accepts a numpy ndarray that would specify the dimensions of the voxel grid and the TSDF values within. Additionally this would accept the truncation value and voxel size as it already does.

**Describe alternatives you've considered**

Not clear what alternative would solve this from the end-user side/

**Additional context**

This way, open3d can be used in conjunction with the multitude of deep (T)SDF papers that regress a (truncated) signed distance function with some network. These outputs could be wrapped in a Open3D data type and then a mesh could be extracted, depth images could be rendered, or some other further processing could be done.

**Comment by theNded** [comment]
We are one step closer after #2710 is merged. The underlying scalable TSDF is now stored as a Tensor buffer that can be indexed via a hashmap. Directly assigning voxel values will be available in the next phase.

**Comment by theNded** [comment]
I/O from npz files is supported in the `VoxelBlockGrid`. See the [tutorial](http://www.open3d.org/docs/latest/tutorial/t_reconstruction_system/voxel_block_grid.html) for further instructions.
