### ISSUE TITLE
change the definition of  the geometry::pointcloud 

### ISSUE THREAD

**Issue by ZOUYIyi** [isl-org/Open3D#2587]
I changed the definition of the geometry::pointcloud by add two variable :   vector<int>   ind1   ;  vector<int>  ind2
and I rebuild it .
but I find that some of the function works still good and some not 
for example :
geometry::pointcloud  p_0 , p_1;
auto   pointcloud = p_0 + p_1  ;
it works well in debug mode ,but always fails in release mode ,and it  throws  "std::bad_alloc"
anyboyknow what happened ? please ....

**Comment by sanskar107** [comment]
@ZOUYIyi can you share your code where you made changes?

**Comment by ZOUYIyi** [comment]
![捕获](https://user-images.githubusercontent.com/44751133/98691749-548e7700-23a9-11eb-8c4e-2efad70ed38d.PNG)
all I need is to add these two variable and make everything ok

**Comment by theNded** [comment]
Please override the constructor and operator+ accordingly when you customize a class.
