### ISSUE TITLE
invalid tetra in TetraMesh

### ISSUE THREAD

**Issue by alddiaz** [isl-org/Open3D#2597]
alpha = 0.02
tetra_mesh, tetra_pt_map = open3d.geometry.TetraMesh.create_from_point_cloud(pcd)
---> alpha_shape = open3d.geometry.TriangleMesh.create_from_point_cloud_alpha_shape(pcd, alpha, tetra_mesh, tetra_pt_map)

RuntimeError: [Open3D ERROR] [CreateFromPointCloudAlphaShape] invalid tetra in TetraMesh

**Comment by colinlaney** [comment]
Yes, [there is](https://github.com/intel-isl/Open3D/issues/1829#issuecomment-628456177) the problem.
