### ISSUE TITLE
Importing open3d after wandb causes a ModuleNotFoundError: No module named 'prompt_toolkit.formatted_text'

### ISSUE THREAD

**Issue by rankela** [isl-org/Open3D#2599]
**Describe the bug**
Importing open3d after importing wandb (weights and biases) raises a ModuleNotFoundError:
`Traceback (most recent call last):  
  File "<stdin>", line 1, in <module>  
  File "/usr/local/lib/python3.8/dist-packages/open3d/__init__.py", line 95, in <module>  
    from .j_visualizer import *  
  File "/usr/local/lib/python3.8/dist-packages/open3d/j_visualizer.py", line 27, in <module>  
    import ipywidgets as widgets  
  File "/usr/local/lib/python3.8/dist-packages/ipywidgets/__init__.py", line 23, in <module>  
    from IPython import get_ipython  
  File "/usr/local/lib/python3.8/dist-packages/IPython/__init__.py", line 56, in <module>  
    from .terminal.embed import embed  
  File "/usr/local/lib/python3.8/dist-packages/IPython/terminal/embed.py", line 16, in <module>  
    from IPython.terminal.interactiveshell import TerminalInteractiveShell  
  File "/usr/local/lib/python3.8/dist-packages/IPython/terminal/interactiveshell.py", line 21, in <module>  
    from prompt_toolkit.formatted_text import PygmentsTokens  
ModuleNotFoundError: No module named 'prompt_toolkit.formatted_text'`  

Importing open3d first and then wandb works as expected

**To Reproduce**

1. pip install wandb (assuming present open3d)
2. python3 -c 'import wandb; import open3d'
3. See error above

**Expected behavior**
Import order should not influence the import success, it should be possible to import open3d regardless of any libraries imported before

**Environment (please complete the following information):**

- Operating system: (e.g. OSX 10.15, Ubuntu 18.04, Windows 10 64-bit)
- Python version: 3.8.5
- Open3D version: 0.11.1
- Is this remote workstation?: No
- How did you install Open3D?: pip
- ipython version: 7.17
- Compiler version (if built from source): /

**Additional context**
This occured in a codebase after bumping our versions of python and open3d to latest, we were several versions back for both (pyhthon 3.6 and open3d 0.8.0 if I recall correctly, but I might be wrong).

**Comment by sanskar107** [comment]
`wandb` comes with a very older version of `prompt_toolkit==1.0.15`, whereas some Open3D dependencies (`jupyter-console`, `ipython`) requires newer versions `prompt_toolkit>=2.0.0`.
Even if you have latest version of `prompt_toolkit` installed, importing `wandb` first exposes the internal older version which causes this issue.
If you want to work with both `open3d` and `wandb`, workaround is to import open3d first.

**Comment by yxlao** [comment]
Looks like the issue comes from `j_visualizer.py`. We have refactored the Jupyter support. See: http://www.open3d.org/docs/latest/tutorial/visualization/web_visualizer.html for details.
