### ISSUE TITLE
Versioning problem: 0.11 is considered compatible with 0.10 but does not have open3d.registration

### ISSUE THREAD

**Issue by jackjansen** [isl-org/Open3D#2620]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
I have code that depends on `open3d.transformation.TransformationPointToPoint`. This functionality has moved to a different place between 0.10 and 0.11.

But if I `pip install open3d~=0.10` it will currently install 0.11.X, which is incompatible.

**To Reproduce**

1. `pip install open3d~=0.10`
2. run code that depends on 0.10 features that have disappeared in 0.11
3. See error

**Expected behavior**

A compatible version would be installed, probably 0.10.X for the highest value of X.

- Operating system: Windows 10 (but shouldn't make a difference)
- Python version: 3.7
- Open3D version:
- Is this remote workstation?: yes and no
- How did you install Open3D?: pip
- Compiler version (if built from source): not applicable

**Additional context**

**Comment by sanskar107** [comment]
@jackjansen `pip install` takes first major version into account, which is currently `0.*` for Open3D.
 `open3d~=0.10` installs a version `>=0.10, ==0.*`. and in this case, it is `0.11.2`

@yxlao is it possible for us to do something about it?

**Comment by jackjansen** [comment]
Indeed. pip version specifiers only work well if you use semantic versioning (increase major version for api-incompatibilities, minor version for backward-compatible api changes, micro version otherwise).

Also, as an outsider I would consider Open3D quite stable enough to leave the `0.x` versions. I've been using it for quite some time, and I'm not the only one (more than 3000 stars...). Maybe you should consider that is good enough to leave alpha and go for a 1.0 release?
