### ISSUE TITLE
select_by_index doesn't work for meshes with multiple textures

### ISSUE THREAD

**Issue by nickponline** [isl-org/Open3D#2621]
[Open3D WARNING] [SelectByIndices] This mesh contains triangle uvs that are not handled in this function:
```
clusters, _, _ = mesh.cluster_connected_triangles()

indices = []
for index, cluster in enumerate(clusters):
    if cluster == 0:
        indices.append(index)

mesh = mesh.select_by_index(indices)
```

**Comment by benjaminum** [comment]
@nickponline This seems to be a feature request, right? Please let me know then I will reopen and add the corresponding label.

**Comment by nickponline** [comment]
@benjaminum This is an attempt to work around this limitation: https://github.com/isl-org/Open3D/issues/1870

**Comment by benjaminum** [comment]
@nickponline Just to clarify, the mesh created by `select_by_index` should preserve the `triangle_uvs` field.

**Comment by letatanu** [comment]
Any updates on this one? I'm trying to crop a mesh with multiple textures. It can drop the mesh but the texture. It would be nice if we have this function updated.

**Comment by nickponline** [comment]
@letatanu Doesn't seem like it, I'm happy to sponsor development of this feature, but not getting any responses, I tried on Discord too: https://github.com/isl-org/Open3D/issues/1870

**Comment by benjaminum** [comment]
@nickponline Contributions like improving this functions are very welcome.

**Comment by benjaminum** [comment]
The problem is that the function only preserves vertex attributes like normals and colors but ignores everything else like textures and texture coordinates. See https://github.com/isl-org/Open3D/blob/c9035ece2f266e46a5e6bb06fef36bff69b4f856/cpp/open3d/geometry/TriangleMesh.cpp#L1631

**Comment by letatanu** [comment]
> @letatanu Doesn't seem like it, I'm happy to sponsor development of this feature, but not getting any responses, I tried on Discord too: #1870

I found another way through Blender that works on it. Blender can crop and export the mesh with multiple texture.

**Comment by nickponline** [comment]
I was able to work around needing with `mesh.triangle_material_ids = o3d.utility.IntVector(..)` it's a workaround for:
https://github.com/isl-org/Open3D/issues/1870

But doesn't solve whatever the issue is with mesh not showing up in OffscreenRenderer: https://github.com/isl-org/Open3D/issues/5049

**Comment by benjaminum** [comment]
What does the workaround do? Do you copy the missing information after cropping to the new mesh?
