### ISSUE TITLE
open3d::io::TriangleMeshIO::AddTrianglesByEarClipping fails in triangulating concave polygon

### ISSUE THREAD

**Issue by 2012312055** [isl-org/Open3D#2632]
**Describe the bug**
TriangleMeshIO::AddTrianglesByEarClipping fails in triangulating concave polygon

**To Reproduce**
auto poly = std::make_shared< TriangleMesh >();
std::vector< unsigned int > indices;

poly->vertices_.resize(5);
indices.resize(5);

Eigen::Vector3d v1(0., 0., 0.);
Eigen::Vector3d v2(0., 2., 0.);
Eigen::Vector3d v3(1., 1., 0.);
Eigen::Vector3d v4(2., 2., 0.);
Eigen::Vector3d v5(2., 0., 0.);

poly->vertices_[0] = v1;
poly->vertices_[1] = v2;
poly->vertices_[2] = v3;
poly->vertices_[3] = v4;
poly->vertices_[4] = v5;
indices[0] = 0;
indices[1] = 1;
indices[2] = 2;
indices[3] = 3;
indices[4] = 4;

AddTrianglesByEarClipping(*poly, indices); ←return false

**Environment (please complete the following information):**
- Operating system: Windows 10 64-bit
- Open3D version: v0.11.2
- How did you install Open3D?: build from source
- Compiler version (if built from source): VS2019

**Comment by benjaminum** [comment]
This issue has been fixed in #4609
