### ISSUE TITLE
How can I get the timestamp out of a point cloud?

### ISSUE THREAD

**Issue by Me817** [isl-org/Open3D#2634]
Hello,

 I need the timestamp of a point cloud to identify the specific point cloud. I already looked it up in the documentation but I did not find anything helpful. Can anybody tell me how to get the timestamp for a specific point cloud?#

Thank you in advance.

**Comment by sanskar107** [comment]
`Pointcloud` class does not have any attribute for storing timestamp. You can consider creating a tuple of pcd object and timestamp.
