### ISSUE TITLE
How to use cv::Mat create Open3d Image in C++ API ?

### ISSUE THREAD

**Issue by joy-yjl** [isl-org/Open3D#2645]
I want to create a Open3D Image (open3d::geometry::Image) with cv::Mat (or unchar* ).And the image is 16 bit depth image.  I did not find the interface in the c++ api doc. Could somebody help me?

**Comment by ssheorey** [comment]
Hi @joy-yjl you can use this to convert from OpenCV Mat to open3d::t::geometry::Image:
```c++
int main(int argc, char *argv[]) {
    fmt::print("Reading image {}\n", argv[1]);
    // Read an image without an conversion with OpenCV
    cv::Mat im_cv = cv::imread(argv[1], cv::IMREAD_UNCHANGED);
    if (im_cv.empty()) {
        open3d::utility::LogError("Could not open image!");
    }
    fmt::print("rows={}, cols={}, channels={}, depth={}\n", im_cv.rows,
               im_cv.cols, im_cv.channels(), im_cv.depth());
    // Convert OpenCV depth to Open3D Dtype
    open3d::core::Dtype dt;
    switch (im_cv.depth()) {
        case CV_8U:
            dt = open3d::core::Dtype::UInt8;
            break;
        case CV_16U:
            dt = open3d::core::Dtype::UInt16;
            break;
        case CV_32F:
            dt = open3d::core::Dtype::Float32;
            break;
        case CV_64F:
            dt = open3d::core::Dtype::Float64;
            break;
        default:
            open3d::utility::LogError("See docs for other element Dtypes.");
    }
    // Create a blob for externally managed memory with no-op deleter
    auto pblob = std::make_shared<open3d::core::Blob>(
            open3d::core::Device(), im_cv.data, [](void *) {});
    // Create tensor
    open3d::core::Tensor data_o3d(
            /*shape=*/{im_cv.rows, im_cv.cols, im_cv.channels()},
            /*stride in elements (not bytes)*/
            {int64_t(im_cv.step[0] / im_cv.elemSize1()),
             int64_t(im_cv.step[1] / im_cv.elemSize1()), 1},
            im_cv.data, dt, pblob);
    open3d::t::geometry::Image im_o3d(data_o3d);
    // If you need the Eigen based legacy Image:
    // open3d::geometry::Image im_o3d_e = im_o3d.ToLegacy();
    fmt::print("rows={}, cols={}, channels={}, dtype={}\n", im_o3d.GetRows(),
               im_o3d.GetCols(), im_o3d.GetChannels(),
               im_o3d.GetDtype().ToString());
    open3d::t::io::WriteImage("output_image.png", im_o3d);
}

```

**Comment by manhha1402** [comment]
> Hi @joy-yjl you can use this to convert from OpenCV Mat to open3d::t::geometry::Image:
> 
> ```c++
> int main(int argc, char *argv[]) {
>     fmt::print("Reading image {}\n", argv[1]);
>     // Read an image without an conversion with OpenCV
>     cv::Mat im_cv = cv::imread(argv[1], cv::IMREAD_UNCHANGED);
>     if (im_cv.empty()) {
>         open3d::utility::LogError("Could not open image!");
>     }
>     fmt::print("rows={}, cols={}, channels={}, depth={}\n", im_cv.rows,
>                im_cv.cols, im_cv.channels(), im_cv.depth());
>     // OpenCV use BGR channels, while Open3D uses RGB. Perform a conversion
>     // if the channel order is important for your application.
>     if (im_cv.channels()==3) {
>         cv::cvtColor(im_cv, im_cv, cv::COLOR_BGR2RGB);
>     }
>     // Convert OpenCV depth to Open3D Dtype
>     open3d::core::Dtype dt;
>     switch (im_cv.depth()) {
>         case CV_8U:
>             dt = open3d::core::Dtype::UInt8;
>             break;
>         case CV_16U:
>             dt = open3d::core::Dtype::UInt16;
>             break;
>         case CV_32F:
>             dt = open3d::core::Dtype::Float32;
>             break;
>         case CV_64F:
>             dt = open3d::core::Dtype::Float64;
>             break;
>         default:
>             open3d::utility::LogError("See docs for other element Dtypes.");
>     }
>     // Create a blob for externally managed memory with no-op deleter
>     auto pblob = std::make_shared<open3d::core::Blob>(
>             open3d::core::Device(), im_cv.data, [](void *) {});
>     // Create tensor
>     open3d::core::Tensor data_o3d(
>             /*shape=*/{im_cv.rows, im_cv.cols, im_cv.channels()},
>             /*stride in elements (not bytes)*/
>             {int64_t(im_cv.step[0] / im_cv.elemSize1()),
>              int64_t(im_cv.step[1] / im_cv.elemSize1()), 1},
>             im_cv.data, dt, pblob);
>     open3d::t::geometry::Image im_o3d(data_o3d);
>     // If you need the Eigen based legacy Image:
>     // open3d::geometry::Image im_o3d_e = im_o3d.ToLegacy();
>     fmt::print("rows={}, cols={}, channels={}, dtype={}\n", im_o3d.GetRows(),
>                im_o3d.GetCols(), im_o3d.GetChannels(),
>                im_o3d.GetDtype().ToString());
>     open3d::t::io::WriteImage("output_image.png", im_o3d);
> }
> ```

Hi @ssheorey ,
I tried to convert cv::cuda::GpuMat to open3d::t:geometry::Image and vice verse but wasn't successful. The converted open3d Image look weird. Below is my code for the conversion, could you have a look on it please?. Thank you
 ```
  const open3d::core::Device device("CUDA:0");
  cv::Mat rgb_img = cv::imread(dataset.color_files_[0][src_frame_id]);
  cv::cuda::GpuMat img;
  img.upload(rgb_img);
  auto rgbBlob = std::make_shared<open3d::core::Blob>(device, img.cudaPtr(), [](void*) {});
  auto rgb_tensor = open3d::core::Tensor(
      { rgb_img.rows, rgb_img.cols, rgb_img.channels() },
      { int64_t(rgb_img.step[0] / rgb_img.elemSize1()), int64_t(rgb_img.step[1] / rgb_img.elemSize1()), 1 },
      img.cudaPtr(), open3d::core::Dtype::UInt8, rgbBlob);
  open3d::t::geometry::Image o3d_img(rgb_tensor);
  open3d::t::io::WriteImage("o3d_image.png", o3d_img);
 ```
