### ISSUE TITLE
[Help wanted] How to seperate different plannar areas ?

### ISSUE THREAD

**Issue by xiaodongww** [isl-org/Open3D#2647]
I want to detect all planes in the point cloud using [pcd.segment_plane()](http://www.open3d.org/docs/release/tutorial/geometry/pointcloud.html#Plane-segmentation). The result do find a plane as follows. All **red** points are on the same plane. However, the plane contains multiple planar areas.  I want to separate them (i.e. the table's surface and sofa's surface should be two different planes). Also, the red points on the wall are not what I want.
![4DB4BFA27E1E2C5E883A0699BD30DC6D](https://user-images.githubusercontent.com/33693065/99770853-17fa1280-2b43-11eb-9ed5-3615771537b0.jpg)

![20738EF619357FA009A5C62417CCE784](https://user-images.githubusercontent.com/33693065/99770866-1e888a00-2b43-11eb-817c-e85b3e82ccd1.jpg)

Can I achieve this using Open3D? Any suggestion will be helpful.

BTW, please let me know if I was supposed to ask such questions elsewhere. 

Thanks a lot!

**Comment by HollowHeartNet** [comment]
Yes, it is possible. You should adjust the parameters accordingly and you might want to use the function within a while-loop (save the inliers and use the outliers as input for the next loop-step).
