### ISSUE TITLE
Set image files region of interest in Colormap Optimization

### ISSUE THREAD

**Issue by drperpen** [isl-org/Open3D#2712]
Hi,
I am reconstructing from 2d images in SideFX Houdini and was thinking in using your Open3D Colormap with my mesh to compare it with my Houdini's color assignment results. However, my 2d images files from the cameras are large (8K). In Houdini I deal with this by creating region of interest/bounding boxes on the images, as the area of interest rarely is higher than 15% of the whole frame (cameras are far)

Is there a way or would you consider to implement a way to set only the area you need from the image file?

Thanks!

**Comment by yxlao** [comment]
Yes, it is possible to automatically detect the regions of interest using an "adaptive anchor point" approach.  It is not included in the current `master` branch, but we do have some demo code. You may check this for your reference (though you might need to fix some build issues to get it to compile): https://github.com/intel-isl/Open3D/commit/2dd6a714efe6e255bac328c2a81259c032b6484a .

Here are the ideas:
1. Unified anchor points are placed in a square grid pattern over the image for image warping (`src/Core/ColorMap/ImageWarpingField.h`, the density is controlled by `number_of_vertical_anchors`.)
2. Only some of the grid cells contain the subjects, the anchor points associated with these grid cells receives non-zero warping field flow values
3. The rest of the anchor points does not contain the subject, thus their flow values are always zero
4. Now,
    - Original implementation: we consider all anchor points and build solve a linear system with a large matrix
    - "Adaptive anchor point" approach: only the anchor points associated with the activated grid cells are used to build a sparse matrix, and we solve the linear system with the sparse matrix

Given the same parameters, the results of both implementations are identical. However, the "adaptive anchor point" approach is significantly faster, which allows us to use finer grid cells (larger `number_of_vertical_anchors`) to achieve better results.

**Comment by drperpen** [comment]
Thank you for your answer. I will look into that!
