### ISSUE TITLE
generate point cloud with color information from mesh file(.obj)

### ISSUE THREAD

**Issue by Retia-development** [isl-org/Open3D#2726]
If I have a mesh file like .obj, is it possible to use an mtl file for the color information using open3D?

Currently in a project I am trying to add a form of meta data to pointclouds, I wanted to try to use the color for that.
However I thought to make it user friendly, instead of manually finding the right dots and coloring them (which I think is very hard since the pointcloud seems messy to me) To use the original obj file for the colors.
I tried vertex colors already, but our obj files don't have enough vertices for that. I use the sample_points_poisson_disk method to solve that issue.

my current test code looks like this
```
inbouwdoos_enkel = o3d.io.read_triangle_mesh("Models/test4.obj")
inbouwdoos_enkel.compute_vertex_normals()
nop = 3000
pc_source = inbouwdoos_enkel.sample_points_poisson_disk(nop)
o3d.visualization.draw_geometries([pc_source],
                                    point_show_normal=True,
                                    window_name="Source and Target")
```

**Comment by errissa** [comment]
@Retia-development The mtl file stores material properties which can include a limited set of color-related properties. Please see this for details: https://en.wikipedia.org/wiki/Wavefront_.obj_file#Material_template_library

If you are still trying to work through this issue, please feel free to reopen this issue.
