### ISSUE TITLE
open3d- Vulnerability issue in pyyaml@5.3.1 - snyk report

### ISSUE THREAD

**Issue by manasars** [isl-org/Open3D#2730]
The https://app.snyk.io/ reports a vulnerability issue in pyyaml@5.3.1  introduced through open3d.
PFA screenshot for the vulnerability reported.

- Operating system: Ubuntu 18.04
- Python version: Python 3
- Open3D version: 0.11.2
- Is this remote workstation?: No
- How did you install Open3D?: pip
- Compiler version (if built from source): NA

![image001](https://user-images.githubusercontent.com/44188718/101778444-de9d3d00-3b19-11eb-9beb-c6fb5d892e4b.png)

**Comment by ssheorey** [comment]
Thanks for reporting this. This is a known issue and we will need a fix from `pyyaml` for this:
https://github.com/yaml/pyyaml/issues/420

We would recommend users to manually inspect untrusted `yaml` configuration files before using them.
