### ISSUE TITLE
Unable to find the Open3D Viewer

### ISSUE THREAD

**Issue by Zumbalamambo** [isl-org/Open3D#2732]
I have installed the open3d viewer from the official website. However the installation is not found within the $HOME .local/share/applications . How can I launch the open3d viewer?

**Comment by yxlao** [comment]
@Zumbalamambo are you on Ubuntu 18.04 or 20.04?

**Comment by Zumbalamambo** [comment]
I'm on Ubuntu 20.0.4

**Comment by chuong98** [comment]
Me too, I am on Ubuntu 20.04. On terminal, I type "Open3D" but get error:
```
FEngine (64 bits) created at 0x7f14d8420010 (threading is enabled)
FEngine resolved backend: OpenGL
N5utils17PreconditionPanicE
in static filament::MaterialParser *filament::FMaterial::createParser(backend::Backend, const void *, size_t):513
reason: Material version mismatch. Expected 10 but received 7.
#0 /usr/local/share/Open3D/bin/Open3D(+0xa8d830) [0x55aafd60e830]
#1 /usr/local/share/Open3D/bin/Open3D(+0x9c8c41) [0x55aafd549c41]
#2 /usr/local/share/Open3D/bin/Open3D(+0x9c8a36) [0x55aafd549a36]
#3 /usr/local/share/Open3D/bin/Open3D(+0x39a33f) [0x55aafcf1b33f]
#4 /usr/local/share/Open3D/bin/Open3D(+0x39ae87) [0x55aafcf1be87]
#5 /usr/local/share/Open3D/bin/Open3D(+0x39cac2) [0x55aafcf1dac2]
#6 /usr/local/share/Open3D/bin/Open3D(+0x390a46) [0x55aafcf11a46]
#7 /usr/local/share/Open3D/bin/Open3D(+0x390a9d) [0x55aafcf11a9d]
#8 /usr/local/share/Open3D/bin/Open3D(+0x390b8d) [0x55aafcf11b8d]
#9 /usr/local/share/Open3D/bin/Open3D(+0x24b74e) [0x55aafcdcc74e]
#10 /usr/local/share/Open3D/bin/Open3D(+0x24bc8f) [0x55aafcdccc8f]
#11 /usr/local/share/Open3D/bin/Open3D(+0x221209) [0x55aafcda2209]
#12 /usr/local/share/Open3D/bin/Open3D(+0x206902) [0x55aafcd87902]
#13 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f14db8010b3]
terminate called after throwing an instance of 'utils::PreconditionPanic'
Aborted (core dumped)
```

**Comment by littlesaohuo** [comment]
> Me too, I am on Ubuntu 20.04. On terminal, I type "Open3D" but get error:
> 
> ```
> FEngine (64 bits) created at 0x7f14d8420010 (threading is enabled)
> FEngine resolved backend: OpenGL
> N5utils17PreconditionPanicE
> in static filament::MaterialParser *filament::FMaterial::createParser(backend::Backend, const void *, size_t):513
> reason: Material version mismatch. Expected 10 but received 7.
> #0 /usr/local/share/Open3D/bin/Open3D(+0xa8d830) [0x55aafd60e830]
> #1 /usr/local/share/Open3D/bin/Open3D(+0x9c8c41) [0x55aafd549c41]
> #2 /usr/local/share/Open3D/bin/Open3D(+0x9c8a36) [0x55aafd549a36]
> #3 /usr/local/share/Open3D/bin/Open3D(+0x39a33f) [0x55aafcf1b33f]
> #4 /usr/local/share/Open3D/bin/Open3D(+0x39ae87) [0x55aafcf1be87]
> #5 /usr/local/share/Open3D/bin/Open3D(+0x39cac2) [0x55aafcf1dac2]
> #6 /usr/local/share/Open3D/bin/Open3D(+0x390a46) [0x55aafcf11a46]
> #7 /usr/local/share/Open3D/bin/Open3D(+0x390a9d) [0x55aafcf11a9d]
> #8 /usr/local/share/Open3D/bin/Open3D(+0x390b8d) [0x55aafcf11b8d]
> #9 /usr/local/share/Open3D/bin/Open3D(+0x24b74e) [0x55aafcdcc74e]
> #10 /usr/local/share/Open3D/bin/Open3D(+0x24bc8f) [0x55aafcdccc8f]
> #11 /usr/local/share/Open3D/bin/Open3D(+0x221209) [0x55aafcda2209]
> #12 /usr/local/share/Open3D/bin/Open3D(+0x206902) [0x55aafcd87902]
> #13 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f14db8010b3]
> terminate called after throwing an instance of 'utils::PreconditionPanic'
> Aborted (core dumped)
> ```
I encountered the same problem, but my system is ubuntu18.04. Can anyone help me. .

**Comment by chuong98** [comment]
I updated the open3D to the lastest version 0.12.0) and the error is gone.

**Comment by littlesaohuo** [comment]
> I updated the open3D to the lastest version 0.12.0) and the error is gone.

I was using v0.12.0, but it also made the same error.

**Comment by littlesaohuo** [comment]
> > I updated the open3D to the lastest version 0.12.0) and the error is gone.
> 
> I was using v0.12.0, but it also made the same error.

I upgraded OpenGL to 4.6, open3d can now be used normally.

**Comment by reyanshsolis** [comment]
@bgilreath may you try clearing your browser's cache. It seems to be working for me.
