### ISSUE TITLE
Ball Pivoting Parameters

### ISSUE THREAD

**Issue by petrasvestartas** [isl-org/Open3D#2733]
Can someone explain me Ball Pivoting algorithm in terms of choosing right radii?

Below code estimates average density of the pointcloud and multiplies by some value.
Is there any rule how to define radius properly, should I choose one or many radius?

            auto distances = Open3DCloud->ComputeNearestNeighborDistance();
            float average = 0.0f;
            if (distances.size() != 0)
                average = std::accumulate(distances.begin(), distances.end(), 0.0) / distances.size();

            const std::vector<double> radii{ average*MeanScale}; 
            auto&  ballPivoting =  open3d::geometry:: TriangleMesh::CreateFromPointCloudBallPivoting( *Open3DCloud,radii);

In the image below the MeanScale is 1, then 1.5, 2,3,4,5.
![aaa](https://user-images.githubusercontent.com/18013985/101823277-ceda2480-3b2a-11eb-9834-bec8bce649f1.png)

**Comment by benjaminum** [comment]
The radii highly depends on the point distribution and there is unfortunately no rule that fits for all problems. Calculating the density is a good choice to estimate the radii. Hope this helps.
