### ISSUE TITLE
open3d version is 11.0.2,but report no module named open3d.visualization

### ISSUE THREAD

**Issue by chongxian** [isl-org/Open3D#2747]
I  import the open3d.visualization.gui as gui, but the error is that ModuleNotFoundError: No module named 'open3d.visualization'

Environment (please complete the following information)

- Operating system:  Windows 10 64-bit
- Python version: Python 3.6
- Open3D version: 11.0.2
- Is this remote workstation?: no
- How did you install Open3D?: pip

**Comment by yxlao** [comment]
Did you mean version `0.11.2`? It works for me on py3.6 and v0.11.2. 

```
❯ python
Python 3.6.12 |Anaconda, Inc.| (default, Sep  9 2020, 00:29:25) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import open3d.visualization.gui as gui
>>> gui
<module 'open3d.visualization.gui' from 'C:\\Users\\yixing\\miniconda3\\envs\\open3d36new\\lib\\site-packages\\open3d\\visualization\\gui\\__init__.py'>
>>> import open3d
>>> open3d.__version__
'0.11.2'
```

**Comment by Jake-zhi** [comment]
(o3d) 7590:~/3D/Open3D/examples/python$ python
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import open3d
>>> print(open3d.__version__)
0.10.0.0
>>> import open3d.visualization.gui as gui
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'open3d.visualization'
>>> 

the same error as mine, does it works, and how to make it succesed?

**Comment by ssheorey** [comment]
@chongxian @Jake-zhi Please try with the new release `v0.12.0` and let us know if you still have this issue.

**Comment by khatrishubham88** [comment]
@ssheorey  The issue is still present with v0.12.0

**Comment by ssheorey** [comment]
@khatrishubham88 sorry I could not reproduce this with v0.12 either (Windows 10) with these commands:
```
PS C:\Users\ssheorey> C:\Users\ssheorey\.pyenv\pyenv-win\versions\3.8.2\python.exe -m pip install open3d
....
PS C:\Users\ssheorey> C:\Users\ssheorey\.pyenv\pyenv-win\versions\3.8.2\python.exe
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import open3d.visualization.gui as gui
>>> gui
<module 'open3d.visualization.gui' from 'C:\\Users\\ssheorey\\.pyenv\\pyenv-win\\versions\\3.8.2\\lib\\site-packages\\open3d\\visualization\\gui\\__init__.py'>
```

Please install open3d in an empty virtual environment and ensure you are using the correct python executable.

**Comment by SergioDME** [comment]
Hi I have the same problem, how can I solve it?

**Comment by khatrishubham88** [comment]
@ssheorey I tried setting up a new virtual environment with python 3.7 and I am getting same issue again with v0.12. Is python3.7 still compatible with open3d v0.12? I get the same issue on ubuntu 18.04 as well.

**Comment by ssheorey** [comment]
@khatrishubham88 Python 3.6-3.8 is supported for Open3D v0.12. Please list the exact commands used to create the empty virtual environment, install Open3D and the output of `open3d.__version__` after importing it.

**Comment by khatrishubham88** [comment]
@ssheorey following is the output when I import the open3d

`
Python 3.7.5 (default, Feb 23 2021, 13:22:40)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import open3d
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shubhamkhatri/venv/lib/python3.7/site-packages/open3d/__init__.py", line 79, in <module>
    import open3d.visualization
ModuleNotFoundError: No module named 'open3d.visualization'
`

**Comment by theNded** [comment]
@khatrishubham88 as @ssheorey mentioned, this is usually an environment configuration issue. Please create a new virtual environment using e.g. conda, and install open3d again.

**Comment by MohamedEttaieb** [comment]
pip3 install open3d --user
