### ISSUE TITLE
Arcore 1.8 and later

### ISSUE THREAD

**Issue by moheydy** [isl-org/Open3D#2749]
In Arcore 1.8 and  Unity I can to save RGBD and RGB image in the one frame, this is possible to use of them to Reconstruction a 3d object?
The point here is that I can get just RGBD and RGB and no other anythings like intrinsic file

**Comment by Zumbalamambo** [comment]
@moheydy you can get the camera intrinsics directly from the [ARCore](https://developers.google.com/ar/reference/unity/class/GoogleARCore/Frame/CameraImage#imageintrinsics) which you could use to create an intrinsic file.

**Comment by theNded** [comment]
Thanks @Zumbalamambo for the answer. Issue closed for now.
