### ISSUE TITLE
【Texture Error】Texture loading and drawing error when using OBJ file

### ISSUE THREAD

**Issue by Hydrogenion** [isl-org/Open3D#2757]
**Describe the bug**
When I try to load and draw 3d mesh with texture, I meet this problem.
[figure 1](https://dataset-1253353217.cos.ap-beijing.myqcloud.com/1.png)
The figure 1 is a 3d mesh shown in MeshLab

[figure 2](https://dataset-1253353217.cos.ap-beijing.myqcloud.com/2.png)
The figure 2 is the same 3d mesh shown in Open3D. There is an error in the texture drawing. The texture is not shown correctly. 
Why is it? Cloud you help me! 

Thank you! 

**To Reproduce**
Here is my code.
```
import open3d as o3d
mesh = o3d.io.read_triangle_mesh('1.obj')
o3d.visualization.draw_geometries([mesh])
```

**Expected behavior**
The texture should looks the same as which in MeshLab.

**Environment (please complete the following information):**

- Operating system: Windows 10 64-bit
- Python version: Python 3.7
- Open3D version: 0.11
- Is this remote workstation?: no
- How did you install Open3D?: pip

**Comment by JohnHardline** [comment]
Same Problem!

**Comment by Hydrogenion** [comment]
> Same Problem!

I think the reason is the 'glTexParameteri' in TexturePhongShader.cpp and TextureSimpleShader.cpp

the source code use GL_CLAMP_TO_BORDER texture bind mode
```
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_BORDER);
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_BORDER);
```

It should be GL_REPEATE.
```
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_REPEAT);
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_REPEAT);
```

I think  GL_REPEATE should be right, I am still trying.

**Comment by marvinmouroum** [comment]
same problem, but using

`mesh = o3d.io.read_triangle_mesh('texturedMesh.obj',True)`

<img width="960" alt="example" src="https://user-images.githubusercontent.com/28195629/112058758-46bcdf80-8b5b-11eb-9cf3-3cb756ca556e.png">

**Comment by Abo-go** [comment]
Same problem, is there any way to set texture wrap mode?

**Comment by errissa** [comment]
It is not possible to set the texture wrap mode in the old visualizer. The new visualizer supports clamp, repeat and mirrored repeat.

**Comment by Abo-go** [comment]
> 
Thank you.
Is `O3DVisualizer` the new visualizer? Please tell me how to set wrap mode in it, I can't find any example.

**Comment by dufengit** [comment]
Did you fix this problem, or is there any workaround? I think i met the same problem: 
https://github.com/isl-org/Open3D/issues/6506
