### ISSUE TITLE
Send data type geometry::PointCloud from C# to DLL C++

### ISSUE THREAD

**Issue by engineer-johntran** [isl-org/Open3D#2761]
I have problem with data type. How can we exchange data between a C # application and a C ++ DLL containing Open3d ?
I have created a self-defined data type to send data, but when using the Open3D library the conversion to the library's data type, the conversion takes too long (over 1 million points ). Now I want to use the data type of the library to exchange data (not through an intermediate type) is it?
*conversion code:*

       ` std::shared_ptr<geometry::PointCloud> source_pcd(new geometry::PointCloud);
        std::shared_ptr<geometry::PointCloud> target_pcd(new geometry::PointCloud);
        std::shared_ptr<geometry::PointCloud> source, target;
        std::shared_ptr<registration::Feature> source_fpfh, target_fpfh;
        
        TFL::TFL_PointXYZ point_tfl;
        source_pcd->points_.resize(size);
        source_pcd->colors_.resize(size);

        target_pcd->points_.resize(mResult->size());
        target_pcd->colors_.resize(mResult->size());

        for (int i = 0; i < size; i++)
        {
            source_pcd->points_[i] = Eigen::Vector3d(
                                            color_point_cloud_source->x, 
                                            color_point_cloud_source->y, 
                                            color_point_cloud_source->z);

            source_pcd->colors_[i] = Eigen::Vector3d(
                                            color_point_cloud_source->r, 
                                            color_point_cloud_source->g, 
                                            color_point_cloud_source->b);
            color_point_cloud_source++;
        }

        for (int i = 0; i < mResult->size(); i++)
        {
            target_pcd->points_[i] = Eigen::Vector3d(
                                            mResult->at(i).x,
                                            mResult->at(i).y,
                                            mResult->at(i).z);
            target_pcd->colors_[i] = Eigen::Vector3d(
                                            mResult->at(i).r,
                                            mResult->at(i).g,
                                            mResult->at(i).b);
        } `

**Comment by ssheorey** [comment]
@benjaminum Would the RPC functionality help here?

**Comment by petrasvestartas** [comment]
We actually wrote c# wrappers it is not so difficult. 

For sure the main bottleneck is data transfer back and forth between c# and c++ and back to c#. You are reading 4 times the same point list.. In my case I do this using flat double array. I am curious to know if there is a faster way?

**Comment by ssheorey** [comment]
I think you are looking for zero copy C# wrappers for the C++ geometry data types. I don't believe we can help with that since we don't support C#. You'll need a way to ensure that C# can access the C++ data layout.
