### ISSUE TITLE
Build with debug symbols

### ISSUE THREAD

**Issue by myFree** [isl-org/Open3D#2774]
**Describe the bug**

I've been unable to track down my mistake - although I'm sure this is a setup issue on my side.

I am connecting to a container; and mounting the code in the same directory as on the host PC:
-v /home/brent/repos/Open3D:/home/brent/repos/Open3D

I've built the code in the container; and am trying to launch and debug an executable via vscode. The executable launches; but whenever I set a breakpoint it goes clear and I get the hover over message: module containing this breakpoint has not yet loaded

**To Reproduce**

 in the container I am running
1. cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/home/brent/apps/Open3D ..
2. make -j$(nproc)

**Expected behavior**
I would like to be able to set breakpoints and hit them

I raised a ticket with vscode; which has additional details https://github.com/microsoft/vscode-cpptools/issues/6658

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:43:50.597Z)
OS version: Linux x64 5.4.0-54-generic snap
Remote OS version: Linux x64 5.4.0-54-generic

System Info
|Item|Value| |---|---| |CPUs|AMD Ryzen Threadripper 3960X 24-Core Processor (48 x 2200)| |GPU Status|2d_canvas: unavailable_software
flash_3d: disabled_software
flash_stage3d: disabled_software
flash_stage3d_baseline: disabled_software
gpu_compositing: disabled_software
multiple_raster_threads: enabled_on
oop_rasterization: disabled_off
opengl: disabled_off
protected_video_decode: disabled_off
rasterization: disabled_software
skia_renderer: enabled_on
video_decode: disabled_software
vulkan: disabled_off
webgl: unavailable_software
webgl2: unavailable_software| |Load (avg)|1, 1, 1| |Memory (System)|62.75GB (20.40GB free)| |Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 205183f6-0566-4829-8349-b40996aca137| |Screen Reader|no| |VM|0%| |DESKTOP_SESSION|ubuntu| |XDG_CURRENT_DESKTOP|Unity| |XDG_SESSION_DESKTOP|ubuntu| |XDG_SESSION_TYPE|x11|

**Comment by ssheorey** [comment]
Can you try running the code with `gdb` inside the container? Do breakpoints work?

**Comment by myFree** [comment]
Yes in the container; I am able to hit a breakpoint if I launch the executable with gdb directly

```
root@f521657f69ae:/home/brent/repos/Open3D/build/bin/examples# gdb Visualizer                                                                    
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
Type "apropos word" to search for commands related to "word"...
Reading symbols from Visualizer...
(gdb) 
(gdb) b main
Breakpoint 1 at 0x13ad52
(gdb) info b
Num     Type           Disp Enb Address            What
1       breakpoint     keep y   0x000000000013ad52 <main>
(gdb) run pointcloud /home/brent/repos/Open3D/examples/test_data/fragment.ply
Starting program: /home/brent/repos/Open3D/build/bin/examples/Visualizer pointcloud /home/brent/repos/Open3D/examples/test_data/fragment.ply
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, 0x000055555568ed52 in main ()
(gdb) where
#0  0x000055555568ed52 in main ()
```

**Comment by ssheorey** [comment]
Closing this issue. This looks like a VS Code issue since gdb breakpoints work.
