### ISSUE TITLE
Color map Optimization for stationary cameras

### ISSUE THREAD

**Issue by chunduri11** [isl-org/Open3D#2775]
Hi @yxlao @qianyizh @syncle 
Color map Optimization implementation(CMO) gives very good 3D texture, thanks for implementation.

The CMO is assumes that the camera is a moving camera and tries to optimize camera pose on every frame.(This is my understanding from the paper)

If we know that the **cameras are stationary**, do we still need to optimize the CMO for camera pose(T) for every frame.
I understand that we still need to optimize for non-rigid alignment(F) and Auxiliary color variable(C) terms.

Thanks

**Comment by yxlao** [comment]
For stationary cameras in a studio setting, we still found the rigid optimization (for camera poses) to be useful. This is because there may be some errors in camera calibration, and the rigid optimization helps further refine the camera poses. 

If we know the exact camera poses (e.g. in a synthetic dataset), we might be able to skip the rigid optimization.

**Comment by chunduri11** [comment]
Thanks for the quick reply, your inputs are very useful to me.

For rigid optimization CMO optimizes T(extrinsic matrix) and C(auxiliary variable).

Since we do not know the exact camera pose(T), rigid optimization is still useful. 

In the case of stationary cameras, we don't have to optimize for camera pose for every image in the video, because the cameras are stationary. 
**
Is it possible we find through optimization, correct camera pose(T) once and use it for the entire video?
**
**
With this we optimize for camera pose once and not optimize for camera pose on every Image.
**
Is this a valid point.

**Comment by theNded** [comment]
@yxlao has addressed the issue. Even the cameras poses are stationary and fixed, their poses could be subject to minor disturbance. It is necessary to optimize them along with the color map for a better consistency.
