### ISSUE TITLE
Problems with Sampling Rate

### ISSUE THREAD

**Issue by Me817** [isl-org/Open3D#2793]
Hello, 

**Describe the bug**
I recorded a mkv-file with the [azure_kinect_recorder.py ](https://github.com/intel-isl/Open3D/blob/master/examples/python/reconstruction_system/sensors/azure_kinect_recorder.py) with the `default_config.json`: that means a sampling rate of 30 fps. The length of the video is 57 seconds (`"stream_length_usec" : 57000011`). If I understand it right I would have 57x30=1710 frames in this mkv-file. But I only get 394 color and depth images and also 394 point clouds. How cloud that be?

**To Reproduce**
1. Record with the `azure_kinect_recorder.py` without giving a specific config-file using the `default_config.json`.
2. Run `python path/to/azure_kinect_mkv_reader.py --input config_nfov_record.mkv --output frames`
3. Get only 394 jpg and png files but the streamlength is 57 seconds. This is a sampling rate of 6.9123 (394/57=6,9123).

**Expected behavior**
I would expect that I get 1710 jpg and 1710 png files and out of them 1710 pcd files if I have a stream length of 57 seconds and a sampling rate of 30 fps. Does `azure_kinect_recorder.py` sample with 30 fps if it is configured in the `default_config.json`? How can I achieve a sampling rate of 30 fps?

**Screenshots**
![grafik](https://user-images.githubusercontent.com/56630682/102725022-0e1b2900-4314-11eb-91af-06cfe7355401.png)
![grafik](https://user-images.githubusercontent.com/56630682/102725380-8c78ca80-4316-11eb-85af-8dd497b6c11f.png)
![grafik](https://user-images.githubusercontent.com/56630682/102725328-3b68d680-4316-11eb-97b6-c4633c2c3831.png)

**Environment (please complete the following information):**

- Operating system: Windows 10 64-bit
- Python version: Python 3.7
- Open3D version: 0.10.0
- Is this remote workstation?: no
- How did you install Open3D?: pip
- Azure Kinect SDK version: v1.4.1
- Compiler version (if built from source): /

**Additional context**
Why are the timestamps of the color and depth respektively the point cloud not equidistant? Bewteen the first and the second point cloud is a difference of 66666 usec, between the second and the third 133323 usec, and between the third and the fourth 266689 usec. Between the last and second last 133334 usec and between the second last and the point cloud before 100011 usec. But why?

I would be very thankful for a hint what I can do.
Thank you in advance.

**Comment by ssheorey** [comment]
Hi @Me817 the frame rate of the received data also depends on the CPU and system load. With the same settings on the same system, what do you get directly with the Kinect SDK (`k4arecorder.exe`)?

**Comment by ssheorey** [comment]
Closing due to lack of response. Please reopen if you would like to investigate this further.
