### ISSUE TITLE
Calculating corresponding point coordinates for a pixel

### ISSUE THREAD

**Issue by ozgucbertug** [isl-org/Open3D#2799]
I'm currently trying to isolate certain pixels' point coordinates from a MKV recorded using an Azure Kinect camera. I've checked the documentation and it says that each point coordinates are calculated using:
```
z = d / depth_scale
x = (u - cx) * z / fx
y = (v - cy) * z / fy
```
However, when I try to access the value of a pixel in the depth image I get values as shown below:
```
65180
65211
65195
65163
65000
65029
65013
64988
65037
65066
65050
65023
65219
65248
65232
65202
```
My question is, whether there is a function that would allow me to isolate individual points from an RGB-D image, given corresponding pixel (u,v) coordinates. If not, is there a quick way to convert the values I've posted above to meters etc.?

**Comment by ssheorey** [comment]
Do the values computed with the intrinsic formula match what you expect? The depth image pixel values are the `d` values in the formula.

**Comment by ozgucbertug** [comment]
Sorry for my late response. I haven't been able to take a look at my code until now. 

The list of values given in my previous post belongs to points with significantly different Z values once I generate a point cloud from the depth image using the depth_scale value of 1 (which gives me distance values in mm). I'm not sure what I'm missing here.

**Comment by ssheorey** [comment]
Can you post the actual depth image? Specific pixels may have [invalid values from the sensor](https://docs.microsoft.com/en-us/azure/kinect-dk/depth-camera#invalidation).

**Comment by theNded** [comment]
The depth scale should be 1000.0 (corresponding to meter) for Azure Kinect. Closed for now.
