### ISSUE TITLE
Determinism of remove_radius_outlier

### ISSUE THREAD

**Issue by ValentinSteiner** [isl-org/Open3D#2830]
I expected `remove_radius_outlier` to always return the same output given the same input, however, the number of removed points changes.

To reproduce:

```
import numpy as np
import open3d

points = np.random.uniform(-0.4, 0.4, 3*50).reshape((-1,3))
pcd1 = open3d.geometry.PointCloud()
pcd1.points = open3d.utility.Vector3dVector(points)

for i in range(20):
    _, inlier_indices = pcd1.remove_radius_outlier(nb_points=1, radius=0.1)
    print("keeping %d points" % len(inlier_indices))

```

Sample output:

> keeping 13 points
> keeping 10 points
> keeping 12 points
> keeping 10 points
> ...

Environment 1:
- Operating system: Ubuntu 16.04
- Python 3.6
- Open3D version '0.11.2+e35069d'
- Is this remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): gcc 9.3.0

Environment 2:
- Operating system: Ubuntu 18.04
- Python version: Python 3.6
- Open3D version: '0.11.2'
- Is this remote workstation?: yes
- How did you install Open3D?: pip

**Comment by reyanshsolis** [comment]
Moving the discussion to #2344
