### ISSUE TITLE
the direction and side length of each axis of oriented_bounding_box

### ISSUE THREAD

**Issue by whenwherewhy** [isl-org/Open3D#2845]
Hello,
with function  get_oriented_bounding_box() we can get oriented_bounding_box of points.And the side length of each side is in "extent". However, I can't tell which side length corresponds to which direction. They appear to be arranged in order from largest to smallest, rather than corresponding to XYZ, etc. Is rotation matrix of oriented_bounding_box obtained from xyz? Can I get the rotation angle of the corresponding XYZ axis? Thanks a lot and happy new year.

**Comment by benjaminum** [comment]
You can get the orientation/rotation of the oriented bounding box from `obb.R`. The axes are ordered from largest to smallest principal component, i.e., the local x-axis (first row in `obb.R`) corresponds to the largest component.

**Comment by wxfred** [comment]
> You can get the orientation/rotation of the oriented bounding box from `obb.R`. The axes are ordered from largest to smallest principal component, i.e., the local x-axis (first row in `obb.R`) corresponds to the largest component.

Why re-order the axes? How to revert it to the original order?
