### ISSUE TITLE
Crash when running python sample scripts with GUI API under OS X

### ISSUE THREAD

**Issue by spadolini** [isl-org/Open3D#2851]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**

MacOS crashes when running sample code using Python GUI API

I have tried to run several scripts from "examples/python/gui/", e.g "vis-gui.py", "draw.py", "all-widgets.py" and always get the same crash: first a black screen for a few few seconds and then return to the login screen.

I have run several other sample py scripts, and those not using GUI functions work okay. 

**To Reproduce**
1.  Using VSCode 1.52.1
2. Conda environment active with open3d installation 
3. Click "Run File in Python Terminal"

Attached is a screen shot from the top of the OSX crash report.

**Expected behavior**
Running sample code

**Screenshots**
![image](https://user-images.githubusercontent.com/63147693/103547151-4db14b80-4ea4-11eb-8362-299ad1068f2d.png)

**Environment (please complete the following information):**

- Operating system: OSX 10.15
- Python version: Python 3.8.6
- Open3D version: 0.12
- Is this remote workstation?: no
- How did you install Open3D?: conda
- Compiler version (if built from source): n/a

**Additional context**

**Comment by ssheorey** [comment]
@spadolini Do you have an NVIDIA graphics card? Do you still have this error with the latest NVIDIA driver and Open3D (0.14.1)? Please provide details about your hardware and drivers. Also test with integrated graphics (Intel), i.e. with the NVIDIA GPU turned off and let us know if that works.

**Comment by ssheorey** [comment]
Please re-open if you still have this issue.
