### ISSUE TITLE
More filament materials and running mode required -- now transparent is not really transparent with view angle changed

### ISSUE THREAD

**Issue by 1939938853** [isl-org/Open3D#2890]
Hello,

I want to be able to see the object in a transparent object, see the two pics below. I tried both defaultLitTransparency and defaultUnlitTransparency for the transparent object,  but it seems no way to make it transparent in all the view angle. In half of the view aspects, it is totally not transparent.

I contacted Filament github issue "support", [they suggest me to try  "fade" blending mode](https://github.com/google/filament/issues/3410) . Could you please add this mode in the coming version release?

Thank you! 

Here is more material for the transparent object
`
 mat->base_color = { 119.0f / 255.0f, 119.0f / 255.0f, 119.0f / 255.0f, 0.2f };
    mat->point_size = 1.0;
    mat->base_metallic = 0.f;
    mat->base_roughness = 0.f;
    mat->base_reflectance = 0.0f;
    mat->base_clearcoat = 1.f;
    mat->base_clearcoat_roughness = 0.0f;
    mat->base_anisotropy = 0.0f;
    mat->thickness = 1.f;
    mat->transmission = 1.f;
    mat->absorption_color = { 0.5f, 0.5f, 0.5f };
    mat->absorption_distance = 0.f;
    //mat->shader = "defaultLitTransparency";
    mat->shader = "defaultUnlitTransparency";
    mat->name = "glass";
`

![image](https://user-images.githubusercontent.com/59957922/104150907-bedc8b80-53db-11eb-915b-254d5005d13c.png)
![image](https://user-images.githubusercontent.com/59957922/104150915-c4d26c80-53db-11eb-866a-e78ad1312b1a.png)

**Comment by 1939938853** [comment]
Unlike PCL, Open3D visualization::visualizer has no transparency (alpha) setting. 

Hopefully the new open3d::visualization::O3dVisualizer can add this setting. But now it is not really transparent. Only in some view angles.

**Comment by errissa** [comment]
As the Filament team noted what you are seeing there is a very bright specular highlight. The settings you are using for the material (0 roughness and a clearcoat of 1) are for highly shiny surfaces so it's not surprising that at just the right angle you see a very prominent specular reflection that blocks out everything else.

Please see the following script and associated screenshots for transparency. There are two options: `defaultLithTransparency` and `defaultLitSSR`. Only `defaultLitSSR` uses the `thickness`, `transmission`, `absorption` and `absoprtion_color` material parameters.

```
import open3d as o3d
import open3d.visualization as vis
import numpy as np

sphere = o3d.geometry.TriangleMesh.create_sphere(1.0)
sphere.compute_vertex_normals()
sphere.translate(np.array([0, 0, -3.5]))
box = o3d.geometry.TriangleMesh.create_box(2, 4, 4)
box.translate(np.array([-1, -2, -2]))
box.compute_triangle_normals()

mat_sphere = vis.rendering.MaterialRecord()
mat_sphere.shader = 'defaultLit'
mat_sphere.base_color = [0.8, 0, 0, 1.0]

mat_box = vis.rendering.MaterialRecord()
# mat_box.shader = 'defaultLitTransparency'
mat_box.shader = 'defaultLitSSR'
mat_box.base_color = [0.467, 0.467, 0.467, 0.2]
mat_box.base_roughness = 0.0
mat_box.base_reflectance = 0.0
mat_box.base_clearcoat = 1.0
mat_box.thickness = 1.0
mat_box.transmission = 1.0
mat_box.absorption_distance = 10
mat_box.absorption_color = [0.5, 0.5, 0.5]

geoms = [{'name': 'sphere', 'geometry': sphere, 'material': mat_sphere},
         {'name': 'box', 'geometry': box, 'material': mat_box}]
vis.draw(geoms)
```
With `defaultLitTransparency`:
![2022-01-04-131101_1024x768_scrot](https://user-images.githubusercontent.com/3722407/148104912-fd0900d7-7d2f-4cff-8491-cf63eb52591e.png)

With `defaultLitSSR`:
![2022-01-04-131143_1024x768_scrot](https://user-images.githubusercontent.com/3722407/148104936-284de1dc-27c5-4d0c-b29f-a73b42cc29f4.png)

**Comment by athinnappan** [comment]
Is there a way to do this using add_geometry to Visualizer?
