### ISSUE TITLE
Interpretation of OrientedBoundingBox.R and R to quaternion

### ISSUE THREAD

**Issue by xXBasti** [isl-org/Open3D#2892]
**Describe the bug**
The observed behavior is a weird behavior of the R matrix postprocessed by different libraries:
I am working with lidar sensor data so mostly the x-y plane is planar.
The rest of the system works with quaternions so quaternion <-> rotation matrix should work

The goal is to test the following:
Rot -> quaternion -> Rot == Rot

But non of the used libraries is even close to the original Rot

**To Reproduce**

        from scipy.spatial.transform import Rotation as Rot
        from tf import transformations
        import quaternionic as qt
        import open3d as o3d
        import numpy as np

        #labels = o3d.io.read_point_cloud("/lidar_measurement.pcd")
        #points = np.asarray(labels.points)
        points=np.array([[ 0.55011748, -0.83363892,  0.04916215],
       [ 0.83449447,  0.55099135,  0.0052447 ],
       [ 0.0314601 , -0.03814035, -0.99877704]])

        pcd.points = o3d.utility.Vector3dVector(points[100:1000])
        aabb = pcd.get_axis_aligned_bounding_box()
        aabb.color = (1, 0, 0)
        obb = pcd.get_oriented_bounding_box()

        q1 = transformations.quaternion_from_matrix(t)
        q2 = qt.array.from_rotation_matrix(obb.R, False)
        q3 = Rot.from_matrix(obb.R)

        r1 = obb.get_rotation_matrix_from_quaternion(q1)
        r2 = obb.get_rotation_matrix_from_quaternion(q2)
        r3 = obb.get_rotation_matrix_from_quaternion(q3.as_quat())

        r21 = q2.to_rotation_matrix
        r31 = q3.as_matrix()

        r_list = [obb.R, r1, r2, r3, r21, r31]
        box_list = []
        for r in r_list:
            box_list.append(
                o3d.geometry.OrientedBoundingBox(
                    center=np.array([0, 0, 0]),
                    R=r,
                    extent=np.array([1, 2, 3]),
                )
            )
        box_list[1].color = (1, 0, 0)
        box_list[2].color = (0, 1, 0)
        box_list[3].color = (0, 0, 1)
        box_list[4].color = (0, 1, 1)
        box_list[5].color = (1, 0, 1)

        o3d.visualization.draw_geometries(
            box_list,
        )

**Expected behavior**
Rot -> quad -> Rot == Rot
So all boxes should match to each other, notice that the black box is obb.R
**Screenshots**
![image](https://user-images.githubusercontent.com/12966495/104335032-4cf76580-54f3-11eb-8757-09aaeec99de9.png)
![image](https://user-images.githubusercontent.com/12966495/104335082-5b458180-54f3-11eb-8946-3c6219d074a5.png)

**Environment (please complete the following information):**

- Operating system: Ubuntu 20.04
- Python version: 3.8
- Open3D version: 0.12.0
- Is this remote workstation?: yes or no
- How did you install Open3D?: pip

**Additional context**

**Comment by benjaminum** [comment]
There was a bug in the code computing the OBB, which caused the rotation matrix to include a reflection in some cases (det(R)=-1). This has been fixed in https://github.com/isl-org/Open3D/pull/4452.
With the bugfix I get the same rotation matrix after conversion with scipy. Did not check with the other libraries due to compile issues.
Please let me know if this did not fix the problem so I can reopen this issue.

**Comment by L-Reichardt** [comment]
@xXBasti Have you ever solved this issue? I am getting the same issue, however its not related to reflection. I presume it might have something to do with determinants/left-right-handedness.
