### ISSUE TITLE
GLIBC_2.18 not found

### ISSUE THREAD

**Issue by philwilkes** [isl-org/Open3D#2893]
I get the error `OSError: /lib64/libc.so.6: version GLIBC_2.18' not found` when trying to import open3d

```
conda create -n open3d -c open3d-admin open3d
python -c "import open3d"
```
produces

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/ucfaptv/opt/miniconda/envs/open3d/lib/python3.8/site-packages/open3d/__init__.py", line 46, in <module>
>     _CDLL(next((_Path(__file__).parent).glob('*c++abi.*')))
>   File "/home/ucfaptv/opt/miniconda/envs/open3d/lib/python3.8/ctypes/__init__.py", line 373, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/ucfaptv/opt/miniconda/envs/open3d/lib/python3.8/site-packages/open3d/libc++abi.so.1)

- Operating system: RHEL 7.2
- Python version: Python 3.8.6
- Open3D version: 0.12.0
- How did you install Open3D?: conda 4.9.2

**Comment by ruanyyyyyyy** [comment]
Hi. I used the same command and met the same error when importing.

**Comment by xiao-xian** [comment]
any fix on this?

**Comment by ssheorey** [comment]
Hi @phil0stine We do not support RHEL 7.x any more due to requirements of some 3rd party libraries. You may be able to build the Python package from source without GUI. i.e. with the CMake option `BUILD_GUI=OFF`.

**Comment by CurryYuan** [comment]
Build the Python package from source is much more complicated. Will this error be fixed?

**Comment by ssheorey** [comment]
An alternative is to install and run Open3D code in a docker container on RHEL 7.2. The docker image should have a recent glibc (eg: RHEL 8+ or Ubuntu 18.04+).

**Comment by tb2-sy** [comment]
pip install open3d-python

**Comment by Song-xx** [comment]
> pip install open3d==0.9.0

but i come across another problem ,what a pity, /lib64/libstdc++.so.6: version `CXXABI_1.3.8

**Comment by onlyonewater** [comment]
> pip install open3d-python

this could cause another problem, so I uninstall it: "pip uninstall open3d-python", and now when I `import open3d`, it works now, it seems strategy. I do not know why?

**Comment by nican2018** [comment]
Please how did you solve this issues?
