### ISSUE TITLE
Live Streaming Images

### ISSUE THREAD

**Issue by rcffc** [isl-org/Open3D#2896]
It would be great if I could livestream images as nd.array from my Kinect camera to open3d.
Otherwise I would have to save it and load again, which is a significant overhead.

**Comment by rcffc** [comment]
Might be this: http://www.open3d.org/docs/release/python_api/open3d.utility.html

**Comment by ssheorey** [comment]
Please see the [Azure Kinect tutoria]( http://www.open3d.org/docs/latest/tutorial/sensor/azure_kinect.html)l for live streaming images from Kinect to Open3D.
Here is the [example code](https://github.com/isl-org/Open3D/blob/master/examples/python/reconstruction_system/sensors/azure_kinect_viewer.py).
Once in Open3D, you can convert the RGBD images to a pair of Numpy arrays with `np.asarray(open3d.geometry.image)`

```python
# rgbd is of type open3d.geometry.RGBDImage, obtained from Kinect
rgb = np.asarray(rgbd.color)
depth = np.asarray(rgbd.depth)
```
