### ISSUE TITLE
Return value format error

### ISSUE THREAD

**Issue by arkerman** [isl-org/Open3D#2899]
hello :
         I try to use a function **get_oriented_bounding_box()** to achieve orient bounding box. I writed **print (o3d.geometry.PointCloud.get_oriented_bounding_box(Filtered_point_cloud))**， and it ruturned **OrientedBoundingBox: center: (69.925, 21.1186, 19.0637), extent: 488.633, 531.05367.0896)** just like the pic uploaded. I found something wrong . A comma seems miss in the **extent: 488.633, 531.05367.0896**
![mistake](https://user-images.githubusercontent.com/63221199/104670614-274aa600-5717-11eb-9998-223584a400f1.png)

**Comment by sanskar107** [comment]
@arkerman thanks for pointing it out. This is a small typo in print statement.

**Comment by arkerman** [comment]
@sanskar107 Thank you for your reply. Where should I put the comma? It's very important to me

**Comment by sanskar107** [comment]
That is hard to tell. You can fix the typo here and compile again to verify https://github.com/intel-isl/Open3D/blob/master/cpp/pybind/geometry/boundingvolume.cpp#L61

**Comment by arkerman** [comment]
@sanskar107 Thanks for your suggestion!
