### ISSUE TITLE
Can't import open3d

### ISSUE THREAD

**Issue by jonnymaserati** [isl-org/Open3D#2903]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
When I try `import opend3d as o3d` I get the following Exception:
```
Exception has occurred: OSError
/home/user/anaconda3/envs/welleng/lib/python3.8/site-packages/open3d/cpu/pybind.cpython-38-x86_64-linux-gnu.so: undefined symbol: glPopGroupMarkerEXT
  File "/home/user/Dropbox/user/GitHub/welleng/work/octree_nav.py", line 1, in <module>
    import open3d as o3d
```

**To Reproduce**

1. create a .py file
2. add `import open3d`
3. run it

**Expected behavior**
import the module.

**Environment (please complete the following information):**
- Operating system: (Ubuntu 20.04)
- Python version: (Python 3.7 and 3.8)
- Open3D version: 0.12.0
- Is this remote workstation?: no
- How did you install Open3D?: (conda - conda install -c open3d-admin open3d)

**Comment by ssheorey** [comment]
Hi @jonnymaserati I was not able to reproduce this issue in an Ubuntu 20.04 docker container with Python 3.8 using a `pip` installation (system default Python). Can you reproduce this issue after installing Open3D with `pip`? We are planning to deprecate conda packages.

**Comment by jonnymaserati** [comment]
Hi there @ssheorey

It's the same regardless of how I install it, I've tried pip also.

I've tried with a clean env and same thing.

**Comment by ssheorey** [comment]
@errissa Possibly relevant issue:
https://github.com/mapbox/mapbox-gl-native/issues/268

**Comment by iacisme** [comment]
Hi;

I"m experiencing the exact same issue. I had Open3D 0.10.0 installed, uninstalled it - deleted the folder and then did a pip install open3d.

The package installs fine, but when you try to import Open3D, I get this error: 

```
OSError: /home/user_name/.virtualenvs/depthAI/lib/python3.7/site-packages/open3d/cpu/pybind.cpython-37m-x86_64-linux-gnu.so: undefined symbol: glPushGroupMarkerEXT
```
Debain 10, Macbook Pro 2009.

**Comment by MartinHahner** [comment]
I got the same issue.

Debian GNU/Linux 10 (buster)
conda 4.10.3
open3d 0.13.0


```bash
conda create --name open3d python=3.8 -y
conda activate open3d
pip install open3d
python
import open3d as o3d
```

```
OSError: .../python3.8/site-packages/open3d/cpu/pybind.cpython-38-x86_64-linux-gnu.so: undefined symbol: glPushGroupMarkerEXT
```

**Comment by ssheorey** [comment]
Can you paste the output of:
`ldd <site-packages from output of pip show open3d>/open3d/cpu/pybind.cpython-38-x86_64-linux-gnu.so`

**Comment by MartinHahner** [comment]
> open3d/cpu/pybind.cpython-38-x86_64-linux-gnu.so

```bash
(open3d) mhahner@hox:/home/mhahner
$ pip show open3d
Name: open3d
Version: 0.13.0
Summary: Open3D: A Modern Library for 3D Data Processing.
Home-page: http://www.open3d.org
Author: Open3D Team
Author-email: info@open3d.org
License: MIT
Location: /scratch_net/hox/mhahner/apps/anaconda3/envs/open3d/lib/python3.8/site-packages
Requires: matplotlib, pygments, wheel, jupyterlab, pandas, ipywidgets, jupyter-packaging, pyyaml, scikit-learn, numpy, pillow, numpy, tqdm, setuptools, addict
Required-by:

(open3d) mhahner@hox:/home/mhahner
$ ldd /scratch_net/hox/mhahner/apps/anaconda3/envs/open3d/lib/python3.8/site-packages/open3d/cpu/pybind.cpython-38-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffcb9fac000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007fa13c2e8000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa13c2c7000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fa13c2bd000)
	libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007fa13c297000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007fa13bf58000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa13bdd4000)
	libc++.so.1 => not found
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa13bdcd000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fa13bc8c000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa13bb09000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa13baef000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa13b92e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa1442a6000)
	libnvidia-tls.so.418.197.02 => /usr/lib/x86_64-linux-gnu/libnvidia-tls.so.418.197.02 (0x00007fa13b728000)
	libnvidia-glcore.so.418.197.02 => /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.418.197.02 (0x00007fa139ab4000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fa1398a2000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fa139878000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fa139674000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fa13946c000)
	libbsd.so.0 => /usr/lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fa139452000)
```

**Comment by MartinHahner** [comment]
<img width="173" alt="grafik" src="https://user-images.githubusercontent.com/14181188/133132431-afb739bd-8137-4ec2-bf4c-c8c23c7d275d.png">

On Mac I have no issues:

```bash
~ 🅒 open3d
➜ python
Python 3.8.11 (default, Aug  6 2021, 08:56:27)
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import open3d as o3d
>>>
```

**Comment by csyhping** [comment]
Same issue here, could you please help with it?

**Comment by charlottesilver11** [comment]
I have successfully imported open3d in my terminal by writing "pip install open3d" but then when I go into my Pycharm and write "import open3d as o3d" it says " ModuleNotFoundError: No module named 'open3d' ". How do I fix this?

**Comment by ssheorey** [comment]
This question is unrelated to this issue. Please ask this as a question here: https://github.com/isl-org/Open3D/discussions

Very likely PyCharm is using a virtual environment and you need to install open3d inside that virtual environment.  Or change the PyCharm virtual environment to the one with open3d installed. See PyCharm documentation for details.

**Comment by johnthagen** [comment]
@shivam280699 If you are use Poetry to install Open3D, your issue may be:

- #5747
