### ISSUE TITLE
Azure Kinect MKV Reader

### ISSUE THREAD

**Issue by HelliceSaouli** [isl-org/Open3D#2908]
Hello, I'm trying to compile the azure kinect mkv reader c++ sample in the examples and it does not compile saying do to the compiler not able to find the #include <json/json.h>. i looked in my open3d build and i could not find it either.

I fixed this by copying the files to the install directory from the original source. for some reason Open3d does not install the jsoncpp lib from 3rdparty.

The example compile fine but it does not run.  its seems that the mkv file can't be read or something, no error messages where showing on the screen

am using open3d  0.12.0 on windows 10
this what i get as out put, not that other examples works fine. wish mean was able to find the k4a_lib_dir
![image](https://user-images.githubusercontent.com/10406314/104853087-8adefa00-58f6-11eb-8ce0-c2cee9757fa5.png)

**Comment by sanskar107** [comment]
@HelliceSaouli could you please post your build logs here?

**Comment by theNded** [comment]
Closed via #4476.
