### ISSUE TITLE
Build error from source, open3d 0.12.0, python 3.6, ubuntu 18.04

### ISSUE THREAD

**Issue by wingvortex** [isl-org/Open3D#2910]
Hi, I followed the instruction, tried several times, always end with the following error:

[ 25%] No update step for 'ext_tbb'
[ 25%] Performing patch step for 'ext_tbb'
HEAD is now at 141b0e3 quoting fixes, quenched warnings on MSVC
error: patch failed: CMakeLists.txt:1
error: CMakeLists.txt: patch does not apply
CMakeFiles/ext_tbb.dir/build.make:119: recipe for target 'tbb/src/ext_tbb-stamp/ext_tbb-patch' failed
make[2]: *** [tbb/src/ext_tbb-stamp/ext_tbb-patch] Error 1
CMakeFiles/Makefile2:889: recipe for target 'CMakeFiles/ext_tbb.dir/all' failed
make[1]: *** [CMakeFiles/ext_tbb.dir/all] Error 2

Here is the configuration:
-- ========================================================================
-- Open3D 0.12.0 Configuration Summary
-- ========================================================================
-- Enabled Features:
--   OpenMP .................................. ON
--   Headless Rendering ...................... OFF
--   Azure Kinect Support .................... OFF
--   Intel RealSense Support ................. OFF
--   CUDA Support ............................ OFF
--   Build GUI ............................... ON
--   Build Shared Library .................... OFF
--   Build Unit Tests ........................ OFF
--   Build Examples ..........................
--   Build Python Module ..................... ON
--   - with Jupyter Notebook Support ......... OFF
--   Build TensorFlow Ops .................... OFF
--   Build PyTorch Ops ....................... OFF
--   Build Benchmarks ........................ OFF
--   Bundle Open3D-ML ........................ OFF
--   Build RPC interface ..................... OFF
--   Force GLIBCXX_USE_CXX11_ABI= ............ 0
-- ========================================================================
-- Third-Party Dependencies:
--   EIGEN3 .................................. yes (build from source)
--   FAISS ................................... yes (build from source)
--   FILAMENT ................................ yes (build from source)
--   FLANN ................................... yes (build from source)
--   FMT ..................................... yes (build from source)
--   GLEW .................................... yes (build from source)
--   GLFW .................................... yes (build from source)
--   GOOGLETEST .............................. no
--   IMGUI ................................... yes (build from source)
--   JPEG .................................... yes (build from source)
--   JSONCPP ................................. yes (build from source)
--   LIBLZF .................................. yes (build from source)
--   OPENGL .................................. yes (build from source)
--   PNG ..................................... no
--   PYBIND11 ................................ yes (build from source)
--   QHULL ................................... yes (build from source)
--   LIBREALSENSE ............................ no
--   TINYFILEDIALOGS ......................... yes (build from source)
--   TINYGLTF ................................ yes (build from source)
--   TINYOBJLOADER ........................... yes (build from source)
-- ========================================================================

**Comment by liveforday** [comment]
I also have the problem. but I solved the problem by adding the `ext_tbb-patch` file  manually in the path `build/tbb/src/ext_tbb-stamp`.  I don't write anything in the file called `ext_tbb-patch`.  It just a empty file.

**Comment by ssheorey** [comment]
Hi @wingvortex @liveforday please delete the folder `build/tbb` and try again. Patching will succeed the first time, but can fail if an attempt is made to repeat it. If you still have errors, can you upload the contents of `build/tbb/src/ext_tbb-build/CMakeError.log`?

**Comment by ssheorey** [comment]
Closing. Please re-open if there are still issues.
