### ISSUE TITLE
Saving structured point clouds with o3d.io.write_point_cloud

### ISSUE THREAD

**Issue by sglimberg** [isl-org/Open3D#2912]
We are always working with structured point clouds in Python. But is seems that o3d.io.write_point_cloud only allow us to save it unstructured. If foo.pcd is a structured 16x16 point cloud and we do this:

```
pcd = o3d.io.read_point_cloud('foo.pcd',remove_nan_points=False)
o3d.io.write_point_cloud('out.pcd',pcd)
```
The header of out.pcd has a header containing
```
WIDTH 256
HEIGHT 1
```

And we will manually have to change it into
```
WIDTH 16
HEIGHT 16
```

We suggest that the pcd object is aware of the points being structured and saves it accordingly.

Alternatively the write_point_cloud function may take additional input arguments specifying the dimensions.

**Comment by HelliceSaouli** [comment]
I think its pointless to add this feature, since unlike PCL, open3d has good 2D image structure called RGBDimage.  and they are basicaly 3d structured point cloud. this why you dont need organized pcd, unless you want to use them in PCL which i can't see the reason of using pcl and open3d both in one app

**Comment by YoshuaNava** [comment]
@HelliceSaouli Thanks for the feedback.

Nonetheless, are RGBDimages general enough for any representation? For example, from a half-dome LiDAR, or an Spherical scanner. What kind of camera model would you use in that case?

Best,
Yoshua

**Comment by HelliceSaouli** [comment]
@YoshuaNava,
Hello,
 I'm not sure but i think open3D has some sort of support for LIDAR Data, am not sure though , check this  https://www.youtube.com/watch?v=Rsh4poEpahI

The thing is PCD is format dedicated for PCL and I think Open3D devs wrote the write_point_cloud('.pcd') for  the propose of output the point cloud to be visualized and not to be processed. what am trying to say PCD is not native to open3d and the best way to input data is via RGBDImages or DepthImage

**Comment by reyanshsolis** [comment]
Thanks @HelliceSaouli for the reply. You are right, `organised point-cloud` is currently not supported in Open3D. We may add the support in future, currently, it would be best to input it as an `RGBD / Depth Image`.

**Comment by MohamedEttaieb** [comment]
Quel est le rôle de pcd `??
