### ISSUE TITLE
Request for Open3D to use a stable release from Eigen instead of master branch

### ISSUE THREAD

**Issue by SoulProtagonist** [isl-org/Open3D#2919]
Within my project I was using Eigen 3.3.7 and Open3D 0.9.0. When I upgraded to Open3D 0.11.2 I needed to switch to using the master branch from Eigen as the header "Open3D/include/open3d/geometry/Line3D.h" uses a method from ParametrizedLine which only exists on Eigens' master branch. Specifically it uses "transform" that doesn't exist on any stable eigen branch as far as I can tell. Changing the version of Eigen we were using presented its own problems we needed to fix. 

A solution for this could be that Open3D use a stable release of Eigen.

Alternatively the code within Line3D could be moved inside the compiled library, instead of in a header file so that a different version of Eigen could be used by any libraries linking against Open3D.

**Comment by ssheorey** [comment]
Open3D now uses the stable Eigen release 3.4.0, see here:
https://github.com/isl-org/Open3D/blob/3bd635bc17e840a22e197c3e44a3fe5bf3546f8e/3rdparty/eigen/eigen.cmake#L6
