### ISSUE TITLE
Is it possible to load a triangle mesh with only vertices (no faces)

### ISSUE THREAD

**Issue by EricWiener** [isl-org/Open3D#2924]
mmdetection3D produces triangle mesh files (`.bin`) with just vertices and no faces. I am trying to display these with Open3D, but the triangle mesh doesn't get loaded because there are no faces. I am given the message:
```
[Open3D INFO] Skipping non-triangle primitive geometry of type: 1
```

Is it possible to force Open3D to load just the vertices?

Thanks!

**Comment by EricWiener** [comment]
According to mmdetection3d, it is valid to have a mesh file with just vertices. https://github.com/open-mmlab/mmdetection3d/issues/281

**Comment by meng-zha** [comment]
You can downgrade to the version 0.9.0.0 to read the obj without triangle meshes.

**Comment by EricWiener** [comment]
@meng-zha that doesn’t seem like a good solution

**Comment by prewettg** [comment]
If you have just vertices and no triangles, you really have a point cloud, not a triangle mesh. Does `open3d.io.read_point_cloud()` work?

**Comment by PranavGupta98** [comment]
> If you have just vertices and no triangles, you really have a point cloud, not a triangle mesh. Does `open3d.io.read_point_cloud()` work?

I am working with 'obj' output from FCAF3D, gives two files file1:"..._points.obj" and file2:"..._pred.obj" per detection. Able to visualize the file2 although abstract but not file1 it gives warning: "geometry::TriangleMesh appears to be a geometry::PointCloud (only contains vertices, but no triangles" and shows a blank canvas. 

Any ideas how to visualize these outputs?

**Comment by Resham-Sundar** [comment]
> 

Were you able to solve it? Facing the same issue

**Comment by BuddyZhu** [comment]
Facing the same problem, seems not solved.

**Comment by BuddyZhu** [comment]
> 

Not working.

"[Open3D WARNING] Read geometry::PointCloud failed: unknown file extension for ./output/thred0.5_000000_points.obj (format: auto)."

**Comment by ehedlin** [comment]
It seems that it wants a ply file. I just prepend the lines 

> import trimesh
> mesh = trimesh.load_mesh("surface_points.obj")
> mesh.export("surface_points.ply")

before

> pcd = o3d.io.read_point_cloud("surface_points.ply")
