### ISSUE TITLE
'open3d' has no attribute 'registration'

### ISSUE THREAD

**Issue by hamid54** [isl-org/Open3D#2951]
Hi,
I am using a code which has written by open3d 0.9.0, so I have built up a conda environment accordingly (python 3.6 and open3d 0.9.0). However when I run the code I get:

`AttributeError: module 'open3d' has no attribute 'registration'`

It seems there is a versioning problem. I tried it with open3d 0.10.0 but nothing changed. Any idea what the problem could be? I even thought maybe conda is installing a wrong version, but it sees to do just fine:

`
$ conda install -c open3d-admin open3d=0.10.0
...
The following NEW packages will be INSTALLED:

  argon2-cffi        pkgs/main/linux-64::argon2-cffi-20.1.0-py36h7b6447c_1
  async_generator    pkgs/main/linux-64::async_generator-1.10-py36h28b3542_0
  attrs              pkgs/main/noarch::attrs-20.3.0-pyhd3eb1b0_0
  backcall           pkgs/main/noarch::backcall-0.2.0-py_0
  bleach             pkgs/main/noarch::bleach-3.2.3-pyhd3eb1b0_0
  cffi               pkgs/main/linux-64::cffi-1.14.4-py36h261ae71_0
  decorator          pkgs/main/noarch::decorator-4.4.2-py_0
  defusedxml         pkgs/main/noarch::defusedxml-0.6.0-py_0
  entrypoints        pkgs/main/linux-64::entrypoints-0.3-py36_0
  importlib-metadata pkgs/main/noarch::importlib-metadata-2.0.0-py_1
  importlib_metadata pkgs/main/noarch::importlib_metadata-2.0.0-1
  ipykernel          pkgs/main/linux-64::ipykernel-5.3.4-py36h5ca1d4c_0
  ipython            pkgs/main/linux-64::ipython-7.16.1-py36h5ca1d4c_0
  ipython_genutils   pkgs/main/noarch::ipython_genutils-0.2.0-pyhd3eb1b0_1
  ipywidgets         pkgs/main/noarch::ipywidgets-7.6.3-pyhd3eb1b0_1
  jedi               pkgs/main/linux-64::jedi-0.18.0-py36h06a4308_1
  jinja2             pkgs/main/noarch::jinja2-2.11.2-pyhd3eb1b0_0
  jsonschema         pkgs/main/noarch::jsonschema-3.2.0-py_2
  jupyter_client     pkgs/main/noarch::jupyter_client-6.1.7-py_0
  jupyter_core       pkgs/main/linux-64::jupyter_core-4.7.0-py36h06a4308_0
  jupyterlab_pygmen~ pkgs/main/noarch::jupyterlab_pygments-0.1.2-py_0
  jupyterlab_widgets pkgs/main/noarch::jupyterlab_widgets-1.0.0-pyhd3eb1b0_1
  libsodium          pkgs/main/linux-64::libsodium-1.0.18-h7b6447c_0
  markupsafe         pkgs/main/linux-64::markupsafe-1.1.1-py36h7b6447c_0
  mistune            pkgs/main/linux-64::mistune-0.8.4-py36h7b6447c_0
  nbclient           pkgs/main/noarch::nbclient-0.5.1-py_0
  nbconvert          pkgs/main/linux-64::nbconvert-6.0.7-py36_0
  nbformat           pkgs/main/noarch::nbformat-5.1.2-pyhd3eb1b0_1
  nest-asyncio       pkgs/main/noarch::nest-asyncio-1.4.3-pyhd3eb1b0_0
  notebook           pkgs/main/linux-64::notebook-6.2.0-py36h06a4308_0
  open3d             open3d-admin/linux-64::open3d-0.10.0.0-py36_0
...
Downloading and Extracting Packages
open3d-0.10.0.0      | 3.9 MB    | ################################################################################################################################################################ | 100% 
...
`

Thank you!
Hamid

**Comment by sanskar107** [comment]
Could you please send your code lines which throws this Error?

**Comment by albertotono** [comment]
I have the same error with this line @sanskar107  
`o3d.registration.compute_fpfh_feature(pcd)`

http://www.open3d.org/docs/latest/python_api/open3d.registration.compute_fpfh_feature.html

**Comment by albertotono** [comment]
**o3d.pipelines.**registration.compute_fpfh_feature(pcd).

It seems that now it is under pipelines based on the new documentation http://www.open3d.org/docs/release/python_api/open3d.pipelines.html
 
Is it correct?

**Comment by legel** [comment]
@albertotono yes you've identified what appears to be a change in the API, but that works

**Comment by 1805344946ts** [comment]
I have the same error with under line,what can I do? @albertotono 
o3d.registration.compute_fpfh_feature(pcd)

**Comment by albertotono** [comment]
Add pipelines before registration like in my example.

**Comment by 1805344946ts** [comment]
ok,thank you very much




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "intel-isl/Open3D"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月11日(星期四) 晚上9:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [intel-isl/Open3D] 'open3d' has no attribute 'registration' (#2951)





 
Add pipelines before registration like in my example.
