### ISSUE TITLE
frame-to-model reconstruction algorithm (similar to KinectFusion)

### ISSUE THREAD

**Issue by emilyveenstra** [isl-org/Open3D#2960]
I have experimented with making model reconstructions using both Kinect Fusion and Open3D. 

The frame-to-model alignment algorithm used in Kinect Fusion has shown promising results and I haven't been able to match that performance using Open3D's frame-to-frame algorithm. 

I read here (https://github.com/intel-isl/Open3D/issues/2728) that you plan to implement similar frame-to-model tracking in Open3D in the future.  I am very interested in trying out this feature.  Could you give me an estimate for when we might expect this feature? 

Thanks for all your work developing Open3D!

**Comment by theNded** [comment]
This feature has been supported, see this [tutorial](http://www.open3d.org/docs/latest/tutorial/t_reconstruction_system/index.html). However the robustness is still less ideal and we will be working on it.
