### ISSUE TITLE
Number of points in pcd

### ISSUE THREAD

**Issue by JordanMakesMaps** [isl-org/Open3D#2988]
Is there already a built-in method for getting the total number of points in a pcd? I can't seem to find it and instead am doing this, but I'd rather not 😎

```python
pcd = o3d.io.read_point_cloud(file)
num_points = len(np.asarray(pcd.points))
```
Thanks for the repo, loving it!

**Comment by agrodet** [comment]
Since there is no answer, I guess it is worth mentioning that since `pcd.points` is a `o3d.utility.Vector3dVector` (a `std::vector<Eigen::Vector3d>` under the hood), one can use `len` without any conversion to numpy array. 
Simple use `len(pcd.points)` like you would do with any Python list.

**Comment by theNded** [comment]
For the legacy API this is the right approach to get the length. For the latest `t.geometry.PointCloud` API, point cloud attributes are now stored as Tensors and you can use tensor operators to obtain the length.

**Comment by solarjoe** [comment]
@theNded which attribute or method in the latest `t.geometry.PointCloud` will return the number of points?

**Comment by gachiemchiep** [comment]
@solarjoe 

.point method will return a TensorMap like this
TensorMap(primary_key="positions") with 2 attributes:
  - colors   : shape={1000, 3}, dtype=Float32, device=CPU:0
  - positions: shape={1000, 3}, dtype=Float32, device=CPU:0 (primary)

so use this to get the number of point

```bash
num_points = pcd_t.point["colors"].shape[0]
```
