### ISSUE TITLE
javascript support(webassembly) like opencv.js

### ISSUE THREAD

**Issue by naah69** [isl-org/Open3D#2993]
**Is your feature request related to a problem? Please describe.**
 i wanna open3d be compiled to webassembly and javascripte interface,like opencv.js

**Describe the solution you'd like**
compile open3d to webassembly and javascripte file

**Describe alternatives you've considered**
there is not great 3d-develop libary on javascript

**Additional context**

**Comment by theNded** [comment]
Making the entire library in json could be another project from scratch. However we have recently supported [web visualization](http://www.open3d.org/docs/latest/tutorial/visualization/web_visualizer.html) with Open3D running as a backend. Hope it helps.
