### ISSUE TITLE
Is there anyway to generate triangle mesh from point cloud?

### ISSUE THREAD

**Issue by liuliu66** [isl-org/Open3D#2999]
given a triangle mesh, I can extract vertices as point cloud. So, is there anyway to generate triangles from a point cloud, with some parameters? Many Thanks!

**Comment by ssheorey** [comment]
Hi @liuliu66 is this what you are looking for?
http://www.open3d.org/docs/latest/tutorial/pipelines/rgbd_integration.html
This tutorial shows how to create a triangle mesh from RGBD images.

**Comment by cbenitez81** [comment]
You can use poisson reconstruction or ball pivoting http://www.open3d.org/docs/latest/tutorial/Advanced/surface_reconstruction.html
