### ISSUE TITLE
Poisson surface recon width is type size_t but should be float or double, I think

### ISSUE THREAD

**Issue by Andyjk1406** [isl-org/Open3D#3008]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
If we wish to use width in Surface Reconstruction Poisson, instead of octree depth, it may need to be in float format. Eg 0.5. Having size_t constrains us to a minimum octree depth of 1mm, for example, which may not be small enough.

**To Reproduce**
N/A

**Expected behavior**
Should be able to specify minimum octree cell size in float/double

**Environment (please complete the following information):**

- Operating system: (Windows 10 64-bit)
- C++
- Open3D version: N/A

**Comment by Andyjk1406** [comment]
Just checking in on progress here. It ought to be a very minor change (from size_t to float for the width parameter).
My understanding is that the minimum voxel width could then be specified, rather than Poisson depth. This is very useful if you are surfacing different sized objects but require the same resolution.

Thats assuming my understanding of the parameter is correct? In my case I'd need, for example, width=0.05, which is currently not possible.

**Comment by nigels-com** [comment]
Should be resolved now in master @Andyjk1406 .
Time to close this?
