### ISSUE TITLE
open3d.pipelines.registration.Feature Display

### ISSUE THREAD

**Issue by albertotono** [isl-org/Open3D#3016]
How can I access the Feature?

I created the fpfh

```
pcd_fpfh = o3d.pipelines.registration.compute_fpfh_feature(pcd_down,o3d.geometry.KDTreeSearchParamHybrid(radius=50, max_nn=100))
pcd_fpfh
```

It would be great to be able to display these features.

**Comment by JoeNatan30** [comment]
You can access the feature with:

`pcd_fpfh.data`

that is a numpy array
