### ISSUE TITLE
Orient point cloud points using the estimated surface normals instead of applying the billboarding effect

### ISSUE THREAD

**Issue by elvircrn** [isl-org/Open3D#3022]
I would like the orientation of each individual point in the point cloud to be equal to the estimated surface normal, rather than to have their surface always point towards to camera(billboarding).  Is it possible to apply this change programmatically with the existing source code, or is this effectively a feature request?

**Comment by theNded** [comment]
The normals are always equal to the estimated surface normal after `pcd.estimate_normals()`.
