### ISSUE TITLE
PoseGraphNode argument

### ISSUE THREAD

**Issue by GabrieleGalimberti-GaleSelector** [isl-org/Open3D#3039]
Hi,

I'm trying to create a pose graph but I don't understand what I must set as argument of each node.

After align each LR point clouds of a Dataset KAIST, I'm trying to create a pose graph.
I insert a pose as the argument of each Node actually an identity matrix. 

```
pose_graph.nodes.append(o3d.pipelines.registration.PoseGraphNode())
 ```

I expected that in each node of pose graph there's a pose that allow to align every couple of point clouds.

I also tried to follow the tutorial (http://www.open3d.org/docs/release/tutorial/pipelines/multiway_registration.html#Pose-graph) in which for each pair of point clouds they find the alignment and multiply it cumulatively, but I did not get the desired result.

```odometry = np.identity(4)
for source_id in range(n_pcds-1):
      t, information_icp = pairwise_registration( pcds[source_id] , pcds[source_id+1] )
      odometry = np.dot(t,odometry)
      pose_graph.nodes.append(
          o3d.pipelines.registration.PoseGraphNode( np.linalg.inv(odometry) ))
      pose_graph.edges.append(
          o3d.pipelines.registration.PoseGraphEdge(source_id, source_id+1, t, np.identity(6), uncertain=False))
```

- Operating system: OSX 10.14.6
- Python version: Python 3.6
- Open3D version: 0.12.0
- Is this remote workstation?: no

**Comment by theNded** [comment]
Pose graph optimization is only valid when there are loop closures, i.e. `target id != source_id + 1`. Otherwise, there are no further constraints to refine the poses.
