### ISSUE TITLE
TSDFVoxelGrid get voxel data

### ISSUE THREAD

**Issue by anthonybrunel** [isl-org/Open3D#3040]
Hi,

I successfully use TSDFVoxelGrid on GPU.
Now, I would like to know if there is a way to bring back the data on CPU and iterate over each allocated block/voxel (if I understand correctly you use an hashmap). 
Specifically, for each x,y,z inside the map, I want to get the tsdf & weight.

Is this possible and have you any suggestion to do this?

Rgds
Anzzy

**Comment by theNded** [comment]
Which version are you using, C++ or python?

**Comment by Anzzy30** [comment]
Hi,

I use python 3.8 with open3d 0.12.0 (but i will probably switch my project to c++).
Therefore, i will be glad if you can show me in both language. 

Thx.

**Comment by theNded** [comment]
This feature is now (partly) supported in the new `VoxelBlockGrid` API.
