### ISSUE TITLE
Distorted Point cloud from panorama face

### ISSUE THREAD

**Issue by xsertx** [isl-org/Open3D#3041]
Hi, I have a problem. I work with rgbd panoramas. So since open3d supports only pinhole camera model, I converted panoramas to perspective views (w=1024, h=1024). However, when i tried to [create a pcld from rgbd](http://www.open3d.org/docs/latest/tutorial/Basic/rgbd_image.html)  the result looks wrong (distorted). It feels like my camera intrinsics are wrong, but i'm not sure.

PinholeCameraIntrinsic with width = 1024 and height = 1024.
Access intrinsics with intrinsic_matrix.
[[1024. 0. 512.]
[ 0. 1024. 512.]
[ 0. 0. 1.]]

Could you help me with my problem ?

<img width="784" alt="Screen Shot 2021-02-16 at 4 34 12 PM" src="https://user-images.githubusercontent.com/29440138/108032515-f4793200-7075-11eb-8a62-c761d70dedae.png">

**Comment by ssheorey** [comment]
@xsertx  Looking at the distortion, your focal length is likely too small. Do you know the actual value from the camera? Otherwise it's best to measure it with camera calibration. Setting it to a very large value should approximate orthographic projection, if that's what you have.

**Comment by theNded** [comment]
Closed due to the dormant state. Please feel free to reopen.
