### ISSUE TITLE
Close camera connection with Azure Kinect

### ISSUE THREAD

**Issue by Holtskog** [isl-org/Open3D#3044]
When working with the Azure kinect camera I cannot close the connection through open3d. It would be nice to have a method, similar to your start() method, that closes the connection, e.g. stop().

I have considered to just remove the object I get when starting the device, but a nicer solution would be to have a method for it, so that I can keep the object and start it up again whenever I want.

It is a suggestion for python.

**Comment by Holtskog** [comment]
Any progress on this @ssheorey ?

**Comment by ssheorey** [comment]
It may take some time till we get to this feature request. This looks like a good feature for a new contributor (PRs are welcome!).

**Comment by theNded** [comment]
#3044 merged, thanks for the contribution!
