### ISSUE TITLE
L515 recording and reconstruction *bag file

### ISSUE THREAD

**Issue by AH50** [isl-org/Open3D#3051]
This is a continuation of the issue: https://github.com/intel-isl/Open3D/issues/2985

Operating System: Ubuntu 20.04.2 LTS
Kernel: Linux 5.4.0-65-generic
Python version: Python 3.8.5
Device: L515
Open3D 0.12.0

There are different system parameters compared to the previous issue because I tried to repeat the situation on a laptop and got exactly the same result.

I tried to reconstruct the scene from my recording and got only one RGB and depth photo each and the *bag file itself weighs 900MB(recording 4-5 seconds).The RGB photo is completely black. The depth photo seems to be correct. It created one "fragment" and "scene" from these two photos.

I also tried to reconstruct the *bag file which is given on the site and I had no problems with it. The scene built normally from the L515_test.bag file which weighed 37MB. I noticed that there is a difference in resolution because in the L515_test file it is using 960x540 and in my case it is 1280x720. I didn't edit configuration file of the recording script, I used examples following the guidelines on open3d(http://www.open3d.org/docs/latest/tutorial/sensor/realsense.html) website

For recording I used:
 ``
bin/examples/RealSenseRecorder --config ../examples/test_data/rs_default_config.json --record test_data.bag
 ``
For the reconstruction I used:
 ``
python run_system.py config/realsense.json --make --register --refine --integrate
 ``
This is my realsense.json file:

{
"name": "realsense bag file",
"path_dataset": "/home/user/scans/L515_test.bag",
"max_depth": 3.0,
"voxel_size": 0.05,
"depth_scale" : 3999.999755859375,
"max_depth_diff": 0.07,
"preference_loop_closure_odometry": 0.1,
"preference_loop_closure_registration": 5.0,
"tsdf_cubic_size": 3.0,
"icp_method": "color",
"global_registration": "ransac",
"python_multi_threading": true
}

**Comment by ssheorey** [comment]
Hi @AH50 can you play the recorded file in the `realsense-viewer`. Does that look correct?

**Comment by AH50** [comment]
the recording can be normally viewed with ``realsense-viewer``

**Comment by AH50** [comment]
after : ``python run_system.py config/realsense.json --make --register --refine --integrate``
log file : https://pastebin.com/NtLaDZc2

**Comment by AH50** [comment]
Hi @ssheorey , is there any update to this issue?

**Comment by ssheorey** [comment]
Hi @AH50 Can you attach the log files directly here. The `pastebin` link has expired.

**Comment by AH50** [comment]
Hi @sanskar107 
this file is too big to paste here .
New link: https://pastebin.com/7Nk98zub

**Comment by ssheorey** [comment]
Hi @AH50 Please try with the latest development Python wheel from here:
http://www.open3d.org/docs/latest/getting_started.html#development-version-pip
[or test with building from the `master` branch]
and let us know if you still have this issue.
