### ISSUE TITLE
Install dependencies instead of using 3rd party libraries

### ISSUE THREAD

**Issue by cbenitez81** [isl-org/Open3D#3068]
**Problem:** We have too many 3rdparty libraries of basic packages, i.e. flann, tbb, openblas etc. So this causes many issues if we want to link create a package with other libraries such as ros, pcl and even faiss. 

## Possible solutions:
1. We already have an install dependencies, so we can potentially add glew, glfw, tbb to that script instead of building that and attaching the binary code to some libOpen3dxxx.so
1. I have faced a lot of issues because since namespace in those 3rdpary libraries are the same than in the system libraries, then at compilation or execution one can get "confused" by the other killing objects that are still running etc. _If we decided to keep 20 thirdparty libraries we might need to dig into each folder and change the namespace_ just to be sure that it would not interfered with the system one.
2. If the use from those 3rdparty libraries is minimum (reading an obj file), we can potentially use that portion of the code (copy paste as long as license permits) and reformatted inside the main modules.
3. Some cases such as poisson-reconstruction the code comes "as it is", ready to be linked, but it also lacks namespaces which needs editing.
4. Make the default cmake behavior to look for system libraries

Any thoughts ?

**Comment by yxlao** [comment]
For a subset of the 3rd-party libraries, we have the option to use the system's installed version: https://github.com/intel-isl/Open3D/blob/dea0fbd3788e0e31fd8b70351fae135f36258aa7/CMakeLists.txt#L30-L44

The other thing you may try is to build Open3D as a static library, and you'll get a `libOpen3D.a` together with some other `.a` files. You can then figure out a way to link `libOpen3D.a` to your project and link other libraries manually for the missing symbols. 

Regarding point 2, this shouldn't happen as long as we don't include the headers from both the system-installed version and the version that comes with Open3D. Make sure not to use both of them at the same time. For instance, if you'd like to use the system library, make sure to set the corresponding `USE_SYSTEM_XXXX=ON`.

Regarding point 4, this is true. We will be happy to review pull requests that fix this.

Regarding point 5, The reason we choose to not look for system libraries by default is that the developers can have very different system configurations (e.g. they may have different versions or incompatible versions of 3rd-party libraries installed) and this leads to inconsistent behaviors.

**Comment by theNded** [comment]
Closed due to the dormant state. Please feel free to reopen.
