### ISSUE TITLE
how to get a non-convex hull

### ISSUE THREAD

**Issue by praharsh05** [isl-org/Open3D#3078]
Is there a way to get non convex/ concave hull, I am trying to calculate the volume of an open top box which is partially filled, I tried using the convex hull and `get_volume` function to obtain the volume but I am getting wrong values in the output. Please suggest something as I'm stuck and not getting new ideas 😅

**Comment by ssheorey** [comment]
Hi @praharsh05 an option here would be if you can remove the open top box from the point cloud / mesh, you should be able to use convex hull directly. e.g. you can try removing all vertices within 2mm of the box faces, if the box wall is 2mm thick.
