### ISSUE TITLE
Can I create a cylinder from two points? 

### ISSUE THREAD

**Issue by timeanddoctor** [isl-org/Open3D#3089]
A simple requestion I need create a cylinder from two point..And I searched many code but found nothing..

**Comment by theNded** [comment]
I don't think it is well-posed to construct a cylinder from 2 points. You may create a cylinder with [this API](http://www.open3d.org/docs/latest/python_api/open3d.geometry.TriangleMesh.html#open3d.geometry.TriangleMesh.create_cylinder).
