### ISSUE TITLE
Read_point_cloud(‘file.ply’) fails to read colors

### ISSUE THREAD

**Issue by tibbben** [isl-org/Open3D#3100]
**Description**

o3d.io.read_point_cloud() fails to read colors from a ply file with the headers below:

```
ply
format binary_little_endian 1.0
element vertex 1423059
property float x
property float y
property float z
property uchar diffuse_red
property uchar diffuse_green
property uchar diffuse_blue
end_header
```

no color information is read.

**To Reproduce**

```
pcd = o3d.io.read_point_cloud('file.ply')
pcd.colors => std::vector<Eigen::Vector3d> with 0 elements.
```

The colors for the point cloud are visible in several viewers (cloud compare, blender). Exported as a pcd from cloud compare, read_point_cloud() correctly reads the color information.

**Expected behavior**

```
pcd = o3d.io.read_point_cloud('file.ply')
pcd.colors => std::vector<Eigen::Vector3d> with 1423059 elements.
```

**Environment:**

- Windows 10 64-bit and Catalina 10.16.7
- Python 3.6
- Open3D 0.12.0
- Is this remote workstation?:  no
- conda install (windows and mac)

**Extra info:**

[example file](https://drive.google.com/file/d/16NQrVFmbKs_LCrtQy6vlX1pFy_G4RnOI/view?usp=sharing)

**Comment by nikhilpatil99** [comment]
How the ply file is generate ...? can I see the code..? depth image ..?

**Comment by tibbben** [comment]
I will try to get this information from my colleagues who created the files.

**Comment by tibbben** [comment]
The point cloud was created with the commercial software Pix4D, https://www.pix4d.com. We have created a workaround to modify the headers to use the labels red, green, blue instead of diffuse_red, diffuse_green, diffuse_blue (with the package plyfile). With the headers below the file now loads correctly:

```ply
format binary_little_endian 1.0
element vertex 1423059
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
end_header```

In any case, it would be great if open3D could read alternative headers from ply files. I believe there are several alternatives for red, green, blue, but you probably know more than I :).

**Comment by reyanshsolis** [comment]
![image](https://user-images.githubusercontent.com/32535717/142899334-542ab70a-ed7e-40e7-9ed9-4b6356810a64.png)

Seems to work fine for me. Could you please try again with the master branch?

**Comment by reyanshsolis** [comment]
Yes, you are right, currently we support only  `red / blue / green` name in header, we may add more combinations, in future.

The Tensor based IO (open3d.t.io), allows custom attributes in `.ply`, `.pcd` formats, so, you may load using that and combine the attributes of name `diffused_red, diffused_green, diffused_blue` in the `color` attribute using `concatenate/append` op. 

I can help you with the same if you want. Let me know if that resolves your issue.

**Comment by reyanshsolis** [comment]
http://paulbourke.net/dataformats/ply/
`diffused_` attributes are user-defined attributed, and are currently not supported by Open3D. 
if you rename them to `red`, `blue`, `green` they should work fine. 

Thanks.
