### ISSUE TITLE
Programmatically know if global optimization failed

### ISSUE THREAD

**Issue by erezposner** [isl-org/Open3D#3111]
Hi, how can I know programmatically that the pose graph optimization failed?
Running this code below does not indicate whether the process failed besides the verbose.

I wonder if there is a way to get it as a success/fail flag. 
Thanks
```
        with o3d.utility.VerbosityContextManager(o3d.utility.VerbosityLevel.Info) as cm:
            o3d.registration.global_optimization(
                pose_graph, o3d.registration.GlobalOptimizationLevenbergMarquardt(),
                o3d.registration.GlobalOptimizationConvergenceCriteria(), option)
```

**Comment by medico2** [comment]
i think the whole idea of "option" is that it runs until the criteria is met.
you can check the result of the pose graph to see if it mets your criteria

ps. i dont know much about open3d, take it for what it's worth

**Comment by theNded** [comment]
It is still an open question whether global optimization succeeds. Only under certain circumstances with certain assumptions can we verify the optimality, for example, see [this paper](https://arxiv.org/abs/1612.07386).
