### ISSUE TITLE
Remove impure build steps

### ISSUE THREAD

**Issue by rowanG077** [isl-org/Open3D#3130]
**Is your feature request related to a problem? Please describe.**
The last day and a half I have been struggling to get Open3D working with the Nix package manager (https://nixos.org/). The main struggle is that the build is not allowed to fetch any remote dependencies. And Open3D does this all over the place.

**Describe the solution you'd like**
I would like to patch the build system to allow for the build system to not download any external dependencies and allow a user to specify them upfront.

**Comment by yxlao** [comment]
Open3D makes heavy use of CMake's `ExternalProject_Add`, which, fetches external code at **build** time (not at **config** time or **clone** time). Are we aware of some workarounds to make `ExternalProject_Add` work for the Nix package manager?

One idea is to allow downloading from local URLs, e.g. in `3rdparty/mkl/mkl.cmake` we allow users to download MKL to `${OPEN3D_THIRD_PARTY_DOWNLOAD_DIR}` in their local machine, and CMake will pick it up from there. This is not an elegant way though -- you'll need to change all `ExternalProject_Add` and manage the downloaded files manually.

**Comment by rowanG077** [comment]
Yes that's what I patched in my local repo.

https://github.com/intel-isl/Open3D/compare/v0.12.0...rowanG077:v0.12.0-nix

I made a lot of `ExternalProject_Add` refer to local URLS with a remote fallback. This allows me to write a nix expressions essentially open3d depends on these 3rd party libraries. This seems to work.

My main question is can I upstream this? Please note that my branch is not really cleaned yet with proper fallback urls. But it demonstrates the principle.

**Comment by fricklerhandwerk** [comment]
Also working on building with `nix` and stumbled upon this issue. It was recently addressed by #3689. Thanks!

**Comment by rowanG077** [comment]
@fricklerhandwerk If you have an expression please let me know! Currently I just wrap compiled the pypi release...

**Comment by fricklerhandwerk** [comment]
I was trying to approach it from scratch, but this is too much of a beast to do in one afternoon. Can you share your wrapper?

**Comment by rowanG077** [comment]
@fricklerhandwerk Sure: https://gist.github.com/rowanG077/6e12b2edda19aa9179b238bc442acaa3

I didn't update to 0.13 yet so it's still the 0.12 release. But I think it shouldn't be too update. But be aware the cuda stuff takes ages to compile.

**Comment by ssheorey** [comment]
After PR #3689 , all dependencies will first be checked in a local folder (`Open3D/3rdparty_downloads`), so you can download them once and re-use for the build step. Please check `master` (v0.13+) and let us know if this is sufficient for you.

**Comment by theNded** [comment]
Should have been fixed in #3689. Please feel free to reopen.
