### ISSUE TITLE
Writing Poinclouds generated from 3D scanning continuously in the same file

### ISSUE THREAD

**Issue by ammaryasirnaich** [isl-org/Open3D#3132]
Hi, i am new to open3d. I was looking to somehow record the point clouds generated from the real-world scene
continuously in the same file.fly  

while True:
      pcd = o3d.geometry.PointCloud.create_from_rgbd_image( rgbd_image, o3d.camera.PinholeCameraIntrinsic(cam) )
      o3d.io.write_point_cloud("PointcloudDataset.ply", pcd)

The above snippet code replaces the previous information, Also, I tried to concatenate the pcd variable which is an open3d.cuda.pybind.geometry.PointCloud type but it doesn't seem to support the concatenation.

Please can one suggest a better way to write in a real-time fashion?

**Comment by satej1210** [comment]
You can convert the point cloud to a numpy array. Then grab the old points and convert the numpy array to a point cloud object.

[This page](http://www.open3d.org/docs/latest/tutorial/geometry/working_with_numpy.html) from the Open3D documentation will help you understand this conversion process better.

Here's some sample code to help you get started:
```
import numpy as np

# Something to help know if the "PointcloudDataset.ply" file was actually created
file_created = False

while True:
    pcd = o3d.geometry.PointCloud.create_from_rgbd_image( rgbd_image, o3d.camera.PinholeCameraIntrinsic(cam) )
    
    # if PointcloudDataset.ply was not created, then store the pcd in that file
    if not file_created:
        o3d.io.write_point_cloud("PointcloudDataset.ply", pcd)
        file_created = True
    
    else:
        old_pcd = o3d.io.read_point_cloud("PointcloudDataset.ply")

        # Get old and new points from point cloud
        old_points = np.asarray(old_pcd.points)
        new_points = np.asarray(pcd.points)

        # Concatenate old and new points
        concatenated_points = np.concatenate((old_points, new_points), axis=0)

        # Convert points to pointcloud
        concatenated_pcd = o3d.geometry.PointCloud()
        o3d.io.write_point_cloud("PointcloudDataset.ply", pcd)
        concatenated_pcd.points = o3d.utility.Vector3dVector(concatenated_points)
        o3d.io.write_point_cloud("PointcloudDataset.ply", concatenated_pcd)
```

**Comment by theNded** [comment]
@satej1210 thanks for the answer! Issue closed for now, please feel free to reopen.
