### ISSUE TITLE
Activate ICP on a subset of points based on a condition on angle between local normals of two point clouds for ICP 

### ISSUE THREAD

**Issue by NicolasBourbakis** [isl-org/Open3D#3139]
Hello, 
Beginner here, sorry for the amateur question if it is...
I'm trying to use ICP point to point to register several point clouds in a building. It work "too" well, meaning that the ICP try to match the two opposites faces of wall together (like if the wall had no thickness).
Can I use the CorrespondenceCheckerBasedOnNormal criteria in a Registration based on Point to Point ICP to avoid matching on points not on planes with the same orientation? 
http://www.open3d.org/docs/0.8.0/python_api/open3d.registration.CorrespondenceCheckerBasedOnNormal.html

**Comment by reyanshsolis** [comment]
I guess it will be easier to add the constraint in compute kernel of the transformation_estimation for the point-to-plane icp. 
You may refer to the existing implementation and change the source code according to your use case.

we don't have immediate plans to add this feature, but I will surely keep this in mind, and implement it in future when I get bandwidth for the same. 

Thanks.
