### ISSUE TITLE
in  china,how to fast download thirdparty files, look here!

### ISSUE THREAD

**Issue by VegetableWithChicken** [isl-org/Open3D#3150]
**in china ,because of XX,git clone very slowly ,so ,i change the .gitmodules to solve it **
[click here](https://github.com/VegetableWithChicken/Open3D)

1,we can change all git link "https://github.com/ "to "https://github.com.cnpmjs.org/"  of .gitmodules   in files
if find Eigen module failed，you can download release and put it in Open3D\3rdparty\Eigen files
2，not pybind11 files：delete  Open3D\3rdparty\pybind11 file，right click open3d file，git clone https://github.com.cnpmjs.org/pybind/pybind11.git  to download it

**Comment by theNded** [comment]
You may go through the `3rdparty` folder and change the git links in relevant CMake files with the git mirror links.
