### ISSUE TITLE
Open3d Transformation

### ISSUE THREAD

**Issue by adrian11655** [isl-org/Open3D#3153]
Hi, I use the following program to translate and rotate the axis. 
The first method is with copy.deepcopy(mesh).translate(translation) and mesh_t.rotate(R). And the second method is with mesh2.transform(T). 
However, the results obtained by the two methods are not coincident, and there is a small space between the transformed axes. 
The URL of the image link shown is: 
![image](https://user-images.githubusercontent.com/74853097/110558416-704e3200-817d-11eb-98d8-1b7adcf96f9f.png)
Thank you.

# program
import open3d as o3d
import math
import numpy as np 
import copy

rotate_angle = np.array([0,2*np.pi/3, np.pi])
translation = np.array([1, 2, 0])

mesh = o3d.geometry.TriangleMesh.create_coordinate_frame()
T = np.eye(4)
T[:3,:3] = mesh.get_rotation_matrix_from_xyz(rotate_angle)
T[0,3] = translation[0]
T[1,3] = translation[1]
T[2,3] = translation[2]

print(T)
mesh = o3d.geometry.TriangleMesh.create_coordinate_frame()
mesh_t = copy.deepcopy(mesh).translate(translation)
R = mesh_t.get_rotation_matrix_from_xyz(rotate_angle)
mesh_tranform1 = mesh_t.rotate(R)
print(R)

mesh = o3d.geometry.TriangleMesh.create_coordinate_frame()
mesh2 = copy.deepcopy(mesh)
mesh_tranform2 = mesh2.transform(T)
o3d.visualization.draw_geometries([mesh, mesh_tranform1, mesh_tranform2])

**Comment by chiarapalu** [comment]
Hey adrian, I'm facing the same problem. Did you solve it? I'm using 1.global+icp refinement and 2. icp registration only to register an object in a point cloud. If I only use the icp registration method and then extract the euler angles and translation vector from the matrix, applying directly the transform or translate+rotate doesn't make a difference, while if I use a global registration method then the translate+rotate doesn't work anymore. this is driving me crazy

**Comment by reyanshsolis** [comment]
Hi,

Rotate Geometry function rotates about the geometry's centre by default. 
So, `Rotate` operation is: `X = [R . (X - C)] + C` where `C` is the `centre` (which is `X_mean` by default).
Therefore `Rotate -> Translate` operation is: `X = [R . (X - C)] + C + t`.

Whereas, `Transform` is: `X = T . X`.

Therefore the following code gives the correct output (rotate with origin as centre):
```python
import open3d as o3d
import math
import numpy as np
import copy

mesh = o3d.geometry.TriangleMesh.create_coordinate_frame()

rotate_angle = np.array([0,2*np.pi/3, np.pi])
translation = np.array([1, 2, 0])
R = mesh.get_rotation_matrix_from_xyz(rotate_angle)
T = np.eye(4)
T[:3,:3] = R
T[0,3] = translation[0]
T[1,3] = translation[1]
T[2,3] = translation[2]

X = copy.deepcopy(mesh)
X0 = np.array([0, 0, 0])
X = X.rotate(R, X0)
X = X.translate(translation)
mesh_transform1 = X

X2 = copy.deepcopy(mesh)
mesh_transform2 = X2.transform(T)
o3d.visualization.draw_geometries([mesh_transform1, mesh_transform2])
```

Thanks!
