### ISSUE TITLE
Getting point in point cloud that corresponds with mouse location

### ISSUE THREAD

**Issue by cygann** [isl-org/Open3D#3161]
Hi,

I'm looking to add a feature to a custom python open3d gui visualization where upon either hovering or selecting a point in a displayed point cloud, the point index can be extracted (Such as what the old VisualizerWithVertexSelection class would accomplish) for displaying some simple statistics about it. 
I see there is a new mouse events class, but I'm not sure how exactly to leverage the mouse event location to extract what point the click/hover corresponds to. Is there a way to do this?

Any input or suggestions would be much appreciated!

**Comment by prewettg** [comment]
This already exists in the O3DVisualizer: under Mouse Selection click on the Selection tab. Ctrl click (Cmd click on macOS) will select a vertex, adding shift will unselect. See `examples/python/gui/draw.py` (or `examples/cpp/Draw.cpp`)

If you cannot use O3DVisualizer, you can do the same thing we do, which is set each point to be a slightly different color (assuming your background is white, index 0 = rgb(0, 0, 0), index 1 = rgb(0, 0, 1), etc.), render to an image, find the pixel that you clicked on, read back the color, and then convert to the index. You may find that you want to look at a certain radius of pixels around the one clicked on, as it can be easy to click on a point behind the point you actually want if they are nearby.

You might also want to look at the new `examples/python/gui/mouse-and-point-coord.py` example (see #3192), which overrides Ctrl/Cmd-click to read a point and convert to world coordinates. The point conversion is not what you are asking for, but it illustrates using the mouse events.

**Comment by prewettg** [comment]
Shoot, I just realized that you will need to disabling anti-aliasing and tone-mapping for this to work. You can use #3193 to set tone-mapping to linear, but we haven't exposed the ability to disable anti-aliasing yet, so I am re-opening this. (Anti-aliasing changes the color of the pixel at the border, which is no good because it is not actually a color, it is an index, so you get all kinds of craziness.)

**Comment by hduonggithub** [comment]
@prewettg 
Do you have a code for this idea?

> If you cannot use O3DVisualizer, you can do the same thing we do, which is set each point to be a slightly different color (assuming your background is white, index 0 = rgb(0, 0, 0), index 1 = rgb(0, 0, 1), etc.), render to an image, find the pixel that you clicked on, read back the color, and then convert to the index. You may find that you want to look at a certain radius of pixels around the one clicked on, as it can be easy to click on a point behind the point you actually want if they are nearby.

I did try this code, but the world coordinate returned from the lick is not correct. Any suggestion to make it right? Thanks
The issue was shown in here, https://github.com/intel-isl/Open3D/discussions/3736#discussioncomment-1044890
> You might also want to look at the new examples/python/gui/mouse-and-point-coord.py example (see #3192), which overrides Ctrl/Cmd-click to read a point and convert to world coordinates. The point conversion is not what you are asking for, but it illustrates using the mouse events.
