### ISSUE TITLE
Assimp won't load OBJ through Open3D python (and Open3D's warning message doesn't help!)

### ISSUE THREAD

**Issue by meder-yembo** [isl-org/Open3D#3166]
**Describe the bug**
I am outputting OBJ files from an iOS app, and trying to read them with the Python Open3D interface, but Open3D seems unable to read them. Meshlab, Blender, and really every other 3D viewer I've tried seems to read the file just fine. This is almost certainly an Assimp issue, but Open3D doesn't expose the Assimp error through Python at least. All I get is the following:

```
[Open3D WARNING] Unable to load file model.obj with ASSIMP
[Open3D DEBUG] Read geometry::TriangleMesh: 0 triangles and 0 vertices.
```
Does anyone know what the issue is here?

Secondly, is it possible to expose more of the underlying error messages to Python in `VerbosityLevel.Debug`? Alternatively, maybe add an even more verbose level, like `VerbosityLevel.Everything`.

**To Reproduce**

1. Install Open3D 0.12.0 for python: `pip install -y open3d==0.12.0`
2. Download the attached OBJ and MTL files (zipped as [model.zip](https://github.com/intel-isl/Open3D/files/6127118/model.zip))
3. Navigate to directory where you put the downloaded file
2. Start a Python console (e.g. `python3`):
```
import open3d as o3d
o3d.utility.set_verbosity_level(o3d.utility.VerbosityLevel.Debug)
mesh = o3d.io.read_triangle_mesh("model.obj")
```

**Expected behavior**
The model should load just fine and show 10,096 vertices and 16,145 faces.

**Environment (please complete the following information):**

- Operating system: Ubuntu 20.04
- Python version: Python 3.8
- Open3D version: 0.12.0
- Is this remote workstation?: no, but it is a headless Docker environment. Other files work though--it's unlikely related to any rendering stuff.
- How did you install Open3D?: pip

**Comment by hernot** [comment]
could you please create a patchfix which temporarily switches back to your own read obj method until assimp stuff is solved cause it seems it is a not yet solved assimp library itself  (https://github.com/assimp/assimp/issues/2063) which might take longer to solve.
