### ISSUE TITLE
OAK-D support?

### ISSUE THREAD

**Issue by TheBricktop** [isl-org/Open3D#3168]
Hello,
since Luxonis released their stereo depth enabled camera with neural Myriad coprocessor, could Open3d be used with it?
Especially with OpenVino models being run on the ai processor for object recognition .

**Comment by TheBricktop** [comment]
Oh sorry.

**Comment by theNded** [comment]
Unfortunately we don't have the bandwidth to support additional sensors. Please feel free to make a PR if you are interested in contributing.
