### ISSUE TITLE
Extrude a 3D triangulation into a watertight mesh.

### ISSUE THREAD

**Issue by HollowHeartNet** [isl-org/Open3D#3185]
Dear community, 

it would be very helpful to implement a function for mesh / surface extrusion in order to create a "thickness" for plane meshes. The newly created mesh would be watertight. As far as I know, there is an implementation available for 2D mesh extrusion, but I haven't found any implementation for 3D meshes. 

Hope you will consider this feature request for future developments. 

Thank you in advance!

Best,

**Comment by benjaminum** [comment]
To create a plane with some thickness a flat cube could be used instead.
Extrusion is often implemented in interactive/visual mesh editing software packages like Blender.
Can you provide more information on how this feature would be used?
