### ISSUE TITLE
Return vertices_deleted ids for mesh simplification

### ISSUE THREAD

**Issue by rfalcon100** [isl-org/Open3D#3210]
## **Is your feature request related to a problem? Please describe.**
Currently, mesh simplification functions (such as `simplify_quadric_decimation()` or `simplify_vertex_clustering()` return the simplified mesh. However, the ids of the deleted vertices and triangles is lost. These ids are needed when working with additional surface or vertex properties (e.g. semantic classes per surface).

## **Describe the solution you'd like**
I would like to let the mesh simplification return the modified mesh, as well as the list of vertices and triangle ids that where deleted. Something like:

```python
mesh_smp, vertices_deleted_ids, surfaces_deleted_ids = mesh_in.simplify_vertex_clustering(
                voxel_size=voxel_size,
                contraction=o3d.geometry.SimplificationContraction.Average)
            print(
                f'Simplified mesh has {len(mesh_smp.vertices)} vertices and {len(mesh_smp.triangles)} triangles'
            )
            
# removed deleted items from lists of properties
smp_surface_properties = surface_properties[surfaces_deleted_ids]
smp_vertex_properties = vertex_properties[vertices_deleted_ids]
```

## **Describe alternatives you've considered**
The workaround that I currently apply is to use the `vertex_colors` array a pseudo labels for vertex properties. However, there is no workaround for surface properties.

## **Additional context**
It seems that the simplification functions are already using vectors of deleted ids. This feature would only require to change the return of the functions and expose them to the python API.

**Comment by benjaminum** [comment]
Thank you for describing a workaround. Would you consider contributing this functionality? Please let me know until then I will close the issue.
