### ISSUE TITLE
How can we do rgbd odometry with pointclouds instead of color and depth images?

### ISSUE THREAD

**Issue by SebasKoel** [isl-org/Open3D#3248]
Hi,

Happy Easter!
I'm making pointclouds of my color and depth images so I can do some preprocessing steps before the odometry pipeline, however   o3d.pipelines.odometry.compute_rgbd_odometry() takes in rgbd images. 

Is there a way to use the pointclouds or convert the pointclouds into rgbd images?

One sort of hack I tried was using the Visualizer to render the pointclouds and capture the depth float buffer.
```

import numpy as np
import open3d as o3d

def capture_depth(pcd, camera_parameters, do_render):
    viewer = o3d.visualization.Visualizer()
    viewer.create_window(width = 1280, height = 720)
    viewer.add_geometry(pcd)
    # comment viewer.run() if you don't want a window, set do_render=True when capturing buffer.
    viewer.run()

    control = viewer.get_view_control()
    control.convert_from_pinhole_camera_parameters(camera_parameters, allow_arbitrary=True)

    depth = viewer.capture_depth_float_buffer(do_render=do_render)
    viewer.destroy_window()
    viewer.close()
    return depth

img_path = 'depth_img_1.png'
depth = o3d.io.read_image(img_path)
camera_parameters = make_open3d_camera_parameters('intrinsics.txt')

pcd_depth1 = o3d.geometry.PointCloud.create_from_depth_image(depth, intrinsic, depth_scale=1000.0, depth_trunc=3)
captured_depth = capture_image(pcd_depth1,camera_parameters, False)
pcd_depth2 = o3d.geometry.PointCloud.create_from_depth_image(captured_depth, intrinsic,depth_scale=1000.0, depth_trunc=3)
captured_depth = capture_image(pcd_depth1,camera_parameters, True)
pcd_depth3 = o3d.geometry.PointCloud.create_from_depth_image(captured_depth, intrinsic,depth_scale=1000.0, depth_trunc=3)

print(pcd_depth1)
# PointCloud with 136324 points.
print(pcd_depth2)
# PointCloud with 67558 points.
print(pcd_depth3)
# PointCloud with 35563 points.
```
However a lot of points are lost doing it this way. Especially when you want to do this for all images in a loop without a window popping up.

Thanks in advance.

**Comment by sanskar107** [comment]
@SebasKoel capturing depth float buffer is the only method supported for now. You can try headless rendering for background processing http://www.open3d.org/docs/release/tutorial/visualization/headless_rendering.html

**Comment by SebasKoel** [comment]
@sanskar107 Thanks for the reply. I'll try the headless rendering. Do you know why there are less points after rendering, is there a way to keep all points?

**Comment by theNded** [comment]
It is suggested to use ICP for point clouds, as a projection of point clouds discard many information due to occlusions.
