### ISSUE TITLE
Global Optimization does not detect failed edges

### ISSUE THREAD

**Issue by Andyjk1406** [isl-org/Open3D#3254]
**Describe the bug**
Using global optimisation to optimise a pose graph of 10 clouds, I find that it will cluster the clouds into 2 correctly aligned clusters, but that these clusters are far apart in 3d space.

**To Reproduce**
I use a C++ copy of the Python tutorial. I set all edges as uncertain (no odometry data), with the following params

open3d::pipelines::registration::GlobalOptimizationOption option(voxel_size * 0.5, 0.25, 2.0, 0); // Reference node is zero

and I use FastGlobalRegistration to get pairwise intital guesses, pruning any with less than 500 correspondences.

**Expected behavior**
Expect the line processes to break where there is a clear conflict between edges, or I expect all  alignments to be in one global space

Output from optimiser is...

Optimizing PoseGraph ...[Open3D WARNING] Certain-edge subset of PoseGraph is not connected.
[Open3D DEBUG] Validating PoseGraph - finished.
[Open3D DEBUG] [GlobalOptimizationLM] Optimizing PoseGraph having 10 nodes and 23 edges.
[Open3D DEBUG] Line process weight : 1278.642609
[Open3D DEBUG] [Initial     ] residual : 1.446377e+10, lambda : 3.575356e-03
[Open3D DEBUG] [Iteration 00] residual : 2.940711e+04, valid edges : 0, time : 0.000 sec.
[Open3D DEBUG] [Iteration 01] residual : 2.940488e+04, valid edges : 0, time : 0.000 sec.
[Open3D DEBUG] [Iteration 02] residual : 2.940316e+04, valid edges : 0, time : 0.000 sec.
[Open3D DEBUG] [Iteration 03] residual : 2.940105e+04, valid edges : 0, time : 0.000 sec.
[Open3D DEBUG] [Iteration 04] residual : 2.939611e+04, valid edges : 0, time : 0.000 sec.
[Open3D DEBUG] [Iteration 05] residual : 2.937980e+04, valid edges : 0, time : 0.000 sec.
[Open3D DEBUG] [Iteration 06] residual : 2.899959e+04, valid edges : 1, time : 0.000 sec.
[Open3D DEBUG] [Iteration 07] residual : 2.833862e+04, valid edges : 1, time : 0.000 sec.
[Open3D DEBUG] [Iteration 08] residual : 2.777721e+04, valid edges : 2, time : 0.000 sec.
[Open3D DEBUG] [Iteration 09] residual : 2.688095e+04, valid edges : 4, time : 0.000 sec.
[Open3D DEBUG] [Iteration 10] residual : 2.454944e+04, valid edges : 4, time : 0.000 sec.
[Open3D DEBUG] [Iteration 11] residual : 2.309422e+04, valid edges : 6, time : 0.000 sec.
[Open3D DEBUG] [Iteration 12] residual : 2.202935e+04, valid edges : 6, time : 0.000 sec.
[Open3D DEBUG] [Iteration 13] residual : 2.138075e+04, valid edges : 6, time : 0.000 sec.
[Open3D DEBUG] [Iteration 14] residual : 1.946444e+04, valid edges : 9, time : 0.000 sec.
[Open3D DEBUG] [Iteration 15] residual : 1.798333e+04, valid edges : 10, time : 0.000 sec.
[Open3D DEBUG] [Iteration 16] residual : 1.706756e+04, valid edges : 10, time : 0.001 sec.
[Open3D DEBUG] [Iteration 17] residual : 1.684637e+04, valid edges : 10, time : 0.000 sec.
[Open3D DEBUG] [Iteration 18] residual : 1.680052e+04, valid edges : 10, time : 0.000 sec.
[Open3D DEBUG] [Iteration 19] residual : 1.655739e+04, valid edges : 14, time : 0.000 sec.
[Open3D DEBUG] [Iteration 20] residual : 5.535660e+03, valid edges : 23, time : 0.000 sec.
[Open3D DEBUG] [Iteration 21] residual : 9.776444e+02, valid edges : 23, time : 0.000 sec.
[Open3D DEBUG] [Iteration 22] residual : 9.412858e+02, valid edges : 23, time : 0.000 sec.
[Open3D DEBUG] [Iteration 23] residual : 9.398126e+02, valid edges : 23, time : 0.000 sec.
[Open3D DEBUG] [Iteration 24] residual : 9.397462e+02, valid edges : 23, time : 0.000 sec.
[Open3D DEBUG] [Iteration 25] residual : 9.397426e+02, valid edges : 23, time : 0.000 sec.
[Open3D DEBUG] Current_residual - new_residual < 1.000000e-06 * current_residual
[Open3D DEBUG] [GlobalOptimizationLM] total time : 0.008 sec.
[Open3D DEBUG] [GlobalOptimizationLM] Optimizing PoseGraph having 10 nodes and 23 edges.
[Open3D DEBUG] Line process weight : 1278.642609
[Open3D DEBUG] [Initial     ] residual : 9.397424e+02, lambda : 1.650853e+05
[Open3D DEBUG] Delta.norm() < 1.000000e-06 * (x.norm() + 1.000000e-06)
[Open3D DEBUG] [GlobalOptimizationLM] total time : 0.000 sec.
[Open3D DEBUG] CompensateReferencePoseGraphNode : reference : 0

...and the final pose graph (below) shows that, for example, cloud 0 has a high confidence alignment to 1,2,3,4,5,6,7,8 and then cloud 9 is aligned to cloud 5) so this should hold all clouds in the same global space, or if the alignments are poor, it should break the line processes.

Refined...
1 to 2 with confidence 0.99288
7 to 8 with confidence 0.980045
**0 to 1** with confidence 0.996186
4 to 5 with confidence 0.838871
6 to 8 with confidence 0.877083
**0 to 2** with confidence 0.994942
5 to 7 with confidence 0.905835
4 to 6 with confidence 0.954441
9 to 5 with confidence 1
4 to 7 with confidence 0.932975
**0 to 3** with confidence 0.999863
3 to 6 with confidence 0.992257
4 to 8 with confidence 0.958431
1 to 4 with confidence 0.962568
1 to 5 with confidence 0.929414
**0 to 4** with confidence 0.970561
1 to 6 with confidence 0.826677
**0 to 5** with confidence 0.933041
1 to 7 with confidence 0.898484
**0 to 6** with confidence 0.87981
1 to 8 with confidence 0.905028
**0 to 7** with confidence 0.908041
**0 to 8** with confidence 0.931979

**Screenshots**
Example of 10 clouds that have ended up in two clusters
![image](https://user-images.githubusercontent.com/32988487/113703040-387dd000-96d2-11eb-99f0-f02248028a05.png)

**Environment (please complete the following information):**

- Operating system: Windows 10 64-bit)
- Python version: Python 3.6
- Is this remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version Visual Studio 2019
- 
**Additional context**
How can the confidence remain so high for all edges for cloud 0, when there must be a clear error in pose to cause the resulting two clusters of clouds? Why are the line processes not decreasing enough to detect this?

**Comment by Andyjk1406** [comment]
I think I've worked this out. The optimiser thinks its solved this because the transformation is very small, and the rotation matrix is basically 180 degrees around Y between the two clusters of clouds.
I guess this 180 degree rotation causes some local minimum in the optimiser.

The issue therefore, is not having good initial poses (I set them all to identity, assuming that given all the good edges, the initial pose does not matter). 
I think that instead, the LM optimisation still requires a half-decent initial pose guess (in addition to good edge transformations). Maybe at least in the correct quadrant). Maybe this should be documented more clearly?

**Comment by theNded** [comment]
We shall improve the documentation of the pose graph optimization. Robust pose graph optimization is challenging, and even the state-of-the-art solution, e.g. [SE(3)-Sync](https://arxiv.org/abs/1612.07386) cannot guarantee a successful convergence.
