### ISSUE TITLE
Global registration with scaling not working

### ISSUE THREAD

**Issue by pranavkhekare** [isl-org/Open3D#3270]
I am trying to implement the global registration function from Open3d. Trying to register a small cylinder to transform and scale into a large cylinder. After changing the orientation of the cylinder and applying transformation, the small cylinder orients perfectly with the large cylinder but does not scale even after setting the scaling flag to True for the `o3d.pipelines.registration.TransformationEstimationPointToPoint` function. Does anyone know if the scaling flag works on the global registration function?

**Comment by theNded** [comment]
The scale estimation is not necessarily working, especially when the scale difference is large. According to the [underlying Umeyama method](http://web.stanford.edu/class/cs273/refs/umeyama.pdf), it may only work if a good initial correspondence is known.
