### ISSUE TITLE
Support for rendering 3d polygon meshes

### ISSUE THREAD

**Issue by johnwlambert** [isl-org/Open3D#3301]
Hi Open3D team, thanks for all your work on putting together a great library.

Feature request -- currently it appears that Open3D can only supports rendering 3d points, 3d lines, or 3d triangle meshes.

It would be quite helpful if 3d polygon meshes could also be specified via the Open3D API, instead having to triangulate/tesselate polygons into triangles beforehand.

This would mean supporting something like `glBegin(GL_POLYGON)` instead of just `GL_POINTS`, `GL_LINES`, `GL_TRIANGLES`.

**Comment by johnwlambert** [comment]
Hi @ssheorey, any update on whether this might be considered in the future? Thanks very much.

**Comment by errissa** [comment]
@johnwlambert Unfortunately, this will not be possible. The rendering backend uses modern versions of OpenGL and the immediate mode `glBegin/glEnd` is not available. One possibility to simplify a user's workflow would be a `PolygonMesh` class that (like `TriangleMesh`) that seamlessly tessellates when a user visualizes a `PolygonMesh`. We have no plans to implement a `PolygonMesh` but would more than welcome a contribution!
