### ISSUE TITLE
Bug: Visualizer window size not set properly, and cannot be changed

### ISSUE THREAD

**Issue by johnwlambert** [isl-org/Open3D#3303]
**Describe the bug**
There appears to be 2 bugs -- the visualizer window size cannot be changed. It neither reflects what was requested in the constructor, nor does update work using `convert_from_pinhole_camera_parameters()`.

Run the following code:
```python
import open3d as o3d

vis = o3d.visualization.Visualizer()

vis.create_window(
	width = 1550,
	height = 2048
)
ctr = vis.get_view_control()

param = ctr.convert_to_pinhole_camera_parameters()
print(param.intrinsic)
param.intrinsic.width = 2000
param.intrinsic.height = 3000

ctr.convert_from_pinhole_camera_parameters(param, allow_arbitrary=True)

vis.poll_events()
vis.update_renderer()

print(ctr.convert_to_pinhole_camera_parameters().intrinsic)
```
This prints:
```bash
python open3d_bug.py 
PinholeCameraIntrinsic with width = 1848 and height = 1016.
Access intrinsics with intrinsic_matrix.
PinholeCameraIntrinsic with width = 1848 and height = 1016.
Access intrinsics with intrinsic_matrix.
```

**Expected behavior**
I would expect the visualizer window size to be immediately reflected in the pinhole parameters (should be 2048x1550) not 1016 x 1848. I would also expect the window size to be updated to 2000x3000

**Environment (please complete the following information):**

- Operating system: Ubuntu 20.04.1 x86_64 
- Python version: Python 3.7.10
- Open3D version: '0.12.0'
- Is this remote workstation?: yes
- How did you install Open3D?: pypi/pip

**Comment by johnwlambert** [comment]
Hi @prewettg and @sanskar107, thanks for taking a look at this. Just as an update -- I see the window size set correctly for the `OffscreenRenderer` -- but not for the on-screen version, i.e. `o3d.visualization.Visualizer()`

**Comment by prewettg** [comment]
The old visualizer does not support programmatically changing its size. However, the intrinsic parameters are intended to model a pinhole camera for processing an image captured from a camera sensor. My understanding is that when these are used for visualization, it is so that the 3D objects are rendered with the same transformations that happened in the physical camera. This would enable, for example, rendering 3D geometry extracted from camera + depth on top of the camera image for debugging or augmented reality applications. Since the intrinsics models the physical camera, changing the the width/height reflects the physical camera changing the number of pixels it has. Although it may be convenient to have the window be the same size as the incoming image, from a 3D rendering standpoint the size of the window does not matter, things will just be able to have more or less detail.

It's possible you are trying to do something we did not envision; have I understood your use case properly?

**Comment by johnwlambert** [comment]
Hi @prewettg, thanks very much for your reply.

Indeed I'm interested in the use case where a rendering would be pixel-perfect w.r.t. to sensor images, e.g. for AR.

Two questions/comments on my end:
(1) My understanding was that v0.12 had the latest visualizer (I'm using v0.12). Does v.012 have the "old visualizer"?
(2) I do find it weird that the `o3d.visualization.Visualizer()` `create_window()` call would accept width and height arguments, if they are ignored. This seems like a bug.

If there's any way you all could provide this functionality, it would be quite useful. The current defaults appear to be width = 1848 and height = 1016, and I'm interested in a camera with larger resolution, so I cannot just take a center crop or something of that nature.

Thanks again for your time.

**Comment by prewettg** [comment]
The "old visualizer" is `o3d.visualization.Visualizer` and `o3d.visualization.draw_geometries()` and the "new visualizer" is `o3d.visualization.O3DVisualizer` and `o3d.visualization.draw()`. Both are available in 0.12, although new development is not happening on the old visualizer and it will be deprecated soon. Unfortunately, the new visualizer does not support configuring the camera with an intrinsic/extrinsic matrix, although #3338 will add support for that when it is merged. (It will not change the window size, either, though, for the same reasons as described above.)

If create_window() did ignore it's width and height arguments, that would be a bug. I didn't realize that there were two bugs reported here, and just focused on the resizing. I've tried running your script above on both Ubuntu 18.04 and Linux, and they size correctly. I'm using the Ubuntu defaults; have you configured your DPI settings or window scaling settings? Or perhaps 20.04 automatically configures them?

**Comment by johnwlambert** [comment]
Got it -- thanks for putting in the work on the new `O3DVisualizer`, that's cool to see your PR. I hope it gets merged soon, and new wheels get added as well : - )

I haven't modified my window scaling settings, so I believe this would likely be auto-configured on 20.04.

On another note, would it be possible to add the option of loading extrinsic and intrinsic parameters to the `OffscreenVisualizer` as well? The `lookat` method seems to be the only way of configuring that, which isn't as useful for me.

**Comment by prewettg** [comment]
That's a good idea, although surprisingly troublesome to implement. I've added it to #3338, so you should be able to use OffscreenRenderer.setup_camera with FoV + look_at params, or intrinsics.

**Comment by johnwlambert** [comment]
I saw #3338 got merged @prewettg -- thanks very much for your work on that. I'm happy to mark this closed if we can get it in a new release : - )
