### ISSUE TITLE
Why is the mesh rendering result different from the point cloud rendering?

### ISSUE THREAD

**Issue by Lemon-XQ** [isl-org/Open3D#3308]
Hi, I met with a problem: when I use the **gui** module to display a model(.ply format, **with face information**), I find the rendering result is different if I load it in two ways: mesh and point cloud. It seems that the point cloud rendering result is right while the mesh rendering is strange. I don't know if there are some settings that I should set for mesh rendering? 

My code is like this, and the mesh rendering result and point cloud rendering result are shown below:
```
......
app = gui.Application.instance
self.window = app.create_window("Visualization", 1280, 720)
self.window.set_on_layout(self._on_layout)
self.widget3d = gui.SceneWidget()
self.window.add_child(self.widget3d)

self.widget3d.scene = rendering.Open3DScene(self.window.renderer)
self.widget3d.scene.set_background([0, 0, 0, 0])

#pcd = o3d.io.read_point_cloud(self.ply_path) # point cloud
pcd = o3d.io.read_triangle_mesh(self.ply_path) # mesh

mat = rendering.Material()
mat.shader = "defaultUnlit"
self.widget3d.scene.add_geometry("Point Cloud", pcd, mat)
......
```

- Mesh rendering result
![image](https://user-images.githubusercontent.com/25324194/115218695-67b42880-a139-11eb-9548-60a4e1eec071.png)

- Point cloud rendering result
![image](https://user-images.githubusercontent.com/25324194/115218681-6420a180-a139-11eb-9ff6-04ba4c47a737.png)

**Comment by theNded** [comment]
By default point normals are explicitly calculated for mesh visualization, while it is not for point clouds. Normals control the appearance and illuminations are emphasized, so it looks white-ish. Disabling the lighting and/or playing with the lighting intensity should change the appearance.
