### ISSUE TITLE
assimp/lib/libIrrXML.a from  assimp/lib/libIrrXML.a

### ISSUE THREAD

**Issue by 43998213** [isl-org/Open3D#3309]
on jetson nano 
follow:

# Clone
git clone --recursive https://github.com/intel-isl/Open3D
cd Open3D
git submodule update --init --recursive
mkdir build
cd build

# Configure
# > Set -DBUILD_CUDA_MODULE=ON if CUDA is available (e.g. on Nvidia Jetson)
# > Set -DBUILD_GUI=ON if OpenGL is available (e.g. on Nvidia Jetson)
# > We don't support TensorFlow and PyTorch on ARM officially
cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=ON \
    -DBUILD_CUDA_MODULE=OFF \
    -DBUILD_GUI=OFF \
    -DBUILD_TENSORFLOW_OPS=OFF \
    -DBUILD_PYTORCH_OPS=OFF \
    -DBUILD_UNIT_TESTS=ON \
    -DCMAKE_INSTALL_PREFIX=~/open3d_install \
    -DPYTHON_EXECUTABLE=$(which python) \
    ..

# Build C++ library
make -j$(nproc)

[ 57%] Building CXX object cpp/open3d/io/CMakeFiles/io.dir/file_format/FileTUM.cpp.o
[ 58%] Building CXX object cpp/open3d/io/CMakeFiles/io.dir/file_format/FileXYZ.cpp.o
[ 58%] Building CXX object cpp/open3d/io/CMakeFiles/io.dir/file_format/FileXYZN.cpp.o
[ 58%] Building CXX object cpp/open3d/io/CMakeFiles/io.dir/file_format/FileXYZRGB.cpp.o
[ 58%] Built target io
[ 58%] Built target pipelines
Scanning dependencies of target Open3D
[ 58%] Building CXX object cpp/open3d/CMakeFiles/Open3D.dir/Open3DConfig.cpp.o
make[2]: *** no rules to make“assimp/lib/libIrrXML.a”，from“lib/Release/libOpen3D.so”stop
make[2]: *** ....
CMakeFiles/Makefile2:1287: recipe for target 'cpp/open3d/CMakeFiles/Open3D.dir/all' failed
make[1]: *** [cpp/open3d/CMakeFiles/Open3D.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

tk any help

**Comment by ssheorey** [comment]
Some dependencies are downloaded from the network during the build process. The process may fail if the network is not available or slow. Please ensure you have a good network connection in the device and retry the build from a clean `build` folder.
