### ISSUE TITLE
Slice a mesh with a plane or a polygon ?

### ISSUE THREAD

**Issue by xleEmesent** [isl-org/Open3D#3312]
Does Open3D support slicing a mesh with a plane and seal the mesh?

In trimesh, and meshMixer, both provide the function of cutting a mesh with a plane, return a cut mesh and intersected polygons. Does Open3D also has the similar function mesh module?

Thanks.

**Comment by benjaminum** [comment]
Unfortunately, we don't have this functionality at the moment. Is this something you would like to contribute or do you have more implementation pointers? Please let me know, closing the issue until then.
