### ISSUE TITLE
3d text example failing with windows error code: 2000

### ISSUE THREAD

**Issue by luke-sockhill** [isl-org/Open3D#3317]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
Running examples/python/gui/text3d.py fails with this error:

Windows error code: 2000. (null)

in void __cdecl filament::PlatformWGL::makeCurrent(struct filament::backend::Platform::SwapChain *,struct filament::backend::Platform::SwapChain *) noexcept:241
reason: wglMakeCurrent() failed. hdc = 0000000004010C83

**To Reproduce**

1. Simply run this file

**Expected behavior**

Expected the 3d text example to work correctly

**Screenshots**
This is the GUI window that pops up
![image](https://user-images.githubusercontent.com/73573957/115472523-63912380-a27d-11eb-96bf-0e19bce78e19.png)

This is the error message:
![image](https://user-images.githubusercontent.com/73573957/115472815-f16d0e80-a27d-11eb-8236-cbb377892dc0.png)

**Environment (please complete the following information):**

- Operating system: Windows 10 64-bit
- Python version: Python 3.8.5
- Open3D version: Latest build from master (also had this problem on 0.12)
- Is this remote workstation?: no
- How did you install Open3D?: build from source (problem also happened from pip install of latest release)
- Compiler version (if built from source): cmake version 3.20.1

**Additional context**

**Comment by prewettg** [comment]
I've tried this using both Python 3.8 and 3.9 on Windows 10 and it works for me. The errors are within Filament (the rendering engine), not being able to use the OpenGL context. What graphics card are you using? Are you able to use other programs that use OpenGL? Are you using another OpenGL program at the same time as Open3D?

**Comment by luke-sockhill** [comment]
Hi I have updated my drivers for my integrated graphics: AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx 2.00 GHz

Is there a simple program I can run to test whether OpenGL is working correctly on my machine?

**Comment by prewettg** [comment]
I recommend [GLview](http://www.realtech-vr.com/home/glview). Check that OpenGL 4.1 is supported, it might be that your driver only supported 3.2 or something, which would fail with our renderer, which requires 4.1. It has a "Rendering tests" link-button in the left, too, that would be worth trying to verify that you can actually get a WGL context.

**Comment by luke-sockhill** [comment]
I've done all this and the rendering tests went fine, and. I have run the code on a different computer without issue so the code is not the problem. Any other thoughts?
![Uploading image.png…]()

**Comment by prewettg** [comment]
It seems like OpenGL is working okay, as both of us can run the example on different computers it must be something about this configuration. Do the other examples in `examples/python/gui` work? Are you running in a virtual machine, by any chance? The Vega 8 GPU only has 1GB of VRAM, is it possible that VRAM is being used up by the OS or other applications (high resolution external monitor(s), many large windows open, CAD program running, for example)? I would not expect VRAM to be a problem, since this example isn't going to use much, but I suppose you never know.

**Comment by ssheorey** [comment]
Closing since we can't reproduce it. Please test with the latest Open3D and reopen the issue if you still have this problem.

**Comment by Leerw** [comment]
I have the same issue with CPU AMD Ryzen 5 5600G with Radeon Graphics, but works well on intel cpu with a embedded graphics card.

**Comment by v479038280** [comment]
![屏幕截图 2023-04-27 234800](https://user-images.githubusercontent.com/25096045/234916847-57de02a9-af43-40d0-8184-41b5ffebc517.jpg)
I still have the same issue,how to solve it

**Comment by jrajpal5-singularity** [comment]
I am also facing this error when using the open3d visualizer programs. I have AMD ryzen 5 5600H and RTX 3050 Ti.
![image](https://user-images.githubusercontent.com/17953051/234936385-a817a85e-0328-4c3b-859a-7d74781ea6ec.png)

**Comment by rebaljber** [comment]
I have the same problem. any ideas how to fix it? many thanks

**Comment by pebbie** [comment]
> I am also facing this error when using the open3d visualizer programs. I have AMD ryzen 5 5600H and RTX 3050 Ti.

You need to go to NVIDIA Control Panel, 

go to 3D Settings > Manage 3D settings 

and in the Global settings tab, set preferred graphics processor as "High-performance NVIDIA processor".

the integrated (AMD GPU) option is not working (it's mentioned in the other ticket but it is not known when it will be solved).

**Comment by ssheorey** [comment]
If someone has this issue, please test with the filament rendering engine that Open3D uses. 

Download from: https://github.com/google/filament/releases
Run the gltf_viewer example from the bin folder.

If this doesn't run on your system, please open an issue in the filament repo. If it does, let us know here. Also, we don't have an AMD GPU, so we would need your help to submit a bugfix PR for this.

**Comment by Timezyxdev** [comment]
Hello @ssheorey, I am also experiencing this issue. Which release version of filament should be used for testing? I am having difficulty determining which version the filament engine that Open3D uses belongs to.

**Comment by organic-nailer** [comment]
Hi @ssheorey.
I have the same problem on my laptop (Windows11 23H2, AMD Ryzen 5 4500U with Radeon Graphics).

> If someone has this issue, please test with the filament rendering engine that Open3D uses.
> 
> Download from: https://github.com/google/filament/releases
> Run the gltf_viewer example from the bin folder.

I tested if the Filament(v1.9.19) example code works, and it worked. This result may indicate that this problem is not a bug in Filament.

![image](https://github.com/isl-org/Open3D/assets/31440714/6cd4f43a-1708-4a30-909f-b50fc06275a2)

**Comment by Gilabite** [comment]
Have the same problem with win11 and 7900XTX

**Comment by ICO-Fantasy** [comment]
I meet the same problem with Intel i7-14700 and AMD Radeon RX 550X
Based on the similar issues mentioned at https://github.com/google/filament/issues/994 as well as https://github.com/google/filament/pull/1021, this problem seems to be caused by a change in Windows?

**Comment by macsunmood** [comment]
The same issue with Ryzen 7 5700G (Vega 8) on Windows 11. Any chances on clearing this up ?
