### ISSUE TITLE
3d reconstruction on live feed from realsense L515

### ISSUE THREAD

**Issue by aditdoshi333** [isl-org/Open3D#3366]
Thank you for such an amazing repo. I am using 3d reconstruction of Open3d from .bag files. I am curious to know is it possible to do the same from the live feed of realsense L515. If yes is there any example for the same?

Thank you

**Comment by ssheorey** [comment]
Hi @aditdoshi333 you should be able to put something together for this based on some of the new features and examples. Have a look at these two PRs:
C++ Live reconstruction pipeline: https://github.com/intel-isl/Open3D/pull/3363
Python live capture from RealSense GUI example: https://github.com/intel-isl/Open3D/pull/3410

**Comment by maohong30** [comment]
Hi. I am able to run offline 3D surface reconstruction system and python live capture from Realsense GUI.  
I am still waiting for the new release of live 3D surface reconstruction in Python. Not knowing when the new release will be coming out, can I have some guide on how to do the online 3D surface reconstruction system in Python ? Thank You

**Comment by ssheorey** [comment]
Also see the new Tensor based reconstruction system tutorial and examples:
http://www.open3d.org/docs/release/tutorial/t_reconstruction_system/index.html
https://github.com/isl-org/Open3D/blob/master/examples/python/t_reconstruction_system/dense_slam_gui.py

Closing this issue. Please reopen this or a new issue if you have more questions.
