### ISSUE TITLE
Warning when I show 3d point cloud image in the jupyter notebook

### ISSUE THREAD

**Issue by yuchenlichuck** [isl-org/Open3D#3368]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
When I tried to show a point cloud 3d image in the jupyter notebook, there is a warning jump out of the windows. 
```
Notebook validation failed: {'version_major': 2, 'version_minor': 0, 'model_id': '51452704be354e37b8401fe164e0544a'} is not valid under any of the given schemas:
{
 "version_major": 2,
 "version_minor": 0,
 "model_id": "51452704be354e37b8401fe164e0544a"
}
```

**To Reproduce**

```
def draw_point_cloud(points, colors=None, normals=None):
    pc = open3d.geometry.PointCloud()
    pc.points = open3d.utility.Vector3dVector(points)
    if colors is not None:
        pc.colors = open3d.utility.Vector3dVector(colors)
    if normals is not None:
        pc.normals = open3d.Vector3dVector(normals)
    return pc


def visualize_point_cloud(points, colors=None, normals=None):
    pc = draw_point_cloud(points, colors, normals)
    #mesh_frame = open3d.geometry.TriangleMesh.create_coordinate_frame(size=1.0, origin=[0, 0, 0])
    #open3d.visualization.draw_geometries([pc, mesh_frame])
    visualizer = JVisualizer()
    visualizer.add_geometry(pc)
    visualizer.show()
```

**Expected behavior**

No warning
**Screenshots**
![image](https://user-images.githubusercontent.com/38585175/116746547-51458100-aa05-11eb-8125-d27ad7b7bd7a.png)

**Environment (please complete the following information):**

- Operating system:  Ubuntu 18.04,
- Python version: Python 3.7
- Open3D version:0.12.0
- Is this remote workstation?: yes
- How did you install Open3D?: conda,
- Compiler version (if built from source): gcc 7.5

**Comment by sanskar107** [comment]
@yuchenlichuck this feature will be supported in the next release (within a week). But you can try it out using latest master branch.
