### ISSUE TITLE
convert voxelgrid to numpy array

### ISSUE THREAD

**Issue by THHHomas** [isl-org/Open3D#3381]
how could we convert voxel grid to 3d numpy array(a cube)?
It seems that the voxelgrid is based on octree.

**Comment by sanskar107** [comment]
@THHHomas you can convert voxel grid to a list of voxels. This may be of some help http://www.open3d.org/docs/release/python_api/open3d.geometry.VoxelGrid.html#open3d.geometry.VoxelGrid.get_voxels
