### ISSUE TITLE
Illegal instruction (core dumped) in python at "import open3d"

### ISSUE THREAD

**Issue by tomatac** [isl-org/Open3D#3405]
**Describe the bug**
in python3 running:
`import open3d`
results in: "Illegal instruction (core dumped)"

**To Reproduce**
On an Nvidia Xavier NX (ARM), using install from source instructions:
http://www.open3d.org/docs/release/arm.html#nvidia-jetson

```
cmake \
    -DCMAKE_BUILD_TYPE=Release \g
    -DBUILD_SHARED_LIBS=ON \
    -DBUILD_CUDA_MODULE=ON \
    -DBUILD_GUI=ON \
    -DBUILD_TENSORFLOW_OPS=OFF \
    -DBUILD_PYTORCH_OPS=OFF \
    -DBUILD_UNIT_TESTS=ON \
    -DBUILD_EXAMPLES=ON \
    -DBUILD_JUPYTER_EXTENSION=ON \
    -DCMAKE_INSTALL_PREFIX=~/open3d_install \
    -DPYTHON_EXECUTABLE=$(which python) \
    ..

make -j$(nproc)

make install

make install-pip-package -j$(nproc)

python -c "import open3d; print(open3d)"
```

See error: "Illegal instruction (core dumped)"

**Environment:**

- Operating system: Ubuntu 18.04
- Python version: (e.g. Python 3.6.9)
- Open3D version: master branch
- Is this remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): (e.g. gcc 7.5.0, clang 7.0.0)

**Comment by ssheorey** [comment]
Hi @tomatac Please share your build logs (output of cmake and make).
