### ISSUE TITLE
ModuleNotFoundError: No module named'open3d.cpu' when build with GCC7.5.0

### ISSUE THREAD

**Issue by zpw6106** [isl-org/Open3D#3406]
I was able to build from the source with gcc7.5.0, import python module fails.
*The cmake flag are
```
$ cmake  \
      -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_SHARED_LIBS=ON \
      -DGLIBCXX_USE_CXX11_ABI=OFF \
      -DCMAKE_INSTALL_PREFIX=/usr/local \
      -DPYTHON_EXECUTABLE=/usr/bin/python3.6 \
      -DBUILD_CUDA_MODULE=ON \
      -DBUILD_PYTORCH_OPS=OFF \
      -DBUILD_TENSORFLOW_OPS=ON \
      -DBUNDLE_OPEN3D_ML=ON \
      -DOPEN3D_ML_ROOT=/home/zpw/third_party/Open3D-ML \
        ../           
$ make     
$ sudo make install     
$ make install-pip-package     
$ python3 -c "import open3d"       
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/zpw/.local/lib/python3.6/site-packages/open3d/__init__.py", line 75, in <module>
    from open3d.cpu.pybind import (camera, geometry, io, pipelines, utility, t)
ModuleNotFoundError: No module named 'open3d.cpu'
```

**I looked at a similar [problem](https://github.com/intel-isl/Open3D/issues/3141) and tried to modify it according to the instructions, but the error still exists** 
**This is my revised version**
`"buffer_size"_a = size_t{RSBagReader::DEFAULT_BUFFER_SIZE})`

I also use the nm command to check whether has undefined symbol like RSBagReader::DEFAULT_BUFFER_SIZEE. **output none**  
`$ nm -D lib/Release/Python/cuda/pybind.cpython-36m-x86_64-linux-gnu.so | grep RSBagReader`  
Check `libOpen3D.so` with nm command:
```
$ nm -D lib/Release/libOpen3D.so | grep RSBagReader  
0000000000bdd4f0 W _ZN6open3d1t2io11RSBagReader11GetMetadataEv
0000000000bdd510 W _ZNK6open3d1t2io11RSBagReader11GetFilenameEv
0000000000bdd4e0 W _ZNK6open3d1t2io11RSBagReader11GetMetadataEv
0000000000bdd500 W _ZNK6open3d1t2io11RSBagReader8IsOpenedEv
```

**Environment**
* Ubuntu18.04
* Python version: 3.6.9
```
$ python3
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by zpw6106** [comment]
Thank you very much, I rebuilt and created a python 3.8 virtual environment and successfully compiled it。

**Comment by heethesh** [comment]
This seems to be an issue with the `cudaGetDeviceCount` call and had nothing to do with the Open3D build system or the source. If you build Open3D with CUDA support and the device count is 0, it falls back to using `__DEVICE_API__ = 'cpu'` in `__init__.py` and this module is not present in the python package directory. First try building and running the `deviceQuery` example from `/usr/local/cuda/sample/1_Utilities` and ensure the `cudaGetDeviceCount` call works. Rebooting my system resolved the issue.

**Comment by ssheorey** [comment]
Enable python warnings to get some debugging information in such cases:

`python -W default -c "import open3d as o3d"`

**Comment by heethesh** [comment]
@ssheorey thanks, I was wondering why those warning were not being shown in the first place.

**Comment by PhuongNDVN** [comment]
I got the same error. I installed Open3d by source with CUDA is ON on Jetson Orin. The libOpen3D.so is saved in /usr/local/lib. The error in detail is:

```
python -W default -c "import open3d as o3d"
/home/zootos/miniconda3/envs/scanner3d/lib/python3.8/site-packages/open3d/__init__.py:63: ImportWarning: Open3D was built with CUDA support, but Open3D CPU Python bindings were not found. Open3D will not work on systems without CUDA devices.
  warnings.warn(
/home/zootos/miniconda3/envs/scanner3d/lib/python3.8/site-packages/open3d/__init__.py:83: ImportWarning: Open3D was built with CUDA support, but an error ocurred while loading the Open3D CUDA Python bindings. This is usually because the CUDA libraries could not be found. Check your CUDA installation. Falling back to the CPU pybind library. Reported error: /usr/local/lib/libOpen3D.so: cannot allocate memory in static TLS block.
  warnings.warn(
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/zootos/miniconda3/envs/scanner3d/lib/python3.8/site-packages/open3d/__init__.py", line 93, in <module>
    from open3d.cpu.pybind import (core, camera, data, geometry, io, pipelines,
ModuleNotFoundError: No module named 'open3d.cpu'
```
For now, the only solution I found is 
`export LD_PRELOAD=/usr/local/lib/libOpen3D.so`

My question is: is there any better way to correct this error?
