### ISSUE TITLE
Intersection between two point cloud

### ISSUE THREAD

**Issue by aditdoshi333** [isl-org/Open3D#3412]
I am using Open3d to process rgbd data from intel realsense L515. So I want to place a bounding volume in a point cloud before that I want to would there be any collision for that particular location. Is there any function that can give an intersection between two point clouds? 

Any help would be appreciated.
Thank you

**Comment by HM102** [comment]
you can try `compute_point_cloud_distance` to find overlapping indices. There is an example  [here](http://www.open3d.org/docs/latest/tutorial/Basic/pointcloud.html)
