### ISSUE TITLE
Misleading warning message?

### ISSUE THREAD

**Issue by xtorker** [isl-org/Open3D#3415]
Hi
I got the following warning message after I read the point cloud using `o3d.io.read_point_cloud()`.

```
RPly: Aborted by user
[Open3D WARNING] Read PLY failed: unable to read file: test.ply
```

This issue only happens on reading color point clouds.

Besides the warning message, I got some artifacts after I write the point cloud to the ply file directly after reading it.

I traced back to the source code and found out that the line below is the most likely place that gives me the warning message.
https://github.com/intel-isl/Open3D/blob/317628457b60f624c8f54e1dbba7b6e20730cd2a/cpp/open3d/io/file_format/FilePLY.cpp#L449-L454

I don't get the meaning of this block, I thought we already read all the data from the ply file to the `p_ply` instance like below.
https://github.com/intel-isl/Open3D/blob/317628457b60f624c8f54e1dbba7b6e20730cd2a/cpp/open3d/io/file_format/FilePLY.cpp#L402-L406

Then, what is the purpose of the validation-like function at line 449?

Below is the minimum code and ply file to reproduce the issue.
```
import open3d as o3d
pc = o3d.io.read_point_cloud('c3f92e6a78ad156863b2acb037dfbcde.ply')
o3d.io.write_point_cloud('test.ply', pc)
```
Ply file: [c3f92e6a78ad156863b2acb037dfbcde.zip](https://github.com/intel-isl/Open3D/files/6453767/c3f92e6a78ad156863b2acb037dfbcde.zip)

Thank you.

**Comment by ssheorey** [comment]
Hi @xtorker Line 401 checks for errors in opening the file (e.g.: incorrect path or permission), while line 449 checks for errors in the data read from the file (e.g.: less data than expected or incorrect / unsupported data type). 

The newer ply reader is more robust.

This worked for me as a work around:
```
import open3d as o3d
pc = o3d.t.io.read_point_cloud('c3f92e6a78ad156863b2acb037dfbcde.ply').to_legacy_pointcloud()
o3d.visualization.draw_geometries([lpc])
```

**Comment by xtorker** [comment]
Hi @ssheorey, thanks for your rapid response.

The workaround works for me too. But the color value of the new/legacy point cloud seems to use a different scale.
legacy: 0-1
new: 0-255

The `to_legacy_pointcloud()` method looks like missing the converting part.

Do you have any idea?

**Comment by reyanshsolis** [comment]
Yes @xtorker you are right. 

The new/tensor-based IO, allows for custom attribute and data-types, therefore the original dtype/scale is used.
Eg. `UInt8` [0-255] attribute in Tensor-IO will be unchanged, but in Eigen/Legacy IO it will be converted to `Double` (0-1). 

The conversion part was also added to the `to_legacy_pointcloud` method. Please try with the latest master/release 0.14.0. 

Thanks!
