### ISSUE TITLE
How to make open3d pcd(point clouds) directly from a live realsense?

### ISSUE THREAD

**Issue by JimXu1989** [isl-org/Open3D#3430]
**Is your feature request related to a problem? Please describe.**
I want to get 3d point cloud directly from a realsense
the example provided by official document is only:
im_rgbd = rs.capture_frame(True, True)  # wait for frames and align them
I want to know how to get 3d points from the im_rgbd variable

**Describe the solution you'd like**
Just use open3d python API 

**Describe alternatives you've considered**
Use librealsense2 instead

**Comment by ssheorey** [comment]
You can use this function: 
http://www.open3d.org/docs/latest/python_api/open3d.t.geometry.PointCloud.html#open3d.t.geometry.PointCloud.create_from_depth_image

There is a related function for getting a colored point cloud as well. Here is an example:

https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/online-processing.py
