### ISSUE TITLE
Metric to understand point cloud

### ISSUE THREAD

**Issue by aditdoshi333** [isl-org/Open3D#3438]
Hello,

The doubt is not directly related to Open3d, it's more for 3d geometry. So in an application, I am using real sense L515 to construct point cloud of the scene. I want to automate the process of data collection. Is there any metric/ way from where I can understand how good/complete is the point for the current scene?

For example, there would a person going around and capture data for the point cloud generation. Is there any way I can programmatically decide that collected data is enough to get the point cloud?

**Comment by ssheorey** [comment]
The next release of Open3D has support for real time scene reconstruction with a GUI for live feedback. Please try it out (C++ master branch or Python devel wheels) and let us know if that helps.

https://github.com/intel-isl/Open3D/pull/3363

Python devel wheels:
http://www.open3d.org/docs/latest/getting_started.html#development-version-pip
