### ISSUE TITLE
How to clear the bulge part in the mesh surface reconstruction?

### ISSUE THREAD

**Issue by rasunag27** [isl-org/Open3D#3450]
1. I am converting a point cloud data points into mesh using Open3D library from python. I have presented the code usage below. 
2. But, the mesh seems fine but there is a little of bulge at the corners of the datapoints. **How to clear that out using the existing code or new code. I am also attaching the 3D mesh datapoints for reference.**

Code snippet :

```
pcd = o3d.io.read_point_cloud('mesh.xyz')
pcd.estimate_normals()

# To obtain consistent normal orientation

pcd.orient_normals_towards_camera_location(pcd.get_center())

# Or to flip normals to make the point cloud outward, not mandatory
pcd.normals = o3d.utility.Vector3dVector(-np.asarray(pcd.normals))

# Surface reconstruction using Poisson reconstruction
mesh, _ = o3d.geometry.TriangleMesh.create_from_point_cloud_poisson(pcd, depth=8)
mesh = o3d.geometry.TriangleMesh.compute_triangle_normals (mesh)

#o3d.visualization.draw_geometries([mesh])

o3d.io.write_triangle_mesh('mesh.stl', mesh)

```
Mesh in xyz format: [Mesh in xyz format](https://drive.google.com/file/d/1ovKGW3wrywWC6rLUahsBn_G8DEacpuln/view?usp=sharing)

Mesh after reconstruction: [Bulge part is shown after reconstruction](https://drive.google.com/file/d/17BcKnYwl0GCbInrngm9DjP2YjBNQgXnJ/view?usp=sharing)

Any leads will be appreciated.

Regards,

Sunag R A.

**Comment by benjaminum** [comment]
@rasunag27 You could check if these parts are disconnected. If yes you could try `cluster_connected_triangles()`. If not it is probably easiest to clean up the mesh manually.
