### ISSUE TITLE
Sampling point clouds from meshes with RGB value

### ISSUE THREAD

**Issue by meidachen** [isl-org/Open3D#3468]
I'm wondering is there a way to sample a point cloud from a mesh with the color for each point? (not getting the vertices from the mesh, but doing the sampling like sample_points_uniformly). Thank you!!

**Comment by sanskar107** [comment]
@meidachen you can refer to this open3d.org/docs/release/tutorial/geometry/mesh.html#Sampling
`sample_points_uniformly` also returns the color value.

**Comment by meidachen** [comment]
Thank you for the reply, I was trying to load an obj file and sample points from it, it seems like the obj is not loaded with color. I have attached the obj here:

https://webdisk.ict.usc.edu/index.php/s/cjWHz1ZAmBJZcmq

my code is simple like this:

mesh = o3d.io.read_triangle_mesh(MeshOBJPath)
print (str(mesh.has_vertex_colors()))
singlePC = mesh.sample_points_uniformly(number_of_points=10000)


I would really appreciate your help!!

**Comment by Bitfultea** [comment]
> 
mesh = o3d.io.read_triangle_mesh('file_name',enable_post_processing=True)
with enable_post_processing being set to true, the textures can be attached and displayed. But I haven't figured out a way to sample the texture of corresponding points

**Comment by benjaminum** [comment]
@Bitfultea  You can try to store the uv coordinates in the vertex colors. This way you can get a point cloud with the interpolated uv coordinates and you can then use these to sample the actual color values.
