### ISSUE TITLE
AttributeError: module 'open3d.open3d.visualization' has no attribute 'pipelines'

### ISSUE THREAD

**Issue by lavaaaw** [isl-org/Open3D#3487]
I am currently using the reconstruction_system code on my Linux system. (Installing open3d with pip command)
When I run this command
`python run_system.py datasets/config.json --make`
it reports that:
`AttributeError: module 'open3d.open3d.visualization' has no attribute 'pipelines'`
Any idea what causes such exception?Is it something about the version?

**Comment by sanskar107** [comment]
@lavaaaw I cannot reproduce this issue. Can you post your installed open3d version?
`python -c "import open3d; print(open3d.__version__)"`
