### ISSUE TITLE
ModuleNotFoundError: No module named 'global_registration'

### ISSUE THREAD

**Issue by donaldlee2008** [isl-org/Open3D#3492]
>>> import open3d as o3d
>>> o3d.__version__
'0.12.0'
>>> from global_registration import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'global_registration'
>>> from fast_global_registration import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'fast_global_registration'
>>>

**Comment by ssheorey** [comment]
Hi @donaldlee2008 are you looking for this function?

http://www.open3d.org/docs/latest/python_api/open3d.pipelines.registration.registration_fast_based_on_feature_matching.html

**Comment by ssheorey** [comment]
Related: https://github.com/intel-isl/Open3D/issues/3494#issuecomment-847200785
