### ISSUE TITLE
Cannot compile the cpp examples, cmake generates "Unknown CMake command "open3d_show_and_abort_on_warning"

### ISSUE THREAD

**Issue by Tetsujinfr** [isl-org/Open3D#3493]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
I cannot compile the cpp examples, cmake generates an error "Unknown CMake command "open3d_show_and_abort_on_warning"

**To Reproduce**

1. cd Open3D/examples/cpp/
2. mkdir build
3. cd build
4. cmake ..

**Expected behavior**
Successful compilation of the examples, at least those which do not rely on third party dependencies like realsense stuff, if any.

**Screenshots**
no need

**Environment (please complete the following information):**

- Operating system: (e.g. Ubuntu 18.04 Linux4Tegra)
- Python version: 3.6
- Open3D version: 0.12
- Is this remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): gcc 7.5, clang 10.0

**Additional context**
The library works successfully otherwise, e.g. I could run the gui and test all the python examples successfully.

thanks for your help.

**Comment by ssheorey** [comment]
> * cd Open3D/examples/cpp/
> * mkdir build
> * cd build
> * cmake ..

Hi @Tetsujinfr you have to configure the entire project at once and then build the specific examples that you want from the top level:

```
cd Open3D
mkdir build
cd build
cmake ..
make <list of examples to build>
```
