### ISSUE TITLE
Global/ICP registration with different coordinate systems

### ISSUE THREAD

**Issue by gabrieleangeletti** [isl-org/Open3D#3496]
I'm trying to align two point clouds in the `WGS 84/Pseudo-Mercator` coordinate system, in which the coordinates have a big magnitude, e.g. `[ 1.60142459e+07, -4.51722285e+06,  4.35892391e+02]`. The initial alignment is pretty good which means that both global registration (RANSAC) and ICP should work well.

The problem is that when I leave the coordinates as is, RANSAC works as expected but ICP doesn't. When I change the space, for example by centering the target cloud at (0, 0, 0) and moving the source cloud accordingly, the opposite happens - ICP works as expected but RANSAC doesn't.

Do you know if this is done to the magnitude of the coordinates or is there something else I should be aware of when choosing the coordinate system?

Thanks.

**Comment by theNded** [comment]
Both RANSAC and ICP uses Euclidean distance metric to setup correspondences, so a different metric space might affect the performance. Might be interesting to customize the distance metric as well, let's see if we have bandwidth in the future.
