### ISSUE TITLE
Unaccesible parameter name `lambda`

### ISSUE THREAD

**Issue by m1kit** [isl-org/Open3D#3531]
**Describe the bug**
Some keyword arguments cannot be used because their name conflict with the reserved word `lambda`.

**To Reproduce**
```python
mesh.filter_smooth_laplacian(lambda=1.0)
```

This results in:
```
  File "./main.py", line 4
    mesh.filter_smooth_laplacian(lambda=1.0)
                                       ^
SyntaxError: invalid syntax
```

**Expected behavior**
We can configure parameters

**Current workarounds**
```pyhton
mesh.filter_smooth_laplacian(**{'lambda': 1.0})
```

**Comment by reyanshsolis** [comment]
Fixed in #4379
