### ISSUE TITLE
no function to convert 3 channel float image back to 3 channel 8-bit image?

### ISSUE THREAD

**Issue by taijihua** [isl-org/Open3D#3539]
I was trying to use CreateImageFromFloatImage() to convert a float image from CaptureScreenFloatBuffer() which is 3 channel float image, but it looks like the CreateImageFromFloatImage() only support single channel? it seems to be an easy expansion to just modify this function to support 3 channel as well if we allow num_of_channels_ to be 3 as well:

if (num_of_channels_ != 1 || bytes_per_channel_ != 4) {        utility::LogError(                "[CreateImageFromFloatImage] Unsupported image format.");    }

am I missing something?

**Comment by ssheorey** [comment]
Please check the new Tensor API. This is supported:

http://www.open3d.org/docs/latest/cpp_api/classopen3d_1_1t_1_1geometry_1_1_image.html#aa864590929ffc3f3f4dcd07521792a3e
