### ISSUE TITLE
Check on coincident objects 

### ISSUE THREAD

**Issue by thomasTUK** [isl-org/Open3D#3544]
Hello,

i want to compare two ifc files. I want to check on coincident objects in those two ifc files. Extract the geometric boundarys if ifc element and check if the space is already occupied by another element. Would that be possible with open3D? 

Regards
Thomas

**Comment by theNded** [comment]
A potential way is to use voxel downsample to obtain voxelized point clouds, and check their intersection using the [hashmap interface](http://www.open3d.org/docs/latest/tutorial/core/hashmap.html).
