### ISSUE TITLE
Compilation failed on Jetson Tx2: An extended __device__ lambda cannot capture variables with array type

### ISSUE THREAD

**Issue by JianxiangFENG** [isl-org/Open3D#3545]
**Describe the bug**
There is an compiling error on NVIDIA Jetson tx2 with Jetpack 4.3 (CUDA10.0, Ubuntu18.04). By following the the [instructions](http://www.open3d.org/docs/release/arm.html) and fixing the bugs of header file according to [this](https://github.com/intel-isl/Open3D/issues/2468#issuecomment-714738851), I came across this error:
```
/home/nvidia/packages/src/Open3D/cpp/open3d/t/geometry/kernel/ImageImpl.h(148): error: An extended __device__ lambda cannot capture variables with array type

1 error detected in the compilation of "/tmp/tmpxft_00005efb_00000000-6_ImageCUDA.cpp1.ii".
cpp/open3d/t/geometry/CMakeFiles/tgeometry.dir/build.make:243: recipe for target 'cpp/open3d/t/geometry/CMakeFiles/tgeometry.dir/kernel/ImageCUDA.cu.o' failed
make[2]: *** [cpp/open3d/t/geometry/CMakeFiles/tgeometry.dir/kernel/ImageCUDA.cu.o] Error 1
CMakeFiles/Makefile2:2040: recipe for target 'cpp/open3d/t/geometry/CMakeFiles/tgeometry.dir/all' failed
make[1]: *** [cpp/open3d/t/geometry/CMakeFiles/tgeometry.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

It does not seem to be the error of CUDA library, because there is a definition about this in E.4.1.5 from [CUDA programing guide](https://www3.nd.edu/~zxu2/acms60212-40212/CUDA_C_Programming_Guide_V7.5.pdf). Does anyone have ideas?
Thank you in advance.

**Expected behavior**
To be compiled and installed without errors.

**Environment:**
- Operating system: Ubuntu 18.04
- Python version: Python 3.6.13
- Open3D version: v0.13.0
- Is this remote workstation?: yes 
- Compiler version (if built from source):  gcc 7.5, clang 7.0

**Additional context**
The commands I used:
- `cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DBUILD_CUDA_MODULE=ON -DBUILD_GUI=ON -DBUILD_TENSORFLOW_OPS=OFF -DBUILD_PYTORCH_OPS=OFF -DBUILD_UNIT_TESTS=ON -DCMAKE_INSTALL_PREFIX=~/packages/install/open3d_install -DPYTHON_EXECUTABLE=$(which python) ..`
- `make -j3`

**Comment by ssheorey** [comment]
@JianxiangFENG this is a limitation of CUDA 10.0. Please upgrade to CUDA 10.1 or later.

**Comment by JianxiangFENG** [comment]
> @JianxiangFENG this is a limitation of CUDA 10.0. Please upgrade to CUDA 10.1 or later.

Thanks for the reply. Because I used a carrier board from another company, therefore the JetPack version is limited to 4.3. Do you know which version of Open3d can sidestep it?

**Comment by ssheorey** [comment]
This was introduced in the current version v0.13. v0.12 should work for you with CUDA 10.0.
If you are familiar with CUDA / need features from v0.13, you are welcome to submit a patch to improve compatibility with CUDA 10.0.

**Comment by reyanshsolis** [comment]
Please upgrade your CUDA to 10.1 or later for using v0.13 or later. You may use v0.12.0 with CUDA 10.0.
It is recommended to use CUDA 11.0 or later for versions above 0.14.0.
 
Thanks.
