### ISSUE TITLE
ICP between reconstructed cloud model and mesh CAD model

### ISSUE THREAD

**Issue by bumbastic** [isl-org/Open3D#3561]
I want to align a mesh CAD model in a reconstructed scene containing the model. 
One problem is that the CAD model is  a mesh containing a lot of internal not visible surfaces.
Another problem is creating a uniform cloud representation of the mesh CAD model.

I was thinking something like a virtual reconstruction of the CAD model. The output should be a uniform cloud representing only the visible surfaces of the CAD model. It is also important to be able the set view points(virtual sensor poses).
It is important that it is relative fast. Something like 1.000.000 points in a second or faster.

Any suggestions or examples on how to best align a mesh CAD model in a live sensor cloud and/or reconstructed scene using Open3D?

**Comment by cemunds** [comment]
I was just about to open a similar issue to ask for this feature. I have a CAD model of an indoor scene and want to sample points from the geometries as if I placed a laser scanner in the middle of the room for example. My purpose is different than the one of aligning a CAD model to a real scan as described above, but the possiblity of performing "virtual scans" that sample only visible points given a sensor position would be great to have.

**Comment by ssheorey** [comment]
Hi @bumbastic @cemunds the new `RayCastingScene` feature in Open3D v0.14.1 should work for your use case:

**Tutorial:** http://www.open3d.org/docs/latest/tutorial/geometry/ray_casting.html
**Docs:** http://www.open3d.org/docs/latest/python_api/open3d.t.geometry.RaycastingScene.html?highlight=raycasting#

Please check it out and let us know.
