### ISSUE TITLE
How can I visualize point cloud data in real time using Azure Kinect DK in Windows?

### ISSUE THREAD

**Issue by gh-BumsooKim** [isl-org/Open3D#3568]
Is it possible to render point cloud data in real time?

I edit files `azure_kinect_viewer.py` in Open3D Python Example folder. like following code : 

```
        while not self.flag_exit:
            rgbd = self.sensor.capture_frame(self.align_depth_to_color)
            if rgbd is None:
                continue

--------rgbd_image = o3d.geometry.RGBDImage.create_from_color_and_depth(
--------    rgbd.color, rgbd.depth, convert_rgb_to_intensity=False)

--------pcd = o3d.geometry.PointCloud.create_from_rgbd_image(rgbd_image,
                                                         intrinsic)
--------print(pcd)
            #o3d.io.write_point_cloud("pcd/pcd_" + str(index) + ".ply", pcd)
            index+=1
            if not vis_geometry_added:
--------    vis.add_geometry(pcd)
                vis_geometry_added = True
             
--------vis.update_geometry(pcd)
            vis.poll_events()
            vis.update_renderer()
```
I marked '---' in the part I edited for point cloud data visualization.

**Problem** :  In the case of existing `rgbd` variable rendering, it works in real time, but for point cloud data 'pcd' it doesn't render in the same window in real time.

**Environment** 
- Windows10
- Open3D : 0.13.0
- Python : 3.8.10
- Azure Kinect SDK 1.2.0

I want to use Azure Kinect to render point cloud data using rgb+depth from real-time raw images.

**Comment by ssheorey** [comment]
Hi @gh-BumsooKim take a look at this GUI example for RealSense:

https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/online-processing.py

You may need to adjust configuration and will likely need CUDA for real time frame rate. (Open3D pre-built Python packages for Windows don't support CUDA yet).

**Comment by gh-BumsooKim** [comment]
Currently PCD frames cannot be measured. This is because the first pcd is still rendered in the window, and later updated pcd are not rendered. And in the window, the first pcd is receiving mouse interaction.

However, when I print the number of points in the point cloud being updated in real time, the new number of points is always printed in console.

**Comment by ssheorey** [comment]
Hi @gh-BumsooKim `update_geometry()` does not work in Windows. Please use `remove_geometry()` and `add_geometry()` instead and let us know what frame rate you get. See the RealSense example as a guide:
https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/online-processing.py

**Comment by TitansWhale** [comment]
hello,I don't know how to get the intrinsic of kinect. What should I do?

**Comment by gh-BumsooKim** [comment]
Hi, you can obtain the `intrinsic.json` to use `azure_kinect_mkv_reader.py` by reading mkv file that is recorded using azure kinect.

**Comment by TitansWhale** [comment]
> 您好，您可以通过阅读使用 azure kinect 录制的 mkv 文件来获得`intrinsic.json`使用。`azure_kinect_mkv_reader.py`

thanks.
