### ISSUE TITLE
how to save ICP debug information

### ISSUE THREAD

**Issue by robertoruizmu** [isl-org/Open3D#3570]
Hi everyone !
I´m using ICP registration, as I want to make a plot with RMSE value in each iteration, I run:
 with o3d.utility.VerbosityContextManager(o3d.utility.VerbosityLevel.Debug) as cm:
     call ICP 
output example : [Open3D DEBUG] ICP Iteration #999: Fitness 0.6484, RMSE 0.5323
Is there any way to save open3d debug in a data frame in order to make a plot with pandas ?
It is a nuisance copy and paste  spyder´s terminal. 

thanks all.

**Comment by reyanshsolis** [comment]
Added option to save loss_log in a TesnsorMap in PR #4271.

Thanks!
