### ISSUE TITLE
How to save ICP debug information

### ISSUE THREAD

**Issue by robertoruizmu** [isl-org/Open3D#3571]
Hi everyone !
I´m using ICP registration, as I want to make a plot with RMSE value in each iteration, I run:
with o3d.utility.VerbosityContextManager(o3d.utility.VerbosityLevel.Debug) as cm:
call ICP
output example : [Open3D DEBUG] ICP Iteration #999: Fitness 0.6484, RMSE 0.5323
Is there any way to save open3d debug in a data frame in order to make a plot with pandas ?
Or, it is possible access data in each iteration to save it ?
It is a nuisance copy and paste spyder´s terminal.

thanks all.

**Comment by ssheorey** [comment]
Would returning the iteration, fitness and error in another variable work?

**Comment by ssheorey** [comment]
Related: #3559

**Comment by robertoruizmu** [comment]
> Would returning the iteration, fitness and error in another variable work?
 I think so, but how can I do that?

**Comment by robertoruizmu** [comment]
> Would returning the iteration, fitness and error in another variable work?

I think so, but how can I do that @ssheorey ?

**Comment by ssheorey** [comment]
It's not supported yet. If you want to work on it, you are welcome to submit a PR. It should be a fairly straightforward update.

**Comment by reyanshsolis** [comment]
You may go to the `pipeline::registration::RegistrationICP` function and write some additional lines there to dump the values.
If you are using the `t::pipeline::registration::RegistrationICP` then, you may keep appending values to a `Tensor` and use `Tensor::Save` to save it as a `.npy` file, which you can `Load` in python as numpy file, and plot the graph. 
Thanks.

**Comment by reyanshsolis** [comment]
I am closing this issue, for now, if you still face issues, feel free to reopen the same.

**Comment by reyanshsolis** [comment]
Added option to save `loss_log` in a `TesnsorMap` in PR #4271.

Thanks!
