### ISSUE TITLE
The issue of projecting point cloud to depth image

### ISSUE THREAD

**Issue by dinghongkai** [isl-org/Open3D#3578]
Hi,

I tried to unproject a depth image to the point cloud, and then projected the point cloud back to a new depth image using the function 'ProjectToDepthImage'. However, the new generated depth image seems missing some data (see the following picture).
I am wondering why it is? 

![Picture1](https://user-images.githubusercontent.com/34554291/121804353-7f5ee780-cc78-11eb-9b2b-0da3372b952e.png)

```	
std::shared_ptr<geometry::Image> depth_input = io::CreateImageFromFile(depth_input_file);
auto pcd_legacy = geometry::PointCloud::CreateFromDepthImage(
	*depth_input, intrinsic, Eigen::Matrix4d::Identity(), depth_scale, depth_trunc);

t::geometry::PointCloud pcd_t = t::geometry::PointCloud::FromLegacyPointCloud(*pcd_legacy);

t::geometry::Image depth_t = pcd_t.ProjectToDepthImage(
	width, height, intrinsic_t, extrinsic_t, (float)depth_scale, (float)depth_trunc);
geometry::Image depth_output = *depth_t.ToLegacyImage().CreateImageFromFloatImage<uint16_t>();
```

**Comment by theNded** [comment]
This could be a rounding issue in numerical computations regarding u, v coordinates. I will look into them later.
