### ISSUE TITLE
Dead kernel in Jupyter/End without any notice in Python. Point cloud outlier removal

### ISSUE THREAD

**Issue by hwy1992129** [isl-org/Open3D#3580]
I want to make outlier removal on multiple point clouds
I import all the point clouds from a directory.
I used a loop to downsample all the point clouds
I used the outlier removal methods on the point clouds.
Outlier removal causes the kernel dead.
I tried the scripts in python. It seems that it ends somewhere caused by errors, but it doesn't show anything in the console...
My OS is **Windows 10**

```
mypath = "pointcloud/directory"
onlyfiles = [join(mypath, f) for f in listdir(mypath) if isfile(join(mypath, f))]

# Read all the point cloud
ply_list = []
for p in onlyfiles:
    ply_list.append(o3d.io.read_point_cloud(p))

for ply in ply_list:
    ply = ply.voxel_down_sample(voxel_size=0.005)

for ply in ply_list:
    cl, ind = ply.remove_radius_outlier(nb_points=30, radius=0.02)
    ply = cl.select_by_index(ind)

```
I want to work with more than 40 point clouds
However, it doesn't work...
I remove the loop and work one by one. It seems that it doesn't allow more than two point clouds.
I also attempt to make it in Python. There are no errors shown up when the program is stopped.....

Moreover, the voxel_size, nb_points, radius may cause the dead kernel, if the values are not good......

I switch to **Linux** system. I run it in python, the terminal shows errors like malloc()? corrupt?

**Comment by sanskar107** [comment]
@hwy1992129 It looks like the kernel is dying due to your memory limitations. The pointcloud is not getting downsampled in your case. Your downsampled pointcloud is saved in `ply` variable which doesn't modify the original list. You can try doing something like this:
```
for i in range(len(ply_list)):
    ply_list[i] = ply_list[i].voxel_down_sample(voxel_size=0.005)
```

**Comment by theNded** [comment]
> @hwy1992129 It looks like the kernel is dying due to your memory limitations. The pointcloud is not getting downsampled in your case. Your downsampled pointcloud is saved in `ply` variable which doesn't modify the original list. You can try doing something like this:
> 
> ```
> for i in range(len(ply_list)):
>     ply_list[i] = ply_list[i].voxel_down_sample(voxel_size=0.005)
> ```

This should be the correct answer. In addition, 5mm is in practice very small for voxel downsampling and may exhaust memory in the following `remove_radius_outlier`. Please use system resource manager to monitor your memory footprint.

**Comment by hwy1992129** [comment]
@theNded I increase the value of voxel_size to 0.02. The outlier removal still has the memory issue in the loop for outlier removal. Such an issue is gone, only if the removal removes all the points.........

**Comment by theNded** [comment]
If your memory budget is low, you can try to read a point cloud, process it, and save it to disk, one by one.

**Comment by hwy1992129** [comment]
@theNded Is there any way to improve the outlier removal. I write the point cloud, read them, and denoise. Denoise is easy to fail, though using the value in the documentation......

**Comment by hwy1992129** [comment]
@theNded I go testing again. I find if I use `remove_statistical_outlier`, `cl.select_by_index(ind)` cause dead kernel. However, `cl` can be visualized and it seems that there is nothing in the visualization window... Does `cl.select_by_index(ind)` cause dead kernel when no points in the point cloud?

**Comment by theNded** [comment]
Please provide example point clouds and let us see why it won't work.

**Comment by hwy1992129** [comment]
> Please provide example point clouds and let us see why it won't work.
Hmmm, it is a few months ago. I don't remember..... It seems that after outlier removal with bad parameters, the points are all removed and the ind is [] or None. Then, select_by_index fails.. I think... I haven't encountered this problem anymore...
