### ISSUE TITLE
How is the size of the bounding box determined in voxel downsampling?

### ISSUE THREAD

**Issue by arkerman** [isl-org/Open3D#3585]
How is the size of the bounding box determined in voxel downsampling?

**Comment by sanskar107** [comment]
What do you mean by bounding box? The parameter `voxel_size` determines the resolution.
http://www.open3d.org/docs/0.6.0/python_api/open3d.geometry.voxel_down_sample.html

**Comment by arkerman** [comment]
I mean how to determine the size of the voxel.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "intel-isl/Open3D"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月17日(星期四) 晚上11:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [intel-isl/Open3D] How is the size of the bounding box determined in voxel downsampling? (#3585)





 
What do you mean by bounding box? The parameter voxel_size determines the resolution.
 http://www.open3d.org/docs/0.6.0/python_api/open3d.geometry.voxel_down_sample.html

**Comment by arkerman** [comment]
I mean how to determine the size of the voxel.

**Comment by sanskar107** [comment]
@arkerman that's per your need. Lower the voxel_size, higher will be the resolution.

**Comment by arkerman** [comment]
@sanskar107 Oh, i got it. And now i have a new question. How the voxel grid size is calculated？Does the larger the voxel grid contain more points?
