### ISSUE TITLE
Questions on View Control for GUI 

### ISSUE THREAD

**Issue by hduonggithub** [isl-org/Open3D#3590]
**Is your feature request related to a problem? Please describe.**
I am modifying the vis_gui.py code so that it can be used as visualizer and further analysis. I do know how to get and use the View Control from the (non-gui) visualizer (view_controls = vis.get_view_controls()) but not from the gui code.

For example, in visualizer, to have a top view (or XY plane), I will do like below:
            view_ctl = vis.get_view_control()
            view_ctl.set_front((0, 0, 1))
            view_ctl.set_up((0, 1, 0))
            view_ctl.set_zoom(0.5)
            view_ctl.change_field_of_view(step = -90)

My question is that is there a way to have those functions as in View Control from GUI visualizer? 
Many thanks !

**Comment by hduonggithub** [comment]
@ssheorey Do you have any hint how to do for this question? Thanks1

**Comment by ssheorey** [comment]
Hi @hduonggithub you can use the [`setup_camera()`](http://www.open3d.org/docs/latest/python_api/open3d.visualization.O3DVisualizer.html#open3d.visualization.O3DVisualizer.setup_camera) function in `O3DVisualizer`.

**Comment by Zhouwudexiazhou** [comment]
> 你好@hduonggithub您可以使用[`setup_camera()`](http://www.open3d.org/docs/latest/python_api/open3d.visualization.O3DVisualizer.html#open3d.visualization.O3DVisualizer.setup_camera)中的函数`O3DVisualizer`。

Hey, I have a question. I change the value of the filed_of_view in O3DVisualizer. Why the photo by render do not change tegother?
