### ISSUE TITLE
Can´t obtain aligment with Fast global registration 

### ISSUE THREAD

**Issue by robertoruizmu** [isl-org/Open3D#3597]
I´m using code example of fast global registration  [http://www.open3d.org/docs/release/tutorial/pipelines/global_registration.html](url)
After try several values for radius_normal, radius_feature and distance_threshold, I can´t achieve good aligment. Matrix transformation doesn´t vary from original position.
Here is a picture of the two downsampled pcd I´m using. If someone could help me I could share with him the data.
@syncle @griegler 
![image](https://user-images.githubusercontent.com/26384726/122257635-7ec08e00-ced0-11eb-926c-9bd9cf99d20d.png)
![image](https://user-images.githubusercontent.com/26384726/122257686-897b2300-ced0-11eb-9b1a-a9c28b339cdd.png)

**Comment by theNded** [comment]
Discussed in #3222 and #3571. Open3D's registration might not work on this data due to the significant differences in shape. Interaction aided software (e.g. CloudCompare) might do the job.
