### ISSUE TITLE
Plot new points inside the point cloud with a different shape and draw a cuboid

### ISSUE THREAD

**Issue by YashRunwal** [isl-org/Open3D#3599]
Hi,

I have plotted a point cloud using the following function:

```
def plot_pointcloud(points):
    xyz = points[:, :3]
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(xyz)
    # pcd.colors = o3d.utility.Vector3dVector(points[:, -1])
    o3d.visualization.draw_geometries([pcd])  # Uncomment this to see the plot
```

However, I have two questions:
1. I have 4 points inside this point cloud which I would like to highlight, i.e. plot those points in a different shape (like a star (*)) as we can do that using matplotlib. Each point has x, y, z coordinates.
2. I would also like to draw a cuboid inside this point cloud. I know the centroid of the cuboid along with length, width, and height of the cuboid. I tried to use the [http://www.open3d.org/docs/latest/tutorial/Basic/visualization.html](url) geometry_primitives but I couldn't get it work. 

Would appreciate your help. 

Thank You.

**Edit 1:** 
After spending some time with the documentation I could come up with the following but it is still not working.

vis = o3d.visualization.Visualizer()

```
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(pcl[:, :3])
pcd.voxel_down_sample(voxel_size=0.02)

npcd = o3d.geometry.PointCloud()
npcd.points = o3d.utility.Vector3dVector(final_vectors)
npcd.voxel_down_sample(voxel_size=100)

vis.create_window()
vis.add_geometry(pcd)
vis.add_geometry(npcd)
vis.run()
```

But I Still cannot see the npcd geometry, i.e points inside the same window, and the final_vectors is:
```
[[91880.89459653832, -2708.737916335661, -1730.0734772576566],
 [90430.34106591332, 1834.8493388687614, -1877.4787076426303],
 [79213.75686745065, -13735.364471289078, -1362.9547396160897],
 [80652.42734587997, -11789.482291008097, -1457.6744061307322]]
```

**Comment by YashRunwal** [comment]
@ssheorey Sorry to tag you here. But I really need some help.

**Comment by hduonggithub** [comment]
@YashRunwal 
To highlight the 4 points, you should use sphere, create_sphere for 4 spheres and translate each sphere to its point (xyz).

    sphere1 = o3d.geometry.TriangleMesh.create_sphere(radius=0.04)
    sphere1.compute_vertex_normals()
    sphere1.paint_uniform_color([1,0,0]) #red
    sphere1.translate([x1,y1,z1], relative=True)

You also can find create box in here, http://www.open3d.org/docs/release/python_api/open3d.geometry.TriangleMesh.html

**Comment by theNded** [comment]
@hduonggithub thanks for the answer. The issue is closed for now, please feel free to reopen.
