### ISSUE TITLE
Jetson  Open3D ML

### ISSUE THREAD

**Issue by feersantana5** [isl-org/Open3D#3614]
I am having plenty issues installing from source Open 3D ML on Jetson nano using Ubuntu 18.04. Python 3.6

1.Install dependencies

2.git clone --recursive https://github.com/intel-isl/open3d

3.cd open3d and mkdir build && cd build

 4. cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CUDA_COMPILER=/usr/local/cuda-10.2/bin/nvcc \
    -DBUILD_SHARED_LIBS=ON \
    -DUSE_BLAS=ON \
    -DBUILD_FILAMENT_FROM_SOURCE=ON \
    -DCMAKE_CXX_FLAGS_RELEASE=ON \
    -DCMAKE_CXX_FLAGS_RELEASE="-O3 -DNDEBUG -faligned-new" \
    -DBUILD_GUI=ON \
    -DGLIBCXX_USE_CXX11_ABI=ON \
    -DBUILD_CUDA_MODULE=ON \
    -DOPEN3D_ML_ROOT=https://github.com/intel-isl/Open3D-ML.git \
    -DBUNDLE_OPEN3D_ML=ON \
    -DBUILD_TENSORFLOW_OPS=ON \
    -DBUILD_PYTORCH_OPS=ON \
    -DBUILD_UNIT_TESTS=ON \
    -DCMAKE_INSTALL_PREFIX=~/open3d_install \
    -DPYTHON_EXECUTABLE=$(which python)

5. make -j3

**In cmake step I´ve the following error:**

**_could not find tensorflow_framework lib_**

**In 5th step the error is:**

_**recipe for target 'all' failed
make: *** [all] Error 2**_

**Comment by MeenatchiKV** [comment]
I dont think Open3d supports Tensorflow and Pytorch yet. Try changing them as follows.
-DBUILD_TENSORFLOW_OPS=OFF
-DBUILD_PYTORCH_OPS=OFF

**Comment by yxlao** [comment]
Yes, TF/PyTorch ops are not supported on Jetson. We may revisit this in the future.
