### ISSUE TITLE
Global registration: Fitness always 1

### ISSUE THREAD

**Issue by aycameric** [isl-org/Open3D#3617]
Hello I am using version 9 of Open3d and Ubuntu 16.4

why is my fitness always 1 but my rmse and correspondence set vary, even if I change voxel size between 0.05 and 0.001?
I need to verify the initial global registration to continue with ICP, however in case of bad matches and good matches I get very similar evaluation parametrics. Even though, my pointclouds don't change (one is a CAD model, one is from a depth camera and the scene is not changing for now)

Thank you in advance.
Best regards,

**Comment by sanskar107** [comment]
@aycameric Can you also verify the same problem with latest version of Open3D(0.13)?

**Comment by aycameric** [comment]
@sanskar107 unfortunately I use Python 2.7 and Ubuntu 16.04, hence as far as I understood I am not able to install the latest version of Open3d, am I?

**Comment by sanskar107** [comment]
Right, we don't support python<3.6. Open3D has evolved a lot in recent versions, we recommend you to update your python and use latest version of Open3D.
