### ISSUE TITLE
How to render without visualization on remote device without visual graphical interface

### ISSUE THREAD

**Issue by AK250** [isl-org/Open3D#3619]
Hi，thanks for your excellent work！I am trying to render the  oriented bounding box on remote device without GUI，I tried o3d.visualization.rendering.OffscreenRenderer but I got :
`LFW Error: X11: The DISPLAY environment variable is missing`
`Failed to initialize GLFW`
Could you please tell me how to handle it

**Comment by errissa** [comment]
If you are on a system without a display you need to add `headless=True` when creating the `OffscreenRenderer`. For example,
`renderer = o3d.visualization.rendering.OffscreenRenderer(640, 480, headless=True)`

If you encounter further issues, please feel free to comment or reopen this issue.
