### ISSUE TITLE
Errors in opening .bag file 

### ISSUE THREAD

**Issue by stefanorobbiani** [isl-org/Open3D#3623]
Good morning!
i m tryng to open a .bag file with the code reported on the website (here reported for clarity)

import open3d as o3d

bag_reader = o3d.t.io.RSBagReader()
bag_reader.open(bag_filename)
im_rgbd = bag_reader.next_frame()
while not bag_reader.is_eof():
# process im_rgbd.depth and im_rgbd.color
im_rgbd = bag_reader.next_frame()

bag_reader.close()

while it works with the example when I change the filename to a bag recorded by d4351i by intel it shows two kinds of error opening different files:

[Open3D Error] (class open3d::t::geometry::RGBDImage __cdecl open3d::t::io::RSBagReader::NextFrame(void)) D:\a\Open3D\Open3D\cpp\open3d\t\io\sensor\realsense\RSBagReader.cpp:187: Null file handler. Please call Open().

[Open3D Error] (class Json::Value __cdecl open3d::t::io::RealSenseSensorConfig::GetMetadataJson(const class rs2::pipeline_profile &)) D:\a\Open3D\Open3D\cpp\open3d\t\io\sensor\realsense\RealSenseSensorConfig.cpp:281: Different frame rates for color ({} fps) and depth (90 fps) streams is not supported.

when i open them on real sense viewer they open correctly

thank you very much in advance for your help

**Comment by sanskar107** [comment]
@stefanorobbiani from the first error it looks like your file isn't opened. Can you check what does `bag_reader.open(bag_filename)` return?
If it returns `True`, feel free to post link of your bagfile.

**Comment by stefanorobbiani** [comment]
hi @sanskar107 ,
Sorry for the late answer. it seems that the function is not executed, so it returns nothing, while with the example it works properly, so I think that there is a problem with the file

![image](https://user-images.githubusercontent.com/48244577/123459347-76f69d00-d5e6-11eb-979d-28e2e97d2f60.png)

and when i press step over from this brake point 
![image](https://user-images.githubusercontent.com/48244577/123459455-98f01f80-d5e6-11eb-9978-0ec735660744.png)
