### ISSUE TITLE
o3d.pipelines.registration.GlobalOptimizationConvergenceCriteria() does not accept max_iteration setting

### ISSUE THREAD

**Issue by HiPupilxD-Hao** [isl-org/Open3D#3625]
**IMPORTANT: Please use the following template to report the bug.**

Before submitting:

1. Search for [similar issues](https://github.com/intel-isl/Open3D/issues).
2. For Python issues, please test with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip). It may be already fixed!
_____

**Describe the bug**
When I tried to follow the tutorial `multiway_registration` http://www.open3d.org/docs/release/tutorial/pipelines/multiway_registration.html
and set max_teration for function `o3d.pipelines.registration.GlobalOptimizationConvergenceCriteria`
but did not work. Actually, the iteration for lm one did not work as well

**To Reproduce**

1. follow the tutorial http://www.open3d.org/docs/release/tutorial/pipelines/multiway_registration.html
2. change the line when do global_optimization as following:
o3d.pipelines.registration.global_optimization(
            pose_graph,
            o3d.pipelines.registration.GlobalOptimizationLevenbergMarquardt(),
            o3d.pipelines.registration.GlobalOptimizationConvergenceCriteria(max_iteration=10),
            option) 
3. error poped up.

**Expected behavior**
Tried to set max_teration but did not work. Actually, the lm one did not work as well

**Screenshots**
![image](https://user-images.githubusercontent.com/57452142/122950066-12340c00-d374-11eb-96b8-e6c13a98b1ed.png)

**Environment (please complete the following information):**

- Operating system: Ubuntu 18.04
- Python version: Python 3.6
- Open3D version: 0.13.0
- Is this remote workstation?: no
- How did you install Open3D?: pip install open3d

**Additional context**

**Comment by theNded** [comment]
Thanks for the catch. The constructor seems missing. At current you may use
```
criteria = o3d.pipelines.registration.GlobalOptimizationConvergenceCriteria()
criteria.max_iteration = 10
```
then pass it to the optimizer.
