### ISSUE TITLE
EGL (1.4) Failed to find any suitable EGL configs

### ISSUE THREAD

**Issue by goncalo120** [isl-org/Open3D#3632]
**Describe the bug**
I installed 0.13.0 for the new remote visualization. I manage to install it pip and by source and I'm getting the same error everytime I try to run draw using the webrtc:

![EGL Config Missing](https://user-images.githubusercontent.com/9056959/123139589-4aa81880-d44e-11eb-88a9-e75299ae895f.png)

I also tried doing the visualization through jupyter but it gives the same error and crashes the notebook.
Any idea what the problem can be?

**Environment:**

- Operating system: Ubuntu 20.04
- Python version: Python 3.8.8
- Open3D version: 0.13.0
- Is this remote workstation?: yes 
- How did you install Open3D?: pip, conda and build from source
- Compiler version (if built from source): gcc 8.4

Thanks

**Comment by ssheorey** [comment]
This looks the same as #3596 

Do you have a GPU (integrated is OK) on your remote server? Many Xeons don't have GPUs. See the linked issue for how to check.

**Comment by goncalo120** [comment]
Yes! I have a RTX 2070.
I went to my remote machine and tried locally and it works well. But through ssh with -X/Y from my mac it does not work.

**Comment by ssheorey** [comment]
Please paste the output of running `eglinfo` on your remote server. We are trying to pin down problematic configurations.

**Comment by goncalo120** [comment]
Here it is:
![eglinfo](https://user-images.githubusercontent.com/9056959/123849919-49c12c00-d911-11eb-8f60-2dd0abaf8724.png)

**Comment by ssheorey** [comment]
> Yes! I have a RTX 2070. I went to my remote machine and tried locally and it works well. But through ssh with -X/Y from my mac it does not work.

ssh -X does not support OpenGL. In this case you can use CPU rendering with the env var `OPEN3D_CPU_RENDERING=True`

Another option is to use `x11vnc` to connect to an already running X11 session.
