### ISSUE TITLE
cluster_dbscan  "interrupted by signal 9: SIGKILL" issue

### ISSUE THREAD

**Issue by javi-99** [isl-org/Open3D#3645]
Hi, 
I applied dbscan on pointcloud having 5392930 number of 3d points, I am facing an issue I guess because of excessive memory usage. I am using pycharm , python 3.8 , ram 16 GB. Can you guide me on what should I do ? in order to solve this issue 
![image](https://user-images.githubusercontent.com/47158235/123425860-eeb2d080-d5c2-11eb-9750-5ef36617e4ae.png)

**Comment by ssheorey** [comment]
Can you try subsampling your point cloud, running dbscan on it, and then assigning clusters to the unused points based on nearest neighbors?

Can you tell us more about your use case? We are looking into improving support for very large data sets. Yours seems to have around 5M points.

**Comment by theNded** [comment]
Closed due to the dormant state. Please feel free to reopen.
