### ISSUE TITLE
How to fit a straight line with points?

### ISSUE THREAD

**Issue by arkerman** [isl-org/Open3D#3653]
How can I fit a straight line with a few points? 
Are there any related functions in open3d?

**Comment by hduonggithub** [comment]
@arkerman 
Open3D does not have such function. But you can take xyz points as xyz = pcd.points, and google any code to fit a line. Then if you want to draw the fitted line, make a lineset from 2 end points

**Comment by arkerman** [comment]
@hduonggithub ok,Thank you for your answer

**Comment by hduonggithub** [comment]
@arkerman please close the ticket if you found it useful! ;)

**Comment by leomariga** [comment]
@arkerman you can use [pyRANSAC3D library](https://github.com/leomariga/pyRANSAC-3D), it has the 3d line feature that you can fit with your points.

**Comment by arkerman** [comment]
@leomariga oh ,thanks for your information！
How to detect the points on the edge of the point cloud image?by open3d or pyransac3d?

**Comment by arkerman** [comment]
@hduonggithub ok ,but i got some new questions.I will close this issue after I resolve it。

**Comment by hduonggithub** [comment]
@arkerman 
open3d has only plane_segment. No line detection.
pyransac3d should be your choice

**Comment by arkerman** [comment]
@hduonggithub Thank you for your information！Are there other libraries besides pyransac3d?

**Comment by ssheorey** [comment]
> @leomariga oh ,thanks for your information！
> How to detect the points on the edge of the point cloud image?by open3d or pyransac3d?

You can use convex hull for this:
http://www.open3d.org/docs/release/tutorial/geometry/pointcloud.html#Convex-hull
http://www.open3d.org/docs/release/python_api/open3d.geometry.PointCloud.html#open3d.geometry.PointCloud.compute_convex_hull

The second return value is the list of indices of points on the convex hull.

**Comment by arkerman** [comment]
@ssheorey Thank you for the information, it is very helpful to me!
