### ISSUE TITLE
Sample: icp_registration.ipynb not working with my PCD's 

### ISSUE THREAD

**Issue by masterchop** [isl-org/Open3D#3669]
**IMPORTANT: Please use the following template to report the bug.**

Before submitting:

1. Search for [similar issues](https://github.com/intel-isl/Open3D/issues).
2. For Python issues, please test with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip). It may be already fixed!
_____

**Describe the bug**

**To Reproduce**

1. cd '...'
2. python '....'
3. See error

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

- Operating system: (, Ubuntu 18.04)
- Python version: (e.g. Python 3.6)
- Open3D version: 0.13
- Is this remote workstation?: no
- How did you install Open3D?: pip

**Additional context**
I am using that example but i am not able to correlate the pcds i creataed with Open3d itself.

you can get the PCD's from here: https://drive.google.com/drive/folders/1li9xtChuPTcZEIPXolPzbaLo2fHwuLO0?usp=sharing

I only changed the following lines from the code;

```
    o3d.visualization.draw_geometries([source_temp, target_temp],
                                      zoom=0.69999999999999996,
                                      front=[0.7595975145695093, 0.084188447065477262, 0.64492163961254045],
                                      lookat=[-0.0003042184839312522,-6.39557458571973e-05,-0.00024301114184330545],
                                      up=[-0.033853203532186113, 0.9953606193024187, -0.090062190471440068])
```
    
and

```
trans_init = np.asarray([[0.0, 0.0, 1.0, 0.000100], [1.0, 0.0, 0.0, -0.00005],
                         [0.0, 1.0, 0.0, -0.00055], [1.0, 0.0, 0.0, 1.0]])
```

I would appreciate any help, thanks

**Comment by reyanshsolis** [comment]
Hi @masterchop, 
I am unable to open the pcd files you shared. Are these the same files found inside Open3D `examples/test_data/ICP` ?
If not, may you please share how you generated these files ?

Also, it would be helpful, if you may share more information regarding your issue.

Thanks.

**Comment by masterchop** [comment]
I am using open3d to generate the PCD's, i might be missing something. 

```
            img_depth = o3d.geometry.Image(depth_img)
            img_color = o3d.geometry.Image(color_img)
            rgbd = o3d.geometry.RGBDImage.create_from_color_and_depth(img_color, img_depth)
            pinhole_camera_intrinsic = o3d.camera.PinholeCameraIntrinsic(800,800,286.203,286.185,stereo_cx,stereo_cy)
            pcd = o3d.geometry.PointCloud.create_from_rgbd_image(rgbd, pinhole_camera_intrinsic)
            # i can display this PCD no problem using open3d visualization
            # i save it like this:
            o3d.io.write_point_cloud(f"cloud_bin_{counter}.pcd",pcd)

```

Any help is welcome.

**Comment by reyanshsolis** [comment]
So are you trying to correlate two consecutive point cloud frames?

If that is the case, you might want to downsample your point cloud using `VoxelDownSample` (you may take 0.05 to start with), and `initializing the trans_init as 4x4 identity`, and use large search_radius or max_correspondence_distance (let's try 0.2), and check `registration_result` to see fitness / inilier_rmse / number of correspondences.

**Comment by theNded** [comment]
> You can see the life pointcloud working on this video: [link](https://www.youtube.com/watch?v=TKD5oPNxiGQ)

ICP is in general designed for static objects observed at different viewpoints. Your video has a dynamic human in the front, so it could be challenging.  Potentially you will need to segment out the moving objects and perform ICP for the static background, like [StaticFusion](https://github.com/raluca-scona/staticfusion)

**Comment by masterchop** [comment]
I am quite new to this topic, so ill go slow with your recommendations, i can try the VoxelDownSample, in a few minutes but i would assume that more points would be better quality and easier to match? isnt it in this case?

i just want to show you that i can load the PCD's and display them: [vid](https://youtu.be/H51bdBU607g) and when i run this code:

`reg_p2p = o3d.pipelines.registration.registration_icp(
    source, target, threshold, trans_init,
    o3d.pipelines.registration.TransformationEstimationPointToPoint(),
    o3d.pipelines.registration.ICPConvergenceCriteria(max_iteration=6000))
print(reg_p2p)
print("Transformation is:")
print(reg_p2p.transformation)
draw_registration_result(source, target, reg_p2p.transformation)`

I get the following:  [after icp resgistration](https://youtu.be/hMgcjgZxFGM)

**Comment by masterchop** [comment]
> > You can see the life pointcloud working on this video: [link](https://www.youtube.com/watch?v=TKD5oPNxiGQ)
> 
> ICP is in general designed for static objects observed at different viewpoints. Your video has a dynamic human in the front, so it could be challenging. Potentially you will need to segment out the moving objects and perform ICP for the static background, like [StaticFusion](https://github.com/raluca-scona/staticfusion).
> 
> Edit: I realized that you are scanning the room after a while -- ICP should work in that scenario, but since ICP requires a good initialization you may have to move the camera slower.

what i did was to rotated the camera a few degress, i am not even collecting the entire room, i am testing the most basic thing i could imagine the PCD's are almost the same.

Please look at this video using cloud compare to compare both PCD's  [LINK](https://youtu.be/zH2Z9pyhPEk)

**Comment by reyanshsolis** [comment]
The PointToPlane ICP method requires the target pointcloud to have normals. 
So, if you want to use the `PointToPlane` ICP method, you must use the function `EstimateNormals` to first add normals to the target point cloud, or use the `PointToPoint` method. 

`TransformationEstimationPointToPlane and TransformationEstimationColoredICP require pre-computed normal vectors for target PointCloud.`

**Comment by GabbySuwichaya** [comment]
Thanks ! @reyanshsolis... 

Yes, it does need the normal vectors for the target ....   

```
target.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30)) ## << Add this line

print(":: Point-to-plane ICP registration is applied on original point")
print("   clouds to refine the alignment. This time we use a strict")
print("   distance threshold %.3f." % distance_threshold)

result = o3d.pipelines.registration.registration_icp( source, target, distance_threshold, result_ransac.transformation, o3d.pipelines.registration.TransformationEstimationPointToPlane())
```
