### ISSUE TITLE
Can open3d achieve fast bilateral filtering?

### ISSUE THREAD

**Issue by arkerman** [isl-org/Open3D#3685]
Are there any related functions in open3d?

**Comment by ssheorey** [comment]
@arkerman do you mean for images? HW accelerated bilateral filtering is present for both CPU and CUDA.

http://www.open3d.org/docs/latest/python_api/open3d.t.geometry.Image.html#open3d.t.geometry.Image.filter_bilateral

Bilateral filtering for point clouds is not supported yet. Please tell us more about your use case if you need this.

**Comment by arkerman** [comment]
@ssheorey I mean the bilateral filtering used in the point cloud, just like the bilateral filtering and fast bilateral filtering in PCL.

**Comment by theNded** [comment]
Unfortunately, it is not implemented and is not in our plan.
