### ISSUE TITLE
Import and export in 3MF format

### ISSUE THREAD

**Issue by caniko** [isl-org/Open3D#3720]
[3MF](https://3mf.io/specification/) is a very promising data structure for storing meshes, should be supported by open3d.

**Comment by ssheorey** [comment]
@caniko can you talk more about your use case? Are any current datasets available in this format?

From what I can tell, this is a Linux foundation project for 3D printing applications.
Underlying library: https://github.com/3MFConsortium/lib3mf/blob/master/README.md (BSD license, binaries available)

**Comment by caniko** [comment]
I was really intrigued by this [video](https://www.youtube.com/watch?v=BABdR9d8Cp4). I'd like to store my meshes in this format. It also seems like the perfect for meshes for NFTs.

**Comment by theNded** [comment]
Please feel free to contribute to the project. Unfortunately we currently don't have the bandwidth for this format.
