### ISSUE TITLE
Open3D build ERROR f given arguments:      "NOT" "DATASET_FULL_PATH" "MATCHES" "^.../Open3D/examples/test_data/open3d_downloads"    Regular expression cannot compile

### ISSUE THREAD

**Issue by Likhith-Sugganahalli** [isl-org/Open3D#3744]
**Describe the bug**
while building, with cmake command:
cmake ..
then, 
make install

the follow error appears:

RegularExpression::compile(): Nested *?+.
RegularExpression::compile(): Error in compile.
CMake Error at /...../Open3D/examples/test_data/download_test_data.cmake:17 (if):
  if given arguments:

    "NOT" "DATASET_FULL_PATH" "MATCHES" "^/...../Open3D/examples/test_data/open3d_downloads"

  Regular expression
  "^/home/whoknows/Documents/c++/PointCloudVisualization/Open3D/examples/test_data/open3d_downloads"
  cannot compile
Call Stack (most recent call first):
  /...../Open3D/examples/test_data/download_test_data.cmake:48 (download_dataset_file)

make[2]: *** [CMakeFiles/open3d_downloads.dir/build.make:70: CMakeFiles/open3d_downloads] Error 1
make[1]: *** [CMakeFiles/Makefile2:1159: CMakeFiles/open3d_downloads.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**To Reproduce**

git clone --recursive https://github.com/intel-isl/Open3D
cd Open3D
sudo util/install_deps_ubuntu.sh
mkdir build
cd build
cmake ..
make -j8
make install

**Environment (please complete the following information):**

- Operating system: Ubuntu 20
- Python version: (e.g. Python 3.8)
- Open3D version: 13
- Is this remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): (e.g. gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, clang 10.0.0-4ubuntu1)

EDIT:formatting

**Comment by wangdongw** [comment]
I meet the same issues. How can I solve it? Thank you.

**Comment by wangdongw** [comment]
> **Describe the bug**
> while building, with cmake command:
> cmake ..
> then,
> make install
> 
> the follow error appears:
> 
> RegularExpression::compile(): Nested *?+.
> RegularExpression::compile(): Error in compile.
> CMake Error at /...../Open3D/examples/test_data/download_test_data.cmake:17 (if):
> if given arguments:
> 
> ```
> "NOT" "DATASET_FULL_PATH" "MATCHES" "^/...../Open3D/examples/test_data/open3d_downloads"
> ```
> 
> Regular expression
> "^/home/whoknows/Documents/c++/PointCloudVisualization/Open3D/examples/test_data/open3d_downloads"
> cannot compile
> Call Stack (most recent call first):
> /...../Open3D/examples/test_data/download_test_data.cmake:48 (download_dataset_file)
> 
> make[2]: *** [CMakeFiles/open3d_downloads.dir/build.make:70: CMakeFiles/open3d_downloads] Error 1
> make[1]: *** [CMakeFiles/Makefile2:1159: CMakeFiles/open3d_downloads.dir/all] Error 2
> make: *** [Makefile:136: all] Error 2
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> git clone --recursive https://github.com/intel-isl/Open3D
> cd Open3D
> sudo util/install_deps_ubuntu.sh
> mkdir build
> cd build
> cmake ..
> make -j8
> make install
> 
> **Environment (please complete the following information):**
> 
> * Operating system: Ubuntu 20
> * Python version: (e.g. Python 3.8)
> * Open3D version: 13
> * Is this remote workstation?: no
> * How did you install Open3D?: build from source
> * Compiler version (if built from source): (e.g. gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, clang 10.0.0-4ubuntu1)
> 
> EDIT:formatting

I meet the same issues . How can I solve it?
