### ISSUE TITLE
realsense_recorder.py and L515 causes config error

### ISSUE THREAD

**Issue by ekolve** [isl-org/Open3D#3753]
The depth configuration defined on this line:

https://github.com/intel-isl/Open3D/blob/master/examples/python/reconstruction_system/sensors/realsense_recorder.py#L114

is not compatible with the RealSense L515 camera.  The following exception is raised:
```bash
Traceback (most recent call last):
  File "./examples/python/reconstruction_system/sensors/realsense_recorder.py", line 126, in <module>
    profile = pipeline.start(config)
RuntimeError: Couldn't resolve requests
```

The valid options are:

320x240 @30fps z16
640x480 @30fps z16
1024x768 @30fps z16

I was able to workaround the issue by switching the resolution to 640x480 and everything worked.

**Comment by ssheorey** [comment]
Hi @ekolve thanks for catching this. Would you be able to submit a PR to update the code?
