### ISSUE TITLE
If the operation order of add_geometry and convert_from_pinhole_camera_parameters is different, the result of visualizer will be different. 

### ISSUE THREAD

**Issue by nenoNaninu** [isl-org/Open3D#3769]
[In the load_view_point function of "examples/python/visualization/load_save_viewpoint.py"](https://github.com/intel-isl/Open3D/blob/master/examples/python/visualization/load_save_viewpoint.py#L21-L29), it is called in the order of `add_geometry-> convert_from_pinhole_camera_parameters` and it is functioning correctly. 

However, calling `convert_from_pinhole_camera_parameters -> add_geometry` does not work properly and gives the same visualization results as not calling `convert_from_pinhole_camera_parameters`. 

**To Reproduce**

Rewrite  [examples/python/visualization/load_save_viewpoint.py#L26-L27](https://github.com/intel-isl/Open3D/blob/master/examples/python/visualization/load_save_viewpoint.py#L26-L27)

```py

# OK
def load_view_point(pcd, filename):
    # ...
    vis.add_geometry(pcd)
    ctr.convert_from_pinhole_camera_parameters(param)
    # ...
    

# The result is different from calling load_view_point.
# The visualization result is the same as when camera_parameter is not set. 
def load_view_point(pcd, filename):
    # ...
    ctr.convert_from_pinhole_camera_parameters(param)
    vis.add_geometry(pcd)
    # ...

```

**Expected behavior**
The same visualization results are expected. 

It seems strange that the visualization results are different, because `add_geometry` adds geometry to the world coordinate system and it is independent of camera_parameter. 

Is this behavior expected? If it is the expected behavior, I would appreciate it if you could tell me why it is behaving like this. 

**Environment**

- Operating system: Windows 10 64-bit
- Python version: Python 3.8.10
- Open3D version: 0.13.0
- Is this remote workstation?: no
- How did you install Open3D?: pip

**Comment by theNded** [comment]
This is expected behavior: when adding a new geometry, the viewpoint will be recomputed based on the new object's bounding box, resulting in a reconfiguration of the viewpoint.
