### ISSUE TITLE
Is it possible to embed the web visualizer into a web page?

### ISSUE THREAD

**Issue by nicholas-p1** [isl-org/Open3D#3770]
I'd like to display Open3D visualisations as part of an already existing web page. I have looked at HTML options such as `iframe`, `object`, and `embed` but had no success with these.

**Comment by reyanshsolis** [comment]
Yes, it is possible to do that after v0.13.0 release, using our WebVisualizer http://www.open3d.org/docs/release/tutorial/visualization/web_visualizer.html. 
Video Reference: https://youtu.be/pLCVCH7ypI4?t=137

Thanks!
