### ISSUE TITLE
How to set renderer near and far planes?

### ISSUE THREAD

**Issue by dd-ff** [isl-org/Open3D#3774]
Can anyone tell me how we can set near and far planes for the renderer's camera in Python?
As far as I can see you can only get those values  via the camera object of current scene but you cannot set it individually?
It would be great if you could only set those values while the rest of the camera properties could remain the same.

**Comment by dd-ff** [comment]
Did someone figure out how to set renderer near and far planes in Python?
I found that the default setting for near plane is really restrictive when visualizing large scanned scenes (and other rendered objects) in 1:1 meter scale. I know I can scale up everything in order to mitigate the relatively large near plane value but that is not really the answer since dynamically scaling very large point clouds uses CPU time.

**Comment by errissa** [comment]
@dd-ff The near/far planes can be set using the `open3d.visualization.rendering.Camera.set_projection` functions which all take `near` and `far` parameters. If you use the `setup_camera` functions of the `SceneWidget` then you don't have direct control of the near and far planes. Instead, they will be set automatically based on the scene bounds.
