### ISSUE TITLE
get_volume() for triangle mesh is not invariant of location

### ISSUE THREAD

**Issue by jinseok-karl** [isl-org/Open3D#3776]
Hi, I'd like to use open3d for estimate point cloud volume.
So, I created for simple tetrahedron,

`import numpy as np`
`import open3d`
`points = np.array([[1,0,0],[0,1,0],[0,0,1],[0,0,0]])`
`point_cloud = open3d.geometry.PointCloud()`
`point_cloud.points = open3d.utility.Vector3dVector(points)`
`hull, _ = point_cloud.compute_convex_hull()` 

The result of the hull.get_volume() is 0.1666666, which is correct.
But if I translate this tetrahedron, the get_volume() return is changed,( translation e.g points += [100,100,0])

I read the code of get_volume.
It may depend on triangle mesh and its tetrahedron volume with sign.
But this is not invariant of location(by translation), even if the volume is a value doesn't affected by translation.

Is it intended? 

Thanks
Karl

**Comment by jinseok-karl** [comment]
It seems come from the order of triangle vertices.
So the signed volumes were not appropriate.
Because there is normal vector not direct outward.

Is there better way to give the order of triangle vertices.

**Comment by ssheorey** [comment]
What volume do you get after translation?

**Comment by benjaminum** [comment]
@jinseok-karl #4508 fixes the triangle orientation of the convex hull. `get_volume()` returns now the same volume for the translated tetrahedron.
