### ISSUE TITLE
open3d.crop_point_cloud(pcd_file, [-30, -10, -2], [30, 10, 100]) does not work in latest version of open3d

### ISSUE THREAD

**Issue by saina110** [isl-org/Open3D#3779]
Dear everyone,

Recently, I tried to use Open3d to crop my point cloud into a cube area. I use the code `open3d.crop_point_cloud(pcd_file, [-30, -10, -2], [30, 10, 100])`, but it doesn't work.. As far as I know in Pcl, I just need to set the pair of x,y,z with max and min value, then I could get the region of interest. 

But in open3d, it seems little bit difficult to define such easy things...I notice that I need to use some Json file to define the poly area, which is not the interest of my concern...

I wish someone could give me some tips and suggestions regarding about this issue, i am a freshman in open3d area. Thank you all for your kind and patience

Best Regards,

**Comment by saina110** [comment]
I found this function only exists in open3d-python version, but it is not maintained anymore. when I install open3d-python and uninstall open3d version, this function works. but other functions are not working because of low version I used...

**Comment by saina110** [comment]
I try to change some settings in the json file (region of interest, cuboid): 

`{
	"axis_max" : 400.022921085357666,  
	"axis_min" : -100.76341366767883301, 
	"bounding_polygon" :   
	[
		[100, 50, 0], 
                [-100, 50, 0],
                [100, -50, 0],
                [-100, -50, 0] 
	],
	"class_name" : "SelectionPolygonVolume", 
	"orthogonal_axis" : "Z",  
	"version_major" : 1,   
	"version_minor" : 0
}`

but the result is not square:

![image](https://user-images.githubusercontent.com/11236663/126612441-af7ff22a-3dc7-4f20-99dc-9b884ba5e2d4.png)

you can see there is some blank at the left and right side

**Comment by saina110** [comment]
Hello everyone, now I figure out the problem. If you want to crop a square area, you need to set the coordinate in the json file with clockwise or counter-clockwise. then you can get a square area.

The configured json file demo is:

`{
	"axis_max" : 400.022921085357666,  
	"axis_min" : -100.76341366767883301, 
	"bounding_polygon" :   
	[
		[50, -50, 0],
		[50, 50, 0], 
		
                [-50, 50, 0],
                
                [-50, -50, 0] 
	],
	"class_name" : "SelectionPolygonVolume", 
	"orthogonal_axis" : "Z",  
	"version_major" : 1,   
	"version_minor" : 0
}`

**Comment by sanskar107** [comment]
@saina110 `open3d-python` is renamed to `open3d` a long time ago and there have been many API changes since then. We recommend using latest version of open3d.
Refer to the following documentation for cropping the pointcloud.
http://www.open3d.org/docs/release/python_api/open3d.geometry.PointCloud.html#open3d.geometry.PointCloud.crop

**Comment by theNded** [comment]
Closed due to the dormant state. Please feel free to reopen.
