### ISSUE TITLE
How to get the real time 3D reconstruction demo like the youtube video?

### ISSUE THREAD

**Issue by zhanghua7099** [isl-org/Open3D#3780]
I found that the youtube video providing a real time 3D reconstruction demo:

https://www.youtube.com/watch?v=pLCVCH7ypI4&list=PLLMgZwl-AQOm9wDOWzup2KTl9Ak0CnpjI

It has GUI to visualize the 3D reconstruction with about 30 FPS. But I can't find this demo's code. Can you provide a link?

**Comment by zhanghua7099** [comment]
This issue has been mentioned in [https://github.com/intel-isl/Open3D/issues/3556](url).

**Comment by zhanghua7099** [comment]
I have another question about this amazing app.

I try to export the `VoxelHashingGUI.cpp` into a new project using the method:
https://github.com/intel-isl/open3d-cmake-find-package

But it will have errors when compiling it like this:
```
/usr/local/lib/libOpen3D.a(RGBDOdometryCUDA.cu.o)：‘open3d::t::pipelines::kernel::odometry::ComputeOdometryResultIntensityCUDA(open3d::core::Tensor const&, open3d::core::Tensor const&, open3d::core::Tensor const&, open3d::core::Tensor const&, open3d::core::Tensor const&, open3d::core::Tensor const&, open3d::core::Tensor const&, open3d::core::Tensor const&, open3d::core::Tensor const&, open3d::core::Tensor&, float&, int&, float, float)’：
/home/zhy/Tools/Open3D/cpp/open3d/core/CUDAUtils.h:77：‘cudaGetErrorString’ Undefined reference
```

It may be some errors when the pre-installed Open3D finding CUDA. `Undefined reference` will be inevitably occurred.

How to fix this problem?

**Comment by xiaopeige** [comment]
我使用cpu的没有报错

**Comment by theNded** [comment]
Please use the latest distribution and refer to [this tutorial](http://www.open3d.org/docs/latest/tutorial/t_reconstruction_system/index.html).
