### ISSUE TITLE
RGBD odometry is always success even when images are not overlapping

### ISSUE THREAD

**Issue by rjtshrm** [isl-org/Open3D#3781]
I am trying to find the odometry between two rgbd frames. It works for the frames which are closer. But when try to compare two rgbd fames at very large distance it returns success, pose, information matrix. However these two images does not share any area. Below are the two images for which I am computing the rgbd odometry. 
![image00001](https://user-images.githubusercontent.com/6351392/126623024-d5714a29-1429-47aa-817e-3940be05cab7.png) 
![image01364](https://user-images.githubusercontent.com/6351392/126623064-417e53a3-b142-4cda-88be-ece0a1682201.png)

**Comment by ssheorey** [comment]
@rjtshrm RGBD odometry is designed for frames with a small pose change. It will not work for large pose changes in general. Do you need the function to specifically fail in this case?

**Comment by theNded** [comment]
Could you please share your returned results? Unlike humans, RGBD odometry does not know there are no overlaps. It only decides success by local geometry (and optionally appearance), so a false positive is possible.
