### ISSUE TITLE
Is there a way to draw a camera in a visualizer?

### ISSUE THREAD

**Issue by bhkim94** [isl-org/Open3D#3782]
Hi,

Is there a way to draw a camera in a visualizer?
Like in the picture below, I want to put a camera icon in a visualizer with my extrinsic camera matrix.
I'm working on 0.13.0 in Python.

Thanks in advance.
![image](https://user-images.githubusercontent.com/25083932/126652124-1de089fb-d98f-48f9-82c6-4ff0569e8d7d.png)

**Comment by ssheorey** [comment]
http://www.open3d.org/docs/latest/python_api/open3d.geometry.LineSet.html#open3d.geometry.LineSet.create_camera_visualization
