### ISSUE TITLE
Building tests fails with linker error when using -DUSE_SYSTEM_GOOGLETEST=ON

### ISSUE THREAD

**Issue by WysokiStudent** [isl-org/Open3D#3785]
**Describe the bug**
The building tests fails when using system googletest. 

**To Reproduce**
```
 cmake .. \                    
        -DBUILD_SHARED_LIBS=ON \
        -DCMAKE_BUILD_TYPE=Release \
        -DUSE_SYSTEM_FMT=ON \
        -DUSE_SYSTEM_GLEW=ON \
        -DUSE_SYSTEM_GLFW=ON \
        -DUSE_SYSTEM_GOOGLETEST=ON \
        -DUSE_SYSTEM_JPEG=ON \
        -DUSE_SYSTEM_PNG=ON \
        -DUSE_SYSTEM_PYBIND11=ON \
        -DBUILD_UNIT_TESTS=ON
make
```

**Expected behavior**
The build should succeed.

**Environment (please complete the following information):**

- Operating system:  Archlinux
- Python version: Python 3.9.6
- Open3D version: 6c4080d2aec2c0df95e2e37ed75fc0911f14dbe9
- Is this remote workstation?: no
- How did you install Open3D?: from source
- Compiler version (if built from source): gcc (GCC) 11.1.0

**Additional context**
My installed googletest version is: `gtest 1.11.0-1`
Here are the logs when building without system googletest
[project_googletest_cmake.txt](https://github.com/intel-isl/Open3D/files/6866675/cmake.txt)
[project_googletest_make.txt](https://github.com/intel-isl/Open3D/files/6866676/make.txt)

Here are the logs when buidling with system googletest
[system_googletest_cmake.txt](https://github.com/intel-isl/Open3D/files/6866677/cmake.txt)
[system_googletest_make.txt](https://github.com/intel-isl/Open3D/files/6866678/make.txt)

**Comment by stotko** [comment]
Thanks for bringing this up again. I "fixed" this issue in #3808 where the `USE_SYSTEM_GOOGLETEST` option is removed. Unfortunately, using the system `googletest` package will not work with `GLIBCXX_USE_CXX11_ABI=OFF`, so building from source (as also recommended by Google developers) should always be preferred.
