### ISSUE TITLE
Running VoxelHashingGUI crashes

### ISSUE THREAD

**Issue by HelloCentaurus** [isl-org/Open3D#3797]
**Describe the bug**

**To Reproduce**
Running VoxelHashingGUI(debug version), hit "resume/pause" button in GUI,then throw a error as picture shows in below.

**Expected behavior**

![image](https://user-images.githubusercontent.com/15262893/126948714-d93ba41b-c3c9-4c94-b247-78df8ce677cd.png)

**Environment (please complete the following information):**

- Operating system: (Windows 10 64-bit)
- Python version: (Python 3.6)
- Open3D version: 0.13.0
- Is this remote workstation?: no
- How did you install Open3D?: (build from source)
- Compiler version (visual studio 2019)

**Additional context**

**Comment by HelloCentaurus** [comment]
RelwithDebInfo version can run normally!

**Comment by theNded** [comment]
Should have been fixed in #4217
