### ISSUE TITLE
read_triangle_mesh function is returning a wrong number of vertices 

### ISSUE THREAD

**Issue by dhorka** [isl-org/Open3D#3799]
**Describe the bug**
 o3d.io.read_triangle_mesh returns a wrong number of vertices. I have double-check it with meshlab, and I observed that the read_triangle_mesh function of the current version of open3d is returning a different number of vertices than meshlab. In version 0.11.2 that was working fine. 

**To Reproduce**

mesh = o3d.io.read_triangle_mesh(filename)
print(mesh)

**Expected behavior**
Obtain the same number of vertices obtained in version 0.11.2 and in meshlab.

**Screenshots**
0.11.2
8334.obj : TriangleMesh with 2323 points and 4647 triangles.
0.12
8334.obj : TriangleMesh with 13941 points and 4647 triangles.
0.13
8334.obj : TriangleMesh with 13941 points and 4647 triangles

![Screenshot_20210726_105429](https://user-images.githubusercontent.com/39189267/126964638-c663edf4-4756-4d63-9207-52335ca2418c.png)

**Environment (please complete the following information):**

- Operating system: Ubuntu 20
- Python version: Python 3.8
- Open3D version: 0.13
- Is this remote workstation?: no
- How did you install Open3D?: pip

**Additional context**
I am attaching the [file](https://drive.google.com/file/d/1l5Y3O7DRpHbCJGJ79TeXfnLAn-SpHvvF/view?usp=sharing) used for the testing.

**Comment by reyanshsolis** [comment]
Hi @dhorka, Thanks for reporting this. For loading `.obj` models, we use `ASSIMP` which might be performing some additional post-processing on the model. I will update you soon.
 
@errissa do you have any idea about the same?

Thanks

**Comment by TrepangCat** [comment]
I have the same problem. And when I write the mesh as .obj file, I find that some vertices repeat several times.

**Comment by reyanshsolis** [comment]
This PR https://github.com/isl-org/Open3D/pull/4119 solves this issue.

Thanks for your patience, 
Rishabh Singh
