### ISSUE TITLE
Search doesn't work in latest doc

### ISSUE THREAD

**Issue by richardrl** [isl-org/Open3D#3802]
http://www.open3d.org/docs/release/python_api/open3d.core.html

If you search any term for 0.13.0, you get this screen:

![image](https://user-images.githubusercontent.com/5181990/127080981-06452c3e-5e90-4b51-b7bb-f37b2fa94a7e.png)

**Comment by ssheorey** [comment]
Thanks for reporting this. Looks like sphinx search broke between v0.12 and v0.13. We'll look into this.

**Comment by ssheorey** [comment]
Possibly this commit upgrading sphinx version from 3.1.2 to 3.5.4:
https://github.com/isl-org/Open3D/commit/6749ab12611f7fd3bcd65038661c643aa2d8b7de#diff-18ec76eaf17930a8825ba4b336f81a24f94c570e9f946062fc36cd1aaffb15b0

**Comment by richardrl** [comment]
![image](https://user-images.githubusercontent.com/5181990/131461526-c728b005-cdfb-45d1-98ca-b8ca761626d8.png)

It is still broken.

**Comment by richardrl** [comment]
@ssheorey Still broken

**Comment by ssheorey** [comment]
@richardrl the fixed search is only available in the latest master here: http://www.open3d.org/docs/latest/index.html.
It will be available for release for the next release (0.14). Look for it early this week.
