### ISSUE TITLE
Open3d availability in Python 3.9 pip

### ISSUE THREAD

**Issue by jackjansen** [isl-org/Open3D#3805]
Now that #3611 has been merged I get the impression that open3d could finally be available for Python 3.9 installation through pip.

Is there an expected time for when this will be available?

**Comment by ssheorey** [comment]
Python 3.9 release wheels will be available on PyPI for the next release 0.14 onward. In the mean time, you can use the devel wheels:

http://www.open3d.org/docs/latest/getting_started.html#development-version-pip

**Comment by jackjansen** [comment]
Ok, I think I'll wait for 0.14, and hope it comes soon. I don't want to contemplate teaching my cicd jobs how to do this for all three of osx/win/linux:-(

**Comment by ssheorey** [comment]
For CI/CD, I would recommend downloading a fixed commit development wheel for each platform and using that for repeatability. We do something similar with many 3rd party packages (C++ source code) in Open3D. We store the 3rd party packages as a github release in the `open3d_downloads` repo. This has a fixed URL that can be used by tools such as `CMake` (C++) and `pip install` (Python).
