### ISSUE TITLE
How to get the size of PointCloud.ply of YOLO predefined region

### ISSUE THREAD

**Issue by yiyangd** [isl-org/Open3D#3807]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

My goal is capturing a Bottle by running Yolov3 and do the registration with the Bottle modelled by using FreeCAD with the exact bottle size (e.g. 16cm height).

However, I noticed that the bottle_yolo.ply is significantly smaller than the bottle_CAD.ply.

Following is I re-scale bottle_yolo by 500 and bottle_CAD by 0.01.

![](https://user-images.githubusercontent.com/25696979/126841970-b964799d-1175-47d5-9a8b-90acde3235ea.png)
I would like to know is there any api to replace my manual solution and could re-scale the bottle_yolo to the real bottle size (as what I did with FreeCAD)?

Thanks!

**Comment by ssheorey** [comment]
You can transform point clouds (scale and rotate) with a known scale factor and rotation. If you don't know the scale factor / rotation, you will need to do registration. See the tutorials here:
http://www.open3d.org/docs/latest/tutorial/pipelines/index.html

Note that very large scale changes (500) may not work.

**Comment by theNded** [comment]
Closed due to the dormant state. Please feel free to reopen.
