### ISSUE TITLE
High quality scene reconstruction is possible?

### ISSUE THREAD

**Issue by sentojh** [isl-org/Open3D#3810]
Hi. I'm trying to use reconstruction pipeline through python api. I'm using realsense l515 to get RGB-D sequences to feed into reconstruction system. I take pictures around my seat and want to get the reconstructed of many object seven if they have quite difficult geometry. In my case, the target object is mug cup.

Rarely, the mug cup is reconstructed well, but they are very few cases. Most cases are poor result in my opinion. Sometimes, cup is missing and the geometry is collapsed. I want to get correct and high quality reconstruction result.

I guess the reason comes from the make fragments or register fragments step due to alignment failure based on RGB-D odometry or loop closure checking to do global registration. But I could not find exact reason and solution to get real world scene reconstruction using rgbd camera.

Here is the result
I uploaded both poor and good case
Below result is gotten just taking the RGB-D sequences in front of cup(180 view only, but I think it is irrelevant. I tried all of thing I could)

quite good case
![Screenshot from 2021-07-27 20-13-27](https://user-images.githubusercontent.com/78716419/127270160-f51d20d3-57d5-47e3-af1e-764cd6c16454.png)

poor case(cup is missing)
![Screenshot from 2021-07-25 22-02-47](https://user-images.githubusercontent.com/78716419/127270099-0a1d24ab-2711-494a-aa98-4f5f0e42bb84.png)

poor case(cup handle is missing)
![Screenshot from 2021-07-25 22-31-12](https://user-images.githubusercontent.com/78716419/127270108-77cd3fab-77e9-4918-935e-0e4ffec3d589.png)

**Comment by sentojh** [comment]
I don't know why some detailed parts of object are collapsed. Is it possible or something should be wrong??

**Comment by theNded** [comment]
The pipeline is mainly designed for scene-scale reconstruction. Pose graph optimization performs an 'average' of poses that can over smooth the trajectory and the scene. So scene details can be blurry.

Potentially the `SLAC` module can refine details, but it is less stable and not guaranteed to converge well at current.

**Comment by theNded** [comment]
VoxelHashing (now DenseSLAM) estimates poses and mapping simultaneously, while RGBD integration assumes known poses. The latter one is usually working with offline reconstruction. It is slower, but could be more accurate than DenseSLAM.
