### ISSUE TITLE
Pointcloud style/color suddenly changes without altering code

### ISSUE THREAD

**Issue by JulianFhofer** [isl-org/Open3D#3815]
Im using the Global Registration example and just a few hours ago when I executed the draw_registration_result method the graphical output looked as follows:

![pinterguss14](https://user-images.githubusercontent.com/63345212/127340247-3c4d2f9c-e7c6-435d-afb8-0731a61a7f3e.png)

A few hours later without changing the code it looks like this:

![pinterguss144](https://user-images.githubusercontent.com/63345212/127340321-d6ca3b5c-a99d-4beb-8253-9d82a4ad6e5e.png)

Can anyone tell me why this happens? Seems like some shader and/or light source is deactivated. Would appreciate it if someone could tell me how to set it back to the state of the first image.

**Comment by theNded** [comment]
Figure 1 is generated with point cloud normals computed. Figure 2 is without normals. Please try to first estimate normals prior to rendering.

Closed for now, feel free to reopen if it does not solve the issue.
