### ISSUE TITLE
Delaunay tetrahedralization of exactly four points yields unexpected results

### ISSUE THREAD

**Issue by li6in9muyou** [isl-org/Open3D#3818]
# Describe the bug
In the if-branch for handling such small point cloud, the return value ```pt_map``` is not  populated with appropriate elements.
```Qhull::ComputeDelaunayTetrahedralization``` returns uninitialized ```pt_map```, as shown below in [this file](https://github.com/isl-org/Open3D/blob/master/cpp/open3d/geometry/Qhull.cpp#L121) .
```c++
std::tuple<std::shared_ptr<TetraMesh>, std::vector<size_t>>
Qhull::ComputeDelaunayTetrahedralization(
        const std::vector<Eigen::Vector3d>& points) {
    typedef decltype(TetraMesh::tetras_)::value_type Vector4i;
    auto delaunay_triangulation = std::make_shared<TetraMesh>();
    std::vector<size_t> pt_map; // initialized with size zero

    if (points.size() < 4) {
        ...
    }

    // qhull cannot deal with this case
    if (points.size() == 4) {
        delaunay_triangulation->vertices_ = points;
        delaunay_triangulation->tetras_.push_back(Vector4i(0, 1, 2, 3));
        // returned an empty pt_map
        return std::make_tuple(delaunay_triangulation, pt_map);
    }
    ...
}
```

# To Reproduce
Use a snippets similar to:
```c++
std::vector<Eigen::Vector3d> four = {
    {1,2,3},{4,5,6},{7,8,9},{10,11,12}
};
std::make_shared<TetraMesh> foo;
std::vector<size_t> pt_map;

std::tie(foo, pt_map) = Qhull::ComputeDelaunayTetrahedralization(four);
assert(pt_map.size() == foo.size()); // 0 != 4

four.emplace_back({13,14,15});
std::tie(foo, pt_map) = Qhull::ComputeDelaunayTetrahedralization(four);
assert(pt_map.size() == foo.size());
```

# Expected behavior
Both assertions pass.

# Remarks
I spot this purely by reading through source. This behaviour may break code that assumes two containers modified/returned by ```Qhull::ComputeDelaunayTetrahedralization``` always has same size.

**Comment by benjaminum** [comment]
Hi @li6in9muyou , thanks for reporting this!

Returning an empty `pt_map` for 4 points seems wrong. It should always be the size of the number of points.

Do you think you can create a PR with a fix for this?
