### ISSUE TITLE
Seeking for advices on human reconstruction

### ISSUE THREAD

**Issue by rampagedog12** [isl-org/Open3D#3826]
I am trying for human reconstruction using Open3D with L515, I think, which is similar to scan a large object.
The result is not good. I want to know the problems in my work and how to improve my procedure.....
I export a set of point clouds from a video captured by L515.
I use plane segmentation and outlier removal to remove the floor and noise.
I register them together according to Multiway registration in [http://www.open3d.org/docs/latest/tutorial/Advanced/multiway_registration.html.](url)
I also change some parameters to adapt my data.
I check all the pairwise result using non-blocking visualization, they look nice.
![QQ图片20210729170827](https://user-images.githubusercontent.com/25874618/127566248-6e958867-2a22-44d0-9a84-e121d8a7144e.jpg)
![QQ图片20210729170836](https://user-images.githubusercontent.com/25874618/127566263-7cf1a726-0abf-40cd-81e1-a6db63c61724.jpg)
However, the full body result isn't.
![QQ图片20210729170844](https://user-images.githubusercontent.com/25874618/127566284-1aa79e8f-d8ef-486f-b29e-532fd51275c4.jpg)
![QQ图片20210729170851](https://user-images.githubusercontent.com/25874618/127566300-45c14146-4af3-406c-9043-652d9d65f12a.jpg)

**Comment by theNded** [comment]
Noise is expected with simple accumulation. Please consider using [RGB-D integration](http://www.open3d.org/docs/latest/tutorial/t_reconstruction_system/integration.html) to get a denoised reconstruction.
