### ISSUE TITLE
Does open3d have Harris corner detection for point cloud?

### ISSUE THREAD

**Issue by arkerman** [isl-org/Open3D#3831]
Are there any related functions in open3d?

**Comment by arkerman** [comment]
Can open3d find the curvature of a point cloud?

**Comment by arkerman** [comment]
Or is there any other library that can realize Harris detection of point cloud?

**Comment by sanskar107** [comment]
We don't have Harris corner detection currently. External contributions in this area are welcomed.

**Comment by arkerman** [comment]
@sanskar107 Okay, I know.
