### ISSUE TITLE
Getting [Open3D INFO] Connection::send() recv failed with: Resource temporarily unavailable when using external observer

### ISSUE THREAD

**Issue by TommasoBendinelli** [isl-org/Open3D#3834]
The external visualizer is not working properly I keep getting:
[Open3D INFO] Connection::send() recv failed with: Resource temporarily unavailable

I do not think is an issue with ssh tunneling, as I sometimes I am getting the point cloud in the local machine GUI, sometimes not. If it was ssh tunneling related should never work, however sometimes it does.

**Comment by benjaminum** [comment]
If sending small point clouds works reliably then the problem is probably the data size.
There is a timeout of 10 seconds to avoid programs blocking forever.

**Comment by theNded** [comment]
Closed for now due to the dormant state. Please feel free to reopen.
