### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by feersantana5** [isl-org/Open3D#3841]
When I use o3d.geometry.TriangleMesh.create_from_point_cloud_alpha_shape(pcd, alpha=0.01) I get:

RuntimeError: QH6019 qhull input error: can not scale last coordinate.  Input is cocircular
   or cospherical.   Use option 'Qz' to add a point at infinity.

While executing:  | qhull d Qbb Qt
Options selected for Qhull 2018.0.1.r 2018/12/28:
  run-id 867987954  delaunay  Qbbound-last  Qtriangulate  _pre-merge
  _zero-centrum  Pgood

**Comment by ssheorey** [comment]
Hi @feersantana5 can you share the point cloud data that gives this error? If it is large / confidential, it would be useful to have a smaller dataset that lets us reproduce this error.
