### ISSUE TITLE
Point Cloud Projection is reversed, images look incorrect

### ISSUE THREAD

**Issue by iacisme** [isl-org/Open3D#3845]
![image](https://user-images.githubusercontent.com/72644814/127760373-0f9fd459-da68-4b51-9047-c95c09829dc4.png)

![image](https://user-images.githubusercontent.com/72644814/127760411-06b33fad-2b89-46a4-bb43-047db291352b.png)

![image](https://user-images.githubusercontent.com/72644814/127760420-1039604d-d6f8-4881-804e-a7877116cc90.png)

Hello folks;

I'm having problems fixing an issue with the point cloud I'm generating.

If you can see by the pictures, it looks like the image is being projected from behind me, instead of infront of me.

I'm stumped, I'm using the OAK-D depthAI cam, and I'm not sure what intrinsic I need to set in order to get the image to project from in front of me.

I've compared the camera intrinsic matrix I'm using, to one of a script I know works (makes the correct piont cloud projection) and they seem consistent (At least by checking cam intrinsics on generated point clouds using open3d).

I'd appreaciate anyone's thoughts or suggestions of how to fix.

Thanks!

**Comment by ssheorey** [comment]
Hi @iacisme can you provide more information?
- RGB image and depth image used to create the point cloud.
- Intrinsic matrix used.
- Open3D code used that gives these results.

**Comment by iacisme** [comment]
[DepthAI_to_Open3D.zip](https://github.com/isl-org/Open3D/files/6927829/DepthAI_to_Open3D.zip)
[rgb_and_depth.zip](https://github.com/isl-org/Open3D/files/6927835/rgb_and_depth.zip)

HI @ssheorey, thank you for your follow-up.

I've included two attachments:

1. DepthAI_to_Open3D.zip - this is the notebook that has all the code I've run. I re-ran the code in the notebook so you'll see all the outputs such as camera intrinsics, etc.
2. An RGB and Depth image from this same sequence, it won't be the same ones run in the notebook, but the results are the same with I make the PCD.

Please let me know if more info is required, I really appreciate the help!

**Comment by theNded** [comment]
I have briefly looked at the data and it seems the depth image has not been correctly stored (or stored with incorrect quantization). Dispite it is stored in `uint16`, it has min value of 0 and max value of 95.

We usually expect the depth pixel value to be in the unit of mm (corresponding to a depth scale factor fo 1000), but this doesn't seem the case. A correct unit should be provided. But even with a correct depth scale, this precision seems unreasonable -- you can only have at most 100 level of depth after quantization.

I would suggest to carefully look at the sensor API and see how to ship uint16 data at a higher precision.

**Comment by theNded** [comment]
Closed due to lack of activity. Please feel free to reopen if you want to revisit the issue.
