### ISSUE TITLE
3D scene reconstruction with constrains

### ISSUE THREAD

**Issue by levmarki** [isl-org/Open3D#3846]
Hello All!
I'm sorry for amateur question...

I want to reconstruct scene from moving the L515 camera on the 2D robot in front of the surface I'm interested in.
If there some way to limit the optimization during stiching to only three axis (x,y, theta)? Since Z position of robot and two other angles won't change.
Thank you in advance!

**Comment by reyanshsolis** [comment]
Hi @levmarki, Sorry we don't have support for that yet. 
However, you may take a look at google-cartographer, which I think supports 2D mapping. 

If you want to construct a 3D scene, with additional information about localization (in your case the fixed height), you may write an EKF node, with input from the visual-based localization and your constraints (if you use IMU, you may also pass X, Y, Z information here), then use the output of this EKF, in the scene reconstruction. 

Closing this issue, for now, feel free to reach out. Also, If you come up with such a feature, please feel welcome to contribute the same to Open3D. Your contributions will be appreciated. 
Thanks and All the best!
