### ISSUE TITLE
draw_geometries

### ISSUE THREAD

**Issue by soccken** [isl-org/Open3D#3850]
Hello.
I’m analyzing point cloud data
The library used for analysis is pytorch-geometric.
Open3d draw_geometries will not work if you import the library with from torch_geometric.nn import.
[Open3D WARNING] GLFW Error: GLX: No GLXFBConfigs returned is displayed and cannot be visualized.
Do you know how to solve this problem?

**Comment by ssheorey** [comment]
Hi @soccken to help us reproduce this error:
- Paste the exact code that gives this error.
- Fill in the system / environment information as asked in the bug reporting template.
