### ISSUE TITLE
what is PrimeSense factory setting?

### ISSUE THREAD

**Issue by AI-ML-Enthusiast** [isl-org/Open3D#3864]
" If it is not given, the PrimeSense factory setting is used instead."
What is PrimeSense factory setting?

I did not find camera intrinsic, how they calculate find it?
https://drive.google.com/open?id=11U8jEDYKvB5lXsK3L1rQcGTjp0YmRrzT

http://www.open3d.org/docs/release/tutorial/reconstruction_system/system_overview.html

Thanks in advanced

**Comment by theNded** [comment]
The factory setting can be found [here](https://github.com/isl-org/Open3D/blob/master/examples/test_data/camera_primesense.json). They could have been calibrated by the [opencv calibration package](https://docs.opencv.org/3.4/dc/dbb/tutorial_py_calibration.html).
