### ISSUE TITLE
Build issue with Open3D v0.13.0 on Windows 10

### ISSUE THREAD

**Issue by 1939938853** [isl-org/Open3D#3868]
Hello,

Now it seems all folders in the 3rdParty folder are empty. Feels quite inconvenient.  Possible to make auto-download the 3rdParty libraries again?

Thank you!

**Comment by ssheorey** [comment]
In `master` all 3rd party folders are downloaded automatically (only once) if not present, so closing this. please re-open if this doesn't work for you with the latest `master`.
