### ISSUE TITLE
normalization in Visualizer

### ISSUE THREAD

**Issue by Leerw** [isl-org/Open3D#3872]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
In Visualizer.add_geometry(), it automatically normalizes the geometry and display,  can I have the option that turn off the automatic normalization?

**Describe alternatives you've considered**
have the option that turn off the automatic normalization

**Additional context**

**Comment by reyanshsolis** [comment]
May you please elaborate on your issue, with an example and screenshot (you may include and compare to other options such as MeshLab output).

Thanks
