### ISSUE TITLE
Build process tries installing to real root filesystem not local temp one

### ISSUE THREAD

**Issue by darenw** [isl-org/Open3D#3881]
I am building Open3D on an Arch Linux machine. Makepkg builds the whole thing, calling cmake for the various pieces. At one point the built files are "installed" into a local  /usr tree using chroot.  At least, that's my understanding; I'm rusty on this stuff. Actual destination is /usr/local/src/open3d/pkg/...  which is inside the git clone I pulled from AUR.  

Many files are installed then the build halts with an error when a file is installed into /usr/share - the line printed out shows it as actually the root /usr/share/ not a folder named usr/share somewhere inside /usr/local/src/open3d/   

I'm not sure if this is a bug in a cmake file, or PKGBUILD used by makepkg, or something goofy about my filesystem. 

The tail of the build's stdout/stderr spewage is this:

```
...
-- Installing: /usr/local/src/open3d/pkg/open3d/usr/bin/Open3D/resources/unlitBackground.filamat
-- Installing: /usr/local/src/open3d/pkg/open3d/usr/bin/Open3D/Open3D
-- Installing: /usr/local/src/open3d/pkg/open3d/usr/bin/Open3D/Open3D.desktop
-- Installing: /usr/share/applications/Open3D.desktop
CMake Error at cpp/apps/cmake_install.cmake:66 (file):
  file INSTALL cannot copy file
  "/usr/local/src/open3d/src/open3d/build/bin/Open3D/Open3D.desktop" to
  "/usr/share/applications/Open3D.desktop": Permission denied.
Call Stack (most recent call first):
  cpp/cmake_install.cmake:57 (include)
  cmake_install.cmake:59 (include)


make: *** [Makefile:83: install] Error 1
==> ERROR: A failure occurred in package_open3d().
    Aborting...
```

**Comment by ssheorey** [comment]
This is the CMake command trying to install in `/usr/share`
https://github.com/isl-org/Open3D/blob/4f70ff19da8f65380a3835c10cbadb1a01c1b80e/cpp/apps/CMakeLists.txt#L86
