### ISSUE TITLE
How can i get a 3d visualizer in my own web?

### ISSUE THREAD

**Issue by QiukuZ** [isl-org/Open3D#3882]
As 0.13.0's video (https://www.youtube.com/watch?v=pLCVCH7ypI4) show, open3D can add a web server by adding only a line code.And then the video show a demo with web 3D visualizer in a dataset website.
How can I put the 3D visualizer into a personal or project web page?

**Comment by ssheorey** [comment]
Duplicate of #3770

**Comment by theNded** [comment]
Please refer to possible updates in #3770.
