### ISSUE TITLE
Segmentation Fault for Colored Point Cloud Registration

### ISSUE THREAD

**Issue by JayKarhade** [isl-org/Open3D#3883]
I have been trying to run the colored point cloud registration for 2 point clouds of raw sizes of approximately 7 million points by following the colored point cloud registration.
However, every time I run the code, it results in a segmentation fault. 
I tried downsampling the two by varying voxel sizes ranging from 0.01 to 0.1 for increasing speed. However, this does not rectify the situation.

I tried this on both 0.12.0 and 0.13.0.  The function that performs the registration is as follows : 

```
def refine_registration(source, target, source_fpfh, target_fpfh, voxel_size):
    '''
    Output: Refined transformation for aligning two point clouds
    '''
    distance_threshold = voxel_size * 0.4
    #downsource = source.voxel_down_sample(voxel_size)
    #downtarget = source.voxel_down_sample(voxel_size)
    #downsource.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=voxel_size, max_nn=30))
    #downtarget.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=voxel_size, max_nn=30))

    result = o3d.pipelines.registration.registration_icp(
        source, target, distance_threshold, result_ransac.transformation,
        o3d.pipelines.registration.TransformationEstimationForColoredICP())
    return result

```
I could not any related issue about this in the previous issues, hence opened up a new one.
Thanks!

**Comment by theNded** [comment]
There is an API mismatch. To use colored ICP, you need to explicitly use the [registration_colored_icp](http://www.open3d.org/docs/release/python_api/open3d.pipelines.registration.registration_colored_icp.html#open3d.pipelines.registration.registration_colored_icp) signature along with the `TransformationEstimationForColoredICP` estimation. I agree that there have been confusions in the API, so in the latest tensor-based API we have merged them.
