### ISSUE TITLE
Jupyter visualizer example not working

### ISSUE THREAD

**Issue by rubenverhack** [isl-org/Open3D#3884]
**Describe the bug**
The example notebook crashes the ipython kernel.
https://github.com/isl-org/Open3D/blob/master/examples/python/visualization/jupyter_visualization.ipynb 

```
import open3d as o3d
from open3d.web_visualizer import draw
cube_red = o3d.geometry.TriangleMesh.create_box(1, 2, 4)
cube_red.compute_vertex_normals()
cube_red.paint_uniform_color((1.0, 0.0, 0.0))
draw(cube_red)
```

**To Reproduce**

Run notebook in vscode or in the browser;

In browser:
```
[I 11:37:44.541 NotebookApp] 302 GET /?token=84ed3591d93c0f284edf62ed5d7bef2182d5e350b093a4a7 (127.0.0.1) 0.800000ms
Exception in callback <TaskWakeupMethWrapper object at 0x7fd59e7eb610>(<Future finis...971"\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x7fd59e7eb610>(<Future finis...971"\r\n\r\n'>)>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending coro=<HTTP1ServerConnection._server_request_loop() running at /home/rverhack/qorepy/libs/geopy/.venv/lib/python3.7/site-packages/tornado/http1connection.py:823> wait_for=<Future finished result=b'GET /api/co...2971"\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /home/rverhack/qorepy/libs/geopy/.venv/lib/python3.7/site-packages/tornado/ioloop.py:688]> while another task <Task pending coro=<MultiKernelManager._async_start_kernel() running at /home/rverhack/qorepy/libs/geopy/.venv/lib/python3.7/site-packages/jupyter_client/multikernelmanager.py:214>> is being executed.
```
In vscode notebook, it crashes silently, when trying to rerun it gives:

```
Error: Session cannot generate requests
Error: Session cannot generate requests
at w.executeCodeCell (/home/rverhack/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1195043623/out/client/extension.js:90:325139)
at w.execute (/home/rverhack/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1195043623/out/client/extension.js:90:324460)
at w.start (/home/rverhack/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1195043623/out/client/extension.js:90:320276)
at async t.CellExecutionQueue.executeQueuedCells (/home/rverhack/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1195043623/out/client/extension.js:90:334803)
at async t.CellExecutionQueue.start (/home/rverhack/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1195043623/out/client/extension.js:90:334343)
```

**Expected behavior**
No crash

**Environment (please complete the following information):**

- Operating system: Ubuntu 18.04
- Python version: 3.7
- Open3D version: 0.13.0
- Is this remote workstation?: yes
- How did you install Open3D?: pip install open3d

**Comment by ssheorey** [comment]
@rubenverhack does your remote workstation have a GPU (embedded is OK)?
Please try running the `draw_webrtc.py` example.
Also report the outputs of `glxinfo` and `eglinfo` (from the package `mesa-utils-extra`) commands.

**Comment by germanros1987** [comment]
Issue closed due to lack of activity. Feel free to open a new issue if you still consider this is a critical matter.

**Comment by Paul373sfo** [comment]
Hi, When I run draw_webrtc.py on VS Code I can visualize the box on a browser with localhost:8888. 

The issue comes when I try to use Jupyter Notebook in VS code using "from open3d.web_visualizer import draw" module. The cell output's rendered showed blank and with the below texts. 
 
![image](https://github.com/isl-org/Open3D/assets/137510558/63a46064-d3ea-479c-a1d2-fcc5fecacb2a)

Any help to address this? Thanks
