### ISSUE TITLE
Transformation Parameters' details in ICP Registration

### ISSUE THREAD

**Issue by yiyangd** [isl-org/Open3D#3891]
Hi, 

I am trying to simulate the example below with my RealSense D435i Depth Camera, I would like to know how could I understand the parameters for initial transformation's parameters and how to define a set of transformation on my own experiment?

![Screenshot from 2021-08-09 08-54-51](https://user-images.githubusercontent.com/25696979/128736229-d85e1703-b3a7-4e14-acd8-2695cc31c3a7.png)

Thanks!

**Comment by JayKarhade** [comment]
The initial set of transformation parameters is often found by performing global registration. Something like RANSAC is used to perform this. Open3D has a set of tutorials for global registration as well which you may want to check. 

I am not sure by what you mean by "how to understand the transformation" but it is a standard homogenous transformation matrix. Hope this helps!

Is this what you were looking for?

**Comment by yiyangd** [comment]
> standard homogenous transformation

Thank you Jay!
Yes that is really helpful for me because I haven't known what is ["standard homogenous transformation"](http://planning.cs.uiuc.edu/node111.html) yet, but thank you for mentioning and now I could study and [try to apply it](https://robotics.stackexchange.com/questions/8053/how-to-use-the-homogeneous-transformation-matrix)!

**Comment by theNded** [comment]
These transformations are for demonstration in the tutorial, and as have mentioned by @JayKarhade could be the output of global registration. For this specific pair, ICP with an initial identity matrix may also work with more iterations.
