### ISSUE TITLE
Build Open3d from source on Windows:  IMPORTED_LOCATION not set for imported target

### ISSUE THREAD

**Issue by FarahSaeed** [isl-org/Open3D#3896]
Hi

I am trying to build from source on Windows following these instructions [http://www.open3d.org/docs/release/compilation.html#windows]

I am following these steps 

```
git clone --recursive https://github.com/intel-isl/Open3D
mkdir build
cd build

cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_INSTALL_PREFIX="C:\libs\Open3DDynamic\Open3D" ..
```

It gives me errors 

```
CMake Error in CMakeLists.txt:
  IMPORTED_LOCATION not set for imported target "OpenMP::OpenMP_CXX"
  configuration "RelWithDebInfo".


CMake Error in CMakeLists.txt:
  IMPORTED_LOCATION not set for imported target "OpenGL::GL" configuration
  "RelWithDebInfo".


CMake Error in CMakeLists.txt:
  IMPORTED_LOCATION not set for imported target "Threads::Threads"
  configuration "RelWithDebInfo".


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

I searched previous issues and found that most solutions recommend "git clone --recursive" but it is still not working. Can you please let me know how where I am mistaken here.

Thanks a lot.

**Comment by cdrose** [comment]
Did you run cmake-gui and configure your build settings?

**Comment by FarahSaeed** [comment]
Yes I tried using cmake gui to configure and generate. It is showing same on that as well.

**Comment by ssheorey** [comment]
`git clone --recursive` is no longer needed. Please look at:

https://github.com/isl-org/Open3D/blob/c7718fd626d2f446bbbf40fd552ffd424e66d7a0/.github/workflows/windows.yml#L115

for the exact Windows build commands. 

Closing this issue since the discussion is out of date. Please reopen if you still have any problems building.
