### ISSUE TITLE
Alignment of two point cloud 

### ISSUE THREAD

**Issue by aditdoshi333** [isl-org/Open3D#3903]
Hello,

I am using two point cloud geometries. I am trying to align them in a way the both of them should have a similar oriented bounding box. I am getting a similar axis-aligned box but the oriented bounding box is different. Is there any way to get the rotation matrix for any one of them and we can use that matrix to rotate the other one. 

Attaching examples of the two geometries. Currently, the boxes are not aligned.

Thank you

![Screenshot from 2021-08-12 00-24-28](https://user-images.githubusercontent.com/23434856/129086964-61db2bf6-9326-48ec-ab3a-d1d2ef01a2aa.png)

**Comment by JayKarhade** [comment]
Hi

You can view the python api here:

http://www.open3d.org/docs/0.9.0/python_api/open3d.geometry.OrientedBoundingBox.html

There are multiple ways of getting the R matrix.

 You can either directly access the class members after getting the bounding box which would be the most straightforward way. 
An alternative albeit not a straightforward and tedious way would be to get the 8 points and have a custom function calculating the angle from the points. 

Is this what you were looking for ? Hope this helps :)

**Comment by theNded** [comment]
@JayKarhade thanks for the answer! Issue closed due to the dormant state, please feel free to reopen.
