### ISSUE TITLE
Support for Orbbec sensors

### ISSUE THREAD

**Issue by whizbuzzer** [isl-org/Open3D#3908]
I have used Open3D in Python3 for point cloud visualization for two sensors so far; the RealSense D455 and the Azure Kinect DK, and I have loved it as it turned out to be faster than PCL.

Currently, I am working to get a PC visualization for the Astra Embedded S sensor by Orbbec, and I would appreciate it if you could provide support for this sensor, or Orbbec sensors in general like you did for the RealSense and Azure sensors.

Also, I wanted to know if there was a way to visualize moving/dynamic voxel grids. So far, I have been successful in creating dynamic point clouds, but I have had no success in creating dynamic voxel grids although the approach was the same as the one for the point cloud. Only static voxel grids could be formed.

**Comment by ssheorey** [comment]
@whizbuzzer Please open a separate issue to visualize dynamic voxel grids.

**Comment by theNded** [comment]
Unfortunately we don't have the bandwidth to support more sensors. It is appreciated if you are willing to contribute to supporting desired sensors. Feel free to make PRs.
