### ISSUE TITLE
o3d.io.read_triangle_mesh

### ISSUE THREAD

**Issue by hernot** [isl-org/Open3D#3917]
**IMPORTANT: Please use the following template to report the bug.**

Before submitting:

1. Search for [similar issues](https://github.com/isl-org/Open3D/issues).
2. For Python issues, please test with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip). It may be already fixed!
_____

**Describe the bug**

After loading *.obj file which has just one texture image `0_0.png`
```
object_path = 3.obj
mesh = o3d.io.read_triangle_mesh(mesh_path)
```
a call to `mesh.has_textures()` returns `False`. Calling  `len(mesh.textures)` returns a length of 2. Checking the two images it appears that the first image is an empty image where `mesh.textures[0].is_empty()` returns `True` whereas the `mesh.textures[1]` stores the actual  texture image.  

**To Reproduce**
see above

**Expected behavior**
The call to `mesh.has_textures()` should return true and `len(mesh.textures)` should return 1 and `mesh.textures[0].is_empty()` should return `False`.

The following can be used as workarround for now:
```
print(mesh.has_textures()) # -> False
if len(mesh.textures) > 1:
  mesh.textures = [ img for img in mesh.textures if not img.is_empty()]
print(mesh.has_textures()) # -> True if has one or more valid texture images otherwise False

**Screenshots**
not applicable 

**Environment (please complete the following information):**

- Operating system: Mint 19 (e.g. Ubuntu 19.04)
- Python version: Python 3.6
- Open3D version: 0.13. and latest development from above
- Is this remote workstation?: no
- How did you install Open3D?: pip 
- Compiler version (if built from source): wheel

**Additional context**

**Comment by ssheorey** [comment]
@hernot can you share the obj file with the read error? Are you able to read it correctly in another software?

**Comment by hernot** [comment]
I can. First i want to check some issues in preparing the Triangle mesh before writing if they could be the cause.

**Comment by hernot** [comment]
Sorry for the delay attached below a tar.gz archive containing two recordings
0.obj was created with open3D 0.13.0
1.obj was created with ooen3D 0.11.2

When loading 1.obj i do see the spurious extra empty 0 texture image and all triangle materials are recoded to material 1
When correcting back to material 0 and removing empty 0 texture image so that texture is again displayed by
 `

**Comment by ssheorey** [comment]
This works correctly in the latest Open3D (and likely in v0.16 as well):

`$ open3d draw path_to_model.obj`

<img width="800" alt="Screenshot 2023-02-24 at 10 31 29 AM" src="https://user-images.githubusercontent.com/41028320/221262924-dc9f37be-99b6-46ca-8106-4e37b134bee4.png">
<img width="816" alt="Screenshot 2023-02-24 at 10 30 47 AM" src="https://user-images.githubusercontent.com/41028320/221262932-990fdb72-18c2-44dc-8f2b-d7f035b9e491.png">

<img width="983" alt="Screenshot 2023-02-24 at 10 34 27 AM" src="https://user-images.githubusercontent.com/41028320/221262888-ae62d861-2bf7-4590-8e00-b77898ac4461.png">
<img width="739" alt="Screenshot 2023-02-24 at 10 33 33 AM" src="https://user-images.githubusercontent.com/41028320/221262907-eb47980c-0f97-4ea8-96b2-192d8af8a722.png">
