### ISSUE TITLE
The source of point cloud in official document

### ISSUE THREAD

**Issue by yiyangd** [isl-org/Open3D#3921]
I would like to know if these poind cloud (cloud_bin_0.pcd, cloud_bin_1.pcd is captured from RealSense RGB-D sensor)

![Screenshot from 2021-08-09 08-54-51](https://user-images.githubusercontent.com/25696979/129425661-02afdd7e-7bf5-436f-8678-e6a7a15c290d.png)

Since I tried to capture poind cloud by my D435i RealSense Sensor, didn't get good results. So I am wondering maybe the "pretty whole-scene point cloud" is hand-made rather than real-life scene captured by sensor.

![Screenshot from 2021-08-09 10-15-12](https://user-images.githubusercontent.com/25696979/129425777-b16d33a3-6791-41bd-8125-58e94335e1f3.png)

**Comment by theNded** [comment]
They are two problems. This point cloud is simulated, but [others](http://www.open3d.org/docs/latest/tutorial/reconstruction_system/make_fragments.html) are real.

You are messing up with either intrinsic or depth scale in your own scanning. It is reckless and unprofessional to doubt the integrity of the community when your single trial does not match your expectation.

**Comment by yiyangd** [comment]
Hi Wei, I am sorry for my reckless and unprofessional question and thank you for your point out this!
