### ISSUE TITLE
How to get each cluster after using DBScan for the point cloud?

### ISSUE THREAD

**Issue by saina110** [isl-org/Open3D#3923]
Dear everyone,

Currently, I am trying to use DBScan to cluster the point clouds, and then pick up the clustered points to do the further processing. **_But What I am frustrated is how to derive each clusters ?_** As far as I know, in PCL, you can easily get each indices of the clustered points after clustering... **_But in Open3D, when you finish the clustering, it only outputs the 1D array with labels [1,1,-1,1,..],_** I don't know how to use easy way to get the clustered points without doing any matrix calculation by myself....

Maybe I missed some API, but according to my current knowledge, I am afraid there is no simple API could provide immediately the clustered points like PCL does...

Thank you for your patience and time

Look forward to your confirmation

Best Regards,

**Comment by saina110** [comment]
without getting each clustered points, I cannot draw the bounding box... this is the reason why I need to get each clustered groups

**Comment by hduonggithub** [comment]
answer is here

https://github.com/isl-org/Open3D/discussions/3722

**Comment by theNded** [comment]
Thanks @hduonggithub for the answer, issue closed for now.
