### ISSUE TITLE
Are the slac and slac_integrate working well in Open3D reconstruction system?

### ISSUE THREAD

**Issue by hwy1992129** [isl-org/Open3D#3926]
**Device:**
- One Realsense L515

**Environment:**

- Operating system: Windows 10 64-bit
- Python version: Python 3.6
- Open3D version: 0.13

**Describe the bug**
I run python run_system.py with different options to learn each step of reconstruction. It starts from make, register, refine, integrate, slac, and slac_integrate. The first 5 options work, but "slac_integrate" has an error.
The tutorial doesn't have much detail about slac.

**To Reproduce**
python run_system.py config/xxxxx.json --make
python run_system.py config/xxxxx.json --register
python run_system.py config/xxxxx.json --refine
python run_system.py config/xxxxx.json --integrate

python run_system.py config/xxxxx.json --slac
python run_system.py config/xxxxx.json --slac_integrate

```
slac non-rigid optimisation.
[Open3D WARNING] Read JSON failed: unable to open file: E:/innovision2021/open3DTest/yzdata/yz_full_capture\20210727_182429\slac/0.030/optimized_posegraph_slac.json
[Open3D Error] (class open3d::core::NumpyArray __cdecl open3d::core::NumpyArray::Load(const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)) D:\a\Open3D\Open3D\cpp\open3d\core\NumpyIO.cpp:290: NumpyLoad: Unable to open file E:/innovision2021/open3DTest/yzdata/yz_full_capture\20210727_182429\slac/0.030/ctr_grid_keys.npy.

Traceback (most recent call last):
  File "run_system.py", line 116, in <module>
    slac_integrate.run(config)
  File "E:\innovision2021\open3DTest\5_12_2021\open3D\Open3D\examples\python\reconstruction_system\slac_integrate.py", line 63, in run
    ctr_grid_keys = o3d.core.Tensor.load(slac_folder + "ctr_grid_keys.npy")
RuntimeError: [Open3D Error] (class open3d::core::NumpyArray __cdecl open3d::core::NumpyArray::Load(const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)) D:\a\Open3D\Open3D\cpp\open3d\core\NumpyIO.cpp:290: NumpyLoad: Unable to open file E:/innovision2021/open3DTest/yzdata/yz_full_capture\20210727_182429\slac/0.030/ctr_grid_keys.npy.
```

I check it seems to be a directory problem. slac create folder "20210727_182429slac"
![image](https://user-images.githubusercontent.com/70329303/129463045-1b409fcb-d3bb-4562-8790-5567bd5ff02e.png)
I create a folder slac in 20210727_182429, and move all the files in `20210727_182429slac` to `20210727_182429/slac`.
It has another error. 
```
slac non-rigid optimisation.
[Open3D Error] (void __cdecl open3d::t::geometry::kernel::tsdf::TouchCPU(class std::shared_ptr<class open3d::core::Hashmap> &,const class open3d::core::Tensor &,class open3d::core::Tensor &,__int64,float,float)) D:\a\Open3D\Open3D\cpp\open3d\t\geometry\kernel\TSDFVoxelGridCPU.cpp:117: No block is touched in TSDF volume, 
abort integration. Please check specified parameters, especially depth_scale and voxel_size

Traceback (most recent call last):
  File "run_system.py", line 116, in <module>
    slac_integrate.run(config)
  File "E:\innovision2021\open3DTest\5_12_2021\open3D\Open3D\examples\python\reconstruction_system\slac_integrate.py", line 94, in run
    config["depth_scale"], config["max_depth"])
RuntimeError: [Open3D Error] (void __cdecl open3d::t::geometry::kernel::tsdf::TouchCPU(class std::shared_ptr<class open3d::core::Hashmap> &,const class open3d::core::Tensor &,class open3d::core::Tensor &,__int64,float,float)) D:\a\Open3D\Open3D\cpp\open3d\t\geometry\kernel\TSDFVoxelGridCPU.cpp:117: No block is touched in TSDF volume, abort integration. Please check specified parameters, especially depth_scale and voxel_size
```

**Additional context**
config values should be initialized in run_system.py or written in the json file....

**Comment by theNded** [comment]
Problem 1): There seems to be a mixed path formation in the code. We will fix it.
Problem 2): There could be many reasons leading to this. Could you please share the output of SLAC and a screenshot of integrated.ply?

**Comment by hwy1992129** [comment]
> Problem 1): There seems to be a mixed path formation in the code. We will fix it.
> Problem 2): There could be many reasons leading to this. Could you please share the output of SLAC and a screenshot of integrated.ply?

I run python run_system.py config/xxxxx.json --slac, and move the files.
![image](https://user-images.githubusercontent.com/70329303/129604662-1aa69cb2-425f-4a4c-90d6-7d0870486f94.png)

I run python run_system.py config/xxxxx.json --slac_integrate. The console shows nothing after "slac non-rigid optimisation" and is stuck there. My config["path_dataset"] ends with ".bag".
I removed the ".bag". It was running, but it has erros, as shown below.
```
slac non-rigid optimisation.
[Open3D Error] (void __cdecl open3d::core::Hashmap::Find(const class open3d::core::Tensor &,class open3d::core::Tensor &,class open3d::core::Tensor &)) D:\a\Open3D\Open3D\cpp\open3d\core\hashmap\Hashmap.cpp:147: [Hashmap]: Invalid key tensor shape

Traceback (most recent call last):
  File "run_system.py", line 116, in <module>
    slac_integrate.run(config)
  File "E:\innovision2021\open3DTest\5_12_2021\open3D\Open3D\examples\python\reconstruction_system\slac_integrate.py", line 91, in run
    config["max_depth"])
RuntimeError: [Open3D Error] (void __cdecl open3d::core::Hashmap::Find(const class open3d::core::Tensor &,class open3d::core::Tensor &,class open3d::core::Tensor &)) D:\a\Open3D\Open3D\cpp\open3d\core\hashmap\Hashmap.cpp:147: [Hashmap]: Invalid key tensor shape
```


The integrated.ply is shown below. Actually, I modified the fragments myself via removing the floor and the irrelevant points for better registration................ Also, if you have some advice on human reconstruction, please let me know....
![image](https://user-images.githubusercontent.com/70329303/129604827-0a7cca0e-de62-4025-be2b-bdba3f7e6366.png)

**Comment by hwy1992129** [comment]
@theNded Hi, any updates on slac?

**Comment by hwy1992129** [comment]
@theNded @ssheorey I think I figured out the problem... The depth scale is not correct... The previous step seems to adjust the depth scale when I load bag file. However, when I run the reconstruction step by step, slac_integrate uses the default depth scale which is not my sensor depth scale....

**Comment by hwy1992129** [comment]
I reopen it... I want to generate a mesh, but I got the following error. The point cloud is managed to integrate.
`Traceback (most recent call last):
  File "run_system.py", line 116, in <module>
    slac_integrate.run(config)
  File "E:\innovision2021\open3DTest\5_12_2021\open3D\Open3D\examples\python\reconstruction_system\slac_integrate.py", line 113, in run
    mesh_legacy = mesh.to_legacy()
AttributeError: 'open3d.cpu.pybind.t.geometry.TriangleMesh' object has no attribute 'to_legacy'`

**Comment by hwy1992129** [comment]
@ssheorey @theNded I change to_legacy() to to_legacy_triangle_mesh(). It works... Please update the document for it....
`>>> dir(o3d.t.geometry.TriangleMesh)
['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'clear', 'clone', 'cpu', 'cuda', 'from_legacy_triangle_mesh', 'get_center', 'get_max_bound', 'get_min_bound', 'is_empty', 'rotate', 'scale', 'to', 'to_legacy_triangle_mesh', 'transform', 'translate', 'triangles', 'vertices']`

**Comment by theNded** [comment]
Sorry for being not responsive. We are working on the new release with new features and will fix these issues in the next phase.

**Comment by hwy1992129** [comment]
> Sorry for being not responsive. We are working on the new release with new features and will fix these issues in the next phase.

It is fine... I go check again. slac_integrate read my instrinsic.json, but it doesn't load the depth_scale in my instrinsic.json.

**Comment by hwy1992129** [comment]
I reopen it again... I found it still has some issues. I test slac_integrate with the same data and different parameter sets. I let the program print the index of frames. It has an error as follows..... 
`69
70
71
[Open3D Error] (void __cdecl open3d::t::geometry::kernel::tsdf::TouchCPU(class std::shared_ptr<class open3d::core::Hashmap> &,const class open3d::core::Tensor &,class open3d::core::Tensor &,__int64,float,float)) D:\a\Open3D\Open3D\cpp\open3d\t\geometry\kernel\TSDFVoxelGridCPU.cpp:117: No block is touched in TSDF volume, abort integration. Please check specified parameters, especially depth_scale and voxel_size`
