### ISSUE TITLE
Building Open3D on arm64 using python2.7

### ISSUE THREAD

**Issue by Aki92-Xavier** [isl-org/Open3D#3941]
I'm trying to build Open3D on Jetson agx Xavier.
cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=ON \
    -DBUILD_CUDA_MODULE=O \
    -DBUILD_GUI=ON \
    -DBUILD_TENSORFLOW_OPS=OFF \
    -DBUILD_PYTORCH_OPS=OFF \
    -DBUILD_UNIT_TESTS=ON \
    -DCMAKE_INSTALL_PREFIX=~/open3d_install \
    -DPYTHON_EXECUTABLE=$(which python2) \
    ..

For the "-DPYTHON_EXECUTABLE" I changed to python2 but when I try to import on python2 it could not work but on python3 it could import.

manilab@manilab:~$ python3
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import open3d
>>>

manilab@manilab:~$ python2
Python 2.7.17 (default, Feb 27 2021, 15:10:58) 
[GCC 7.5.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import open3d
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named open3d

What should I do to use Open3D with python2.7.

**Comment by ssheorey** [comment]
Sorry, we cannot support software where the original authors do not support it. Python 2 is EOL. 
https://www.python.org/doc/sunset-python-2/
