### ISSUE TITLE
open3d.geometry.OrientedBoundingBox

### ISSUE THREAD

**Issue by qsisi** [isl-org/Open3D#3947]
Hello!

As far as I know, when I run:

**bounding_box = open3d.geometry.OrientedBoundingBox(center = XXX, R = XXX, extent = XXX)**

I'm create a bounding box at a certain center with a certain rotation and box size. The thing that frustrates me is that it seems that I can only extent my bounding box in **3** directions since the **args** set in **extent** will simultaneously enlarge the bounding box in two directions. For example when **extent = np.array([X, X, 10])**, the bounding box will extent vertically in both directions. But what if I only need to extent my bounding box upward but not downward? Same situation for the other 4 directions.

It would be so much helpful if someone could help this!

**Comment by sanskar107** [comment]
@qsisi You can change the box center accordingly to deal with this problem.

**Comment by benjaminum** [comment]
@sanskar107 Thanks for providing this solution.
