### ISSUE TITLE
How can I save 16 bit image using open3d.io.write_image?

### ISSUE THREAD

**Issue by AI-ML-Enthusiast** [isl-org/Open3D#3950]
Want to read and write 16-bit image in open3d similar to opencv-python, where we can use cv2.IMREAD_UNCHNAGED.
Also need to use resize the image after reading a image using open3d.
More concretely,

o3d.io.read_image(read 16 bit depth image)
rgbd_image=o3d.geometry.RGBDImage.create_from_color_and_depth(color, depth)

rgbd_image.depth>> I got it as 8 bit image
but I want to save it as 16 bit image as before I read.

**Comment by theNded** [comment]
If you sequentially run `o3d.io.read_image` and `o3d.io.write_image` you will find that the 16-bit is preserved. There could have been other mistakes in say rgbd image construction. 
Closed for now, feel free to reopen.
