### ISSUE TITLE
What will happen to Open3D's future as Intel is shuttering its Realsense camera business?

### ISSUE THREAD

**Issue by nitinkapgate** [isl-org/Open3D#3951]
Hi Dev Team,
Recently I read this news item on Intel is shutting down its Realsense Division [https://www.crn.com/news/components-peripherals/intel-says-it-s-shuttering-realsense-camera-business?itc=refresh](url) .
Should we be worried about Open3D's future because of this?

**Comment by germanros1987** [comment]
Indeed sad news, but Open3D is more alive than ever.

**Comment by nitinkapgate** [comment]
Great to hear that.
