### ISSUE TITLE
[Question] Build failed (Embree on ARM macOS)

### ISSUE THREAD

**Issue by bingkangzhang** [isl-org/Open3D#3955]
Hi，I'm building open3d from source on mac.But when i compile according the script, it fails and throws the following error:
... ...
[ 32%] Built target 3rdparty_qhullcpp
/Users/bingkang.zhang/iOSProjects/Open3D-Build/Open3D/build/libpng/src/ext_libpng/arm/arm_init.c:49:4: error: "PNG_ARM_NEON_FILE undefined: no support for run-time ARM NEON checks"

error "PNG_ARM_NEON_FILE undefined: no support for run-time ARM NEON checks"
^
/Users/bingkang.zhang/iOSProjects/Open3D-Build/Open3D/build/libpng/src/ext_libpng/arm/arm_init.c:86:27: error: implicit declaration of function 'png_have_neon' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
no_neon = !png_have_neon(pp);
^
2 errors generated.
make[5]: *** [CMakeFiles/png_static.dir/arm/arm_init.c.o] Error 1
make[4]: *** [CMakeFiles/png_static.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [libpng/src/ext_libpng-stamp/ext_libpng-build] Error 2
make[1]: *** [CMakeFiles/ext_libpng.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 34%] Built target glfw
CMake Error at CMakeLists.txt:374 (MESSAGE):
Using Embree as static library is not supported with AppleClang >= 9.0 when
multiple ISAs are selected. Please either build a shared library or enable
only one ISA.

-- Configuring incomplete, errors occurred!
See also "/Users/bingkang.zhang/iOSProjects/Open3D-Build/Open3D/build/embree/src/ext_embree-build/CMakeFiles/CMakeOutput.log".
See also "/Users/bingkang.zhang/iOSProjects/Open3D-Build/Open3D/build/embree/src/ext_embree-build/CMakeFiles/CMakeError.log".
make[2]: *** [embree/src/ext_embree-stamp/ext_embree-configure] Error 1
make[1]: *** [CMakeFiles/ext_embree.dir/all] Error 2
make: *** [all] Error 2

what can i do now to complete the build?

**Comment by nitinkapgate** [comment]
Is this on Mac M1?

**Comment by ssheorey** [comment]
@bingkangzhang Please fill out your system / environment information as in the bug reporting template.

**Comment by bingkangzhang** [comment]
> Is this on Mac M1?

Yes, macOS Big Sur, Version 11.2.3, Apple M1, this is my Mac configuration.

Is the compilation failed due to M1？What can I do to complete this compilation？

**Comment by bingkangzhang** [comment]
> @bingkangzhang Please fill out your system / environment information as in the bug reporting template.

- Operating system: macOS Big Sur, Version 11.2.3, Apple M1
- Python version: Python 3.8
- Cmake version: 3.21.0
- Apple clang version: 12.0.5
- Open3D version:0.13.0

**Comment by bingkangzhang** [comment]
@ssheorey @benjaminum I'm trying to change a Mac with Intel chip to compile it, but a new error has occurred.
... 
[ 84%] Linking CXX executable ../../bin/Open3D.app/Contents/MacOS/Open3D
Undefined symbols for architecture x86_64:
 “___CFConstantStringClassReference”, referenced from:
   CFString in Open3DViewer_mac.mm.o
   CFString in Open3DViewer_mac.mm.o
   CFString in Open3DViewer_mac.mm.o
   CFString in Open3DViewer_mac.mm.o
   CFString in Open3DViewer_mac.mm.o
   CFString in Open3DViewer_mac.mm.o
   CFString in Open3DViewer_mac.mm.o
   ...
 “_OBJC_CLASS_$_NSApplication”, referenced from:
   objc-class-ref in Open3DViewer_mac.mm.o
 “_OBJC_METACLASS_$_NSObject”, referenced from:
   _OBJC_METACLASS_$_AppDelegate in Open3DViewer_mac.mm.o
 “_OBJC_CLASS_$_NSObject”, referenced from:
   _OBJC_CLASS_$_AppDelegate in Open3DViewer_mac.mm.o
 “_objc_setProperty_atomic”, referenced from:
   -[AppDelegate setTimer:] in Open3DViewer_mac.mm.o
 “_LSSetDefaultRoleHandlerForContentType”, referenced from:
   Open3DVisualizer::OnMenuItemSelected(int)::‘lambda0’()::operator()() const in Open3DViewer_mac.mm.o
 “_NSHomeDirectory”, referenced from:
   _main in Open3DViewer_mac.mm.o
 “__objc_empty_cache”, referenced from:
   _OBJC_CLASS_$_AppDelegate in Open3DViewer_mac.mm.o
   _OBJC_METACLASS_$_AppDelegate in Open3DViewer_mac.mm.o
 “_objc_alloc”, referenced from:
   _main in Open3DViewer_mac.mm.o
 “_NSApp”, referenced from:
   _main in Open3DViewer_mac.mm.o
   (maybe you meant: __OBJC_PROTOCOL_$_NSApplicationDelegate, __OBJC_LABEL_PROTOCOL_$_NSApplicationDelegate )
 “_objc_getProperty”, referenced from:
   -[AppDelegate timer] in Open3DViewer_mac.mm.o
 “_objc_msgSend”, referenced from:
   -[AppDelegate application:openFile:] in Open3DViewer_mac.mm.o
   _main in Open3DViewer_mac.mm.o
 “_objc_msgSendSuper2”, referenced from:
   -[AppDelegate init] in Open3DViewer_mac.mm.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/Open3D.app/Contents/MacOS/Open3D] Error 1
make[1]: *** [cpp/apps/CMakeFiles/Open3DViewer.dir/all] Error 2

Can you please let me know how where I am mistaken here.

Thanks a lot.

**Comment by benjaminum** [comment]
@bingkangzhang I don't understand the second error you posted. Do you try to cross compile on the Intel Mac?
For the original error there seem to be problems with libpng and embree.

To solve the problem with embree try to replace lines 10-18 in this file https://github.com/isl-org/Open3D/blob/5bb9aece260603681ec6ab13037f1fa9c8be14cb/3rdparty/embree/embree.cmake#L10
with the lines 20-27.

**Comment by bingkangzhang** [comment]
@benjaminum Yes, the second error occurred on the Intel Mac. I solved the first mistake with your solution on Mac M1, but it gives a new error similar to the second error, 
...
Undefined symbols for architecture arm64:
  "rtc::InitializeSSL()", referenced from:
      void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, open3d::visualization::webrtc_server::WebRTCWindowSystem::StartWebRTCServer()::$_4> >(void*) in WebRTCWindowSystem.cpp.o
  "webrtc::I420Buffer::CropAndScaleFrom(webrtc::I420BufferInterface const&, int, int, int, int)", referenced from:
      open3d::visualization::webrtc_server::VideoScaler::OnFrame(webrtc::VideoFrame const&) in PeerConnectionManager.cpp.o
  "webrtc::VideoFrame::VideoFrame(rtc::scoped_refptr<webrtc::VideoFrameBuffer> const&, unsigned int, long long, webrtc::VideoRotation)", referenced from:
      open3d::visualization::webrtc_server::VideoScaler::OnFrame(webrtc::VideoFrame const&) in PeerConnectionManager.cpp.o
...
 "filament::VertexBuffer::Builder::Builder(filament::VertexBuffer::Builder const&)", referenced from:
      open3d::visualization::rendering::TriangleMeshBuffersBuilder::ConstructBuffers() in TriangleMeshBuffers.cpp.o
  "_LAPACKE_sgetri", referenced from:
      open3d::core::InverseCPU(void*, void*, void*, long long, open3d::core::Dtype, open3d::core::Device const&) in InverseCPU.cpp.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/RelWithDebInfo/libOpen3D.dylib] Error 1
make[1]: *** [cpp/open3d/CMakeFiles/Open3D.dir/all] Error 2

What else do I need to change to solve this error？

**Comment by benjaminum** [comment]
@bingkangzhang I suggest disabling BUILD_GUI and BUILD_WEBRTC to see if the build completes without these features.

**Comment by bingkangzhang** [comment]
@benjaminum I agree with you, but How can I disable it? Can you give me some ideas?

**Comment by benjaminum** [comment]
You can use `cmake -DBUILD_GUI=OFF -DBUILD_WEBRTC=OFF ..` in the build directory or use cmakes configuration utility in the build directory with `ccmake .`

**Comment by benjaminum** [comment]
Updating to the latest versions for TBB and parallelstl could help to resolve the problem.

**Comment by ZongqingHou** [comment]
@bingkangzhang You can download the embree on the noticed specific version and build by yourself. Then replace the path in the find_dependencies.cmake file which is in the 3rdparty folder. I solved this problem on Apple M1 chip.

**Comment by devNi3** [comment]
Found mac-arm supported embree here https://www.embree.org/. Where can we get the latest parallelstl from?

**Comment by ZongqingHou** [comment]
@devNi3 Install the parallelstl lib by brew, it was renamed as onedpl. After installation, replace the .cmake file in the find_dependencies.cmake file.

**Comment by Jaykob** [comment]
@ZongqingHou Can you explain what you exactly mean by replacing the .cmake file?

**Comment by yxlao** [comment]
Hi folks, we now have an experimental build for Apple Silicon. I encourage you to try it out and tell us if it works for you. Thanks! 

See https://github.com/isl-org/Open3D/issues/2675#issuecomment-980613404 for details.

**Comment by tgoelles** [comment]
The same problem arrises when I build a linux container on M1 and try to build arm open3d from source.

**Comment by yxlao** [comment]
We have uploaded the Apple Silicon wheel to pip for the 0.14 release. 

1. Get python 3.8 or python 3.9
2. Install Apple Silicon wheel:
   ```bash
   pip install open3d
   ```
3. Checkout the known issues at: https://github.com/isl-org/Open3D/pull/4428

Please create a new issue if you run into problems.

**Comment by yxlao** [comment]
The embree compilation problem has been fixed via #4428
