### ISSUE TITLE
Would you mind build a NDK crossing complier for users? It realy helps.

### ISSUE THREAD

**Issue by 44825762** [isl-org/Open3D#3957]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ssheorey** [comment]
@44825762 Please fill out the complete form so that we have some idea what you need.

**Comment by theNded** [comment]
Closed due to the dormant state. Please feel free to reopen.
