### ISSUE TITLE
 [Open3D ERROR] GLFW Error: GLX: Failed to create context: BadLength 

### ISSUE THREAD

**Issue by newera-001** [isl-org/Open3D#3959]
When i run my py file about visualization error, the error detail information as follows：

 File "drinktest.py", line 14, in <module>
    model.show_results(data, result, out_dir='results')
  File "/root/mmdetection3d-master/mmdet3d/models/detectors/base.py", line 107, in show_results
    show_result(points, None, pred_bboxes, out_dir, file_name)
  File "/root/mmdetection3d-master/mmdet3d/core/visualizer/show_result.py", line 98, in show_result
    vis = Visualizer(points)
  File "/root/mmdetection3d-master/mmdet3d/core/visualizer/open3d_vis.py", line 362, in __init__
    self.o3d_visualizer.create_window()

 [Open3D ERROR] GLFW Error: GLX: Failed to create context: BadLength (poly request too large or internal Xlib length error)

Hope that there has some guys could help me ，thinks a lot!

**Comment by ssheorey** [comment]
Hi @newera-001 please fill out the bug reporting template with info about your system / environment.
Add a minimal example that will let us reproduce this issue.

**Comment by theNded** [comment]
Closed due to dormant state. Please feel free to reopen.

**Comment by FuckingNoO** [comment]
i also met the issue? could anyone solve this issue?
