### ISSUE TITLE
How to create open3d.t.geometry.Image from numpy depth image of Uint16?

### ISSUE THREAD

**Issue by maohong30** [isl-org/Open3D#3962]
I have two numpy arrays:-

 1. RGB color image numpy array of (height, width, 3) uint8 
2. Depth numpy array of (height,width,1) uint16.
 
And I want to create tensor RGBDImage pair with `open3d.t.geometry.RGBDImage`

The two required parameters are:-

1. Color (open3d.t.geometry.Image) – The color image
2. Depth (open3d.t.geometry.Image) – The depth image

So to produce the above required parameters from the numpy arrays , i wrote:

```
rgb = o3d.geometry.Image(color_np)
depth = o3d.geometry.Image(depth_np)
color_from_np = o3d.t.geometry.Image.from_legacy_image((rgb) , device = self.o3d_device)
depth_from_np = o3d.t.geometry.Image.from_legacy_image((depth) , device = self.o3d_device)
```
However, the codes are only working for the Color image perfectly but not for Depth image. I think the problem is with the depth array being uint16.

When i printed out the matrix of the Depth in numpy after conversion for checking, the elements jumped like below with some unknown elements in between.

![130245763-cbdaa22c-80e3-49e7-8e11-1e9c3bca75c9](https://user-images.githubusercontent.com/77562730/130732825-cd3d249a-e23e-4a0e-bee2-24993daab7a9.jpg)

I hope somebody can help me. 

Environment:
Open3d: V0.13
Operating system: Windows 10 64-bit
Python version: Python 3.8
Cuda: 10.1
GPU : Nvidia RTX 2070
Camera: Realsense D415
Visual studio 2019
Spyder

**Comment by maohong30** [comment]
The codes below don't seem to work for Uint16. I am stucked here for some time. 
@ssheorey Do you think you can help me with this? Thank you very much.

```
o3d.t.geometry.Image.from_legacy_image((depth) , device = self.o3d_device)

o3d.t.geometry.Image(depth)
```

**Comment by ssheorey** [comment]
Hi @maohong30 you can convert a Numpy array to an Open3D image by going through a Tensor. See documentation for APIs for converting from Numpy to Tensor and then  `t.geometry.Image`.
```
>>> b = np.ones((2,2,3), dtype=np.uint16)
>>> ob = o3d.t.geometry.Image(o3d.core.Tensor(b))
>>> b
array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]], dtype=uint16)
>>> ob.as_tensor()
[[[1 1 1],
  [1 1 1]],
 [[1 1 1],
  [1 1 1]]]
Tensor[shape={2, 2, 3}, stride={6, 3, 1}, UInt16, CPU:0, 0x55a392553ae0]
>>> ob
Image[size={2,2}, channels=3, UInt16, CPU:0]
```

**Comment by maohong30** [comment]
@ssheorey Thank you very much. Problem solved.
