### ISSUE TITLE
Issue when build from source on Ununtu

### ISSUE THREAD

**Issue by wangdongw** [isl-org/Open3D#3964]
When I make, the following issues occured.

-- Configuring done
CMake Error at CMakeLists.txt:11 (add_library):
  No SOURCES given to target: ippiw

CMake Generate step failed.  Build files cannot be regenerated correctly.
CMakeFiles/ext_ippicv.dir/build.make:91: recipe for target 'ippicv/src/ext_ippicv-stamp/ext_ippicv-configure' failed
make[2]: *** [ippicv/src/ext_ippicv-stamp/ext_ippicv-configure] Error 1
CMakeFiles/Makefile2:1062: recipe for target 'CMakeFiles/ext_ippicv.dir/all' failed
make[1]: *** [CMakeFiles/ext_ippicv.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by sanskar107** [comment]
@wangdongw Could you provide your build configuration and full logs?

**Comment by reyanshsolis** [comment]
may you please share more details about your system?
Are you using an x86 processor / ARM processor device / Jetson?

On Jetson, IPPICV is not available yet, you might want to use CUDA device on Jetson, as NPP is available.

**Comment by ssheorey** [comment]
@wangdongw your repo may be corrupted. Please try building again from a fresh clone. Closing for now. Feel free to reopen if you still have problems.
