### ISSUE TITLE
Build form source,some issues.

### ISSUE THREAD

**Issue by wangdongw** [isl-org/Open3D#3968]
(base) wangdongw@wangdongw-MS-7B89:~/test_my/fast_point_cloud_sampling/Open3D/build$ make install
[  1%] Built target ext_ippicv
[  2%] Built target ext_mkl_include
[  3%] Built target ext_parallelstl
[  4%] Built target ext_zlib
-- [download 100% complete]
CMake Error at /home/wangdongw/test_my/fast_point_cloud_sampling/Open3D/examples/test_data/download_test_data.cmake:30 (file):
  file DOWNLOAD HASH mismatch

    for file: [/home/wangdongw/test_my/fast_point_cloud_sampling/Open3D/examples/test_data/open3d_downloads/RGBD/normal_map.npy]
      expected hash: [ce3eb60bef47179e9099bad2efecf76dac5cdb305c3c1dc45bd8dfd34502586f]
        actual hash: [e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855]
             status: [7;"Couldn't connect to server"]

Call Stack (most recent call first):
  /home/wangdongw/test_my/fast_point_cloud_sampling/Open3D/examples/test_data/download_test_data.cmake:48 (download_dataset_file)

**Comment by ssheorey** [comment]
A file download was interrupted due to network issues. Please re-run cmake. Try with a clean build folder if you still have problems.

**Comment by wangdongw** [comment]
Thank you for your help.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月25日(星期三) 上午9:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [isl-org/Open3D] Build form source,some issues. (#3968)





 
A file download was interrupted due to network issues. Please re-run cmake. Try with a clean build folder if you still have problems.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
