### ISSUE TITLE
Open3D Build Error MSB8066 and C4819 from Visual Studio

### ISSUE THREAD

**Issue by wodndb** [isl-org/Open3D#3975]
**Describe the bug**
MSB8066 and Lot's of C4819 and recognized error for C4819 in Visual Studio.

**To Reproduce**
1. `git clone --recursive -b v0.13.0 https://github.com/isl-org/Open3D.git`
2. open cmake GUI and configure for Visual Studio 2019 x64
3. generate a project using cmake.
4. Open the project using Visual Studio 2019.
5. Build ALL_BUILD solution with Release.

**Expected behavior**
Build well

**Screenshots**

##### MSB8066
```
심각도	코드	설명	프로젝트	파일	줄	비표시 오류(Suppression) 상태
오류	MSB8066	'C:\Open3D\build\CMakeFiles\f3d45eafc58ca2a28074dfe0116656f9\open3d_downloads-download.rule;C:\Open3D\build\CMakeFiles\f3d45eafc58ca2a28074dfe0116656f9\open3d_downloads-update.rule;C:\Open3D\build\CMakeFiles\f3d45eafc58ca2a28074dfe0116656f9\open3d_downloads-patch.rule;C:\Open3D\build\CMakeFiles\f3d45eafc58ca2a28074dfe0116656f9\open3d_downloads-configure.rule;C:\Open3D\build\CMakeFiles\f3d45eafc58ca2a28074dfe0116656f9\open3d_downloads-build.rule;C:\Open3D\build\CMakeFiles\f3d45eafc58ca2a28074dfe0116656f9\open3d_downloads-install.rule;C:\Open3D\build\CMakeFiles\c75044d5f6961d00978770d58f0fff78\open3d_downloads-complete.rule;C:\Open3D\build\CMakeFiles\0a47d2e5f68e6be8e1dbe12a97b46eec\open3d_downloads.rule'에 대한 사용자 지정 빌드가 종료되었습니다(코드 9009).	open3d_downloads (ExternalProjectTargets\open3d_downloads\open3d_downloads)	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	241	
```

##### C4819
![image](https://user-images.githubusercontent.com/8624058/130730189-2448c467-2c5f-48fb-ba0e-547fd610f021.png)

**Environment (please complete the following information):**

- Operating system: Windows 10 64bit 21H1 (Korean)
- Python version: Python 3.9
- Open3D version: 0.13.0
- Is this remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): MSVC 19.29.30133.0

**Additional context**
Well.. I success Open3D under v0.11.2 version.
Now I try hard to convert encoding of source codes...

**Comment by wodndb** [comment]
What is a proper encoding for Open3D codes to build?

**Comment by wodndb** [comment]
No way. I can't be solve the error MSB8066.

**Comment by ssheorey** [comment]
HI @wodndb does adding the  `/UTF-8` compiler option to MSVC resolve the errors? Open3D code *should* be UTF-8, but we have not  run into these issues before.

**Comment by wodndb** [comment]
@ssheorey Maybe I didn't. I'm going to build Open3D 0.14.x. with encoding option.

**Comment by wodndb** [comment]
I have some error to build v0.14.1 (https://github.com/isl-org/Open3D/issues/4584).

I will retry build Open3D after solve that

**Comment by wodndb** [comment]
I don't know but I success to build Open3d v0.13.0 works well.

0. Install python 3.9 using Microsoft store
1. `git clone -b v0.13.0 --recurse git@github.com:isl-org/Open3D.git`
2. cmake build using Cmake GUI
3. open Visual Studio
4. Change solution to release and build ALL_BUILD
5. build INSTALL
