### ISSUE TITLE
Removing points from a point cloud relative from another cloud.

### ISSUE THREAD

**Issue by space219** [isl-org/Open3D#3977]
Hi, 
I am working with a point cloud data and I have access to two point clouds - one with all the ground plane points, and the other with all the elevated points. I am trying to find a way to filter the points in the elevated point cloud of less than 2m relative to the ground. I tried numpy filtering using `np.where` but it doesn't give the right result if I filter using a common z-axis threshold as the ground is not entirely a flat plane (max value in the z axis for the ground is 6m). Would be great if I could get some help. 

This is how I was trying to filter it currently. 

```python
elevation_extraction = non_ground_cloud.select_by_index(np.where(np.asarray(non_ground_cloud.points) < 2)[0])
```</div>

**Comment by JulianFhofer** [comment]
Hey, I've recently had a very similar problem where I needed to remove outliers of one pointcloud relative to a second one. Here's the code:

    def remove_outliers(self):
        """Remove outliers from pointcloud"""

        distances = np.asarray(self._source_pointcloud_transformed.compute_point_cloud_distance(self._target_pointcloud_transformed))

        # indices containing inliers
        indices = np.array(list(set(np.concatenate((np.where(distances < 15)))))).astype(int)
        self.display_inlier_outlier(self._source_pointcloud_transformed, indices)

        # update source pointcloud to contain inliers only
        self._source_pointcloud_temp = self._source_pointcloud_temp.select_by_index(indices)

        distances = np.asarray(self._target_pointcloud_transformed.compute_point_cloud_distance(self._source_pointcloud_transformed))

        # indices containing inliers
        indices = np.array(list(set(np.concatenate((np.where(distances < 15)))))).astype(int)
        self.display_inlier_outlier(self._target_pointcloud_transformed, indices)

        # update source pointcloud to contain inliers only
        self._target_pointcloud_temp = self._target_pointcloud_temp.select_by_index(indices)

**Comment by surmitbhui** [comment]
@JulianFhofer thank you so much. This makes it a lot clearer!
