### ISSUE TITLE
fully implement reading of .pcd files.

### ISSUE THREAD

**Issue by odddozen** [isl-org/Open3D#3988]
the .pcd file format allows for fields to be extended.  this means it can neatly hold data about the label or object of a point.  this can be very handy for ML tasks.  However, the open3d file io does not appear to be able to read other fields other than the xyz, rgb, normals etc .  I haven't been able to find where in the open3d structure the code for the file io pcd loading is implemented to attempt a solution.  geometry.pointcloud does not appear to have the ability to hold custom fields as well.

It'd be nice to have the ability to read .pcd files with other fields in them (as per the .pcd file specification), whether this is implemented in the pointcloud class or via another means.

**Comment by reyanshsolis** [comment]
Added the features in the new Tensor API IO (v0.14.0). PR: https://github.com/isl-org/Open3D/pull/3978.

**Comment by qenops** [comment]
How does one access the new Tensor API from python? I am trying to read and write .pcd files that contain multiple fields. Is it possible to do in the current release of Open3d?
