### ISSUE TITLE
[Open3D 0.13.0 Version] - "Real-time" and "Live" 3D reconstruction pipeline with Open3D

### ISSUE THREAD

**Issue by vanloctc** [isl-org/Open3D#3993]
I have a question about the "Real-Time 3D Reconstruction pipeline". I'm really confused with 2 words "Real-time" from Open3D Reconstruction.

1.   I think the "Real-time" mode will be operating with frame by frame from the Camera. It means, If how many frames from the Camera so "Real-time 3D Reconstruction" will process that frames in that time. But In Open3d-Video (link below) from 0:11 to 0:50 (seconds). Seem to be "Real-time 3D Reconstruction pipeline just worked with available data (3001 frames in the video). Is that right? 

2.   Besides, If the question (1) above is correct so Any method for Open3D Reconstruction that can operate with "live mode" from frame to frame with live frame from the Camera?

Thank you.
_____
![Untitled](https://user-images.githubusercontent.com/48701460/131277731-2ad3a2ad-6e29-43bf-a15b-09c6e8880f41.png)
_____
Link 1: Open3D Release v0.13.0 [https://www.youtube.com/watch?v=pLCVCH7ypI4](url)

**Comment by theNded** [comment]
1) Real-time refers to the system performance. If a system runs with frame rate, which is typically 30Hz, then it is real-time. I believe it is the common usage in the community.
2) We don't have a live reconstruction system as of now. We have an online streamer for RealSense (https://github.com/isl-org/Open3D/blob/master/examples/python/gui/online-processing.py). A combination of the streamer and the reconstruction system is in our plan.
