### ISSUE TITLE
[ VoxelHashingGUI - Open3D v0.13.0 ] - Can't found VoxelHashingGUI (code) in Open3D SourceCode 

### ISSUE THREAD

**Issue by vanloctc** [isl-org/Open3D#4005]
** Thanks for your good solution.

Regarding the Real-Time Reconstruction Open3D - VoxelHashingGUI.cpp. I remember that VoxelHashingGUI has been released a few times but now I can't found that code or binary file (when building success). Is there any problem or where can I get that code.
_____
The Link mention to VoxelHashingGUI.cpp:  https://github.com/isl-org/Open3D/issues/3556
_____
Thank you very much.

**Comment by theNded** [comment]
This has been renamed to `DenseSLAMGUI.cpp`:
https://github.com/isl-org/Open3D/blob/master/examples/cpp/DenseSLAMGUI.cpp.

A tutorial will come in a later release.

**Comment by theNded** [comment]
Tutorial is available in the latest doc. Closed for now.
