### ISSUE TITLE
eglInitialize failed error while headless rendering in Docker

### ISSUE THREAD

**Issue by alonks1234** [isl-org/Open3D#4011]
**Describe the bug**
Headless render in Docker throwing eglInitialize failed error

**Expected behavior**
I would expect the headless render mode to work in docker, like it does locally.

**Environment (please complete the following information):**

- Operating system: (e.g. Docker (Ubuntu 20.04) 64-bit)
- Python version: (e.g. Python 3.8)
- Open3D version: 0.13
- Is this remote workstation?: no
- How did you install Open3D?: (pip)
- Compiler version (if built from source):

**Additional context**
I have some code to take a pointcloud (numpy), turn it into an open3d pointcloud, and use open3d.visualization.rendering
to render depth and rgb images.

When running this through docker, I keep getting error:
```
[Open3D INFO] EGL headless mode enabled.
FEngine (64 bits) created at 0x7fbefde2f010 (threading is enabled)
eglInitialize failed
```
while running
```open3d.visualization.rendering.OffscreenRenderer(640, 480, headless=True)```

**Comment by alonks1234** [comment]
I have made a simple reproduction of the bug on my (amd ryzen7, nvidia rtx 3050 laptop):

Dockerfile
```
FROM ubuntu:20.04

RUN apt-get update
RUN apt-get -y install python3-pip python3-dev
RUN DEBIAN_FRONTEND="noninteractive" apt-get install -y tzdata
RUN apt-get install -y ffmpeg libsm6 libxext6
RUN apt-get install -y libegl1

RUN pip install open3d
RUN apt-get update
COPY test_open3d.py /home/test_open3d.py
```

test_open3d.py:
```
import open3d


if __name__ == "__main__":
    render = open3d.visualization.rendering.OffscreenRenderer(640, 480, headless=True)

```

**Comment by alonks1234** [comment]
I think i figured it out. I needed to use nvidia-docker instead of docker.
Installed via steps on https://cnvrg.io/how-to-setup-docker-and-nvidia-docker-2-0-on-ubuntu-18-04/

**Comment by ssheorey** [comment]
@alonks1234 Open3D needs access to the GPU through docker for any rendering to work. With NVIDIA GPUs, you can also use the `--gpus=all` option to `docker run`.

**Comment by alonks1234** [comment]
@ssheorey 
Is there some way to do headless rendering in docker, on a machine without a GPU?

I can't use --gpus=all because this links back to cuda/nvidia drivers, which the machine would not have.

Thanks!

**Comment by ssheorey** [comment]
If you want CPU rendering, please open a new feature request. This is something we may look into in the future.

**Comment by theNded** [comment]
Redirected to #4013. Closed for now.
