### ISSUE TITLE
How to build a high-dimensional point cloud and apply KDTree on it

### ISSUE THREAD

**Issue by aoligei178** [isl-org/Open3D#4015]
Hi! I'm interested in open3d and want to do 6D pose estimation based on it. 
But when I try to build my own descriptor for a keypoint in point cloud, I encountered this problem: I saw ''pcd.points = o3d.utility.Vector3dVector(pcd.points) '' which can build 3-dimention point cloud, but if I want to build a  high-dimensional point cloud in feature space, what should I do? Can open3d do this?
Thank you !

**Comment by theNded** [comment]
It was not supported in the legacy point cloud, but you may specify point-wise features **in addition** to the [tensor-based 3D point cloud](http://www.open3d.org/docs/release/python_api/open3d.t.geometry.PointCloud.html#open3d.t.geometry.PointCloud).
