### ISSUE TITLE
How to change the camera position and rotation when saving point cloud to image?

### ISSUE THREAD

**Issue by haodongyu** [isl-org/Open3D#4021]
Hallo,

I'm trying to save an image from my point cloud. It can works if I don't add any changes like this:

```
def save_pcd_asIMG(pc ,FileName = None):

    sampled = np.asarray(pc)
    PointCloud_koordinate = sampled[:, 0:3]
    point_cloud = open3d.geometry.PointCloud()
    point_cloud.points = open3d.utility.Vector3dVector(PointCloud_koordinate)
    point_cloud.colors = open3d.utility.Vector3dVector(sampled[:, 3:])

    vis = open3d.visualization.Visualizer()  
    vis.create_window(visible=False) #works for me with False, on some systems needs to be true
    ctr = vis.get_view_control()
    vis.add_geometry(point_cloud)

   # vis.update_geometry(point_cloud)
    vis.poll_events()
    vis.update_renderer()
    vis.capture_screen_image(FileName)
    vis.destroy_window()
```
But in this situation, the view of image is not what I want.
![Scene5_1](https://user-images.githubusercontent.com/63580500/132279865-00512771-d382-4ddd-84fa-a14177ec163b.jpg)
I want to get a result that is opposite to the current perspective. Such like this:
<img width="313" alt="001" src="https://user-images.githubusercontent.com/63580500/132280090-ef686ced-809d-4c37-a5d9-0aee9167aca3.PNG">
How should I change my code?  Thank you inadvance.

**Comment by theNded** [comment]
@akgoins thanks for the solution! Issue closed for now.
