### ISSUE TITLE
run_system.py error during make custom Dataset

### ISSUE THREAD

**Issue by Ed0flower93** [isl-org/Open3D#4022]
Hello, I'm trying to reconstruct my own file but I experienced in this error, while if I run the Dataset downloaded from L515 example this error do not appear.
I'm acquire the data with a D435 camera. and i will show you the error in the image. 
For every doubt I am available, Thanks
![error_1](https://user-images.githubusercontent.com/64417077/132322013-71811bcf-3ac0-4cb0-b1f9-4ab81b0acccf.png)
![error_2](https://user-images.githubusercontent.com/64417077/132322024-2bb489ef-c9dd-4470-b55f-3f0135138610.png)
![realsensejsonfile](https://user-images.githubusercontent.com/64417077/132322029-721549c0-09c3-4f17-b0ce-bddd2e736a1c.png)

**Comment by theNded** [comment]
Could you please show the folder structure? It looks like the files are not loaded correctly.

**Comment by theNded** [comment]
Closed due to lack of activity. Please feel free to reopen if you can provide more details.
