### ISSUE TITLE
OpenCV loads 0x0 px image when linked in the same program with Open3D

### ISSUE THREAD

**Issue by igzer89** [isl-org/Open3D#4023]
**Describe the bug**
OpenCV cannot load an image when linked to the same app with Open3D (see MWE below). After commenting-out the line `open3d::visualization::gui::Application::GetInstance();`, OpenCV suddenly proceeds to correctly load the image.

I think either the Open3D library or one of its dependencies interfere with OpenCV. After uncommenting `open3d::visualization::gui::Application::GetInstance();`, I can see these extra linked libraries via `ldd`:
```
'libGLEW.so.2.1 => /lib/x86_64-linux-gnu/libGLEW.so.2.1',
'libOpen3D.so => /usr/local/lib/libOpen3D.so',
'libOpenGL.so.0 => /lib/x86_64-linux-gnu/libOpenGL.so.0',
'libc++.so.1 => /lib/x86_64-linux-gnu/libc++.so.1',
'libc++abi.so.1 => /lib/x86_64-linux-gnu/libc++abi.so.1',
'libcublas.so.11 => /usr/local/cuda-11.4/lib64/libcublas.so.11',
'libcublasLt.so.11 => /usr/local/cuda-11.4/lib64/libcublasLt.so.11',
'libcusolver.so.11 => /usr/local/cuda-11.4/lib64/libcusolver.so.11',
'libglfw.so.3 => /lib/x86_64-linux-gnu/libglfw.so.3',
'libmkl_intel_thread.so => /lib/x86_64-linux-gnu/libmkl_intel_thread.so',
'libnppc.so.11 => /usr/local/cuda-11.4/lib64/libnppc.so.11',
'libnppicc.so.11 => /usr/local/cuda-11.4/lib64/libnppicc.so.11',
'libnppif.so.11 => /usr/local/cuda-11.4/lib64/libnppif.so.11',
'libnppig.so.11 => /usr/local/cuda-11.4/lib64/libnppig.so.11',
'libnppim.so.11 => /usr/local/cuda-11.4/lib64/libnppim.so.11',
'libomp.so.5 => /lib/x86_64-linux-gnu/libomp.so.5'
```

**To Reproduce**
main.cpp
```cpp
#include <stdio.h>
#include <opencv2/opencv.hpp>
#include <open3d/Open3D.h>

int main(int argc, char *argv[])
{
    cv::Mat img = cv::imread("/tmp/image.jpg");
    printf("Resolution: %dx%d\n", img.cols, img.rows);
    
    // The program's output when the line below is commented: "Resolution: 1280x720"
    // Uncomment the line below and the program's output is: "Resolution: 0x0"

    // open3d::visualization::gui::Application::GetInstance();
}
```

CMakeLists.txt
```cmake
cmake_minimum_required(VERSION 3.20)
project(open3d_test)

set(CMAKE_CXX_STANDARD 14)

find_package(Open3D REQUIRED)
find_package(OpenCV REQUIRED)

include_directories(${Open3D_INCLUDE_DIRS})
include_directories(${OpenCV_INCLUDE_DIRS})

add_executable(open3d_test main.cpp)

target_link_libraries(open3d_test Open3D::Open3D ${OpenCV_LIBS})
```

**Expected behavior**
OpenCV should load the image even when Open3D and its dependencies are linked. The app should print "Resolution 1280x720" regardless if `open3d::visualization::gui::Application::GetInstance();` is (un)commented.

**Environment (please complete the following information):**

- Operating system: Ubuntu 20.04
- Python version: *not using Python*
- Open3D version: 0.13.0
- Is this remote workstation?: no
- How did you install Open3D?: built from source
- Compiler version (if built from source): gcc 9.3

**Additional context**
When building Open3D from source, I enabled CXX11 ABI otherwise I could not even build the MWE above. I also enabled ABI description when building OpenCV from source.

**Comment by ssheorey** [comment]
This should be resolved in master / latest. The example code produces the correct output now.
