### ISSUE TITLE
Sample points inside a mesh

### ISSUE THREAD

**Issue by Hassan-math** [isl-org/Open3D#4024]
Hi,

In geometry processing, sometimes we need to sample points **_inside_** a mesh. I searched in the open3D documentations, but I only found a surface sampling method using `mesh.sample_points_uniformly`, not inside the mesh. So, I would like to suggest you add this feature to the package.

Regards,

**Comment by theNded** [comment]
Sampling inside a mesh is not a conventional operation. Is there any reference for doing it?

**Comment by Hassan-math** [comment]
Sampling inside mesh is nessesary in geometry processesing when we want to do a physics-based simulation and model the mechanical and physical properties of a mesh.
I found an implementation in sampling random points inside a mesh in **trimesh** package with following code:
```
trimesh.sample.volume_mesh(mesh, count)
```
this uses rejection sampling to produce points randomly distributed in the volume of a mesh.
you can find the documentation here:

[https://trimsh.org/trimesh.sample.html](url)

**Comment by theNded** [comment]
Thanks for the update, this looks more like a voxel-related operation -- voxelization followed by sampling. I will look into that.

**Comment by benjaminum** [comment]
@Hassan-math Checkout http://www.open3d.org/docs/latest/tutorial/geometry/distance_queries.html
We added this new class in v0.14.
You can create a grid of points and query if the point is inside the mesh with this.
Hope this helps.
