### ISSUE TITLE
open3d.t.io.RSBagReader not reading Bag file

### ISSUE THREAD

**Issue by maohong30** [isl-org/Open3D#4036]
Hi.
I recorded a **bag** file with the following example.
Open3d/examples/python/reconstruction_system/sensors/realsense_recorder.py
by running-

`run realsense_recorder.py --record_rosbag`

using the configuration-
```
{
  "serial": "",
  "color_format": "RS2_FORMAT_RGB8",
  "color_resolution": "1280,720",
  "depth_format": "RS2_FORMAT_Z16",
  "depth_resolution": "1280,720",
  "fps": "30",
  "visual_preset": ""
}
```
I am able to read the bag file recorded above by running the code below and play on Intel RealSense Viewer

`run realsense_recorder.py --playback_rosbag`

However, I am **unable** to read the bag file with the code snippets given on tutorial :
http://www.open3d.org/docs/release/tutorial/sensor/realsense.html
```
import open3d as o3d
import cv2

bag_reader = o3d.t.io.RSBagReader()
bag_reader.open('dataset/realsense/realsense.bag')
im_rgbd = bag_reader.next_frame()

while not bag_reader.is_eof():
    im_rgbd = bag_reader.next_frame()
    color_np = im_rgbd.color.cpu().as_tensor().numpy()
    cv2.namedWindow('Realsense', cv2.WINDOW_AUTOSIZE)
    cv2.imshow('Realsense', color_np)
    key = cv2.waitKey(1)   
    
    # if 'esc' button pressed, escape loop and exit program
    if key == 27:
        cv2.destroyAllWindows()
        break
bag_reader.close()
```

```
run bag_playback.py --rgbd-video dataset/realsense/realsense.bag
[Open3D INFO] File dataset/realsense/realsense.bag opened
[Open3D DEBUG] frame_reader_thread_ start reading tail_fid_=0, head_fid_=0.
[Open3D DEBUG] frame_reader_thread EOF. Join.
[Open3D INFO] EOF reached
```
but it is able to play `L515_test .bag` dataset given.

Hope somebody can help me with this. Thank you.

**Environment:**
Open3d: V0.13
Operating system: Windows 10 64-bit
Python version: Python 3.8
Cuda: 10.1
GPU : Nvidia RTX 2070
Camera: Realsense D415
Visual studio 2019
Spyder

**Comment by maohong30** [comment]
Problem solved. 

When recording using `realsense_recorder.py --record_rosbag` , change the FPS from 30 to 15.

**Comment by modaresimr** [comment]
@maohong30 it doesn't solve the issue. open3d should also work with 30 FPS

**Comment by avivshalem** [comment]
Hi, have you figured this out?
Cant seem to get the bag reader to work with FPS that is 30 or 60,  it reaches EOF in a few milliseconds and ends the program:

`import open3d as o3d

bag_filename = ".\capture.bag" # This capture.bag file is 400mb, taken with D435, depth and RGB are 640X480, FPS is 30
bag_reader = o3d.t.io.RSBagReader()
bag_reader.open(bag_filename)
im_rgbd = bag_reader.next_frame()
i = 0
while not bag_reader.is_eof():
    # process im_rgbd.depth and im_rgbd.color
    i+=1
    im_rgbd = bag_reader.next_frame()

print(i) # Always print out 0, i.e. there are no frames seen
bag_reader.close()`
