### ISSUE TITLE
dense_slam.py error during execution

### ISSUE THREAD

**Issue by andapka** [isl-org/Open3D#4037]
**Describe the bug**
I'm running dense_slam.py from 
Open3D/examples/python/new_reconstruction_system/
and get the error:

Traceback (most recent call last):
  File "new_reconstruction_system/dense_slam.py", line 95, in <module>
    volume, poses = slam(depth_file_names, color_file_names, intrinsic, config)
  File "new_reconstruction_system/dense_slam.py", line 41, in slam
    model = o3d.t.slam.Model(config.voxel_size, config.sdf_trunc, 16,
AttributeError: module 'open3d.cpu.pybind.t' has no attribute 'slam'

**To Reproduce**

1. python3 new_reconstruction_system/dense_slam.py --config new_reconstruction_system/my_config.yml 
(if run with default_config.yaml the error is the same)
2. see the error

**Screenshots**
![image](https://user-images.githubusercontent.com/42839869/132839494-afecce16-eca3-475f-b8e3-b73b80658cf3.png)

**Environment (please complete the following information):**

- Operating system: Ubuntu 20.04
-  Python 3.8
- Open3D version: 0.13.0
- How did you install Open3D?: pip install open3d

**Comment by sanskar107** [comment]
@andapka This example has been added after the last open3d release. This example works fine for me with the current master wheel. You can try out the latest development wheels here http://www.open3d.org/docs/latest/getting_started.html#development-version-pip

**Comment by andapka** [comment]
@sanskar107 now it's working. Thanks!
