### ISSUE TITLE
Camera position

### ISSUE THREAD

**Issue by Camilochiang** [isl-org/Open3D#4038]
I know that this question has been already answered (#2338),my apologies for this.

Given a specific camera position  and angle , how should I fill the homogeneous transformation matrix  so a camera view is possible?

`rot_angle_xyz = [-0.000327, -0.008498, -0.003058] # In rad`
`pos_xyz = [0.072031, 0.111291, -0.175588] # from the origin`

I do understand that the each column of the matrix correspond to the right vector, up vector , forward vector and the last one to the position plus arrow with 0,0,01 but not sure how to fill it with my angles on the different vectors as i dont know what vector represent ...

Coud you give a hand @griegler ? Thanks in advance!

**Comment by Camilochiang** [comment]
I have tried with this but no success ...
```
 rx = np.mat([[1, 0, 0, 0],
        [0, math.cos(angle[0]), math.sin(angle[0]),0],
        [0, -math.sin(angle[0]), math.cos(angle[0]),0],
        [0, 0, 0, 1]])
 ry = np.mat([[math.cos(angle[1]), 0 , -math.sin(angle[1]), 0],
        [0, 1, 0, 0],
        [math.sin(angle[1]), 0, math.cos(angle[1]), 0],
        [0, 0, 0 ,-1]])
  rz = np.mat([[math.cos(angle[2]), -math.sin(angle[2]), 0, 0],
        [math.sin(angle[2]), math.cos(angle[2]), 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0 ,1]])
 cam.extrinsic = np.matmul(rx, ry, rz)

```

**Comment by theNded** [comment]
First of all the extrinsic does not include the positions, so it might be helpful to specify `cam.extrinsic[:3, 3:] = pos_xyz`.
The second thing is that the order of Euler angles matters, so you may want to try `np.matmul(rz, ry, rx)` and see how it works. 
And finally `extrinsic` is world to camera transformation, but your parameters might be camera to world, so an inversion might help.

Closed for now, but feel free to reopen once you have confirmed the right configuration and convention.
