### ISSUE TITLE
Tensor ICP behaviour with 0 correspondences does not align with legacy ICP

### ISSUE THREAD

**Issue by Andyjk1406** [isl-org/Open3D#4041]
**Is your feature request related to a problem? Please describe.**
Looking at the code, the GPU/Tensor ICP will log an error if 0 correspondences are found during any iteration. This will cause a programme to exit, but I don't think this is ideal, and does not match the legacy implementation

**Describe the solution you'd like**
If no correspondences are found in GetRegistrationResultAndCorrespondences(..), I think the function should return the constructed result (ie the identity transform, or the original passed-in transform, along with 0 correspondences in the Tensors

**Additional context**
Some cases of building models from multiple scans will invariably find bad pairs of clouds, with 0 correspondences, so causing the code to exit is undesirable.

**Comment by reyanshsolis** [comment]
Resolved in PR #4271.

Thanks!
