### ISSUE TITLE
Unnesessary std::unordered_set in ScalableTSDFVolume::Integrate()

### ISSUE THREAD

**Issue by mak-corp** [isl-org/Open3D#4042]
https://github.com/isl-org/Open3D/blob/d63c6d2faff395cb474b6379d0a5f5f8e573811b/cpp/open3d/pipelines/integration/ScalableTSDFVolume.cpp#L108

There is no need for the touched_volume_units_ set because OpenVolumeUnit() function already checks if Eigen::Vector3i(x, y, z) was already processed.

**Comment by theNded** [comment]
`touched_volume_units_` is a local variable. It records if `xyz` has been **processed** **in the current frame**. 
`volume_units_` in `OpenVolumeUnit` is a global variable. It records if `xyz` has been **allocated** **globally**. It could be processed multiple times across frames.
Therefore the combination is necessary.
