### ISSUE TITLE
RayCastingScene AddTriangles crashes on Windows

### ISSUE THREAD

**Issue by Andyjk1406** [isl-org/Open3D#4044]
**Describe the bug**
When trying to add a mesh to a raycastingscene, the program exits without revealing the error

**To Reproduce**
Complete example below - just create a sphere.ply mesh and save it in the exe folder

#include <Open3d/open3d.h>
#include <open3d/t/geometry/RaycastingScene.h>

int main(int argc, char* argv[])
{
	
	// Load a mesh
	open3d::geometry::TriangleMesh mesh;
	open3d::io::ReadTriangleMesh("Sphere.ply", mesh);

	// Convert to t mesh
	open3d::t::geometry::TriangleMesh t_mesh;
	t_mesh.FromLegacy(mesh);

	// Create scene and add mesh
	open3d::t::geometry::RaycastingScene scene;
	uint32_t mesh_id = scene.AddTriangles(t_mesh); // This line crashes the program
	std::cout << "Added to scene " << std::endl;

	// Cast a ray
	std::vector<float> xyzdir = { 0,0,0,-4.376193, -45.752384,87.615952 };
	open3d::core::Tensor rays(xyzdir,{ 6 }, open3d::core::Dtype::Float32);
	auto result = scene.CastRays(rays);

	std::cout << "Ray cast!" << std::endl;

	return 1;
}

**Expected behavior**
Ray should be cast

**Environment (please complete the following information):**
Windows 10, VS2019
Open3d master built with CUDA. I didn't explicitly build filament - is this needed? 
I have embree libs in the release folder

**Comment by benjaminum** [comment]
Hi @Andyjk1406 , filament is not required.

Does the python unit test for the RaycastingScene work for you? https://github.com/isl-org/Open3D/blob/master/python/test/t/geometry/test_raycasting_scene.py

**Comment by Andyjk1406** [comment]
Thanks. I'll check but I think I didn't build the python bindings (I just use c++)
I also wonder whether I need to build with simd? I haven't, but I think Embree requires it?

**Comment by benjaminum** [comment]
The default configuration in https://github.com/isl-org/Open3D/blob/master/3rdparty/embree/embree.cmake for windows enables AVX, which should be fine for your system.

**Comment by Andyjk1406** [comment]
I get the same result I'm afraid. With python it just hangs and closes. With C++ code as above, I get to the AddTriangles line, and it hangs and crashes.
Sorry - I'm not not very helpful as there is little information.

**Comment by Andyjk1406** [comment]
What might help is that I can build Embree separately. So if Open3d Cmake shipped with USE_SYSTEM_EMBREE I might be able to get it working?

**Comment by benjaminum** [comment]
Not sure what the problem is. How you describe it there is no output in the terminal, right?
I recommend to compile everything in debug mode and run the program inside a debugger.

**Comment by Andyjk1406** [comment]
Good idea

I built in debug. It seems to be a bad index in the std::unordered_map<>

Unhandled exception at 0x00007FF833A64ED9 in RayCast.exe: Microsoft C++ exception: std::out_of_range at memory location 0x00000071B4FFF130.

and the call stack was at:

RayCast.exe!std::unordered_map<std::string,open3d::core::Tensor,std::hash<std::string>,std::equal_to<std::string>,std::allocator<std::pair<std::string const ,open3d::core::Tensor>>>::at(const std::string & _Keyval) Line 403	C++


so I'm guessing the scene.AddTriangles(t_mesh) line is not converting the t_mesh into the correct scene data geometry. Or there is a bug in converting a legacy triangle mesh into a tensor mesh?

(I'm 100% confident of the PLY file)

**Comment by Andyjk1406** [comment]
Yes - it seems to be a problem converting a Trianglemesh to a tensor mesh. Hence the input to AddTriangles is bugged.
For example, my output is:

Loading...[Open3D DEBUG] Read geometry::TriangleMesh: 81920 triangles and 40962 vertices.
done
 Number of vertex elements in tensor mesh :  

....from the following code.....

std::cout << "Loading...";
	// Load a mesh
	open3d::geometry::TriangleMesh mesh;
	open3d::io::ReadTriangleMesh("C://myProjects//RayCast//Debug//Sphere.ply", mesh);

	std::cout << "done" << std::endl;

	// Convert to t mesh
	open3d::t::geometry::TriangleMesh t_mesh;
	t_mesh.FromLegacy(mesh);
	std::cout << " Number of vertex elements in tensor mesh : ";
	std::cout << t_mesh.GetVertexPositions().NumElements();
	std::cout << "T mesh";

So maybe there is an issue in t::TriangleMesh  ?

**Comment by Andyjk1406** [comment]
Thanks for the pointers. I have solved this now, but the key issue is that converting to a Tensor TriangleMesh using FromLegacy is incompatible with scene.AddTriangles(t_mesh).

The index tensor must be Dtype UInt32 for the scene call.
However, t::TriangleMesh::FromLegacy(mesh) can only allow Int64 or Int32   ie.... 

t_mesh.FromLegacy(mesh, open3d::core::Dtype::Float32, open3d::core::Dtype::Int32, open3d::core::Device("CPU:0"));
or
t_mesh.FromLegacy(mesh, open3d::core::Dtype::Float32, open3d::core::Dtype::Int64, open3d::core::Device("CPU:0"));

So the way to do it at the moment is:

// Load a mesh
	open3d::geometry::TriangleMesh mesh;
	open3d::io::ReadTriangleMesh("Sphere.ply", mesh);

	// Create the correct typed tensors ready for scene ray casting
	auto verts = open3d::core::eigen_converter::EigenVector3dVectorToTensor(mesh.vertices_, open3d::core::Dtype::Float32,
		open3d::core::Device("CPU:0"));
	std::cout << "Tensor vertices : " << verts.GetLength() << std::endl;

	auto ids = open3d::core::eigen_converter::EigenVector3iVectorToTensor(mesh.triangles_, open3d::core::Dtype::UInt32, 
		open3d::core::Device("CPU:0"));
	std::cout << "Tensor ids : " << ids.GetLength() << std::endl;

	// Create scene and add mesh
	open3d::t::geometry::RaycastingScene scene;
	uint32_t mid = scene.AddTriangles(verts, ids);


....but I think FromLegacy should allow the unsigned int 32 type, to provide the expected behaviour for this class. Not sure how we make that request visible?

On a second note, what is the correct way to build the ray tensor? As a test I do....

std::vector<float> xyzdir = { 0,0,0,-4.376193, -45.752384,87.615952 };
	open3d::core::Tensor rays(xyzdir,{ 1,6 }, open3d::core::Dtype::Float32);
	auto result = scene.CastRays(rays);

If I have millions of rays, is it best just to create a single long vector of sets of 6 (ox,oy,oz,dx,dy,dz) and use the above method, or is there a more optimal way?

Thanks

**Comment by Andyjk1406** [comment]
Wait - its a simpler error than that...

The lines
open3d::t::geometry::TriangleMesh t_mesh;
t_mesh.FromLegacy(mesh);

are wrong, they should be...
open3d::t::geometry::TriangleMesh t_mesh;
t_mesh = open3d::t::geometry::TriangleMesh::FromLegacy(mesh);

So all is fine.
