### ISSUE TITLE
Caught an unknown exception! When used scene.add_geometry to visualize a Pointcloud with 1 point.

### ISSUE THREAD

**Issue by yatengLG** [isl-org/Open3D#4053]
**Describe the bug**
When i used 'scenc.add_geometry' to add a pointcloud with 1 point. Interrupt the program and prompt "RuntimeError: Caught an unknown exception!"

**To Reproduce**

```python
import numpy as np
import open3d as o3d
import open3d.visualization.gui as gui
import open3d.visualization.rendering as rendering

app = gui.Application.instance
app.initialize()

pointcloud = o3d.geometry.PointCloud(o3d.utility.Vector3dVector(np.array([[1, 1, 1]])))
print(pointcloud)
window = app.create_window("3DViewer", 1280, 720)
scene_widget = gui.SceneWidget()
scene_widget.scene = rendering.Open3DScene(window.renderer)

material = o3d.visualization.rendering.Material()
scene_widget.scene.add_geometry('one point', pointcloud, material)

app.run()

```

**Expected behavior**
I need to filter Pointcloud and visualize filtered result. 

**Environment (please complete the following information):**

- Operating system: Ubuntu 18.04
- Python version: Python 3.8
- Open3D version: 0.13.0
- Is this remote workstation?: no
- How did you install Open3D?: pip
- Compiler version (if built from source): (e.g. gcc 7.5, clang 7.0)

**Comment by theNded** [comment]
It is not the correct way to use the pointcloud API. The correct way should be
```
pointcloud = o3d.geometry.PointCloud()
pointcloud.points = o3d.utility.Vector3dVector(np.array([[1, 1, 1]]))
```
