### ISSUE TITLE
ICP Registration Point to Plane Symmetric implementation

### ISSUE THREAD

**Issue by rcr1994** [isl-org/Open3D#4054]
At the moment, Open3D provides ICP  Point to Point and ICP Point to Plane, however "Point to Plane Symmetric" performs better for smooth surfaces. 

Is there already an implementation of ICP Point to Plane Symmetric in Open3D? If not, could we add this? 

This should not be very difficult to add, as the code for Point to Plane can be used with little modification.

**Comment by reyanshsolis** [comment]
Closing this PR. If interested, you may drop a PR for the feature, we will be happy to assist you. Thanks!

**Comment by hernot** [comment]
Sorry for reopening. 

Just came across the following publication regarding symmetric point to plane registration. It covers exactly what i have in mind for our noisy surface recordings which should be aligned as optimally as possible to be able to extract sensor positions with a precision of a millimetre or ideally less.

[Szymon Rusinkiewicz, "A symmetric objective function for ICP", ACM Transactions on Graphics, 2019, July, 38(4):1-7, DOI:10.1145/3306346.3323037](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjYmNv7tu_0AhVpQvEDHWvtCYQQFnoECAIQAQ&url=https%3A%2F%2Fgfx.cs.princeton.edu%2Fpubs%2FRusinkiewicz_2019_ASO%2Fsymm_icp.pdf&usg=AOvVaw0Kcmd0uIASleybEZqzo7QB) 

As speaking of today, we do not have any resources to contribute a pull request.
