### ISSUE TITLE
Multiway registration

### ISSUE THREAD

**Issue by tashfin-msu** [isl-org/Open3D#4059]
I am using multiway registration algorithm from open3d to create registered map. Multiway registration algorithm leveraged ICP, which provides the transformation matrix.
Let's say, 
I)  I have two point cloud A, B 
II) a registered point cloud X which is the output of multiway registration.
III) I also have the transformation matrix T.
The algorithm considers A as the reference. My question is if I multiply T with the second point cloud B, it should give me the registered point cloud X?
But I am not getting anything like that.
Any suggestions would be appreciated. Thanks

**Comment by theNded** [comment]
Multiway registration takes n point clouds, performs pose graph optimization, and outputs poses. What is X here? Is it an accumulation of multiple other point clouds, or A, or B? 
And what is transformation T? Is it the transformation from A to B, or the pose of A or B, or the pose of X?

**Comment by tashfin-msu** [comment]
I wanted to say that X is the output of the multiway registration between A and B.
Transformation matrix T which aligns the source geometry A to the target geometry B.

**Comment by theNded** [comment]
Then multiway registration is an overkill. Just use ICP or RANSAC instead. Transformation is from A to B, so A.transform(T) is aligned with B.

**Comment by tashfin-msu** [comment]
Mainly, I have 4 point clouds and I want to create a map from them. After that, I want to find out if the input pointcloud's points are present in the map. As they are already transformed, I just can not get them directly.

 I guess using ICP among them would be a good choice then I found out ICP needs a initial transformation matrix which I do not have.
Link: http://www.open3d.org/docs/release/tutorial/pipelines/icp_registration.html

**Comment by theNded** [comment]
In multiway registration, there is generally no so-called pairwise transformation. Then you should use the output pose graph's pose:
`pcds[i].transform(pose_graph.nodes[i].pose)`
to transform them in the same coordinate system. This is detailed [here](http://www.open3d.org/docs/latest/tutorial/Advanced/multiway_registration.html#Make-a-combined-point-cloud).
