### ISSUE TITLE
How to render a mesh whose texture background  is transparent

### ISSUE THREAD

**Issue by 1612190130** [isl-org/Open3D#4060]
I want to render a mesh whose texture background  is transparent, but when I render it by open3d, the background of texture turns black. Can someone help figure out it? 
My open3d code is below, and target mesh are   `label.obj` and `label.mtl` 
```python
vis = o3d.visualization.Visualizer()
vis.create_window(width=window_width, height=window_height)
mesh_ply = 'labe.obj'
mesh = o3d.io.read_triangle_mesh(mesh_ply, True) 
vis.add_geometry(mesh)
ctr = vis.get_view_control()
vis.poll_events()
vis.update_renderer()
vis.run()
```
The rendering result of the above code is
![1_save](https://user-images.githubusercontent.com/53040496/133871238-fbf8b4cb-ecf7-4e32-86ce-1f01c18a3b2b.png)
The texture with transparent background is shown below:
![cooltext393336158506898](https://user-images.githubusercontent.com/53040496/133871269-4b23c8f6-9d0c-4de0-8529-89d0dab196d4.png)
The rendering result of `label.obj`in the blender is below:
![blender_google_street](https://user-images.githubusercontent.com/53040496/133878135-f2a6fd65-9ca9-4abb-8817-27e51621af4d.png)

**Comment by errissa** [comment]
That can easily be accomplished in the new visualizer. Please see script below as an example. The example uses `open3d.visualization.draw` which is a convenient way to visualize data quickly. However, you can build more complex applications with the new visualizer. See the examples in `examples/python/gui`.
```
import open3d as o3d

plane = o3d.geometry.TriangleMesh.create_box(5,0.1,2, create_uv_map=True, map_texture_to_each_face=True)
plane.compute_triangle_normals()
mat = o3d.visualization.rendering.MaterialRecord()
mat.shader = "defaultLitTransparency"
mat.albedo_img = o3d.io.read_image("../test_scripts/google_street.png")

o3d.visualization.draw({'name': 'plane', 'geometry': plane, 'material': mat})
```
![2021-12-15-151103_1024x768_scrot](https://user-images.githubusercontent.com/3722407/146263529-c1f28e9e-4464-49d4-b165-0bc4deb909a7.png)

**Comment by Abo-go** [comment]
I use the `TriangleMesh.texture` to set multi-material for a mesh, and use the `open3d.visualization.VisualizerWithKeyCallback` to visualizing. Is there any transparency solution for me?
@errissa

**Comment by errissa** [comment]
Unfortunately not. We are no longer adding features to the legacy visualizer. Depending on what you're doing with the key callbacks you may be able to use the new `draw` with `actions`. The `examples/python/gui/draw.py` example shows a complex use of `actions`.

**Comment by Abo-go** [comment]
> 

Thanks, does the new visualizer support multi-materials binding to one TriangleMesh?

**Comment by errissa** [comment]
Not exactly. If you have a TriangleMesh made up of sub-parts each with their own material then you have two options:

1) separate the triangle mesh into multiple `TriangleMesh`es and create a material for each one.
2) use `TriangleMeshModel` which takes multiple meshes and multiple materials and allows you to associate the meshes with the materials. It's pretty simple to use.

**Comment by richardrl** [comment]
@errissa 

![image](https://user-images.githubusercontent.com/5181990/150617727-8355b3f9-7246-4ee9-9120-eb2455115baf.png)

This looks pretty good. However, how do I remove that weird turqoise background? the background setting should be white...

```
mesh = open3d.io.read_triangle_mesh(mesh_path)

mesh.scale(.75, center=np.zeros(3))


mesh.paint_uniform_color(np.array([64,224,208])/255)

mesh.compute_vertex_normals()


geoms_to_draw.append(mesh)
mat = open3d.visualization.rendering.MaterialRecord()
mat.base_color = np.array([1, 1, 1, .5])


# open3d.visualization.draw_geometries(geoms_to_draw)

open3d.visualization.draw({'name': 'test', 'geometry': mesh, 'material': mat})
```

**Comment by errissa** [comment]
add `show_skybox = False` to the `draw` call. We are considering changing the default to no skybox for 0.15 release.

**Comment by lelleMU** [comment]
> That can easily be accomplished in the new visualizer. Please see script below as an example. The example uses `open3d.visualization.draw` which is a convenient way to visualize data quickly. However, you can build more complex applications with the new visualizer. See the examples in `examples/python/gui`.
> 
> ```
> import open3d as o3d
> 
> plane = o3d.geometry.TriangleMesh.create_box(5,0.1,2, create_uv_map=True, map_texture_to_each_face=True)
> plane.compute_triangle_normals()
> mat = o3d.visualization.rendering.MaterialRecord()
> mat.shader = "defaultLitTransparency"
> mat.albedo_img = o3d.io.read_image("../test_scripts/google_street.png")
> 
> o3d.visualization.draw({'name': 'plane', 'geometry': plane, 'material': mat})
> ```
> 
> ![2021-12-15-151103_1024x768_scrot](https://user-images.githubusercontent.com/3722407/146263529-c1f28e9e-4464-49d4-b165-0bc4deb909a7.png)

However, that materia is not 'really' transparent. I mean if there is a another triangle with texture beneath the transparent background, that triangle can not be shown like nothing is in front of it. How can I fix this issue?

**Comment by lelleMU** [comment]
> > That can easily be accomplished in the new visualizer. Please see script below as an example. The example uses `open3d.visualization.draw` which is a convenient way to visualize data quickly. However, you can build more complex applications with the new visualizer. See the examples in `examples/python/gui`.
> > ```
> > import open3d as o3d
> > 
> > plane = o3d.geometry.TriangleMesh.create_box(5,0.1,2, create_uv_map=True, map_texture_to_each_face=True)
> > plane.compute_triangle_normals()
> > mat = o3d.visualization.rendering.MaterialRecord()
> > mat.shader = "defaultLitTransparency"
> > mat.albedo_img = o3d.io.read_image("../test_scripts/google_street.png")
> > 
> > o3d.visualization.draw({'name': 'plane', 'geometry': plane, 'material': mat})
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![2021-12-15-151103_1024x768_scrot](https://user-images.githubusercontent.com/3722407/146263529-c1f28e9e-4464-49d4-b165-0bc4deb909a7.png)
> 
> However, that materia is not 'really' transparent. I mean if there is a another triangle with texture beneath the transparent background, that triangle can not be shown like nothing is in front of it. How can I fix this issue?

Maybe I didn't make myself clear. When I have got a mesh with many triangles and some of some are transparent. However, when these triangles are overlapping with each other, the so call transparent triangles are not really transparent. I know it can be solved by  separating the triangle mesh into multiple TriangleMesh. However that adds too much numbers of meshes. I will try to use use TriangleMeshModel.
