### ISSUE TITLE
estimate_normals missing

### ISSUE THREAD

**Issue by SiegelDaniel** [isl-org/Open3D#4064]
**IMPORTANT: Please use the following template to report the bug.**

Before submitting:
_____

**Describe the bug**
Estimate_normals on a point cloud is no longer found

**To Reproduce**

Calling 
`pcd.normals = o3d.estimate_normals(pcd,search_param=03d.geometry.KDTreeSearchParamHybrid(radius=0.1,max_nn=30))`

yields 

`AttributeError: module opend3.open3d_pybind.geometry has no attribute estimate_normals`

I have searched the sourcecode and could not find any hint to estimate_normals in the current version. In 0.8.0.0 it still exists. What happened to it? Are there any alternatives?

**Expected behavior**
The call should go through

**Environment (please complete the following information):**

- Operating system: Ubuntu 20.04
- Python version: Python 3.8
- Open3D version: Tried it with 0.10.0.0, 0.12.0 and 0.13.0
- Is this remote workstation?: no
- How did you install Open3D?: pip

**Additional context**

**Comment by xkaraman** [comment]
I think you need to try calling `YourPCD.estimate_normals()` instead of `o3d.estimate_normals()`

**Comment by SiegelDaniel** [comment]
@xkaraman That did work partially, it is yielding another error now:

![grafik](https://user-images.githubusercontent.com/14983741/133992422-fb6bf361-433e-4cd7-9fc3-f0b43b5ffbde.png)

The corresponding code to this is:

![grafik](https://user-images.githubusercontent.com/14983741/133992457-9df9bdd7-c72a-4933-82f2-e9894b8d1b3e.png)

Am I missing something essential here?

**Comment by xkaraman** [comment]
Yes, the error complains about the function arguments of `estimate_normal()`. As you can see it needs only 2 arguments `search_param` and `fast_normal_computation`. (You omit the first self argument). So try, estimate_normals without `pcd.points` as an argument.

Moreover, i don't think you need to save as `pcd.normals = ` as the function does not return anything [Pointcloud API ](http://www.open3d.org/docs/release/cpp_api/classopen3d_1_1geometry_1_1_point_cloud.html#a0eb1b6e14c8beb0073bded699b3c81a7). It will be automatically saved in `pcd` and then you can access normals with `pcd.normals`. I am not 100% sure about this. Maybe you can confirm it!

**Comment by SiegelDaniel** [comment]
I can confirm that this worked! Thank you very much, I really appreciate your help!
