### ISSUE TITLE
GPU nn Speed

### ISSUE THREAD

**Issue by Andyjk1406** [isl-org/Open3D#4075]
**Describe the bug**
Not sure if this is expected behaviour, but CUDA nearest neighbour search is much slower than CPU

**To Reproduce**
Here is some code. The two point clouds are about 1 million points each:

#include <iostream>
#include <memory>
#include <thread>

// Open3D
#include <Open3d/open3d.h>

#include "Eigen/Dense"
#include <fstream>      // std::ifstream
using namespace open3d::t::geometry;

using namespace open3d;

core::Device device_;
core::Device host_;
core::Dtype dtype_; // Only 32 bit supported on GPU for now with Open3d

int main(int argc, char *argv[])
{
	using namespace open3d;

	device_ = core::Device("CPU:0");
	host_ = core::Device("CPU:0");
	dtype_ = core::Dtype::Float32; // Only 32 bit supported on GPU for now with Open3d
	

	std::string src_file,tgt_file;
	src_file = open3d::utility::GetProgramOptionAsString(argc, argv, "--src").c_str();
	tgt_file = open3d::utility::GetProgramOptionAsString(argc, argv, "--tgt").c_str();

	if (src_file == "" || tgt_file=="")
	{
		std::cout << "Need filenames for the source and target eg '--src C://Scans//myscan//myscan.ply --tgt c://.//xxx.ply'";
		return -1;
	}

	open3d::utility::SetVerbosityLevel(open3d::utility::VerbosityLevel::Debug);
   
	// Load pointclouds into CPU
	open3d::geometry::PointCloud src_legacy;
	open3d::geometry::PointCloud tgt_legacy;
	open3d::io::ReadPointCloud(src_file, src_legacy);
	open3d::io::ReadPointCloud(tgt_file, tgt_legacy);

	// Perform nn search on CPU
	auto start_cpu = std::chrono::high_resolution_clock::now();

	open3d::geometry::KDTreeFlann kdtree;
	kdtree.SetGeometry(tgt_legacy);
	std::vector<int> idxs(src_legacy.points_.size());

#pragma omp parallel 
	{

#pragma omp for schedule(static) nowait
		for (int src_i = 0; src_i < src_legacy.points_.size(); ++src_i)
		{

			std::vector<int> indices(1);
			std::vector<double> dists(1);
			if (kdtree.SearchKNN(src_legacy.points_[src_i], 1, indices, dists) > 0)
			{
				// Nearest point found, store index
				idxs[src_i] = indices[0];
			}

		}
	}

	auto elapsed_cpu = std::chrono::high_resolution_clock::now() - start_cpu;
	auto microseconds_cpu = std::chrono::duration_cast<std::chrono::microseconds>(elapsed_cpu).count();
	std::cout << "Time for nn cpu " << microseconds_cpu  << std::endl;
	
	// GPU nn search
	//auto start_gpu = std::chrono::high_resolution_clock::now();

	t::geometry::PointCloud src_gpu;
	t::geometry::PointCloud tgt_gpu;
	src_gpu = t::geometry::PointCloud::FromLegacy(src_legacy, dtype_, device_);
	tgt_gpu = t::geometry::PointCloud::FromLegacy(tgt_legacy, dtype_, device_);
	
	auto start_gpu = std::chrono::high_resolution_clock::now();
        // The nn search structure
        core::nns::NearestNeighborSearch target_nns(
            tgt_gpu.GetPointPositions());
       
        bool check = target_nns.KnnIndex();
        if (!check) {
            utility::LogError(
                "NearestNeighborSearch::KnnSearch: Index is not "
                "set.");
        }
		
		// NNS Search: Getting Correspondences, Inlier Fitness and RMSE.
		core::Tensor indices, distances;
		std::tie(indices, distances) =
			target_nns.KnnSearch(
				src_gpu.GetPointPositions(), 1);

		idxs = indices.ToFlatVector<int>();
		//auto shape = indices.GetShape();
		//auto am = indices.ArgMax({ 0 });
		
		auto elapsed_gpu = std::chrono::high_resolution_clock::now() - start_gpu;
		auto microseconds_gpu = std::chrono::duration_cast<std::chrono::microseconds>(elapsed_gpu).count();
		std::cout << " Time for nn gpu : " << microseconds_gpu  << std::endl;	

	return 1;
}

1. cd '...'
2. python '....'
3. See error

**Expected behavior**
I thought with 1 million points that GPU would be faster? If this is not expected, is there any indication at what point GPU nn search would be worthwhile (eg 20 million points? More?)

Outputs:
a) Using device = CUDA:0
C:\myProjects\GPU_nn\Release>GPU_nn.exe --src Model_cloud_0_c.ply --tgt Model_cloud_1_c.ply
[Open3D DEBUG] Format auto File Model_cloud_0_c.ply
[Open3D DEBUG] Read geometry::PointCloud: 923287 vertices.
[Open3D DEBUG] Format auto File Model_cloud_1_c.ply
[Open3D DEBUG] Read geometry::PointCloud: 899913 vertices.
Time for nn cpu 1809253
 Time for nn gpu : 3380591

b) Using device = CPU:0
C:\myProjects\GPU_nn\Release>GPU_nn.exe --src Model_cloud_0_c.ply --tgt Model_cloud_1_c.ply
[Open3D DEBUG] Format auto File Model_cloud_0_c.ply
[Open3D DEBUG] Read geometry::PointCloud: 923287 vertices.
[Open3D DEBUG] Format auto File Model_cloud_1_c.ply
[Open3D DEBUG] Read geometry::PointCloud: 899913 vertices.
Time for nn cpu 1734202
 Time for nn gpu : 1187624

So it seems CPU tensor nn search is faster than legacy CPU.
GPU nn search is half the speed.

**Environment (please complete the following information):**

- Operating system: Windows 10 64-bit NVidia RTX2080 Super and i7 10875H
- Open3D version: master
- Is this remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version VS2019

**Comment by Andyjk1406** [comment]
It seems there was another discussion related to radius search on the GPU, and how if many points fall into a radius bin, the GPU will perform less well. I suspect pure KNN with no maximum search radius is the worst case of all - hence the poor result above.

Maybe warn users in the documentation about this ?

**Comment by reyanshsolis** [comment]
Hi, 
Yes, it is a known issue, and we are working on improving the same. 
Currently, KNN CUDA is slower than KNN CPU for general cases in lower dimensions, and faster in higher dimensions (here dimension for a point cloud is 3). 

Hybrid-Search CUDA is generally a lot faster than Hybrid-Search CPU, but one needs to choose the `search radius` parameter efficiently. Too large a radius parameter will lead to poor performance on CUDA, for the reason mentioned by @Andyjk1406.

Thanks for using Open3D, we are continuously working on the performance improvements and we hope to resolve this issue in a few months time.

Thanks, 
Rishabh
