### ISSUE TITLE
simplify_quadric_decimation leaves holes in the output mesh

### ISSUE THREAD

**Issue by brucedjones** [isl-org/Open3D#4083]
**IMPORTANT: Please use the following template to report the bug.**

Before submitting:

1. Search for [similar issues](https://github.com/isl-org/Open3D/issues).
2. For Python issues, please test with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip). It may be already fixed!
_____

**Describe the bug**
I have a large mesh that I am trying to decimate, simply using `simplify_quadric_decimation` leaves the mesh full of holes.

**To Reproduce**

```python
import open3d as o3d

stl = 'cube_thing'
mesh_in = o3d.io.read_triangle_mesh(f"./{stl}.stl")

mesh_smp = mesh_in.simplify_quadric_decimation(target_number_of_triangles=10, maximum_error=1e-14, boundary_weight=3.0)
mesh_smp.compute_triangle_normals()
mesh_smp.compute_vertex_normals()
print(
    f'Simplified mesh has {len(mesh_smp.vertices)} vertices and {len(mesh_smp.triangles)} triangles'
)

o3d.io.write_triangle_mesh(f"./{stl}_simple.stl", mesh_smp)
```

**Expected behavior**
The output mesh remains manifold if the input mesh is manifold

**Screenshots**

![Screen Shot 2021-09-23 at 8 19 37 AM](https://user-images.githubusercontent.com/1107675/134505477-fb365afb-9340-4423-af6d-b992db9e2aec.png)
![Screen Shot 2021-09-23 at 8 19 28 AM](https://user-images.githubusercontent.com/1107675/134505478-4dbf9729-1c69-4fa8-9cd5-a48db0d52a5b.png)

**Environment (please complete the following information):**

- Operating system: OSX 11.5.2
- Python version: Python 3.7.9
- Open3D version: 0.13.0
- Is this remote workstation?: no?
- How did you install Open3D?: pip
- Compiler version (if built from source): NA

**Additional context**
STLs here:
[cube_thing.zip](https://github.com/isl-org/Open3D/files/7217467/cube_thing.zip)

**Comment by benjaminum** [comment]
We added a different algorithm in #5199
