### ISSUE TITLE
Build failed using ARM CPU on NVIDIA Jetson TX2

### ISSUE THREAD

**Issue by peterzxli** [isl-org/Open3D#4085]
Hi, I am unable to build the latest release on the NVIDIA Jetson TX2 platform. Here is the build command that I used:
```
cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=ON \
    -DBUILD_TENSORFLOW_OPS=OFF \
    -DBUILD_PYTORCH_OPS=OFF \
    -DBUILD_UNIT_TESTS=ON \
    -DBUILD_CUDA_MODULE=ON \
    -DBUILD_GUI=ON \
    -DCMAKE_INSTALL_PREFIX=~/open3d_install \
    -DPYTHON_EXECUTABLE=$(which python3) \
    -DBUILD_EIGEN3=ON -DBUILD_GLEW=ON -DBUILD_GLFW=ON -DBUILD_JSONCPP=ON -DBUILD_PNG=ON \
    -DGLIBCXX_USE_CXX11_ABI=ON \
    ..
```

I encountered the following error:
```[ 81%] Building CXX object cpp/pybind/CMakeFiles/pybind.dir/visualization/visualizer.cpp.o
[ 81%] Building CXX object cpp/pybind/CMakeFiles/pybind.dir/visualization/o3dvisualizer.cpp.o
[ 81%] Building CXX object cpp/pybind/CMakeFiles/pybind.dir/visualization/gui/events.cpp.o
/usr/lib/gcc/aarch64-linux-gnu/8/include/arm_neon.h(38): error: identifier "__Int8x8_t" is undefined
/usr/lib/gcc/aarch64-linux-gnu/8/include/arm_neon.h(39): error: identifier "__Int16x4_t" is undefined
/usr/lib/gcc/aarch64-linux-gnu/8/include/arm_neon.h(40): error: identifier "__Int32x2_t" is undefined
/usr/lib/gcc/aarch64-linux-gnu/8/include/arm_neon.h(41): error: identifier "__Int64x1_t" is undefined
/usr/lib/gcc/aarch64-linux-gnu/8/include/arm_neon.h(42): error: identifier "__Float16x4_t" is undefined
/usr/lib/gcc/aarch64-linux-gnu/8/include/arm_neon.h(43): error: identifier "__Float32x2_t" is undefined
/usr/lib/gcc/aarch64-linux-gnu/8/include/arm_neon.h(44): error: identifier "__Poly8x8_t" is undefined
/usr/lib/gcc/aarch64-linux-gnu/8/include/arm_neon.h(45): error: identifier "__Poly16x4_t" is undefined
```

- Operating system: Ubuntu 18.04
- Python version: 3.6
- Open3D version: 0.13.0
- Compiler version (if built from source): gcc 8.4

Please let me know how I can resolve this issue. Thanks!

**Comment by mebasoglu** [comment]
Hello, I faced the same issue when I tried clonning the repo with the latest commit on Jetson Nano. I think a commit after v0.13.0 tag caused this issue. You can use v0.13.0 branch, that worked for me.

**Comment by peterzxli** [comment]
Thanks! I can confirm that 39c5e9d06750fffeeaf5de7cc22881c0eb5d1143 works very well on the TX2.

**Comment by guyuezuntinggithub** [comment]
> Hello, I faced the same issue when I tried clonning the repo with the latest commit on Jetson Nano. I think a commit after v0.13.0 tag caused this issue. You can use v0.13.0 branch, that worked for me.

I face the same issue. But I don't know which branch works? I tried "git clone --recursive https://github.com/isl-org/Open3D" and "git clone --recursive https://github.com/intel-isl/Open3D". They all have the same issue.

**Comment by mebasoglu** [comment]
Hello, you can check out with `git checkout  v0.13.0` after you clone the repo as described in the documentation.
