### ISSUE TITLE
Can I set additional feature on o3d.geometry.PointCloud?

### ISSUE THREAD

**Issue by demul** [isl-org/Open3D#4088]
Can I set additional feature on o3d.geometry.PointCloud?
o3d.geometry.PointCloud only have features below.

pcd.points : xyz coordinate
pcd.colors : rgb value
pcd.normals : normal

but i want to set additional features like neural network latent vectors pointwisely.
is there any plan to add such utility?

**Comment by hduonggithub** [comment]
You can try open3d.**t**.geometry.PointCloud

http://www.open3d.org/docs/latest/python_api/open3d.t.geometry.PointCloud.html#open3d.t.geometry.PointCloud

**Comment by demul** [comment]
> You can try open3d.**t**.geometry.PointCloud
> 
> http://www.open3d.org/docs/latest/python_api/open3d.t.geometry.PointCloud.html#open3d.t.geometry.PointCloud

Thanks! I haven't use this sub package "open3d.t" before.
If it's not too bothersome, can you briefly explain what the package is about?

**Comment by xkaraman** [comment]
I think this a new Tensor-Based package. I don't know exactly when they introduced it but it seems all work to be moving in that area like pipelines and such.

**Comment by hduonggithub** [comment]
All info and example can be found from the link. That 's it. Make your pointcloud as tensor based pointcloud.  Everything else could be almost the same.

**Comment by demul** [comment]
@hduonggithub @xkaraman 
Thanks.
Maybe 't' refer to 'tensor' :)
