### ISSUE TITLE
Add all materials to open3d.visualization.rendering

### ISSUE THREAD

**Issue by hahwang** [isl-org/Open3D#4090]
I try to use the python function `open3d.visualization.rendering.render_to_image()` to project 3D mesh with multiple materials and textures  into 2D image.
I find that the function `open3d.visualization.rendering.scene.add_geometry()` only can add a model and a material.
How can I add all materials to the rendering? 
(test on Open3D 0.13.0)

**Comment by errissa** [comment]
You can call `add_geometry` as many times as you need to add all of the objects (and their materials) that you want to visualize. The example `examples/python/gui/render-to-image.py` shows how to add multiple objects to a scene then render it to an image. `examples/python/gui/demo_scene.py` is another example of a complex setup. Also shown in the `demo_scene.py` example is the use of `read_triangle_model` which can be used to load complex objects with multiple materials.

If you have further questions after reviewing the examples please feel free to reopen this issue and post your sample code.
