### ISSUE TITLE
tensor clouds not releasing GPU device memory

### ISSUE THREAD

**Issue by Andyjk1406** [isl-org/Open3D#4094]
**Describe the bug**
t::Pointcloud never releases the device RAM on the GPU

I have tried defining the cloud in a local scope, I've tried calling cloud.Clear() and I've tried copy it it back to host.
In all cases, the GPU RAM remains allocated (monitoring using Task Manager->Performance on Windows)

So after few calls to a function which locally creates a GPU tensor cloud, then returns, I get a CUDA mem alloc error

**To Reproduce**
Create and fill a tensor GPU (device) pointcloud in a function. Return (without the cloud).

After multiple calls, your GPU RAM will fill, and you get the CUDA mem alloc error

**Expected behavior**
Once a tensor pointcloud goes out of scope, I would expect the GPU RAM to be cleared.
If not, there should be an explicit method to clear the RAM. 
Note - Pointcloud::Clear() does not clear the GPU RAM.
Note - PointCloud::To(host) does not clear the GPU RAM

**Environment (please complete the following information):**

- Operating system: ( Windows 10 64-bit)
- Open3D version: 013 master
- How did you install Open3D?: (build from source)
- Compiler version (if built from source): VS2019

**Comment by Andyjk1406** [comment]
Hi again.
Actually this looks to be OK after all. I guess open3d allocates gpu ram in chunks, and once allocated, this never deallocates (according to task manager on Windows), but internally open3d will reuse it.

It's probably also the reason I always get a Cuda runtime error when exiting an open3d program which uses cuda - I think open3d never gives memory back to the operating system? (However, the Gpu ram gets cleaned up after the cuda runtime error message, so it's not pretty, but it works)

**Comment by yxlao** [comment]
> Can I somehow explicitly clear Open3d GPU (CUDA) RAM if I know I have no pointclouds?

`open3d::cuda::ReleaseCache()`, or `open3d.cuda.release_cache()` in Python.

> Can I somehow get the CUDA context that Open3d created, and then initialise my own RAM and pass it to Open3d when creating pointclouds (and clear it myself later)?

Yes, it is possible. But we'll need to use some lower-level APIs. The idea is to create a Tensor (e.g. `nx3` for point cloud) with custom memory, and use that Tensor in the point cloud (no memory copy when creating a point cloud from tensor).

1. Create a `core::Blob` with your pre-allocated memory. You'll need to use:
    ```cpp
    Blob(const Device& device,
         void* data_ptr,
         const std::function<void(void*)>& deleter)
    ```
2. Create a `core::Tensor` with that blob. Use this constructor:
    ```cpp
    Tensor(const SizeVector& shape,
           const SizeVector& strides,
           void* data_ptr,
           Dtype dtype,
           const std::shared_ptr<Blob>& blob)
    ```
3. Create the `t::geometry::PointCloud` with the tensor:
    ```cpp
    PointCloud(const core::Tensor &points);
    ```

**Comment by YvanYin** [comment]
I face the issue "cuda out of memory". 

This is my code:
`
def downsample_and_filter_cuda(points : np.array, colors : np.array, normals: np.array, voxel_size = 0.02):
    print('downsample pcd cuda.')
    cuda_device = "CUDA:3" #f"CUDA:{torch.cuda.current_device()}"
    device = o3d.core.Device(cuda_device)
    dtype = o3d.core.float32
    # create point cloud tenor
    color_normal = colors / 255.0
    pcd = o3d.t.geometry.PointCloud(device)
    pcd.point.positions = o3d.core.Tensor(points, dtype, device)
    pcd.point.normals = o3d.core.Tensor(normals, dtype, device)
    pcd.point.colors = o3d.core.Tensor(color_normal, dtype, device)
    # downsample point cloud
    print('pre downsample', pcd.point.positions.shape)
    voxel_down_pcd = pcd.voxel_down_sample(voxel_size=voxel_size)
    print('after downsample', voxel_down_pcd.point.positions.shape)
    # filter point cloud 
    pcd_filter, _ = voxel_down_pcd.remove_radius_outliers(nb_points=10, search_radius =0.1)
    # pcd_filter = voxel_down_pcd
    print('after filter',pcd_filter.point.positions.shape)
    print('pre filter points num:', pcd.point.positions.shape[0], 'after filter points num:', pcd_filter.point.positions.shape[0])
    # get points/normals/colors output
    points_down = pcd_filter.point.positions.cpu().numpy()
    colors_down = (pcd_filter.point.colors.cpu().numpy()  * 255.0).astype(np.uint8)
    normals_down = pcd_filter.point.normals.cpu().numpy()
    # o3d.t.io.write_point_cloud(f'img4_down_{voxel_size}.ply', pcd_filter)
    del pcd
    del voxel_down_pcd
    del pcd_filter
    return points_down, colors_down, normals_down
`

After I call the downsample_and_filter_cuda, I find that the cuda memory is still in use. How could I clear the cuda cache?
