### ISSUE TITLE
Rotation matrix of oriented bounding box

### ISSUE THREAD

**Issue by hadasbd** [isl-org/Open3D#4106]
I wish to make sense (and use) of the R matrix, given as an output for the get_oriented_boundiing_box function.
I can't find any proper documentation or example about it.
Is it euler based? can anyone write down the components of the matrix straight forward as trigo formulas with the yaw, pitch, roll angles?
Thanks (:

**Comment by theNded** [comment]
R is simply a 3x3 rotation matrix in SO(3). You can interpret it as a combination of Euler rotations with closed-form [formulations](https://en.wikipedia.org/wiki/Euler_angles) upon your convention.
