### ISSUE TITLE
Remove warnings in generated cmake Config file

### ISSUE THREAD

**Issue by ahoarau** [isl-org/Open3D#4112]
in `Open3DConfig.cmake`, those lines 
```cmake
if(POLICY CMP0072)
    cmake_policy(SET CMP0072 OLD)
endif()
```

generate a big harmless warning:
```
[cmake] CMake Deprecation Warning at ../CMake/Open3DConfig.cmake:18 (cmake_policy):
[cmake]   The OLD behavior for policy CMP0072 will be removed from a future version
[cmake]   of CMake.
[cmake] 
[cmake]   The cmake-policies(7) manual explains that the OLD behaviors of all
[cmake]   policies are deprecated and that a policy should be set to OLD only under
[cmake]   specific short-term circumstances.  Projects should be ported to the NEW
[cmake]   behavior and not rely on setting a policy to OLD.
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:235 (find_package)
[cmake] 
```

ref: https://cmake.org/cmake/help/latest/policy/CMP0072.html

Starting at cmake 3.11, the policy is `new` by default, so it is safe to remove it.

Can we add something like:

```cmake
# Default policy is NEW in cmake >= 3.11 
# https://cmake.org/cmake/help/latest/policy/CMP0072.html
if(${CMAKE_VERSION} VERSION_LESS "3.11.0") 
  if(POLICY CMP0072)
      cmake_policy(SET CMP0072 OLD)
  endif()
endif()
```

**Comment by reyanshsolis** [comment]
The behaviour was changed in PR https://github.com/isl-org/Open3D/pull/1782, and later refactorings.

Closing this issue, as outdated. Feel free to re-open if required in future. 
Thanks

**Comment by willat343** [comment]
I'm confused by your comment @reyanshsolis. I get the same issue as @ahoarau using Open3D 0.13 (released Jun 2021) whereas the pull request you reference is dated Jun 2020, so would presumably be in versions 0.11 onward.

Can we reopen this issue, or can you explain why the warning is necessary? From the docs @ahoarau linked, it looks like `OpenGL_GL_PREFERENCE` could be set directly instead of using the `OLD` policy, and we would avoid this warning.

**Comment by EwingKang** [comment]
I have a local Open3D build from source. My application include a local install directly with `find_package()` call in my application's cmake.
I'm still having this problem of massive CMP0072 warnings with v0.19 released in Jan 2025. I'll try to see what is happening.
