### ISSUE TITLE
Numpy representation generated by the indexer is misinterpreted by o3d Image

### ISSUE THREAD

**Issue by cansik** [isl-org/Open3D#4120]
After using the array indexing in numpy to crop an image to a region of interest, it is not possible to correctly load the image as `open3d.cpu.pybind.geometry.Image`. The image seems misinterpreted.

**To Reproduce**
Run the following python code with the example image provided.

```python
import cv2
import numpy as np
import open3d as o3d
from open3d.cpu.pybind.geometry import Image

image = cv2.imread("plant.jpg")
roi = image[100:300, 100:300]
cv2.imshow("", roi)
texture: Image = o3d.geometry.Image(roi)
o3d.io.write_image("plant_text.png", texture)
```

<img width="250" src="https://user-images.githubusercontent.com/5220162/135685696-dbd7ff93-637c-4594-a84f-c395de90df95.jpg">

*Input Image (scaled)*

**Expected behaviour**
The cropped version looks like a part of the original image (see first screenshot).

**Screenshots**
Window of the `cv2.imshow` command:
<img width="151" alt="KId8jMnBUT" src="https://user-images.githubusercontent.com/5220162/135685979-9e529dac-b82b-44f9-8ffc-09d49ece3754.png">

This is the output after converting it to an `open3d.cpu.pybind.geometry.Image`:
![plant_text](https://user-images.githubusercontent.com/5220162/135685646-36fc7288-a58b-40a6-a9a7-51cf349f5671.png)
*plant_text.png*

**Environment**

- Operating system: tested on OSX 10.15, Windows 10 64-bit)
- Python version: Python 3.8
- Open3D version: 0.13.0
- Is this remote workstation?: no
- How did you install Open3D?: pip

**Additional context**
Saving the numpy mat to a file and importing it with open3d.io works.
And it seems that only the second part in the indexing makes problems. This works fine:

```python
roi = image[100:300, 0:]
```

As well this works, so it seems like a memory problem?

```python
roi = np.array(image[100:300, 100:300], copy=True)
```

**Comment by reyanshsolis** [comment]
Hi @yxlao don't we always copy memory blob while doing numpy -> open3d data conversions?

**Comment by theNded** [comment]
There was no explicit converter from numpy for the legacy image container, so misinterpretation is expected. 
In the new API, you may construct a tensor-based image by
`im = o3d.t.geometry.Image(o3d.core.Tensor(roi))`. You can convert it to legacy by `im.to_legacy()`.
