### ISSUE TITLE
Definition for remove_statistical_outlier 

### ISSUE THREAD

**Issue by FarahSaeed** [isl-org/Open3D#4126]
I was trying to find the definition for remove_statistical_outlier  in python. Is it available in python.

Thanks!
Farah

**Comment by reyanshsolis** [comment]
http://www.open3d.org/docs/release/python_api/open3d.geometry.PointCloud.html#open3d.geometry.PointCloud.remove_statistical_outlier

Thanks,
Rishabh

**Comment by FarahSaeed** [comment]
Thanks! I was also wondering if there is a way I could access the code behind this function.

Thank you!

**Comment by reyanshsolis** [comment]
sure, for our `legacy` version (or eigen-based version) its https://github.com/isl-org/Open3D/blob/2961f911dbfe6d203d510e16dfdcfe1292d7fd61/cpp/open3d/geometry/PointCloud.cpp#L528.

We have not added this functionality in the `tensor` version (with CPU, GPU support), but a draft PR on `RemoveRadiusOutlier` is there, you may refer: https://github.com/isl-org/Open3D/pull/3422.

**Comment by FarahSaeed** [comment]
Thank you!
