### ISSUE TITLE
eigen third party archive link is broken

### ISSUE THREAD

**Issue by ovidiu-cristea** [isl-org/Open3D#4127]
I am trying to build Open3D from source, and I got a md5 mismatch related to the eigen package archive.
Looking more closely, the package was not downloaded at all from the specified location.

3rdparty/Eigen/eigen.cmake has the following URL on line 6:
https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.bz2

That URL seems to be broken (does not download eigen-3.4.0.tar.bz2, instead redirects to https://gitlab.com/libeigen/eigen )

**Comment by theNded** [comment]
Seems an upstream bug, we will monitor how it evolves
https://gitlab.com/libeigen/eigen/-/issues/2336

**Comment by ovidiu-cristea** [comment]
looks like the link is back online and everything is good again.
