### ISSUE TITLE
Error for "engine: tensor" in "new_reconstruction_system"

### ISSUE THREAD

**Issue by andapka** [isl-org/Open3D#4129]
**Describe the bug**
I set engine == tensor in config.yaml file and run dense_slam.py
I got the "RuntimeError: [Open3D Error]"

RuntimeError: [Open3D Error] (void open3d::t::pipelines::kernel::DecodeAndSolve6x6(const open3d::core::Tensor&, open3d::core::Tensor&, float&, int&)) /root/Open3D/cpp/open3d/t/pipelines/kernel/TransformationConverter.cpp:155: Singular 6x6 linear system detected, tracking failed.

**To Reproduce**
- set engine as tensor
- run dense_slam.py
- See error

**Expected behavior**
The process is running without any errors

**Screenshots**
<img width="772" alt="new_reconstruction_system_error_tensor" src="https://user-images.githubusercontent.com/42839869/135838998-3b9863eb-51ae-492d-a305-ddce07997081.png">

**Environment (please complete the following information):**
Operating system: Ubuntu 20.04
Python 3.8
Open3D version: development version
How did you install Open3D?: pip install --pre https://storage.googleapis.com/open3d-releases-master/python-wheels/open3d-0.13.0+9efe03a-cp38-cp38-manylinux_2_27_x86_64.whl

**Additional context**
I got also the warning (look at screenshot) "[Open3D WARNING] Property not found for color, return an empty tensor!"
Maybe the main error connects with this one.
 What should I pay attention to?

**Comment by theNded** [comment]
The warning is not critical, it is mainly for the default ray casting.
There are many reasons for tracking failure. Did you specify the correct intrinsic matrix or depth scale?

**Comment by andapka** [comment]
@theNded 

I can check when set engine to "legacy"
intrinsic.shape = (3, 3)
intrinsic = [[3.97051699e+03 0.00000000e+00 1.66432301e+03]
 [0.00000000e+00 3.95871613e+03 1.61584663e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
It seems that matrix is correct.
How can I check when intrinsic.matrix is a Tensor?

depth_scale == 1000.0 by default.
Should I play with depth_scale?

Is it necessary to run on GPU when engine==tensor?

**Comment by theNded** [comment]
The tensor version is printable, just `print(intrinsic)`.
I don't know which sensor you are using, so `depth_scale` could be the most critical part here.
GPU is not necessary, CPU also works but much slower.

**Comment by andapka** [comment]
I'm using Ipad Pro
3024x4032
depth = 384x576
I received bad result with reconstruction_system, so I decide to try new one.

**Comment by theNded** [comment]
Then the intrinsic is wrong. It is for RGB image but I would say not for the depth.
Currently we don't support RGB/depth with different resolutions, see
https://github.com/isl-org/Open3D/issues/4104
We will try to add this feature. Before that, you can disable the color input, figure out the correct depth intrinsics and depth scale, and try again.

**Comment by andapka** [comment]
I know that RGB and Depth should have one resolution.
That why when I preprocess images I upscale depth images to RGB.
Any way, afterwards, I create RGBD images and apply o3d.pipelines.integration.ScalableTSDFVolume. I can do it due to transformation data from Apple devices. I get pretty good result but not for all cases. That why I'm trying to find better solution.
If I have mistakes in my pipeline I'll appreciate for your advices.

**Comment by andapka** [comment]
If I use only depth images, what should be the pipeline?

**Comment by theNded** [comment]
Ok, sorry for the confusion -- it looks like intrinsics and scales are fine, as the reconstruction with `o3d.pipelines.integration.ScalableTSDFVolume` actually works.

The offline system is the best we have now in terms of accuracy, if it does not work then there is not much space for improvement. However, it would be good to find the actual depth intrinsics, since color and depth intrinsics are not necessarily the same even at the same resolution. Once you find it, rather than upsampling the depth, it might be better to downsample the color. Also, an alignment of depth and color could be important to ensure data association.

As of now, RGB images are not used for tracking, only for rendering, so any dummy color image with the same resolution of depth should work (e.g., a white image) -- I have supported that in the integration pipeline (not the SLAM pipeline) that will appear in a new PR. I should have constructed an interface for that, but unfortunately, I'm running out of time developing new features.

**Comment by andapka** [comment]
Thanks a lot!
So, as far as I have intrinsic matrix for RGB images how can I convert it to intrinsic matrix for depth? They are already aligned (as far as I know). Maybe I don't need to convert and just downscale it according to depth resolution.
But I have an issue in that case - how to convert transformation matrix. I think it includes elements according to RGB as well.

**Comment by theNded** [comment]
Thanks for the feedback! Low resolution could be a problem for reconstruction. I personally would be interested in such hand-held device's data, but my capacity is limited for now. Will close the issue and let you know if I have any update later.
