### ISSUE TITLE
How to change the locations and the colors of selected points in a point cloud?

### ISSUE THREAD

**Issue by Hassan-math** [isl-org/Open3D#4142]
Hi,

I've created a point cloud(e.g. `pcd`) with 200 points. Now, I want to use "Non-blocking visualization" and for instance change the location and the color of point 0 in the point cloud. So, I tried this code:

```
for i in range(icp_iteration):
    pcd.points[0] = o3d.utility.Vector3dVector(New_Location)
    vis.update_geometry(pcd)
    vis.poll_events()
    vis.update_renderer()
vis.destroy_window()
``` 
Where `New_Location` is a (1, 3) numpy array. But I get this error:

```
    pcd.points[0] = o3d.utility.Vector3dVector(New_Location)
TypeError: __setitem__(): incompatible function arguments. The following argument types are supported:
    1. (self: open3d.cpu.pybind.utility.Vector3dVector, arg0: int, arg1: numpy.ndarray[float64[3, 1]]) -> None
    2. (self: open3d.cpu.pybind.utility.Vector3dVector, arg0: slice, arg1: open3d.cpu.pybind.utility.Vector3dVector) -> None

Invoked with: std::vector<Eigen::Vector3d> with 166 elements.
Use numpy.asarray() to access data., 0, std::vector<Eigen::Vector3d> with 1 elements.
Use numpy.asarray() to access data.

Did you forget to `#include <pybind11/stl.h>`? Or <pybind11/complex.h>,
<pybind11/functional.h>, <pybind11/chrono.h>, etc. Some automatic
conversions are optional and require extra headers to be included
when compiling your pybind11 module.
```
Same thing happens for the "color" if I use:
```
pcd.colors[0] = o3d.utility.Vector3dVector(New_Color)
```
Where  `New_Color` is a (1, 3) numpy array.
Please, note that I cannot use "translate" matrix, as I want to change the location of only a set of points (not all of them).

How can I manually change the location, color, size and etc of a set of points in a point cloud?

**Comment by hduonggithub** [comment]
You have to convert pcd.points to numpy array like points = np.asarray(pcd.points)
points[0,:] = New_Location # replace the point, it assume that your point is at 0 index
pcd.points = o3d.utility.Vector3dVector(points)

**Comment by theNded** [comment]
@hduonggithub Thanks for the answer! Closed for now.
