### ISSUE TITLE
how to remove 3d labels

### ISSUE THREAD

**Issue by seanloo98** [isl-org/Open3D#4145]
Hi, I'm having a problem removing the 3d labels I've added to a scene widget using the add_3d_label function. Please help

**Comment by errissa** [comment]
Try `remove_3d_label`. It expects a valid label that was created with `add_3d_label`.

**Comment by seanloo98** [comment]
This is the line I used to add the 3D labels:
`        for i in range(len(self.arealabelpoints.points)):
            self.topLeftPanel.add_3d_label(self.arealabelpoints.points[i], self.faceAreas[i])`

I can't seem to remove them using this function:
`        for i in range(len(self.arealabelpoints.points)):
            self.topLeftPanel.remove_3d_label(gui.Label3D(str(self.faceAreas[i]), self.arealabelpoints.points[i]))`

What have I done wrong?
