### ISSUE TITLE
Radius outlier removal  - Estimated time /Percentage

### ISSUE THREAD

**Issue by Camilochiang** [isl-org/Open3D#4153]
**Is your feature request related to a problem? Please describe.**
When working with big point clouds (>30x10^6 points) Radius outlier removal take a while and sometimes is hard to determinate if the program is still running

**Describe the solution you'd like**
Is is possible to implement a loading /percentage bar? 

Thanks!

**Comment by chunibyo-wly** [comment]
I'm working on this.
