### ISSUE TITLE
Issues in registering the same 3D models using the development version.

### ISSUE THREAD

**Issue by chz31** [isl-org/Open3D#4154]
Hi all,

I asked this question here because I could not register the open3D forum. The activation email did not send to me.

I encountered issues when using the open3D development version 0.13.0+db6d656 by using the Python console in 3D Slicer platform. Some models are not registered/aligned properly (with or without setting up the seed). I checked every step, and the problem occurred at the step of RANSAC calculation based on the function "pipelines.registration.registration_ransac_based_on_feature_matching". I used the default settings for the arguments.

I previously used the stable version 0.10.0, and the models are registered very well. However, I wanted to set up a seed for repeatable results for other purposes, so I tried the development version. 

I wonder if there is any change of algorithm in RANSAC calculation in the development version vs. the stable version of open3D?

Thank you very much!

Chi
**Environment (please complete the following information):**

- Operating system: Windows 10 64-bit
- Python version: Python 3.6
- Open3D version: 0.13.0+db6d656
- Is this remote workstation?: No
- How did you install Open3D?: Pip Install

**Comment by theNded** [comment]
The major changes are in the `criteria` (see [0.13](http://www.open3d.org/docs/release/python_api/open3d.pipelines.registration.registration_ransac_based_on_feature_matching.html) and [0.10](http://www.open3d.org/docs/0.10.0/python_api/open3d.registration.registration_ransac_based_on_feature_matching.html))We have switched from a hard-coded number of validations to a confidence-based iteration estimation. 
You may increase the number of iterations (to say 1M) and confidence (to say 0.9999) to improve the accuracy.

**Comment by chz31** [comment]
Thank you very much for your reply! Sorry for the delayed response. I changed the number of iterations to 10000 and confidence to 0.9999, I still got the same problem of wrong registration after setting a seed. This issue did not happen with version 10.0.

Best,
Chi

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by chz31** [comment]
I changed the iterations to 1 million, sorry for the typo in the previous message.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
