### ISSUE TITLE
Fusing multiple depth maps

### ISSUE THREAD

**Issue by chinmay5** [isl-org/Open3D#4156]
Thank you so much for the wonderful library. I was struggling with one thing though and your help would be highly appreciated.

I want to perform a reconstruction of small objects such as the one shown in this figure. 

![image](https://user-images.githubusercontent.com/16525717/136954918-bb512ee3-9926-4c7b-af7c-791ca34b66f6.png)

For this, I am using the Intel realsense D435i cameras. The setup would involve 8 cameras looking at the objects from 8 different viewpoints. I would record the images and depth maps for each of the views and try the reconstruction. For this, I am following the 
`https://github.com/isl-org/Open3D/blob/master/examples/python/reconstruction_system/run_system.py`
script. I have modified the record_images script to get input images and depth maps from the multiple different sensors. Now I would really appreciate some feedback for the following:-
1. Since I have multiple cameras, how should I handle the different intrinsic during the reconstruction? Would it be fine to use the default setup (I am currently experimenting with a couple of cameras only).
2. Does the setup sound robust (It would be great to have some feedback on the feasibility of such a setup before proceeding with buying more hardware).

I am open to suggestions and changes to the overall pipeline if the approach does not seem useful.

Thanks in advance.

**Comment by theNded** [comment]
Sorry for getting back late. For fixed rig calibration it is recommended to use OpenCV's calibration module, since that is not our specialty. Provided the poses, you may use the [integration](http://www.open3d.org/docs/latest/tutorial/t_reconstruction_system/integration.html) pipeline after organizing the captured images. Hope it helps!
