### ISSUE TITLE
Someting Error  find  when  compiling the code，How  to  slove it? 

### ISSUE THREAD

**Issue by WJinhai** [isl-org/Open3D#4158]
patch failed: CMakeLists.txt:1	ext_tbb (ExternalProjectTargets\ext_tbb\ext_tbb)	E:\BaiduNetdiskDownload\Open3D\build\CUSTOMBUILD	1	

CMakeLists.txt: patch does not apply	ext_tbb (ExternalProjectTargets\ext_tbb\ext_tbb)	E:\BaiduNetdiskDownload\Open3D\build\CUSTOMBUILD	1

**Comment by WJinhai** [comment]
![image](https://user-images.githubusercontent.com/29060221/137851254-fa570dad-453c-4f05-9dd3-53e6f1fec873.png)

17>-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19042.
16>CUSTOMBUILD : error : patch failed: CMakeLists.txt:1
16>CUSTOMBUILD : error : CMakeLists.txt: patch does not apply
16>已完成生成项目“ext_tbb.vcxproj”的操作 - 失败。

**Comment by xkaraman** [comment]
I think it is something about `git` operations. Make sure you updated all submodules in open3d folder with `git submodule update --init --recursive`. Remove your build folder and follow again the procedure of building.

**Comment by theNded** [comment]
Thanks @xkaraman for the instructions. Closed for now.
