### ISSUE TITLE
Missing include path for fmt/format.h

### ISSUE THREAD

**Issue by SoftwareApe** [isl-org/Open3D#4162]
**Describe the bug**
When using CMake `find_package` to retrieve Open3D installed somewhere, `Open3D_LIBRARIES` is set to `<INSTALL_DIR>/include`. When trying to include `open3d/Open3D.h` I get the error that it can't find `fmt/format.h`.

**To Reproduce**
Use CMake find_package as described above.

**Expected behavior**
Add ` `<INSTALL_DIR>/include/open3d/3rdparty` to Open3D_LIBRARIES, which includes the `fmt/format.h` header.

**Environment (please complete the following information):**

- Operating system: Ubuntu 18.04
- Python version: Python 3.6
- Open3D version: master (535d4216e713dd2dfa43f5be91f2f6fe23f7bb1e)
- Is this remote workstation?: yes
- How did you install Open3D?: build from source
- Compiler version (if built from source): gcc 7.5

**Comment by xkaraman** [comment]
Are you refering to building a 3rd party project that use Open3D as a dependency? 

How does your CMakeLists.txt look like?

I couldnt reproduce the error while following this [example](http://www.open3d.org/docs/latest/tutorial/C++/cplusplus_interface.html#create-c-project).

**Comment by theNded** [comment]
Redirect to #4164, closed for now.
