### ISSUE TITLE
fatal error: 'format.cc' file not found

### ISSUE THREAD

**Issue by SoftwareApe** [isl-org/Open3D#4163]
**Describe the bug**
After fixing the include paths for 3rd party dependencies (#4162 ), I get the error `fatal error: 'format.cc' file not found`.

There is indeed no format.cc on my system anywhere. According to https://askubuntu.com/a/1205769/728779 this is part of spdlog. But even install libspdlog-dev, find_packaging it and including it's include directories, the bug remains.

When including ./usr/include/spdlog/fmt/bundled/ (which includes format.cc) I get a host of errors, which don't seem to be related.

I was able to work around this by removing `#define FMT_HEADER_ONLY 1` in `<open3d_install>/include/open3d/utility/Logging.h`.

**To Reproduce**
Build using CMake

**Expected behavior**
Build without issues.

**Environment (please complete the following information):**

- Operating system: Ubuntu 18.04
- Python version: Python 3.6
- Open3D version: master (535d4216e713dd2dfa43f5be91f2f6fe23f7bb1e)
- Is this remote workstation?: yes
- How did you install Open3D?: build from source
- Compiler version (if built from source): gcc 7.5

**Comment by theNded** [comment]
Redirect to #4164, closed for now.
