### ISSUE TITLE
Lots of undefined reference errors when using CMake

### ISSUE THREAD

**Issue by SoftwareApe** [isl-org/Open3D#4164]
**Describe the bug**
After adding workaround for #4162 and #4163, and adding `-DGLIBCXX_USE_CXX11_ABI=ON` as detailed in [this comment on #2286](https://github.com/isl-org/Open3D/issues/2286#issuecomment-766102193) compilation works, but linking breaks on multiple undefined references.

After some iteration I found I needed to add these libraries to get it to link

```cmake
<open3d_install>/lib/libOpen3D_3rdparty_assimp_IrrXML.a
<open3d_install>/lib/libOpen3D_3rdparty_assimp_assimp.a
<open3d_install>/lib/libOpen3D_3rdparty_glew.a
<open3d_install>/lib/libOpen3D_3rdparty_jsoncpp.a
<open3d_install>/lib/libOpen3D_3rdparty_qhullcpp.a
<open3d_install>/lib/libOpen3D_3rdparty_qhull_r.a
<open3d_install>/lib/libOpen3D_3rdparty_rply.a
<open3d_install>/lib/libOpen3D_3rdparty_liblzf.a
<open3d_install>/lib/libOpen3D_3rdparty_glfw.a
<open3d_install>/lib/libOpen3D_3rdparty_tinyfiledialogs.a
```

**To Reproduce**
Build something with CMake and open3d.

**Expected behavior**
All libraries should be contained in `Open3D_LIBRARIES`.

**Environment (please complete the following information):**

- Operating system: Ubuntu 18.04
- Python version: Python 3.6
- Open3D version: master@535d4216e713dd2dfa43f5be91f2f6fe23f7bb1e
- Is this remote workstation?: yes
- How did you install Open3D?: build from source
- Compiler version (if built from source): gcc 7.5

**Comment by HTLife** [comment]
@xkaraman This minimal example might be related to this issue.
https://github.com/isl-org/Open3D/issues/2286#issuecomment-948234131

**Comment by SoftwareApe** [comment]
Hi, I did the installation according to the documentation to a specified folder, only adding the Release flag and building as a static library.

Then I find_packaged it with a hint to the installation directory.

http://www.open3d.org/docs/release/compilation.html

**Comment by theNded** [comment]
Did you use the `--recursive` flag when cloning the repo in the first place? It was required for previous versions.

At current it is not needed though, so it might worth trying to start from scratch and see how it works.

**Comment by ssheorey** [comment]
Closing this issue since @theNded 's comment should solve it. Please open a new issue if anyone faces this problem.
