### ISSUE TITLE
Usage of CUDA GPU ICP for open3D

### ISSUE THREAD

**Issue by nubertj** [isl-org/Open3D#4170]
Hi everyone,
Thanks a lot for making open3D available! We are using the library directly in C++ and are very happy about its extensive functionality.
As we have GPU compute available on our robot, we would be happy about making also full use of the GPU capabilities of open3D.

However, after successfully building open3D from source with the CUDA flag, we do not exactly know how to make use of the GPU ICP as advertised in this video: [link](https://youtu.be/pLCVCH7ypI4?t=64).
Is there any documentation for this somewhere? 

Thanks a lot!

**Comment by nubertj** [comment]
@reyanshsolis , is there any update on this?

**Comment by reyanshsolis** [comment]
Yes, I have added a PR for it. After merging you may find the same at Open3D Documentation. 
Meanwhile, you may download the same from [here](https://github.com/isl-org/Open3D/suites/4315597572/artifacts/112877061)

P.S. The PR also adds new features.

Thanks!

**Comment by jelavice** [comment]
Thank you for the tutorial and for the whole library :+1: :pray:  I really enjoy using it :smiley: 

I quickly made a simple registration benchmark where I compared the old (eigen based) ICP with the tensor ICP (with and without GPU). It seems that the old registration pipeline is still the fastest. The tensor on CPU is by far the slowest for me, while with GPU enabled the registration is between 1.8x and 10x slower compared to the old ICP, depending on the pointcloud size.

I briefly searched the issues and it seems that other users have experienced similar behaviour for the NN search. Have you benchmarked the registration pipeline ever? Does it fit with your observations?

Thanks for the info.

**Comment by AlexandreLaborde** [comment]
@jelavice 4 years later and I still have the same issue!

- Old ICP : 322 ms
- Tensor ICP CUDA : 1285 ms
- Tensor ICP CPU : 1551 ms
 
Have you made any progress speeding up ICP ?

**Comment by TheExDeus** [comment]
Same for me. Tensor ICP on CPU is MUCH slower than the old one.
