### ISSUE TITLE
module 'open3d.cpu.pybind.t.geometry' has no attribute 'RaycastingScene'

### ISSUE THREAD

**Issue by luiscastro1995** [isl-org/Open3D#4176]
I am trying to run the RaycastingScene example however I getting a few errors running the following lines:
1. vertices = o3d.core.Tensor([[0, 0, 0], [1, 0, 0], [1, 1, 0]], dtype=o3d.core.float32)
    1.1. error: AttributeError: module 'open3d.core' has no attribute 'float'
2. triangles = o3d.core.Tensor([[0, 1, 2]], dtype=o3d.core.uint32)
    2.1. error: AttributeError: module 'open3d.core' has no attribute 'uint32'
3. scene = o3d.t.geometry.RaycastingScene()
    3.1. AttributeError: module 'open3d.cpu.pybind.t.geometry' has no attribute 'RaycastingScene'

I am using
- Ubuntu 20.04 LTS
- Python 3.6 and Python 3.8.8
- Open3D installed with pip and conda on both python versions

Does anyone know how to solve this problem?

**Comment by theNded** [comment]
This is still the latest feature and compiling from source would provide the feature. It will be shipped with Open3D 0.14 which is due soon, so you may either play with the source code and wait for a little while.
