### ISSUE TITLE
C++ Static library support

### ISSUE THREAD

**Issue by HTLife** [isl-org/Open3D#4177]
I want to create a handy tool like point cloud downsampling using Open3D with C++.
However, the .so shared library is very large.  (libOpen3D.so is about 1GB)
Therefore, I'm thinking to build the Open3D as a static library and make the utility program only link the used symbol.

Open3D on Windows seems to have the static library support.  Do you have any instructions for building the Linux (Ubuntu) version of the static library? (.a file)

---
I tried the python binary packaging tool "pyinstaller".  But the result execution file is too big.  And also has the dependencies issue.

**Comment by xkaraman** [comment]
Did you `cmake -DCMAKE_BUILD_TYPE=Release ..`? `libOpen3D.so` in my install folder is around 120 MBs. You probably built the library with debug information included.

Also about static library you have to set also the flag `-DBUILD_SHARED_LIBS=OFF`.
