### ISSUE TITLE
Memory keep increasing when use Open3D GUI app to load point cloud in many times

### ISSUE THREAD

**Issue by yuecideng** [isl-org/Open3D#4179]
I built Open3D from source and run GUI app for test (which is inside `build/bin/Open3D/`).
But when I open the same point cloud file many times, the memory keeps increased which is so weird!

The first open:
![image](https://user-images.githubusercontent.com/42235877/137908211-9b559238-d7e7-42d1-9c37-135e7732b0a5.png)

After about open 6 times:
![image](https://user-images.githubusercontent.com/42235877/137908510-c9605cc4-e8e8-45f7-b1de-cdebf3a50a5e.png)

System environment:
- ubuntu 20
- Open3D == 0.13.0

**Comment by hduonggithub** [comment]
You would better to remove geometry before adding, remove_geoemetry('you pcd name')
Or check if the pcd is already added then skip adding again, scene.has_geometry('you pcd name')

**Comment by yuecideng** [comment]
Actually when I use the `open` button in GUI app, the program wil call `SetGeometry` function backend, in which the `ClearGeometry ` will be called. (the source file is in `Open3D/cpp/open3d/visualization/visualizer/GuiVisualizer.cpp`)
```
void GuiVisualizer::SetGeometry(
        std::shared_ptr<const geometry::Geometry> geometry, bool loaded_model) {
    auto scene3d = impl_->scene_wgt_->GetScene();
    scene3d->ClearGeometry();
```

**Comment by errissa** [comment]
PR #4421 which is now merged should fix this problem. Please reopen if you continue to have problems.
