### ISSUE TITLE
Document Bug, The steps in 'Build from source' does not optimize correctly.

### ISSUE THREAD

**Issue by YusukeSuzuki** [isl-org/Open3D#4207]
**Describe the bug**
Following 'Build from source' will perform a debug build using `-O2` . This results in serious performance degradation for the end user. This is a problem because self-building is common in ARM environments.

**To Reproduce**

when cmake

```shell
mkdir build
cd build
cmake ..
find . -name '*.make' | xargs grep O2
```

when make

```shell
make VERBOSE=1 | grep O2
```

or 

```
cmake --build . --config Release --target install VERBOSE=1 | grep O2
```

**Expected behavior**

At `3. Config` step, the correct command is:

```shell
cmake -DCMAKE_BUILD_TYPE=Release
```

check result

```shell
find . -name '*.make' | xargs grep O3
cmake --build . --config Release --target install VERBOSE=1 | grep O3
```

**Environment (please complete the following information):**

Ah ... do you need this?

- Operating system: Ubuntu 20.04
- Python version: Python 3.8
- Open3D version: 0.13.0
- Is this remote workstation?: yes
- How did you install Open3D?: build from source
- Compiler version (if built from source): gcc 9.3.0

**Comment by yxlao** [comment]
This is true. By default, we use `RelWithDebInfo` which is O2. To use O3, you'll need to use the `Release` cmake build type.

If we follow the instructions in http://www.open3d.org/docs/release/arm.html#build, we do recommend using `Release` build type by default.
