### ISSUE TITLE
How to combine webrtc visualization with a custom visualizer?

### ISSUE THREAD

**Issue by thanos-sakelliou** [isl-org/Open3D#4216]
Hello,

I am trying to use my custom visualizer that is made with 
`   vis = o3d.visualization.Visualizer()`
 `   vis.create_window()`
`    ...`
 `   vis.poll_events()`
`    vis.update_renderer()
`
and stream it with the new webrtc_visualizer/server.

The only way displayed in the documentation is by using `draw()` function from `webrtc_visualizer`. Is it possible (and how) to do that with a custom visualizer?

**Environment:**
-  Ubuntu 18.04
- Python 3.6
- Open3D version: 0.13.0

**Comment by ssheorey** [comment]
Hi @thanos-sakelliou for webrtc, you will need to use the new visualization APIs from:
```
o3d.visualization.O3DVisualizer
o3d.visualization.gui
o3d.visualization..rendering
```

**Comment by yxlao** [comment]
As mentioned above, we need to use the new visualizer API.
