### ISSUE TITLE
Depth Image filtering and normal estimation not working

### ISSUE THREAD

**Issue by jjparkcv** [isl-org/Open3D#4220]
I'm trying to filter my depth image using filter_bilateral and estimate normal using create_normal_map.

`color_raw = o3d.io.read_image("./rgb/00021/0000001-000000000000.jpg")
depth_raw = o3d.io.read_image("./depth/00021/0000001-000000000000.png")
rgbd_image = o3d.geometry.RGBDImage.create_from_color_and_depth(
    color_raw, depth_raw)
rgbd_image.depth.create_normal_map()
`

This code gives me the error:
`AttributeError: 'open3d.cpu.pybind.geometry.Image' object has no attribute 'create_normal_map'
`

What is wrong, and how can I use the create_normal_map function? Is this potentially a bug in the python binder?
Thank you in advance.

**Comment by theNded** [comment]
A normal map should be estimated from a vertex map. A vertex map can be created by [create_vertex_map](http://www.open3d.org/docs/release/python_api/open3d.t.geometry.Image.html#open3d.t.geometry.Image.create_vertex_map). All of them are from the `t` namespace (stands for tensor), so you will need to start from `im = o3d.t.io.read_image`.

**Comment by jjparkcv** [comment]
Thank you @theNded !

**Comment by theNded** [comment]
No problem, feel free to reopen if the problem persists.
