### ISSUE TITLE
AttributeError: type object 'open3d.cpu.pybind.t.geometry.TriangleMesh' has no attribute 'from_legacy'

### ISSUE THREAD

**Issue by wxyelena** [isl-org/Open3D#4227]
in textured-mesh.py

if i use 
mesh = o3d.t.geometry.TriangleMesh.from_legacy(
        o3d.io.read_triangle_mesh(model_name))
i got issue: 
AttributeError: type object 'open3d.cpu.pybind.t.geometry.TriangleMesh' has no attribute 'from_legacy'

but if i use
mesh = o3d.t.geometry.TriangleMesh.from_legacy_triangle_mesh(
        o3d.io.read_triangle_mesh(model_name))
it works. 

so what's the problem?

**Comment by ybbouchta** [comment]
Hey @wxyelena, 

I had a similar issue a couple weeks ago. I fixed it by downloading the latest development branch - the current release (0.13.0) uses the x.from_legacy_x() syntax but that has been changed in the most recent development branch to x.from_legacy() 

You can download the latest development version by following the instruction posted [here](http://www.open3d.org/docs/0.12.0/getting_started.html)

**Comment by yxlao** [comment]
You can find the latest dev wheel at:
http://www.open3d.org/docs/latest/getting_started.html#development-version-pip

**Comment by wxyelena** [comment]
> Hey @wxyelena,
> 
> I had a similar issue a couple weeks ago. I fixed it by downloading the latest development branch - the current release (0.13.0) uses the x.from_legacy_x() syntax but that has been changed in the most recent development branch to x.from_legacy()
> 
> You can download the latest development version by following the instruction posted [here](http://www.open3d.org/docs/0.12.0/getting_started.html)

Thank you!!!!!!!!!!

**Comment by wxyelena** [comment]
> You can find the latest dev wheel at: http://www.open3d.org/docs/latest/getting_started.html#development-version-pip

thanks!
