### ISSUE TITLE
Inconsistent results while initializing a point cloud with an extrinsic matrix vs using the transform method

### ISSUE THREAD

**Issue by ybbouchta** [isl-org/Open3D#4232]
I have noticed inconsistent results when initializing a point cloud with an extrinsic matrix vs initializing the unaligned point cloud and then subsequently transforming the point cloud (see code below) 

I have performed a calibration using a chessboard to align two depth cameras. I would expect that method 1 and method 2 give the same results, but instead, only method 1 works. Is that behaviour expected ? 
```
import open3d as o3d
import numpy as np

#Method 1 
def method_1(color, depth, intrinsics, extrinsics):
    rgbd = o3d.t.geometry.RGBDImage(color, depth, aligned = True)
    #Initializing point cloud from an RGBD image with an extrinsic matrix
    pcd = o3d.t.geometry.PointCloud.create_from_rgbd_image(rgbd, intrinsics, extrinsics, scale, depth_max )
    return pcd

#Method 2
def method_2(color, depth, intrinsics, extrinsics):
    rgbd = o3d.t.geometry.RGBDImage(color, depth, aligned = True)
    temp_extrinsics = o3d.core.Tensor(np.identity(4),dtype = o3d.core.Dtype.Float32)
    pcd = o3d.t.geometry.PointCloud.create_from_rgbd_image(rgbd, intrinsics, temp_extrinsics, scale, depth_max )
    pcd.transform(extrinsics)
    return pcd


pcd_1 = method_1 (color, depth, intrinsics, extrinsics, scale, depth_max)
pcd_2 = method_2 (color, depth, intrinsics, extrinsics, scale, depth_max)
o3d.visualization.draw_geometries([pcd_1.to_legacy(), pcd_2.to_legacy()])
```

Here is the results of this code with the values initialized from a RealSense camera:

![image](https://user-images.githubusercontent.com/17818708/140008283-7a957e2c-3d1b-49a7-84e4-7d5cedb2b664.png)

I would expect the two images to be perfectly overlapped but obviously not the case here. 

Edit: Forgot to mention that the point cloud initialised with method_1 is the one in the correct frame of reference

**Comment by WangYixuan12** [comment]
I encountered the same issue. The result of calling o3d.geometry.PointCloud.create_from_rgbd_image(rgbd, intrinsics, extrinsics) is not correct in my case.

**Comment by ybbouchta** [comment]
I did a few test using a simple point cloud have encountered some interesting results. 

As @WangYixuan12 mentioned, Method 2 (using the .transform() method) gives the correct results (a matrix multiplication of each points' coordinate)

To produce the correct results using Method 1, you would have to replace the extrinsics matrix by its inverse.

**Comment by theNded** [comment]
Extrinsic means `world to camera`. Pose means `camera to world`.
You need to provide extrinsic for the creation, and the pose (which is the inverse extrinsic) for the transform. The results should be consistent, and please let us know if that doesn't work either.
