### ISSUE TITLE
Does Open3D have a C API?

### ISSUE THREAD

**Issue by ababo** [isl-org/Open3D#4233]
I would like to use Poisson surface reconstruction from Rust, so I need a C API for that. Does Open3D provide a C (not C++) API?

**Comment by reyanshsolis** [comment]
Hi @ababo, I don't think Open3D provides a C API.

**Comment by timzaak** [comment]
This give an example of Rust use Open3D: https://github.com/timzaak/rust-use-cpp-complex-library
