### ISSUE TITLE
Frustum filter

### ISSUE THREAD

**Issue by Pablojc05** [isl-org/Open3D#4234]
Hi there, I need to filters points inside a frustum given by pose and FOV of the camera. I have been looking for a class that could do so but the only thing I have found is that I can filter points inside a Bounding Box. But, how can I create that Bounding Box based on the FOV of the camera and distances to the near and far planes? Is there a more optimal way to do it instead of working with bounding boxes?

**Comment by theNded** [comment]
You can use projective transform. Given a `(x, y, z)` point, you first check its depth. If it is between the near and far planes, then you project the point to the camera plane and see if it is inside (depending your coordinate system, it could be [0, width] x [0, height] if you are using pixel as units, or [-1, 1] x [-1, 1] if it is in NDC). [This link] might help.
