### ISSUE TITLE
Changing PointCloud representation of points and normals from std::vector<Eigen::Vector3d> to Eigen::Matrix3Xd?

### ISSUE THREAD

**Issue by vitsensei** [isl-org/Open3D#4239]
**Describe the solution you'd like**
Most people who works with Eigen library like to keep their matrix in the format `Eigen::Matrix3Xd` instead of `std::vector<Eigen::Vector3d>`. While it is convenient to convert `std::vector<Eigen::Vector3d>` to `Eigen::Matrix3Xd` using map, it is not so trivial to do the other way since std::vector will always take full control of its memory.

I would like to see Open3D's representation of matrices (point cloud's points and normals) to be in Eigen::Matrix format instead of going through std::vector, unless there's a technical challenge behind it?

**Describe alternatives you've considered**
I have consider keeping copies of the same data in both format (`Eigen::Matrix3Xd` and `std::vector<Eigen::Vector3d>`), but it is not ideal since it is not memory efficient. Imagine working with 100mil+ point cloud!

**Additional context**
```
//// To convert from eigen matrix to Open3D's
const std::vector<Eigen::Vector3d> load_eigen_matrix_into_std_vector_eigen_vector(const Eigen::Matrix3Xd &eigen_matrix)
{
    // First copy
    const auto tensor_cloud = open3d::core::eigen_converter::EigenMatrixToTensor(eigen_matrix.transpose().eval());
    // Second copy
    return open3d::core::eigen_converter::TensorToEigenVector3dVector(tensor_cloud);
}

//// To convert from Open3D's to eigen matrix
const Eigen::Map<const Eigen::Matrix3Xd> eigen_cloud(open_cloud.points_[0].data(), 3, open_cloud.points_.size());

// or
const Eigen::Matrix3Xd eigen_cloud = Eigen::Map<const Eigen::Matrix3Xd>(open_cloud.points_[0].data(), 3, open_cloud.points_.size());
```

**Comment by reyanshsolis** [comment]
Hi @vitsensei, we don't have plans to modify the Eigen based geometry implementation, however, we have been working on adding `Tensor` based geometry support in the library, with GPU support. It's in `t` namespace. You may explore that for flexibility. 

Thanks!

**Comment by vitsensei** [comment]
Gotcha.

Out of curiosity, what is the `t` in t namespace stands for?

**Comment by reyanshsolis** [comment]
It is the namespace for `open3d tensor` based implementations. 
open3d tensor [link](http://www.open3d.org/docs/latest/tutorial/core/tensor.html), supports vectorized operations link numpy, eigen on CPU and GPU. We are working on exporting our geometry, io, pipelines, based on this data structure, like this [ICP](http://www.open3d.org/docs/latest/tutorial/t_pipelines/index.html) for example.
We will be adding more tutorials soon! 

Thanks for using Open3D.
