### ISSUE TITLE
mouse-and-point-coord.py example giving different coordinates from different camera angle

### ISSUE THREAD

**Issue by JiayouQin** [isl-org/Open3D#4244]
**IMPORTANT: Please use the following template to report the bug.**

Before submitting:

1. Search for [similar issues](https://github.com/isl-org/Open3D/issues).
2. For Python issues, please test with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip). It may be already fixed!
_____

**Describe the bug**

Hi, I was trying one of the examples  and  have encontered some issue:
the world coordnates the example gives me seems to be very random, each time I change camera view angle the same point gives me different coordinates. 
I rendered a sphere to the coordnates it gave me and they were all over the place.
they do deviate alot as I move around, they are not approximations.

**To Reproduce**
file path: examples/python/gui/mouse-and-point-coord.py

**cd examples/python/gui
python mouse-and-point-coord.py**

to make things easier visually I made the following changes:

mat renamed to self.mat for referencing
named self.click=0
added the following code to render a sphere after

> **text = "({:.3f}, {:.3f}, {:.3f})".format(world[0], world[1], world[2])**

```
mesh = o3d.geometry.TriangleMesh.create_sphere(radius=15/1000)
mesh.translate((world[0],world[1],world[2]), relative=False)
self.widget3d.scene.add_geometry(f"Point Cloud{self.click}", mesh, self.mat)
self.click += 1
```

**Expected behavior**

Expecting the point to be exact same value and spheres are in the same spot

**Screenshots**
![scr](https://user-images.githubusercontent.com/46877249/140458046-c4e18778-1373-4d9b-9ba2-27bbb771521a.png)
The red mark shows where I click, and the grey spheres poistioned from the coordinates I get.

**Environment (please complete the following information):**

- Operating system: (Windows 10 64-bit)
- Python version: (Python 3.8)
- Open3D version:  (open3d-0.13.0-cp38)
- Is this remote workstation?: (No)
- How did you install Open3D?: (pip)

**Additional context**
I monkeyed around the code for a bit and found that if I don't set any camera angle and do not rotate the camera I the coordinates are correct except that the y axis is reversed. 
(I cannot see anything using the original pcd this way so I loaded another ply file)
If I turn the camera the coordinates are incoorect again.

**Comment by JiayouQin** [comment]
Hello @prewettg, sorry to bother you here but I've been trying to working this out for  a  few days...any help would be  appreciated!

**Comment by chunibyo-wly** [comment]
It looks like a problem of mixing local and world coordinates.
I need to spend a little time studying the code time and then find out why.

**Comment by chunibyo-wly** [comment]
Looks like a bug of camera projection matrix

**Comment by KimJR** [comment]
I have encountered the same problem. Does anyone know how to fix this?

**Comment by JiayouQin** [comment]
due to this issue I used openGL to write my own code, I have encountered similar issue, and it was due to stack matrix. i suspect that you need to pop the current matrix stack before adding new element, however I do not know what api have caused this issue: be it addgeometry or unproject

**Comment by ins7itia** [comment]
I think inside unproject(), it uses input coord(img domain coord with depth) directly to gl coord. Thus:
```
world = self.widget3d.scene.camera.unproject(
                        event.x, (self.widget3d.frame.height - event.y), depth, self.widget3d.frame.width,
                        self.widget3d.frame.height)
```

Which flips y-coord; In my case it fixed the problem.

**Comment by vdrobnyi** [comment]
Thanks, @ins7itia!

It is also necessary to use pixel coordinates of a widget. This would be necessary if the widget is not located in the top-left part of the window. 

`
world = self.widget3d.scene.camera.unproject(
                        x, (self.widget3d.frame.height - y), depth, self.widget3d.frame.width,
                        self.widget3d.frame.height)
`
