### ISSUE TITLE
DenseSLAM.cpp set device “CPU：0”， does it mean the denseslam only supports CPU？

### ISSUE THREAD

**Issue by guyuezuntinggithub** [isl-org/Open3D#4256]
DenseSLAM.cpp set device “CPU：0”， does it mean the denseslam only supports CPU？
![Screenshot from 2021-11-08 15-37-42](https://user-images.githubusercontent.com/63081832/140702420-5e968531-faff-4958-9a9e-53f2f47a2b1c.png)

**Comment by reyanshsolis** [comment]
That is the default option, you may pass the `device` as an argument. 
If you have CUDA installed, you may use `CUDA:0` for example `--device CUDA:0` , as a device to run the example on.
P.S. Open3D must be built with CUDA, to use GPU.

**Comment by guyuezuntinggithub** [comment]
> That is the default option, you may pass the `device` as an argument. If you have CUDA installed, you may use `CUDA:0` for example `--device CUDA:0` , as a device to run the example on. P.S. Open3D must be built with CUDA, to use GPU.

I found a situation. When I create an image with "CUDA:0" with the following code 
uint16_t *imagedata;
Image depthimage(480,640,1,core::Dtype::UInt16,core::Device("CUDA:0"));
imagedata = (uint16_t *)depthimage.GetDataPtr();
uint16_t  R=255;
uint16_t  G=255;
uint16_t  B=255;
colorimagedata[0]=R;
colorimagedata[1]=G;
colorimagedata[2]=B;
It occurs error at "colorimagedata[0]=R".simeslike there is no memory for R to instore.
