### ISSUE TITLE
compile PointCloudCPU.cpp on macOS 12.0.1 problem

### ISSUE THREAD

**Issue by chnmrc** [isl-org/Open3D#4257]
**Describe the bug**
Problem on compile Open3D on macOS

**To Reproduce**

`
git clone --recursive https://github.com/intel-isl/Open3D
cd Open3D
mkdir build
cd build
cmake ..
make -j
`

**Expected behavior**
Compilation error on:

https://github.com/isl-org/Open3D/blob/8c6a7e74582fe09f3a2295933794bfc16026c21f/cpp/open3d/t/geometry/kernel/PointCloudCPU.cpp#L79

**Screenshots**
![Screenshot 2021-11-08 at 09 45 02](https://user-images.githubusercontent.com/1184799/140711002-b575491c-364d-4de0-b564-4b897abd63d2.png)

**Environment (please complete the following information):**

- Operating system: macOs 12.0.1
- Open3D version: master branch
- Is this remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source):
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: x86_64-apple-darwin21.1.0
Thread model: posix
**Additional context**

If I remove https://github.com/isl-org/Open3D/blob/8c6a7e74582fe09f3a2295933794bfc16026c21f/cpp/open3d/t/geometry/kernel/PointCloudCPU.cpp#L79
then it will compile

**Comment by Jaykob** [comment]
I can confirm the same problem with Big Sur 11.5.2
