### ISSUE TITLE
Is there anyone runningDenseSLAM.cpp successfully?

### ISSUE THREAD

**Issue by guyuezuntinggithub** [isl-org/Open3D#4259]
Is there anyone running DenseSLAM.cpp successfully?
the first integrate get an error

**Comment by reyanshsolis** [comment]
Yes, it is a tested example. May you please share more details about the issue?

**Comment by guyuezuntinggithub** [comment]
> Yes, it is a tested example. May you please share more details about the issue?
here is my code 
using namespace open3d;
    using core::Tensor;
    using t::geometry::Image;
    using t::geometry::PointCloud;
    using t::geometry::RGBDImage;


    std::string device_code ="CPU:0";
    utility::SetVerbosityLevel(utility::VerbosityLevel::Info);
    core::Device device(device_code);
    utility::LogInfo("Using device: {}", device.ToString());
    std::string color_folder = "/usr/local/Open3D/rgbd_dataset_freiburg1_room/rgb";
    std::string depth_folder = "/usr/local/Open3D/rgbd_dataset_freiburg1_room/depth";
    std::vector<std::string> color_filenames, depth_filenames;
    utility::filesystem::ListFilesInDirectory(color_folder, color_filenames);
    utility::filesystem::ListFilesInDirectory(depth_folder, depth_filenames);
    if (color_filenames.size() != depth_filenames.size()) {
            utility::LogError(
                    "[DenseSLAM] numbers of color and depth files mismatch. "
                    "Please provide folders with same number of images.");
        }
    std::sort(color_filenames.begin(), color_filenames.end());
    std::sort(depth_filenames.begin(), depth_filenames.end());
    size_t n = color_filenames.size();
    size_t iterations = n;
    iterations = std::min(n, iterations);
    // Intrinsics
    std::string intrinsic_path = "/usr/local/Open3D/rgbd_dataset_freiburg1_room/camera.json";
    camera::PinholeCameraIntrinsic intrinsic = camera::PinholeCameraIntrinsic(
                camera::PinholeCameraIntrinsicParameters::PrimeSenseDefault);
        if (intrinsic_path.empty()) {
            utility::LogWarning("Using default Primesense intrinsics");
        } else if (!io::ReadIJsonConvertible(intrinsic_path, intrinsic)) {
            utility::LogError("Unable to convert json to intrinsics.");
        }
        auto focal_length = intrinsic.GetFocalLength();
        auto principal_point = intrinsic.GetPrincipalPoint();
        Tensor intrinsic_t = Tensor::Init<double>(
                {{focal_length.first, 0, principal_point.first},
                 {0, focal_length.second, principal_point.second},
                 {0, 0, 1}});
        // VoxelBlock configurations
        float voxel_size = 3.f / 512.f;
        float sdf_trunc = 0.04f;
        int block_resolution = 16;
        int block_count = 10000;
// Odometry configurations
        float depth_scale = 1000.f;
        float depth_max = 3.f;
        float depth_diff = 0.07f;

        // Initialization
           Tensor T_frame_to_model =
                   Tensor::Eye(4, core::Dtype::Float64, core::Device("CPU:0"));

           t::pipelines::slam::Model model(voxel_size, sdf_trunc, block_resolution,
                                           block_count, T_frame_to_model, device);

           // Initialize frame
           Image ref_depth = *t::io::CreateImageFromFile(depth_filenames[0]);
           t::pipelines::slam::Frame input_frame(
                   ref_depth.GetRows(), ref_depth.GetCols(), intrinsic_t, device);
           t::pipelines::slam::Frame raycast_frame(
                   ref_depth.GetRows(), ref_depth.GetCols(), intrinsic_t, device);

           // Iterate over frames
               for (size_t i = 0; i < iterations; ++i) {
                   utility::LogInfo("Processing {}/{}...", i, iterations);
                   // Load image into frame
                   Image input_depth = *t::io::CreateImageFromFile(depth_filenames[i]);
                   Image input_color = *t::io::CreateImageFromFile(color_filenames[i]);
                   input_frame.SetDataFromImage("depth", input_depth);
                   input_frame.SetDataFromImage("color", input_color);

                   bool tracking_success = true;
                   if (i > 0) {
                       auto result =
                               model.TrackFrameToModel(input_frame, raycast_frame,
                                                       depth_scale, depth_max, depth_diff);

                       core::Tensor translation =
                               result.transformation_.Slice(0, 0, 3).Slice(1, 3, 4);
                       double translation_norm = std::sqrt(
                               (translation * translation).Sum({0, 1}).Item<double>());

                       // TODO(wei): more systematical failure check.
                       // If the overlap is too small or translation is too high between
                       // two consecutive frames, it is likely that the tracking failed.
                       if (result.fitness_ >= 0.1 && translation_norm < 0.15) {
                           T_frame_to_model =
                                   T_frame_to_model.Matmul(result.transformation_);
                       } else {  // Don't update
                           tracking_success = false;
                           utility::LogWarning(
                                   "Tracking failed for frame {}, fitness: {:.3f}, "
                                   "translation: {:.3f}. Using previous frame's "
                                   "pose.",
                                   i, result.fitness_, translation_norm);
                       }
                   }

                   // Integrate
                   model.UpdateFramePose(i, T_frame_to_model);
                   if (tracking_success) {
                       model.Integrate(input_frame, depth_scale, depth_max);
                   }
                   model.SynthesizeModelFrame(raycast_frame, depth_scale, 0.1, depth_max,
                                              false);
               }

//               if (utility::ProgramOptionExists(argc, argv, "--pointcloud"))
               {
//                   std::string filename = utility::GetProgramOptionAsString(
//                           argc, argv, "--pointcloud",
//                           "pcd_" + device.ToString() + ".ply");
//                   auto pcd = model.ExtractPointCloud(-1);
//                   auto pcd_legacy =
//                           std::make_shared<open3d::geometry::PointCloud>(pcd.ToLegacy());
//                   open3d::io::WritePointCloud(filename, *pcd_legacy);
               }

//               if (utility::ProgramOptionExists(argc, argv, "--mesh"))
               {
                   std::string filename =  "mesh_" + device.ToString() + ".ply";
                   auto mesh = model.ExtractTriangleMesh(-1);
                   auto mesh_legacy = std::make_shared<open3d::geometry::TriangleMesh>(
                           mesh.ToLegacy());
                   open3d::io::WriteTriangleMesh(filename, *mesh_legacy);
               }
when I RUN to code "model.Integrate(input_frame, depth_scale, depth_max);" then I =0 ,it's first frame to integrate. It occurs this wrong info and dump
![image](https://user-images.githubusercontent.com/63081832/141234109-504a6bd4-9076-45ee-a63c-12aea858b1ed.png)

**Comment by theNded** [comment]
Depth scale should be 5000 for TUM datasets. Please wisely use commandline inputs instead of messing up with the code.

**Comment by guyuezuntinggithub** [comment]
> Depth scale should be 5000 for TUM datasets. Please wisely use commandline inputs instead of messing up with the code.

thank you! But I have to build my project, not just play your sample ok?
