### ISSUE TITLE
write_triangle_uvs parameter in open3d.io.write_triangle_mesh not working

### ISSUE THREAD

**Issue by vincentabb** [isl-org/Open3D#4265]
write_triangle_uvs (bool, optional, default=True) – Set to False to not write any triangle uvs, even if present on the mesh. For obj format, mtl file is saved only when True is set

When I set write_triangle_uvs to True, there are no MTL files saved with the obj file. Any insight or help is appreciated.

**Comment by reyanshsolis** [comment]
Closing this issue, due to inactivity. 
The operation seems to work fine on my system. Feel free to re-open the issue, and share your example in future if required.
Thanks.
