### ISSUE TITLE
Degraded color map optimization quality in most recent version

### ISSUE THREAD

**Issue by jaadelgren** [isl-org/Open3D#4266]
**Describe the bug**
There may be an issue with color map optimization in Open3D versions 0.13.0 and up. There's a noticeable difference in the quality of the results when using 0.12.0 versus 0.13.0 (or the latest development version). In the recent versions, the residual falls for a while (first 100 iterations or so, depending on dataset of course) before climbing indefinitely. This is not seen on version 0.12.0.

**To Reproduce**
Install Open3D version 0.13.0 (I used pip/venv).

Download the fountain sample dataset:
```
wget https://github.com/intel-isl/open3d_downloads/releases/download/open3d_tutorial/fountain.zip
unzip fountain.zip
```

Create a config file for the fountain data:
```
{
    "name": "Fountain",
    "path_dataset": "<path/to/fountain/dataset>",
    "template_global_traj": "scene/key.log"
}
```

Run the script `color_map_optimization_for_reconstruction_system.py`, which is included with the Open3D repository:
```
python3 color_map_optimization_for_reconstruction_system.py --config <path/to/fountain/config> --sample_rate 1
```

Observe the results. Repeat the color map optimization with the same data and Open3D version 0.12.0 and notice the difference in outcome.

Let me know if I can provide additional info, logs etc. Hopefully I'm not missing something silly.

**Screenshots**
Here are the (expected) results from Open3D 0.12.0 (first is rigid, second non-rigid):

![0 12 0-rigid](https://user-images.githubusercontent.com/12105947/140847222-263ce452-fc9b-430b-b6e2-611f5ad46d2b.png)
![0 12 0-nonrigid](https://user-images.githubusercontent.com/12105947/140847245-906dcbb5-2996-4da8-a66b-2b6235a8a29b.png)

And here are the results from Open3D 0.13.0 and latest development (rigid, non-rigid):

![0 13 0-rigid](https://user-images.githubusercontent.com/12105947/140847713-2da316e8-e14b-4baf-8894-823cab05634f.png)
![0 13 0-nonrigid](https://user-images.githubusercontent.com/12105947/140847788-e5d20ddf-f775-4dbd-bd1a-108e5386f8a1.png)

`max_iteration` was set to 300 for all of these. The issue is exacerbated when using higher iteration count.

**Environment**
- Operating system: Ubuntu 20.04.3
- Python version: 3.8.10
- Open3D version: 0.12.0, 0.13.0 and latest development
- Is this remote workstation?: no
- How did you install Open3D?: pip

**Comment by yxlao** [comment]
Interesting. Looking at the unit tests, we have hard-coded comparison numerical values and they are consistent across 0.12 and 0.13:
- 0.12: https://github.com/isl-org/Open3D/blob/v0.12.0/python/test/test_color_map.py#L89-L91
- 0.13: https://github.com/isl-org/Open3D/blob/v0.13.0/python/test/test_color_map.py#L100-L102

For the unit test, we only ran 5 iterations. 

I'll check higher-iteration results.

**Comment by yxlao** [comment]
I can confirm the issue. 

```bash
pip install pytest
git checkout yixing/issue-4266

pip install -U open3d==0.12.0
pytest test_012.py -s > test_012_out.txt

pip install -U open3d==0.13.0
pytest test_013.py -s > test_013_out.txt

wget https://storage.googleapis.com/open3d-releases-master/python-wheels/open3d-0.13.0+dd076ba-cp36-cp36m-manylinux_2_27_x86_64.whl
pip install open3d-0.13.0+dd076ba-cp36-cp36m-manylinux_2_27_x86_64.whl
pytest test_013.py -s > test_master_dd076ba.txt
```

And the outputs are:
- https://github.com/isl-org/Open3D/blob/yixing/issue-4266/test_012_out.txt
- https://github.com/isl-org/Open3D/blob/yixing/issue-4266/test_013_out.txt
- https://github.com/isl-org/Open3D/blob/yixing/issue-4266/test_master_dd076ba.txt

Master has exactly the same output as 0.13, but they are different from 0.12.

**Comment by jaadelgren** [comment]
Thanks, @yxlao! I appreciate the quick response (and turnaround) time--let me know if I can provide any other info, but it looks like you've got it under control.
