### ISSUE TITLE
Question about light and shadow effect

### ISSUE THREAD

**Issue by Gilgamesh666666** [isl-org/Open3D#4281]
Hi,

Thank you for the excellent software! I want to draw my point cloud use paint_uniform_color, but i the point cloud has no shadow like this:
![2021-11-11_17-03](https://user-images.githubusercontent.com/43331134/141278096-e1aefc46-4d3a-4aca-86b6-e2d74120905a.png)
but i want the result like the tutorial show:
![image](https://user-images.githubusercontent.com/43331134/141278258-ba607ac9-88f9-4c51-8b95-9be0e50ece63.png)
I will very appreciate if you could give me some hint. Thank you!

**Comment by theNded** [comment]
You will need to first [compute the normals](http://www.open3d.org/docs/latest/python_api/open3d.geometry.PointCloud.html#open3d.geometry.PointCloud.estimate_normals) before visualization.
