### ISSUE TITLE
Transform shift

### ISSUE THREAD

**Issue by skyline624** [isl-org/Open3D#4287]
Hello everyone,
I try to convert a matrix-transformations from the position of my camera into a Pose graph but I have a problem with the "transform" function to check the alignment of my point cloud.

i need to apply rotation on x and y axis but if i do it directly in matrix the point cloud is shifted: 
```python
            a= rotateMatrix(angle_vertical*np.pi/180, angle*np.pi/180, 0)
            pcd.transform(a)
```
![image](https://user-images.githubusercontent.com/35170939/141470456-f50a1ad1-36ce-4fd1-bca8-15aca3107459.png)

if I apply the rotation on the axes one after the other an and transformation each time my cloud of points is aligned

```python
            a= rotateMatrix(angle_vertical*np.pi/180, 0, 0)
            pcd.transform(a)
            

            a= rotateMatrix(0, angle*np.pi/180, 0)
            pcd.transform(a)
```
![image](https://user-images.githubusercontent.com/35170939/141470907-f48037d8-2935-4dbc-be22-e0ea56b309c6.png)

I realized that if I reverse the transformations I find myself in the same case as the first.
Can someone explain to me why this does this and how I can fix it? thank you

**Comment by theNded** [comment]
I don't know where does `rotateMatrix` come from. Could you please give a context? In addition, `transform` expects a transformation matrix, but you seem to be providing a (maybe augmented) rotation matrix, which could cause issue as well.

**Comment by skyline624** [comment]
"rotatematrix" is obtained from this function:
```python
def rotateMatrix(x,y,z):

    rotateXMatrix=np.array([[1, 0, 0, 0],
                     [0, np.cos(x),-np.sin(x), 0],
                     [0, np.sin(x), np.cos(x), 0],
                     [0, 0, 0, 1]])
    rotateYMatrix=np.array([[ np.cos(y), 0, np.sin(y), 0],
                     [ 0, 1, 0, 0],
                     [-np.sin(y), 0, np.cos(y), 0],
                     [ 0, 0, 0, 1]])
    rotateZMatrix=np.array([[np.cos(z),-np.sin(z), 0, 0],
                     [np.sin(z), np.cos(z), 0, 0],
                     [0, 0, 1, 0],
                     [0, 0, 0, 1]])
    rotMat = np.dot(rotateXMatrix, np.dot(rotateYMatrix, rotateZMatrix))
    return rotMat
```
Unless I am mistaken, it is indeed a transformation matrix.
I also did the same manipulation with the "get_rotation_matrix_from_xyz" function of open3d to create the matrix:
```python
            R = pcd.get_rotation_matrix_from_xyz(( angle_vertical*np.pi/180, angle*np.pi/180, 0))
            pcd.rotate(R, center=(0, 0, 0)
```
but I get the same as the first image

**Comment by theNded** [comment]
Order matters in rotation, see [Euler angles](https://en.wikipedia.org/wiki/Euler_angles). According to your successful case
```
            a= rotateMatrix(angle_vertical*np.pi/180, 0, 0)
            pcd.transform(a)
            

            a= rotateMatrix(0, angle*np.pi/180, 0)
            pcd.transform(a)
```
it is more likely that you are using a ZYX order instead of XYZ order. Please try to confirm your Euler angle formulation and modify `rotateMatrix` accordingly.
