### ISSUE TITLE
How do I add shade to my scene and save scene as pictures with different view?

### ISSUE THREAD

**Issue by wxyelena** [isl-org/Open3D#4288]
I tried to use the demo_scene.py file to place the **obj** on the **table** and the **obj** is shadowed. But this can only be shown with vis.draw(). How can I automatically save as images with different view?

![1](https://user-images.githubusercontent.com/75186221/141471160-472bb086-87ee-4608-ba02-13a43b8b3d27.png)

Then I use render_to_image.py to save the image, but the **obj** has no shadow. How do I add a shadow?
![test1](https://user-images.githubusercontent.com/75186221/141471354-821e0d69-fcd3-4a68-95b5-1c183d08724a.png)

**Comment by blueardour** [comment]
Hi, Could I ask is there any progress on the issue? I also have similar needs.

**Comment by wxyelena** [comment]
> Hi, Could I ask is there any progress on the issue? I also have similar needs.

Hello. I was using render_to_image.py to save the photo and the obj had no shadow. That's because I only rendered the shadows for obj and not for table. So after adding the shadow to table, the saved image was fine. Maybe you could try that.

**Comment by wxyelena** [comment]
This problem has been solved. Remember, you need to add shadows to all objects before rendering. Thanks to the authors for their intelligent work.
