### ISSUE TITLE
DenseSLAMGUI  varies from different datasets?

### ISSUE THREAD

**Issue by hitsz-zuoqi** [isl-org/Open3D#4290]
Hey, I Know Open3d is developed following REDWOOD simulated dataset, so when I run  it on the official "016.zip" shot. I get amazing performance like the demo.

However, when I turn into TUM RGBD dataset, the initial can be finished. When I click the pause/resume bottom, it breaks and report the following error:

[Open3D INFO] Using device CUDA:0.
FEngine (64 bits) created at 0x7fa964d08010 (threading is enabled)
FEngine resolved backend: OpenGL
[Open3D INFO] Using Primesense default intrinsics.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Open3D Error] (void open3d::t::geometry::kernel::voxel_grid::DepthTouchCUDA(std::shared_ptr<open3d::core::HashMap>&, const open3d::core::Tensor&, const open3d::core::Tensor&, const open3d::core::Tensor&, open3d::core::Tensor&, open3d::t::geometry::kernel::voxel_grid::index_t, float, float, float, float, open3d::t::geometry::kernel::voxel_grid::index_t)) /home/q/Desktop/Vis_3D/Open3D/cpp/open3d/t/geometry/kernel/VoxelBlockGridCUDA.cu:216: No block is touched in TSDF volume, abort integration. Please check specified parameters, especially depth_scale and voxel_size

what should I do to make it work?

**Comment by hitsz-zuoqi** [comment]
Any suggestion will be appreciated~

**Comment by guyuezuntinggithub** [comment]
> Any suggestion will be appreciated~

I am running this code too, and using the tum dataset, how to set the depth_max and block_resoluthon ? I run the code with many errors, maybe the parameter is wrong. thank you!

**Comment by hitsz-zuoqi** [comment]
@guyuezuntinggithub I have successfully make it by rescale the depth map.
eg.  the depth_scale is 5000 for TUM RGB-D dataset, in Python, using the following code to convert it into REDWOOD simulated form.
`
import cv2
import numpy as np
depthFrame = cv2.imread(dir, -1)
rescaleDepthFrame = (0.2*depthFrame.astype(np.float16)).astype(np.uint16)
cv2.imsave(new_dir, rescaleDepthFrame)
`

**Comment by guyuezuntinggithub** [comment]
> @guyuezuntinggithub I have successfully make it by rescaling the depth map. eg. the depth_scale is 5000 for TUM RGB-D dataset, in Python, using the following code to convert it into REDWOOD simulated form(depth_scale=1000).
> 
> import cv2 import numpy as np depthFrame = cv2.imread(dir, -1) rescaleDepthFrame = (0.2*depthFrame.astype(np.float16)).astype(np.uint16) cv2.imsave(new_dir, rescaleDepthFrame)
> 
> Then the you can run it without any modification to the config except the max_depth. Change the max_depth to verify the performance~

very appreciate your reply! I set the depth scale to 5000 it runs a new error at "TrackFrameToModel" as following
![image](https://user-images.githubusercontent.com/63081832/141683395-c0e84e5e-1750-464c-883f-7d8ba4f7678c.png)
Is there any problem with my code?

**Comment by hitsz-zuoqi** [comment]
I have set depth_scale as 5000 before, in the meanwhile I adjust other possible parameters.
But the initialization will fail like your code. Can you can post your error message?

**Comment by guyuezuntinggithub** [comment]
> I have set depth_scale as 5000 before, in the meanwhile I adjust other possible parameters. But the initialization will fail like your code. Can you can post your error message?
 It occurs this wrong info and dump
![image](https://user-images.githubusercontent.com/63081832/141684239-31a370f6-df89-4ec2-9bf8-9872a2a818fa.png)

**Comment by guyuezuntinggithub** [comment]
> I have set depth_scale as 5000 before, in the meanwhile I adjust other possible parameters. But the initialization will fail like your code. Can you can post your error message?

It occurs this wrong info and dump
![image](https://user-images.githubusercontent.com/63081832/141684280-dd3a14bc-8c25-4303-acb6-421d5cab4a87.png)

**Comment by theNded** [comment]
@hitsz-zuoqi which `commit` of Open3D are you using? There have been several updates and it would be good to stay at the latest commit. Also, you can specify depth scale using the slider in the GUI before clicking start/pause, by default the largest scale is 5000.

**Comment by theNded** [comment]
Closed due to lack of activity. Please feel free to reopen if you can provide more details.
