### ISSUE TITLE
What is the fifferent of Tensor::At and Tensor::GetDataPtr

### ISSUE THREAD

**Issue by guyuezuntinggithub** [isl-org/Open3D#4294]
First I use `(uint16_t *)` get Tensor's DataPtr and set value to  `(uint16_t *)`
second get value from `Tensor's ::At(i,j)`
it occurs dump error.

**Comment by yxlao** [comment]
Could you provide the actual code of how you use the tensor?

**Comment by theNded** [comment]
You have been opening and closing issues so I lost track, but according to what I've briefly seen, you have been trying to directly read/write data on the CUDA device with a pointer. CUDA and CPU are using different address spaces. Please first operate on CPU for such manipulations before you putting everything on CUDA.

**Comment by guyuezuntinggithub** [comment]
> You have been opening and closing issues so I lost track, but according to what I've briefly seen, you have been trying to directly read/write data on the CUDA device with a pointer. CUDA and CPU are using different address spaces. Please first operate on CPU for such manipulations before putting everything on CUDA.

yes, you are right! I change device to CPU, runs ok
