### ISSUE TITLE
module 'open3d.cpu.pybind.t.pipelines' has no attribute 'slam'

### ISSUE THREAD

**Issue by guyuezuntinggithub** [isl-org/Open3D#4295]
I install open3d on windows with pip install. The version is 0.13.0 ,python version is 3.7
When I run the sample file dense_slam.py.
It occurs error "module 'open3d.cpu.pybind.t.pipelines' has no attribute 'slam'"
here is the code

import os
import numpy as np
import open3d as o3d
import time

from config import ConfigParser
from common import load_rgbd_file_names, save_poses, load_intrinsic, extract_trianglemesh, get_default_testdata

def slam(depth_file_names, color_file_names, intrinsic, config):
    n_files = len(color_file_names)
    device = o3d.core.Device(config.device)

    T_frame_to_model = o3d.core.Tensor(np.identity(4))

    model = o3d.t.pipelines.slam.Model(config.voxel_size, 16,
                                       config.block_count, T_frame_to_model,
                                       device)
    depth_ref = o3d.t.io.read_image(depth_file_names[0])
    input_frame = o3d.t.pipelines.slam.Frame(depth_ref.rows, depth_ref.columns,
                                             intrinsic, device)
    raycast_frame = o3d.t.pipelines.slam.Frame(depth_ref.rows,
                                               depth_ref.columns, intrinsic,
                                               device)

    poses = []

    for i in range(n_files):
        start = time.time()

        depth = o3d.t.io.read_image(depth_file_names[i]).to(device)
        color = o3d.t.io.read_image(color_file_names[i]).to(device)

        input_frame.set_data_from_image('depth', depth)
        input_frame.set_data_from_image('color', color)

        if i > 0:
            result = model.track_frame_to_model(input_frame, raycast_frame,
                                                config.depth_scale,
                                                config.depth_max,
                                                config.odometry_distance_thr)
            T_frame_to_model = T_frame_to_model @ result.transformation

        poses.append(T_frame_to_model.cpu().numpy())
        model.update_frame_pose(i, T_frame_to_model)
        model.integrate(input_frame, config.depth_scale, config.depth_max)
        model.synthesize_model_frame(raycast_frame, config.depth_scale,
                                     config.depth_min, config.depth_max, False)
        stop = time.time()
        print('{:04d}/{:04d} slam takes {:.4}s'.format(i, n_files,
                                                       stop - start))

    return model.voxel_grid, poses

if __name__ == '__main__':
    parser = ConfigParser()
    parser.add(
        '--config',
        is_config_file=True,
        help='YAML config file path. Please refer to default_config.yml as a '
        'reference. It overrides the default config file, but will be '
        'overridden by other command line inputs.')
    parser.add('--path_npz',
               help='path to the npz file that stores voxel block grid.',
               default='output.npz')
    config = parser.get_config()

    if config.path_dataset == '':
        config.path_dataset = get_default_testdata()

    depth_file_names, color_file_names = load_rgbd_file_names(config)
    intrinsic = load_intrinsic(config)

    if not os.path.exists(config.path_npz):
        volume, poses = slam(depth_file_names, color_file_names, intrinsic,
                             config)
        print('Saving to {}...'.format(config.path_npz))
        volume.save(config.path_npz)
        save_poses('output.log', poses)
        print('Saving finished')
    else:
        volume = o3d.t.geometry.VoxelBlockGrid.load(config.path_npz)

    mesh = extract_trianglemesh(volume, config, 'output.ply')
    o3d.visualization.draw([mesh])

**Comment by yxlao** [comment]
@guyuezuntinggithub try the latest dev wheel: http://www.open3d.org/docs/latest/getting_started.html#development-version-pip .

**Comment by guyuezuntinggithub** [comment]
> @guyuezuntinggithub try the latest dev wheel: http://www.open3d.org/docs/latest/getting_started.html#development-version-pip .

Thank you for your reply! I reinstall open3d with packs from your URL above, it occurs new error

[Open3D Error] (class std::shared_ptr<class open3d::core::DeviceHashBackend> __cdecl open3d::core::CreateDeviceHashBackend(__int64,const class open3d::core::Dtype &,const class open3d::core::SizeVector &,const class std::vector<class open3d::core::Dtype,class std::allocator<class open3d::core::Dtype> > &,const class std::vector<class open3d::core::SizeVector,class std::allocator<class open3d::core::SizeVector> > &,const class open3d::core::Device &,const enum open3d::core::HashBackendType &)) D:\a\Open3D\Open3D\cpp\open3d\core\hashmap\DeviceHashBackend.cpp:57: [CreateDeviceHashBackend]: Unimplemented device

![image](https://user-images.githubusercontent.com/63081832/141811517-d7f05b4b-e1b1-44d5-9ca1-4dbf489525a9.png)
 .

**Comment by theNded** [comment]
Since it is on windows, CUDA is not supported from pip. You need to use CPU:0 to specify the devices.

**Comment by guyuezuntinggithub** [comment]
> Since it is on windows, CUDA is not supported from pip. You need to use CPU:0 to specify the devices.

thank you for your reply! I will try it

**Comment by guyuezuntinggithub** [comment]
> Since it is on windows, CUDA is not supported from pip. You need to use CPU:0 to specify the devices.

I change the device to CPU, but it comes to another error
![image](https://user-images.githubusercontent.com/63081832/141878530-c35bd513-912c-401c-bb7b-f982bb2941bc.png)

the following is code

![image](https://user-images.githubusercontent.com/63081832/141878459-0e2fdfb5-ba5d-439b-85a6-5d5faefec176.png)

**Comment by theNded** [comment]
Did you change the default config or the loading of intrinsic? Does it work with the default setup, i.e. `python dense_slam.py --device CPU:0`(you need to run it in a cloned Open3D repo)?

**Comment by guyuezuntinggithub** [comment]
> Did you change the default config or the loading of intrinsic? Does it work with the default setup, i.e. `python dense_slam.py --device CPU:0`(you need to run it in a cloned Open3D repo)?

Yes, I did. The default file content is 
![image](https://user-images.githubusercontent.com/63081832/141883686-6ff7a2ea-c098-4848-96fd-032078c2eca8.png)
the parameters from default_intrinsics.json work well too, The debug info can confirm that
![image](https://user-images.githubusercontent.com/63081832/141884086-a6f0b267-6ad7-44cc-9546-991ad11bce06.png)
![image](https://user-images.githubusercontent.com/63081832/141884221-58ef230c-c1b2-46f6-9b4e-1314df547e84.png)

**Comment by theNded** [comment]
You have also changed the engine to `legacy`, which is not supported for now. Please fall back to `tensor`. Please first go through the examples unchanged, and make sure everything works, before you play with the configurations.

**Comment by guyuezuntinggithub** [comment]
> You have also changed the engine to `legacy`, which is not supported for now. Please fall back to `tensor`. Please first go through the examples unchanged, and make sure everything works, before you play with the configurations.

than you very much! I am a really new user. very appreciate your reply.
