### ISSUE TITLE
error C2220: 以下警告被视为错误 (编译源文件

### ISSUE THREAD

**Issue by Ryyyc** [isl-org/Open3D#4296]
**IMPORTANT: Please use the following template to report the bug.**

Before submitting:

_____

**Describe the bug**
When I used [the tutorial here](http://www.open3d.org/docs/release/compilation.html#windows) to compile Open3D on Windows 10, a lot of similar errors appeared.
```
error C2220: 以下警告被视为错误 (编译源文件
```

It may be the default settings of VS2019 or incorrect settings in some places, which caused the compilation warning level to be too high. Microsoft's explanation is [here](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2220?view=msvc-170).

**To Reproduce**

1. Clone the repository source code and create a directory
```
git clone --recursive https://github.com/intel-isl/Open3D
git submodule update --init --recursive
mkdir build && cd build
```
2. Run cmake
```
cmake -G "Visual Studio 16 2019" -A x64  ..
cmake --build . --config Release --target ALL_BUILD
```

3. See error

**Expected behavior**
Hope to get the warning level set from Open3D.

**Screenshots**
![help](https://user-images.githubusercontent.com/47767371/141782572-cd2b3250-b463-45eb-b9d4-09bd4960d41d.PNG)

**Environment (please complete the following information):**

- Operating system: Windows 10 64-bit
- Python version: Python 3.8
- Open3D version: 0.13.0 (The latest source code)
- Is this remote workstation?: no
- How did you install Open3D?: build from source Visual Studio 2019

**Comment by yxlao** [comment]
For a workaround, try disabling the C4819 warning.

Add
```
/wd4819
```

to

https://github.com/isl-org/Open3D/blob/5e4d5019596b5652e6c957cf6bb133df1396c25b/cmake/Open3DShowAndAbortOnWarning.cmake#L6-L22

**Comment by Ryyyc** [comment]
There was an error here
```
C:\Environment\Open3D\Open3D\cpp\open3d\visualization\visualizer\GuiVisualizer.cpp(682,11): fatal error C1017: 无效的整
数常量表达式 [C:\Environment\Open3D\build\cpp\open3d\visualization\visualization.vcxproj]
```
position
https://github.com/isl-org/Open3D/blob/3dca06c398a4f9dd61a7cd26607feb17a3c8121d/cpp/open3d/visualization/visualizer/GuiVisualizer.cpp#L681

I added information output in CMakeLists.txt, it is incredible that it entered the `if(WIN32)` branch, but my operating system is x64.

**Comment by Ryyyc** [comment]
> When I running command `cmake --build . --config Release --target ALL_BUILD`, there was an error here
> 
> ```
> C:\Environment\Open3D\Open3D\cpp\open3d\visualization\visualizer\GuiVisualizer.cpp(682,11): fatal error C1017: 无效的整
> 数常量表达式 [C:\Environment\Open3D\build\cpp\open3d\visualization\visualization.vcxproj]
> ```
> 
> position
> 
> https://github.com/isl-org/Open3D/blob/3dca06c398a4f9dd61a7cd26607feb17a3c8121d/cpp/open3d/visualization/visualizer/GuiVisualizer.cpp#L681
> 
> I added information output in CMakeLists.txt, it is incredible that it entered the `if(WIN32)` branch, but my operating system is x64.



I found a possibility and tried it, WIN32 was indeed used as a string.
see https://stackoverflow.com/questions/53425282/generator-expression-evaluates-win32-variable-to-true-even-not-on-windows

> In the generator expression
> ```
> $<BOOL:WIN32>
> ```
> CMake evaluates "WIN32" as a string, not as a variable. Because this string doesn't correspond to any false pattern, it is evaluated as TRUE.
> 
> You need to dereference the variable for check its value:
> ```
> $<BOOL:${WIN32}>
> ```

**Comment by Ryyyc** [comment]
Oh no, I check `WIN32` after `project(...)`, it is `1`.

**Comment by Ryyyc** [comment]
I repeated all the steps and finally succeeded, thank you very much for your help. @yxlao

**Comment by Ryyyc** [comment]
To sum up, if you compile Open3D from source code, the following error occurs:
```
error C2220: 以下警告被视为错误 (编译源文件
```
![help](https://user-images.githubusercontent.com/47767371/141782572-cd2b3250-b463-45eb-b9d4-09bd4960d41d.PNG)


try disabling the C4819 warning

Add
```
/wd4819
```
to
https://github.com/isl-org/Open3D/blob/5e4d5019596b5652e6c957cf6bb133df1396c25b/cmake/Open3DShowAndAbortOnWarning.cmake#L6-L22

**Comment by yuecideng** [comment]
Should we add this 

> For a workaround, try disabling the C4819 warning.
> 
> Add
> 
> ```
> /wd4819
> ```
> 
> to
> 
> https://github.com/isl-org/Open3D/blob/5e4d5019596b5652e6c957cf6bb133df1396c25b/cmake/Open3DShowAndAbortOnWarning.cmake#L6-L22

Should we add this by default? I used vs2022 for building open3d under windows and also encounter this problem. @yxlao

**Comment by yxlao** [comment]
> Should we add this by default? I used vs2022 for building open3d under windows and also encounter this problem. @yxlao

Yes, thanks! @yuecideng
