### ISSUE TITLE
Image.cpp:319: FilterBilateral with data type Float32 on device CPU:0 is not implemented!

### ISSUE THREAD

**Issue by guyuezuntinggithub** [isl-org/Open3D#4297]
running DenseSLAM.cpp when code runs to here as follows. It occurs title error
![image](https://user-images.githubusercontent.com/63081832/141810210-9a0f7712-8a39-4d1b-9066-09f6524d7858.png)

the following is the whole code

using namespace open3d;
using core::Tensor;
using t::geometry::Image;
using t::geometry::PointCloud;
using t::geometry::RGBDImage;

std::string device_code ="CPU:0";
utility::SetVerbosityLevel(utility::VerbosityLevel::Info);
core::Device device(device_code);
utility::LogInfo("Using device: {}", device.ToString());
std::string color_folder = "/usr/local/Open3D/rgbd_dataset_freiburg1_room/rgb";
std::string depth_folder = "/usr/local/Open3D/rgbd_dataset_freiburg1_room/depth";
std::vector<std::string> color_filenames, depth_filenames;
utility::filesystem::ListFilesInDirectory(color_folder, color_filenames);
utility::filesystem::ListFilesInDirectory(depth_folder, depth_filenames);
if (color_filenames.size() != depth_filenames.size()) {
        utility::LogError(
                "[DenseSLAM] numbers of color and depth files mismatch. "
                "Please provide folders with same number of images.");
    }
std::sort(color_filenames.begin(), color_filenames.end());
std::sort(depth_filenames.begin(), depth_filenames.end());
size_t n = color_filenames.size();
size_t iterations = n;
iterations = std::min(n, iterations);
// Intrinsics
std::string intrinsic_path = "/usr/local/Open3D/rgbd_dataset_freiburg1_room/camera.json";
camera::PinholeCameraIntrinsic intrinsic = camera::PinholeCameraIntrinsic(
            camera::PinholeCameraIntrinsicParameters::PrimeSenseDefault);
    if (intrinsic_path.empty()) {
        utility::LogWarning("Using default Primesense intrinsics");
    } else if (!io::ReadIJsonConvertible(intrinsic_path, intrinsic)) {
        utility::LogError("Unable to convert json to intrinsics.");
    }
    auto focal_length = intrinsic.GetFocalLength();
    auto principal_point = intrinsic.GetPrincipalPoint();
    Tensor intrinsic_t = Tensor::Init<double>(
            {{focal_length.first, 0, principal_point.first},
             {0, focal_length.second, principal_point.second},
             {0, 0, 1}});
    // VoxelBlock configurations
    float voxel_size = 3.f / 512.f;
    float sdf_trunc = 0.04f;
    int block_resolution = 16;
    int block_count = 10000;
// Odometry configurations
float depth_scale = 1000.f;
float depth_max = 3.f;
float depth_diff = 0.07f;

    // Initialization
       Tensor T_frame_to_model =
               Tensor::Eye(4, core::Dtype::Float64, core::Device("CPU:0"));

       t::pipelines::slam::Model model(voxel_size, sdf_trunc, block_resolution,
                                       block_count, T_frame_to_model, device);

       // Initialize frame
       Image ref_depth = *t::io::CreateImageFromFile(depth_filenames[0]);
       t::pipelines::slam::Frame input_frame(
               ref_depth.GetRows(), ref_depth.GetCols(), intrinsic_t, device);
       t::pipelines::slam::Frame raycast_frame(
               ref_depth.GetRows(), ref_depth.GetCols(), intrinsic_t, device);

       // Iterate over frames
           for (size_t i = 0; i < iterations; ++i) {
               utility::LogInfo("Processing {}/{}...", i, iterations);
               // Load image into frame
               Image input_depth = *t::io::CreateImageFromFile(depth_filenames[i]);
               Image input_color = *t::io::CreateImageFromFile(color_filenames[i]);
               input_frame.SetDataFromImage("depth", input_depth);
               input_frame.SetDataFromImage("color", input_color);

               bool tracking_success = true;
               if (i > 0) {
                   auto result =
                           model.TrackFrameToModel(input_frame, raycast_frame,
                                                   depth_scale, depth_max, depth_diff);

                   core::Tensor translation =
                           result.transformation_.Slice(0, 0, 3).Slice(1, 3, 4);
                   double translation_norm = std::sqrt(
                           (translation * translation).Sum({0, 1}).Item<double>());

                   // TODO(wei): more systematical failure check.
                   // If the overlap is too small or translation is too high between
                   // two consecutive frames, it is likely that the tracking failed.
                   if (result.fitness_ >= 0.1 && translation_norm < 0.15) {
                       T_frame_to_model =
                               T_frame_to_model.Matmul(result.transformation_);
                   } else {  // Don't update
                       tracking_success = false;
                       utility::LogWarning(
                               "Tracking failed for frame {}, fitness: {:.3f}, "
                               "translation: {:.3f}. Using previous frame's "
                               "pose.",
                               i, result.fitness_, translation_norm);
                   }
               }

               // Integrate
               model.UpdateFramePose(i, T_frame_to_model);
               if (tracking_success) {
                   model.Integrate(input_frame, depth_scale, depth_max);
               }
               model.SynthesizeModelFrame(raycast_frame, depth_scale, 0.1, depth_max,
                                          false);
           }

**Comment by reyanshsolis** [comment]
IPPICV might be missing from your system, as FilterBilateral supports Float32 for 1 and 3 channel images.
Can you check in your CMake summary if IPPICV was detected and used?
`cmake -DWITH_IPPICV = ON ..` (but this is also the default setting, so there might be some other cause for the issue as well).


You may also put debugging statement in your source code, at `cpp/open3d/t/geometry/Image.cpp` `FilterBilateral` function.
```C++
Image Image::FilterBilateral(int kernel_size,
                             float value_sigma,
                             float dist_sigma) const {
    if (kernel_size < 3) {
        utility::LogError("Kernel size must be >= 3, but got {}.", kernel_size);
    }

    static const dtype_channels_pairs npp_supported{
            {core::UInt8, 1}, {core::UInt16, 1}, {core::Float32, 1},
            {core::UInt8, 3}, {core::UInt16, 3}, {core::Float32, 3},
    };
    static const dtype_channels_pairs ipp_supported{
            {core::UInt8, 1},
            {core::Float32, 1},
            {core::UInt8, 3},
            {core::Float32, 3},
    };

    Image dst_im;
    dst_im.data_ = core::Tensor::EmptyLike(data_);
    if (data_.GetDevice().GetType() == core::Device::DeviceType::CUDA &&
        std::count(npp_supported.begin(), npp_supported.end(),
                   std::make_pair(GetDtype(), GetChannels())) > 0) {
        CUDA_CALL(npp::FilterBilateral, data_, dst_im.data_, kernel_size,
                  value_sigma, dist_sigma);
    } else if (HAVE_IPPICV &&
               data_.GetDevice().GetType() == core::Device::DeviceType::CPU &&
               std::count(ipp_supported.begin(), ipp_supported.end(),
                          std::make_pair(GetDtype(), GetChannels())) > 0) {

       utility::LogWarning(" IPPICV is there, and format is supported ");

        IPP_CALL(ipp::FilterBilateral, data_, dst_im.data_, kernel_size,
                 value_sigma, dist_sigma);
    } else {
    
       utility::LogWarning(" HAVE_IPPICV is {}", HAVE_IPPICV);

        utility::LogError(
                "FilterBilateral with data type {} on device {} is not "
                "implemented!",
                GetDtype().ToString(), GetDevice().ToString());
    }
    
    
    return dst_im;
}
```

**Comment by guyuezuntinggithub** [comment]
> IPPICV might be missing from your system, as FilterBilateral supports Float32 for 1 and 3 channel images. Can you check in your CMake summary if IPPICV was detected and used? `cmake -DWITH_IPPICV = ON ..` (but this is also the default setting, so there might be some other cause for the issue as well).
> 
> You may also put debugging statement in your source code, at `cpp/open3d/t/geometry/Image.cpp` `FilterBilateral` function.
> 
> ```c++
> Image Image::FilterBilateral(int kernel_size,
>                              float value_sigma,
>                              float dist_sigma) const {
>     if (kernel_size < 3) {
>         utility::LogError("Kernel size must be >= 3, but got {}.", kernel_size);
>     }
> 
>     static const dtype_channels_pairs npp_supported{
>             {core::UInt8, 1}, {core::UInt16, 1}, {core::Float32, 1},
>             {core::UInt8, 3}, {core::UInt16, 3}, {core::Float32, 3},
>     };
>     static const dtype_channels_pairs ipp_supported{
>             {core::UInt8, 1},
>             {core::Float32, 1},
>             {core::UInt8, 3},
>             {core::Float32, 3},
>     };
> 
>     Image dst_im;
>     dst_im.data_ = core::Tensor::EmptyLike(data_);
>     if (data_.GetDevice().GetType() == core::Device::DeviceType::CUDA &&
>         std::count(npp_supported.begin(), npp_supported.end(),
>                    std::make_pair(GetDtype(), GetChannels())) > 0) {
>         CUDA_CALL(npp::FilterBilateral, data_, dst_im.data_, kernel_size,
>                   value_sigma, dist_sigma);
>     } else if (HAVE_IPPICV &&
>                data_.GetDevice().GetType() == core::Device::DeviceType::CPU &&
>                std::count(ipp_supported.begin(), ipp_supported.end(),
>                           std::make_pair(GetDtype(), GetChannels())) > 0) {
> 
>        utility::LogInfo(" IPPICV is there, and format is supported ");
> 
>         IPP_CALL(ipp::FilterBilateral, data_, dst_im.data_, kernel_size,
>                  value_sigma, dist_sigma);
>     } else {
>     
>        utility::LogInfo(" HAVE_IPPICV is {}", HAVE_IPPICV);
> 
>         utility::LogError(
>                 "FilterBilateral with data type {} on device {} is not "
>                 "implemented!",
>                 GetDtype().ToString(), GetDevice().ToString());
>     }
>     
>     
>     return dst_im;
> }
> ```

very appreciate your reply! I will try it soon.

**Comment by guyuezuntinggithub** [comment]
@reyanshsolis  I have checked cmakelist.txt The WITH_IPPICV is ON. but when I run CMake, The IPPICV doesn't support the jetson nano 2G platform. Is there any solution to this problem?

**Comment by reyanshsolis** [comment]
Hi @guyuezuntinggithub, yes IPPICV is not supported on jetson yet, you may use the CUDA device in jetson, which will internally use NPP (comes with CUDA). 

I am closing this issue for now, but in future, we will try to add fallback kernel implementation to support functionalities if IPPICV is not available. 
Thanks!

**Comment by guyuezuntinggithub** [comment]
> Hi @guyuezuntinggithub, yes IPPICV is not supported on jetson yet, you may use the CUDA device in jetson, which will internally use NPP (comes with CUDA).
> 
> I am closing this issue for now, but in future, we will try to add fallback kernel implementation to support functionalities if IPPICV is not available. Thanks!
but I want to use this function? Do you mean that I can't use open3d to track frame to model? Or,there is other function and config?
auto result =
                       model.TrackFrameToModel(input_frame, raycast_frame,
                                               depth_scale, depth_max, depth_diff);

**Comment by reyanshsolis** [comment]
I would suggest using the `CUDA` device on Jetson. Jetson has CUDA cores, so you can use that. 
As I mentioned, it will use the NPP that comes with CUDA. 

Build Open3D with CUDA enabled, and try using `CUDA:0` instead of `CPU:0`. 
In future, we will try to add a fallback path for such cases.
