### ISSUE TITLE
point cloud registration to make comple 3d model

### ISSUE THREAD

**Issue by jrajpal5-singularity** [isl-org/Open3D#4303]
hi i am trying to make 3d model of face using realsense d435i camera.
I have tried with 18 point cloud files of face with each point cloud has 20 degree difference with adjacent point cloud.
I have tried transform matrix T = [[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]] and T = [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]] but was not getting correct alignment of face.
after that i tried the formula T = [[np.cos(angle),0,np.sin(angle),0],[0,1,0,0],[-1*np.sin(angle),0,np.cos(angle),0],[0,0,0,1]] with translation matrix pcd.translate((.465*np.sin(angle),0,.465*np.cos(angle)),relative=False) but i was getting void in the center. If i tried making a lower value than 0.465 causing the point clouds to shift in y axis(y axis is the axis of rotation).
![No6testmr00](https://user-images.githubusercontent.com/17953051/142072899-2edbb756-d809-4462-a00b-5cd0306ee682.png)
![snapshot01](https://user-images.githubusercontent.com/17953051/142073016-8e645086-04f3-484d-afb2-c0c7c3f8f34a.png)

**Comment by theNded** [comment]
What is the problem? I saw your attempts, but you didn't use any point cloud registration method right?

**Comment by jrajpal5-singularity** [comment]
I have used these transformation matrix for initialization then i have used point to plane ICP algorithm.

**Comment by theNded** [comment]
The images (esp Fig 1) show reasonable alignment. I would suggest not to mess up with the initialization and tune the ICP parameters (number of iterations, distance threshold, etc).

**Comment by jrajpal5-singularity** [comment]
i want to create a complete 3d model of face. 
For this i am rotating myself along y-axis only according to which i added initial transformation for testing.
When i use only 2 point clouds; alignment is good 
but when i add more of the point clouds to it; alignment gets disturbed.
I have also tried colored ICP algorithm and I am getting similar issue
![snapshot00](https://user-images.githubusercontent.com/17953051/142666026-9ca9f9d7-6782-48ce-bb07-77fa4b806b4c.png)

**Comment by jrajpal5-singularity** [comment]
I want to make a complete 3d model but I am getting back of the head as hollow and some images are shifted like in the image below there are 2 shoulders.
![twoshoulders00](https://user-images.githubusercontent.com/17953051/142666693-0fbc652d-8c04-4099-a884-e97e9dd8a078.png)

**Comment by theNded** [comment]
1. Realsense is noisy, minor misalignment is expected.
2. Every scan is hollow, because the sensor can only see the surface. You can use [surface reconstruction](http://www.open3d.org/docs/latest/tutorial/Advanced/surface_reconstruction.html) to create mesh and make it look less hollow, but it indeed is still hollow.
3. The better practice should be rotating the camera instead of yourself -- the registration algorithm heavily relies on the backgrounds.
4. You may use [multiway registration](http://www.open3d.org/docs/latest/tutorial/Advanced/multiway_registration.html) to register multiple point clouds and reduce artifacts.

**Comment by jrajpal5-singularity** [comment]
I have tried many approaches for alignment
And i have found without registration I am getting a result like in image 
![resultwithoutregistration00](https://user-images.githubusercontent.com/17953051/142718912-d385c75f-1228-4f7d-9157-18158518400e.png)
And with icp registration (point to plane or colored point cloud registration). one of the point cloud gets shifted upwards(in y- axis).
