### ISSUE TITLE
Need a C++ 3D reconstruction examples!  Eager!

### ISSUE THREAD

**Issue by jcyhcs** [isl-org/Open3D#4312]
hi,professor:
i work on jetson platform, i want to use this project to realize a 3D scene reconstruction, but the examples don't have any about how to do this in C++， oh, please give an examples!  HELP PLEASE!

**Comment by theNded** [comment]
This is on our timeline but would not be supported soon. You may expect to see it at 0.15 (the next release will be 0.14 though).
