### ISSUE TITLE
NumberEdit.SetLimits method sets same value vor minumum and maximum

### ISSUE THREAD

**Issue by hernot** [isl-org/Open3D#4314]
**IMPORTANT: Please use the following template to report the bug.**

Before submitting:

1. Search for [similar issues](https://github.com/isl-org/Open3D/issues).
2. For Python issues, please test with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip). It may be already fixed!
_____

**Describe the bug**

The `gui.NumberEdit.SetLimits` method sets minumum and maximum value to the same value when set to `DOUBLE` type. This issue is caused by the line 90 in [`NumberEdit`](https://github.com/isl-org/Open3D/blob/master/cpp/open3d/visualization/gui/NumberEdit.cpp) on current master branch. This line should correctly read
```
impl_->max_value = max_value
``` 

**To Reproduce**

Create a `NumberEdtit`.
call `SetLimits
check `maximum_value` and `minimum_value`
both are the same 

**Expected behavior**

`minimum_value < maximum_value`
**Environment (please complete the following information):**

- Operating system: Ubuntu 20.04 (likely any)
- Python version: 3.8 ( likely any)
- Open3D version:  0.13.0
- Is this remote workstation?: no
- How did you install Open3D?: pip (likely does not matter)
- Compiler version (if built from source): (likely does not matter)

**Comment by ssheorey** [comment]
Thanks @hernot for reporting this! PR #4588 resolves this bug.
