### ISSUE TITLE
open3d ICP gives weird results

### ISSUE THREAD

**Issue by an99990** [isl-org/Open3D#4316]
**IMPORTANT: Please use the following template to report the bug.**

Before submitting:

1. Search for [similar issues](https://github.com/isl-org/Open3D/issues).
2. For Python issues, please test with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip). It may be already fixed!
_____

**Describe the bug**
I made a small test_icp function to evalute if it was actually working and i get weird results. I saw other issues mentionning that changing the threshold would work but it doesnt in my case. I tried 0.02,0.05,2,20,50..

**To Reproduce**

```
def ICP(pcd_1, pcd_2):
    trans = o3d.pipelines.registration.registration_icp(pcd_1, pcd_2, 2)
    trans_buffer = copy.deepcopy(trans.transformation)
    # rotation array
    quat = R.from_matrix(trans_buffer[:-1, :3])
    quat = quat.as_quat()
    # translation array
    t = trans_buffer[:-1, -1]
    return quat, t
```

```
def test_ICP():
    
    first_datapoint = np.random.random_sample([500,3])
    euler_rotation_matrix = np.array([ 0.2, 0.3, 0.4 ])
    
    # w, h, c = first_datapoint.shape
    # pt = first_datapoint.reshape(w * h, c)
    pcd_1 = o3d.geometry.PointCloud()
    pcd_1.points = o3d.utility.Vector3dVector(first_datapoint)

    rotation_matrix = Rotation.from_euler('xyz', euler_rotation_matrix).as_matrix()
    rotated_datapoint_matrix = np.asarray([ 
                                           np.matmul(rotation_matrix,ee.reshape([3,1])) 
                                           for ee in first_datapoint ]).reshape(first_datapoint.shape)

    pcd_2 = o3d.geometry.PointCloud()
    pcd_2.points = o3d.utility.Vector3dVector(rotated_datapoint_matrix)
    quat_ = ICP(pcd_1, pcd_2)[0]
    assert np.allclose(euler_rotation_matrix,Rotation.from_quat(quat_).as_euler('xyz'))
```

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

- Operating system: (e.g. OSX 10.15, Ubuntu 18.04, Windows 10 64-bit)
- Python version: 3.8
- Open3D version:
- Is this remote workstation?: yes
- How did you install Open3D?:pip

**Additional context**
Please help

**Comment by theNded** [comment]
Please upload screenshots and define "weird".

**Comment by an99990** [comment]
HI @theNded 
I just tried with a threshold of 2 and for some reason it works.
Why doesnt it work with a threshold of 0.02 ? How can we decide the value of the threshold ?

this is the rotation transformation i obtain with 0.02 as a threshold :
array([ 0.00810447, -0.02537858,  0.00259127])

but with threshold of 2 I get :
array([ 0.2, 0.3, 0.4 ])
which is the right result
Thank you

**Comment by theNded** [comment]
There is no geometrical meaning in your data, so debugging threshold is randomly selecting numbers and does not have any constructive meaning for real usages. 
In real-world data, the threshold indicates the distance in meter between correspondent point pairs. 0.02 means that 'if two points are closer than 2cm, then they are regarded as a correspondent pair', and 2 means 2 meters respectively.

The issue will be closed since ICP is not targeted at registering random points with large perturbations. Please open issues when dealing with real-world data, or synthetic data with geometrical meaning.
