### ISSUE TITLE
Is “pipelines::odometry::ComputeRGBDOdometry”  a cuda version?

### ISSUE THREAD

**Issue by guyuezuntinggithub** [isl-org/Open3D#4320]
I use pipelines::odometry::ComputeRGBDOdometry in my project. And I find that it runs too slow and runs on the CPU.
Is there a Cuda version function of this function? thanks!

**Comment by theNded** [comment]
`t::pipelines::odometry` contain CUDA versions, with slightly different APIs. Docs can be found [here](http://www.open3d.org/docs/release/cpp_api/namespaceopen3d_1_1t_1_1pipelines_1_1odometry.html).
