### ISSUE TITLE
fatal error when building  on Windows "fatal error C1017"

### ISSUE THREAD

**Issue by gregary** [isl-org/Open3D#4322]
https://github.com/isl-org/Open3D/blob/d6db89582328fb75e60a3da4f952dcef0d1987eb/cpp/open3d/visualization/visualizer/GuiVisualizer.cpp#L681

D:\Open3D\cpp\open3d\visualization\visualizer\GuiVisualizer.cpp(681): fatal error C1017: invalid integer constant expression [D:\Open3D\build\cpp\open3d\visualization\visualization.vcxproj]

I think it should be` #ifdef WIN32`

**Comment by yxlao** [comment]
Thanks for reporting.
