### ISSUE TITLE
3d model surface construction

### ISSUE THREAD

**Issue by jrajpal5-singularity** [isl-org/Open3D#4324]
![No4testfinalchange1](https://user-images.githubusercontent.com/17953051/142741404-412472d4-c588-4d42-a0e2-c44a2cc5ab80.JPG)
![No4testfinalchange2](https://user-images.githubusercontent.com/17953051/142741408-943a3955-b265-4fc8-b17f-fe5f1af0811c.JPG)
![No4testfinalchange3](https://user-images.githubusercontent.com/17953051/142741409-531de5f0-1a72-4626-a900-612902f07d9b.JPG)
I have taken 6 point clouds of face from intel realsense d435i camera. Each point cloud has rotation difference of 60 degree along y-axis.
I haven't used any ICP registration algorithm since it was shifting third or fourth point cloud upwards in y-axis.
Now I just want to align adjacent point clouds on each other and remove the duplicate points in them.
I have attached some images of the result I have reached.
Kindly help.
![No4testfinal1](https://user-images.githubusercontent.com/17953051/142741268-999562cd-df31-45ea-9833-7f06bb0d164a.JPG)
![No4testfinal2](https://user-images.githubusercontent.com/17953051/142741273-d97bb97d-92f9-47e9-a30b-48f978ce282a.JPG)
![No4testfinal3](https://user-images.githubusercontent.com/17953051/142741277-21efb82a-29a3-44c3-a29f-62f824bc43c1.JPG)

**Comment by stanleyshly** [comment]
Do you have RGB and depth image pairs? I would recommend either reconstruction system, they do a good job in creating a mesh with color.

**Comment by theNded** [comment]
In #4303, I have given you suggestions of 
1. moving the **camera** instead of yourself,
2. using [multiway registration](http://www.open3d.org/docs/latest/tutorial/Advanced/multiway_registration.html)
Now @stanleyshly has also given you another suggestion of registering RGB-D images using the reconstruction system. Note it would only work with suggestion 1: you move the camera and keep yourself static, and requires more scanning (typically 100).
Please understand that multi-RGBD registration is not trivial and will not work if you play with the transformations according to some rough estimations. Please kindly consider the suggestions before repeating your question, thanks.

**Comment by jrajpal5-singularity** [comment]
I have tried multiway registration and was looking for similar approach as done by nakedlabs system (https://nakedlabs.com)
If there is still need for rotating the camera then i feel that there will be issue with realsense cameras like d415 which doesn't have IMU.
I just want to know that how can i align two point clouds with similar features eg. Two point clouds have left ear of a person. But both the point clouds show different ears even after aligning. So how can we solve this issue??

**Comment by jrajpal5-singularity** [comment]
> In #4303, I have given you suggestions of 
> 1. moving the **camera** instead of yourself,
> 2. using [multiway registration](http://www.open3d.org/docs/latest/tutorial/Advanced/multiway_registration.html)
> 
> Now @stanleyshly has also given you another suggestion of registering RGB-D images using the reconstruction system. Note it would only work with suggestion 1: you move the camera and keep yourself static, and requires more scanning (typically more than 100 frames).
> Please understand that multi-RGBD registration is not trivial and will not work if you play with the transformations according to some rough estimations. Please kindly consider the suggestions before repeating your question, thanks.

I have tried with both icp registration as well as without icp registration 
But i haven't tried with rotating the camera.
I'll also try that.
When i was trying registration like shown in the image![20211121_161812.jpg](https://user-images.githubusercontent.com/17953051/142758808-61787a11-a15e-4bf0-87b6-6ef71a99b1f0.jpg)
The point clouds are shifted along z-axis

**Comment by jrajpal5-singularity** [comment]
Hi
After a little more research I have found that by moving the camera instead of object; and by getting the odometry values; the point clouds can be aligned.
Further I want to ask if I can receive the odometry values not from camera but from some external module like microcontroller with attached IMU. Can I get a good alignment between point clouds?

**Comment by theNded** [comment]
Glad to know it works now. 
IMU is not supported in Open3D. You may refer to [GTSAM](https://gtsam.org/notes/IMU-Factor.html) for preintegration of IMU data.

Closed now. Please feel free to reopen if there are further questions.
