### ISSUE TITLE
Legacy Reconstruction With Slac Does Not Save Colored Point Cloud, but Without Slac, Point Color Is Colored

### ISSUE THREAD

**Issue by stanleyshly** [isl-org/Open3D#4325]
I'm running the legacy reconstruction system with --slac and --slac_integrate arguments selected. However, when viewing the created point cloud, it has no color, while the mesh created has color. Is this a bug, or do I need to enabled colored PCs when running open3d? The results from the standard integration does have color, even if I modify it to save a point cloud. Saving as an ASCII file, I can see that colors are being saved, but loading both into Open3D and Meshlab, no colors are loaded, making me think it is a bug with the tensor system's method of saving point clouds.
Note: I'm building from source right now.

**Comment by theNded** [comment]
SLAC is targeted at geometry refinement by deforming the projection. While the geometry can be corrected, the colors could be more blurry, so it is disabled for now. Thanks for the reminder, we shall add this to the docs.
