### ISSUE TITLE
ModuleNotFoundError: No module named 'open3d._build_config'

### ISSUE THREAD

**Issue by adamjstewart** [isl-org/Open3D#4328]
**Describe the bug**

I'm trying to install the open3d Python library from source. Although the installation succeeds, importing the package fails.

**To Reproduce**

First, install Open3D from source:
```console
$ wget https://github.com/isl-org/Open3D/archive/refs/tags/v0.13.0.tar.gz
$ tar zxvf v0.13.0.tar.gz
$ cd Open3D-0.13.0/python
$ sed -i '' 's/@PYPI_PACKAGE_NAME@/open3d/'
$ sed -i '' 's/@PROJECT_VERSION@/0.13.0/'
$ python setup.py build
$ python setup.py install --prefix=...
```
Then, try to import the library:
```console
$ python
>>> import open3d
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".../lib/python3.8/site-packages/open3d/__init__.py", line 42, in <module>
    from open3d._build_config import _build_config
ModuleNotFoundError: No module named 'open3d._build_config'
```

**Expected behavior**

I would expect the `_build_config.py` file to be installed as well if it is needed.

**Environment (please complete the following information):**

- Operating system: macOS 10.15.7
- Python version: Python 3.8.12
- Open3D version: 0.13.0
- Is this remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): Apple Clang 12.0.0

**Comment by yxlao** [comment]
I don't think we have support for `python setup.py build`.

To build from source, you'll need to follow [this instruction](http://www.open3d.org/docs/latest/compilation.html).

The minimal steps:

```bash
mkdir build
cd build
cmake ..
make install-pip-package -j$(nproc)
```

**Comment by adamjstewart** [comment]
Thanks @yxlao, I hadn't seen those docs. Yes, I can use CMake to build. Will the pip package get installed to the `-DCMAKE_INSTALL_PREFIX` or does it get installed to the Python installation directory? I'm adding a build recipe for the [Spack](https://spack.io) package manager and we want each build to be isolated from each other.

**Comment by yxlao** [comment]
`-DCMAKE_INSTALL_PREFIX` does not control python installation. It only controls the C++ library installation path.

`make install-pip-package` installs the Python library inside the current virtualenv. So you'll need to activate the virtualenv before running `cmake ..`.

**Comment by adamjstewart** [comment]
We don't use `virtualenv`, each package must be installed to a different directory. This allows you to install multiple versions of numpy with different compilers and BLAS/LAPACK libraries without each installation overwriting the previous one. I'll look at the Makefile and see if I can hack it to run `pip install --prefix` instead of `pip install` (I assume this is what it's doing).

**Comment by yxlao** [comment]
Sure. You may want to hack this file: https://github.com/isl-org/Open3D/blob/master/cpp/pybind/make_install_pip_package.cmake.
