### ISSUE TITLE
Raycast result from TSDF (GPU)

### ISSUE THREAD

**Issue by icsl-Jeon** [isl-org/Open3D#4340]
**Describe the bug**
The raycast image (rendered from mesh?) looks very noisy. It has many unfilled squares 
The below is raycast Image.
![image](https://user-images.githubusercontent.com/30062474/143226117-54ca4d40-776b-4abd-99f3-6ca3e88d105e.png).

And this is depth image
![image](https://user-images.githubusercontent.com/30062474/143226768-35ecbf78-5547-459c-ab62-0fe837522ef5.png)

* TSDF Volume
```
   auto volumePtr = (new o3d_tensor::TSDFVoxelGrid({{"tsdf", open3d::core::Dtype::Float32},
                                                {"weight", open3d::core::Dtype::UInt16},
                                                {"color", open3d::core::Dtype::UInt16}},
                                               8.f / 512.f,  0.1f, 16,
                                               4000, device_gpu));
```

* Integrate and raycast
```
            volumePtr->Integrate(depthO3d,imageO3d,intrinsic,extrinsicO3dTensor,1,5);
            auto results = volumePtr->RayCast(intrinsic,extrinsicO3dTensor,col,row,1,0.01,5.0,3,
                                              o3d_tensor::TSDFVoxelGrid::SurfaceMaskCode::ColorMap);
            *renderImagePtr  = o3d_tensor::Image(results[o3d_tensor::TSDFVoxelGrid::ColorMap]).ToLegacy();
```
I want more filled image. Could you show me the way?
Regards

**Environment (please complete the following information):**

- Operating system: (Windows 10 64-bit)
- Open3D version:
- How did you install Open3D?: (build from source)

**Comment by theNded** [comment]
Could you please switch to `t::geometry::VoxelBlockGrid`? `TSDFVoxelGrid` was a temporary development version and is deprecated now. 
`VoxelBlockGrid::RayCast(const core::Tensor &block_coords,
                                  const core::Tensor &intrinsic,
                                  const core::Tensor &extrinsic,
                                  int width,
                                  int height,
                                  const std::vector<std::string> attrs,
                                  float depth_scale,
                                  float depth_min,
                                  float depth_max,
                                  float weight_threshold)`
You would be advised to change `depth_min` to 0, `depth_max` to a large value (say 5), `weight_threshold` to 0 to keep more voxel blocks.

A [python tutorial](http://www.open3d.org/docs/latest/tutorial/t_reconstruction_system/voxel_block_grid.html) is available, and the C++ interface would be similar.

**Comment by icsl-Jeon** [comment]
Okay. I tried your advice. But something I cannot understand at all.
I spawned this, 
```
   auto volumePtr = (new o3d_tensor::VoxelBlockGrid( {"tsdf","weight","color"} ,
                                     {o3d_core::Dtype::Float32,o3d_core::Dtype::UInt16,o3d_core::Dtype::UInt16},
                                     {{1},{1},{3}},
                                      8.f / 512.f,  16,
                                      1000, device_gpu));
```
Then tried 
```
            auto blockCoord = volumePtr->GetUniqueBlockCoordinates(depthO3d,intrinsic,extrinsicO3dTensor,1,5);
            ElapseMonitor monitor("TSDF integration + register mesh"); // in Release, 2ms
            volumePtr->Integrate(blockCoord,depthO3d,imageO3d,intrinsic,extrinsicO3dTensor,1,5);

            mesh = volumePtr->ExtractTriangleMesh(-1,3.0);
            *meshPtr = mesh.ToLegacy();
```
All of the depth, intrinsic, extrinsic tensors are in CUDA:0. 
But the `GetUniqueBlockCoordinates`  complains that extrinsic matrix is not in CPU when inverting it.
I found that you use `DepthTouchCUDA`  in below along the path in case CUDA tsdf. 
```
void DepthTouch(std::shared_ptr<core::HashMap>& hashmap,
                const core::Tensor& depth,
                const core::Tensor& intrinsic,
                const core::Tensor& extrinsic,
                core::Tensor& voxel_block_coords,
                index_t voxel_grid_resolution,
                float voxel_size,
                float sdf_trunc,
                float depth_scale,
                float depth_max,
                index_t stride) {
    core::Device::DeviceType device_type = hashmap->GetDevice().GetType();

    if (device_type == core::Device::DeviceType::CPU) {
        DepthTouchCPU(hashmap, depth, intrinsic, extrinsic, voxel_block_coords,
                      voxel_grid_resolution, voxel_size, sdf_trunc, depth_scale,
                      depth_max, stride);
    } else if (device_type == core::Device::DeviceType::CUDA) {
        CUDA_CALL(DepthTouchCUDA, hashmap, depth, intrinsic, extrinsic,
                  voxel_block_coords, voxel_grid_resolution, voxel_size,
                  sdf_trunc, depth_scale, depth_max, stride);
    } else {
        utility::LogError("Unimplemented device");
    }
}
```
But the below code `InverseTransformation` wants my extrinsic to be CPU 
```
void DepthTouchCUDA(std::shared_ptr<core::HashMap> &hashmap,
                    const core::Tensor &depth,
                    const core::Tensor &intrinsics,
                    const core::Tensor &extrinsics,
                    core::Tensor &voxel_block_coords,
                    index_t voxel_grid_resolution,
                    float voxel_size,
                    float sdf_trunc,
                    float depth_scale,
                    float depth_max,
                    index_t stride) {
    core::Device device = depth.GetDevice();
    NDArrayIndexer depth_indexer(depth, 2);
    core::Tensor pose = t::geometry::InverseTransformation(extrinsics);
    TransformIndexer ti(intrinsics, pose, 1.0f);
```

Should I move all the tensors to CPU even though I am working with CUDA tsdf? 
Why did you design like this? Am I missing something?

**Comment by theNded** [comment]
Thanks for the feedback. The overall logic is that we keep small tensors on CPU (for easier manipulation) and large tensor on GPU. In other words, intrinsic and extrinsics should be on CPU anyways, and others should be on the desired device. I think we should relax this constraint and also allow small tensors on GPU.

**Comment by icsl-Jeon** [comment]
Thank you for the reply.
But the function complains that all the depth, intrinsic, extrinsic should be in the same device (mixed input combination error), which means I should also transfer the depth image to cpu from gpu to find the block coordinates :(

**Comment by theNded** [comment]
Sorry for the confusion, this should not happen. Let me investigate. I will keep you posted.

**Comment by theNded** [comment]
Sorry for the late revisit. Please refer to the new provided example. You may run and debug frame-by-frame through 
```shell
cd build
make -j8 TIntegrateRGBD
./bin/examples/TIntegrateRGBD /path/to/color/folder /path/to/depth/folder /path/to/traj.log --device CUDA:0 --raycast --debug
```

**Comment by theNded** [comment]
Closed due to inactivity. Please feel free to reopen.
