### ISSUE TITLE
ScalableTSDFVolume.integrate doesn't integrate the RGBDImage

### ISSUE THREAD

**Issue by CyrielleAlbert** [isl-org/Open3D#4342]
I have been following the example "Reconstruction system". I am stuck when trying to make the fragments. 
I have managed to get point clouds for one RGBD image but can't get a point cloud with severals RGBDImage  with the ScalableTSDFVolume. It seems like nothing happen when calling the integrate() function as it returns an empty volume even after the integration of the first RGBDImage.
Any idea of where this could come from? 
Has anyone experienced the same?
Here is the code I have (a bit different from the exemple but same problem): 
![image](https://user-images.githubusercontent.com/43926352/143267963-1f2e6688-dbbd-4efa-92ee-60acd9e550c5.png)

And here are the results for the integration of two RGBDImages: 
![image](https://user-images.githubusercontent.com/43926352/143267884-d0f7f7e8-da7c-4f2f-87fc-56f9063d5646.png)

**Comment by theNded** [comment]
There might be inconsistencies within your choice of parameters.
You set the `depth_scale=100`, which is non-conventional for RGB-D images. Which kind of data are you using (e.g. sensor, dataset).
Assuming you are using our convention to obtain depth at the meter unit after applying `depth_scale`, then `voxel_length=1` gives you huge voxels with 1-meter length. Then you use `depth_trunc=0.04`, which rejects any points that are 4cm away from the surface, a threshold way smaller than 1-meter.

So please double check your dataset setup and change parameters accordingly. Usually the only thing you need to verify and customize is `depth_scale`.

**Comment by CyrielleAlbert** [comment]
I managed to find a coefficient of 1/260 in depth_scale that "solved" the problem. I can't find in the documentation how to adapth the parameters depending on the dataset (I checked [here](http://www.open3d.org/docs/release/python_api/open3d.pipelines.integration.ScalableTSDFVolume.html#open3d.pipelines.integration.ScalableTSDFVolume)). Is there any place in the documentation where it is explained?

**Comment by theNded** [comment]
This parameter should be given in the sensor/dataset documents. Here are several examples:
- [TUM](https://vision.in.tum.de/data/datasets/rgbd-dataset/file_formats): "The depth images are scaled by a factor of 5000, i.e., a pixel value of 5000 in the depth image corresponds to a distance of 1 meter from the camera, 10000 to 2 meter distance, etc."
- [Redwood](http://redwood-data.org/indoor_lidar_rgbd/download.html): "where pixel values represent depth in millimeters"
- [Azure Kinect](https://docs.microsoft.com/en-us/azure/kinect-dk/depth-camera): "A depth map is a set of Z-coordinate values for every pixel of the image, measured in units of millimeters."
- [Real Sense L515](https://github.com/IntelRealSense/librealsense/issues/8058): " The scale for L515 is 0.00025".
So please check the source of your data provider.
