### ISSUE TITLE
Open3D reconstruction pipeline 'run_synchronization' error

### ISSUE THREAD

**Issue by nikhilgiji** [isl-org/Open3D#4345]
open3d run_synchronization.py script showing error when giving input data with sub-folders containing image and depth folders 

error: 

`
Traceback (most recent call last):
  File "synchronize_frames.py", line 111, in <module>
    run_synchronization(args)
  File "synchronize_frames.py", line 55, in run_synchronization
    depth_timestamp = int(os.path.basename(depth_files[i]).replace('-', '.').split('.')[1])
`

**Comment by theNded** [comment]
Could you please show your folder structure and your command running the script?

**Comment by nikhilgiji** [comment]
folder structure:

`dataset
├── depth
│   ├── 1000.png
│   ├── 1001.png
│   ├── 1002.png
│   ├── 1003.png 
└── image
       ├── 1000.jpg
       ├── 1001.jpg
       ├── 1002.jpg
       ├── 1003.jpg` 

running script: 

`python3 synchronize_frames.py dataset_path`

**Comment by theNded** [comment]
Your dataset is ready to use and does not require synchronization.
From the line where error has been reported, we can see that the file format is assumed to be `timestamp`-`number`.`postfix`. They are usually collected from sensors where depth and color streams that are unsynchronized.
