### ISSUE TITLE
Reconstruction Pipeline on custom data error 'no correspondences between source and target point cloud' 

### ISSUE THREAD

**Issue by nikhilgiji** [isl-org/Open3D#4346]
I have extracted 994 frames and their corresponding 16bit depth map of teeth data, I have used intel midas to generate depth map, and I have run the reconstruction pipeline and it has generated 10 fragments but it is not able to combine the fragments and generate the scene. I have run the pipeline using:

'python3 run_system.py tutorial.json --make --register --refine --integrate' 

error: 

`
Traceback (most recent call last):
  File "run_system.py", line 123, in <module>
    refine_registration.run(config)
  File "Open3D-master\Open3D-master\examples\python\reconstruction_system\refine_registration.py", line 228, in run
    make_posegraph_for_refined_scene(ply_file_names, config)
  File "Open3D-master\Open3D-master\examples\python\reconstruction_system\refine_registration.py", line 204, in make_posegraph_for_refined_scene
    register_point_cloud_pair(ply_file_names,
  File "Open3D-master\Open3D-master\examples\python\reconstruction_system\refine_registration.py", line 151, in register_point_cloud_pair
    local_refinement(source, target, transformation_init, config)
  File "Open3D-master\Open3D-master\examples\python\reconstruction_system\refine_registration.py", line 132, in local_refinement
    multiscale_icp(
  File "Open3D-master\Open3D-master\examples\python\reconstruction_system\refine_registration.py", line 101, in multiscale_icp
`
`open3d::pipelines::registration::TransformationEstimationForColoredICP::ComputeTransformation(const class open3d::geometry::PointCloud &,const class open3d::geometry::PointCloud &,const class std::vector<class Eigen::Matrix<int,2,1,0,2,1>,class std::allocator<class Eigen::Matrix<int,2,1,0,2,1> > > &) const) Open3D\cpp\open3d\pipelines\registration\ColoredICP.cpp:124: No correspondences found between source and target pointcloud.` 

I have been using intel midas to generate depth maps and then convert it into 16 bit, how to generate the config.json file for the data and how to run the reconstruction pipeline on custom data, that is depth maps generated using neural networks and not from depth scanner.

_Originally posted by @nikhilgiji in https://github.com/isl-org/Open3D/issues/4337#issuecomment-977526415_

**Comment by reyanshsolis** [comment]
are you passing coloured images as well? 
if not maybe try changing the registration method from `ColoredICP` to `PointToPlane` or `GeneralizedICP`.

**Comment by nikhilgiji** [comment]
I have used colour and depth images, I have been using intel midas to generate depth map and then convert it to 16bit and the fragements are generated in PLY format, but it is not able to register the fragments, I am not using RGB-D camera to generate depth, the reconstruction pipeline is working well on other datasets mentioned in the open3d documentation.

**Comment by CyrielleAlbert** [comment]
Do you have the .pcd (or .ply) files created after making the fragments?

**Comment by theNded** [comment]
MiDAS outputs non-metrical depth, so the fragment reconstruction could be problematic. Could you please visualize the fragments and see if they look reasonable>?

**Comment by nikhilgiji** [comment]
I have converted the MiDAS depth map to 16 bit metric depth, and the fragments look reasonable, do I need to create a new `config.json` file, currently I have edited the dataset path in the `config.json`, do I need to change any other parameters.

**Comment by theNded** [comment]
Could you please share the source and target fragments where the error was reported?

**Comment by nikhilgiji** [comment]
When changing from `ColoredICP` to `PointToPlane` the reconstruction pipeline is working, but the final scene fragment is not aligned and out of shape, it is distorted. I have attached the fragments and scene file here.
[fragments](https://drive.google.com/drive/folders/1Ufs_ywxeGUNES4rUy_QQfVTF87M4ya3H?usp=sharing) 
[scene](https://drive.google.com/drive/folders/1n5DgqgV9PVVsWPDC8bu8vePWD9stbUg-?usp=sharing) 
the fragments are generated from teeth images, but the final registered fragments is distorted, is there any other parameters that need to be changed.

**Comment by wxyelena** [comment]
i got the same issue. 

i set voxel_size=0.05, it will report : no correspondences between source and target point cloud

if i set voxel_siye = 0.025, it works. but the integrated result is not make sense.

and i also check all fragments, they all look good.

Does anyone know how to solve it?

**Comment by theNded** [comment]
@nikhilgiji first of all, MiDAS outputs **inverse depth**. I cannot recognize any reasonable 'teeth' structure in the fragments, so either you are by mistake using inverse depth, or the depth qualities are too low for reconstruction. Please confirm that.
In general the reconstruction system is designed for RGB-D sensors and does not work out-of-box with deep depth prediction networks. I believe it is still a research problem.

@wxyelena please provide more context in another issue.

**Comment by youb1649** [comment]
I got the same problem. It happened with intel realsense. 
I share the data I used.
https://drive.google.com/drive/folders/1a_s-eDr5-pTX4_yx3knKcbNS8-eDjJml?usp=drive_link
