### ISSUE TITLE
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found on Ubuntu16.04

### ISSUE THREAD

**Issue by sunjiahao1999** [isl-org/Open3D#4349]
**IMPORTANT: Please use the following template to report the bug.**

Before submitting:

1. Search for [similar issues](https://github.com/isl-org/Open3D/issues).
2. For Python issues, please test with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip). It may be already fixed!
_____

**Describe the bug**
'''import open3d''' get wrong on Ubuntu16.04 and report '''ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found ...'''
But on Ubuntu 18.04 is ok.
I have no root do change the Operating system
How to solve it? 
 

**To Reproduce**

1. python -c 'import open3d'
2. See error

**Environment (please complete the following information):**

- Operating system:Ubuntu 18.04 & Ubuntu16.04
- Python 3.8
- Open3D version: 0.13.0
- Is this remote workstation?: yes
- How did you install Open3D?: pip
- Compiler version (if built from source): gcc 7.5

**Comment by yxlao** [comment]
Hi, this is expected. The Open3D Python wheel is compiled on 18.04 and thus any Ubuntu >= 18.04 will work. On 16.04, you'll need to compile Open3D from source. See http://www.open3d.org/docs/latest/compilation.html.

**Comment by yxlao** [comment]
@sunjiahao1999 BTW, if you really want to hack around it, try:

1. Copying the missing `.so` file from Ubuntu 18.04 to the new OS.
2. Modify the `__init__.py` to load the `.so` before loading the Open3D pybind `.so`.

**Comment by district10** [comment]
I built recent open3d (0.14.1) on manylinux 2014, available for python 36/37/38/39/310: <https://gist.github.com/district10/c9d3e2a353b3435a5545b80bf7aba746?permalink_comment_id=4062841#gistcomment-4062841>

Help this helpful.

**Comment by quantaji** [comment]
I also built one for 0.17.0. : https://github.com/quantaji/open3d-manylinux2014/tree/main

**Comment by zb12138** [comment]
maybe you can try open3d-python (and uninstall open3d)
