### ISSUE TITLE
Difference between Register fragments and Refine registration

### ISSUE THREAD

**Issue by ronaldpan** [isl-org/Open3D#4352]
I can not get the difference between Register fragments and Refine registration. Their code and process are similar. Could anyone explain the difference in detail.

**Comment by theNded** [comment]
`Register fragments` uses global registrations (RANSAC, fast global registration) to estimate loop closures for non-adjacent fragments (target != source + 1), and ICP for adjacent fragments (target == source + 1). Then a pose graph is constructed and solved. 
This pose graph is redundant and erroneous. Robust solver filters inconsistent loop closures (edges) and outputs a pruned pose graph with relatively more reliable edge measurements.
`Refine registration` then takes in this pruned pose graph. Now that we have good initialization, we perform ICP on **all edges**, including non-adjacent fragments. Another pose graph optimization gives the final poses for all fragments.
