### ISSUE TITLE
Open3D crashes with exit code -1073740771 (0xC000041D) when creating a new window (visualization.gui module) on Windows 10

### ISSUE THREAD

**Issue by seanloo98** [isl-org/Open3D#4353]
**Describe the bug**
Open3D crashes on Windows 10 with the message "Process finished with exit code -1073740771 (0xC000041D)" when I try to create a new window using a gui button/menu callback.

**To Reproduce**

1. Copy this test code

```
import open3d as o3d
import open3d.visualization.gui as gui

class Test:
    def __init__(self):
        self.window = gui.Application.instance.create_window("Test Window", 500, 200)
        vertlayout = gui.Vert()
        addwindowbutton = gui.Button("Add Window")
        addwindowbutton.set_on_clicked(self._add_window)
        vertlayout.add_stretch()
        vertlayout.add_child(addwindowbutton)
        vertlayout.add_stretch()
        self.window.add_child(vertlayout)

    def _add_window(self):
        self.new_window = gui.Application.instance.create_window("Test New Window", 200,100)

if __name__ == "__main__":
    gui.Application.instance.initialize()
    Test()
    gui.Application.instance.run()
```

2. Run
3. Click on the 'Add Window' button.
4. Script crashes with message: "Process finished with exit code -1073740771 (0xC000041D)"

**Expected behavior**
Another window created and program doesn't crash.

**Environment (please complete the following information):**

- Operating system: Windows 10 64-bit
- Python version: Python 3.8.10
- Open3D version: tested on both version 0.13.0 & latest development version (0.13.0+c4c7908)
- Is this remote workstation?: no
- How did you install Open3D?: pip
- Compiler version (if built from source): -

**Additional context**
This process/script works completely fine when running on Ubuntu 20.04 LTS (64-bit)

Please let me know if you need anymore information.

**Comment by seanloo98** [comment]
this is solved with the `gui.Application.instance.post_to_main_thread()` function.

**Comment by JuanIgnacioCG** [comment]
> this is solved with the `gui.Application.instance.post_to_main_thread()` function.

pardon, but where or how should be the post_to_main_thread be used?

**Comment by Zhouwudexiazhou** [comment]
> this is solved with the `gui.Application.instance.post_to_main_thread()` function.
hey, bro.where does the code 'gui.Application.instance.post_to_main_thread()' function in your code:import open3d as o3d
import open3d.visualization.gui as gui

class Test:
    def __init__(self):
        self.window = gui.Application.instance.create_window("Test Window", 500, 200)
        vertlayout = gui.Vert()
        addwindowbutton = gui.Button("Add Window")
        addwindowbutton.set_on_clicked(self._add_window)
        vertlayout.add_stretch()
        vertlayout.add_child(addwindowbutton)
        vertlayout.add_stretch()
        self.window.add_child(vertlayout)

    def _add_window(self):
        self.new_window = gui.Application.instance.create_window("Test New Window", 200,100)

if __name__ == "__main__":
    gui.Application.instance.initialize()
    Test()
    gui.Application.instance.run()? 
my code :from . import gui
from . import O3DVisualizer


def draw(geometry=None,
         title="Open3D",
         width=1024,
         height=768,
         actions=None,
         lookat=None,
         eye=None,
         up=None,
         field_of_view=60.0,
         intrinsic_matrix=None,
         extrinsic_matrix=None,
         bg_color=(1.0, 1.0, 1.0, 1.0),
         bg_image=None,
         ibl=None,
         ibl_intensity=None,
         show_skybox=None,
         show_ui=None,
         raw_mode=False,
         point_size=None,
         line_width=None,
         animation_time_step=1.0,
         animation_duration=None,
         rpc_interface=False,
         on_init=None,
         on_animation_frame=None,
         on_animation_tick=None,
         non_blocking_and_return_uid=False,
         run_one = False,
         save_image=None):
         gui.Application.instance.initialize()
    w = O3DVisualizer(title, width, height)
    w.set_background(bg_color, bg_image)

    if actions is not None:
        for a in actions:
            w.add_action(a[0], a[1])

    if point_size is not None:
        w.point_size = point_size

    if line_width is not None:
        w.line_width = line_width

    def add(g, n):
        if isinstance(g, dict):
            w.add_geometry(g)
        else:
            w.add_geometry("Object " + str(n), g)

    n = 1
    if isinstance(geometry, list):
        for g in geometry:
            add(g, n)
            n += 1
    elif geometry is not None:
        add(geometry, n)

    w.reset_camera_to_default()  # make sure far/near get setup nicely
    if lookat is not None and eye is not None and up is not None:
        w.setup_camera(field_of_view, lookat, eye, up)
    elif intrinsic_matrix is not None and extrinsic_matrix is not None:
        w.setup_camera(intrinsic_matrix, extrinsic_matrix, width, height)

    w.animation_time_step = animation_time_step
    if animation_duration is not None:
        w.animation_duration = animation_duration

    if show_ui is not None:
        w.show_settings = show_ui

    if ibl is not None:
        w.set_ibl(ibl)

    if ibl_intensity is not None:
        w.set_ibl_intensity(ibl_intensity)

    if show_skybox is not None:
        w.show_skybox(show_skybox)

    if rpc_interface:
        w.start_rpc_interface(address="tcp://127.0.0.1:51454", timeout=10000)

        def stop_rpc():
            w.stop_rpc_interface()
            return True

        w.set_on_close(stop_rpc)

    if raw_mode:
        w.enable_raw_mode(True)

    if on_init is not None:
        on_init(w)
    if on_animation_frame is not None:
        w.set_on_animation_frame(on_animation_frame)
    if on_animation_tick is not None:
        w.set_on_animation_tick(on_animation_tick)

    gui.Application.instance.add_window(w)

    if save_image is not None:
        w.export_current_image(save_image)

    if not run_one:
        if non_blocking_and_return_uid:
            return w.uid
        else:
            gui.Application.instance.run()
    else:
        while gui.Application.instance.run_one_tick():
            w.close()
        gui.Application.instance.quit().
why i close the window and quit the gui.application when i call draw funtion with the :o3d.visualization.draw(
                geometry=[{
                    "name": "pcd",
                    "geometry": pcd
                }],
                title="3D Vis",
                width=1280,
                height=720,
                lookat=np.array(center, dtype=np.float32),
                eye=np.array(eye, dtype=np.float32),
                up=np.array([0.0, 1.0, 0.0], dtype=np.float32),
                field_of_view=60.0,
                bg_color=(255.0, 255.0, 255.0, 1.0),
                show_skybox=False,
                point_size=2,
                run_one=True,
                save_image=out_path
            ), it also will crashes with exit code  -1073740771 (0xC000041D)?w.close() and quit() funtion didn't work?
