### ISSUE TITLE
Animating point clouds on webrtc

### ISSUE THREAD

**Issue by anom1267839** [isl-org/Open3D#4357]
is it possible to animate a pointcloud so that it updates the view on webrtc. I can't find any doc explaining how to do this. Thanks!

**Comment by yxlao** [comment]
Hi, you may take a gui example (for simplicity use a single-window example), and add 

```python
o3d.visualization.webrtc_server.enable_webrtc()
```
at the very beginning, before other Open3D calls. 

For example, 

1. Modify `examples/python/gui/video.py`
    ```diff
    diff --git a/examples/python/gui/video.py b/examples/python/gui/video.py
    index cd4dd3aad..b85c6fe4f 100644
    --- a/examples/python/gui/video.py
    +++ b/examples/python/gui/video.py
    @@ -139,6 +139,7 @@ class VideoWindow:
     
     
     def main():
    +    o3d.visualization.webrtc_server.enable_webrtc()
         app = o3d.visualization.gui.Application.instance
         app.initialize()
    ```
2. `python examples/python/gui/video.py`
3. Go to `http://localhost:8888/`
4. You shall see the animation in the browser.
