### ISSUE TITLE
Reconstruction system scene output is not clear.

### ISSUE THREAD

**Issue by berkeSuslu** [isl-org/Open3D#4365]
Hi,
My goal is to scan and mesh the human face without gaps using the Intel Realsense D455 camera. For this, I used the python version of the reconstuction system in open3d. I took about 1200 images with depth as input. While taking the images, I moved the camera and held the person I took the images still. I set the following as config settings:
```
{
    "name": "Captured frames using Realsense",
    "path_dataset": "dataset/realsense",
    "path_intrinsic": "dataset/realsense/camera_intrinsic.json",
    "max_depth": 3.0,
    "voxel_size": 0.05,
    "max_depth_diff": 0.07,
    "preference_loop_closure_odometry": 0.1,
    "preference_loop_closure_registration": 5.0,
    "tsdf_cubic_size": 3.0,
    "icp_method": "color",
    "global_registration": "ransac",
    "python_multi_threading": true
}
```
Then I ran the reconstruction system. Scanning was successful in the images that came out after the system was finished, but the details on the face are not clear.
Example of output:
![open3doutput](https://user-images.githubusercontent.com/32650453/144417715-37e1c3cf-dc2c-4f69-9acf-c10840f4be86.png)
What can I do to make this face clear?

**Comment by theNded** [comment]
The reconstruction system is better suited for the scene-level reconstruction, fine-grained appearance is not guaranteed. You may look at [colormap optimization](http://www.open3d.org/docs/release/tutorial/sensor/realsense.html?highlight=colormap%20optimization#running-the-scene-reconstruction-pipeline) to refine the details, but again face-level details cannot be guaranteed to be good.
