### ISSUE TITLE
Render snapshot of textured triangle mesh with offscreen renderer

### ISSUE THREAD

**Issue by kst179** [isl-org/Open3D#4367]
Hi, I'm trying to capture image of textured triangle mesh with offscreen renderer, but it looks like renderer cannot see any of mesh's material properties such as `triangle_uvs`, `triangle_material_ids` and `textures`. I found way to pass texture as an albedo image to mesh's material, but it wraps texture with no correspondance to given in `triangle_uvs`  coordinates.

Here is minimal example:
```python
box = o3d.io.read_triangle_mesh("crate/wooden_crate.obj")
box.compute_vertex_normals()

material = rendering.Material()
texture = np.asarray(box.textures[1]).copy()
texture = o3d.geometry.Image(texture)
material.albedo_img = texture
# "material.albedo_img = box.textures[1]" throws runtime error:
# "Unable to cast from non-held to held instance (T& to Holder<T>) (compile in debug mode for type information)"

material.aspect_ratio = 1.0
material.shader = "defaultLit"

w, h = 640, 480 

render = rendering.OffscreenRenderer(w, h)
render.scene.add_geometry("box", box, material)
render.scene.scene.set_sun_light([-1, -1, -1], [1.0, 1.0, 1.0], 100000)
render.scene.scene.enable_sun_light(True)
render.scene.show_axes(True)

aspect = h/w
s = 3

render.scene.camera.set_projection(rendering.Camera.Projection.Ortho, 
                                    -s, s, -s*aspect, s*aspect, 0.1, 200)
render.scene.camera.look_at([0, 0, 0], [100, 100, 100], [0, 0, 1])

img = render.render_to_image()
o3d.io.write_image("/tmp/test.png", img)

# for some reason freeing resources cause error:
# corrupted size vs. prev_size in fastbins
# Aborted (core dumped) 
```
And what it produces (left):
![image](https://user-images.githubusercontent.com/6316593/144418664-59b99c74-3c51-47e6-b600-e4c0aae8dd1f.png)
Right is same mesh opened in meshlab, as you can see, it actually does not has any crosshairs on the right side of the crate. Looks like the renderer select it's own strategy how to map given texture on mesh faces, and do not use UV coords.

So here is my questions: Can I somehow render image of mesh with textures and UV mappings defined with `triangle_uvs`, `triangle_material_ids`, `textures` properties? Can I do it if mesh has multiple textures? How to avoid problem with resources freeing?

**OS**: Ubuntu 20.04, x86_64
**o3d version**: 0.13.0

**Comment by errissa** [comment]
Would you please share your crate model? The version we have in the Open3D repo does not have the 'X' side of the box in the texture. That having been said the simplest way to do what you're trying to do is with the `TriangleMeshModel`:

```
import open3d as o3d
from open3d.visualization import rendering

box = o3d.io.read_triangle_model("examples/test_data/crate/crate.obj")

w, h = 640, 480•
render = rendering.OffscreenRenderer(w, h)
render.scene.add_model("box", box)
render.scene.scene.set_sun_light([-1, -1, -1], [1.0, 1.0, 1.0], 100000)
render.scene.scene.enable_sun_light(True)
render.scene.show_axes(True)

aspect = h/w
s = 3

render.scene.camera.set_projection(rendering.Camera.Projection.Ortho,•
                                    -s, s, -s*aspect, s*aspect, 0.1, 200)
render.scene.camera.look_at([0, 0, 0], [100, 100, 100], [0, 0, 1])

img = render.render_to_image()
o3d.io.write_image("/tmp/test.png", img)
```
![test](https://user-images.githubusercontent.com/3722407/146270080-f5a2acdb-e760-46c8-8548-2d11b2b7d09e.png)

**Comment by kst179** [comment]
The problem was not in just this crate render, I have more complex mesh with texture atlas and uv coords, but I cannot render it with offscreen renderer, because textures wrapped incorrectly onto this mesh (meshlab and o3d viewer can render it correctly but only in GUI window, not in image). I used this crate only as an example of my problem with minimal code. Anyway, attached my crate-for-testing in case you need it to reproduce the problem.

[crate.zip](https://github.com/isl-org/Open3D/files/7728779/crate.zip)

**Comment by errissa** [comment]
@kst179 Yes, for complex objects that have multiple materials and/or submeshes you must use `read_triangle_model` and `add_model`. Glad that worked for you!
