### ISSUE TITLE
Compile problem with invalid argument "python 3.6...<3.10" (ppcle64)

### ISSUE THREAD

**Issue by ewrfcas** [isl-org/Open3D#4377]
compile problems.
My python version is 3.7.7, but open3d fails to be complied.

CMake Error at CMakeLists.txt:236 (find_package):
  find_package called with invalid argument "3.6...<3.10"

CMake Error at CMakeLists.txt:246 (message):
  BUILD_PYTHON_MODULE=ON requires Python 3.6-3.9.  Please ensure it is in
  PATH.

**Comment by yxlao** [comment]
What is your OS? 

Could you share the output of:
```shell
cmake --version
python --version
which python
python3 --version
which pyhon3
```

**Comment by ewrfcas** [comment]
Thanks for your reply. I have solved this problem, since my cmake version is too old. But I meet another problem as 

-- Using src='https://github.com/ispc/ispc/releases/download/v1.16.1/ispc-v1.16.1-linux.tar.gz'                  [126/1918]
CMake Error at ext_ispc-subbuild/ispc/src/ext_ispc-populate-stamp/download-ext_ispc-populate.cmake:170 (message):
  Each download failed!

    error: downloading 'https://github.com/ispc/ispc/releases/download/v1.16.1/ispc-v1.16.1-linux.tar.gz' failed
          status_code: 52
          status_string: "Server returned nothing (no headers, no data)"
          log:
          --- LOG BEGIN ---
            Trying 20.205.243.166:443...

  Connected to github.com (20.205.243.166) port 443 (#0)

Can I download this package and put it to some place before the cmake?

**Comment by ewrfcas** [comment]
I fail to download almost all files in 3rdparty_downloads, can you directly provide the whole 3rdparty_downloads?

**Comment by yxlao** [comment]
ISPC won't work on ppcle64, at least it is not configured to work with Open3D. 

Can you try manually downloading the file URLs listed in `examples/test_data/download_file_list.json`? If your machine is inside some firewall, you may download it somewhere else and transfer to that machine.

**Comment by yxlao** [comment]
Closing as the original CMake issue is resolved. 
Open3D is not supported on ppcle64. Feel free to work on a solution for it and submit a pull request.

**Comment by ewrfcas** [comment]
Thanks for your reply! It is a pity, that open3d cannot work in ppcle64.
