### ISSUE TITLE
Pass intensity to PCD / PLY from numpy array 

### ISSUE THREAD

**Issue by rukie** [isl-org/Open3D#438]
I have intensity values with LIDAR information and I'd like to pass it into the PCD variable. I'm looking at the following code example, but I'm not sure how to expand this to include intensity. Previously I wrote out csv's to .xyzrgb files to pass intensity, but I'm benefiting from the binary vs ascii format. 

    # Pass xyz to Open3D.PointCloud and visualize
    pcd = PointCloud()
    pcd.points = Vector3dVector(xyz)
    write_point_cloud("../../TestData/sync.ply", pcd)

**Comment by syncle** [comment]
How about trying this?

```
intensity = np.zeros((np.size(mesh_x),3))
intensity[:,0] = np.reshape(intensity_from_velodyne,-1)
intensity[:,1] = np.reshape(intensity_from_velodyne,-1)
intensity[:,2] = np.reshape(intensity_from_velodyne,-1)
pcd.colors = Vector3dVector(intensity)
```

**Comment by rukie** [comment]
Thanks! I know you're focused on RGBD images, but it might be nice to support a 1d array for colors. There's a decent penalty for storing 6 columns of data, instead of 4.

**Comment by syncle** [comment]
That's true. We are planning potential upgrade on the data structure. I will put it to my list.

**Comment by jccurtis** [comment]
Hi @syncle, any updates on the data structure? This is a very useful feature for lidar based pointclouds. Any fields beyond `xyzrgb` are silently ignored when importing `ply` files. Our team is using `o3d` more and more but this is a particular pain point when moving away from `pcl`. Thanks!

**Comment by germanros1987** [comment]
@yxlao do you think we could take care of this?

**Comment by reyanshsolis** [comment]
@rukie
New support for custom data including intensity in pcd and ply file formats have been added for tensor-based geometry IO, which you may find in `open3d.t` namespace.

https://github.com/isl-org/Open3D/pull/4017
https://github.com/isl-org/Open3D/pull/3978

Thanks!
