### ISSUE TITLE
How to get the angle information through the normal vector？

### ISSUE THREAD

**Issue by sxjpage** [isl-org/Open3D#4380]
Hi ,
I obtained the depth map through a TOF device, after the create_from_depth_image conversion,
and estimate_normals to calculate the normal vector of the point cloud, but how do I obtain the angle of the above normal vector?
My PinholeCameraIntrinsic information as follwos:
fovy = 1.8849555921538759
fovx = 1.3439035240356338
fx = 201.14756782703273
fy = 87.18510336064331
cx= 160
cy = 120
part of points vector as follows:
-0.22777,-2.62751,3.81800
-0.87135,-2.25116,1.76171
-0.15313,2.53486,2.24721
part of normals vector as follows:
-0.12526,0.46365,0.87712
0.97476,-0.02132,0.22223
-0.21603,-0.23897,-0.94669

Thanks

**Comment by theNded** [comment]
Normals are already directional vectors in the Euclidean space. You can convert them to polar coordinates for angles.
