### ISSUE TITLE
Progressbar on PointCloud Filter Radius Outlier always on

### ISSUE THREAD

**Issue by udopa** [isl-org/Open3D#4390]
**Describe the bug**
Using cloud.remove_radius_outlier and cloud.remove_statistical_outliers from Python always produce and print a progressbar.
This was introduced in #4246 with a bool to determine whether to print the output or not. However, the input bool is not connected to the progressbar constructor. 

```cpp
PointCloud::RemoveRadiusOutliers(size_t nb_points,
                                 double search_radius,
                                 bool print_progress /* = false */) const {
...
    utility::OMPProgressBar progress_bar(points_.size(),
                                         "Remove radius outliers: ", true);
...
```
and 
```cpp
ProgressBar::ProgressBar(size_t expected_count,
                         const std::string &progress_info,
                         bool active) {
    Reset(expected_count, progress_info, active);
}

void ProgressBar::Reset(size_t expected_count,
                        const std::string &progress_info,
                        bool active) {
...
    active_ = active;
...

OMPProgressBar::OMPProgressBar(size_t expected_count,
                               const std::string &progress_info,
                               bool active)
    : ProgressBar(expected_count, progress_info, active) {}
...
```
I shortened the code to the relevant parts.

You can see the problem here: [PointCloud](https://github.com/chunibyo-wly/Open3D/blob/master/cpp/open3d/geometry/PointCloud.cpp#L512)  and in [ProgressBar](https://github.com/isl-org/Open3D/blob/master/cpp/open3d/utility/ProgressBar.cpp#L38)

**To Reproduce**
Run the following on any cloud in V0.14.1, the output should directly appear. Tested with Spyder and the IPython Console.
```python
cloud.remove_radius_outlier(nb_points=10, radius=0.1, print_progress=False)
```
**Expected behavior**
No output of a progressbar.

**Screenshots**
![image](https://user-images.githubusercontent.com/46706225/145206932-09812fec-ab01-49d5-bd24-f89a0920b2ea.png)

**Environment (please complete the following information):**

- Operating system:Ubuntu 20.04
- Python version: Python 3.9.7, IPython 7.29.0 
- Open3D version: 0.14.1
- Is this remote workstation?: no
- How did you install Open3D?: pip install open3d

**Comment by yxlao** [comment]
@udopa thanks for reporting.
