### ISSUE TITLE
Open3D reconstruction pipeline generates distorted final mesh 

### ISSUE THREAD

**Issue by nikhilgiji** [isl-org/Open3D#4394]
reconstruction pipeline when run on custom dataset, with depth map 16bit metric generates random distorted mesh. I have added the [image](https://drive.google.com/drive/folders/1B2LH_OSe96E_DfEIr_b0iFqvcc0D1VLo?usp=sharing),  [depth](https://drive.google.com/drive/folders/1RygZCoZmvSJmpwFirYSkH_A2QZQrsNeA?usp=sharing),  [fragments](https://drive.google.com/drive/folders/1IEia1CPPh4XZxSPTCbDqaSjh_hDDdK4z?usp=sharing),  [scene](https://drive.google.com/drive/folders/1p2ChUGNvqILyK6G_4wvGAon2RRCOJGqx?usp=sharing). I have generated the depth map using `MiDas` and used `Numpy` to convert it to 16 bit metric depth, if there is a problem with the depth map, how to generate correct 16bit metric depth.

**Comment by theNded** [comment]
Please see my answers in #4346.
