### ISSUE TITLE
Parallelization of VoxelGrid creation from triangle mesh

### ISSUE THREAD

**Issue by wirthro1** [isl-org/Open3D#4399]
I'm using python to voxelize an STL mesh. For this I use the method open3d.geometry.VoxelGrid.create_from_triangle_mesh. This method does not appear to be parallelized.

Would it be possible to parallelize the method? Or am I using it wrong?
The currently relevant code I use is:
`stl_mesh = o3d.io.read_triangle_mesh(stl_file)

voxel_grid = o3d.geometry.VoxelGrid.create_from_triangle_mesh(stl_mesh, voxel_size=0.5)`

Alternatively I have considered to use create_from_triangle_mesh_within_bounds to do my own parallelization.

**Comment by theNded** [comment]
This API is going to be deprecated and no further new features will be added. It is welcome to submit a PR if you are willing to contribute.
We are in the progress of shifting to the GPU accelerated `VoxelGrid`. Hopefully it will be available within 1 or 2 releases.
