### ISSUE TITLE
Make the printing of "Remove statistical outliers" optional please.

### ISSUE THREAD

**Issue by colinator** [isl-org/Open3D#4408]
Line 551 in PointCloud.cpp will print "Remove statistical outliers: [========================================] 100%" no matter what print_progress is, and that clutters up my console output. Maybe could you do:

if (print_progress) {
   ...that line...
}

**Comment by yxlao** [comment]
It has been fixed recently: https://github.com/isl-org/Open3D/pull/4391 
You can get the latest wheel at: http://www.open3d.org/docs/latest/getting_started.html#development-version-pip
