### ISSUE TITLE
Camera without RGBD

### ISSUE THREAD

**Issue by sctrueew** [isl-org/Open3D#4412]
Hi everyone,

I don't have an RGBD camera like intel realsense but I'm using a GoPro camera after the recording I extract depth with Midas(deep-learning) and save RGB and Depth frames. now I'd like to generate 3d Point cloud reconstruction like below the picture.

![image](https://user-images.githubusercontent.com/5433346/145680769-130da17b-a12e-48e1-8537-2dd481ed9438.png)

or this example:
![image](https://user-images.githubusercontent.com/5433346/145680910-66f6e3df-309f-4604-89d7-0714a0124d5d.png)

my result are:
Frame: 
![point3D1_rgb](https://user-images.githubusercontent.com/5433346/145680738-6449a02c-0ffb-49ed-8855-eae418c52cf7.jpg)

Depth normalization:
![point3D1_depth_normlized255](https://user-images.githubusercontent.com/5433346/145680740-04557604-ffcd-40aa-b662-abca0498e708.jpg)

Depth:
![point3D1_depth](https://user-images.githubusercontent.com/5433346/145680743-9f0784f7-739d-40e2-b7bc-908b31e21fee.jpg)

How can I do that?

Thanks in advance

**Comment by theNded** [comment]
The reconstruction system assumes a relatively high-quality depth map from sensors. While MiDAS provides nice visualization and reasonable depth from monocular images, according to my experience it is very likely to fail in the reconstruction system.

If you want to give it a try anyways, save the depths from the RGB images in a separate `depth` folder and follow the instructions in the tutorial. Be aware of several caveats:
1. MiDAS outputs **inverse depth**. Be sure to invert them properly.
2. MiDAS outputs **non-metric** depth on most datasets. Be aware to adjust them properly and tune `depth_scale` factor that converts them from the uint16 pixel value to the metrical value.
3. Use correct intrinsics.

**Comment by sctrueew** [comment]
@theNded Hi,

Thanks for the reply, I've put my depth frames in a folder. what example should I use? 
[https://github.com/isl-org/Open3D/blob/master/examples/python/gui/online-processing.py](https://github.com/isl-org/Open3D/blob/master/examples/python/gui/online-processing.py)
Is this example works for me?

**Comment by theNded** [comment]
You should be looking at [this tutorial](http://www.open3d.org/docs/release/tutorial/reconstruction_system/index.html).
