### ISSUE TITLE
how to use render_to_depth_image?

### ISSUE THREAD

**Issue by wxyelena** [isl-org/Open3D#4417]
Hello open3d authors, first of all thank you very much for your contribution.

`render = rendering.OffscreenRenderer(640, 480, headless=False)

render.scene.add_geometry("scene1", scene1, material_scene1)

render.scene.add_geometry("scene2", scene2, material_scene2)

render.setup_camera(fov, center, eye, up)

depth_image = render.render_to_depth_image()

color_image = render.render_to_image()`

With the above code, I placed two 3d meshes in a scene and then used render_to_image and render_to_depth_image to save the rgb image and depth image respectively (as shown below)
![581639403999_ pic_hd](https://user-images.githubusercontent.com/75186221/145827355-18a1ff1d-6f23-41d2-bc88-b33b99f4b01a.jpg)

But it seems that only the rgb image is correct, the depth image doesn't look correct.

How do I get the depth image please?

Thanks!

**Comment by errissa** [comment]
Hi @wxyelena. Can you share your scene data? Also please try the following script which shows generating color and depth images for a scene with two objects.
```
import open3d as o3d
from matplotlib import pyplot as plt

sphere = o3d.geometry.TriangleMesh.create_sphere(4.0)
sphere.compute_vertex_normals()
cylinder = o3d.geometry.TriangleMesh.create_cylinder(1.0, 4.0, 30, 4)
cylinder.compute_triangle_normals()
cylinder.translate([6, 2, 0.0])

render = o3d.visualization.rendering.OffscreenRenderer(640, 480)
mat = o3d.visualization.rendering.MaterialRecord()
mat.shader = 'defaultLit'

render.scene.add_geometry("sphere1", sphere, mat)
render.scene.add_geometry("cylinder1", cylinder, mat)
render.setup_camera(45, [0, 0, 0], [0, 0, -25.0], [0, 1, 0])

cimg = render.render_to_image()
dimg = render.render_to_depth_image()

plt.subplot(1, 2, 1)
plt.imshow(cimg)
plt.subplot(1, 2, 2)
plt.imshow(dimg)
plt.show()
```

![2021-12-14-115535_1280x1038_scrot](https://user-images.githubusercontent.com/3722407/146043960-5698015f-bd67-44db-936f-98578dac73d3.png)

**Comment by wxyelena** [comment]
> Hi @wxyelena. Can you share your scene data? Also please try the following script which shows generating color and depth images for a scene with two objects.
> 
> ```
> import open3d as o3d
> from matplotlib import pyplot as plt
> 
> sphere = o3d.geometry.TriangleMesh.create_sphere(4.0)
> sphere.compute_vertex_normals()
> cylinder = o3d.geometry.TriangleMesh.create_cylinder(1.0, 4.0, 30, 4)
> cylinder.compute_triangle_normals()
> cylinder.translate([6, 2, 0.0])
> 
> render = o3d.visualization.rendering.OffscreenRenderer(640, 480)
> mat = o3d.visualization.rendering.MaterialRecord()
> mat.shader = 'defaultLit'
> 
> render.scene.add_geometry("sphere1", sphere, mat)
> render.scene.add_geometry("cylinder1", cylinder, mat)
> render.setup_camera(45, [0, 0, 0], [0, 0, -25.0], [0, 1, 0])
> 
> cimg = render.render_to_image()
> dimg = render.render_to_depth_image()
> 
> plt.subplot(1, 2, 1)
> plt.imshow(cimg)
> plt.subplot(1, 2, 2)
> plt.imshow(dimg)
> plt.show()
> ```
> 
> ![2021-12-14-115535_1280x1038_scrot](https://user-images.githubusercontent.com/3722407/146043960-5698015f-bd67-44db-936f-98578dac73d3.png)

Thank you very much for your reply.

I found out that my wrong result was because I saved the generated image with OpenCV. OpenCV does not save float image data correctly, so after I saved the image with plt it was correct.
