### ISSUE TITLE
ProjectToRGBDImage and ProjectToDepthImage in Python?

### ISSUE THREAD

**Issue by Bastiiiiii** [isl-org/Open3D#4439]
**Is your feature request related to a problem? Please describe.**
I generated a TSDF Volume and extracted a point cloud, now I need the RGB and depth image from this point cloud.

**Describe the solution you'd like**
In the C++ Documentation I saw the functions ProjectToRGBDImage() and ProjectToDepthImage(), this is exactly what I need. Do python versions of these functions exist? How can I do this in python?

**Additional context**
The goal is to run a mask R-CNN on the RGB image and create masked/cropped point clouds of objects, on which I can run a pose estimation algorithm.

**Comment by theNded** [comment]
I have put it on my TODO list.
