### ISSUE TITLE
Incorrect visualization of texture mesh

### ISSUE THREAD

**Issue by manhha1402** [isl-org/Open3D#4444]
I visualized the texture mesh on meshlab and open3d and got different result. I think there is a bug in the visualization of open3d
With Meshlab:
![Screenshot from 2021-12-17 10-25-15](https://user-images.githubusercontent.com/20105284/146521666-dd9691af-08e9-41ee-8a21-5e31aecd718a.png)
With Open3d visualization (`o3d.visualization.draw_geometries([mesh])`):
![Screenshot from 2021-12-17 10-25-31](https://user-images.githubusercontent.com/20105284/146521703-a5968c7c-9b08-40a5-8257-131db613b6d7.png)
But I get correct visualization with open3d window when loading offline mode:
![Screenshot from 2021-12-17 13-04-05](https://user-images.githubusercontent.com/20105284/146542274-6dd83746-3d66-4012-9f22-14dfcd2c6137.png)

Do you have any idea about this issue of visualizing by Python code? 
Thank you

**Comment by yxlao** [comment]
Can you try `draw([mesh])` instead of `draw_geometries([mesh])`?

**Comment by manhha1402** [comment]
Hi @yxlao,
It worked with `draw([mesh])`. Thank you. Can I ask what is difference of 2 functions?
Another the issue that I found out when reading texture mesh from C++.
When read texture mesh with default function `open3d::io::ReadTriangleMesh`
```
open3d::geometry::TriangleMesh mesh;
open3d::io::ReadTriangleMesh("test.obj",mesh);
open3d::io::WriteTriangleMesh("result.obj",mesh);
```
This function cannot save the texture file and gives the warning:
```
[Open3D WARNING] Write PNG failed: image has no data.
[Open3D WARNING] Write OBJ successful, but failed to write texture file.
```
But the function `open3d::io::ReadTriangleMeshFromOBJ` read texture mesh correctly
```
open3d::io::ReadTriangleMeshOptions option;
open3d::io::ReadTriangleMeshFromOBJ("test.obj",mesh,option);
open3d::io::WriteTriangleMesh("result.obj",mesh);
````
I think this function uses `tinyobjloader` library as a backend and load properly
