### ISSUE TITLE
Tensorboard cannot / does not visualize Open3D plugin

### ISSUE THREAD

**Issue by liswp** [isl-org/Open3D#4455]
**Describe the bug**
Tensorboard cannot / does not visualize Open3D plugin after following official Open3D example: http://www.open3d.org/docs/release/tutorial/visualization/tensorboard_plugin.html?highlight=tensorboard#simple-geometry-sequences

**To Reproduce**
Install Tensorboard 2.7.0, Open3D 0.14.1

Following http://www.open3d.org/docs/release/tutorial/visualization/tensorboard_plugin.html?highlight=tensorboard#simple-geometry-sequences

Run: python3 -m tensorboard.main --logdir ...

OR

Run: tensorboard --logdir ...

**Expected behavior**
Tensorboard is supposed to have an Open3D tab

**Screenshots**
![image](https://user-images.githubusercontent.com/43964774/146601012-e8a8ff5e-7bf2-4da7-b638-fe958743252c.png)

**Environment (please complete the following information):**

- Operating system: OSX 11.6 or Ubuntu 20.04
- Python version: Python 3.8.2
- Open3D version: 0.14.1
- Is this remote workstation?: tried both, neither works
- How did you install Open3D?: pip install open3d

**Comment by liswp** [comment]
Just a quick follow-up, if it is not possible to understand why the open3d tab is not available, is there a working example in which open3d **is** available and everything is working? 

In that case, what is the correct version of tensorboard, linux distribution, python version, etc.?

Thank you.

**Comment by ssheorey** [comment]
Hi @liswp the Open3D for TensorBoard plugin is not available for macOS yet. It should work for any Linux distribution on which you can install the Open3D wheel. TensorBoard v2.5 - v2.7 has been tested, others may work as well.

To test your installation download and extract the summary data from https://github.com/isl-org/Open3D/blob/master/examples/test_data/test_tensorboard_plugin.zip
and test with `tensorboard --logdir test_tensorboard_plugin`

If this works correctly, please run the example from: https://github.com/isl-org/Open3D/blob/master/examples/python/gui/tensorboard_pytorch.py

and check.

**Comment by ssheorey** [comment]
Closing for now. Please reopen if things don't work.

**Comment by danielyan86129** [comment]
Hi any update to support this for Mac users? I'm running tensorboard on remote linux machine, and trying to open the page on my MacBook chrome, which didn't work. I'm using Open3D version 0.15. Thanks!

**Comment by ssheorey** [comment]
Hi @danielyan86129 you should be able to **view** Tensorboard on any OS / browser, including macOS Chrome. If not please try with the test data above. If that doesn't work, open a new issue and provide complete details of your environment and a small example summary file that didn't work for you.
