### ISSUE TITLE
support for non-uniform voxel size

### ISSUE THREAD

**Issue by ammaryasirnaich** [isl-org/Open3D#4456]
Hi, I was wondering if there is an option to create a non-uniform voxel of the grid space instead of fixed-uniform voxel_size using the `open3d.geometry.VoxelGrid` class?
I just checked the interface parameters of the open3d.geometry.VoxelGrid methods to create the voxel grid but it only accepts a single `float voxel `for all dimensions.
It will be very much appreciated for any suggestion or hint !

Thanks

**Comment by theNded** [comment]
You may take a look at Octree; at current we don't have the bandwidth to implement multi-scale voxel grids -- contribution is always welcome. Closed for now.
