### ISSUE TITLE
build python module for python 3.10.1

### ISSUE THREAD

**Issue by Rheinwalt** [isl-org/Open3D#4461]
Is there a specific reason why we can't build the python module for python 3.10.1 ?
When running cmake it fails because it expects version 3.6 - 3.9:
-- Open3D 0.14.1+96bb48c5a
-- Could NOT find Python3: Found unsuitable version "3.10.1", required range is "3.6...<3.10"

Best, A.

**Comment by yxlao** [comment]
We're waiting for PyTorch and TensorFlow to support 3.10. 

For now, we can enable Open3D to build on 3.10 by changing the CMake file. Search for "3.6...<3.10" in the code base and you'll find the line.

**Comment by Rheinwalt** [comment]
Yes, works. Builds like a charm except for this [turbojpeg issue](https://github.com/isl-org/Open3D/issues/4372). I just did a ln -s lib64 lib inside build/turbojpeg/ like suggested. Thanks!

**Comment by yxlao** [comment]
@Rheinwalt what's your OS?

**Comment by Rheinwalt** [comment]
I'm using Arch linux, but I don't believe this turbojpeg issue is related to python 3.10 so I'm closing this now.
