### ISSUE TITLE
Installation of development version through pip

### ISSUE THREAD

**Issue by Bastiiiiii** [isl-org/Open3D#4467]
**Describe the bug**
I want to install the development version, to use the new features from this [commit](https://github.com/isl-org/Open3D/commit/7a6af3ecac3a65f78566564160fddf8a2cdf8bd1). I think the installation worked, but I still can't use the functions project_to_rgbd_image and project_to_depth_image.

**To Reproduce**
I downloaded the wheel file [here](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip) for Linux (Ubuntu 20.04) and python 3.8. 
I installed the package through pip like this: 
`pip install --pre ../../Downloads/open3d-0.14.1+da463fb-cp38-cp38-manylinux_2_27_x86_64.whl`
I checked through pip list and it says: open3d  version 0.14.1+da463fb, so I guess the installation worked.

Now I try to run a small example code: 
```
import open3d as o3d
import numpy as np
import os

if __name__ == '__main__':
    path_PCLs = 'Evaluation/Eval_PCL/'
    obj: str = 'Chrome_screw' # Object Name
    scene_id = 1

    intrinsic = o3d.core.Tensor([[535.4, 0, 320.1], [0, 539.2, 247.6],
                                 [0, 0, 1]])

    pcd = o3d.io.read_point_cloud(os.path.join(path_PCLs, 'GT_PCLs', obj,  'GT_%s_scene_%s.ply' % (obj, scene_id)))

    o3d.visualization.draw([pcd])

    rgbd_reproj = pcd.project_to_rgbd_image(640, 480, intrinsic, depth_scale=5000.0, depth_max=10.0)

    print(rgbd_reproj)

```
But I get an error: 
AttributeError: 'open3d.cpu.pybind.geometry.PointCloud' object has no attribute 'project_to_rgbd_image'

**Environment (please complete the following information):**

- Operating system: Linux Ubuntu 20.04
- Python version: Python 3.8.10
- Open3D version: 0.14.1+da463fb
- Is this remote workstation?: no
- How did you install Open3D?: pip wheel

**Comment by theNded** [comment]
Please check the PR again. It is `t.io.read`, and the point cloud is in the `t.geometry.PointCloud` namespace.

**Comment by Bastiiiiii** [comment]
Sry, my fault. Anyway, thanks for the clarification!

**Comment by tan-may16** [comment]
I am getting the same error even with t.geometry.PointCloud namespace.

Error: 'open3d.cuda.pybind.t.geometry.PointCloud' object has no attribute 'project_to_depth_image'

Can anyone help?
I am also getting the same error for 'project_to_color_image'
