### ISSUE TITLE
TSDFVoxelGrid integration got empty mesh extraction

### ISSUE THREAD

**Issue by 1939938853** [isl-org/Open3D#4469]
Hello, 

I was trying to follow some examples of  point cloud extraction and mesh extraction from RGBD. For point cloud extraction it seems OK, but for mesh extraction, it seems not work. Got an empty mesh. Bellow is my code. Anything wrong?

Thank you!

`
auto depth = t::io::CreateImageFromFile("D:/git/Open3D_0.14.1/examples/test_data/RGBD/other_formats/TUM_depth.png");
    auto color = t::io::CreateImageFromFile("D:/git/Open3D_0.14.1/examples/test_data/RGBD/other_formats/TUM_color.png");
    auto intrinsic = core::Tensor::Init<double>({ { 535.4, 0, 320.1 }, { 0, 539.2, 247.6 },
        { 0, 0, 1 } });
    auto extrinsic = core::Tensor::Eye(4, core::Float32, core::Device("CPU:0"));
    float depth_scale = 5000.0f;
    float depth_max = 10.0;
    t::geometry::RGBDImage rgbd(*color, *depth);

    /// RGBD to point cloud
    
   auto pcd_t = t::geometry::PointCloud::CreateFromRGBDImage(rgbd, intrinsic, extrinsic, depth_scale, depth_max);
    auto pcd = std::make_shared<geometry::PointCloud>();
    *pcd = pcd_t.ToLegacy();
    visualization::DrawGeometries({ pcd });

    /// Depth to mesh
    
    float voxel_size = 4.0f / 512.0f;
    float sdf_trunc = 0.04f;
    t::geometry::TSDFVoxelGrid voxel_grid({ { "tsdf", core::Dtype::Float32 },
                                              { "weight", core::Dtype::UInt16 },
                                              { "color", core::Dtype::UInt16 } },
        voxel_size, sdf_trunc);
    voxel_grid.Integrate(*depth, intrinsic, extrinsic, depth_scale, depth_max);
    auto mesh = voxel_grid.ExtractSurfaceMesh();
    auto mesh_legacy = std::make_shared<geometry::TriangleMesh>(mesh.ToLegacy());
    visualization::DrawGeometries({ mesh_legacy });
`

**Comment by theNded** [comment]
It is only one frame, so points get filtered with insufficient frames. Use `voxel_grid.ExtractSurfaceMesh(-1, 0)` instead.
