### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by eldar** [isl-org/Open3D#4470]
Installing Open3D with `pip` into a conda environment does not work.

Steps to reproduce:
1. `conda create -y python=3.9 -n debug`
2. `conda activate debug`
3. `pip install open3d`

This results in the following error message:

```
ERROR: Could not find a version that satisfies the requirement open3d (from versions: none)
ERROR: No matching distribution found for open3d
```

Installation with conda still works (`conda install -y -c open3d-admin -c conda-forge open3d`)

- Operating system: CentOS 7.9
- Python version: Python 3.9
- Open3D version:
- Is this remote workstation?: yes
- How did you install Open3D?: pip

**Comment by yxlao** [comment]
Typically when this happens, it is the **name** of the `.whl` file that does not match your pip (not Python) version. It could be related to the CentOS configuration.

I would first try the following:
```bash
pip install --upgrade pip
pip install open3d
```

If that doesn't work, try the following:
Download `open3d-0.14.1-cp39-cp39-manylinux_2_27_x86_64.whl ` from: https://pypi.org/project/open3d/0.14.1/#files
Run 
```bash
# Try installing directly
pip install open3d-0.14.1-cp39-cp39-manylinux_2_27_x86_64.whl

# Try rename and install
mv open3d-0.14.1-cp39-cp39-manylinux_2_27_x86_64.whl open3d-0.14.1-cp39-cp39-manylinux_2_27_x86_64.manylinux2010_x86_64.whl 

```
Run `pip install open3d-0.14.1-cp39-cp39-manylinux_2_27_x86_64.whl`
2.3. If 2.2 doesn't work, try renaming the `whl` and reinstall
   ```
    mv open3d-0.14.1-cp39-cp39-manylinux_2_27_x86_64.whl open3d-0.14.1-cp39-cp39-manylinux_2_27_x86_64.manylinux2010_x86_64.whl 
    pip install open3d-0.14.1-cp39-cp39-manylinux_2_27_x86_64.manylinux2010_x86_64.whl 
   ```

**Comment by yxlao** [comment]
@eldar please let us know if the "rename and install" works for you. We don't have a CentOS for testing.

**Comment by eldar** [comment]
Hi @yxlao 

I tried your suggestions, after upgrading pip I still get the same error. I tried downloading and installing the wheel manually, this gives me another error message:

```
ERROR: open3d-0.14.1-cp39-cp39-manylinux_2_27_x86_64.whl is not a supported wheel on this platform.
```

**Comment by yxlao** [comment]
@eldar did you try renaming the wheel?

**Comment by eldar** [comment]
> @eldar did you try renaming the wheel?

No I have not. Which name should I give it?

**Comment by ssheorey** [comment]
Hi @eldar sorry, we do not support CentOS 7.x. The pre-built Open3D wheel will not work on it since CentOS 7.x has an older version of `glibc`. The wheel should work on CentOS 8.x. Using Open3D inside an Ubuntu 18.04+ docker container is the best option. Other users have tried building Open3D from source on CentOS, but I think that's complicated due to requirements of `filament`, one of Open3D's core dependencies for visualization.

Related: 
- https://github.com/isl-org/Open3D/issues/3762
- https://github.com/isl-org/Open3D/issues/1307

**Comment by Md23abu** [comment]
Hello @yxlao 

I'm encountering an issue while attempting to install Open3D on Windows. The error message I'm receiving is: "ERROR: Could not find a version that satisfies the requirement open3d (from versions: none) ERROR: No matching distribution found for open3d." Despite trying various methods, I haven't been able to resolve this issue. Could you please provide guidance on how to successfully install Open3D on Windows?

**Comment by Kin-Zhang** [comment]
![image](https://github.com/isl-org/Open3D/assets/35365764/94a23c6a-e118-4c87-8ec5-52a1fc6d5c8b)

I also have problems on Windows .... I try to install other pkgs which is ok with win_amd64 but open3d said not a supported wheel on this platform...
