### ISSUE TITLE
Question regarding building whl files

### ISSUE THREAD

**Issue by Roozter** [isl-org/Open3D#4471]
Hi,

I am using Open3D on the Jetson Xavier platform. I was able to successfully build it and install it from source, however it needs to be installed on multiple devices and I would prefer not to have to build it from source every time. I thought I could generate the .whl file and install it that way, but when installing it this way, when I import open3d it complains about not having the libOpen3D.so file? Is this to be expected and is there a way that I can install Open3D on multiple platforms without building from source every time?

**Comment by Roozter** [comment]
Just to be clear, I am installing with -DBUILD_SHARED_LIBS=ON and the libOoen3D.so is being generated in the open3d_install directory, it just isn't included in the whl file.

**Comment by ssheorey** [comment]
Hi @Roozter thanks for reporting this. We prefer to use static libraries to create Open3D wheels, since correctly including shared libraries in Python wheels requires an additional `auditwheel repair` step to patch the shared library. It is easier to avoid this by using static libraries instead. Do static libraries work for you?

**Comment by Roozter** [comment]
Oh I see. Static libraries are fine. Is the solution simply to have -DBUILD_SHARED_LIBS=OFF?

**Comment by yxlao** [comment]
Yes, ` -DBUILD_SHARED_LIBS=OFF` will work, and you do not need to copy `libOpen3D.so`. That's how we build other wheels for release.

Currently, with ARM systems, we do rely on dynamic OpenBLAS / LAPACK to be pre-installed in the system.

**Comment by Roozter** [comment]
Got it. Thanks for your help.
