### ISSUE TITLE
block jupyter

### ISSUE THREAD

**Issue by SamTov** [isl-org/Open3D#4474]
Is there a way to block Open3D from trying to run something through Jupyter? I want to run the O3DVisualizer but call if from a notebook. When you do this nothing will happen. Is there a way to prevent Open3D from trying to do anything with the notebook and just run normally?

**Comment by yxlao** [comment]
1. `python -c "import open3d; print(open3d)"`, get the path to the `__init__.py` file.
2. Edit `__init__.py` file, comment out:
   ```python
   open3d.visualization.webrtc_server.enable_webrtc()
   open3d.visualization.webrtc_server.disable_http_handshake()
   ```

**Comment by yxlao** [comment]
I think we can diable this behaviour by default. Future work.

**Comment by SamTov** [comment]
I think has been resolved, it now runs automatically in a seperate shell and opens a new window from Jupyter.

**Comment by vnmsklnk** [comment]
I have the same problem. Open3D version 0.17.0

**Comment by SamTov** [comment]
> I think has been resolved, it now runs automatically in a seperate shell and opens a new window from Jupyter.

I was a bit fast here. It works for me on MacOS computers but in linux it still freezes up. No idea about Windows.
