### ISSUE TITLE
O3DVisualizer Point cloud rendering issue

### ISSUE THREAD

**Issue by bgao-onet** [isl-org/Open3D#4483]
We're using O3DVisualizer (v0.13.0) to show point cloud generated from LiDAR devices, and noticed point cloud rendering issue (see the screenshots below). Basically there're random highlighted points, but `Visualizer` produces consistent points. The shader for the screenshots below is "unlitSolidColor", but the same issue occurs with "defaultUnlit" and others as well; the lighting profile is "NO_SHADOWS".

**Expected behavior**
We should **not** see the randomly highlighted points.

**Screenshots**
- See the circulated point as an example.
![lidar_viewer_windows](https://user-images.githubusercontent.com/87908675/147150236-59115494-e34c-4bd1-acda-97f91c5af749.PNG)

**Environment:**
- Operating system: Ubuntu 20.04, Windows 10 64-bit
- Python version: Python 3.8
- Open3D version: 0.13.0
- Is this remote workstation? No
- How did you install Open3D? Build from source
- Compiler version: gcc 9.3, MSVC 2019

**Comment by errissa** [comment]
Currently we use different versions of Filament (our backend rendering engine) on Windows and Linux so that may account for the difference. We are planning to synchronize Filament versions across all platforms in the next release.

If you can share the script that created these images I can investigate to see if anything else is going on here.

**Comment by bgao-onet** [comment]
@errissa , thanks for the response. I did some more tests and realized that the initial statement wasn't accurate. The issue actually occurs on both Windows 10 and Ubuntu 20.04. The reason for the inaccurate statement was because I was using a Ubuntu VM and once I tested it on an actual Ubuntu machine, the same rendering issue also occurred. So I updated the title and the report above. 

I have also tested with `visualization::Visualizer` which gives better results. So it seems some issue with Filament as you said. Please use the following code and attached point cloud file from KITTI dataset to test with both `O3DVisualizer` and `Visualizer` if they can be helpful.
[000000.zip](https://github.com/isl-org/Open3D/files/7809100/000000.zip)

```c++
#include <logging/Logging.h>
#include <open3d/geometry/PointCloud.h>
#include <open3d/visualization/gui/Application.h>
#include <open3d/visualization/rendering/Open3DScene.h>
#include <open3d/visualization/visualizer/O3DVisualizer.h>
#include <open3d/visualization/visualizer/Visualizer.h>

using namespace open3d::visualization;

static const Eigen::Vector3f CENTER_OFFSET(0.0f, 0.0f, -3.0f);
static const int WIDTH = 1024;
static const int HEIGHT = 768;
static auto logger = cppbase::logging::GetLoggerForCurrentModule();

static bool ReadPointCloudBinFile(const std::string& filename, open3d::geometry::PointCloud& pointcloud)
{
    std::ifstream file(filename.c_str(), std::ios::binary);
    if (file.is_open())
    {
        try
        {
            float buf[4];
            while (file.good())
            {
                file.read((char*)buf, sizeof(buf));
                pointcloud.points_.emplace_back(buf[0], buf[1], buf[2]);
                pointcloud.colors_.emplace_back(buf[3], buf[3], buf[3]);
            }
        } catch (...)
        {
            logger->error("Error reading point cloud file: {}", filename);
            return false;
        }
    } else
    {
        return false;
    }
    logger->debug("Read point cloud file: {} with {} points", filename, pointcloud.points_.size());

    return true;
}

int main(int argc, char** argv)
{
#ifndef NDEBUG
    logger->set_level(spdlog::level::debug);
    open3d::utility::SetVerbosityLevel(open3d::utility::VerbosityLevel::Debug);
#endif

    if (argc < 2)
    {
        logger->error("Usage: {} <pointcloud_bin_file>", argv[0]);
        return -1;
    }

    auto point_cloud_path = fs::path(argv[1]);
    if (!fs::exists(point_cloud_path))
    {
        logger->error("Point cloud file does not exist: {}", point_cloud_path);
        return -1;
    }

    // app.Initialize() has to be called before constructing any UI widgets
    auto& app = gui::Application::GetInstance();

#ifdef OPEN3D_DIR
#define STR(x) #x
#define STR_VALUE_OF(x) STR(x)
#if defined(WIN32) || defined(_WIN32) || defined(__WIN32__)
    fs::path res_path = fs::path(STR_VALUE_OF(OPEN3D_DIR)) / "../bin/Open3D/resources";
#elif defined(__linux__)
    fs::path res_path = fs::path(STR_VALUE_OF(OPEN3D_DIR)) / "../../../bin/Open3D/resources";
#endif
    if (!fs::exists(res_path))
        res_path = "resources";
    if (fs::exists(res_path))
        app.Initialize(res_path.string().c_str());
    else
        app.Initialize();
#else
    app.Initialize();
#endif

    // O3DVisualizer
    auto vis = std::make_shared<visualizer::O3DVisualizer>("O3DVisualizer", WIDTH, HEIGHT);
    vis->SetBackground({0, 0, 0, 0});
    vis->SetPointSize(1);

    // Visualizer
    Visualizer visualizer;

    auto pc = std::make_shared<open3d::geometry::PointCloud>();
    if (ReadPointCloudBinFile(point_cloud_path.string(), *pc))
    {
		pc->PaintUniformColor({1.0, 1.0, 1.0});
        app.PostToMainThread(vis.get(), [vis, pc] {
            if (!vis || !pc)
                return;

            vis->AddGeometry("pointcloud", pc)
            vis->GetScene()->GetScene()->GeometryShadows("pointcloud", false, false);
            vis->ResetCameraToDefault();
        });

        app.PostToMainThread(vis.get(), [&visualizer, pc] {
            visualizer.CreateVisualizerWindow("Visualizer", WIDTH, HEIGHT);
            auto& render_option = visualizer.GetRenderOption();
            render_option.SetPointSize(1.0);
            render_option.background_color_ = {0.0, 0.0, 0.0};
            visualizer.AddGeometry(pc);
            visualizer.Run();
        });
    }

    app.AddWindow(vis);
    vis.reset();
    app.Run();

    visualizer.DestroyVisualizerWindow();

    return 0;
}
```

**Comment by errissa** [comment]
I haven't tried your code yet but what are you expecting to see? Consistently solid white points? You probably need to disable post processing so try adding the following when setting up the `O3DVisualizer` in `PostToMainThread`:

```
vis->GetView()->SetPostProcessing(false);
```

PR #4441 Gives an example of the difference between the default rendering and rendering with no post processing.

**Comment by bgao-onet** [comment]
Thank you! It does work as expected after adding `vis->GetScene()->GetView()->SetPostProcessing(false);` I'm closing this now.

**Comment by bgao-onet** [comment]
Duplicate of #2946
