### ISSUE TITLE
Picking point on open3d_v0.14/example/draw.cpp seems not work on Windows 10 with VS2019?

### ISSUE THREAD

**Issue by 1939938853** [isl-org/Open3D#4484]
Hello,

Picking point on open3d_v0.14/example/draw.cpp seems not work on Windows 10 with VS2019? I tried to pick point on the blue and yellow objects, but nothing happened.

![image](https://user-images.githubusercontent.com/59957922/147151986-500aa05f-ea54-480e-bfa2-caf94e8e299c.png)

**Comment by errissa** [comment]
Did you `ctrl-click` to select the points?

**Comment by 1939938853** [comment]
Yes. I did the keyboard-ctrl+mouse-left-button-click.

**Comment by errissa** [comment]
Thanks for confirming. I could not reproduce this on Mac or Linux. I will test on Windows and report back.

**Comment by errissa** [comment]
@1939938853 Please try with the latest release (0.15). A picking related bug was fixed and this should no longer be an issue. If you continue to have problems feel free to reopen this issue.
