### ISSUE TITLE
It is easy to add transparency to open3d::visualization::visualizer?

### ISSUE THREAD

**Issue by 1939938853** [isl-org/Open3D#4489]
Just wonder if anyone has tried to add transparency to open3d::visualization::visualizer? Is it easy? How to? 

I know open3d::visualization::visualizer is going to be  deprecated, but the new O3DVisualizer seems still need time to be able to fully replace the legacy one.

https://www.opengl-tutorial.org/intermediate-tutorials/tutorial-10-transparency/

Thanks

**Comment by errissa** [comment]
We do no have the bandwidth within the team to add support for transparency to the legacy visualizer given that it will be deprecated. If you would like to contribute the feature I will gladly review the PR.

Please see #4060 for an example of transparency with the new visualizer.

If there are features other than those you've already reported that are missing from the new visualizer please open an issue describing the missing feature.
