### ISSUE TITLE
Working with NumPy

### ISSUE THREAD

**Issue by CarrierDiagnostics** [isl-org/Open3D#4490]
**IMPORTANT: Please use the following template to report the bug.**

Before submitting:

1. Search for [similar issues](https://github.com/isl-org/Open3D/issues).
2. For Python issues, please test with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip). It may be already fixed!
_____

**Describe the bug**
The working with numpy example ends with:
o3d.visualization.draw_geometries([img])
RuntimeError: [Open3D ERROR] [CreateCoordinateFrame] size <= 0

**To Reproduce**
Just run the tutorial, googling shows this has been an issue since march 2020

**Expected behavior**
Not to have an error in the tutorial

**Environment (please complete the following information):**

- Operating system: Win10
- Python version: 3.8.6
- Open3D version: 0.10.0.0
- Is this remote workstation?: no
- How did you install Open3D?: pip

```
import copy
import numpy as np
import open3d as o3d

if __name__ == "__main__":

    # generate some neat n times 3 matrix using a variant of sync function
    x = np.linspace(-3, 3, 401)
    mesh_x, mesh_y = np.meshgrid(x, x)
    z = np.sinc((np.power(mesh_x, 2) + np.power(mesh_y, 2)))
    z_norm = (z - z.min()) / (z.max() - z.min())
    xyz = np.zeros((np.size(mesh_x), 3))
    xyz[:, 0] = np.reshape(mesh_x, -1)
    xyz[:, 1] = np.reshape(mesh_y, -1)
    xyz[:, 2] = np.reshape(z_norm, -1)
    print('xyz')
    print(xyz)

    # Pass xyz to Open3D.o3d.geometry.PointCloud and visualize
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(xyz)
    o3d.io.write_point_cloud("sync.ply", pcd)

    # Load saved point cloud and visualize it
    pcd_load = o3d.io.read_point_cloud("sync.ply")
    o3d.visualization.draw_geometries([pcd_load])

    # convert Open3D.o3d.geometry.PointCloud to numpy array
    xyz_load = np.asarray(pcd_load.points)
    print('xyz_load')
    print(xyz_load)

    # save z_norm as an image (change [0,1] range to [0,255] range with uint8 type)
    img = o3d.geometry.Image((z_norm * 255).astype(np.uint8))
    o3d.io.write_image("sync.png", img)
    o3d.visualization.draw_geometries([img])
```

**Comment by theNded** [comment]
The problem is not reproducible in the latest version (0.14.0). Please upgrade and reopen the issue if it persists.
