### ISSUE TITLE
configargparse does not exist

### ISSUE THREAD

**Issue by luiscastroDTx** [isl-org/Open3D#4493]
- Running Ubuntu 20.04
- Installed open3d 0.14
- Trying to run the example code "Open3D/examples/python/t_reconstruction_system/dense_slam_gui.py" but getting the following error:

```bash
from config import ConfigParser
File "/home/luis/repos/Realsense_o3d_Python/Open3D/examples/python/t_reconstruction_system/config.py", line 28, in <module>
    import configargparse
ModuleNotFoundError: No module named 'configargparse'
```

**Comment by 0xZuk0** [comment]
Have you tried "pip install configargparse" ?

**Comment by theNded** [comment]
As commented above.
