### ISSUE TITLE
Hello! How to use crop_point_cloud

### ISSUE THREAD

**Issue by 459737087** [isl-org/Open3D#4504]
I've searched docs, it told me to add a json file.
**_o3d.visualization.read_selection_polygon_volume(    "../../test_data/Crop/cropped.json")_**

but  i don't know the file pattern.

**Comment by ted8201** [comment]
adding this comment to [crop point cloud tutorial](http://www.open3d.org/docs/release/tutorial/geometry/pointcloud.html#Crop-point-cloud) would be nice.

**Comment by P-polycephalum** [comment]
I have been struggling with this. What does axis_min and axis_max stand for. If they were the min and max bounds of the y axis values should be 0.56663716 and 2.55 respectively. Instead we get  	"axis_max" : 4.022921085357666, 
 	"axis_min" : -0.76341366767883301. Where did this values come from, the documentation says nothing about this json format.
