### ISSUE TITLE
A bug on point cloud RemoveStatisticalOutliers

### ISSUE THREAD

**Issue by mastaLin** [isl-org/Open3D#4506]
Open3D version == 0.13 , ubuntu 1804
When I use RemoveStatisticalOutliers or RemoveRadiusOutliers function,  I can't get the point cloud after outlier removal:
![src](https://user-images.githubusercontent.com/68329237/147561911-3f350263-a98a-430a-8b8c-4b292bf64dce.png)
![results](https://user-images.githubusercontent.com/68329237/147561920-a7717dba-27bc-4fad-9cf3-60b5ad663754.png)

As shown in pics, point cloud with 3749 points(after outlier removal) is missing , I can only obtain the point cloud after down sample.

**Comment by yxlao** [comment]
If you read `cpp/open3d/geometry/PointCloud.h`, the `RemoveRadiusOutliers` returns the down-sampled point cloud, instead of modifying the point cloud.

So, something similar to this would work:
```cpp
std::shared_ptr<PointCloud> model_downsampled;
std::vector<size_t> selected_indices;
std::tie(model_downsampled, selected_indices) = model->RemoveRadiusOutliers(xxx);
```
