### ISSUE TITLE
Illegal instruction (core dumped) [nouveau driver]

### ISSUE THREAD

**Issue by c0ffymachyne** [isl-org/Open3D#4510]
Hi,

I have just installed latest open3d 0.14 in Ubuntu 20.04 and I am getting an error during import `Illegal instruction (core dumped)`
It's a non-gpu machine only equipped with geforce GT 710 (server).

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```

`Python 3.8.10`

```
20:50:35 kernel: traps: python3[215860] trap invalid opcode ip:7f89ea2cc76e sp:7fff28e8efb0 error:0 in pybind.cpython-38-x86_64-linux-gnu.so[7f89e1c3b000+a70b000]
20:50:35 kernel: traps: python3[215860] trap invalid opcode ip:7f89ea2cc76e sp:7fff28e8efb0 error:0 in pybind.cpython-38-x86_64-linux-gnu.so[7f89e1c3b000+a70b000]
20:50:22 kernel: traps: python3[215692] trap invalid opcode ip:7f3286afb76e sp:7ffd0f6962e0 error:0 in pybind.cpython-38-x86_64-linux-gnu.so[7f327e46a000+a70b000]
```

**Comment by c0ffymachyne** [comment]
I had to downgrade pybind to get 0.11 installed and now it work although it is not latest.

**Comment by ssheorey** [comment]
Hi @c0ffymachyne thanks for reporting this. 

Is this local or remote?
Please provide graphics driver version, CUDA runtime version (output of `nvidia-smi`) and the output of `eglinfo`.
Open3D v0.14 binary wheels require CUDA 11.0+ and may not work with older CUDA. CUDA 10.1+ is supported but you will need to build from source.
Also could you test with `CUDA_VISIBLE_DEVICES=none python -W default -c "import open3d as o3d"`? This will disable the CUDA specific code.

**Comment by c0ffymachyne** [comment]
It's using nouveau driver.

**Comment by c0ffymachyne** [comment]
OK, I can try that.

**Comment by ssheorey** [comment]
Hi @c0ffymachyne to check whether this is due to the `nouveau` driver, can you:
- Disable the graphics card by removing the nouveau driver package.
- make sure that the latest mesa driver for integrated graphics (Intel / AMD) is installed.
- reboot and check the output of `eglinfo` to ensure EGL works correctly.
- Try `import open3d` and run some GUI examples.

**Comment by ssheorey** [comment]
@c0ffymachyne which CPU is it? Can you provide the output of `cat /proc/cpuinfo`?
Also, please try building the Python wheel from source and let us know if that works.

**Comment by c0ffymachyne** [comment]
Xeon X5670.

**Comment by ssheorey** [comment]
Please reopen if you still have this issue.
