### ISSUE TITLE
TypeError: 'open3d.cuda.pybind.geometry.PointCloud' object is not subscriptable

### ISSUE THREAD

**Issue by schleptech** [isl-org/Open3D#4514]
I am trying to load a PCD file to build mesh

import numpy as np
import open3d as o3d
print("modules loaded ok")

cloud = o3d.io.read_point_cloud("Aligned.pcd")

pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(cloud[:,:3])

Output:
modules loaded ok
Traceback (most recent call last):
  File "visualize.py", line 11, in <module>
    pcd.points = o3d.utility.Vector3dVector(cloud[:,:3])
TypeError: 'open3d.cuda.pybind.geometry.PointCloud' object is not subscriptable

Trying to build a mesh of a point cloud using rolling ball method

- Operating system: Ubuntu 18.04
- Python version: Python 3.6.9
- Open3D version:
- Is this remote workstation?: no
- How did you install Open3D?: (build from source)
- Compiler version (if built from source): gcc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0

**Comment by ssheorey** [comment]
The error message is correct. If you want to slice the PointCloud, you have to convert the data to Numpy arrays first (e.g. with Numpy `asarray()`), slice it and then create a new PointCloud.
