### ISSUE TITLE
Voxel to Mesh

### ISSUE THREAD

**Issue by karansapra** [isl-org/Open3D#4515]
**Is your feature request related to a problem? Please describe.**
I am not sure if this exists but I am wondering why we don't have support for a voxel to mesh using marching cube. Feel like going from voxel to mesh should be feasible.

**Describe the solution you'd like**
Given a voxel, it should create a 3d mesh using a marching cube or if not that generate mesh representing voxels that can be loaded into other software.

**Comment by theNded** [comment]
Please refer to the [Voxel Block Grid](http://www.open3d.org/docs/release/tutorial/t_reconstruction_system/voxel_block_grid.html). Notice that it is still under construction, more features (switching between dense and sparse features) will be added.

**Comment by seghier** [comment]
Hi @theNded 
How to use this [Voxel Block Grid](http://www.open3d.org/docs/release/tutorial/t_reconstruction_system/voxel_block_grid.html). 
to convert Voxel to mesh?
`voxel_grid = o3d.geometry.VoxelGrid.create_from_point_cloud(pcd,voxel_size=size)`
