### ISSUE TITLE
Read PLY failed: A polygon in the mesh could not be decomposed into triangles.

### ISSUE THREAD

**Issue by c0ffymachyne** [isl-org/Open3D#4517]
Hi, 

I am getting below error in my python application but open3d viewer is loading the file fine. The file was exported from instant-meshes application.

`mesh = o3d.io.read_triangle_mesh(filepath)`

`'0.14.1'`

[Open3D WARNING] Read PLY failed: A polygon in the mesh could not be decomposed into triangles.
RPly: Aborted by user
[Open3D WARNING] Read PLY failed: unable to read file: 002311.ply
[Open3D WARNING] geometry::TriangleMesh appears to be a geometry::PointCloud (only contains vertices, but no triangles).

**Comment by reyanshsolis** [comment]
may you please share the file used?

**Comment by reyanshsolis** [comment]
@c0ffymachyne I cannot confirm the issue without the file. I request you to share the files used if possible.

**Comment by HospitableHost** [comment]
Same error

**Comment by zjwzcx** [comment]
Same error. I found that my mesh file consists of polygons instead of three-vertex face. Thus, I solved it through transforming my mesh into the mesh without polygons.

**Comment by vivekmadhavaram** [comment]
> Same error. I found that my mesh file consists of polygons instead of three-vertex face. Thus, I solved it through transforming my mesh into the mesh without polygons.

Can you please tell how to transform mesh?

**Comment by vivekmadhavaram** [comment]
@zjwzcx Can you please tell how to transform mesh?

**Comment by zjwzcx** [comment]
> @zjwzcx Can you please tell how to transform mesh?

I use MeshLab to transform.

**Comment by LiangXu123** [comment]
> > @zjwzcx Can you please tell how to transform mesh?
> 
> I use MeshLab to transform.

Could you please tell exactly how to transform this?

**Comment by zjwzcx** [comment]
> transforming my mesh into the mesh without polygons.

Meshlab:  Filters > Remeshing, Simplification and Reconstruction > Turn into a Pure-Triangular mesh
