### ISSUE TITLE
Is it possible to add nonrigid icp to open3d ?

### ISSUE THREAD

**Issue by c0ffymachyne** [isl-org/Open3D#4518]
For registering deforming meshes.

**Comment by theNded** [comment]
Unfortuantely we don't have the bandwidth to develop that. Please feel free to contribute by making PRs.

Simultaneous Localization and Calibration (SLAC) module has done a similar job for non-rigid distortion registration, but the documentation is not ready. You may refer to the implementation if you are interested: http://www.open3d.org/docs/release/python_api/open3d.t.pipelines.slac.html

**Comment by c0ffymachyne** [comment]
Thank you for you response !
