### ISSUE TITLE
FastGlobalRegistrationBasedOnFeatureMatching sometime fail

### ISSUE THREAD

**Issue by hungmiu** [isl-org/Open3D#4522]
**IMPORTANT: Please use the following template to report the bug.**

Describe the bug

Sometimes, when I use FastGlobalRegistrationBasedOnFeatureMatching for registering two pointclouds. It fails. And a message box appears "vector out of range".

I check the code, I found that at the line 74 of file FastGlobalRegistration.cpp
if (corres_ji[ij.second] == ij.first) corres_cross.push_back(ij);
some time ij.second = -1.

Please add a condition to check valid ij.second.

Thank you.

**Comment by ssheorey** [comment]
Hi @hungmiu thanks for reporting this. Can you provide the code and data that can produce this error? That will help us reproduce it and debug it faster.

**Comment by hungmiu** [comment]
> Hi @hungmiu thanks for reporting this. Can you provide the code and data that can produce this error? That will help us reproduce it and debug it faster.

This is sample code and data.
Running the function 1 time, the error may not appear but run 1000 times, you can see the error.


[RegistrationRANSAC.zip](https://github.com/isl-org/Open3D/files/7797284/RegistrationRANSAC.zip)

Thanks.
