### ISSUE TITLE
Where is the origin and the axis of the coordinate system in the Reconstructed PLY file ?  How to crop the point cloud with ArUco code?

### ISSUE THREAD

**Issue by AnsunWu** [isl-org/Open3D#4526]
Hello,

I'm using the OPEN 3D library and an intel D435 camera to reconstruct the point cloud of a scene of my office desk. 

After several attempts of reconstruction, the results are decent. But the coordinate system for every reconstructed point clouds  are different. Could you please tell me where is the **default** origin and the axis of the coordinate system of the reconstructed point cloud?

I went through all the tutorial of the OPEN 3D website, I'm trying to use the ArUco code to corp the point cloud data, but I still dont have a hint about how to do it...Could you please give me some advice?

Thank you so much! 

![选区_044](https://user-images.githubusercontent.com/61506167/147966812-d3f5c810-2e76-4b0d-a110-2e65f787aa4d.png)

**Comment by theNded** [comment]
The default coordinate system is set by the 1st frame's camera pose, which is kind of arbitrary. Semantic info and/or gravity may help determine the natural coordinate system, but it is out of the scope of our reconstruction system as of now. Please feel free to contribute if you have a good idea how.
