### ISSUE TITLE
TriangleMesh::CreateFromPointCloudBallPivoting is more than 10 times slower than old version Open3D v0.11.2?

### ISSUE THREAD

**Issue by 1939938853** [isl-org/Open3D#4533]
Hello,

Recently I tried to TriangleMesh::CreateFromPointCloudBallPivoting with Open3D v0.13 and v0.14.1. Both are more than 10 times slower than the old verion v0.11.2.

My code is exactly the same, see below. What can be the problem? 

By the way, what is the fastest way to create mesh from point cloud with Open3D?

Thank you!

`
auto distance = pcd->ComputeNearestNeighborDistance();
    auto n = distance.size();
    double dist_average = 0.0;
    if (n != 0) {
        dist_average = accumulate(distance.begin(), distance.end(), 0.0) / n;
    }
    double radius = 1.5 * dist_average;
    std::vector<double> radii = { radius, radius * 1 };
    std::shared_ptr<geometry::TriangleMesh> mesh;
    {
        utility::ScopeTimer timer("Create mesh");
        mesh = geometry::TriangleMesh::CreateFromPointCloudBallPivoting(*pcd, radii);
    }
`
Open3d v0.13
![image](https://user-images.githubusercontent.com/59957922/148044660-df2ba41b-372a-478f-a745-be70d9eed58c.png)

Open3d v0.11.2
![image](https://user-images.githubusercontent.com/59957922/148044824-31c95f9a-d485-4749-85a0-3efacfdc6034.png)

**Comment by 1939938853** [comment]
I checked the source code of SurfaceReconstructionBallPivoting.cpp on both versions of v0.11.2 and v0.14.1. The only changes of the new version, is that utility::LogError added at two places. But from my console output, no error message was shown.

Open3D new version (since v0.13), point cloud normal estimation seems also slow. Can it be something becoming worse in the "open3d\core"?

Thank you!

**Comment by 1939938853** [comment]
I tested Open3D v0.12. The running speed for SurfaceReconstructionBallPivoting is OK.

So it is from Open3D v0.13.0, the running speed for SurfaceReconstructionBallPivoting was dramatically (> 10 times) slowed down.

**Comment by reyanshsolis** [comment]
Hi @1939938853 thanks for pointing out this issue. I can reproduce the same. 

Till now I have narrowed down that function `BallPivoting::FindCandidateVertex` in `cpp/open3d/geometry/SurfaceReconstructionBallPivoting.cpp` is 10x slow between current `master` and `v0.12.0`.

**Comment by reyanshsolis** [comment]
Found the issue. 
It's `LogDebug`, causing the performance issue. I will try to investigate further and try to resolve the same. 

Removing all the `LogDebug` in `FindCandidateVertex` function (both in current master and v0.12.0), makes the pipeline in v0.13+ 10x slower.

**Comment by reyanshsolis** [comment]
Followed up discussion on Issue: #4595.
