### ISSUE TITLE
TSDF_Integration TypeError: compute_unique_block_coordinates(): incompatible function arguments. 

### ISSUE THREAD

**Issue by szx0112** [isl-org/Open3D#4541]
I am using Open3d 0.14.1. And I got the type error issue when calling `vbg.compute_unique_block_coordinates()` function as in the [TSDF_integration](http://www.open3d.org/docs/latest/tutorial/t_reconstruction_system/integration.html) page.

```
TypeError: compute_unique_block_coordinates(): incompatible function arguments. The following argument types are supported:
    1. (self: open3d.cuda.pybind.t.geometry.VoxelBlockGrid, depth: open3d.cuda.pybind.t.geometry.Image, intrinsic: open3d.cuda.pybind.core.Tensor, extrinsic: open3d.cuda.pybind.core.Tensor, depth_scale: float = 1000.0, depth_max: float = 3.0, trunc_voxel_multiplier: float = 4.0) -> open3d.cuda.pybind.core.Tensor
    2. (self: open3d.cuda.pybind.t.geometry.VoxelBlockGrid, pcd: open3d.cuda.pybind.t.geometry.PointCloud, trunc_voxel_multiplier: float = 4.0) -> open3d.cuda.pybind.core.Tensor

Invoked with: <open3d.cuda.pybind.t.geometry.VoxelBlockGrid object at 0x7f780b652f30>, Image of size 640x360, with 1 channels.
Use numpy.asarray to access buffer data., PinholeCameraIntrinsic with width = 640 and height = 360.
Access intrinsics with intrinsic_matrix., array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]]), 1000.0, 0.7; kwargs: trunc_voxel_multiplier=4.0
```
Here is my input dataset type:
**vbg**: <class 'open3d.cuda.pybind.t.geometry.VoxelBlockGrid'>  # defined based on TSDF_Integration tutorial
**depth**:<class 'open3d.cuda.pybind.geometry.Image'>  # open3d depth image
**intrinsic**:<class 'open3d.cuda.pybind.camera.PinholeCameraIntrinsic'>  # o3d camera intrinsic
**extrinsic**:<class 'numpy.ndarray'>    # 4x4 transofmration matrix
**depth_scale**:<class 'float'>   
**depth_max**:<class 'float'>

I also use o3c.Tensor() to change the intrinsic and extrinsic to `open3d.cuda.pybind.core.Tensor` class. This matches the required data type in  `compute_unique_block_coordinates()`. But then I got the following errors:

```
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. open3d.cuda.pybind.core.Tensor(np_array: numpy.ndarray, dtype: Optional[open3d.cuda.pybind.core.Dtype] = None, device: Optional[open3d.cuda.pybind.core.Device] = None)
    2. open3d.cuda.pybind.core.Tensor(scalar_value: bool, dtype: Optional[open3d.cuda.pybind.core.Dtype] = None, device: Optional[open3d.cuda.pybind.core.Device] = None)
    3. open3d.cuda.pybind.core.Tensor(scalar_value: int, dtype: Optional[open3d.cuda.pybind.core.Dtype] = None, device: Optional[open3d.cuda.pybind.core.Device] = None)
    4. open3d.cuda.pybind.core.Tensor(scalar_value: float, dtype: Optional[open3d.cuda.pybind.core.Dtype] = None, device: Optional[open3d.cuda.pybind.core.Device] = None)
    5. open3d.cuda.pybind.core.Tensor(shape: list, dtype: Optional[open3d.cuda.pybind.core.Dtype] = None, device: Optional[open3d.cuda.pybind.core.Device] = None)
    6. open3d.cuda.pybind.core.Tensor(shape: tuple, dtype: Optional[open3d.cuda.pybind.core.Dtype] = None, device: Optional[open3d.cuda.pybind.core.Device] = None)

Invoked with: PinholeCameraIntrinsic with width = 640 and height = 360.
Access intrinsics with intrinsic_matrix.
```

Any comment is appreciated.

**Comment by theNded** [comment]
As the error log indicated, `Tensor` does not accept `PinholeCameraIntrinsic` for construction. You can try `o3d.core.Tensor(intrinsic.intrinsic_matrix, o3d.core.Dtype.Float64)`.

**Comment by szx0112** [comment]
Thanks for the quick reply @theNded. I modified the code `frustum_block_coords = vbg.compute_unique_block_coordinates(depth, o3c.Tensor(np.asarray(intrinsic.intrinsic_matrix), o3c.Dtype.Float64), o3c.Tensor(np.asarray(extrinsic), o3c.Dtype.Float64), depth_scale=1000.0, depth_max=3.0)` as suggested. And then I get the following errors, quite similar as above. The image dataset is good. I tested it with the legacy CPU TSDF integration. Any suggestion? Thanks.

```
TypeError: compute_unique_block_coordinates(): incompatible function arguments. The following argument types are supported:
    1. (self: open3d.cuda.pybind.t.geometry.VoxelBlockGrid, depth: open3d.cuda.pybind.t.geometry.Image, intrinsic: open3d.cuda.pybind.core.Tensor, extrinsic: open3d.cuda.pybind.core.Tensor, depth_scale: float = 1000.0, depth_max: float = 3.0, trunc_voxel_multiplier: float = 4.0) -> open3d.cuda.pybind.core.Tensor
    2. (self: open3d.cuda.pybind.t.geometry.VoxelBlockGrid, pcd: open3d.cuda.pybind.t.geometry.PointCloud, trunc_voxel_multiplier: float = 4.0) -> open3d.cuda.pybind.core.Tensor

Invoked with: <open3d.cuda.pybind.t.geometry.VoxelBlockGrid object at 0x7fa73bac9e30>, Image of size 640x360, with 1 channels.
Use numpy.asarray to access buffer data., [[462.254 0.0 319.442],
 [0.0 462.356 179.798],
 [0.0 0.0 1.0]]
Tensor[shape={3, 3}, stride={3, 1}, Float64, CPU:0, 0x55f469d73780], [[1.0 0.0 0.0 0.0],
 [0.0 1.0 0.0 0.0],
 [0.0 0.0 1.0 0.0],
 [0.0 0.0 0.0 1.0]]
Tensor[shape={4, 4}, stride={4, 1}, Float64, CPU:0, 0x55f6b5637940], 1000.0; kwargs: depth_max=3.0
```

**Comment by theNded** [comment]
You used:
> depth:<class 'open3d.cuda.pybind.geometry.Image'> # open3d depth image
But it accepts:
>  depth: open3d.cuda.pybind.t.geometry.Image
Note there is a difference of `t` indicating tensor API.

Please refer to https://github.com/isl-org/Open3D/blob/master/examples/python/t_reconstruction_system/integrate_custom.py for the usages.

**Comment by szx0112** [comment]
@theNded It works without error now. Thanks!

I have a following issue related to the visualization of the mesh. I found there are difference between the legacy TSDF integration and the new one. Please see below


```
    volume = o3d.pipelines.integration.ScalableTSDFVolume(
        voxel_length=0.001,  # 2 mm
        sdf_trunc=0.04,
        color_type=o3d.pipelines.integration.TSDFVolumeColorType.RGB8
    )

    mesh = volume.extract_triangle_mesh()
    o3d.visualization.draw([mesh])

```
![5_cams_1](https://user-images.githubusercontent.com/10392640/148435469-3bb36487-24ad-4787-8dc9-8abd9e6e2798.png)


```
    vbg = o3d.t.geometry.VoxelBlockGrid(
        attr_names=('tsdf', 'weight', 'color'),
        attr_dtypes=(o3c.float32, o3c.float32, o3c.float32),
        attr_channels=((1), (1), (3)),
        voxel_size=3.0 / 512,           # representing 3mx3mx3m space with 512x512x512 voxel grid
        block_resolution=8,
        block_count=100000,
        device=device)
    
mesh = vbg.extract_triangle_mesh(weight_threshold=3.0, vertex_size_estimate=-1)
o3d.visualization.draw([mesh])


```
![5_cams_2](https://user-images.githubusercontent.com/10392640/148435482-599b21d7-51a8-49a7-add5-86ac477a75dd.png)

Set weight_threshold = 0.0 (as previous post #2927) improve the result, but still not at the same level as the legacy TSDF pipeline. Another similar one is #3332, but I found there are still difference in their final results.

**Comment by theNded** [comment]
The parameters are not identical in your setups:
- In legacy, you used `voxel_length` = 1mm. In the Tensor setup, you used `voxel_size` = 3/512 ~ 6mm.
- The legacy by default uses 16^3 blocks. In the Tensor setup, you used 8^3.

Please keep voxel size the same, then increase `block_resolution` to 16. You may want to reduce block count accordingly since the subvolumes are larger.

**Comment by szx0112** [comment]
I got the better results with `voxel_size = 0.5/512`. However, if I increase the `block_resolution` to 16, I got the following error

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Open3D Error] (void open3d::core::__OPEN3D_CUDA_CHECK(cudaError_t, const char*, int)) /root/Open3D/cpp/open3d/core/CUDAUtils.cpp:301: /root/Open3D/cpp/open3d/core/MemoryManagerCUDA.cpp:61 CUDA runtime error: an illegal memory access was encountered
```
I put intrinsic/extrinsic on CPU, and the depth/rgb/vbg in GPU with o3d.core.Device('CUDA:0').  The GPU is shared with monitor and I see the rise of the GPU usage when I increase `block_resolution`.

So I decide to use the 2nd GPU with    ` device_gpu = o3d.core.Device('CUDA:1')`. However, I always got the error, even use the default setup. My second GPU is 1080ti
```
vbg = o3d.t.geometry.VoxelBlockGrid(
RuntimeError: tabulate: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Open3D Error] (void open3d::core::__OPEN3D_CUDA_CHECK(cudaError_t, const char*, int)) /root/Open3D/cpp/open3d/core/CUDAUtils.cpp:301: /root/Open3D/cpp/open3d/core/MemoryManagerCUDA.cpp:61 CUDA runtime error: an illegal memory access was encountered
```

**Comment by szx0112** [comment]
It seems that the similar issue happens in [pytorch](https://github.com/pytorch/pytorch/issues/21819).  

![Screenshot from 2022-01-06 16-24-55](https://user-images.githubusercontent.com/10392640/148461102-ca4421f4-f3fc-49ee-845f-4b2acbe3809b.png)

Are there similar setups in open3d?

**Comment by theNded** [comment]
This is most likely due to a memory overflow. As I've said, you may need to shrink the `block_count` accordingly, because by increasing the `block_resolution` by a factor of 2, per subvolume now eats 2^3=8 times the memory than before.

**Comment by szx0112** [comment]
I can get the similar results now. Thanks for the clarification.
