### ISSUE TITLE
project_to_rgbd_image, empty rgb and depth image

### ISSUE THREAD

**Issue by Bastiiiiii** [isl-org/Open3D#4542]
**Describe the bug**
I try to use the project_to_rgbd_image function on my own point cloud like in [this example](https://github.com/isl-org/Open3D/pull/4464). I have generated a TSDF volume, extracted a point cloud and saved this point cloud to my harddrive with Open3D. 
Now I need to get the RGB-D image from this point cloud with the project_to_rgbd_image function. I tried different ways, either:

```
    pcd = o3d.io.read_point_cloud('../../Results/20211210_MV_Nah-einzeln-ZK.ply')
    pcd = o3d.t.geometry.PointCloud.from_legacy(pcd).to(device) 
```
 results in empty images, like this:
![Screenshot from 2022-01-06 11-21-44](https://user-images.githubusercontent.com/50514526/148369097-2216e5d9-37b8-4868-8bde-afbbfe7c8194.png)

or:
`pcd = o3d.t.io.read_point_cloud('../../Results/20211210_MV_Nah-einzeln-ZK.ply').to(device) `
which results in "rgbd_reproj = pcd.project_to_rgbd_image(1280, 720, intrinsic, depth_scale=1, depth_max=10.0)
RuntimeError: [Open3D Error] (const T* open3d::core::Tensor::GetDataPtr() const [with T = float]) /root/Open3D/cpp/pybind/../open3d/core/Tensor.h:1085: Requested values have type Float32 but Tensor has type UInt8. Please use non templated GetDataPtr() with manual casting."

**To Reproduce**
```
import open3d as o3d
import numpy as np
import matplotlib.pyplot as plt

if __name__ == '__main__':
    intrinsic = o3d.core.Tensor([[919.85498046875, 0, 625.6510009765625], [0, 919.0435791015625, 334.63861083984375],
                                 [0, 0, 1]])    
    device = o3d.core.Device('CPU:0')
    pcd = o3d.t.io.read_point_cloud('../../Results/20211210_MV_Nah-einzeln-ZK.ply').to(device) 
    o3d.visualization.draw([pcd])
    rgbd_reproj = pcd.project_to_rgbd_image(1280, 720, intrinsic, depth_scale=1, depth_max=10.0)

    print(np.asarray(rgbd_reproj.color.to_legacy()))

    fig, axs = plt.subplots(1, 2)
    axs[0].imshow(np.asarray(rgbd_reproj.color.to_legacy()))
    axs[1].imshow(np.asarray(rgbd_reproj.depth.to_legacy()))
    plt.show()
```

About any help I would be very happy!

**Comment by weisterki** [comment]
Have you solved it? Same problem with me.
