### ISSUE TITLE
Boolean Operation

### ISSUE THREAD

**Issue by hfpro** [isl-org/Open3D#4543]
a similar Boolean Operations function is provided?

**Comment by theNded** [comment]
Boolean operators are supported on the Tensor API with and/or operands. What are your specific demands?

**Comment by hfpro** [comment]
I need to deform two meshes and define a Boolean Difference

**Comment by benjaminum** [comment]
@hfpro Sorry, boolean operations on meshes are not supported. Please let us know if you find a solution, maybe this can be integrated in Open3D.

**Comment by hfpro** [comment]
thanks

**Comment by benjaminum** [comment]
We added boolean operations in #5257
