### ISSUE TITLE
Request add_3d_label to all Visualizers

### ISSUE THREAD

**Issue by yihsung** [isl-org/Open3D#4565]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Proposed new feature or change

Currently only `o3d.visualization.O3DVisualizer` supports `add_3d_label` method. It's a very useful feature so I suggest all Visualizers to have it as well. Thanks!

**Comment by theNded** [comment]
This is a new feature in the O3DVisualizer. The old visualizers will be deprecated. Please switch to the new API for the feature.

**Comment by yihsung** [comment]
Thanks for the prompt response! Currently I need to use different Visualizers because `open3d.visualization.VisualizerWithKeyCallback` takes key-callbacks and `open3d.visualization.VisualizerWithVertexSelection` can select points. Is it possible in the future `O3DVisualizer` can integrate all features together? 
Thanks!

**Comment by errissa** [comment]
Yes, it is our plan to implement all features of the old visualizer in the new one.
