### ISSUE TITLE
Pose graph optimization not close loops?

### ISSUE THREAD

**Issue by szx0112** [isl-org/Open3D#4575]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [x] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi, 

I used the pose graph optimization as in the multiway registration to reconstruct a scene. The odometry edge and loop closure edge are defined by setting uncertain=True/False to each `o3d.pipelines.registration.PoseGraphEdge`.  However, I found the method cannot properly close loop even I visit the same place twice.

An example is shown below, the zoomed region is where the loop should be closed. The camera scan the surface at close distance, thus there are sufficient overlaps between the new first images and the last ones.

I have tried some feature-based technique, and successfully detect and close such loops. I found the frame-to-frame odometry computed from open3d rgbd odometry shows more accurate results, but I have difficulty on closing the loops.  

Is there any way to improve the detectability of the loops? Any comment is really appreciated.

![Screenshot from 2022-01-10 18-28-05](https://user-images.githubusercontent.com/10392640/148860761-367e2cae-4cf1-456b-aebf-53c87c765501.png)

![Screenshot from 2022-01-10 18-35-17](https://user-images.githubusercontent.com/10392640/148861006-14a574ee-7195-447d-9a8a-af2f16bd74fe.png)

**Comment by theNded** [comment]
How did you construct the pose graph for the loop closure edges? Did you use RANSAC or FGR?

**Comment by szx0112** [comment]
@theNded  Thanks for the reply. I follow the tutorial [Multiway_Registration](http://www.open3d.org/docs/latest/tutorial/Advanced/multiway_registration.html) for constructing both the odometry and loop closure edges. I use `o3d.pipelines.odometry.compute_rgbd_odometry` to find the transformations between every pair of rgbd images and construct the pose graph. I don't think RANSIC is used in the graph optimization.

When I increase the value of `preference_loop_closure` to 2.0 (from the default 0.5 ), the loops can be closed sometime. But I cannot get consistent results (always close loops). I see other post used very large `preference_loop_closure` such as 120.0 as in this #974. Any criteria to properly define this parameter? Thanks.

**Comment by theNded** [comment]
Sorry for the late reply. 
The pose graph optimization module in Open3D serves as the backend. It generally assumes very rich loop closures, meaning we have almost exhaustive N^2 putative loop closures. Then aggressive pruning is applied to remove unreliable loop closures.

In view of this, RANSAC is frequently used as the frontend loop closure detection for point clouds, and no specific frontend is implemented natively for RGBD images -- RGBD odometry is technically not a loop detection approach and is unreliable; a better option is feature-based matching, which is used in the python reconstruction system with OpenCV's components. 

The legacy reconstruction system is on CPU, so it is a bit slow. We are working on the tensor-based system, where we have most components, but the entire system is still not ready.

**Comment by szx0112** [comment]
Thanks for the explanation. Now I can close the loop and obtain the expected results. Please feel free to close the issue. Thanks.

**Comment by nithishnks** [comment]
@szx0112 I am blocked by a similar loop closure issue. Could you talk about the changes you made to the configuration file to solve the loop closure problem in your case?

**Comment by szx0112** [comment]
Hi @nithishnks You can increase the `preference_loop_closure` parameter to trust more the detected loops than odometry. See [http://www.open3d.org/docs/release/python_api/open3d.pipelines.registration.GlobalOptimizationOption.html](http://www.open3d.org/docs/release/python_api/open3d.pipelines.registration.GlobalOptimizationOption.html).

If it still not works for your case, you can try to develop your own graph using G2o.
