### ISSUE TITLE
Register brief text with key callback function

### ISSUE THREAD

**Issue by yihsung** [isl-org/Open3D#4576]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I'd like to learn how to attach some brief text to key callback function. Simply speaking, is it possible to register the text so that when the user press `h` in running, one can see the help text? 
For example, I register key `n`, `p`, `v`, `s`, `x` and I hope when I press `h`, the terminal can show the hints instead of nothing.
Thanks!

<img width="615" alt="open3d_key_callback" src="https://user-images.githubusercontent.com/61091334/148867487-61d78ff8-450b-4ec8-8a68-eb5d35a008ca.png">

**Comment by theNded** [comment]
This API will not be updated, but you may hack the snipped [here](https://github.com/isl-org/Open3D/blob/master/cpp/open3d/visualization/visualizer/Visualizer.cpp#L487).
