### ISSUE TITLE
How to display point cloud created using open3d.t.geometry.pointcloud.create_from_rgbd_image() using the visualizer class without converting it to the legacy geometry?

### ISSUE THREAD

**Issue by prp20** [isl-org/Open3D#4587]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi All,

I'd like to know if there is a visualizer object that would help me display the point cloud generated using the method **open3d.t.geometry.pointcloud.create_from_rgbd_image()** without converting it to the legacy format i'e, _open3d.geometry.Geometry_.

Steps to try it out:
1) Using real sense sensor obtain an RGBD image. Function used to do the same is **open3d.t.io.RealSenseSensor.capture_frame()**. 
2) the obtained image would be in the format of _open3d.t.geometry.RGBDImage_. Using this image, we can generate a point cloud using the above mentioned function _open3d.t.geometry.pointcloud.create_from_rgbd_image()_.
3) Since the visualizer class of Open3d supports only _open3d.geometry.Geometry_ type, the function i need to use to convert the image to the required type is _open3d.t.geometry.pointcloud.to_legacy()_. During this conversion, I fear some data points are getting lost. 

Hence would like to know if there is a way i can display the _open3d.t.geometry.PointCloud_ as is without conversion.

**Comment by ssheorey** [comment]
Use the new GUI functionality from `open3d.visualization.gui` and `open3d.visualization.rendering` namespaces. The simplest way is:

`open3d.visualization.draw([tPointCloud])`

This also supports legacy geometry types.
docs are in progress...

**Comment by prp20** [comment]
HI @ssheorey,
Based on your suggestion i was looking into  open3d.visualization.gui and the examples in them. 
https://github.com/isl-org/Open3D/blob/master/examples/python/gui/online_processing.py. I tried to execute the same, but not getting any point cloud. my setup is connected to a real sense sensor and I'm able to view the point cloud using pyrealsense Api's, as well as open3d.t.io.realsense() api.
Can you please provide any pointers regarding the same.

**Comment by ssheorey** [comment]
Hi @prp20 please paste the terminal output from the example here. Also what do you see instead?

**Comment by ssheorey** [comment]
Make sure to include your system / environment details according to the bug reporting template.

**Comment by ssheorey** [comment]
Please re-open if you still have this issue.
