### ISSUE TITLE
Why does the bunny I save look different in threejs online tool?

### ISSUE THREAD

**Issue by AlexHex7** [isl-org/Open3D#4590]
### Checklist

- [x] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi, I have tried to search for similar issues, but I do not know how to describe this problem properly to search the best issue.

# Environment
- Ubuntu 18.04
- Conda
- open3d==0.14.1
- python=3.8

# Code
    import open3d as o3d
  
    # bun_zipper.ply download from http://graphics.stanford.edu/pub/3Dscanrep/bunny.tar.gz
    mesh = o3d.io.read_triangle_mesh("./bun_zipper.ply")
    mesh.compute_vertex_normals()
    pcd = mesh.sample_points_poisson_disk(7500)
    mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_alpha_shape(pcd, 0.03)
  
    o3d.io.write_triangle_mesh('bunny_sample.ply', mesh)

# Visualization
1. Visualize **bun_zipper.ply** in VSCode plugin (vscode-3d-preview)
![image](https://user-images.githubusercontent.com/30361851/149271284-7ef1532d-2f77-4f15-9bbf-538fbd400c63.png)

2. Visualize **bunny_sample.ply** in VSCode plugin (vscode-3d-preview)
![image](https://user-images.githubusercontent.com/30361851/149271417-dfba979c-4a09-433b-bf06-c119f9c21ba0.png)

3. Visualize **bun_zipper.ply** in {ThreeJD](https://threejs.org/editor/)
![image](https://user-images.githubusercontent.com/30361851/149271483-43273d7b-e35a-4dee-b90a-122a2d0e4983.png)

4. Visualize **bunny_sample.ply** in {ThreeJD](https://threejs.org/editor/)
**Why it looks like some face is empty?**
![image](https://user-images.githubusercontent.com/30361851/149271509-2c7494ad-a5e6-43a0-a82a-d59806220f5a.png)

5. Visualize **bunny_sample.obj** in {ThreeJD](https://threejs.org/editor/)
If I save it as obj file, still meet this problem.
    

        o3d.io.write_triangle_mesh('bunny_sample.obj', mesh)

6. Visualize **bunny_zipper_save_obj.obj** in {ThreeJD](https://threejs.org/editor/)
If I save *bun_zipper.ply* in to **bunny_zipper_save_obj.ob**,  not meet this problem.

        import open3d as o3d

        mesh = o3d.io.read_triangle_mesh("./test_data/bun_zipper.ply")
        o3d.io.write_triangle_mesh('bunny_zipper_save_obj.obj', mesh)

![image](https://user-images.githubusercontent.com/30361851/149273340-58a919b1-d4b5-4cf6-a3d5-26b2c4b67f8d.png)

**Comment by theNded** [comment]
It could be because of irregular face directions. Open3D produces the mesh with desired behavior, see [tutorial](http://www.open3d.org/docs/latest/tutorial/Advanced/surface_reconstruction.html). Please redirect the question to threejs.
