### ISSUE TITLE
Performance Issue with `Open3D Logging`

### ISSUE THREAD

**Issue by reyanshsolis** [isl-org/Open3D#4595]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

There is some performance issue for the Open3D logging function after `v0.13.0`.

Testing conditions for benchmarking: 
- For `LogDebug`, `Verbosity` was set to `Info` and `Warning`, and for `LogWarning`, `verbosity` was set to `Error`, to avoid time due to printing on console. 
- The following cases were taken:

Case 1: 
```cpp
    utility::LogDebug("");
```

Case 2: 
```cpp
    utility::LogDebug("Random Debug Info.");
```

Case 3: 
```cpp
    utility::LogDebug(
            "Random Debug Info. This is a long string, to check the "
            "performance of LogDebug wrt to size of input string.");
```

Case 4: 
```cpp
    std::string test =
            "Random Debug Info. This is a long string, to check the "
            "performance of LogDebug wrt to size of input string.";
    utility::LogDebug("{}", test);
```

Case 5: 
```cpp
    double x = 5.0;
    utility::LogDebug("Double value as input: {}", x);
```

Case 6: 
```cpp
    double x = 5.0;
    utility::LogDebug("Double value as input: {:f}", x);
```
---
#### No. Given, their input is the same, the performance was found to be similar.
---
### Performance Benchmark Results (time in nanoseconds)
| Case  | v0.12.0 | master
| ------------- | ------------- | ------------- |
| 1  |  0.511 ns | 2.00 ns |
| 2  |  0.512 ns | 9.94 ns |
| 3  |  0.511 ns | 10.8 ns |
| 4  |  0.513 ns | 24.9 ns |
| 5  |  0.366 ns | 157 ns |
| 6  |  0.367 ns | 168 ns |

####
The absolute difference might not be much significant, however as these logging functions are part of various pipelines it impacts the performance as it is called various times. 
For example: TriangleMesh::CreateFromPointCloudBallPivoting is more than 10x slow in current master as compared to v0.12.0 #4533 

---
### Steps to reproduce the bug
- Build A(v0.12.0) and B(current master) from the source.
- Use the attached benchmark file to get the result. [PS. v0.12.0: It's Console.h instead of Logging.h].

---
#### Ideally, let's say if the `verbosity` is set to `Info` or `Warning`, `LogDebug` should not take any time at all. If should be directly skipped without evaluation. 
---
### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04
- Python version: Python 3.8
- Open3D version: master [9abcd8c9a8743ab1dbf352b102b3532fc3fee4be]
- System type: x84
- Is this remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): gcc 9.3
```
---

### Additional information

Change the extension from `.txt` to `.cpp` before use. 
Modify the header `Logging.h` to `Console.h` for `v.0.12.0`. 
[Logging.txt](https://github.com/isl-org/Open3D/files/7865892/Logging.txt)

**Comment by yxlao** [comment]
@reyanshsolis could you provide the code for the benchmark?

**Comment by reyanshsolis** [comment]
### Run benchmark on v0.12 [branch: rey/benchmark-v012]

```bash
git clone git@github.com:isl-org/Open3D.git
git checkout rey/benchmark-v012
cd Open3D 
git submodule update --init --recursive
mkdir build && cd build
cmake -DBUILD_SHARED_LIBS=OFF -DBUILD_CUDA_MODULE=OFF -DBUILD_BENCHMARKS=ON -DBUILD_UNIT_TESTS=ON -DBUILD_EXAMPLES=OFF -DBUILD_JUPYTER_EXTENSION=OFF -DBUILD_WEBRTC=OFF .. && make -j8
```
Run Benchmark for `LogDebug`.
```bash
./bin/benchmarks --benchmark_filter=".*LogDebug.*"
```
Output:
```
------------------------------------------------------------------------------------------------------
Benchmark                                                            Time             CPU   Iterations
------------------------------------------------------------------------------------------------------
BenchmarkLogDebugEmpty/Empty                                     0.575 ns        0.575 ns   1000000000
BenchmarkLogDebugSmallString/SmallString                         0.571 ns        0.571 ns   1000000000
BenchmarkLogDebugLongString/LongString                           0.574 ns        0.574 ns   1000000000
BenchmarkLogDebugWithLongStringAsInput/LongStringAsInput         0.572 ns        0.572 ns   1000000000
BenchmarkLogDebugWithDoubleAsInput/Double                        0.412 ns        0.412 ns   1000000000
BenchmarkLogDebugWithDoubleAsInputFmt/DoubleFmt                  0.410 ns        0.410 ns   1000000000
BenchmarkLogDebugEmpty/(W)Empty                                  0.576 ns        0.576 ns   1000000000
BenchmarkLogDebugSmallString/(W)SmallString                      0.575 ns        0.575 ns   1000000000
BenchmarkLogDebugLongString/(W)LongString                        0.574 ns        0.574 ns   1000000000
BenchmarkLogDebugWithLongStringAsInput/(W)LongStringAsInput      0.575 ns        0.575 ns   1000000000
BenchmarkLogDebugWithDoubleAsInput/(W)Double                     0.412 ns        0.411 ns   1000000000
BenchmarkLogDebugWithDoubleAsInputFmt/DoubleFmt                  0.416 ns        0.416 ns   1000000000
```
Run Benchmark for `TriangleMesh::CreateFromPointCloudBallPivoting`.
```bash
./bin/benchmarks --benchmark_filter=".*BallPivot.*"
```
Output:
```
----------------------------------------------------------------------------------------------------
Benchmark                                                          Time             CPU   Iterations
----------------------------------------------------------------------------------------------------
BenchmarkCreateFromPointCloudBallPivoting/PCD_without_nan       2599 ms         2599 ms            1
```


### Run benchmark on v0.14.1 [master] [branch: rey/benchmark-014]

```bash
git clone git@github.com:isl-org/Open3D.git
git checkout rey/benchmark-014
cd Open3D 
mkdir build && cd build
cmake -DBUILD_SHARED_LIBS=OFF -DBUILD_CUDA_MODULE=OFF -DBUILD_BENCHMARKS=ON -DBUILD_UNIT_TESTS=ON -DBUILD_EXAMPLES=OFF -DBUILD_JUPYTER_EXTENSION=OFF -DBUILD_WEBRTC=OFF .. && make -j8
```
Run Benchmark for `LogDebug`.
```bash
./bin/benchmarks --benchmark_filter=".*LogDebug.*"
```
Output:
```
------------------------------------------------------------------------------------------------------
Benchmark                                                            Time             CPU   Iterations
------------------------------------------------------------------------------------------------------
BenchmarkLogDebugEmpty/Empty                                      2.01 ns         2.01 ns    348108841
BenchmarkLogDebugSmallString/SmallString                          11.2 ns         11.2 ns     63156690
BenchmarkLogDebugLongString/LongString                            11.8 ns         11.8 ns     59674684
BenchmarkLogDebugWithLongStringAsInput/LongStringAsInput          29.5 ns         29.5 ns     23388736
BenchmarkLogDebugWithDoubleAsInput/Double                          180 ns          181 ns      3742168
BenchmarkLogDebugWithDoubleAsInputFmt/DoubleFmt                    192 ns          192 ns      3594833
BenchmarkLogDebugEmpty/(W)Empty                                   1.90 ns         1.90 ns    326619046
BenchmarkLogDebugSmallString/(W)SmallString                       10.3 ns         10.3 ns     66897242
BenchmarkLogDebugLongString/(W)LongString                         11.3 ns         11.3 ns     61021808
BenchmarkLogDebugWithLongStringAsInput/(W)LongStringAsInput       30.1 ns         30.1 ns     23749950
BenchmarkLogDebugWithDoubleAsInput/(W)Double                       184 ns          184 ns      3841693
BenchmarkLogDebugWithDoubleAsInputFmt/DoubleFmt                    184 ns          184 ns      3666550
```
Run Benchmark for `TriangleMesh::CreateFromPointCloudBallPivoting`.
```bash
./bin/benchmarks --benchmark_filter=".*BallPivot.*"
```
Output:
```
----------------------------------------------------------------------------------------------------
Benchmark                                                          Time             CPU   Iterations
----------------------------------------------------------------------------------------------------
BenchmarkCreateFromPointCloudBallPivoting/PCD_without_nan      12810 ms        12811 ms            1
```

### Remove all the LogDebug from `CreateFromPointCloudBallPivoting` on the current master and benchmark:
branch: rey/benchmark-ballpivot-wo-log
```
----------------------------------------------------------------------------------------------------
Benchmark                                                          Time             CPU   Iterations
----------------------------------------------------------------------------------------------------
BenchmarkCreateFromPointCloudBallPivoting/PCD_without_nan       1627 ms         1627 ms            1
```

**Comment by reyanshsolis** [comment]
> * How does this affect real workloads? E.g. if a print takes 168 ns, it can print 5,952,380 times in 1 second. Does it really matter?

In the above example of `CreateFromPointCloudBallPivoting` performance, the v0.12 took 2599ms, master took 12810ms, and master with Logging statements removed from the function took 1627ms. 

I believe, ideally, if verbosity is set to `Info`, then `Debug` statement should not evaluate the input. Many of our pipeline performances may improve from this.

**Comment by reyanshsolis** [comment]
> * Does it only affect `LogDebug` since it now prints the line number and file name?

Only `LogError` prints the line number and file name.

**Comment by 1939938853** [comment]
Hello reyanshsolis,

I replaced the v0.14  SurfaceReconstructionBallPivoting.cpp with the one of v0.12. It is still more than 10 times slow  In the v0.12  SurfaceReconstructionBallPivoting.cpp, there is no logging.

Do you mean it is the looging somewhere else that affect the  SurfaceReconstructionBallPivoting performance?

**Comment by reyanshsolis** [comment]
Hi @1939938853, replacing  `SurfaceReconstructionBallPivoting.cpp`, won't affect performance, as the `LogDebug` (defined in cpp/utility/Logging.h in v0.13+, and cpp/utility/Console.h in v0.12). 
I am trying to fix this issue, meanwhile, if you want to use 0.13+, just comment out all the `utility::LogDebug(...)`, statements in  `SurfaceReconstructionBallPivoting.cpp`, and you should get even better performance than v0.12.

**Comment by 1939938853** [comment]
Hello reyanshsolis,

I have tried to comment away the utility::LogDebug() in v0.14. It is still the same -- 10 times slow. Perhaps I need to spend some hours to do a clean rebuild the whole Open3D project. I guess.

**Comment by yxlao** [comment]
>  Perhaps I need to spend some hours to do a clean rebuild the whole Open3D project.

@1939938853 if you're on Linux/Mac, I would highly recommend `ccache`. It takes under 1 min to do a full clean build on a fast machine (several minutes for a laptop). Simply `apt-get install ccache` and build again. Open3D's CMake can detect and use `ccache` when it is available.

**Comment by reyanshsolis** [comment]
@1939938853 
I have updated some changes in PR #4622, may you please remove your build, and re-build with this branch (`rey/fix-logger`)

You may use your own example, or run the benchmark:

```
git clone git@github.com:isl-org/Open3D.git
git checkout rey/fix-logger
cd Open3D 
mkdir build && cd build
cmake -DBUILD_SHARED_LIBS=OFF -DBUILD_CUDA_MODULE=OFF -DBUILD_BENCHMARKS=ON -DBUILD_UNIT_TESTS=ON -DBUILD_EXAMPLES=OFF -DBUILD_JUPYTER_EXTENSION=OFF -DBUILD_WEBRTC=OFF .. && make -j8
```
Run Benchmark for `CreateFromPointCloudBallPivoting`.
```
./bin/benchmarks --benchmark_filter=".*CreateFromPointCloudBallPivoting.*"
```
