### ISSUE TITLE
open3d.utility.Vector3iVector

### ISSUE THREAD

**Issue by hfpro** [isl-org/Open3D#4600]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

hello, I am trying to execute a script from the documentation, an error occurs

### Steps to reproduce the bug

```python
class open3d.utility.Vector3iVector
Convert int32 numpy array of shape (n, 3) to Open3D format..

Example usage

import open3d
import numpy as np

# Example mesh
# x, y coordinates:
# [0: (-1, 2)]__________[1: (1, 2)]
#             \        /\
#              \  (0) /  \
#               \    / (1)\
#                \  /      \
#      [2: (0, 0)]\/________\[3: (2, 0)]
#
# z coordinate: 0

mesh = open3d.geometry.TriangleMesh()
np_vertices = np.array([[-1, 2, 0],
                        [1, 2, 0],
                        [0, 0, 0],
                        [2, 0, 0]])
np_triangles = np.array([[0, 2, 1],
                         [1, 2, 3]]).astype(np.int32)
mesh.vertices = open3d.Vector3dVector(np_vertices)

# From numpy to Open3D
mesh.triangles = open3d.Vector3iVector(np_triangles)

# From Open3D to numpy
np_triangles = np.asarray(mesh.triangles)
```

### Error message

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_9364/3873867975.py in <module>
     20 np_triangles = np.array([[0, 2, 1],
     21                          [1, 2, 3]]).astype(np.int32)
---> 22 mesh.vertices = open3d.Vector3dVector(np_vertices)
     23 
     24 # From numpy to Open3D

AttributeError: module 'open3d' has no attribute 'Vector3dVector'

### Expected behavior

Convert int32 numpy array of shape (n, 3) to Open3D format

### Open3D, Python and System information

```markdown
- Operating system: (e.g. Windows 10 64-bit)
- Python version: (e.g. Python 3.8.12)
- Open3D version: (output from python: `print(open3d.0.14.1)`)
- System type: (arm64 )
- Is this remote workstation?: no
- How did you install Open3D?: (e.g. conda)
- Compiler version (if built from source): (e.g. gcc 7.5, clang 7.0)
```

**Comment by theNded** [comment]
Please use `open3d.utility.Vector3dVector`.
