### ISSUE TITLE
DrawWebRTC.cpp black(empty) video is showing.

### ISSUE THREAD

**Issue by jskimn** [isl-org/Open3D#4601]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Using 'DrawWebRTC.cpp', I checked WebRTC video playing in localhost:8888.
However, it shows black(empty) video like blow.
![image](https://user-images.githubusercontent.com/58724183/149610531-dd121288-363f-40eb-b849-fe77600e4c6e.png)

As I known, ICE server does not need for localhost.
If you know any problem for my case, help me please.

'DrawWebRTC.cpp' is not changed.

**Comment by yxlao** [comment]
It will help to show what's printed in the terminal and Chrome's console.

**Comment by jskimn** [comment]
Dear yxlao,
I am so late for your response because I changed development machine.
And I checked that the sample code(DrawWebRTC.cpp) does not have any problem like below screen shot.

![image](https://user-images.githubusercontent.com/58724183/150901115-366dc261-c0a0-4b2b-9707-c7d9a98a4bf9.png)

Thanks a lot!

**Comment by yxlao** [comment]
Great. Typically for debugging:

1. First is to disable WebRTC and first make sure it works fine with the native window.
2. Then enable WebRTC and test on a browser. 

So it seems to be working for you. Closing this issue.
