### ISSUE TITLE
`create_from_point_cloud_ball_pivoting()` runs x20 slower on `0.14.1` compared to `0.13.0`

### ISSUE THREAD

**Issue by low5545** [isl-org/Open3D#4602]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

I was testing out Ball Pivoting Algorithm to generate a mesh from a point cloud according to this [tutorial](http://www.open3d.org/docs/latest/tutorial/Advanced/surface_reconstruction.html#Ball-pivoting). I realized that `o3d.geometry.TriangleMesh.create_from_point_cloud_ball_pivoting()` on Open3D `0.14.1` runs ~20x longer than Open3D `0.13.0` (~3.3s to ~60s) with a point cloud size of 35947 & the same set of radii.

Is there a bug somewhere?

### Steps to reproduce the bug

```python
import open3d_example    # https://github.com/isl-org/Open3D/blob/master/examples/python/open3d_example.py

gt_mesh = open3d_example.get_bunny_mesh()
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(gt_mesh.vertices)
pcd.normals = o3d.utility.Vector3dVector(gt_mesh.vertex_normals)

nn_dists = pcd.compute_nearest_neighbor_distance()
mean_nn_dists = np.mean(nn_dists)
bpa_min_radius = 4 * mean_nn_dists
radii = o3d.utility.DoubleVector([ bpa_min_radius, 2 * bpa_min_radius, 3 * bpa_min_radius ])

rec_mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_ball_pivoting(
    pcd, o3d.utility.DoubleVector(radii)
)                                              # 0.13.0: 3.3s, 0.14.1: 60s
```

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04
- Python version: Python 3.8
- Open3D version: 0.13.0 / 0.14.1
- System type: x84
- Is this remote workstation?: yes
- How did you install Open3D?: pip & conda (tried both)
```

**Comment by reyanshsolis** [comment]
Please follow the following related issues:
https://github.com/isl-org/Open3D/issues/4595
https://github.com/isl-org/Open3D/issues/4533
