### ISSUE TITLE
Request to add Triangulated Surface Mesh Skeletonization

### ISSUE THREAD

**Issue by xleEmesent** [isl-org/Open3D#4608]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Proposed new feature or change

Can we have Triangulated Surface Mesh Skeletonization feature same as [CGAL](https://doc.cgal.org/latest/Surface_mesh_skeletonization/index.html) ? Many Thanks!!!

![image](https://user-images.githubusercontent.com/66909631/149683283-b51c4895-63b7-49bd-b2e9-13668b86fa71.png)

### References

[CGAL](https://doc.cgal.org/latest/Surface_mesh_skeletonization/index.html) ? 
[1] Andrea Tagliasacchi, Ibraheem Alhashim, Matt Olson, and Hao Zhang. Mean curvature skeletons. Computer Graphics Forum (Proceedings of the Symposium on Geometry Processing), 31(5):1735–1744, 2012.

**Comment by theNded** [comment]
Unfortunately we don't have the bandwidth of extending mesh processing features. Contribution is welcomed.
