### ISSUE TITLE
Any ways to reduce size of compiled libraries?

### ISSUE THREAD

**Issue by changh95** [isl-org/Open3D#4612]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Dear Open3D team,

Is there any way to build the Open3D library with a smaller size?

Below is the context of my question:

I've just managed to compile Open3D. My system is Ubuntu Linux 20.04 with Intel CPU, and I used `cmake -DCMAKE_BUILD_TYPE=Release ..` to configure the build.

What I noticed is the total size of the compiled library is massive - about 1.2GB! The largest library is 'libOpen3D_3rdparty_blas_mkl_merged.a', which I believe is just a wrapper of BLAS and Intel MKL for CPU acceleration of linear algebra computation. This makes it difficult to use Open3D library on a relatively low-power device with scarce memory. Something around ~50MB is tolerable, but 1.2GB is just too much. Also, this kind of devices use ARM CPU, so it won't use MKL anyways. I also tried `cmake -DCMAKE_BUILD_TYPE=Release -DUSE_BLAS=ON ..` with a hope that it won't build MKL (hence a smaller library size), but this build fails as OpenBLAS fails to link with gfortran (If this is an unexpected behaviour, I'll write an issue about it - let me know!).

Many thanks, and excellent work!

**Comment by ssheorey** [comment]
Hi @changh95,
- Are you building for Intel or ARM?
- You can turn off any feature that you do not need to reduce the build size. See the options in `CMakelists.txt`.
- Using system libraries instead of building from source will also reduce the build size.
- Finally, if using shared libraries works in your case, building a shared library with `-D SHARED=ON` will produce a smaller `libopen3d.so`. You do not need the static `lib*.a` in this case.

**Comment by changh95** [comment]
@ssheorey,

- I'm building for Intel CPU.
- To get rid of the 'libOpen3D_3rdparty_blas_mkl_merged.a', will I need to install MKL and BLAS on the system?
   - There isn't a CMake option for `USE_SYSTEM_MKL` or `USE_SYSTEM_BLAS`.

**Comment by ssheorey** [comment]
@changh95 if you set `-D USE_BLAS=ON -D BUILD_BLAS_FROM_SOURCE=OFF` it will look for the system BLAS and LAPACK libraries. See https://github.com/isl-org/Open3D/blob/e008cca9b7ac2455fbd6bf6830e0b5d32f9f6a36/3rdparty/find_dependencies.cmake#L1248

You should have OpenBLAS installed on your system.

**Comment by yxlao** [comment]
@changh95 , if you are fine with shared lib, setting `BUILD_SHARED_LIBS=ON` will generate `libOpen3D.so`, where only the *necessary part* of `libOpen3D_3rdparty_blas_mkl_merged.a` is linked into `libOpen3D.so`. You'll only have one `.so` file instead of many `.a` files.

**Comment by yxlao** [comment]
Embedded Intel MKL in Open3D:
```bash
cmake -DBUILD_SHARED_LIBS=ON ..
make -j
ls -alh lib/Release/libOpen3D.so

Result: 137M
```

Embedded OpenBLAS in Open3D:
```bash
cmake -DBUILD_SHARED_LIBS=ON -DUSE_BLAS=ON -DBUILD_BLAS_FROM_SOURCE=ON ..
make -j
ls -alh lib/Release/libOpen3D.so

Result: 103M
```

**Comment by changh95** [comment]
I might be the only one getting the issue which OpenBLAS fails to link with gfortran when building Open3D...
Because of this, I have not yet been able to test the methods suggested above.

The error looks as below - I'll try the suggested methods again once I solve the current issue.

![image](https://user-images.githubusercontent.com/39010111/150234928-820ecd07-a780-4b35-a35e-3c9e344ee3e4.png)

**Comment by changh95** [comment]
> I might be the only one getting the issue which OpenBLAS fails to link with gfortran when building Open3D... Because of this, I have not yet been able to test the methods suggested above. I'm thinking there might be a problem with my OpenBLAS.
> 
> The error looks as below - I'll try the suggested methods again once I solve the current issue.
> 
> ![image](https://user-images.githubusercontent.com/39010111/150234928-820ecd07-a780-4b35-a35e-3c9e344ee3e4.png)

My bad on this one!
After re-installing LAPACK, the build went successful. It was not so straightforward to spot the mistake since there wasn't any warning for checking LAPACK dependency.

The compiled result with `cmake -DUSE_BLAS=ON -DBUILD_BLAS_FROM_SOURCE=OFF` is around ~400MB, which is far better than before. I believe this is as 'libOpen3D_3rdparty_blas_mkl_merged.a' is not built due to cmake option, and this file is around ~700MB (400MB + 700 MB ~= 1.2GB). One question though, if the `libOpen3D.a` load the system-installed BLAS, wouldn't the total loaded symbol still be around 1.2GB?

**Comment by changh95** [comment]
> Embedded Intel MKL in Open3D:
> 
> ```shell
> cmake -DBUILD_SHARED_LIBS=ON ..
> make -j
> ls -alh lib/Release/libOpen3D.so
> 
> Result: 137M
> ```
> 
> Embedded OpenBLAS in Open3D:
> 
> ```shell
> cmake -DBUILD_SHARED_LIBS=ON -DUSE_BLAS=ON -DBUILD_BLAS_FROM_SOURCE=ON ..
> make -j
> ls -alh lib/Release/libOpen3D.so
> 
> Result: 103M
> ```

Succeeded on this! The output is ~140MB on mine!

**Comment by ssheorey** [comment]
@changh95 closing this issue as resolved. Feel free to reopen this or a new issue if you have any other problems.
