### ISSUE TITLE
Pose graph optimization on multiple scans/cameras

### ISSUE THREAD

**Issue by szx0112** [isl-org/Open3D#4625]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Is it possible for the pose graph to optimize the poses from two RGBD cameras so we can get an improved, integrated reconstruction? For example, I scan a room use two overlapped cameras (camA and camB) mounted on a rig. I can construct the model from each camera and manually register them together. I found each model is distorted, so cannot rigidly align them well. Thus, I am wondering if it is possible to combine them into a **single pose graph** and obtain a better reconstruction.

To do this, I constructed two chain of odometry edges from each camera. I connect these two chains with loop closure edges (`camA-start to camB-start` and `camA-end to camB-end`) forming the loop of the two-cams scan. I use loop closure edges because the camera extrinsic is not accurate and the depth sensor has noise.

The index of the pose graph node is sequentially defined: first assign the index to poses from camA (start at 0 and finished at N), and then set the first pose of the camB as N+1, till the end. 

However, I got the **[Open3D WARNING] Invalid poseGraph - graph is not connected.**. I went through several posts related to the issue but haven't found the answer yet.

Does the error related to my nodes indexing or the edge definition? Is there any specific rules to define the pose graph (e.g,  the graph must be connected by the odometry edges )? 

BTW, not quite sure if the node index needs to be continuous? For example, is that ok to define the node of camA as (100, 101, 102,...) and camB as (200, 201, 202,...). It might be easier for me to differentiate the nodes belong to different cameras.

Any comment is appreciated. Thanks.

**Comment by theNded** [comment]
The node indices should start from zero, so I guess starting from 100 might cause trouble, but they don't have to be continuous.
Let me know if it helps.

**Comment by szx0112** [comment]
@theNded  Thanks for the quick reply. After reindexing the camera nodes, the graph can be optimized. I added more loop closure edges between the cameras to increase the constraints.

I got the warning` [Open3D WARNING] Certain-edge subset of PoseGraph is not connected.` I think it just indicates the graph is not complete.

However, I do not get the correct camera poses when calling `pose_graph.nodes[node_index].pose`. I think the graph optimization is correct because the residual is decreasing (listed below).

I notice the pose graph use node 0 as reference but in my case is not at origin. I set the center of the two cams as the origin. Does it affect the results?

```
[Open3D DEBUG] Validating PoseGraph - finished.
[Open3D DEBUG] [GlobalOptimizationLM] Optimizing PoseGraph having 48 nodes and 192 edges.
[Open3D DEBUG] Line process weight : 11.718910
[Open3D DEBUG] [Initial     ] residual : 3.067833e+05, lambda : 2.518926e+00
[Open3D DEBUG] [Iteration 00] residual : 7.766462e+03, valid edges : 4, time : 0.003 sec.
[Open3D DEBUG] [Iteration 01] residual : 3.243165e+03, valid edges : 14, time : 0.002 sec.
[Open3D DEBUG] [Iteration 02] residual : 1.355308e+03, valid edges : 83, time : 0.002 sec.
[Open3D DEBUG] [Iteration 03] residual : 6.403069e+02, valid edges : 110, time : 0.002 sec.
[Open3D DEBUG] [Iteration 04] residual : 4.312717e+02, valid edges : 116, time : 0.002 sec.
[Open3D DEBUG] [Iteration 05] residual : 3.830156e+02, valid edges : 116, time : 0.002 sec.
[Open3D DEBUG] [Iteration 06] residual : 3.775899e+02, valid edges : 116, time : 0.002 sec.
[Open3D DEBUG] [Iteration 07] residual : 3.765889e+02, valid edges : 116, time : 0.001 sec.
[Open3D DEBUG] [Iteration 08] residual : 3.761565e+02, valid edges : 117, time : 0.002 sec.
[Open3D DEBUG] [Iteration 09] residual : 3.757529e+02, valid edges : 118, time : 0.002 sec.
[Open3D DEBUG] [Iteration 10] residual : 3.752926e+02, valid edges : 118, time : 0.001 sec.
[Open3D DEBUG] [Iteration 11] residual : 3.747582e+02, valid edges : 118, time : 0.001 sec.
[Open3D DEBUG] [Iteration 12] residual : 3.742052e+02, valid edges : 118, time : 0.002 sec.
[Open3D DEBUG] [Iteration 13] residual : 3.737476e+02, valid edges : 118, time : 0.002 sec.
[Open3D DEBUG] [Iteration 14] residual : 3.734478e+02, valid edges : 118, time : 0.002 sec.
[Open3D DEBUG] [Iteration 15] residual : 3.732729e+02, valid edges : 118, time : 0.002 sec.
[Open3D DEBUG] [Iteration 16] residual : 3.731709e+02, valid edges : 118, time : 0.002 sec.
[Open3D DEBUG] [Iteration 17] residual : 3.731062e+02, valid edges : 118, time : 0.001 sec.
[Open3D DEBUG] [Iteration 18] residual : 3.730528e+02, valid edges : 117, time : 0.002 sec.
[Open3D DEBUG] [Iteration 19] residual : 3.729845e+02, valid edges : 117, time : 0.001 sec.
[Open3D DEBUG] [Iteration 20] residual : 3.728604e+02, valid edges : 117, time : 0.001 sec.
[Open3D DEBUG] [Iteration 21] residual : 3.725955e+02, valid edges : 117, time : 0.002 sec.
[Open3D DEBUG] [Iteration 22] residual : 3.720178e+02, valid edges : 118, time : 0.001 sec.
[Open3D DEBUG] [Iteration 23] residual : 3.709812e+02, valid edges : 118, time : 0.001 sec.
[Open3D DEBUG] [Iteration 24] residual : 3.699673e+02, valid edges : 118, time : 0.002 sec.
[Open3D DEBUG] [Iteration 25] residual : 3.696213e+02, valid edges : 118, time : 0.001 sec.
[Open3D DEBUG] [Iteration 26] residual : 3.695749e+02, valid edges : 118, time : 0.001 sec.
[Open3D DEBUG] [Iteration 27] residual : 3.695682e+02, valid edges : 118, time : 0.001 sec.
[Open3D DEBUG] [Iteration 28] residual : 3.695662e+02, valid edges : 118, time : 0.002 sec.
[Open3D DEBUG] [Iteration 29] residual : 3.695652e+02, valid edges : 118, time : 0.002 sec.
[Open3D DEBUG] [Iteration 30] residual : 3.695647e+02, valid edges : 118, time : 0.001 sec.
[Open3D DEBUG] Current_residual - new_residual < 1.000000e-06 * current_residual
[Open3D DEBUG] [GlobalOptimizationLM] total time : 0.054 sec.
[Open3D DEBUG] [GlobalOptimizationLM] Optimizing PoseGraph having 48 nodes and 162 edges.
[Open3D DEBUG] Line process weight : 12.111630
[Open3D DEBUG] [Initial     ] residual : 5.338916e+01, lambda : 4.824496e+00
[Open3D DEBUG] [Iteration 00] residual : 5.163697e+01, valid edges : 118, time : 0.002 sec.
[Open3D DEBUG] [Iteration 01] residual : 5.144049e+01, valid edges : 118, time : 0.001 sec.
[Open3D DEBUG] [Iteration 02] residual : 5.142700e+01, valid edges : 118, time : 0.001 sec.
[Open3D DEBUG] [Iteration 03] residual : 5.142196e+01, valid edges : 118, time : 0.001 sec.
[Open3D DEBUG] [Iteration 04] residual : 5.141965e+01, valid edges : 118, time : 0.001 sec.
[Open3D DEBUG] [Iteration 05] residual : 5.141858e+01, valid edges : 118, time : 0.002 sec.
[Open3D DEBUG] [Iteration 06] residual : 5.141808e+01, valid edges : 118, time : 0.001 sec.
[Open3D DEBUG] [Iteration 07] residual : 5.141785e+01, valid edges : 118, time : 0.002 sec.
[Open3D DEBUG] [Iteration 08] residual : 5.141775e+01, valid edges : 118, time : 0.001 sec.
[Open3D DEBUG] Current_residual - new_residual < 1.000000e-06 * current_residual
[Open3D DEBUG] [GlobalOptimizationLM] total time : 0.015 sec.
[Open3D DEBUG] CompensateReferencePoseGraphNode : reference : 0
```

**Comment by szx0112** [comment]
I figured out the problem. The transformations are reversed.

**Comment by theNded** [comment]
> I figured out the problem. The transformations are reversed.

Thanks for the update, I will close this issue. Please feel free to reopen or report new issues if in need.

**Comment by szx0112** [comment]
Hi @theNded I just noticed that after the revision. The graph never optimizes the camera poses. And the camera poses are not optimal because I can observe the misalignment. Below is the output:

From Pose graph optimization
```
Optimizing PoseGraph ...
[Open3D WARNING] Certain-edge subset of PoseGraph is not connected.
[Open3D DEBUG] Validating PoseGraph - finished.
[Open3D DEBUG] [GlobalOptimizationLM] Optimizing PoseGraph having 32 nodes and 62 edges.
[Open3D DEBUG] Line process weight : 7.697477
[Open3D DEBUG] [Initial     ] residual : 8.179560e-26, lambda : 5.723226e+00
[Open3D DEBUG] Maximum coefficient of right term < 1.000000e-06
[Open3D DEBUG] [GlobalOptimizationLM] Optimizing PoseGraph having 32 nodes and 62 edges.
[Open3D DEBUG] Line process weight : 7.697477
[Open3D DEBUG] [Initial     ] residual : 8.179560e-26, lambda : 5.723226e+00
[Open3D DEBUG] Maximum coefficient of right term < 1.000000e-06
[Open3D DEBUG] CompensateReferencePoseGraphNode : reference : 0
```

The setup is:
```
option = o3d.pipelines.registration.GlobalOptimizationOption(
            max_correspondence_distance=0.01,
            edge_prune_threshold=10,
            reference_node=0)
        with o3d.utility.VerbosityContextManager(
                o3d.utility.VerbosityLevel.Debug) as cm:
            o3d.pipelines.registration.global_optimization(
                pose_graph,
                o3d.pipelines.registration.GlobalOptimizationLevenbergMarquardt(),
                o3d.pipelines.registration.GlobalOptimizationConvergenceCriteria(),
                option)
```

The pose graph. Red dots are camera poses (2 cameras move ahead).  Odom edges (green) are defined within each camera, and the loop closure edges are defined between cameras at the same timestamp. The coordinate axis denotes the origin of the graph (beneath both cameras). 
![Screenshot from 2022-01-21 13-18-10](https://user-images.githubusercontent.com/10392640/150587202-fece4dfa-1000-43ba-9c13-423d4d065adc.png)

**Comment by VladimirYugay** [comment]
@szx0112 for two trajectories for two different cameras, how did you make the graph connected (assuming that the loop edges are sparse)?

**Comment by szx0112** [comment]
@VladimirYugay Hi, I use the center of the two cameras at time 0 as the origin (identity). The two trajectories can then be put into the same coordinate system. 

> @szx0112 for two trajectories of two different cameras, how did you add the loops between the trajectories? Given that the registrations were in the camera space, and that both of the cameras start in the same identity pose (as shown in the multiway registration tutorial)
