### ISSUE TITLE
Consideration of color in global registration

### ISSUE THREAD

**Issue by christinaionescu** [isl-org/Open3D#4632]
Hi, 

I am referring to the issue: https://github.com/isl-org/Open3D/issues/733
Here it is said that the global registration pipeline includes the color information. Is this really true? I expected only the Colored ICP to include the color information and that the global registration only relies on the FPFH which depend only on the geometry.
Could you please elaborate?

Thank you!
Christina

**Comment by theNded** [comment]
You are right, technically global registration refers to FastGlobalRegistration and RANSAC, where color is not used. However, it is usually followed by colored ICP to refine the coarse global registration. So it really depends on the context: as a single algorithm, global registration does not include color; as a pipeline, it may include color.
