### ISSUE TITLE
Tuning of global registration

### ISSUE THREAD

**Issue by christinaionescu** [isl-org/Open3D#4636]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi,

I am currently trying the global registration with RANSAC to match two pointclouds.
How do you recommend tuning the algorithm? 
In my experience the chosen voxel size for downsampling influences the result a lot.
However, sometimes the matching works well while in other times its really bad. 
I would expect that if the algorithm is given enough iterations it can always find a suitable match but increasing the max_iteration doesn't really increase the performance?

Thank you!
Christina

**Comment by christinaionescu** [comment]
Follow up question:
http://www.open3d.org/docs/0.13.0/python_api/open3d.pipelines.registration.registration_ransac_based_on_feature_matching.html
I tried to use TransformationEstimationForColoredICP as estimation method but this is not possible in global registration, true?

**Comment by theNded** [comment]
Are you using the latest wheel? Could you please provide a code snippet that helps identify the problem?

For the second question, true, Colored ICP is not allowed in global registration -- we only use point-to-point transformation here.

**Comment by christinaionescu** [comment]
Sure!
So I want to find the model of "Stecker_modeled.ply" in the scenery "Stecker_scenery_part.ply":
In our use case the object we are searching for can be modeled beforehand ("Stecker_modeled.ply").
In the scenario the object is mounted together which other objects, therefore it is partially occluded as shown in "Stecker_scenery_part.ply".

What I found out so far is that the voxel size of 5.0 is necessary, reducing it leads to even worse results. Sometimes it works, sometimes it doesn't even with the same configuration. In "prepare_dataset" you can vary the initial transformation.

[fail](https://user-images.githubusercontent.com/70575304/150552268-0a2d7c93-1f4e-458e-895e-c1d1844d4d7a.png)
![okay](https://user-images.githubusercontent.com/70575304/150552272-7f6df53a-cce7-46d1-b7aa-b032b1e97c27.png)

You can find the code and the two point clouds in the zip file. 
[example_registration.zip](https://github.com/isl-org/Open3D/files/7914737/example_registration.zip)


Thank you!

**Comment by theNded** [comment]
0.13.0 is problematic. It is recommended to **really** follow the checklist and test the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip) before filing an issue :-)

**Comment by christinaionescu** [comment]
Hey sorry, my bad! I installed the latest version using "pip install --user --pre https://storage.googleapis.com/open3d-releases-master/python-wheels/open3d-0.14.1+b3e9897-cp39-cp39-linux_x86_64.whl"
However, the problem remains :/ Do you have any more remarks?

**Comment by theNded** [comment]
I can always get near-optimal results with this setup, and you may refine it with ICP.
```python
def execute_global_registration(source_down, target_down, source_fpfh,
                                target_fpfh, voxel_size):
    # distance_threshold = voxel_size * 1.5
    distance_threshold = voxel_size * 1.5
    print(":: RANSAC registration on downsampled point clouds.")
    print("   Since the downsampling voxel size is %.3f," % voxel_size)
    print("   we use a liberal distance threshold %.3f." % distance_threshold)
    criteria = o3d.pipelines.registration.RANSACConvergenceCriteria()
    criteria.max_iteration=10000000
    criteria.confidence=1
    result = o3d.pipelines.registration.registration_ransac_based_on_feature_matching(
        source_down, target_down, source_fpfh, target_fpfh, False,
        distance_threshold,
        o3d.pipelines.registration.TransformationEstimationPointToPoint(False),
        3, [
            o3d.pipelines.registration.CorrespondenceCheckerBasedOnEdgeLength(
                0.99),
            o3d.pipelines.registration.CorrespondenceCheckerBasedOnDistance(
                distance_threshold)
        ], criteria)
```
However, due to the symmetry of the shape, I still observe random failures occasionally, which is inevitable due to the handcrafted feature property.
