### ISSUE TITLE
Incorrect lines are displaying in visualizer.

### ISSUE THREAD

**Issue by shaikthouheed** [isl-org/Open3D#4637]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

I am trying to select points using VisualizerWithVertexSelection , After selecting points i want to draw lines.
When i draw the lines using LineSet, the lines are not in order. Most of time the lines not in order as i expected but sometimes it will be in order.

Point selection in order, and line i intended to draw[ What I was expecting]
![image](https://user-images.githubusercontent.com/45675542/150625461-dd307827-1893-4842-8dfe-1779fa5d6fc9.png)

What I usually get
![image](https://user-images.githubusercontent.com/45675542/150625466-51645b43-cf47-4a67-9516-7e301652ba7f.png)

### Steps to reproduce the bug

```python
#include<iostream>
#include <string>
#include <Open3D/Open3D.h>
using namespace std;
open3d::visualization::VisualizerWithVertexSelection visualizer;  //visualizer object creation
auto pcd_ptr = std::make_shared<open3d::geometry::PointCloud>();  //pointcloud object creation
auto lineSet = std::make_shared<open3d::geometry::LineSet>();     //LineSet for drawing line based on point selection
int main()
{
    int i = 0, j = 0;
    open3d::io::ReadPointCloud("Meetal nut.ply", *pcd_ptr);  //Open3D API to read point cloud data
    if (visualizer.CreateVisualizerWindow())
    {

        visualizer.AddGeometry(pcd_ptr);
    }
    //While loop to PollEvents from the Visualizer
    while (visualizer.PollEvents())
    {
        auto v = visualizer.GetPickedPoints();  //To store picked points
        if ((v.size() >= 6))
        {
            i = lineSet->points_.size();
            for (auto itr = v.begin(); itr < v.end(); itr++)
            {
                lineSet->points_.push_back(pcd_ptr->points_[itr->index]);
                if (j < v.size() - 1)
                    lineSet->lines_.push_back({ i  , i + 1 });
                else
                    lineSet->lines_.push_back({ i     ,   i  - v.size()+1 });
                j = j + 1;
                i = i + 1;
            }
            i = 0;j=0;
            visualizer.AddGeometry(lineSet, false);  //Need it for every Iteration

            visualizer.AddGeometry(pcd_ptr, false);   //Need it for every Iteration for updating the visualizer with latest pointcloud data

        }
    }
}
```

### Non Interactive Code, I already given the points with which i want to draw lines.

```C++
#include<iostream>
#include <string>
#include <Open3D/Open3D.h>
using namespace std;
open3d::visualization::VisualizerWithVertexSelection visualizer;  //visualizer object creation
auto pcd_ptr = std::make_shared<open3d::geometry::PointCloud>();  //pointcloud object creation
auto lineSet = std::make_shared<open3d::geometry::LineSet>();     //LineSet for drawing line based on point selection
std::vector<int> v = { 58660,274818,61015,19026,51248,13534 };
int main()
{
    int i = 0, j = 0;
    open3d::io::ReadPointCloud("Meetal nut.ply", *pcd_ptr);  //Open3D API to read point cloud data
    if (visualizer.CreateVisualizerWindow())
    {
        visualizer.AddGeometry(pcd_ptr);   //Need it for every Iteration for updating the visualizer with latest pointcloud data
        
        for (auto itr = v.begin(); itr < v.end(); itr++)
        {
            lineSet->points_.push_back(pcd_ptr->points_[*itr]);
            if (i < v.size() - 1)
                lineSet->lines_.push_back({ i  , i + 1 });
            else
                lineSet->lines_.push_back({ i     ,   i - v.size() + 1 });
            i = i + 1;
        }
        visualizer.AddGeometry(lineSet);  //Need it for every Iteration
        visualizer.AddGeometry(pcd_ptr);   //Need it for every Iteration for updating the visualizer with latest pointcloud data
        
    }
    while (visualizer.PollEvents());
           
}
```
### Error message
When i want to draw line, The lines are not in order as i expected
_No response_
![image](https://user-images.githubusercontent.com/45675542/150534499-89fe2be1-de25-4767-ad5d-4633cec279da.png)

### Expected behavior
This is my expected behaviour
_No response_
![image](https://user-images.githubusercontent.com/45675542/150534548-67736714-b585-4f36-bc50-d6cef9371d8e.png)

### Open3D, Python and System information

```markdown
- Operating system: ( Windows 10 64-bit)
- Language : C++
- Open3D version: latest
- System type: (x64) Intel
- Is this remote workstation?: no
- How did you install Open3D?: (build from source)
- Compiler version (if built from source): MSVC studio 2019 with CMAKE
```

### Additional information

I implemented it in C++.
.Ply file used in this example is attached.
[Meetal nut.zip](https://github.com/isl-org/Open3D/files/7913928/Meetal.nut.zip)

**Comment by theNded** [comment]
You started with `i = lineSet->points_.size();` when you construct a line set. The lineset expect the indices to start from 0.

**Comment by shaikthouheed** [comment]
@theNded 
Even though I start with i=0 to build the line set. It still gives the same behavior. I have put i=lineset->points_.size() because I want to keep it in loop and make it dynamic.

**Comment by shaikthouheed** [comment]
@adamlofts @benjaminum @FreakTheMighty @theNded 
Team i request to reopen this issue.

**Comment by theNded** [comment]
Please provide a reproducible example without interactions. This example depends on interactive point selection.

**Comment by shaikthouheed** [comment]
@theNded Given example code without interactions

**Comment by theNded** [comment]
For the selected points, I painted them in order with [1,0,0] (red), [0,1,0] (green), [0,0,1] (blue), [1,1,0] (yellow), [0,1,1] (cyan), [1, 0, 1] (magenta) and it turns out your presumed index order was wrong. The lineset worked as expected.
![image](https://user-images.githubusercontent.com/6127282/150643469-77c8c261-19f7-453b-9204-817994b3e6df.png)

**Comment by shaikthouheed** [comment]
@theNded I have found out the issue, I will mention it here, if you think it is bug please reopen the issue.
When I select points interactively and query it with "auto v = visualizer.GetPickedPoints();" the order of points are which i selected and the order of points which I get with visualizer.GetPickedPoints() are different. that`s the reason I am not able to get the lines correctly.

What I mean to say is.
If i select points in 1,2,3,4,5,6 order.
visualizer.GetPickedPoints() are giving some weird ordering like: 1,3,2,5,4,6 [It is differing ]

So I think there is some issue in visualizer.GetPickePoints().

Please consider if this is possible bug.
Thanks :)

**Comment by shaikthouheed** [comment]
@theNded @adamlofts @benjaminum @FreakTheMighty 
Team I request to review once again with the latest update i given and consider opening the issue if there is possible bug.
Thanks

**Comment by theNded** [comment]
See response in #2156.
