### ISSUE TITLE
How to get the projection matrix using open3d.visualization.rendering.Camera

### ISSUE THREAD

**Issue by TheDech** [isl-org/Open3D#4646]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi,

I need to map the pixel from a RGB image to 3D coordinates. I would like to use the projection matrix using the open3d.visualization.rendering.Camera but I am confused about how to use it as it has no argument?
Also is there a more straightforward way to get the pixel mapped to 3D.

Thank you

**Comment by TheDech** [comment]
Any update about this question?

**Comment by errissa** [comment]
If you are trying to project a 2D coordinate back into 3D space you can do that with `Camera.unproject` which takes an x,y in screen coordinates, the depth buffer value at x,y and the width and height. It will return the 3D coordinates of that point.

**Comment by errissa** [comment]
Please reopen this issue if you still have questions.

**Comment by charlesstempniak** [comment]
> ### Checklist
> * [x]  I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
> * [x]  For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
> * [x]  I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).
> 
> ### My Question
> Hi,
> 
> I need to map the pixel from a RGB image to 3D coordinates. I would like to use the projection matrix using the open3d.visualization.rendering.Camera but I am confused about how to use it as it has no argument? Also is there a more straightforward way to get the pixel mapped to 3D.
> 
> Thank you

I'm interested on the same thing. @TheDech , do you have success on remapping the original image to the 3D point cloud space?

**Comment by alexs7** [comment]
@errissa 

Can you please let me know how to use  `o3d.visualization.rendering.Camera.unproject()` ?

I try to use it as this:
 `o3d.visualization.rendering.Camera.unproject(120.0, 900.0, 1000.0, 1920.0, 1080.0)`
and I get:
```
*** TypeError: unproject(): incompatible function arguments. The following argument types are supported:
    1. (self: open3d.cuda.pybind.visualization.rendering.Camera, arg0: float, arg1: float, arg2: float, arg3: float, arg4: float) -> numpy.ndarray[numpy.float32[3, 1]]
```

Isn't it a static method ?

**Comment by YuenaQiao** [comment]
> @errissa , @TheDech
> 
> Can you please let me know how to use `o3d.visualization.rendering.Camera.unproject()` ?
> 
> I try to use it as this: `o3d.visualization.rendering.Camera.unproject(120.0, 900.0, 1000.0, 1920.0, 1080.0)` and I get:
> 
> ```
> *** TypeError: unproject(): incompatible function arguments. The following argument types are supported:
>     1. (self: open3d.cuda.pybind.visualization.rendering.Camera, arg0: float, arg1: float, arg2: float, arg3: float, arg4: float) -> numpy.ndarray[numpy.float32[3, 1]]
> ```
> 
> Isn't it a static method ?
Hi, I also encountered this problem. Have you successfully solved it？

**Comment by TheDech** [comment]
Hi @YuenaQiao,

The method proposed didn't work for me, i used the api of my camera. The new version of the version could work. Try to enter it as an array?

**Comment by YuenaQiao** [comment]
Hi @TheDech, 

Thanks for your help. If possible, could you guide me to the new version of the unproject function or share how you managed to obtain 3D coordinates?

I attempted to follow the documentation's formulation at http://www.open3d.org/docs/0.7.0/python_api/open3d.geometry.create_point_cloud_from_rgbd_image.html to obtain the pixel's 3D coordinates. I successfully obtained the pcd of the RGB image, with the center point coordinates being [1.45211462e-05, -6.13778022e-05, 2.30853332e-03]. However, when I obtained the point cloud using the following code:
pcd = o3d.geometry.PointCloud.create_from_rgbd_image(rgbd_image, cam.intrinsic)
the center point coordinates were different from the previous ones: [1.77928369e-05, -7.52065432e-05, 2.82865799e-03].

Although the visualizations of these two versions look nearly the same, the first one has some outliers.  I think I might have missed some operations, but I don't know how to make the first one match the results of "create_from_rgbd_image".

Does Open3D provide any correspondence between the 2D RGB images and 3D point cloud after getting the pcd by "create_from_rgbd_image" function?

I hope these questions are clear. And thanks for your help and time in advance.

**Comment by TheDech** [comment]
Hi @YuenaQiao,

I used the function obb.getcenter() to obtain the coordinates of the pixel,where obb  is the pointcloud. Related functions can be found here [http://www.open3d.org/docs/release/python_api/open3d.geometry.Geometry3D.html?highlight=get_oriented_bounding_box#open3d.geometry.Geometry3D.get_oriented_bounding_box](url).

For the unproject function, there is no function in the 0.17.0 version but still can find it in 0.16.0.
From the docs, the function takes the (x, y, z) location in the view, where x, y are the number of pixels from the upper left of the view, and z is the depth value. Returns the world coordinate (x’, y’, z’).
In the latest version, you can find the new version of the function in mouse_and_point_coord.py.

I can't answer about the correspondence between 2D and 3D point function but you can always start with:
`z = d
x = (u - cx) * z / f
y = (v - cy) * z / f

// where (cx, cy) is the principle point and f is the focal length.`

TheDech

**Comment by YuenaQiao** [comment]
> Hi @YuenaQiao,
> 
> I used the function obb.getcenter() to obtain the coordinates of the pixel,where obb is the pointcloud. Related functions can be found here [http://www.open3d.org/docs/release/python_api/open3d.geometry.Geometry3D.html?highlight=get_oriented_bounding_box#open3d.geometry.Geometry3D.get_oriented_bounding_box](url).
> 
> For the unproject function, there is no function in the 0.17.0 version but still can find it in 0.16.0. From the docs, the function takes the (x, y, z) location in the view, where x, y are the number of pixels from the upper left of the view, and z is the depth value. Returns the world coordinate (x’, y’, z’). In the latest version, you can find the new version of the function in mouse_and_point_coord.py.
> 
> I can't answer about the correspondence between 2D and 3D point function but you can always start with: `z = d x = (u - cx) * z / f y = (v - cy) * z / f
> 
> // where (cx, cy) is the principle point and f is the focal length.`
> 
> TheDech

Thank you for being so patient in answering my question. It helps me a lot!
