### ISSUE TITLE
the results from reconstruction system with realsense l515 is worse than that from tutorial data(016)

### ISSUE THREAD

**Issue by xiang-zhe** [isl-org/Open3D#4649]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

os: ubuntu20.04
python: 3.8
open3d: pip install open3d
open3d.__version__: '0.14.1'
camera: realsense l515

test on [016](https://drive.google.com/open?id=11U8jEDYKvB5lXsK3L1rQcGTjp0YmRrzT); it looks well
```
camera_intrinsic.json, 
{
    "width": 640,
    "height": 480,
    "intrinsic_matrix": [
        518,
        0,
        0,
        0,
        519,
        0,
        325,
        253.5,
        1
    ]
}
```
![2022-01-21 11-26-13 的屏幕截图](https://user-images.githubusercontent.com/36883691/150736285-4dbc5d07-613f-4d46-92a1-84449cb1ad5e.png)

but when i capture use realsense l515, the results look bad, there are **two main problems**,
1,some fragments are broken and some have ghosting
![2](https://user-images.githubusercontent.com/36883691/150738125-ecd548bb-1d71-4963-8f6b-0d269d229986.png)
2, after integration, it not completed, it seem loss a lot of fragments (this result from some fragments are broken?)
![2022-01-21 11-29-16 的屏幕截图](https://user-images.githubusercontent.com/36883691/150738153-5123af43-7105-47de-ace9-4dd11914c15d.png)
i test many times in my room using command like 
first, `python3 sensors/realsense_recorder.py --record_imgs`,
then, `python3 run_system.py ../dataset/room.json --make --register --refine --integrate`
i tried 400 images to 3000 images in resolution both 1920x1080(aligned), 960x540(aligned),
and i tried moving camera slowly,
and because of the short use data line of realsense l515(which linked into host computer), so camera trajectory is limited(is that important),
maybe there are some tricks when capturing images, i don't know;
any helps will be great appreciated!!

**Comment by theNded** [comment]
Please use the correct intrinsic matrix instead of the default one. Also, please try to avoid reflective surfaces.

**Comment by xiang-zhe** [comment]
thanks, theNded; 
> Please use the correct intrinsic matrix instead of the default one. 
but when using reconstruction system by `python3 sensors/realsense_recorder.py --record_imgs`, the code will generate camera intrinsic in folder, matrix of my realsense l515 is like(didn't show above)
```
{
    "width": 1920,
    "height": 1080,
    "intrinsic_matrix": [
        1358.5245361328125,
        0,
        0,
        0,
        1358.778076171875,
        0,
        979.2344360351562,
        544.2269897460938,
        1
    ]
}
```
and i use the matrix to  generate points by 
```
cam_intrinsic = o3d.core.Tensor(
            rs.get_metadata().intrinsics.intrinsic_matrix,
            dtype=o3d.core.Dtype.Float32,
            device=o3d.core.Device("cuda:0"))
cam_extrinsic = o3d.core.Tensor.eye(4, dtype=o3d.core.Dtype.Float32, device=o3d.core.Device("cuda:0"))
pcd = o3d.t.geometry.PointCloud.create_from_rgbd_image(im_rgbd, cam_intrinsic)
pcd = pcd.to_legacy()
```
it works and looks normally
![2022-01-25 09-39-04 的屏幕截图](https://user-images.githubusercontent.com/36883691/150895443-5d166e4a-9b05-4c75-959d-4be92bca10db.png)
.
![2022-01-25 09-39-04 的屏幕截图](https://user-images.githubusercontent.com/36883691/150895468-11e48050-755d-44bf-b4f7-94cc185b19c5.png)

>  Also, please try to avoid reflective surfaces.
**i also tried to capture my bed, many fragments show like a slender strip, it look weird **
![2022-01-25 11-00-37 的屏幕截图](https://user-images.githubusercontent.com/36883691/150903026-f23e4ea8-c15a-43e3-8e5a-1aa8073ca8eb.png)
**the integrated scene show like**
![2022-01-25 11-00-15 的屏幕截图](https://user-images.githubusercontent.com/36883691/150903525-8f65264a-b964-4b2b-826a-deac27016cd5.png)
but in fact i captured the whole bed, include wall along, rgb images like
![000437](https://user-images.githubusercontent.com/36883691/150903738-64dd64c0-37b7-4f7a-b433-46d7556ef674.jpg)
but those farther（maybe more than 1meter away）was missing,  and not included in fragments,  
```
config.json
{
    "name": "Realsense bag file",
    "path_dataset": "../dataset/realsense",
    "path_intrinsic": "../dataset/realsense/camera_intrinsic.json",
    "max_depth": 3.0,
    "voxel_size": 0.05,
    "max_depth_diff": 0.07,
    "preference_loop_closure_odometry": 0.1,
    "preference_loop_closure_registration": 5.0,
    "tsdf_cubic_size": 3.0,
    "icp_method": "point_to_point",
    "global_registration": "ransac",
    "python_multi_threading": true
}
```
**than i set max_depth to 5, it seems better**,
![2022-01-25 11-32-45 的屏幕截图](https://user-images.githubusercontent.com/36883691/150906210-5e21cde3-6698-4a63-81eb-6e9cd8cf57c9.png)
**than i set max_depth to 9, it seems normal, **,
![2022-01-25 12-13-50 的屏幕截图](https://user-images.githubusercontent.com/36883691/150921516-8734048a-a56b-416c-a7f5-d0cd715e9621.png)

when integrating, it take about 64G RAM（almost 100% on my computer host which has 64G RAM), is that normal? image resolution  
but my room  only 3x4 m2, is that depth_scale was set wrong, any advices,thanks

**Comment by xiang-zhe** [comment]
i can get the right distance after set depth_scale to 4000 in initialize_config.py

**Comment by theNded** [comment]
Thanks, I will fix it in the config generation.
