### ISSUE TITLE
DLL Load failed while importing pybind (win10 industrial tablet). [Error]

### ISSUE THREAD

**Issue by GHCK57** [isl-org/Open3D#4652]
### Error message

```shell
Exception has occured: ImportError x

DLL load failed while importing pybind.  

File XxX in Line Xx. The line is :

" from open3d.cpu.pybind import (camera, geometry, io, pipelines, utility, t) "
```

### Open3D, Python and System information

```markdown
- Operating system: (Windows 10 64-bit)
- Python version: (Python 3.8 )
- Open3D version: (0.14.1)
- System type: (Windows Industrial Tablet - 4GB Ram 64bit )
```

### Additional information

Hi All,

I wrote a python code with using open3d library in desktop pc. The code works on desktop pc . But I need the use the industrial tablet that operation system is win10. When I run the code on tablet, the error has occured. The error is "dll load failed while importing pybind" . I checked out the line that in occured error message. It is

```
> if __DEVICE_API__ == 'cpu':
>     from open3d.cpu.pybind import (camera, geometry, io, pipelines, utility, t)
>     from open3d.cpu import pybind
```

The open3d lib trying to import pybind but it gives error. 

What should I do ? 

Best regards.

**Comment by yxlao** [comment]
How did you install Open3D on the tablet? Did you use a virtual environment?

**Comment by GHCK57** [comment]
I installed the open3d with pip

**Comment by GHCK57** [comment]
It is same error with this issue https://github.com/isl-org/Open3D/issues/4468#issue-1084133205  . But I didn't find how to fix it.

**Comment by GHCK57** [comment]
Hi all, 

I tried the code with different computer with different operating system like linux,win xp. It works. Does this problem caused due to graphics card ?

And how I install old version of open3d ?

**Comment by GHCK57** [comment]
Hi all,

I solved the problem by installing old version of open3d library. 

I applied the following steps :

1-) To check the current version of open3d  use  --> **pip show open3d**   

 the version 0.14.1 was  installed on my computer.

2-) Uninstall the current open3d library using --> **pip uninstall open3d**

3-) Then reinstall the old version of open3d using --> **pip install open3d==0.13.0**   

The list of the version of open3d lib:

![image](https://user-images.githubusercontent.com/97222370/151126100-b8a4c89f-800b-4eca-800a-23f3eda0be9e.png)

**Comment by Rushour0** [comment]
The solution is to install the Windows SDK / Desktop Development for C++, C++ Libraries via Visual Studio Community
The missing DLLs are ```API-MS-CORE``` related
The downloading of Windows SDK / Desktop Development libraries resolves this issue of open3d

**Comment by whizbuzzer** [comment]
> Windows SDK / Desktop Development for C++, C++ Libraries

Could you elaborate on exactly what I need to install?

**Comment by GHCK57** [comment]
Hi
First you should download and install Visual Studio Community. You can find it at this link.
https://visualstudio.microsoft.com/tr/vs/community/

After that I think it will be enough to install **"Dektop development with C++"**  dont select the others

![image](https://user-images.githubusercontent.com/97222370/192207540-11e139f2-e177-4304-aea8-f1acbae4e01f.png)

**Comment by whizbuzzer** [comment]
@GHCK57 Thank you so much! It works now even on VSCode!

**Comment by Rushour0** [comment]
> Hi First you should download and install Visual Studio Community. You can find it at this link. https://visualstudio.microsoft.com/tr/vs/community/
> 
> After that I think it will be enough to install **"Dektop development with C++"** dont select the others
> 
> ![image](https://user-images.githubusercontent.com/97222370/192207540-11e139f2-e177-4304-aea8-f1acbae4e01f.png)

Hey,
I think we can mark the issue as closed now?
The solution I mentioned before worked out right?

https://github.com/isl-org/Open3D/issues/4652#issuecomment-1089140999

**Comment by GHCK57** [comment]
Hi,

Yes, Your solution has double checked and it works fine. Thanks again.
