### ISSUE TITLE
Output of ray casting in voxel block grid with smaller image size not complete

### ISSUE THREAD

**Issue by Fuhrmann-sep** [isl-org/Open3D#4658]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

While doing ray casting in voxel block grid with different rendered image size and corresponding intrinsic, it seems last few rows of pixel values are missing.
The example I'm using is [ray_casting.py](examples/python/t_reconstruction_system/ray_casting.py)
The original output of raycasting:
<img src="https://user-images.githubusercontent.com/44905627/151219694-1b4a1d3c-e754-4d3c-a47d-0def171e5818.png" width="282" height="221" />
But I'd like to render a smaller image, with expected image size of `cast_shape = np.array([60, 80])`, 
the intrinsic used is 
<pre>ratio = 1/8    
cast_intr = intrinsic.numpy().copy()
cast_intr[:2, :] = cast_intr[:2, :] * ratio
cast_intr = o3c.Tensor(cast_intr)</pre>
The code in the example is modified as:
<pre>result = vbg.ray_cast(block_coords=frustum_block_coords,
                      intrinsic=cast_intr,
                      extrinsic=extrinsic,
                      width=cast_shape[1],
                      height=cast_shape[0],
                      render_attributes=[
                          'depth', 'normal', 'color', 'index',
                          'interp_ratio'
                      ],
                      depth_scale=config.depth_scale,
                      depth_min=config.depth_min,
                      depth_max=config.depth_max,
                      weight_threshold=1)</pre>

The output images:
<img src="https://user-images.githubusercontent.com/44905627/151219750-bdaf3d35-a70e-42db-97a3-9961be0ff797.png" width="282" height="221" />

It seems the last few rows are missing. I'm not quite sure if I did something wrong. 

Any comment is appreciated. Thanks.

**Comment by theNded** [comment]
Thanks for the report. I can reproduce the issue on this and other datasets, will be working on it.

**Comment by theNded** [comment]
I have identified the issue. 
Internally, we create a coarse near/far range buffer (similar to OpenGL's depth clipping) to speed up ray casting. By default the range map's resolution is 1/8 of the original input. For your case, however, this configuration results in a very low-resolution range buffer that leads to imprecise clipping distances. It can be resolved by changing this parameter.

I exposed this API in #4670 and the code snippet will look like:
```python
result = vbg.ray_cast(block_coords=frustum_block_coords,
                              intrinsic=intrinsic_down,
                              extrinsic=extrinsic,
                              width=cols_down,
                              height=rows_down,
                              render_attributes=[
                                  'depth', 'normal', 'color', 'index',
                                  'interp_ratio',
                              ],
                              depth_scale=config.depth_scale,
                              depth_min=config.depth_min,
                              depth_max=config.depth_max,
                              weight_threshold=1,
                              trunc_voxel_multiplier=8.0,
                              range_map_down_factor=1)
```
Before (`range_map_down_factor=8`):
![Screenshot from 2022-02-01 12-38-37](https://user-images.githubusercontent.com/6127282/152020925-ed8ad6a1-282b-4c3a-bef7-c4dd355f22e5.png)
After (`range_map_down_factor=1`):
![Screenshot from 2022-02-01 12-39-21](https://user-images.githubusercontent.com/6127282/152021033-9e8a2c0c-500f-4d37-91f4-37719674a18c.png)

I will close the issue now. Please wait for the merge of the PR and try again. Feel free to reopen if other problems occur.
