### ISSUE TITLE
Improve pose graph optimization results

### ISSUE THREAD

**Issue by szx0112** [isl-org/Open3D#4659]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi, I am trying to obtain the best result I can while using the open3d reconstruction system. I have read the relevant papers: **Robust Reconstruction of Indoor Scenes** and **Colored Point Cloud Registration Revisited**. Now I have following two questions when I implement them using open3d.

(1) Even ColoredICP use color information for the frame-to-frame and fragment-to-fragment alignments, the graph optimization only use the geometric information (i.e., distance between correspondences) as the error function. It seems this might lead to the optimization with worse result than the prior alignments (using coloredICP) on scenes without distinct geometric features (.e.g, cylinder pipe or a simple planar surface with textures). Am I understand it correctly? If yes, is it possible to actually incorporate the color/texture into the optimization (e.g., customize the information matrix)?

(2) If the ground truth (relative) transformations between some non-overlapped camera poses are known, does these information improve the optimization results (by connecting these non-adjacent nodes with edge type as odometry)? 
Based on my understanding, pose graph optimization use information matrix to collect the errors between the poses. Since there are no overlapping between these poses, the information matrix can not be properly computed. Is there any way to bypass the information matrix and make the optimization still works under such condition?

Any comment is appreciated. Thanks.

**Comment by theNded** [comment]
They are all very good questions.
For 1) the information matrix is always constructed with J^T J where J is the Jacobian matrix under certain error metrics. We are typically using information from the point-to-point metric which is the standard, but I guess using that from ColoredICP is also possible. I haven't tested that though.
For 2) if we have GT transformation, we usually regard them as a rigid body, and parameterize it with one variable. It requires some transformations of the information matrices respectively.

**Comment by theNded** [comment]
I will close this issue since they are still open-ended research questions. Feel free to shoot me an email if you want further discussions.

**Comment by szx0112** [comment]
Sure. Thanks for the explanation.
