### ISSUE TITLE
How to add the Label3D Text to GUI::SceneWidget in Open3D?

### ISSUE THREAD

**Issue by vanloctc** [isl-org/Open3D#4662]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi Open3D Teams and Everyone, 

I am using the Open3D (Ver 0.13.0 C++) for the reconstruction 3D Map. There is no problem with the generated 3DMap process. 
I want to add the Label3D-Text on Point - Trajectory - in generated 3DMap process but when I added the Label3D to SceneWidget, the position of Label3D-Text is not match with the point 3DMap. 

1. See the image below, the trajectory when generated 3DMap and the "trajectory" of Label3D-Text is the same about the shape but wrong about the position. 
![saveImage1](https://user-images.githubusercontent.com/48701460/151368299-1382d8ef-ffd4-40e2-b303-0d6fd21fe417.png)

2. See the image below, I had tried with the {0,0,0} point for both Trajectory and Label3D-Text. But it also does not match.
![saveImage2](https://user-images.githubusercontent.com/48701460/151368841-58f3d597-7aaf-46b7-a809-c5e9a1e6ebf1.png)

3. I think that having a transformation matrix makes the position of Trajectory and Label3D-Text not match together?
See the image about, the source code for (2) above:
![SaveImage3](https://user-images.githubusercontent.com/48701460/151369945-b15a8bf9-eecc-419c-ba76-d6db638ac289.png)

The source code: [DenseSLAMGUI.cpp](https://github.com/isl-org/Open3D/blob/master/examples/cpp/DenseSLAMGUI.cpp)
Thank you very much,

**Comment by vanloctc** [comment]
I had found an ideal for this issue.
I think the reason make the Label3DText is not matched with the position (traject) display on the scene are due to "SetFrame" (layout)
1. See the image below. The Label3DText is not matched with the position (traject)
The Viewer had a resolution of 1280x800
+) Panel (for settings): 0 to 320 pixel (not mention to height)
+) Scene (Display 3DMap): 320 to 1280 pixel (not mention to height) 
![Original](https://user-images.githubusercontent.com/48701460/154315994-5f21ee44-a893-42d2-9ae9-2c41bf57213e.png)

2. See the image below. The Label3DText is matched with the position (traject)
The Viewer had a resolution of 1280x800
+) Panel (for settings): 0 to 320 pixel (not mention to height)
+) Scene (Display 3DMap):  1280 pixel, it will override on panel region (not mention to height) 
![Custom](https://user-images.githubusercontent.com/48701460/154316823-82dec041-8fd7-4d35-bda9-e0948ea0e68a.png)

3. It seems to after "SetFrame" for the scene, the Label3D (AddLabel) is not updated on a new scene (such as updated from 320 to 1280 pixel - 1 above - or such as "3DMap" updated on the new scene). The Label3D (AddLabel) just update at the old scene with the original resolution, is that true? and is there any way for overcoming this issue without using the 2 above?

Thank you very much,

**Comment by errissa** [comment]
@vanloctc Thank you for this report. It is now fixed by PR #4775
