### ISSUE TITLE
How often are pywheels are build and backporting bugs

### ISSUE THREAD

**Issue by muratmaga** [isl-org/Open3D#4669]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

We use open3d as a dependency for a published 3D morphometrics method to do automated landmark transfer (https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.13689) 

The implementation is in 3D Slicer (https://github.com/SlicerMorph/SlicerMorph). So far we have been using version 0.10. However, due to recent python changes (from 3.6.7 to 3.9.0), we can no longer pip install v0.10 due to incompatibility. The latest available pywheel 0.14.1 does not work us due to this we bug we filed and fixed (see https://github.com/isl-org/Open3D/issues/4539). 

So we are sort of stuck. When can we anticipate a new pywheel with this bug fixed or is it possible for you to backport and rebuild the current wheel with this change?

**Comment by ssheorey** [comment]
HI @muratmaga we will release `v0.15` with the bug fix in the next two weeks. 
We are not able to backport fixes, but you can download the[ latest master branch Python wheel,](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip) save it locally, and use that as a dependency in the meantime.

**Comment by chz31** [comment]
Hi Open3D team,

Just a follow-up, this bug-fixed development version of open3d (**open3d version '0.14.1+08c5c79' and '0.14.1+b449b58'**) mentioned in the last post still has issues about RANSAC registration when running in **Python 3.9.10 in Linux** as discussed in #4539 . 

I ran the code to register the same set of mouse skull models in **Python 3.9. 10 in Linux** for multiple times. In a few cases, the mouse skulls are still misaligned (as the screenshot shows). **The '0.14.1+b449b58' version so far appears to be fine with Python 3.9 in Windows after multiple tests.** I haven't tested it in Mac. 
![image](https://user-images.githubusercontent.com/80793828/152069010-d3947376-1a8a-441f-ad5d-6ab075e93882.png)

I used the same script and pilot data for #4539. **You may clone or download the repository as zip file that contains the data (mouse ply files) and scripts here: https://github.com/chz31/o3d_test .** The "data" folder in the repository "o3d_test" contains the mouse models for you to test.

The script is in "test_scripts" folder. **The "test_0.14.1.py" contains script using open3d 0.14.1+08c5c79.**

For this script, please modify three variables for accessing and output data (line 130 to 136 for test_0.14.1.py):
" **sourceFileDir**" points to the folder that contains the mouse models downloaded from the Github repo I provided above.
"**targetFileDir**" points to a specific model "129_S1" in the "sourceFileDir" that serves as the universal target for registration.
"**outDir**" points to the folder that stores the mouse models register to the target "129_S1"

After specifying the above three directories and path, you can run in your python console or cmd by using the code:

  **path = "Enter_Your_Directory_that_stores_the_script/test_0.14.1.py"** #Specify the path to test o3d 0.13.0.py
  
  **exec(open(path).read())** #The registered models will be stored in "outDir"

Please let me know if you have any issues running the code or any further information. 

Thank you very much!

**Comment by theNded** [comment]
RANSAC is a random algorithm and results can go wrong with a probability. Increase the confidence (to as much as 1.0) and iterations and follow the instructions in #4539.

**Comment by theNded** [comment]
FYI, I use this command to align `129_S1` and all the other samples more than 10 times and it never fails. I suspect you haven't configured your environment or parameters properly.
```
python examples/python/pipelines/registration_ransac.py ~/Workspace/code/o3d_test/data/129S1_SVIMJ_.ply ~/Workspace/code/o3d_test/data/NZW_LACJ_.ply   --voxel_size 0.5 --confidence 0.999 --max_iterations 1000000
```

**Comment by muratmaga** [comment]
@theNded thank you we will try those parameters. 

But the current issue is given the same parameter set and the input, why are we getting different results on different operating systems on the same codebase? This is the parameter dictionary. 
https://github.com/chz31/o3d_test/blob/24758002bb06fad49fb2dfc5fe305ba3392d562e/test_scripts/test_0.14.1.py#L116-L117

**Comment by theNded** [comment]
As I have mentioned many times, RANSAC is a **RANdom** algorithm and the results do have variance. You change parameters properly to improve your odds.

However, the reported failure cannot be reproduced on my Linux machine after repetitive trials so I highly suspect the configuration goes wrong somewhere.

**Comment by chz31** [comment]
@theNded Thank you very much for your time and suggestion! 

Last time I did follow your suggestions to manually set up the voxel size and align the models I provided well using open3d 13.0, but I still encountered issues with other mouse models I have (which were all well aligned in repeated tests using 0.10.0's default setting). 

The newest open3d with bug fixed did show highly consistent RANSAC results in Windows. I'll surely try different parameters again in Linux.

**Comment by theNded** [comment]
You may also want to double-check if the version is really up to date by `print(o3d.__version__)`. Sometimes a mismatch may lead to issues. 
Please do play with the Open3D's example as mentioned above and let me know the exact file names if it still fails. Your code is not easy to modify in CLI, so we'd better keep on the same page.

**Comment by chz31** [comment]
The version I'm currently testing is 0.14.1+b449b58 I downloaded here http://www.open3d.org/docs/latest/getting_started.html#development-version-pip . Hope it is the most updated one. 

I'll use the your snippet in #4539 to test specific models and let you know if I encounter the issue again. Thank you!

**Comment by chz31** [comment]
@theNded I tried the voxel size 0.3 in Linux with the newest python wheel and the registration works well for most tests so far. 

Thank you very much again for your help!
