### ISSUE TITLE
How to generate point cloud with camera matrix

### ISSUE THREAD

**Issue by SpOOnySk** [isl-org/Open3D#4673]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hello, I have a problem creating PC. When I pass my calibrated camera matrix into PC it looks weird and nothing like on open3D website where the wall is nice. Anyone has any idea what is the problem? ... I tried different camera matrix but nothing works.

![image](https://user-images.githubusercontent.com/72028304/151710760-bf6f1b62-126d-49ca-99d1-d2892865f04d.png)

is there any way to make it look like this?

![image](https://user-images.githubusercontent.com/72028304/151710813-ea7579c8-0c6a-4fa5-98b3-698c3d3c8def.png)

**Comment by ssheorey** [comment]
Hi @SpOOnySk please add the code that gave you this result.

**Comment by theNded** [comment]
The input looks like inverse depth. Please invert it appropriately. 
Also, if your depth is predicted from images, there is no guarantee that it looks as good as from depth cameras.
