### ISSUE TITLE
ICP registration - Deviations between source and target file

### ISSUE THREAD

**Issue by Sralelb** [isl-org/Open3D#4687]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I used the example for icp registration from: 
[http://www.open3d.org/docs/0.7.0/tutorial/Basic/icp_registration.html](url) 
to compare cad data. I did not change that much of the example code, basically played around with "threshold" parameter and added a convergencecriteria with "max_iteration=2000". 
My example is basically only a 2d-problem. I want to compare both contures and find a good fit solution instead position it by hand.
The result looks even promising but there are some mistakes if you have a closer look. Obviously it seems to me that the angle between contiur 1 and 2 is not correct yet (look at the red marked spots). If have attached a snapshot of both contures before point-to-point ICP and afterwards, as well as my used data.

![draw_registration_before](https://user-images.githubusercontent.com/54818357/152156590-be1f668b-0c2b-4503-8ab4-7554661ef28e.JPG)

![draw_registration_after2](https://user-images.githubusercontent.com/54818357/152157585-74d8f6e7-a7e0-433c-9c39-dfba157bb88a.JPG)

[Aufriss_Original_Punkte.txt](https://github.com/isl-org/Open3D/files/7986465/Aufriss_Original_Punkte.txt)
[Profilscan Reklamation_Punkte.txt](https://github.com/isl-org/Open3D/files/7986466/Profilscan.Reklamation_Punkte.txt)
.

**Comment by theNded** [comment]
ICP only guarantees local optimal solutions. Unfortunately, to the best of my knowledge, I don't think any automatic algorithms can perfectly align your surfaces due to their non-linearity, high local similarity, and partial incompleteness.
