### ISSUE TITLE
Want example/some way to get eight vertices of each child in octree data structure implemented using open3D.

### ISSUE THREAD

**Issue by shashankIITK** [isl-org/Open3D#4688]
I want to implement frustum culling using octree for my project on pointcloud. For this I need eight vertices of each child node (bounding volume) in octree implemented on 3D data. I have gone through functionalities of octree in documentation but could not found any function which can give me such eight vertices of each cube in which we go on dividing space in octree. Kindly help me if this is possible with ope3D with example.

**Comment by theNded** [comment]
You can refer to [this example](http://www.open3d.org/docs/release/tutorial/geometry/octree.html#Traversal). The bounding box can be easily computed given the known octree voxel size and node origin and depth.

**Comment by shashankIITK** [comment]
Can you please tell what does node origin refers to here?  It is not clear from documentation.
Also how to get voxel size (for every child or for entire bounding box of whole scene for that matter) ?

**Comment by theNded** [comment]
You may refer to how Open3D renders an Octree: https://github.com/isl-org/Open3D/blob/master/cpp/open3d/visualization/shader/SimpleShader.cpp#L744-L754

Here, `node_info->origin_` locates a node, [cuboid_vertex_offsets](https://github.com/isl-org/Open3D/blob/master/cpp/open3d/visualization/shader/SimpleShader.cpp#L44) generates all 8 vertices, and `node_info->size_` gives the voxel size.

**Comment by shashankIITK** [comment]
I am working with python. Can you share some method using which I could get all 8 vertices of each children of octree? and I couldn't get what is origin by the link you have shared. Please help me.

**Comment by theNded** [comment]
I already gave you a python example and an explanation of how to generate vertices. 
Origin apparently is the origin point that you put (0,0,0) at a voxel. Please study the basics of octrees and figure out the rest.
