### ISSUE TITLE
Memory Leak with registration_fgr_based_on_feature_matching

### ISSUE THREAD

**Issue by michezio** [isl-org/Open3D#4694]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

When registering two point clouds in a loop with `open3d.pipeline.registration.registration_fgr_based_on_feature_matching`, after a while it gets stuck indefinitely with a memory leak filling up the entire RAM available. Most of the times no error message is displayed and the only way to stop is to force close the Python script, sometimes it shows `MemoryError: bad allocation` when I force quit.

In my case I'm am registering at 3-5 fps, 2 point clouds captured with `RealSenseSensor` object and converted to legacy, both at fixed position (although it shouldn't matter how you capture them). In each loop I limit the registration algorithm to only 30 iterations and use the previous calculated transformation matrix as the initial transformation. This way I get a refinement ot the registration in almost realtime. This works fine for few seconds (30 frames maybe), then gets stuck. I also tried with RANSAC method (`registration_ransac_based_on_feature_matching`) and it works fine.

Another user has had the same issue in a similar setup as described here:

### Discussed in https://github.com/isl-org/Open3D/discussions/4423

<div type='discussions-op-text'>

<sup>Originally posted by **eladlavi** December 14, 2021</sup>
Hi there. registration_fgr_based_on_feature_matching gets stuck for no obvious reason.

I am running it in a loop:
o3d.pipelines.registration.registration_fgr_based_on_feature_matching(
        source_down, target_down, source_fpfh, target_fpfh,
        o3d.pipelines.registration.FastGlobalRegistrationOption(
            maximum_correspondence_distance=distance_threshold,
            iteration_number=10))

I am trying to register a series of consecutive point clouds, not too big, about 50,000 points,
from a scanner, the scanner is in static environment, doesn't event move much so the point clouds are almost identical.
Using a strong PC. It succeeds multipe times (again for the very similar point clouds, only minor noise of difference), and then, at some iteration, it gets stuck (I can hear the PC fan going crazy).

I am using the registration_fgr_based_on_feature_matching to get an initial guess for the transformation and then I pass it to the ICP algorithm.

What can cause it to get internally in an infinite loop ? again, for the same point cloud data it succeed multiple times before this happens.
Perhaps there's no correct release of resources internally within the code ?

Thanks.
</div>

### Steps to reproduce the bug

```python
import open3d as o3d
import numpy as np


def preprocess(pcd, vox_size):
    pcd_down = pcd.voxel_down_sample(vox_size)

    pcd.estimate_normals(
        o3d.geometry.KDTreeSearchParamHybrid(radius=vox_size * 2, max_nn=30))

    radius_feature = vox_size * 5
    pcd_fpfh = o3d.pipelines.registration.compute_fpfh_feature(pcd_down,
            o3d.geometry.KDTreeSearchParamHybrid(radius=radius_feature, max_nn=100))
    
    return pcd_down, pcd_fpfh


transformation = np.identity(4)
voxel_size = 0.02

while True:
    pcd1 = # capture the first pointcloud somehow (realtime)
    pcd2 = # capture the second pointcloud somehow (realtime)

    pcd1_d, pcd1_fpfh = preprocess(pcd1, voxel_size)
    pcd2_d, pcd2_fpfh = preprocess(pcd2, voxel_size)

    pcd1_d.transform(transformation)
    result = o3d.pipelines.registration.registration_fgr_based_on_feature_matching(
        pcd1_d, pcd2_d, pcd1_fpfh, pcd2_fpfh,
        o3d.pipelines.registration.FastGlobalRegistrationOption(iteration_number=30))
    
    print(result)
    transformation = transformation * result.transformation

    # do other stuff applying the whole tansformation to the original pointcloud
```

### Error message

`MemoryError: bad allocation`

### Expected behavior

Computation should not block indefinitely

### Open3D, Python and System information

```markdown
- Operating system: Windows 10 64-bit
- Python version: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
- Open3D version: 0.14.1
- System type: x86_64
- Is this remote workstation?: no
- How did you install Open3D?: pip
```

**Comment by theNded** [comment]
> ### Checklist
> * [x]  I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
> * [x]  For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
> * [x]  I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).
> 

You did not actually follow the instructions right? It has been **reported** in #4481 and fixed in the **latest development wheel** by #4547 and further addressed (for boundary cases) in the following PR #4479.

**Comment by theNded** [comment]
No you don't need to apologize :-). It is just a recommended routine so that both of us can save effort for improvement.
Please feel free to reopen if the problem persists.

**Comment by michezio** [comment]
I've checked on the latest wheel and it has been running for minutes without hanging so I think it's been successfully solved, thank you!

**Comment by hongsheng-Z** [comment]
> I've checked on the latest wheel and it has been running for minutes without hanging so I think it's been successfully solved, thank you!

Hi, I also met the same problem, may I ask how you finally solved it?
