### ISSUE TITLE
Problems in conversion of RGBDImage to legacy

### ISSUE THREAD

**Issue by michezio** [isl-org/Open3D#4696]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

I'm converting an `open3d.t.geometry.RGBDImage` captured with a RealSense camera into the old API with `to_legacy` method. When I try to use the legacy version of the RGBDImage to generate a PointCloud it says `Unsupported image format`. But if I create a new RGBDImage applying `to_legacy` to the color and depth images from the original RGBDImage, it works just fine.

### Steps to reproduce the bug

```python
import open3d as o3d

real_sense_camera = o3d.t.io.RealSenseSensor()
real_sense_camera.start_capture()

rgbd = real_sense_camera.capture_frame(wait=True, align_depth_to_color=True)

intrinsic = o3d.camera.PinholeCameraIntrinsic(
        o3d.camera.PinholeCameraIntrinsicParameters.PrimeSenseDefault)

''' this gives "Unsupported image format" error '''
pcd = o3d.geometry.PointCloud.create_from_rgbd_image(
    rgbd.to_legacy(), intrinsic)
    
''' this works fine '''
rgbd_legacy = o3d.geometry.RGBDImage.create_from_color_and_depth(
    rgbd.color.to_legacy(), rgbd.depth.to_legacy(), convert_rgb_to_intensity=False)
pcd = o3d.geometry.PointCloud.create_from_rgbd_image(
    rgbd_legacy, intrinsic)

real_sense_camera.stop_capture()
```

### Error message

RuntimeError: [Open3D Error] (class std::shared_ptr<class open3d::geometry::PointCloud> __cdecl open3d::geometry::PointCloud::CreateFromRGBDImage(const class open3d::geometry::RGBDImage &,const class open3d::camera::PinholeCameraIntrinsic &,const class Eigen::Matrix<double,4,4,0,4,4> &,bool)) D:\a\Open3D\Open3D\cpp\open3d\geometry\PointCloudFactory.cpp:197: [CreatePointCloudFromRGBDImage] Unsupported image format.

### Expected behavior

`o3d.geometry.RGBDImage.create_from_color_and_depth(rgbd.color.to_legacy(), rgbd.depth.to_legacy(), convert_rgb_to_intensity=False)` and `rgbd.to_legacy()` should yield the same result in theory.

### Open3D, Python and System information

```markdown
- Operating system: Windows 10 64-bit
- Python version: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
- Open3D version: 0.14.1 and 0.14.1+283176a
- System type: x86_64
- Is this remote workstation?: no
- How did you install Open3D?: pip
```

### Additional information

In the error traceback it says `D:\a\Open3D\Open3D\cpp\open3d\geometry\PointCloudFactory.cpp` but I don't actually have Open3D installed in a D:\a\ path (i don't have a D: drive at all in my system). Why does it says like that?

**Comment by michezio** [comment]
So if I need to use some legacy functionality I have to convert the tensor based PointCloud to legacy instead of creating a legacy PointCloud from legacy RGBDImage?

**Comment by Hamza-Robotics** [comment]
@michezio I have the same issue right now did you find a fix? How do you convert to the old API to use the old functions such as segment_plane() etc.?

**Comment by michezio** [comment]
You need to use the method `to_legacy()` on a `o3d.t.geometry.PointCloud` object to convert it to the old version. I guess in the future they'll port all the "old method" to the new version, but as of version 0.15 if you need an old function you have to convert. 

The way I'm creating a "new type" PointCloud from RealSense camera and then convert it, is this:

```python
import open3d as o3d

camera = o3d.t.io.RealSenseSensor()

# get info from the camera itself
metadata = camera.get_metadata()
intrinsic = o3d.core.Tensor(metadata.intrinsics.intrinsic_matrix, dtype=o3d.core.Dtype.Float32)
depth_scale = metadata.depth_scale

# use this extrinsic matrix to rotate the image since frames captured with RealSense camera are upside down 
extrinsic = o3d.core.Tensor([[1,0,0,0], [0,-1,0,0], [0,0,-1,0], [0,0,0,1]], dtype=o3d.core.Dtype.Float32)

camera.start_capture()

while True:
    rgbd = camera.capture_frame(wait=True, align_depth_to_color=True)
    pcd_t = o3d.t.geometry.PointCloud.create_from_rgbd_image(rgbd, intrinsic, extrinsic, depth_scale)
    
    # convert to the old version
    pcd_old = pcd_t.to_legacy()

    # do stuff
```

Sorry if I took so long to answer, hope this helps if you haven't found a solution already,

**Comment by drapado** [comment]
@michezio The problem of your solution is that you can't keep non valid points. Therefore, there's no way to create a structured pointcloud. Any ideas for it?
