### ISSUE TITLE
CentOS 7.8: Cannot install from source

### ISSUE THREAD

**Issue by kimdn** [isl-org/Open3D#4706]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

#### I first cloned Open3D by:
```
git clone https://github.com/isl-org/Open3D.git
cd Open3D
```

#### Then, I build Open3D (on  CentOS Linux release 7.8.2003 (Core)) with:
```
mkdir build
cd build
~/bin/cmake-3.22.2-linux-x86_64/bin/cmake ..
```

### Error message

```shell
(Open3D) [kimd999@deception01 build]$ cmake ..
-- CMAKE_BUILD_TYPE is set to Release.
-- Downloading 3rdparty dependencies to /people/kimd999/script/python/Danny/Open3D/Open3D_git_repo/Open3D/3rdparty_downloads
CMake Deprecation Warning at CMakeLists.txt:162 (cmake_policy):
  The OLD behavior for policy CMP0072 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
-- Open3D 0.14.1
-- Using security hardening compiler flags: $<$<COMPILE_LANGUAGE:CUDA>:-Xcompiler=-fstack-protector-strong,-Wformat,-Wformat-security>;$<$<COMPILE_LANGUAGE:CXX>:-fstack-protector-strong;-Wformat;-Wformat-security>
-- Using security hardening linker flags: $<$<COMPILE_LANGUAGE:CUDA>:-Xcompiler=-Wl,-z,noexecstack,-Wl,-z,relro,-z,now,$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:-pie>,$<$<CONFIG:Release>:LINKER:--strip-debug>>;$<$<COMPILE_LANGUAGE:CXX>:-Wl,-z,noexecstack;-Wl,-z,relro,-z,now;$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:-pie>;$<$<CONFIG:Release>:LINKER:--strip-debug>>
-- Using security hardening compiler definitions: _FORTIFY_SOURCE=2
-- Fetching ISPC compiler
-- Building with detected instruction sets
-- Using ISPC instruction sets: avx2-i32x8
-- Using installed third-party library 3rdparty_threads
-- Using installed third-party library 3rdparty_openmp
-- Building with OpenMP
-- Using installed third-party library 3rdparty_x11
-- Building library 3rdparty_glfw from source
-- Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR)
-- Using X11 for window creation
CMake Error at 3rdparty/glfw/CMakeLists.txt:236 (message):
  The RandR headers were not found


-- Configuring incomplete, errors occurred!
See also "/people/kimd999/script/python/Danny/Open3D/Open3D_git_repo/Open3D/build/CMakeFiles/CMakeOutput.log".
See also "/people/kimd999/script/python/Danny/Open3D/Open3D_git_repo/Open3D/build/CMakeFiles/CMakeError.log".
```

### Open3D, Python and System information

```markdown
- Operating system: CentOS Linux release 7.8.2003 (Core)
- Python version: Python 3.8.3
- Open3D version: N/A (e.g. cannot import Open3D)
- System type: x84
- Is this remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
```

### Additional information

Searching similar issues 
(e.g. 
is:issue install from source is:closed
is:issue "install from source" is:closed
 )
didn't bring similar issue over the last few months. 

These queries didn't seem to refine/restrict search results as well (at least title wise).

**Comment by yxlao** [comment]
@kimdn You'll need the equivalence of these packages: https://github.com/isl-org/Open3D/blob/master/util/install_deps_ubuntu.sh . You might be able to skip some of them though. 

The particular error that you got:
```
CMake Error at 3rdparty/glfw/CMakeLists.txt:236 (message):
  The RandR headers were not found
```
can be resolved by installing:
```
xorg-dev libglu1-mesa-dev
```

We don't have official CentOS support yet (especially for older CentOS versions). Let us know if you get it to work.

**Comment by kimdn** [comment]
> org-dev

Both

source https://github.com/isl-org/Open3D/blob/master/util/install_deps_ubuntu.sh

and
installing
xorg-dev

required sudo that I don't have.

I just requested my linux system administrator.

**Comment by kimdn** [comment]
> @kimdn You'll need the equivalence of these packages: https://github.com/isl-org/Open3D/blob/master/util/install_deps_ubuntu.sh . You might be able to skip some of them though.
> 
> The particular error that you got:
> 
> ```
> CMake Error at 3rdparty/glfw/CMakeLists.txt:236 (message):
>   The RandR headers were not found
> ```
> 
> can be resolved by installing:
> 
> ```
> xorg-dev libglu1-mesa-dev
> ```
> 
> We don't have official CentOS support yet (especially for older CentOS versions). We do not expect it to work out of the box. Additional porting efforts (install system deps and tweaking the build system) will be required.
> 
> Let us know if you get it to work on CentOS. We'd be happy to include that in the documentation to help other users.

Both

source https://github.com/isl-org/Open3D/blob/master/util/install_deps_ubuntu.sh

and
installing
xorg-dev

required sudo that I don't have.

I just requested my linux system administrator.

**Comment by nicolasugrinovic** [comment]
That is a pity. Is there any possible workaround?

**Comment by BinglunWang** [comment]
> That is a pity. Is there any possible workaround?

Hi, I have the same problem. Have you found a solution?

**Comment by giangdip2410** [comment]
You can use this version: https://github.com/cubao/Open3D. It works for me.

**Comment by meidachen** [comment]
> You can use this version: https://github.com/cubao/Open3D. It works for me.

Could you please give more details on the system/environment you have to make it work on CentOS? Thank you!
