### ISSUE TITLE
CentOS 7.8: Cannot import Open3D after pip install

### ISSUE THREAD

**Issue by kimdn** [isl-org/Open3D#4707]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

#### I first installed with pip (pip 22.0.3) by:
```
pip install open3d
```

#### Then, I tried to import Open3D (on CentOS Linux release 7.8.2003 (Core)) with:
```
import open3d as o3d
```

### Error message

```shell
Traceback (most recent call last):
  File "import_Open3D.py", line 1, in <module>
    import open3d as o3d
  File "/people/kimd999/.local/lib/python3.8/site-packages/open3d/__init__.py", line 46, in <module>
    _CDLL(str(next((_Path(__file__).parent).glob('*c++abi.*'))))
  File "/share/apps/python/miniconda3.8/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib64/libc.so.6: version `GLIBC_2.18' not found (required by /people/kimd999/.local/lib/python3.8/site-packages/open3d/libc++abi.so.1)
```

### Open3D, Python and System information

```markdown
- Operating system: CentOS Linux release 7.8.2003 (Core)
- Python version: Python 3.8.3

- Open3D version: N/A (can't import Open3D. However, it tried to install 0.13.0 based on
Requirement already satisfied: open3d in /qfs/people/kimd999/.local/lib/python3.8/site-packages (0.13.0)


- System type: x84
- Is this remote workstation?: no
- How did you install Open3D?: pip (in clean/new conda environment)
```

### Additional information

Similar issue is
https://github.com/isl-org/Open3D/issues/4630

However, error message is different

**Comment by yxlao** [comment]
Open3D is compiled with a newer version of glibc (2.18), so it expects your system to have glibc that is the same or newer than this. That is why we explicitly say it supports Ubuntu 18.04+ (but not 16.04). 

The solution is to somehow get glibc 2.18 in your system and load this library. Or, you may compile from source (which you're already trying).

**Comment by kimdn** [comment]
> Open3D is compiled with a newer version of glibc (2.18), so it expects your system to have glibc that is the same or newer than this. That is why we explicitly say it supports Ubuntu 18.04+ (but not 16.04).
> 
> The solution is to somehow get glibc 2.18 in your system and load this library. Or, you may compile from source (which you're already trying).

Thank you, I just contacted my professional system admin to update GUN libc version.
