### ISSUE TITLE
Volume calculations on similar meshes vary greatly

### ISSUE THREAD

**Issue by FranzEricSchneider** [isl-org/Open3D#4710]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [x] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

I am trying to calculate the volumes of some TriangleMesh objects, created with alpha shapes. The basic issue is that the calculated volume seems to fluctuate pretty wildly even when the meshes look great in a visualizer. For example, here are 6 screenshots of meshes created with an increasing alpha value, getting more and more smooth. The alpha value used can be seen highlighted in the file name on the left. I would say that the volume should increase a little, pockets getting filled in, but not by too much and not by integer multiples.

<img src="https://user-images.githubusercontent.com/3709527/152666985-3ae4c3cb-b0fd-4407-bb9a-07d2b6df36c9.png" width="400">

<img src="https://user-images.githubusercontent.com/3709527/152666987-a350927c-175a-4c47-bfb3-590648d59667.png" width="400">

<img src="https://user-images.githubusercontent.com/3709527/152666989-40709972-412d-4a2c-a242-cb294ebe1733.png" width="400">

<img src="https://user-images.githubusercontent.com/3709527/152666990-e80a3ad8-f343-4e2d-90ad-96112ea060e4.png" width="400">

<img src="https://user-images.githubusercontent.com/3709527/152666991-19bfab35-ad60-43f1-b6f4-9dc8b32266b3.png" width="400">

<img src="https://user-images.githubusercontent.com/3709527/152666993-22776132-ad07-4a7c-8d49-21268d7df4c9.png" width="400">

These meshes are all classified as orientable, watertight, and not self-intersecting. Despite having these reasonable and mostly similar meshes, the volume calculations vary a great deal, there's a factor of 130x between the mesh with alpha=0.1 and alpha=100! In order to find a reasonable upper bound I found the height x width x width of a bounding box and got 639 cm^3 for the bounding box. These calculated volume values vary above and below that.
```
7-9.pcd [alpha 0.02]:   Volume (cm^3): 88.35
7-9.pcd [alpha 0.04]:   Volume (cm^3): 293.90
7-9.pcd [alpha 0.06]:   Volume (cm^3): 437.05
7-9.pcd [alpha 0.1]:    Volume (cm^3): 10.01
7-9.pcd [alpha 10]:     Volume (cm^3): 946.32
7-9.pcd [alpha 100]:    Volume (cm^3): 1345.58
```

Code that got those volume values:
```
mesh = open3d.geometry.TriangleMesh.create_from_point_cloud_alpha_shape(
    cloud,
    alpha=value,
)
volume = mesh.get_volume() * 1e6  # The 1e6 is to get cubic cm
```

Is this a bug in volume computation? Or am I doing something wrong in a subtle way?

I checked out [this issue](https://github.com/isl-org/Open3D/issues/2439) and [the PR where the feature was made](https://github.com/isl-org/Open3D/pull/2407) but I didn't see any relevant comments.

Inside this file are the alpha=0.1 and alpha=100 mesh files for reproducing:
[mesh_files.zip](https://github.com/isl-org/Open3D/files/8009386/mesh_files.zip)

### Steps to reproduce the bug

```python
[Download zipped mesh files from description section]

$ unzip mesh_files.zip
Archive:  mesh_files.zip
  inflating: 7-9_0.1.ply
  inflating: 7-9_100.ply
$ ls
7-9_0.1.ply  7-9_100.ply  mesh_files.zip
$ python
Python 3.8.10 (default, Nov 26 2021, 20:14:08)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import open3d
INFO - 2022-02-05 22:58:04,459 - utils - NumExpr defaulting to 8 threads.
>>> alpha_01 = open3d.io.read_triangle_mesh("7-9_0.1.ply")
>>> print(alpha_01.get_volume() * 1e6)
10.01335556317462
>>> alpha_100 = open3d.io.read_triangle_mesh("7-9_100.ply")
>>> print(alpha_100.get_volume() * 1e6)
1345.5866685926246
```

### Expected behavior

A more consistent and physically reasonable volume calculation.

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04
- Python version: 3.8.10
- Open3D version: 0.13.0
- System type: x84
- Is this remote workstation?: no
- How did you install Open3D?: pip
```

**Comment by FranzEricSchneider** [comment]
Similarly, on each point cloud I tried the convex hull for comparison and got the same type of large variances
```
hull, _ = cloud.compute_convex_hull()
print(f"{pcdfile.name}[hull]: {hull.get_volume() * 1e6}")
```
Became
```
7-9.pcd[hull]: 2347.324797394266
8-1.pcd[hull]: 62.01164490660335
8-2.pcd[hull]: 872.2369374467719
```

**Comment by benjaminum** [comment]
Can you try again with the master branch? There were problems with the triangle orientation in the convex hull algorithm, which have been fixed now.
Here is the link to the artifact with all linux python wheels https://github.com/isl-org/Open3D/suites/5187846017/artifacts/157881416 (3GB).

**Comment by FranzEricSchneider** [comment]
Ah, very interesting! Yes, although the `TriangleMesh`-from-alpha-shape volume did not change above, the convex hull volume did indeed change:

0.13.0 (from above)
```
7-9.pcd[hull]: 2347.324797394266
8-1.pcd[hull]: 62.01164490660335
8-2.pcd[hull]: 872.2369374467719
```

0.14.1
```
Open3D version: 0.14.1+dc2c7fb
7-9.pcd[hull]: 390.74675251279683
8-1.pcd[hull]: 276.5096443848751
8-2.pcd[hull]: 275.29514147633216
```

These definitely look plausible, as mentioned in the first post I found the bounding box volume for the 7-9 cloud and got 639 cm^3.

Do you think it's possible that building the open3d repo from source might fix the alpha-shape mesh volume errors?

**Comment by benjaminum** [comment]
No, the development wheel represents the state of the master branch. There seems to be a problem with the alpha shape. I assume you recomputed the meshes with the dev version before computing the volume. Can you check the triangle orientation/normals?

**Comment by FranzEricSchneider** [comment]
I can pull up the mesh in CloudCompare (which I've been using for cloud/mesh visualization) and check out the normals, can you go into a little more detail about what I should be looking for? Maybe inwards/outwards orientation?

Yes, I am recomputing the mesh and volume each time, for reference this is what is running:

```
print(f"Open3D version: {open3d.__version__}")

for pcdfile in sorted(Path(".").glob("*pcd")):
    for value in [0.02, 0.04, 0.06, 0.1, 10, 100]:
        cloud = open3d.io.read_point_cloud(str(pcdfile))
        cloud = cloud.voxel_down_sample(0.001)
        cleaner_cloud, _ = cloud.remove_radius_outlier(nb_points=20, radius=0.01)
        mesh = open3d.geometry.TriangleMesh.create_from_point_cloud_alpha_shape(
            cleaner_cloud,
            alpha=value,
        )
        try:
            volume = f"{mesh.get_volume() * 1e6:.2f}"
        except RuntimeError:
            volume = "Failed"
        print(f"{pcdfile.name}[{value}]: {volume}"
              f"\tOrientable: {mesh.is_orientable()}"
              f"\tWatertight: {mesh.is_watertight()}"
              f"\tSelf intersecting: {mesh.is_self_intersecting()}")
```

**Comment by benjaminum** [comment]
I wonder if the orientation of the triangles is consistent or if there are some triangles oriented inwards

**Comment by FranzEricSchneider** [comment]
Hi, if I'm interpreting this right and a missing triangle means an inwards normal, then it almost looks like the normals are oscillating inwards and outwards.

<img src="https://user-images.githubusercontent.com/3709527/152882699-b3cd9b75-62a7-47f6-9821-ce3aee52e99c.png" width="200">

**Comment by benjaminum** [comment]
Can you try `mesh.orient_triangles()`? After that all triangles should have consistent orientation.

**Comment by FranzEricSchneider** [comment]
Oh that's lovely, thanks! I didn't realize that was necessary, but it looks like it is. The volume results after doing `orient_triangles()` look great, they very consistently rise with the alpha value up to the convex hull value.

```
7-9.pcd[0.02]: 247.62   Orientable: True    Watertight: True
7-9.pcd[0.04]: 269.05   Orientable: True    Watertight: True
7-9.pcd[0.06]: 285.00   Orientable: True    Watertight: True
7-9.pcd[0.1]:  302.38   Orientable: True    Watertight: True
7-9.pcd[10]:   390.54   Orientable: True    Watertight: True
7-9.pcd[100]:  390.75   Orientable: True    Watertight: True
7-9.pcd[hull]: 390.75

8-1.pcd[0.02]: 208.52   Orientable: True    Watertight: True
8-1.pcd[0.04]: 221.87   Orientable: True    Watertight: True
8-1.pcd[0.06]: Failed   Orientable: False   Watertight: False
8-1.pcd[0.1]:  244.87   Orientable: True    Watertight: True
8-1.pcd[10]:   276.37   Orientable: True    Watertight: True
8-1.pcd[100]:  276.51   Orientable: True    Watertight: True
8-1.pcd[hull]: 276.51

8-2.pcd[0.02]: Failed   Orientable: True    Watertight: False
8-2.pcd[0.04]: 212.45   Orientable: True    Watertight: True
8-2.pcd[0.06]: 222.87   Orientable: True    Watertight: True
8-2.pcd[0.1]:  232.20   Orientable: True    Watertight: True
8-2.pcd[10]:   275.29   Orientable: True    Watertight: True
8-2.pcd[100]:  275.30   Orientable: True    Watertight: True
8-2.pcd[hull]: 275.30
```
<img src="https://user-images.githubusercontent.com/3709527/153075741-2fe06f18-830e-47c8-b295-21192ab89aaa.png" width="300">

In that case, it looks like this isn't exactly a bug but more of a mistake on my part by not calling `orient_triangles()` first. Two thoughts:

1. On the more extreme side, if there are mismatched surface normals, should `get_volume()` call `orient_triangles()` automatically?
2. On the less extreme side, maybe the documentation for `get_volume()` could suggest `orient_triangles()` as an important related function?

**Comment by benjaminum** [comment]
Great to hear that the volume computation works for you now.

On your thoughts
1. I think `get_volume()` is a function that should not alter the mesh. The problem or misunderstanding seems to be that `create_from_point_cloud_alpha_shape()` does not create a mesh that is ready for visualization or analysis. Increasing the runtime some more by including `orient_triangles()` into `create_from_point_cloud_alpha_shape()` to get a better mesh seems to be reasonable and something we should consider.
2. Documentation of `create_from_point_cloud_alpha_shape()` and `get_volume()` should definitely be updated with more information.
