### ISSUE TITLE
how to make it right?

### ISSUE THREAD

**Issue by jinfagang** [isl-org/Open3D#4711]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/21303438/152681772-0908a2eb-130a-46fb-8814-4585f7352e63.png">

I want the human mesh be right, how to make it right quickly.

Also, how to make it interactable wile visualize in realtime?

**Comment by theNded** [comment]
You can `transform` the mesh by reverting the x and y axes.
For online interactive visualization please refer to [this example](https://github.com/isl-org/Open3D/blob/master/examples/python/visualization/online_processing.py)
