### ISSUE TITLE
compiles fine but segfaults for any visualization

### ISSUE THREAD

**Issue by Rheinwalt** [isl-org/Open3D#4712]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

#### I first cloned Open3D by:
```
git clone https://github.com/isl-org/Open3D.git
cd Open3D
```

#### Then, I build Open3D (on Arch Linux) with:
```
mkdir build
cd build
cmake ..
make -j$(nproc)
```

#### Then, I use the Python module like so:
```
import open3d as o3d
pcd = o3d.io.read_point_cloud('fragment.ply')
o3d.visualization.draw_geometries([pcd])
```

### Error message

```shell
Segmentation fault (core dumped)
```

### Open3D, Python and System information

```markdown
- Operating system: current Arch Linux
- Python version: Python 3.10.2
- Open3D version: 0.14.1+b449b58a1
- System type: x84_64
- Is this remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): gcc 11.1.0
```

**Comment by errissa** [comment]
How recently did you clone? There was a segfault with `draw_geometries` that was very recently resolved.

**Comment by Rheinwalt** [comment]
> How recently did you clone? There was a segfault with `draw_geometries` that was very recently resolved.

Oh, good call! I thought I did a pull, but apparently it was prior to the fix. Now that I did a new clone everything works as expected.

Thanks!
