### ISSUE TITLE
point selection with multiple geometries in O3dVisualizer causes crash

### ISSUE THREAD

**Issue by MrSamuelLaw** [isl-org/Open3D#4713]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

When going to select a point on a point cloud, with two overlapping geometries open in the O3dVisualizer,
I get the following error if I happen to click out in space, or on the second imported geometry.

[Open3D Error] (const struct open3d::visualization::gui::SelectionIndexLookup::Obj &__cdecl open3d::visualization::gui::SelectionIndexLookup::ObjectForIndex(unsigned __int64)) D:\a\Open3D\Open3D\cpp\open3d\visualization\gui\PickPointsInteractor.cpp:125: First object != 0

### Steps to reproduce the bug

```python
Launch open3d O3dVisualizer
Import two point clouds
Attempt to select a point not on the point cloud imported first.
```

### Error message

[Open3D Error] (const struct open3d::visualization::gui::SelectionIndexLookup::Obj &__cdecl open3d::visualization::gui::SelectionIndexLookup::ObjectForIndex(unsigned __int64)) D:\a\Open3D\Open3D\cpp\open3d\visualization\gui\PickPointsInteractor.cpp:125: First object != 0

### Expected behavior

For the app not to crash.

### Open3D, Python and System information

```markdown
- Operating system: Windows 10 64 bit
- Python version: 3.9
- Open3D version: 0.14.1
- System type: (x86)
- Is this remote workstation?: no
- How did you install Open3D?: pip
```

**Comment by forrestjgq** [comment]
#4615 fixed this issue
