### ISSUE TITLE
Runnint dataset unit tests deletes all downloaded data

### ISSUE THREAD

**Issue by yxlao** [isl-org/Open3D#4718]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

(Introduced in #4701)

If we run:

```python
pytest python/test/data/test_data.py -s
```

All downloaded data in `$HOME/open3d_data/download` and `$HOME/open3d_data/extact` will be deleted.

### Steps to reproduce the bug

```python
pytest python/test/data/test_data.py -s
```

### Error message

All downloaded data in `$HOME/open3d_data/download` and `$HOME/open3d_data/extact` will be deleted.

### Expected behavior

All downloaded data in `$HOME/open3d_data/download` and `$HOME/open3d_data/extact` shall not be deleted.

The unit test shall run independently (using a different directory for testing).

### Open3D, Python and System information

```markdown
- Operating system: e.g. Ubuntu 20.04
- Python version: e.g. Python 3.8
- Open3D version: master
- System type: x86
- Is this a remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): clang 10
```

**Comment by reyanshsolis** [comment]
I can't reproduce this in my system. 
All unit test data are prefixed by `O3DTest...`. So, other data is not deleted. 

Before and after running `cpp / python` unit tests, the already present data in download and extract dir remains unaffected:
![image](https://user-images.githubusercontent.com/32535717/152953520-a99fe3ca-60d3-45f7-9629-3abbede9de63.png)

**Comment by yxlao** [comment]
You're right. I was expecting to see we change the "data root" in those tests, but you changed the "data set prefix" in those tests. Let's discuss the design later.
