### ISSUE TITLE
How to show coordinates/axes in pointcloud visualization?

### ISSUE THREAD

**Issue by ilyak93** [isl-org/Open3D#4724]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi,
I'm using open3d 0.14.1 and the following code to show pointcloud:

pcd = open3d.io.read_point_cloud("./3dmap.ply")
open3d.visualization.draw_geometries([pcd],
                                  zoom=0.3412,
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[2.6172, 2.0475, 1.532],
                                  up=[-0.0694, -0.9768, 0.2024])

How can I add reference coordinate system or any other axes description?
Thanks!

**Comment by theNded** [comment]
You can use [create_coordinate_frame](http://www.open3d.org/docs/release/tutorial/geometry/transformation.html#Transformation).
