### ISSUE TITLE
'jpeglib.h' file not found

### ISSUE THREAD

**Issue by zuixiaosanlang** [isl-org/Open3D#4735]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

build 0.9.0 failed, 'jpeglib.h' file not found

![image](https://user-images.githubusercontent.com/20105627/153121099-24544f20-27ef-4140-b943-e912e6dbdd87.png)

how to solve this

thanks

**Comment by theNded** [comment]
Please build the latest repo and install dependencies following the [tutorial](http://www.open3d.org/docs/release/compilation.html#install-dependencies).
