### ISSUE TITLE
Issue building from source using MSVC1930 (VS2022) - Hardcoded ASSIMP version in CMake

### ISSUE THREAD

**Issue by Miges** [isl-org/Open3D#4736]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

#### I first cloned Open3D by:
```
git clone https://github.com/isl-org/Open3D.git
cd Open3D
```

#### Then, I built Open3D on Windows 10 with VS 2022:
```
mkdir build
cd build
cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_INSTALL_PREFIX="../x_install" -DBUILD_PYTHON_MODULE=OFF
```

Then opened the VS solution and ran ALL_BUILD using Release.  The linker at the end came up with the error that it couldn't link assimp-vc142-mt.lib

### Error message

```shell
Linker error (LNK1181) for assimp-vc142-mt.lib - for a very large number of projects.
```

### Open3D, Python and System information

```markdown
- Operating system: Windows 10 64-bit
- MSVC_VERSION: 1930
- MSVC_TOOLSET_VERSION: 143
- Python version: N/A
```

### Additional information

Changing this to `assimp-vc143-mt` fixed it:

https://github.com/isl-org/Open3D/blob/master/3rdparty/assimp/assimp.cmake#L4

I suspect that this lib name should be calculated according to the logic here but I am no CMake expert!

https://github.com/assimp/assimp/blob/v5.1.6/CMakeLists.txt#L765

**Comment by axoloto** [comment]
Hi, CMake is currently at 3.23, do you plan to move to this version and fix this issue? Thanks!

**Comment by ssheorey** [comment]
This is resolved. We can build with Visual Studio 2022 now.
