### ISSUE TITLE
how to add shadows and alpha

### ISSUE THREAD

**Issue by jinfagang** [isl-org/Open3D#4745]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

now it looks like 2d image rather than 3d

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/21303438/153439416-5ae4327a-c287-4235-9d36-4d41f6c73588.png">

```
import copy
import numpy as np
import open3d as o3d

if __name__ == "__main__":

    print("Testing mesh in open3d ...")
    # mesh = o3d.io.read_triangle_mesh("extra_data/knot.ply")
    mesh = o3d.io.read_triangle_mesh("extra_data/a.obj")
    print(mesh)
    print(np.asarray(mesh.vertices))
    print(np.asarray(mesh.triangles))
    mesh.paint_uniform_color([1, 0.4, 0.5])
   
    o3d.visualization.draw_geometries([mesh])
```

**Comment by theNded** [comment]
http://www.open3d.org/docs/release/python_api/open3d.geometry.TriangleMesh.html#open3d.geometry.TriangleMesh.compute_vertex_normals
