### ISSUE TITLE
How to mirror the 3D mesh?

### ISSUE THREAD

**Issue by jinfagang** [isl-org/Open3D#4751]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I have a mesh like this:

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/21303438/153621624-801cf69f-4756-4f96-988a-7da77e6bda99.png">

I want make it mirror along vertical axis, make the line on face from / -> \

how to make it in open3d?

```
import copy
import numpy as np
import open3d as o3d

if __name__ == "__main__":

    print("Testing mesh in open3d ...")
    mesh = o3d.io.read_triangle_mesh("extra_data/a.obj")
    print(mesh)
    print(np.asarray(mesh.vertices))
    print(np.asarray(mesh.triangles))
    verts = np.asarray(mesh.vertices)
    mesh1 = copy.deepcopy(mesh)
    mesh1.vertices = o3d.utility.Vector3dVector(verts)

    # make verts mirror
    # verts[:, -1] = -verts[:, -1]
    # verts[:, 0] = -verts[:, 0]
    print(verts.shape)
    verts = verts[:, [0, 2, 1]]
    mesh.vertices = o3d.utility.Vector3dVector(verts)
    mesh.compute_vertex_normals()
    mesh.paint_uniform_color([0.6, 0.1, 0.5])

   
    o3d.visualization.draw_geometries([mesh])
    mesh1.compute_vertex_normals()
    o3d.visualization.draw_geometries([mesh1])
```

not work..

**Comment by theNded** [comment]
> ```# verts[:, 0] = -verts[:, 0]```
This commented line does the job.

**Comment by jinfagang** [comment]
@theNded obviously the reason why I comment it out is that doesn't **work**.

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/21303438/153691552-e93c622c-d52d-48d2-9209-fe150a16040c.png">


otherwise why do u think I comment it out?

**Comment by theNded** [comment]
> otherwise why do u think I comment it out?


The distortion was from this line that shuffles axes: `verts = verts[:, [0, 2, 1]]`. **Otherwise why do u think it will fail?**
Be polite when you ask questions on a public forum.

**Comment by jinfagang** [comment]
@theNded No personal, but I tried, but not work.

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/21303438/153694866-7a672f5e-703a-45ef-8564-a96f5aa0f640.png">

<img width="392" alt="image" src="https://user-images.githubusercontent.com/21303438/153694873-0e6a04cd-91a4-4bce-bef7-dbd8092a9397.png">
