### ISSUE TITLE
How to make mesh transparent with alpha?

### ISSUE THREAD

**Issue by jinfagang** [isl-org/Open3D#4752]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

any example? 

    mesh.paint_uniform_color([0.6, 0.1, 0.5])

not work

**Comment by theNded** [comment]
#2890
