### ISSUE TITLE
Remove low density vertices of Poisson reconstructed mesh in C++

### ISSUE THREAD

**Issue by VeronikaBabii** [isl-org/Open3D#4756]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I've successfully created python program to reconstruct surface mesh from point cloud via Poisson algorithm. 
Now I need to rewrite it to C++ (while being a total noob in C++).
I'm done with all parts expect the low density vertices removal. 
As for python program I was using numpy, but due to lack of C++ knowledge I have no idea on how to implement the same logic of low density vertices removal in C++.

Python program:
```
import open3d as o3d
import numpy as np

# 1 - load ply
pcd = o3d.io.read_point_cloud("/Users/veronika/Desktop/input_data.ply")

# 2 - downsample
downpcd = pcd.voxel_down_sample(voxel_size=0.02)

# 3 - compute normals
downpcd.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30))

# 4 - orient normals
downpcd.orient_normals_towards_camera_location(camera_location=np.array([0., 0., 0.]))

# 5 - reconstruct via Poisson
mesh, densities = o3d.geometry.TriangleMesh.create_from_point_cloud_poisson(downpcd, depth=9)

# 6 - remove vertices with low density
densities = np.asarray(densities)
vertices_to_remove = densities < np.quantile(densities, 0.01)
mesh.remove_vertices_by_mask(vertices_to_remove)

# 7 - save
o3d.io.write_triangle_mesh("/Users/veronika/Desktop/poisson_output_mesh.ply", mesh)
```

C++ program:

```
// 1 - load ply
auto pcd = io::CreatePointCloudFromFile("/Users/veronika/Desktop/input_data.ply");

// 2 - down sample
auto downpcd = pcd->VoxelDownSample(0.02);

// 3 - compute normals
downpcd->EstimateNormals(geometry::KDTreeSearchParamHybrid(0.1, 30));

// 4 - orient normals
auto loc = Eigen::Vector3d(0.0, 0.0, 0.0);
downpcd->OrientNormalsTowardsCameraLocation(loc);

// 5 - reconstruct via Poisson
shared_ptr<geometry::PointCloud> source = downpcd;
auto mesh = get<0>(geometry::TriangleMesh::CreateFromPointCloudPoisson(*source));
auto densities = get<0>(geometry::TriangleMesh::CreateFromPointCloudPoisson(*source));

// 6 - remove vertices with low density
// TODO: densities = np.asarray(densities) 
// TODO: vertices_to_remove = densities < np.quantile(densities, 0.01)
// mesh->geometry::TriangleMesh:RemoveVerticesByMask(vertices_to_remove);

// 7 - save
io::WriteTriangleMesh("poisson_mesh.ply", *mesh, true, true);
```

**Comment by theNded** [comment]
I haven't tested but the snippet below should give the spirit.
In the legacy cpp API you have to deal with [std::vector](https://www.cplusplus.com/reference/vector/vector/). It is recommended to grab basic understandings before writing C++ programs.

```cpp
auto res = geometry::TriangleMesh::CreateFromPointCloudPoisson(*source)
auto mesh = std::get<0>(res);
auto densities = std::get<1>(res);

std::vector<bool> mask(densities.size());
for (int i = 0; i < densities.size(); ++i) {
    mask[i] = densities[i] < 0.01;
}
mesh->RemoveVerticesByMask(mask);
```

**Comment by VeronikaBabii** [comment]
Thank you for your help! The solution you provided is working, but I also needed to change the value from 0.01 to 5.0 to get it work the way I want.
