### ISSUE TITLE
Summarize the bug (e.g., "Segmentation Fault for Colored Point Cloud Registration")

### ISSUE THREAD

**Issue by Robomate** [isl-org/Open3D#4758]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

Update Docs Visualization:

There is no zoom, front, lookat, up .

http://www.open3d.org/docs/release/tutorial/visualization/visualization.html?highlight=line

### Steps to reproduce the bug

```python
print("Load a ply point cloud, print it, and render it")
pcd = o3d.io.read_point_cloud("../../test_data/fragment.ply")
o3d.visualization.draw_geometries([pcd],
                                  zoom=0.3412,
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[2.6172, 2.0475, 1.532],
                                  up=[-0.0694, -0.9768, 0.2024])
```

### Error message

    o3d.visualization.draw_geometries([line_set], zoom=0.8)
TypeError: draw_geometries(): incompatible function arguments. The following argument types are supported:
    1. (geometry_list: List[open3d.cpu.pybind.geometry.Geometry], window_name: str = 'Open3D', width: int = 1920, height: int = 1080, left: int = 50, top: int = 50, point_show_normal: bool = False, mesh_show_wireframe: bool = False, mesh_show_back_face: bool = False) -> None
    2. (geometry_list: List[open3d.cpu.pybind.geometry.Geometry], window_name: str = 'Open3D', width: int = 1920, height: int = 1080, left: int = 50, top: int = 50, point_show_normal: bool = False, mesh_show_wireframe: bool = False, mesh_show_back_face: bool = False, lookat: numpy.ndarray[numpy.float64[3, 1]], up: numpy.ndarray[numpy.float64[3, 1]], front: numpy.ndarray[numpy.float64[3, 1]], zoom: float) -> None

Invoked with: [LineSet with 1 lines.]; kwargs: zoom=0.8

### Open3D, Python and System information

```markdown
- Open3D version: output from python: `print(open3d.__version__)`

0.14.1
```

**Comment by theNded** [comment]
This was a documentation mistake. 
Specify front, lookat, and up when you use zoom, similar to the point cloud example.
