### ISSUE TITLE
Always get Error when reading PointCloud from File (CPP)

### ISSUE THREAD

**Issue by mstranne** [isl-org/Open3D#4762]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I have running code using the python lib, but need to switch to an cpp implementation now.

I need to read a PointCloud, in ply format, which I tried excaclty like in this example: https://github.com/isl-org/Open3D/blob/master/examples/cpp/PointCloud.cpp

However, I always get an bad allocation Exception on ReadPointCloud, also tried CreatePointCloudFromFile which results in a bad allocation too.

Then I tried using: 
`const std::string filename_ply("cloud.ply");`
`io::ReadPointCloudFromPLY(filename_ply, pointcloud, io::ReadPointCloudOption());`

In this case I get:

> RPly: Unable to open file
> [Open3D WARNING] Read PLY failed: unable to open file: á─¤OÝ☺

Any Idea what the problem could be?

**Comment by yxlao** [comment]
- It could be that the `ply` file itself is invalid. So, check with a known-working file first. 
- Also, we don't need to call the PLY-specific function. Use `ReadPointCloud` or `CreatePointCloudFromFile`,

If you're on `master` branch, you can try the following code.

```cpp
#include <iostream>
#include <memory>
#include <string>

#include "open3d/Open3D.h"

int main() {
    using namespace open3d;

    // Download the Eagle dataset
    data::EaglePointCloud dataset;
    std::cout << "Path: " << dataset.GetPath() << std::endl;

    // Option 1: use `CreatePointCloudFromFile`
    std::shared_ptr<geometry::PointCloud> pcd_v1 =
            io::CreatePointCloudFromFile(dataset.GetPath());
    std::cout << "# Points: " << pcd_v1->points_.size() << std::endl;

    // Option 2: use `ReadPointCloud`
    geometry::PointCloud pcd_v2;
    io::ReadPointCloud(dataset.GetPath(), pcd_v2);
    std::cout << "# Points: " << pcd_v2.points_.size() << std::endl;

    return 0;
}
```

**Comment by mstranne** [comment]
The ply File is fine, my python code is working with the same file.

When running your suggested code I get bad allocation exception in the first Line:
` data::EaglePointCloud dataset;`
