### ISSUE TITLE
OBJ file write error: "Write PNG failed: image has no data"

### ISSUE THREAD

**Issue by yxlao** [isl-org/Open3D#4763]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

When writing triangle mesh with texture to `.obj` file, we have error:

```
[Open3D WARNING] Write PNG failed: image has no data.
[Open3D WARNING] Write OBJ successful, but failed to write texture file.
```

If we inspect `mesh.textures`, the first texture is empty, while the second one is the texture image.

Also reported in https://github.com/isl-org/Open3D/issues/4444#issuecomment-996691099.

### Steps to reproduce the bug

```python
python -c "import open3d as o3d; \
           mesh = o3d.io.read_triangle_mesh('examples/test_data/monkey/monkey.obj'); \
           print(mesh.textures); \
           o3d.io.write_triangle_mesh('/tmp/monkey_saved.obj', mesh)"
```

### Error message

```
[Image of size 0x0, with 0 channels.
Use numpy.asarray to access buffer data., Image of size 1024x1024, with 4 channels.
Use numpy.asarray to access buffer data.]
[Open3D WARNING] Write PNG failed: image has no data.
[Open3D WARNING] Write OBJ successful, but failed to write texture file.
```

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04
- Python version: Python 3.8
- Open3D version: master
- System architecture: x86
- Is this a remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): clang 10
```

**Comment by errissa** [comment]
@yxlao Try loading the monkey with `enable_post_processing=True`. It appears that assimp creates a dummy material which ends up occupying that first texture slot. Enabling post processing removes the dummy unused material.

**Comment by yxlao** [comment]
@errissa thanks! This resolves the problem.
