### ISSUE TITLE
Error while running OffscreenRendering example

### ISSUE THREAD

**Issue by elias-Mimetrik** [isl-org/Open3D#4765]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [x] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

I'm trying to run the example in 
https://github.com/isl-org/Open3D/blob/master/examples/cpp/OffscreenRendering.cpp
But I'm getting the following error:
[Open3D WARNING] Read PNG failed: unable to parse header.
[Open3D Error] (void open3d::visualization::rendering::{anonymous}::FormatSettingsFromImage(open3d::visualization::rendering::{anonymous}::TextureSettings&, int, int, bool)) /home/user/Downloads/open3d/Open3D/cpp/open3d/visualization/rendering/filament/FilamentResourceManager.cpp:247: Unsupported image number of channels: 0

### Steps to reproduce the bug

```python
Only run the OffScreenRendering example:
https://github.com/isl-org/Open3D/blob/master/examples/cpp/OffscreenRendering.cpp
```

### Error message

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Open3D Error] (static void open3d::visualization::rendering::EngineInstance::SetResourcePath(const string&)) /home/elias/Downloads/open3d/Open3D/cpp/open3d/visualization/rendering/filament/FilamentEngine.cpp:65: Can't find resource directory: /home/elias/eclipse-workspace/open3d-offscreenRendering/build/./../resources
```

### Expected behavior

It should run fine, and not produce an error.

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04
- Python version: Python 3.8
- Open3D version: output from python: `print(open3d.__version__)`
- System architecture: x86
- Is this a remote workstation: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): gcc 9.3 / clang 710.0.0
```

**Comment by lichangW** [comment]
same issue....thanks @elias-Mimetrik

**Comment by manhha1402** [comment]
same issue. Here is output. Somehow it find wrong resource path
![image](https://user-images.githubusercontent.com/20105284/223678553-07808be8-7cfc-426a-b279-891d63a0726f.png)

**Comment by manhha1402** [comment]
Ok. I have to resource_path in  `"/usr/local/bin/Open3D/resources/"` in `Initialize()` function

**Comment by AlbertoMQ** [comment]
This started happening to me when I upgraded to the newest non-stable release.  I then uninstalled and reinstalled the previous stable version and it kept happening.

**Comment by elias-Mimetrik** [comment]
FYI, the last working commit before this error started happening is 450a053ffdd

**Comment by AlbertoMQ** [comment]
> Ok. I have to set resource_path to `"/usr/local/bin/Open3D/resources/"` in `Initialize()` function

Where do you do this?

**Comment by AlbertoMQ** [comment]
To be clear, this started happening to me when running in python.
