### ISSUE TITLE
Is it possible to change drawing order (overlay and not sublay) in Visualizer.add_geometry?

### ISSUE THREAD

**Issue by Robomate** [isl-org/Open3D#4766]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Is it possible to change drawing order (overlay and not sublay) in Visualizer.add_geometry?

When e.g. having an environment template adding before the animation while loop, like:
vis.add_geometry(pcd_env) # env

 and adding moving objects in the loop, like:

while(1)
vis.add_geometry(pcd_mvobj) # moving objects

 ...the object will be drawn behind the environment template. Is there any way the change the order to draw in front of the template?

**Comment by ssheorey** [comment]
@Robomate the Z order should depend on the actual Z values in the point cloud. Can you increase the min Z value of your environment template to more than the max Z value of your pcd sequence? You'll also need to set the viewpoint parallel to the Z axis.
