### ISSUE TITLE
How can range clipping be set in the O3DVisualizer?

### ISSUE THREAD

**Issue by pythoro** [isl-org/Open3D#4767]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

First - thanks for the great library! Now my question... I have used o3d.visualization.draw to create a simple animation. Everything works well enough, except that I can't clip the range of the view to hide voxels far from the camera. Is there a way? Thanks!

**Comment by errissa** [comment]
By default Open3D sets the near/far clip planes to encompass the entire scene. `o3d.visualization.draw` is intended to be a simple, quick, no fuss way to visualize data so it doesn't offer a lot of configuration options.

If you need more control you can use the underlying visualizer directly. Please refer to the examples in `examples/python/visualization` which demonstrate numerous ways to build an application with the visualizer. To change the near/far clip planes you will need to access the `Camera` directly and set the near/far planes using its `set_projection` methods.
