### ISSUE TITLE
Feature request: boolean operation

### ISSUE THREAD

**Issue by LumiereDeLOmbre** [isl-org/Open3D#4769]
Hi,

I use the C++ API of Open3d.
Having the possibility to have mesh boolean operations right inside open3d would be really useful and avoid using other packages with different languages (like Blender, or CGAL but it requires IO convert to, say, PLY and manage the two libraries).

A cylinder passing through a cube is a nightmare to handle otherwise (with the right triangulation).

Maybe a workaround exists. 
Any Idea?

Thanks guys

**Comment by theNded** [comment]
This is at least the 3rd time to see such a feature request so I guess we need to take it seriously @germanros1987

**Comment by LeHibou2** [comment]
Maybe linking against cgal and automatically manage the gateway in, say, off format or ply between the two inside a function that hides the complexity could avoid to rewrite everything?

**Comment by theNded** [comment]
This is a good idea, but CGAL uses GPL and LGPL licenses which are more restrictive than MIT in general, so I doubt it might be non-trivial to migrate...

**Comment by nop144d** [comment]
Any progress or forecasting on this? Thanks!

**Comment by benjaminum** [comment]
v0.16 has boolean operations using VTK as backend.
See [here](http://www.open3d.org/docs/release/python_api/open3d.t.geometry.TriangleMesh.html#open3d.t.geometry.TriangleMesh.boolean_difference)
