### ISSUE TITLE
point cloud crop with AxisAlignedBoundingBox run error!

### ISSUE THREAD

**Issue by 155cannon** [isl-org/Open3D#4771]
### Checklist

- [x] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [x] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [x] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I follow the docs of open3d to use crop function of point cloud. The program is simple and as follows:

import open3d as o3d

pcd = o3d.io.read_point_cloud('line.pcd')
max_bound = pcd.get_max_bound()
min_bound = pcd.get_min_bound()
min_bound[2] = max_bound[2] - 0.2
bounding_box_zpass = o3d.geometry.AxisAlignedBoundingBox(min_bound, max_bound)
pcd_zpass = pcd.crop(bounding_box_zpass)

RuntimeError: [Open3D Error] (class std::shared_ptr<class open3d::geometry::PointCloud> __cdecl open3d::geometry::PointCloud::Crop(const class open3d::geometry::AxisAlignedBoundingBox &) const) D:\a\Open3D\Open3D\cpp\open3d\geometry\PointCloud.cpp:486: [CropPointCloud] AxisAlignedBoundingBox either has zeros size, or has wrong bounds.

I don't know why the RuntimeError occurs. Thank everyone!

**Comment by theNded** [comment]
`min_bound[2] = max_bound[2] - 0.2`
This line is suspicious. If the original `min_bound[2]` is larger than `max_bound[2] - 0.2` then apparently the box has zero size.

**Comment by 155cannon** [comment]
> 

But actually print the max_bound and min_bound:

print(max_bound)
print(min_bound)
[-0.11278063  9.25705719 -9.54183483]
[ -0.11278063   1.35561967 -10.43259525]

It's OK.
So why?

**Comment by theNded** [comment]
min_bound[0] == max_bound[0] so the bbox's volume is 0. It's not OK.

**Comment by 155cannon** [comment]
min_bound[0] == max_bound[0], yes,it is. Because all the points of the point cloud is in a plane, so their X coordinate is the same. In this case, the crop function doesn't work?

**Comment by theNded** [comment]
Please read the error message:
RuntimeError: [Open3D Error] (class std::shared_ptr __cdecl open3d::geometry::PointCloud::Crop(const class open3d::geometry::AxisAlignedBoundingBox &) const) D:\a\Open3D\Open3D\cpp\open3d\geometry\PointCloud.cpp:486: [CropPointCloud] **AxisAlignedBoundingBox either has zeros size**, or has wrong bounds.

**Comment by 155cannon** [comment]
I see that the AxisAlignedBoundingBox must be 3D, so can't Open3D process 2D point cloud now?

**Comment by theNded** [comment]
If a dimension is degenerated, you can increase it manually to lift the rectangle to an aabb. It is very straightforward and does not require any advanced knowledge. Please think when you use libraries.
