### ISSUE TITLE
Change far and near planes of Camera while using SceneWidget instead of Visualizer

### ISSUE THREAD

**Issue by Alex-Dee** [isl-org/Open3D#4772]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi, 
is there a possibility to set z min/max values when using SceneWidget to prevent geometries being clipped? Currently geometries like point clouds seem to disappear when looked at from certain angles or zoom levels and I suspect they are beeing clipped because their bounding boxes are getting to small or big.

**Comment by errissa** [comment]
Can you share either a sample data set or script that demonstrates the issue you're having?

By default the visualizer will set the near and far planes to encompass the bounding box of the entire scene. You can check the computed near/far planes using the `Camera`'s `get_near` and `get_far` methods. You can change the default behavior by using the `set_projection` functions of `Camera` to explicitly specify the near and far planes.

**Comment by Alex-Dee** [comment]
Okay the issue got resolved by calling setup_camera() from SceneWidget during initialization.

**Comment by errissa** [comment]
Glad that worked for you. `setup_camera` computes the scene bounds and adjusts the clip planes accordingly.
