### ISSUE TITLE
How to implement Faster/Tensor radius outlier removal for live point cloud  ?

### ISSUE THREAD

**Issue by maohong30** [isl-org/Open3D#4780]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi. 
I am working on live point clouds and trying to implement radius outlier removal. 
Since there is no **tensor** implementation of the function, below are my codes of doing it. 
However, it is only working for the first few frames and then crashes.

>RGBD_CUDA_PCD = o3d.t.geometry.PointCloud.create_from_rgbd_image(RGBD_CUDA, self.intrinsic_matrix, self.extrinsics, self.rgbd_metadata.depth_scale, self.depth_max, self.pcd_stride, self.flag_normals)    
                 
>RGBD_CUDA_PCD_DOWN = RGBD_CUDA_PCD.voxel_down_sample(voxel_size=0.02)
>                    
> Outlier_removal = RGBD_CUDA_PCD_DOWN.to_legacy()
>cl, ind = Outlier_removal.remove_radius_outlier(nb_points=16, radius=0.05)             
>inlier_cloud = cl.select_by_index(ind)
>RGBD_PCD_NP = np.asarray(inlier_cloud.points) 

Are there faster outlier removal methods that I can try? 
Will the **tensor** implementations be available in the future?

**Comment by theNded** [comment]
That will be on our timeline. Before that, you may refer to the [Tensor hashmap](http://www.open3d.org/docs/release/tutorial/core/hashmap.html) for fixed radius search.
