### ISSUE TITLE
/docker_build.sh openblas-amd64-py38 fails with "Could not open '/lib64/ld-linux-x86-64.so.2'"

### ISSUE THREAD

**Issue by theRealSuperMario** [isl-org/Open3D#4781]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

Fails at step [20]

### Steps to reproduce the bug

```python
/docker_build.sh openblas-amd64-py38
# or
/docker_build.sh openblas-amd64-py38-dev
```

### Error message

 => ERROR [20/22] RUN mkdir build  && cd build  && cmake     -DBUILD_UNIT_TESTS=ON     -DCMAKE_BUILD_TYPE=Release     -DCMAKE_INSTALL_PREFIX=~/open3d_install     -DDEVELOPER_BUILD=OFF     ..  && ma  0.3s
------
 > [20/22] RUN mkdir build  && cd build  && cmake     -DBUILD_UNIT_TESTS=ON     -DCMAKE_BUILD_TYPE=Release     -DCMAKE_INSTALL_PREFIX=~/open3d_install     -DDEVELOPER_BUILD=OFF     ..  && make -j$(nproc)  && make install-pip-package -j$(nproc)  && make install -j$(nproc)  && pyenv rehash:
#24 0.324 qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
------
executor failed running [/bin/bash -c mkdir build  && cd build  && cmake     -DBUILD_UNIT_TESTS=ON     -DCMAKE_BUILD_TYPE=Release     -DCMAKE_INSTALL_PREFIX=~/open3d_install     -DDEVELOPER_BUILD=${DEVELOPER_BUILD}     ..  && make -j$(nproc)  && make install-pip-package -j$(nproc)  && make install -j$(nproc)  && pyenv rehash]: exit code: 255

### Expected behavior

I was expecting it to build the wheel as in the other docker build options. The arm64 version works.

### Open3D, Python and System information

```markdown
- macOS with M1 Apple Silicon Chip
```

**Comment by yxlao** [comment]
This issue is about "how to build x86 docker image (for Linux) on an ARM64 mac". Therefore, the issue is not particular to Open3D. We don't officially support this use case.

You might be able to get it working by:
1. Launching an x86 terminal (with Rosetta) 
2. Try to run a simple docker container and test the OS architecture:
    ```bash
    docker run --rm -t ubuntu uname -m
    ```
    If you see `aarch64`, we are still in ARM domain. If you see something like `x86_64`, now Docker is successfully setup for x86.
3. Now, in theory, you should be able to use our `docker_build.sh` script to build an x86 image.

**Comment by theRealSuperMario** [comment]
Although the issue is already closed I just add it here in case someone needs it:

Due to some other dependencies, I **have to** build the x86 version of a given linux image (its miniconda). My system is macOS M1.

I was able to build the image successfully so that `uname -m` prints `x86_64` using this line in the dockerfile
```bash
FROM --platform=linux/amd64 continuumio/miniconda3:latest
```
However, now running this simple script of open3D inside the container crashes.

```python
import open3d as o3d

# Create scene and add a cube
cube = o3d.t.geometry.TriangleMesh.from_legacy(o3d.geometry.TriangleMesh.create_box())
scene = o3d.t.geometry.RaycastingScene()
scene.add_triangles(cube) # <--
# qemu: uncaught target signal 11 (Segmentation fault) - core dumped
# Segmentation fault

# Use a helper function to create rays for a pinhole camera.
# rays = scene.create_rays_pinhole(fov_deg=60, center=[0.5,0.5,0.5], eye=[-1,-1,-1], up=[0,0,1],
#                                 width_px=320, height_px=240)

# Compute the ray intersections and visualize the hit distance (depth)
# ans = scene.cast_rays(rays)
```

Note that one might need to specify the platform for `docker run`
```
~ docker run --rm -t ubuntu uname -m
aarch64
~ docker run --platform=linux/amd64 --rm -t ubuntu uname -m
x86_64
```

As the error message indicates and what you pointed out, I might need to have a look into qemu.

Thanks for the help.
