### ISSUE TITLE
Pip can't find 0.15.1

### ISSUE THREAD

**Issue by joshuafishman** [isl-org/Open3D#4796]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Steps to reproduce the issue

Pip (version 22.0.3) can't find the 0.15.1 version even though it's on pypi:
```
pip install open3d==0.15.1 
ERROR: Could not find a version that satisfies the requirement open3d==0.15.1 (from versions: 0.10.0.0, 0.11.0, 0.11.1, 0.11.2, 0.12.0, 0.13.0, 0.14.1)
ERROR: No matching distribution found for open3d==0.15.1
```
The wheel on the installation page (https://storage.googleapis.com/open3d-releases-master/python-wheels/open3d-0.15.1-cp38-cp38-manylinux_2_27_x86_64.whl) works fine as a workaround.

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04 
- Python version: Python 3.8 
- Open3D version: 0.15.1
- System architecture: x86 
- Is this a remote workstation?: no
- How did you install Open3D?: pip
```

**Comment by yxlao** [comment]
We are waiting for https://github.com/pypa/pypi-support/issues/1701 . 

For now you may get it from: http://www.open3d.org/docs/latest/getting_started.html#development-version-pip .

**Comment by yxlao** [comment]
We have an update. We have created a special 0.15.2 release for Linux x86 users only. Linux x86 users don't get 0.15.1. 

Now
```
pip install open3d
```
should give you the 0.15.2 release on Linux x86.

**Comment by wwwouter** [comment]
I'm in this situation where development is done on Windows and macOS and the build server runs Linux.

Do we have to wait for 0.16 for this to be resolved?

**Comment by johnthagen** [comment]
For now the only solution I know of is to pin to 0.14.1, which is the latest version released that has all of the needed wheels.

@yxlao Do you know if a new version of Open3D will be released soon that includes all of the needed wheels?

Thanks.
