### ISSUE TITLE
Add triangles throws incompatible arguments error

### ISSUE THREAD

**Issue by arpan-kusari** [isl-org/Open3D#4799]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I am trying to perform raycasting with the mesh from bunny model but getting an error when I call `add_triangles`:

```
bunny = o3d.data.BunnyMesh()
mesh = o3d.io.read_triangle_mesh(bunny.path)
scene = o3d.t.geometry.RaycastingScene()
scene.add_triangles(mesh)
```
The error stacktrace is:

```
Traceback (most recent call last):
  File "C:\Users\kusari\Documents\Python Projects\Topology-preserving-registration\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3251, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-09babb881753>", line 1, in <module>
    scene.add_triangles(mesh.TriangleMesh)
TypeError: add_triangles(): incompatible function arguments. The following argument types are supported:
    1. (self: open3d.cpu.pybind.t.geometry.RaycastingScene, vertex_positions: open3d.cpu.pybind.core.Tensor, triangle_indices: open3d.cpu.pybind.core.Tensor) -> int
    2. (self: open3d.cpu.pybind.t.geometry.RaycastingScene, mesh: open3d.cpu.pybind.t.geometry.TriangleMesh) -> int
```
I have tried changing `scene.add_triangles(mesh)` to `scene.add_triangles(mesh.vertices, mesh.triangles)` and `scene.add_triangles(mesh.TriangleMesh)` but neither has worked.

**Comment by theNded** [comment]
Please use `mesh = o3d.t.geometry.TriangleMesh.from_legacy(o3d.io.read_triangle_mesh(bunny.path))`.
