### ISSUE TITLE
Error when going from point cloud to mesh 

### ISSUE THREAD

**Issue by arpan-kusari** [isl-org/Open3D#4800]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I have the pcd file of stanford bunny which I read using `read_point_cloud` method. However, when I try to get the `add_triangles` using the mesh generated, I get an incompatible argument error:
```
bunny = o3d.io.read_point_cloud('stanford_bunny_0deg.pcd')
bunny.estimate_normals()
# to obtain a consistent normal orientation
bunny.orient_normals_towards_camera_location(bunny.get_center())
mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_poisson(bunny, depth=9)
scene = o3d.t.geometry.RaycastingScene()
scene.add_triangles(mesh)
```
TypeError: add_triangles(): incompatible function arguments. The following argument types are supported:
    1. (self: open3d.cpu.pybind.t.geometry.RaycastingScene, vertex_positions: open3d.cpu.pybind.core.Tensor, triangle_indices: open3d.cpu.pybind.core.Tensor) -> int
    2. (self: open3d.cpu.pybind.t.geometry.RaycastingScene, mesh: open3d.cpu.pybind.t.geometry.TriangleMesh) -> int

**Comment by yxlao** [comment]
Things inside the `o3d.t.` namespace typically require tensor-based geometry.

```python
t_mesh = o3d.t.geometry.TriangleMesh.from_legacy(mesh)
...
```

In the future, we will move all legacy data structures to `o3d.v0.xxx` and make the `o3d.t` be default.

**Comment by arpan-kusari** [comment]
Hi Yixing, Thank you for your answer. I am still getting this error: 

```
Traceback (most recent call last):
  File "C:\Users\kusari\Documents\Python Projects\Topology-preserving-registration\main.py", line 116, in <module>
    mesh = o3d.t.geometry.TriangleMesh.from_legacy(mesh)
TypeError: from_legacy(): incompatible function arguments. The following argument types are supported:
    1. (mesh_legacy: open3d.cpu.pybind.geometry.TriangleMesh, vertex_dtype: open3d.cpu.pybind.core.Dtype = Float32, triangle_dtype: open3d.cpu.pybind.core.Dtype = Int64, device: open3d.cpu.pybind.core.Device = CPU:0) -> open3d.cpu.pybind.t.geometry.TriangleMesh
```
