### ISSUE TITLE
Add colour to exported meshes

### ISSUE THREAD

**Issue by SamTov** [isl-org/Open3D#4801]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Proposed new feature or change

I am using the file writing functionality of Open3D to export some mesh to a Blender readable format before rendering it and/or making an animation. The scenes that written to a 3d model file have colours however the model files, even the ones capable of storing colour information, do not. I was wondering if it is possible to add the colour information to the files or if I am missing something.

** Update **

I think that #4794 is very much related to the issue I have here as I sum over several meshes to create a single large one that is then exported.

**Comment by theNded** [comment]
Can you specify the format and snippet you are using for exporting the mesh?
@errissa @reyanshsolis could this be related to the format issue? I remember float32 colors are not recognized in several softwares, storing uint8 is necessary sometimes.

**Comment by SamTov** [comment]
Absolutely. So I have  a set of sphere meshes generated using the `TriangleMesh` class within Open3D and on each of the spheres I have called `paint_uniform`. Then I do something like the following:

```python
meshes = [sphere_1, sphere_2, ...]
global_mesh = sphere_1

for item in meshes[1:]:
    global_mesh += item

o3d.io.write_triangle_mesh(f"My_mesh_{self.counter}.stl/ply/gltf", mesh)
```

I have tried all file format on single and multi meshes now and none of them produce a colour when I load them in Blender.

**Comment by theNded** [comment]
I tested the snippet and can see the same issue in blender. I'm not familiar with blender but I suspect the problem might be on their side -- the colors show up in other softwares, including open3d-viewer, meshlab, [3dviewer](https://3dviewer.net/), etc.

`paint_uniform_color` attaches color to vertices, but #4794 deals with uv coordinates so it is irrelevant. Could you please double-check if blender supports vertex-wise color? Or could you find a mesh whose vertex-wise color is correctly shown in blender?

**Comment by errissa** [comment]
There is some information [here](https://blender.stackexchange.com/questions/90890/how-to-display-and-use-vertex-color-from-obj-model) at the bottom of the post that might be helpful. Also, I seem to recall that Blender doesn't support loading vertex colors automatically. There is some work required unlike the viewers @theNded mentioned.
