### ISSUE TITLE
AttributeError: module 'open3d' has no attribute 'data'

### ISSUE THREAD

**Issue by jinfagang** [isl-org/Open3D#4803]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

AttributeError: module 'open3d' has no attribute 'data'

### Steps to reproduce the bug

```python
AttributeError: module 'open3d' has no attribute 'data'
```

### Error message

AttributeError: module 'open3d' has no attribute 'data'

### Expected behavior

AttributeError: module 'open3d' has no attribute 'data'

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04 / macOS 10.15 / Windows 10 64-bit
- Python version: Python 3.8 / output from `import sys; print(sys.version)`
- Open3D version: output from python: `print(open3d.__version__)`
- System architecture: x86 / arm64 / apple-silicon / jetson / rpi
- Is this a remote workstation?: yes or no
- How did you install Open3D?: pip / conda / build from source
- Compiler version (if built from source): gcc 7.5 / clang 7.0
```

### Additional information

AttributeError: module 'open3d' has no attribute 'data'

**Comment by theNded** [comment]
download and install 0.15.1 from http://www.open3d.org/docs/latest/getting_started.html
