### ISSUE TITLE
make pip-package error

### ISSUE THREAD

**Issue by jinfagang** [isl-org/Open3D#4804]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

 make pip-package                                            2 ↵

Error removing directory "/tmp/Open3D/build/bin/resources/html".
make[3]: *** [cpp/open3d/visualization/webrtc_server/CMakeFiles/copy_html_dir.dir/build.make:70: cpp/open3d/visualization/webrtc_server/CMakeFiles/copy_html_dir] Error 1
make[2]: *** [CMakeFiles/Makefile2:3222: cpp/open3d/visualization/webrtc_server/CMakeFiles/copy_html_dir.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:3761: cpp/pybind/CMakeFiles/pip-package.dir/rule] Error 2
make: *** [Makefile:1138: pip-package] Error 2

### Steps to reproduce the bug

```python
make pip-package                                            2 ↵

Error removing directory "/tmp/Open3D/build/bin/resources/html".
make[3]: *** [cpp/open3d/visualization/webrtc_server/CMakeFiles/copy_html_dir.dir/build.make:70: cpp/open3d/visualization/webrtc_server/CMakeFiles/copy_html_dir] Error 1
make[2]: *** [CMakeFiles/Makefile2:3222: cpp/open3d/visualization/webrtc_server/CMakeFiles/copy_html_dir.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:3761: cpp/pybind/CMakeFiles/pip-package.dir/rule] Error 2
make: *** [Makefile:1138: pip-package] Error 2
```

### Error message

 make pip-package                                            2 ↵

Error removing directory "/tmp/Open3D/build/bin/resources/html".
make[3]: *** [cpp/open3d/visualization/webrtc_server/CMakeFiles/copy_html_dir.dir/build.make:70: cpp/open3d/visualization/webrtc_server/CMakeFiles/copy_html_dir] Error 1
make[2]: *** [CMakeFiles/Makefile2:3222: cpp/open3d/visualization/webrtc_server/CMakeFiles/copy_html_dir.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:3761: cpp/pybind/CMakeFiles/pip-package.dir/rule] Error 2
make: *** [Makefile:1138: pip-package] Error 2

### Expected behavior

 make pip-package                                            2 ↵

Error removing directory "/tmp/Open3D/build/bin/resources/html".
make[3]: *** [cpp/open3d/visualization/webrtc_server/CMakeFiles/copy_html_dir.dir/build.make:70: cpp/open3d/visualization/webrtc_server/CMakeFiles/copy_html_dir] Error 1
make[2]: *** [CMakeFiles/Makefile2:3222: cpp/open3d/visualization/webrtc_server/CMakeFiles/copy_html_dir.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:3761: cpp/pybind/CMakeFiles/pip-package.dir/rule] Error 2
make: *** [Makefile:1138: pip-package] Error 2

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04 / macOS 10.15 / Windows 10 64-bit
- Python version: Python 3.8 / output from `import sys; print(sys.version)`
- Open3D version: output from python: `print(open3d.__version__)`
- System architecture: x86 / arm64 / apple-silicon / jetson / rpi
- Is this a remote workstation?: yes or no
- How did you install Open3D?: pip / conda / build from source
- Compiler version (if built from source): gcc 7.5 / clang 7.0
```

### Additional information

 make pip-package                                            2 ↵

Error removing directory "/tmp/Open3D/build/bin/resources/html".
make[3]: *** [cpp/open3d/visualization/webrtc_server/CMakeFiles/copy_html_dir.dir/build.make:70: cpp/open3d/visualization/webrtc_server/CMakeFiles/copy_html_dir] Error 1
make[2]: *** [CMakeFiles/Makefile2:3222: cpp/open3d/visualization/webrtc_server/CMakeFiles/copy_html_dir.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:3761: cpp/pybind/CMakeFiles/pip-package.dir/rule] Error 2
make: *** [Makefile:1138: pip-package] Error 2

**Comment by yxlao** [comment]
```
make[3]: *** [cpp/open3d/visualization/webrtc_server/CMakeFiles/copy_html_dir.dir/build.make:70: cpp/open3d/visualization/webrtc_server/CMakeFiles/copy_html_dir] Error 1
```
comes from 
https://github.com/isl-org/Open3D/blob/b15f8af00c57d7b398ce37cf907572750b7b89a3/cpp/open3d/visualization/webrtc_server/CMakeLists.txt#L32-L39

I suspect some directory is missing or corrupted. 

- What is your OS? 
- Could you modify the issue description to show the detailed info?
- Could you clone open3d from scratch and build it in a non-temp directory and show your full configure and build commands?

**Comment by jinfagang** [comment]
I got it installed. turns out permission issue.
