### ISSUE TITLE
Open3D and Ubuntu 20.04 compatibility ?

### ISSUE THREAD

**Issue by devaale** [isl-org/Open3D#4807]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hello, just a simple question for those who have tried Open3D lib on their Ubuntu 20.04 - are there any known issues or troubles you've ran into while developing on this version of Ubuntu ? - Asking because previous project I was doing on Ubuntu 18.04 was a success and we're going forward with the other project, however this time PC we're ordering only is compatible with Ubuntu 20.04. Appreciate in advance <3

**Comment by theNded** [comment]
I'm developing under 20.04. There are no known issues as of now.

**Comment by devaale** [comment]
> I'm developing under 20.04. There are no known issues as of now.

Appreciate the input, gonna go forward with Ubuntu 20.04 then ❤️
