### ISSUE TITLE
add_geometry(): incompatible function arguments

### ISSUE THREAD

**Issue by RichardSnijder** [isl-org/Open3D#4808]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hello,

First of all, I am really enjoying the possibilities with Open3D!

However, I am having issues understanding and solving the following message:

add_geometry(): incompatible function arguments. The following argument types are supported:
1. (self: open3d.cpu.pybind.visualization.rendering.Open3DScene, name: str, geometry: open3d.cpu.pybind.geometry.Geometry3D, material: open3d.cpu.pybind.visualization.rendering.MaterialRecord, add_downsampled_copy_for_fast_rendering: bool = True) -> None
    2. (self: open3d.cpu.pybind.visualization.rendering.Open3DScene, name: str, geometry: open3d.cpu.pybind.t.geometry.Geometry, material: open3d.cpu.pybind.visualization.rendering.MaterialRecord, add_downsampled_copy_for_fast_rendering: bool = True -> None_

My aim is to open a *.txt file as a point cloud file into an already existing 3Dscene widget. 
This error occurs whenever I try to open the *.txt file using a file selector.
My code is based on the 'vis_gui.py' found on the github. (sample of the file loader function below):

`def load(self, path):
        self._scene.scene.clear_geometry()

        geometry = None
        geometry_type = o3d.io.read_file_geometry_type(path)

        mesh = None
        if geometry_type & o3d.io.CONTAINS_TRIANGLES:
            mesh = o3d.io.read_triangle_model(path)
        if mesh is None:
            print("[Info]", path, "appears to be a point cloud")
            cloud = None
            try:
                cloud = o3d.io.read_point_cloud(path)
            except Exception:
                pass
            if cloud is not None:
                print("[Info] Successfully read", path)
                if not cloud.has_normals():
                    cloud.estimate_normals()
                cloud.normalize_normals()
                geometry = cloud
            else:
                print("[WARNING] Failed to read points", path)

        if geometry is not None or mesh is not None:
            try:
                if mesh is not None:
                    # Triangle model
                    self._scene.scene.add_model("__model__", mesh)
                else:
                    # Point cloud

                    # CODE STOPS WORKING HERE

                    self._scene.scene.add_geometry("__model__", geometry,
                                                   self.settings.material)
                bounds = self._scene.scene.bounding_box
                self._scene.setup_camera(60, bounds, bounds.get_center())
            except Exception as e:
                print(e)`

The code runs until it is inside the else statement, line: '#CODE STOPS WORKING HERE'. 

In a previous, testing phase, I was able to execute a similar task (reading *.txt file as pcd), however this was using the 'draw_geometries' method. This resulted in the code opening a new window in which the point cloud file was shown perfectly. 

I am trying to achieve the same, however with the add_geometry function this time, to get it in the already existing widget, instead of the draw_geometries(), where a new window is opened. In addition, the points generated in the widget should have colors ordered by Z value (a colormap), for my understanding is that the same as using 'material'?

Is there anyone who can help me achieve this result? Please let me know if additional information is required.

Thanks in advance!

Kind regards,
Richard Snijder

**Comment by errissa** [comment]
Can you elaborate on how you load the txt file? What code do you use to do that? A file with a `.txt` extension would not normally be recognized by Open3D as a valid file type.

The `vis_gui.py` example creates a default material for the loaded geometry based on the properties of the geometry. You shouldn't have to do anything else at that point. To view the point cloud depths you can select the `Depth` material type from the `Material Settings` -> `Type` combo box.

**Comment by RichardSnijder** [comment]
Thank you @errissa  for your reply.

In the meantime, I have managed to fix this problem. Turned out that I was missing the 'Materials' section in my own code. 

Unfortunately, I am now getting stuck on the following:
### **Addressing colors to the Z value.** 

The Depth material type you (@errissa) suggested only changes the entire dataset's color based on the amount of zoom. Not exaclty what I am looking for.

the following code plots exactly what I want, where the Z value is colored based on it's height:
`vis.draw_geometries([pcd], window_name='Window Name', width=960, height=540, left=50, top=50)`

At the moment I am only able to achieve 1 color for the entire dataset. I have been looking at some questions related to this issue, but I don't quite understand how they managed to solve it. See image.



**Questions viewed:** 
#4283 'Controlling Min and Max Value of Color Range in Point Cloud Visualization'
#614 'Anyway to paint the point cloud with different colors?'

I tried recreating the first (#4283), however I still receive 1 color for the whole dataset.
![Example_Of_Actual Situation](https://user-images.githubusercontent.com/99733712/155851431-2ccb8924-33cf-4e30-82b0-0ed642acf9a8.png)

What I am trying to achieve here is that I can load in different types of color ramps, like QGIS (GIS software) does:

[[0.000% 68:1:84]
[0.392% 68:2:86]
[0.784% 69:4:87]
...
[99.216% 248:230:33]
[99.608% 251:231:35]
[100.000% 253:231:37]]
Result:   ![viridis](https://user-images.githubusercontent.com/99733712/155851362-602e2fd1-380e-452c-9702-d121e7672f1a.png)

First column shows the percentage equal to the range of Z values present.
The second column indicates the color assigned to the first column. 

I am aware that Open3D uses color values in a range of 0-1.

Can anyone help me achieve this request?

Kind regards,
Richard

**Comment by RichardSnijder** [comment]
Closed this issue with the code showed in the `closed comment` in issue #4830 _'Add_geometry() point color by Z value like o3d.visualization.draw()'_
