### ISSUE TITLE
CUDA CPU device issue with TransformationEstimationPointToPoint

### ISSUE THREAD

**Issue by zhrzhang** [isl-org/Open3D#4810]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

Hi,

I am trying to use the cuda version of TransformationEstimationPointToPoint(), and here's a snippet I've used (I've also tried directly initializing corr with corr_o3d_tensor = open3d.core.Tensor([[0], [1], [2]], device=open3d.core.Device("CUDA:0")), which doesn't work either)

### Steps to reproduce the bug

```python
TE = open3d.t.pipelines.registration.TransformationEstimationPointToPoint()
corr = torch.zeros(3, 1, dtype = torch.int64).cuda(0)
corr[:, 0] = torch.arange(0, 3)
cloud_src_cloud = open3d.t.geometry.PointCloud(device=open3d.core.Device("CUDA:0"))
cloud_tgt_cloud = open3d.t.geometry.PointCloud(device=open3d.core.Device("CUDA:0"))
cloud_src_cloud.point["positions"] = open3d.core.Tensor.from_dlpack(torch.utils.dlpack.to_dlpack(cloud_src))
cloud_tgt_cloud.point["positions"] = open3d.core.Tensor.from_dlpack(torch.utils.dlpack.to_dlpack(cloud_tgt))

transformation_o3d = TE.compute_transformation(cloud_src_cloud, cloud_tgt_cloud, corr_o3d_tensor_alt)
```

### Error message

[Open3D Error] (virtual open3d::core::Tensor open3d::t::pipelines::registration::TransformationEstimationPointToPoint::ComputeTransformation(const open3d::t::geometry::PointCloud&, const open3d::t::geometry::PointCloud&, const open3d::core::Tensor&) const) /root/Open3D/cpp/open3d/t/pipelines/registration/TransformationEstimation.cpp:101: Tensor has device CPU:0, but is expected to have CUDA:0.

### Expected behavior

Should return the transformation matrix 

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 18.04
- Python version: Python 3.9.7
- Open3D version: output from python: 0.14.1
- System architecture: x86 
- Is this a remote workstation?: yes
- How did you install Open3D?: pip
```

**Comment by theNded** [comment]
Try to print cloud_src_cloud.device, cloud_tgt_cloud.device, corr_o3d_tensor_alt.device and see which one is not on CPU.

Using this line does not guarantee the positions are on CUDA: `cloud_tgt_cloud = open3d.t.geometry.PointCloud(device=open3d.core.Device("CUDA:0"))`, when you directly assign points to its underyling tensors.

**Comment by zhrzhang** [comment]
> Try to print cloud_src_cloud.device, cloud_tgt_cloud.device, corr_o3d_tensor_alt.device and see which one is not on CUDA.
> 
> Using this line does not guarantee the positions are on CUDA: `cloud_tgt_cloud = open3d.t.geometry.PointCloud(device=open3d.core.Device("CUDA:0"))`, when you directly assign points to its underyling tensors.

Thanks for your reply! I did print the point clouds and the tensor by
```
print(cloud_src_cloud)
print(cloud_tgt_cloud)
print(corr_o3d_tensor)
```
and the outputs are 
```
PointCloud on CUDA:0 [3 points (Float64)] Attributes: None.
PointCloud on CUDA:0 [3 points (Float64)] Attributes: None.
[[0],
 [1],
 [2]]
Tensor[shape={3, 1}, stride={1, 1}, Int64, CUDA:0, 0x7f99df800200]
```
which I assumed both the point clouds and the correspondence tensor are on CUDA. Do you have any suggestions on this? Also, if I would like to construct a point cloud on CUDA, what would be a proper way to do it instead of assigning points to its underlying tensors by using 
```
cloud_src_cloud.point["positions"] = open3d.core.Tensor.from_dlpack(torch.utils.dlpack.to_dlpack(cloud_src))
```
I was following this [doc](http://www.open3d.org/docs/latest/python_api/open3d.t.geometry.PointCloud.html#open3d.t.geometry.PointCloud), but didn't find any other docs on how to do this. Thanks!

**Comment by theNded** [comment]
@reyanshsolis any idea why? I guess this function was hided from users...

**Comment by zhrzhang** [comment]
> @reyanshsolis any idea why? I guess this function was hidden from users...

Do you have any workaround suggestion on this? I am using the point to point transformation estimation to solve the transformation matrix with RANSAC, and I would like to use CUDA to do computation. Thanks!

**Comment by reyanshsolis** [comment]
@zhrzhang 
May you please attach the entire code? (including src and target point-clouds) ?

Reference unit test: https://github.com/isl-org/Open3D/blob/master/python/test/t/registration/test_transformation_estimation.py

**Comment by zhrzhang** [comment]
@reyanshsolis 
Thanks for your reply! I managed to fix this by explicitly initializing the Nx3 torch tensor on cuda and it doesn't have the error anymore. For some reason if the Nx3 torch tensor is initialized on CPU and initializing 
```
src_cloud = open3d.t.geometry.PointCloud(device=open3d.core.Device("CUDA:0"))
cloud_src_cloud.point["positions"] = open3d.core.Tensor.from_dlpack(torch.utils.dlpack.to_dlpack(cloud_src))
```
will have that error. Thanks for your help @reyanshsolis @theNded !
