### ISSUE TITLE
Issues Running Global Registration on My Datasets

### ISSUE THREAD

**Issue by braden-dev** [isl-org/Open3D#4812]
### Checklist

- [x] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I implemented the global registration code found [here](http://www.open3d.org/docs/latest/tutorial/Advanced/global_registration.html) and it works great with the sample point clouds provided; however, I'm having issues with these point clouds ([MyPointClouds.zip](https://github.com/isl-org/Open3D/files/8149075/MyPointClouds.zip)). I have been editing the values in the global registration script that I copied but I can't seem to get the point clouds to line up consistently. Sometimes they line up pretty well but the next time I run it they don't match at all.

I also can't get the local refinement with point-to-plane ICP to work with these point clouds. I get the error:
`RuntimeError: [Open3D Error] (class open3d::pipelines::registration::RegistrationResult __cdecl open3d::pipelines::registration::RegistrationICP(const class open3d::geometry::PointCloud &,const class open3d::geometry::PointCloud &,double,const class Eigen::Matrix<double,4,4,0,4,4> &,const class open3d::pipelines::registration::TransformationEstimation &,const class open3d::pipelines::registration::ICPConvergenceCriteria &)) D:\a\Open3D\Open3D\cpp\open3d\pipelines\registration\Registration.cpp:147: TransformationEstimationPointToPlane and TransformationEstimationColoredICP require pre-computed normal vectors for target PointCloud.`

Here's the code that I'm using to get these results. I have been adjusting the `radius_normal`, `radius_feature`, and `distance_threshold` values to try to get better results but I'm not really sure what I'm doing. Thanks in advance for any help!

```
from cv2 import threshold
import open3d as o3d
import numpy as np
import copy

voxel_size = 0.0125

def draw_registration_result(source, target, transformation):
    source_temp = copy.deepcopy(source)
    target_temp = copy.deepcopy(target)
    source_temp.paint_uniform_color([1, 0.706, 0])
    target_temp.paint_uniform_color([0, 0.651, 0.929])
    source_temp.transform(transformation)
    o3d.visualization.draw_geometries([source_temp, target_temp],
                                      zoom=0.4559,
                                      front=[0.6452, -0.3036, -0.7011],
                                      lookat=[1.9892, 2.0208, 1.8945],
                                      up=[-0.2779, -0.9482, 0.1556])


def preprocess_point_cloud(pcd, voxel_size):
    print(":: Downsample with a voxel size %.3f." % voxel_size)
    pcd_down = pcd.voxel_down_sample(voxel_size)

    radius_normal = voxel_size * 100
    print(":: Estimate normal with search radius %.3f." % radius_normal)
    pcd_down.estimate_normals(
        o3d.geometry.KDTreeSearchParamHybrid(radius=radius_normal, max_nn=30))

    radius_feature = voxel_size * 500
    print(":: Compute FPFH feature with search radius %.3f." % radius_feature)
    pcd_fpfh = o3d.pipelines.registration.compute_fpfh_feature(
        pcd_down,
        o3d.geometry.KDTreeSearchParamHybrid(radius=radius_feature, max_nn=100))
    return pcd_down, pcd_fpfh

def prepare_dataset(voxel_size):
    print(":: Load two point clouds and disturb initial pose.")

    #Rover Models
    source = o3d.io.read_point_cloud("reconstructed-rover.pcd")
    target = o3d.io.read_point_cloud("ideal-rover.pcd")

    trans_init = np.asarray([[0.0, 0.0, 1.0, 0.0], [1.0, 0.0, 0.0, 0.0],
                             [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 0.0, 1.0]])
    source.transform(trans_init)

    #displays the models without transformation/rotation
    # draw_registration_result(source, target, np.identity(4))

    source_down, source_fpfh = preprocess_point_cloud(source, voxel_size)
    target_down, target_fpfh = preprocess_point_cloud(target, voxel_size)
    return source, target, source_down, target_down, source_fpfh, target_fpfh


source, target, source_down, target_down, source_fpfh, target_fpfh = prepare_dataset(voxel_size)

#RANSAC 
def execute_global_registration(source_down, target_down, source_fpfh,
                                target_fpfh, voxel_size):
    distance_threshold = voxel_size * 150
    print(":: RANSAC registration on downsampled point clouds.")
    print("   Since the downsampling voxel size is %.3f," % voxel_size)
    print("   we use a liberal distance threshold %.3f." % distance_threshold)
    result = o3d.pipelines.registration.registration_ransac_based_on_feature_matching(
        source_down, target_down, source_fpfh, target_fpfh, False, distance_threshold,
        o3d.pipelines.registration.TransformationEstimationPointToPoint(False),
        4, [
            o3d.pipelines.registration.CorrespondenceCheckerBasedOnEdgeLength(
                0.9),
            o3d.pipelines.registration.CorrespondenceCheckerBasedOnDistance(
                distance_threshold)
        ], o3d.pipelines.registration.RANSACConvergenceCriteria(4000000, 500))
    # result = o3d.pipelines.registration.registration_ransac_based_on_feature_matching(
    #     source_down, target_down, source_fpfh, target_fpfh, distance_threshold)
    return result

result_ransac = execute_global_registration(source_down, target_down,
                                            source_fpfh, target_fpfh,
                                            voxel_size)

print(result_ransac)
draw_registration_result(source_down, target_down, result_ransac.transformation)

# Local refinement with point-to-plane ICP
def refine_registration(source, target, source_fpfh, target_fpfh, voxel_size):
    distance_threshold = voxel_size * 0.4
    print(":: Point-to-plane ICP registration is applied on original point")
    print("   clouds to refine the alignment. This time we use a strict")
    print("   distance threshold %.3f." % distance_threshold)
    result = o3d.pipelines.registration.registration_icp(
        source, target, distance_threshold, result_ransac.transformation,
        o3d.pipelines.registration.TransformationEstimationPointToPlane())
    return result

result_icp = refine_registration(source, target, source_fpfh, target_fpfh,
                                 voxel_size)
print(result_icp)
draw_registration_result(source, target, result_icp.transformation)
```

**Comment by theNded** [comment]
Have you tried the latest development wheel (i.e. 0.15.1)? There has been a bug in RANSAC that was fixed recently.

For point to plane ICP, as the log indicated you need to compute normals. In the snippet it was only done for the downsampled point clouds.

**Comment by braden-dev** [comment]
> Have you tried the latest development wheel (i.e. 0.15.1)? There has been a bug in RANSAC that was fixed recently.
> 
> For point to plane ICP, as the log indicated you need to compute normals. In the snippet it was only done for the downsampled point clouds.

I am using the latest update (when I run "python -c "import open3d as o3d; print(o3d.__version__)"" it prints out "0.15.1").

As for computing the normals, whenever I use the demo point clouds there isn't a problem so I wouldn't think there's anything wrong with the code. My guess would be I need to change the `radius_normal` and `radius_feature` but I'm not sure.

**Comment by theNded** [comment]
You are right, voxel_size * 100 or 150 doesn't make any sense in a realistic setup, sorry I didn't pay attention to it. It's better to keep the multiplier unchanged and only tune voxel_size according to your point cloud scale.

**Comment by theNded** [comment]
> As for computing the normals, whenever I use the demo point clouds there isn't a problem so I wouldn't think there's anything wrong with the code. My guess would be I need to change the `radius_normal` and `radius_feature` values but I'm not sure.

I think the demo point cloud files already have normals, so you don't have to compute them again and ICP still works. It is likely that your point clouds don't have normals, so you need to manually call `estimate_normals`, not just for downsampled pcd but for the original pcd as you are refining.

**Comment by braden-dev** [comment]
> > As for computing the normals, whenever I use the demo point clouds there isn't a problem so I wouldn't think there's anything wrong with the code. My guess would be I need to change the `radius_normal` and `radius_feature` values but I'm not sure.
> 
> I think the demo point cloud files already have normals, so you don't have to compute them again and ICP still works. It is likely that your point clouds don't have normals, so you need to manually call `estimate_normals`, not just for downsampled pcd but for the original pcd as you are refining.

Okay, that seemed to do the trick. Thank you, really appreciate your help!
