### ISSUE TITLE
ScalableTSDFVolume Integrate Running Slow for real time large scale reconstruction 

### ISSUE THREAD

**Issue by jianchong-chen** [isl-org/Open3D#4816]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Thanks for your great work! 
I used open3D to reconstruct a large scale scene with provided RGBD & camera intrinsic & extrinsic. I hope it coud be real time. 
And I used _ScalableTSDFVolume_  to integrate the point cloud, but as the point cloud increasing, the function will be more and more slow.  
So how can I apply some strategies to prevent the problem? Thank you very much!

**Comment by theNded** [comment]
This was the legacy API that's not supposed to run in real time. Follow this [tutorial](http://www.open3d.org/docs/release/tutorial/t_reconstruction_system/index.html) and use `VoxelBlockGrid` instead.

**Comment by jianchong-chen** [comment]
Thanks for your help! @theNded
