### ISSUE TITLE
How to create a new material with custom GLSL shader in python?

### ISSUE THREAD

**Issue by cansik** [isl-org/Open3D#4818]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Is it possible to create your own material for point-cloud geometries, using custom GLSL shaders from within python (vertex & fragment)?

Rendering with custom shaders would significantly speed up the [online-processing](https://github.com/isl-org/Open3D/blob/master/examples/python/visualization/online_processing.py) example on non-CUDA devices.

**Comment by errissa** [comment]
Since we use Filament as our rendering backend we will need to expose Filament’s material system in order for you to be able to create your own materials (shaders). If you have a specific concern about performance, however, I might be able to help. For example, disabling shadowing or post-processing can improve performance.

**Comment by cansik** [comment]
@errissa Thank you for the answer.
Are you planning to expose the Filament material system?

I am mainly looking at [these lines](https://github.com/isl-org/Open3D/blob/master/examples/python/visualization/online_processing.py#L165-L171) to combine color and depth to a point-cloud. Wouldn't it be more efficient to just send the two textures to the graphics card and use a shader to combine the color, depth, intrinsic & extrinsic mat to move the pre-allocated vertices to the correct location?

At the moment I have to downscale the depth & colormap / increase the pcd-stride to be able to get decent results using this approach. Rendering the same directly with OpenGL by using a custom GLSL shader seems more performant and intuitive.

**Comment by errissa** [comment]
We may at some point, but not anytime soon.

Regarding your specific question, it may be more efficient to create the point cloud on the GPU directly from RGBD images if you only want to visualize them. However, that is not a typical use case; typically you will want to do some processing on the point clouds in which case there's no advantage to visualizing them directly from the RGBD images.

Also, please note that the Tensor-based point clouds supports operations on the GPU, so the projection of the RGBD images to a point cloud happens on the GPU (if a suitable CUDA device is available). A future release of Open3D will support visualizing tensor point clouds directly from the GPU which would be the most efficient way to visualize point clouds in the `online_processing.py` example.
