### ISSUE TITLE
Cannot open model files with PBR materials properly.

### ISSUE THREAD

**Issue by reyanshsolis** [isl-org/Open3D#4821]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

Trying to load `sword` and `crate` in the `stand-alone Open3D viewer` fails.

### Steps to reproduce the bug

```python
Open Open3D viewer, and try to load the `.obj` file present in `Open3D/examples/test_data/` `/sword` or `/crate` file.
```

### Error message

`Sword`:
```
[Open3D INFO] Skipping non-triangle primitive geometry of type: 20
[Open3D WARNING] Read geometry::Image failed: file extension png  unknown
# Fails to load the model.
```
`Crate:`
```
[Open3D INFO] Skipping non-triangle primitive geometry of type: 20
# Fails to load the model.
```

### Expected behavior

Validated the models in Meshlab. Meshlab is working fine with these two models. Open3D is expected to produce similar output.

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04 
- Python version: Python 3.8 
- Open3D version: output from python: `0.15.1+0ef9796e0`
- System architecture: x86
- Is this a remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): gcc 7.5
```

**Comment by errissa** [comment]
@reyanshsolis I can reproduce the issue. Will look into it.
