### ISSUE TITLE
Integrating two point clouds

### ISSUE THREAD

**Issue by nalinzie** [isl-org/Open3D#4829]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I am trying to create a full human body point cloud. I have two point clouds: one for front side and another for back side. 
How can I combine them into one final human body model.

**Comment by theNded** [comment]
You need to first align them using Global Registration and or ICP, or a calibration board with OpenCV if RGB images exist.
Then you can simply use the '+' operator.

**Comment by nalinzie** [comment]
To be more clear, I first collected point cloud of front part of mannequin with the background (so the point cloud includes mannequin and background). Then, I rotated the mannequin 180 degree and collected point cloud of it with background. When I tried to do ICP registration, the background of two point clouds are matched but the mannequin point cloud are not matched. Do you think removing background before doing ICP helps? or are there any solutions for this?
