### ISSUE TITLE
Add_geometry() point color by Z value like o3d.visualization.draw()

### ISSUE THREAD

**Issue by RichardSnijder** [isl-org/Open3D#4830]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hello,

I am getting stuck on the following:

I want to visualize a XYZ file in an already existing scene. Loading the file into the scene is performed using the `add_geometry()` function. In a test program I have been using the `o3d.visualization.draw()` function using the following code:

```ruby
import open3d as o3d
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

if __name__ == "__main__":
    #Load File
    a = np.loadtxt('FILENAME', dtype=float, delimiter=" ")

    #Order Array by Z value (column 3)
    geometry = a[np.argsort(a[:, 2])[::-1]]

    rows = len(geometry)

    #When Z values are negative, this if else statement switches the min and max
    if geometry[0][2] < geometry[rows - 1][2]:
        min_z_val = geometry[0][2]
        max_z_val = geometry[rows - 1][2]
    else:
        max_z_val = geometry[0][2]
        min_z_val = geometry[rows - 1][2]
    cmap_norm = mpl.colors.Normalize(vmin=min_z_val, vmax=max_z_val)

    #Assigning colors to points
    point_colors = plt.get_cmap('brg')(cmap_norm(geometry[:, -1]))[:, 0:3]

    #Create PCD visualization window
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(geometry)
    pcd.colors = o3d.utility.Vector3dVector(point_colors)
    o3d.visualization.draw([pcd])
```

The `o3d.visualization.draw()` has settings like points and colors which can be assigned using the `o3d.utility.Vector3dVector()` function. Once these values are assigned I can run the visualization command and a new widget opens in which indeed the points are visible with colors assigned to the Z value. 

However, the main difference between my test program and my main program is the following:
The main program already has an application running in which the user can select a file. Once this file is selected the program executes the `add_geometry()` function. For this function the documentation says that a material needs to be used. At the moment loading the file into the widget :

```ruby
self._scene = gui.SceneWidget()
self._scene.scene = rendering.Open3DScene(w.renderer)

self._scene.scene.add_geometry("__model__", geometry, mat)

mat = rendering.MaterialRecord()
mat.base_color = [((1/255)*223), ((1/255)*116), ((1/255)*10), 1.0]
mat.shader = 'defaultLit'
```

In this situation the `geometry` contains the XYZ file. I think I almost tried everything to accomplish the same result as in the test program (except the part where the visualization is performed in a new window), but still not the desired result, as I want the data to be shown in the already existing widget instead of a new widget...

Can somebody help me achieve the desired result by providing tips or an example on how to achieve the same result?

Please let me know if you need more information.

Kind regards,
Richard Snijder

Versions used:
Python: 3.8.0
Open3D: 0.15.1

**Comment by errissa** [comment]
If you want the new data to show in an existing widget you should access the `SceneWidget` that was already created when you initialized your application. In other words, you should not have those first two lines of code that you show above. You can add as many geometries to a single scene as you want.

**Comment by RichardSnijder** [comment]
Thank you for your reply @errissa.

But I am looking for point color adjustments in combination with the add_geometry function, as I have done for the draw() function.

Is there any way I can achieve that?

Kind regards

**Comment by RichardSnijder** [comment]
Thank you for your reply @errissa.
I have tried your suggestion. But now my `defaultUnlit` shows all points the same color: gray.
Is there any way I can change that color? Do I have to make my own `Material`?

For me I think these lines of code, belonging to the `draw` function, are critical:
```ruby
pcd = o3d.geometry.PointCloud()
point_colors = plt.get_cmap('brg')(cmap_norm(geometry[:, -1]))[:, 0:3]
pcd.colors = o3d.utility.Vector3dVector(point_colors)
``` 
`pcd.colors` in particular. Is this function applicable on the `add_geometry()` function as well?
the `plt.get_cmap('colorstyle')` part results in adjustable colormaps applied over the Z value of the data. 

Thanks in advance.

Richard

**Comment by errissa** [comment]
You don't need your own `Material`. Where in your code flow are you assigning the `point_colors` to the point cloud? You should do that _before_ you call `add_geometry`. Any changes to the point cloud after `add_geometry` will not be reflected visually. If later you need to change the point cloud, you have to call `remove_geometry` then `add_geometry` for the update point cloud.

**Comment by RichardSnijder** [comment]
Thank you for your reply @errissa, 
Your answer has proven its value!

The following lines of code did the trick for me:
```ruby
    def load(self, path):
        #clear the screen of any content
        self._scene.scene.clear_geometry()
        cloud = None

        #open file as point cloud
        cloud = o3d.io.read_point_cloud(path, format='xyz')

        #order array by Z value (column 3)
        sorted_z = np.asarray(cloud.points)[np.argsort(np.asarray(cloud.points)[:, 2])[::-1]]

        rows = len(cloud.points)
       
        cloud.normalize_normals()

        #when Z values are negative, this if else statement switches the min and max
        if sorted_z[0][2] < sorted_z[rows - 1][2]:
            min_z_val = sorted_z[0][2]
            max_z_val = sorted_z[rows - 1][2]
        else:
            max_z_val = sorted_z[0][2]
            min_z_val = sorted_z[rows - 1][2]

        #assign colors to the pointcloud file
        cmap_norm = mpl.colors.Normalize(vmin=min_z_val, vmax=max_z_val)
        #'hsv' is changeable to any name as stated here: https://matplotlib.org/stable/tutorials/colors/colormaps.html
        point_colors = plt.get_cmap('hsv')(cmap_norm(np.asarray(cloud.points)[:, -1]))[:, 0:3]
        cloud.colors = o3d.utility.Vector3dVector(point_colors)

        geometry = cloud

        self._scene.scene.add_geometry("__model__", geometry, self.settings.material)
        bounds = self._scene.scene.bounding_box
        self._scene.setup_camera(60, bounds, bounds.get_center())
```
It took me a while before I understood that the `cloud` was holding the `points` and `colors` information, which I wanted to adjust.

Ultimately I would like to adjust the `plt.get_cmap()` content inside the settings panel of the GUI. This would yield in adding the geometry once loaded and changing the point colors afterwards, do I need functions like `update_geometry()` in order to see the geometry with the new point colors assigned to it?

Thanks in advance.

Richard
