### ISSUE TITLE
Point cloud disappears in scene in zooming

### ISSUE THREAD

**Issue by forrestjgq** [isl-org/Open3D#4831]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

When a cloud is added to scene in arcball mode, and zoom it by mouse wheel, sometimes it will disapper

I found this issue in my application:

https://user-images.githubusercontent.com/18083216/156388854-54c5d038-cd7c-4959-b213-c09d36a39aea.mp4

and I tried it in latest master by Open3D:

https://user-images.githubusercontent.com/18083216/156388978-2cb81646-40cb-48e6-90dd-01c69a03ccab.mp4

it looks like a camera transforming issue

this is the file I'm using:
[7.zip](https://github.com/isl-org/Open3D/files/8170558/7.zip)

### Steps to reproduce the bug

```python
using latest Open3D:
 7.ply

rotate to some angles showed in my video, try zooming out and in to reproduce this issue
```

### Error message

None

### Expected behavior

Cloud could be small in view, even as a point, but should not disapper

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04
- Python version: Python 3.9
- Open3D version: 0.15.1
- System architecture: x86
- Is this a remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): gcc 9.3
```

### Additional information

None

**Comment by errissa** [comment]
@forrestjgq Thank you for the video and model. I was able to reproduce the behavior.

**Comment by MeyerBuaharon** [comment]
This issue is still happening in ver. 0.16
when i rotate in certain angle the pcd dissapear.
