### ISSUE TITLE
Wow to set LineSet points color

### ISSUE THREAD

**Issue by erezposner** [isl-org/Open3D#4835]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Is there a way to set the LineSet point colors?
For exampe: creating a LineSet from point cloud correspondences and keep the original points color?
Or set it manually.

Thank you

**Comment by yxlao** [comment]
### Open3D 0.x LIneSet

```python
import open3d as o3d

ls = o3d.geometry.LineSet()
ls.points = o3d.utility.Vector3dVector(ls_points) # shape: (num_points, 3)
ls.lines = o3d.utility.Vector2iVector(ls_lines)   # shape: (num_lines, 2)
ls.colors = o3d.utility.Vector3dVector(ls_colors) # shape: (num_lines, 3)
```

See it actually being used in: https://github.com/yxlao/camtools/blob/b2d91f8ee90e161d7dfbe47d88d99a5427a70b36/geometry.py#L6-L17

**Comment by erezposner** [comment]
Thank you very much
