### ISSUE TITLE
Is there a way to combine meshes in Open3D

### ISSUE THREAD

**Issue by whizbuzzer** [isl-org/Open3D#4848]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I have been trying to create a class called "Capsule" to hold a capsule mesh. My approach was to try to create the capsule mesh using the built-in sphere and cylinder meshes. My plan was:

1. To initialize two sphere meshes and a cylinder mesh
2. Translate sphere meshes to the ends/faces of the cylinder mesh
3. Create a new TriangleMesh
4. Reshape vertices of sphere and cylinder meshes to have identical shapes
5. Add those vertices arrays and set them as the vertices array of the new TriangleMesh
6. Add vertex_colors arrays and set them as the vertex_colos array of the new TriangleMesh

However, visualizing this gives me the following warning:

```
[Open3D WARNING] [SimpleShaderForTriangleMesh] Binding failed with empty triangle mesh.
[Open3D WARNING] [SimpleShaderForTriangleMesh] Binding failed when preparing data.
```
and nothing gets visualized. Any solution(s)?

**Comment by errissa** [comment]
`TriangleMesh` supports the `+=` operator so you should be able to do something like:
```
cylinder += cap1
cylinder += cap2
```

**Comment by whizbuzzer** [comment]
> `TriangleMesh` supports the `+=` operator so you should be able to do something like:
> 
> ```
> cylinder += cap1
> cylinder += cap2
> ```

Thank you very much!

**Comment by jiapei-nexera** [comment]
@errissa 

In that case, can we also do `-=` ?

For instance, I wanna a truncated cone ?

**Comment by jiapei-nexera** [comment]
Tried...

```console
unsupported operand type(s) for -: 'open3d.cpu.pybind.geometry.TriangleMesh' and 'open3d.cpu.pybind.geometry.TriangleMesh'
```

**Comment by sunch1ld** [comment]
I have tried cylinder += cap1, it combine vertex but the colors are not present in the resulting mesh, So it combine vertex but the color are not combined
