### ISSUE TITLE
Links to download Windows C++ libraries are broken

### ISSUE THREAD

**Issue by dnjiang** [isl-org/Open3D#4850]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Steps to reproduce the issue

The two links below from this page (http://www.open3d.org/docs/release/getting_started.html) are broken:
https://storage.googleapis.com/open3d-releases-master/devel/open3d-devel-windows-amd64-0.15.1.zip
https://storage.googleapis.com/open3d-releases-master/devel/open3d-devel-windows-amd64-0.15.1-dbg.zip

### Error message

```shell
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>No such object: open3d-releases-master/devel/open3d-devel-windows-amd64-0.15.1.zip</Details>
</Error>
```

### Open3D, Python and System information

```markdown
Any browser.
```

**Comment by yxlao** [comment]
## Link for `master` branch
http://www.open3d.org/docs/latest/getting_started.html

## Link for 0.15 release
https://github.com/isl-org/Open3D/releases/tag/v0.15.1

## The actual problem
The documentation is not very clear. It says in the notes below that we should go to the "latest" page to fetch the C++ binaries.
![image](https://user-images.githubusercontent.com/1501945/157014363-a20da219-d2be-4688-882f-bc3f43e2e145.png)
