### ISSUE TITLE
How to Interpret Transformation Data

### ISSUE THREAD

**Issue by braden-dev** [isl-org/Open3D#4853]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I'm using the [global_registration](http://www.open3d.org/docs/latest/tutorial/Advanced/global_registration.html) pipeline to find the transformation between two point clouds and it works great, but I'm confused on how to interpret the final transformation matrix. I want to format the data in terms of x, y, and z degree rotations but I'm a bit stuck. Does anyone have any advice on how to go about doing that?

Here's a transformation matrix that I got as an example:
`[[-7.44364791e-01 -1.40990871e-01  6.52719413e-01  1.71897392e+01]`
  `[-1.00299200e-01  9.89973840e-01  9.94578679e-02  3.64271713e+01]`
  `[-6.60197795e-01  8.56569995e-03 -7.51042942e-01  1.44904628e+02]`
  `[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]`

Thanks!

**Comment by yuecideng** [comment]
Hi, 
Simple code to convert the matrix into rotation angle& translation vector form:
```python
import numpy as np
from scipy.spatial.transform import Rotation

T = matrix # the 4x4 matrix you obtained
rotation = T[:3, :3]
translation = T[:3, 3]
# set degrees to False if you want radian value
euler_angle = Rotation.from_matrix(rotation).as_euler('xyz', degrees=True)
``` 
As show above, `transformation` is actually formed by a 3x3 rotation matrix and a 3x1 translation vector. Rotation in 3D space can also be reprented in four widely used form: 1. rotation matrix; 2. quaternion; 3. euler angle; 4. axis angle. Here we use `scipy` to convert rotation matrix into euler angle.

**Comment by braden-dev** [comment]
> Hi, Simple code to convert the matrix into rotation angle& translation vector form:
> 
> ```python
> import numpy as np
> from scipy.spatial.transform import Rotation
> 
> T = matrix # the 4x4 matrix you obtained
> rotation = T[:3, :3]
> translation = T[:3, 3]
> # set degrees to False if you want radian value
> euler_angle = Rotation.from_matrix(rotation).as_euler('xyz', degrees=True)
> ```
> 
> As show above, `transformation` is actually formed by a 3x3 rotation matrix and a 3x1 translation vector. Rotation in 3D space can also be reprented in four widely used form: 1. rotation matrix; 2. quaternion; 3. euler angle; 4. axis angle. Here we use `scipy` to convert rotation matrix into euler angle.

Thank you, that's exactly what I needed! I am curious though about the difference between rotation and translation, could you explain?

**Comment by yuecideng** [comment]
I think this is a very fundamental concept in 3D geometry, you can find a lot of materials and reference online, from which you can learn more comprehensive
