### ISSUE TITLE
Pointclouds from Azure Kinect rgbd depth image are distorted

### ISSUE THREAD

**Issue by chz31** [isl-org/Open3D#4868]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi all,

I am doing some pilot studies about using the rgbd image taken by Azure Connect to extract pointcloud and reconstruct a surface model of the object using open3d on Python. However, the point cloud of the object (a tea box) appears to be distorted as the edges are not straight and the surfaces are concave (I focused the camera on the tea box as in the first picture). I used the default configuration first with 720p color resolution (16:9).
![Azure_viewer2D_2](https://user-images.githubusercontent.com/80793828/157346664-149a4a66-8d39-46bd-ad8e-5b3f96ade92c.PNG)
![Azure_o3d1](https://user-images.githubusercontent.com/80793828/157346680-c5c7c128-9836-4d4e-9cfe-a1298aeae621.PNG)
![Azure_o3d2](https://user-images.githubusercontent.com/80793828/157346682-c1afa3ac-a699-4d5d-a481-7ada3e3bf5c1.PNG)
![Azure_o3d3](https://user-images.githubusercontent.com/80793828/157346685-d6296ff2-7a9d-4fbb-a1da-f4c838d42041.PNG)
 
I followed the examples http://www.open3d.org/docs/release/python_example/geometry/rgbd/index.html to extract depth and color values and then extracted the pointcloud. The python code is:

> config = open3d.io.AzureKinectSensorConfig()
> align_depth_to_color = True
> device = 0
> sensor = open3d.io.AzureKinectSensor(config)
> sensor.connect(device)
> rgbd = sensor.capture_frame(align_depth_to_color)
> 
> img_depth = open3d.geometry.Image(rgbd.depth)
> img_color = open3d.geometry.Image(rgbd.color)
> rgbd_image = open3d.geometry.RGBDImage.create_from_color_and_depth(img_color, img_depth, 
       convert_rgb_to_intensity=False)
> pcd = open3d.geometry.PointCloud.create_from_rgbd_image(rgbd_image, 
       open3d.camera.PinholeCameraIntrinsic(open3d.camera.PinholeCameraIntrinsicParameters.PrimeSenseDefault))
> open3d.visualization.draw_geometries([pcd])

I also toggled the resolution to 1536P (4:3) by changing the config parameter "color_resolution" 
 to "K4A_COLOR_RESOLUTION_1536P". The entire point cloud becomes distorted: 

![Azure_o3d_1536p](https://user-images.githubusercontent.com/80793828/157347540-e7650400-437f-41de-aefc-d534d70bd2e9.PNG)

I have tried to set up the camera from various distances and angles from the object, the distortion still existed to various degree.  I also played with other parameters, such as "depth_mode", but none of it helps. I wonder if any one has encounter a similar situation? I would appreciate any suggestion for changing configurations for achieving an accurate surface point cloud from the rgbd image.

Thank you!

**Comment by chz31** [comment]
@Darris01 Thank you very much! I'll try it ASAP.

I also encountered another relevant issue. I am using open3d to connect to the Azure camera's sensor and retrieve rgbd information in "rgbd" as following:
```
sensor = open3d.io.AzureKinectSensor(config)  #Config: 1536*2048 resolution and "K4A_DEPTH_MODE_WFOV_2X2BINNED" depth mode
device = 0
sensor.connect(device)
rgbd = sensor.capture_frame(align_depth_to_color)
```
I then pass the depth array directly achieved from the sensor to a (1536*2048)*3 array, which is then passed to an o3d pointcloud object as following:
```
#get depth array
depthArray = numpy. asarray(rgbd.depth)
#create an array for storing the coordinates of each pixel
points_array = numpy.zeros(shape = (1536*2048, 3))
points_array[:, 0] = numpy.repeat(list(range(1536)), 2048)
points_array[:, 1] = list(range(2048))*1536
points_array[:, 2] = depthArray.flatten()
#create a point cloud object 
pcd = open3d.geometry.PointCloud()
pcd.points = open3d.utility.Vector3dVector(points_array)
open3d.visualization.draw_geometries([pcd])
```
I though this is the most straightforward way to create a depth pointcloud as I directly pass the depth information of each pixel to each point in the pointcloud. However, the the surface column-like container becomes much less curved (the 1st picture, circled) then the one I saw in the Azure viewer v1.4.0 (the 2nd picture). 
![Inkedo3d_1536p_LI](https://user-images.githubusercontent.com/80793828/158313208-8315f51d-4f7f-462c-a563-d9363476cad6.jpg)
![viewer_1536p_wfov_binned3](https://user-images.githubusercontent.com/80793828/158313594-8b20103c-f620-4604-b3bf-112401356cbe.PNG)

In fact, for other depth mode of 4:3 resolutions, the same issue also occurred. It appears to me that the depth information acquired from  `sensor = open3d.io.AzureKinectSensor()` and` sensor.capture_frame()` is not identical to the depth information in Azure sdk viewer v1.4.0? Should I avoid achieve rgbd information in this way but only record mkv files as you suggested for accessing depth information?

Thank you again!

**Comment by theNded** [comment]
This is of course not the right way to create a point cloud. It is simply a depth map with uv coordinates without any unprojection transform. Depth maps are point clouds are equivalent ONLY under a projective/unprojective transform. Please stick to `create_from_rgbd_image` and use proper intrinsics.

**Comment by chz31** [comment]
@theNded I see. Thanks for your help!

**Comment by chz31** [comment]
@Darris01 I tried to follow the example [here](http://www.open3d.org/docs/release/tutorial/sensor/azure_kinect.html#open3d-azure-kinect-mkv-reader) and use:
 `python local_path/azure_kinect_recorder.py --output record.mkv` to record an mkv, which works well,
then use `python local_path/azure_kinect_mkv_reader.py --input record.mkv` to read the mkv. 
However, it reports an error `ModuleNotFoundError: No module named 'initialize_config'` from `from initialize_config import initialize_config`. Is 'initialize_config" a library that I need to install manually? I could not 'pip install' it.

Also I could not find an `intrinsic.json` file generated and stored locally. I assume it is different from `config.json`?

Thank you!
