### ISSUE TITLE
large torch operation fails with Segmentation Fault if open3d is imported before torch

### ISSUE THREAD

**Issue by GavinGuan95** [isl-org/Open3D#4877]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

if open3d is imported before torch, executing a large linear operation in torch fails on GPU

It doesn't fail if one of the following is satisfied:
execution is on CPU
linear operation size is small
torch is imported before open3d

### Steps to reproduce the bug

```python
>>> import open3d
>>> import torch
>>> torch.nn.functional.linear(torch.randn(16384, 256, device='cuda'), torch.randn(3, 256, device='cuda'))
```

### Error message

Python 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import open3d
>>> import torch
>>> torch.nn.functional.linear(torch.randn(16384, 256, device='cuda'), torch.randn(3, 256, device='cuda'))
Segmentation fault (core dumped)

Interestingly, importing torch first works
Python 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import open3d
>>> torch.nn.functional.linear(torch.randn(16384, 256, device='cuda'), torch.randn(3, 256, device='cuda'))
tensor([[  4.2765,  22.4891, -16.6957],
        [  7.2502,  13.0915,   7.2074],
        [  3.2700,  17.5043,  -3.3900],
        ...,
        [  3.1321,   7.3698,   5.4289],
        [ 12.0529,  -6.1390,  13.0680],
        [ 13.5407,   1.9368,   7.0946]], device='cuda:0')

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04
- Python version: 3.9.7 (default, Sep 16 2021, 13:09:58) [GCC 7.5.0]
- Open3D version: 0.15.2
- System architecture: x86, RTX3060
- Is this a remote workstation?: no
- How did you install Open3D?: pip install open3d

pip list:
addict               2.4.0
anyio                3.5.0
argon2-cffi          21.3.0
argon2-cffi-bindings 21.2.0
asttokens            2.0.5
attrs                21.4.0
Babel                2.9.1
backcall             0.2.0
bleach               4.1.0
certifi              2021.10.8
cffi                 1.15.0
charset-normalizer   2.0.12
cycler               0.11.0
debugpy              1.5.1
decorator            5.1.1
defusedxml           0.7.1
deprecation          2.1.0
entrypoints          0.4
executing            0.8.3
fonttools            4.30.0
idna                 3.3
ipykernel            6.9.1
ipython              8.1.1
ipython-genutils     0.2.0
ipywidgets           7.6.5
jedi                 0.18.1
Jinja2               3.0.3
joblib               1.1.0
json5                0.9.6
jsonschema           4.4.0
jupyter-client       7.1.2
jupyter-core         4.9.2
jupyter-packaging    0.11.1
jupyter-server       1.13.5
jupyterlab           3.3.1
jupyterlab-pygments  0.1.2
jupyterlab-server    2.10.3
jupyterlab-widgets   1.0.2
kiwisolver           1.3.2
MarkupSafe           2.1.0
matplotlib           3.5.1
matplotlib-inline    0.1.3
mistune              0.8.4
nbclassic            0.3.6
nbclient             0.5.12
nbconvert            6.4.2
nbformat             5.2.0
nest-asyncio         1.5.4
notebook             6.4.8
notebook-shim        0.1.0
numpy                1.22.3
open3d               0.15.2
packaging            21.3
pandas               1.4.1
pandocfilters        1.5.0
parso                0.8.3
pexpect              4.8.0
pickleshare          0.7.5
Pillow               9.0.1
pip                  21.2.4
prometheus-client    0.13.1
prompt-toolkit       3.0.28
ptyprocess           0.7.0
pure-eval            0.2.2
pycparser            2.21
Pygments             2.11.2
pyparsing            3.0.7
pyquaternion         0.9.9
pyrsistent           0.18.1
python-dateutil      2.8.2
pytz                 2021.3
PyYAML               6.0
pyzmq                22.3.0
requests             2.27.1
scikit-learn         1.0.2
scipy                1.8.0
Send2Trash           1.8.0
setuptools           58.0.4
six                  1.16.0
sniffio              1.2.0
stack-data           0.2.0
terminado            0.13.3
testpath             0.6.0
threadpoolctl        3.1.0
tomlkit              0.10.0
torch                1.11.0+cu113
torchaudio           0.11.0+cu113
torchvision          0.12.0+cu113
tornado              6.1
tqdm                 4.63.0
traitlets            5.1.1
typing_extensions    4.1.1
urllib3              1.26.8
wcwidth              0.2.5
webencodings         0.5.1
websocket-client     1.3.1
wheel                0.37.1
widgetsnbextension   3.5.2
```

**Comment by ssheorey** [comment]
Please try with `torch` from here:
https://github.com/isl-org/open3d_downloads/releases/tag/torch1.8.2

Do you still have this problem?

See this for details:
http://www.open3d.org/docs/latest/compilation.html#ml-module
