### ISSUE TITLE
Can build but open3d 0.15 is not installed in virtual ENV (Ubuntu 20.04) in AWS

### ISSUE THREAD

**Issue by matthewjwebster** [isl-org/Open3D#4879]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Steps to reproduce the issue

I was trying to build Open3D on my AWS EC2 instance as an ubuntu user. I went down this path after searching online and finding the link below where the user provided the steps to install on AWS:

https://gist.github.com/Manojbhat09/b8f53f68bb9719453989450fcf237bd0

Here are my commands that I used to install:

git clone --recursive https://github.com/intel-isl/Open3D
cd Open3D
util/install_deps_ubuntu.sh
sudo apt install python3.8-venv
python3 -m venv /home/ubuntu/.../Open3D/
source  /home/ubuntu/.../Open3D/bin/activate
wget https://github.com/Kitware/CMake/releases/download/v3.23.0-rc3/cmake-3.23.0-rc3-linux-x86_64.sh
7z e cmake-3.23.0-rc3-linux-x86_64.sh
chmod +x cmake-3.23.0-rc3-linux-x86_64.sh
/home/ubuntu/sw/5ggeo/equityai/v0.0.4/Open3D/cmake-3.23.0-rc3-linux-x86_64.sh
chmod +x cmake-3.23.0-rc3-linux-x86_64
cd /home/ubuntu/.../Open3D/build/
/home/ubuntu/.../Open3D/cmake-3.23.0-rc3-linux-x86_64/bin/cmake -DPYTHON_EXECUTABLE=/home/ubuntu/.../Open3D/bin/python3 -DCMAKE_INSTALL_PREFIX=/home/ubuntu/.../Open3D/open3d_install ..
make -j$(nproc)
make install
make install-pip-package
make python-package

python3 -c "import open3d"

### Error message

```shell
(Open3D) ubuntu@ip-172-31-43-99:~/.../Open3D/build$ make install-pip-package
[  0%] Built target copy_html_dir
[  0%] Built target open3d_downloads
[  1%] Built target ext_assimp
[  2%] Built target ext_eigen
[  3%] Built target ext_nanoflann
[  3%] Built target 3rdparty_glew
[  4%] Built target ext_turbojpeg
[  5%] Built target ext_jsoncpp
[  6%] Built target 3rdparty_liblzf
[  7%] Built target ext_boringssl
[  8%] Built target ext_curl
[ 10%] Built target ext_zlib
[ 11%] Built target ext_libpng
[ 11%] Built target 3rdparty_rply
[ 12%] Built target 3rdparty_tinyfiledialogs
[ 13%] Built target ext_tinygltf
[ 14%] Built target ext_tinyobjloader
[ 15%] Built target ext_qhull
[ 17%] Built target 3rdparty_qhull_r
[ 20%] Built target 3rdparty_qhullcpp
[ 20%] Built target ext_fmt
[ 21%] Built target ext_poisson
[ 22%] Built target ext_imgui
[ 22%] Built target 3rdparty_imgui
[ 23%] Built target ext_filament
[ 24%] Built target ext_zeromq
[ 25%] Built target ext_cppzmq
[ 26%] Built target ext_msgpack-c
[ 28%] Built target ext_tbb
[ 29%] Built target ext_parallelstl
[ 30%] Built target ext_mkl_include
[ 31%] Built target ext_mkl
[ 32%] Built target ext_ippicv
[ 33%] Built target ext_embree
[ 33%] Built target ext_webrtc
[ 33%] Built target ext_webrtc_all
[ 34%] Built target ext_civetweb
[ 37%] Built target glfw
[ 38%] Built target webrtc_server
[ 39%] Built target camera
[ 47%] Built target core
[ 47%] Built target data
[ 51%] Built target geometry
[ 57%] Built target io
[ 57%] Built target ml_contrib
[ 59%] Built target pipelines
[ 60%] Built target tgeometry
[ 61%] Built target tgeometry_kernel
[ 62%] Built target tio
[ 64%] Built target tpipelines
[ 65%] Built target tpipelines_kernel
[ 67%] Built target utility
[ 68%] Built target ShaderLinker
[ 68%] Built target ShaderEncoder
[ 71%] Built target shader
[ 80%] Built target visualization
[ 83%] Built target materials
[ 88%] Built target GUI
[ 88%] Built target Open3D
[100%] Built target pybind
-- Up-to-date: /home/ubuntu/sw/.../Open3D/build/lib/python_package/open3d/cpu
-- Installing: /home/ubuntu/.../Open3D/build/lib/python_package/open3d/cpu/pybind.cpython-38-x86_64-linux-gnu.so
[100%] Built target python-package
Warning: cannot import "wheel" package to build platform-specific wheel
Install the "wheel" package to fix this warning
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'
make[3]: *** [cpp/pybind/CMakeFiles/pip-package.dir/build.make:70: cpp/pybind/CMakeFiles/pip-package] Error 1
make[2]: *** [CMakeFiles/Makefile2:3752: cpp/pybind/CMakeFiles/pip-package.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:3785: cpp/pybind/CMakeFiles/install-pip-package.dir/rule] Error 2
make: *** [Makefile:1151: install-pip-package] Error 2
(Open3D) ubuntu@ip-172-31-43-99:~/.../Open3D/build$ python3 -c "import open3d"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'open3d'
```

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04 
- Python version: Python 3.8 / 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
- Open3D version: 0.15
- System architecture: x86
- Is this a remote workstation?: yes (AWS)
- How did you install Open3D?: build from source
- Compiler version (if built from source): gcc 9.4.0 (See below):
(Open3D) ubuntu@ip-172-31-43-99:~/sw/5ggeo/equityai/v0.0.4/Open3D/build$ gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
(Open3D) ubuntu@ip-172-31-43-99:~/.../Open3D/build$ which gcc
/usr/bin/gcc
(Open3D) ubuntu@ip-172-31-43-99:~/.../Open3D/build$
```

### Additional information

I did check that the python3 I am calling is from the virtual environment but it still made no difference.

**Comment by ssheorey** [comment]
Please follow these messages from your logs:

> Warning: cannot import "wheel" package to build platform-specific wheel
> Install the "wheel" package to fix this warning

We recommend using the pre-built wheel from PyPI (stable) or devel version from 
http://www.open3d.org/docs/latest/getting_started.html#development-version-pip
to avoid issues like this.

**Comment by ssheorey** [comment]
Closing - please reopen if you still have this issue.
