### ISSUE TITLE
How to save voxel data

### ISSUE THREAD

**Issue by ShalloZhao** [isl-org/Open3D#4882]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I created voxelgrid from Lidar point cloud data by (open3d.geometry.VoxelGrid.create_from_point_cloud).

My task is to save this voxel data in file by (open3d.io.write_voxel_grid()) and open it by some Viewers(ex. CloudCompare).

pointcloud = open3d.io.read_point_cloud(‘pointcloud.ply’)
voxel = open3d.geometry.VoxelGrid.create_from_point_cloud(pointcloud, voxel_size=5)
open3d.io.write_voxel_grid(‘voxelfile.***’, voxel)

What file extension I can use?(I woud like to know what is *** ↑)
I searched for it and nothing came up.
(I found out that I can use .ply . However, it is saved as pointcloud or mesh, not Voxel. )

I really appreciate if anyone can help. Thanks.

**Comment by ShalloZhao** [comment]
Just find a way to solve this problem. Save as ‘.ply’ format. And if you want to use 'open3d.io.read_voxel_grid' method to read, no characters other than English are required.

**Comment by jiazhou2023** [comment]
How can I save also the color with .ply?
