### ISSUE TITLE
Any way to extract TSDF volume from ScalableTSDFVolume?

### ISSUE THREAD

**Issue by cwchenwang** [isl-org/Open3D#4910]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I found that for UniformTSDFVolume, the raw tsdf volume can be extracted by extract_volume_tsdf. Is there any plan to support this in ScalableTSDFVolume?

**Comment by theNded** [comment]
This legacy API is going to be deprecated. Please refer to the usages [here](http://www.open3d.org/docs/release/tutorial/t_reconstruction_system/index.html).

**Comment by cwchenwang** [comment]
What is the difference if I use a VoxelBlockGrid you mentioned or ScalableTSDFVolume? Does VoxelBlockGrid just another wrapping for the underlying TSDFVolume?

**Comment by cwchenwang** [comment]
> This legacy API is going to be deprecated. Please refer to the usages [here](http://www.open3d.org/docs/release/tutorial/t_reconstruction_system/index.html).
What is the difference if I use a VoxelBlockGrid you mentioned or ScalableTSDFVolume? Does VoxelBlockGrid just another wrapping for the underlying TSDFVolume?

**Comment by theNded** [comment]
It is built on a new backend that supports GPU.
