### ISSUE TITLE
Error running 'azure_kinect_mkv_reader.py' and how to get Azure camera intrinsic

### ISSUE THREAD

**Issue by chz31** [isl-org/Open3D#4911]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi, 

I am trying to create a point cloud from Azure Kinect camera.

As suggested by https://github.com/isl-org/Open3D/issues/4868#issuecomment-1067227346 and tried to follow  [this example in the open3d doc](http://www.open3d.org/docs/release/tutorial/sensor/azure_kinect.html#open3d-azure-kinect-mkv-reader) and use:
 `python local_path/azure_kinect_recorder.py --output record.mkv` to record an mkv, which works well,
then use `python local_path/azure_kinect_mkv_reader.py --input record.mkv` to read the mkv. 
However, python reported an error `ModuleNotFoundError: No module named 'initialize_config'` from `from initialize_config import initialize_config` (line 37 of [here).](https://github.com/isl-org/Open3D/blob/master/examples/python/reconstruction_system/sensors/azure_kinect_mkv_reader.py) Is 'initialize_config" a library that I need to build from a repository? I could not 'pip install' it.

Also I could not find an `intrinsic.json` file generated and stored locally after recording the mkv as suggested here https://github.com/isl-org/Open3D/issues/4868#issuecomment-1067227346. I assume that when I changed the config.json (e.g., change resolutin & depth mode), I should not simply use the `open3d.camera.PinholeCameraIntrinsic(open3d.camera.PinholeCameraIntrinsicParameters.PrimeSenseDefault)`. If so, how to get intrinsic values and set up the intrinsic matrix by myself?

Thank you!

**Comment by theNded** [comment]
`initialize_config` is [this file](https://github.com/isl-org/Open3D/blob/master/examples/python/reconstruction_system/initialize_config.py). You don't have to build the library, but you need to clone the repo. The recorders and readers do not work alone as separate files.

`intrinsic.json` will be generated when running `azure_kinect_mkv_reader`.
