### ISSUE TITLE
Unsupported image format after PCD -> RGBD projection -> PCD

### ISSUE THREAD

**Issue by Bastiiiiii** [isl-org/Open3D#4915]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

I have a point cloud, project it to a RGBD image (do something with the RGBD image) and reproject it back to a point cloud.

This was working with the version 0.14.1+c91e0a7 but is not working with 0.15.2. Version 0.14.1 does not have the reprocetd to RGBD function.

Can you help me, or how can I install the 0.14.1+c91e0a7 version again?

Thank in advance!

### Steps to reproduce the bug

```python
import open3d as o3d

import numpy as np
import matplotlib.pyplot as plt

import argparse
import os
import cv2

if __name__ == '__main__':
    device = o3d.core.Device('CPU:0')

    pcd = o3d.io.read_point_cloud('PCD.ply')

    pcd = o3d.t.geometry.PointCloud.from_legacy(pcd).to(device)

    extrinsic = o3d.core.Tensor(np.linalg.inv([[-0.99954728,  0.02043388, -0.02208369,  0.01262137],
                                               [ 0.01687051,  0.9883951 ,  0.15096529, -0.40484494],
                                               [ 0.02491222,  0.15052438, -0.98829236,  0.52202064],
                                               [ 0.        ,  0.        ,  0.        ,  1.        ]]))

    intrinsic = o3d.core.Tensor([[919.85498046875, 0, 625.6510009765625], [0, 919.0435791015625, 334.63861083984375],
                                 [0, 0, 1]])   

    o3d.visualization.draw([pcd])
    rgbd_reproj = pcd.project_to_rgbd_image(1280,
                                            720,
                                            intrinsic, extrinsic,
                                            depth_max=10.0)

    fig, axs = plt.subplots(1, 2)
    axs[0].imshow(cv2.cvtColor(np.asarray(rgbd_reproj.color.to_legacy()), cv2.COLOR_BGR2RGB))
    axs[1].imshow(np.asarray(rgbd_reproj.depth.to_legacy()))
    plt.show()


    fx = 919.85498046875
    fy = 919.0435791015625
    cx = 625.6510009765625
    cy = 334.63861083984375
    intrinsic = o3d.camera.PinholeCameraIntrinsic(1280, 720, fx, fy, cx, cy)
    cam = o3d.camera.PinholeCameraParameters()
    cam.intrinsic = intrinsic

    c_img = o3d.geometry.Image(cv2.cvtColor(np.asarray(rgbd_reproj.color.to_legacy()), cv2.COLOR_BGR2RGB))
    d_img = rgbd_reproj.depth.to_legacy()
    rgbd = o3d.geometry.RGBDImage.create_from_color_and_depth(c_img, d_img, depth_trunc=4.0, convert_rgb_to_intensity=False)
    pcd = o3d.geometry.PointCloud.create_from_rgbd_image(rgbd, cam.intrinsic)
    o3d.visualization.draw_geometries([pcd])
```

### Error message

    pcd = o3d.geometry.PointCloud.create_from_rgbd_image(rgbd, cam.intrinsic)
RuntimeError: [Open3D Error] (static std::shared_ptr<open3d::geometry::PointCloud> open3d::geometry::PointCloud::CreateFromRGBDImage(const open3d::geometry::RGBDImage&, const open3d::camera::PinholeCameraIntrinsic&, const Matrix4d&, bool)) /root/Open3D/cpp/open3d/geometry/PointCloudFactory.cpp:197: [CreatePointCloudFromRGBDImage] Unsupported image format.

### Expected behavior

No error, RGBD to PCD reprojection

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04 
- Python version: Python 3.8 
- Open3D version: 0.14.1+c91e0a7 & 0.15.2
- System architecture: x64
- Is this a remote workstation?: no
- How did you install Open3D?: pip
```

**Comment by theNded** [comment]
Please use [this example](https://github.com/isl-org/Open3D/blob/master/examples/python/geometry/point_cloud_to_rgbd.py) and create pcd directly from `rgbd_reproj` with `o3d.t.geometry.PointCloud.create_from_rgbd_image`.

**Comment by Bastiiiiii** [comment]
Thanks, now it's working again.
