### ISSUE TITLE
TIntegrateRGBD dataset

### ISSUE THREAD

**Issue by jianchong-chen** [isl-org/Open3D#4922]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I want to run the c++ example - **TIntegrateRGBD**,  and I download the **SceneNN dataset**(016) from google drive with following the guide in project documentation.
But I found that there're only rgb and depth images in the dataset, and this demo need trajectory as an input.  
So how can I get the dataset with rgbd images & their trajectory? 
Thanks!

**Comment by theNded** [comment]
There are pose.txt files for ScanNet. You can parse these files and convert them to trajectory log file with this format description in mind: http://redwood-data.org/indoor/fileformat.html

**Comment by jianchong-chen** [comment]
Thanks for your help!

**Comment by theNded** [comment]
Ah somehow I have misunderstood your issue, apologize! SceneNN is not ScanNet. I will look into it and upload trajectory files soon.

**Comment by jianchong-chen** [comment]
OK! I've downloaded another dataset from redwood to run the example, thanks!
