### ISSUE TITLE
Tensor TriangleMesh.from_legacy() using python multiprocessing gets stuck in waiting.

### ISSUE THREAD

**Issue by dalnoguer** [isl-org/Open3D#4923]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

Hello everyone,

I am trying to speed up the raycasting scene by using python multiprocessing. 

Loading the mesh in legacy format is fine, but when I try to convert the mesh to tensor format it gets stuck in waiting.

### Steps to reproduce the bug

```
python
import open3d as o3d

def load_meshes(num):
    mesh_path = "..."
    obj_mesh = o3d.io.read_triangle_mesh(mesh_path))
    obj_mesh = o3d.t.geometry.TriangleMesh.from_legacy(obj_mesh)

parallel_jobs = 3
pool = multiprocessing.Pool(parallel_jobs)
list = [1, 2, 3]
pool.map(load_meshes, list)
```

### Error message

It gets stuck, no error message.
When I terminate the program I get this:

```
^CTraceback (most recent call last):
  File "oa_datasets/modules/segmentation_mask_generation/segmentation_mask_projector.py", line 219, in <module>
    pool.map(load_meshes, list)
  File "/home/dnoguer/miniconda3/envs/oa_datasets/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/dnoguer/miniconda3/envs/oa_datasets/lib/python3.7/multiprocessing/pool.py", line 651, in get
    self.wait(timeout)
  File "/home/dnoguer/miniconda3/envs/oa_datasets/lib/python3.7/multiprocessing/pool.py", line 648, in wait
    self._event.wait(timeout)
  File "/home/dnoguer/miniconda3/envs/oa_datasets/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/home/dnoguer/miniconda3/envs/oa_datasets/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt
```

### Expected behavior

I would expect to run in parallel, since the mesh is around 70MB and there is plenty of memory.

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04
- Python version: Python 3.7.11
- Open3D version: 0.14.1
- System architecture: x86
- Is this a remote workstation?: yes
- How did you install Open3D?: pip
```

**Comment by jordanott** [comment]
Any update on this?

**Comment by benjaminum** [comment]
How is the example related to raycasting?

**Comment by jordanott** [comment]
The call to `o3d.t.geometry.TriangleMesh.from_legacy` is needed in order to create a `RaycastingScene` later on. However, the bug occurs on that line, so we never make it to create the scene. This would be a more complete example based on the [raycasting tutorial](http://www.open3d.org/docs/latest/tutorial/geometry/ray_casting.html#Ray-Casting) 

```python 
import multiprocessing
import open3d as o3d

def ray_cast(i):
    # Load mesh and convert to open3d.t.geometry.TriangleMesh
    cube = o3d.geometry.TriangleMesh.create_box().translate([0, 0, 0])
    cube = o3d.t.geometry.TriangleMesh.from_legacy(cube)

    # Create a scene and add the triangle mesh
    scene = o3d.t.geometry.RaycastingScene()
    cube_id = scene.add_triangles(cube)

    # The first ray starts at (0.5,0.5,10) and has direction (0,0,-1).
    # The second ray start at (-1,-1,-1) and has direction (0,0,-1).
    rays = o3d.core.Tensor([
        [0.5, 0.5, 10, 0, 0, -1], 
        [-1, -1, -1, 0, 0, -1]
    ], dtype=o3d.core.Dtype.Float32)

    ans = scene.cast_rays(rays)
    print(ans)

# Serial ray cast
ray_cast(0)

parallel_jobs = 3
pool = multiprocessing.Pool(parallel_jobs)
list = [1, 2, 3]
pool.map(ray_cast, list)
```

**Comment by benjaminum** [comment]
OK, so the problem it is not related to RaycastingScene. I changed the title to reflect this.

Can you reproduce the problem without reading data by creating meshes for example with TriangleMesh.create_sphere()?

**Comment by benjaminum** [comment]
You need to create the processes in `__main__`

```python
import multiprocessing
import open3d as o3d

def create_triangle_mesh_from_legacy(i):
    sphere = o3d.geometry.TriangleMesh.create_sphere()
    print("Sphere created")

    sphere = o3d.t.geometry.TriangleMesh.from_legacy(sphere)
    print("Sphere converted to TriangleMesh from legacy")

if __name__ == '__main__':
    parallel_jobs = 3
    pool = multiprocessing.Pool(parallel_jobs)
    pool.map(create_triangle_mesh_from_legacy, [1, 2, 3])
```

**Comment by jordanott** [comment]
That doesn't change anything for me, does that work for you?
I'm still seeing "Sphere created" three times, then it just hangs

**Comment by benjaminum** [comment]
Can you try to add 
```python
...
if __name__ == '__main__':
    multiprocessing.set_start_method('spawn') # or 'forkserver'
...
```

**Comment by benjaminum** [comment]
@jordanott Did changing the start method fix the problem for you?

**Comment by jordanott** [comment]
Yes, changing the start method fixes the waiting issue. 
However, I'm still not seeing the hoped for speed up from using multiprocessing. Any suggestions?

**Comment by benjaminum** [comment]
The raycasting itself is multithreaded. If you have many rays then probably there is not much benefit of processing meshes in parallel.
