### ISSUE TITLE
Is there a cpp gui demo?

### ISSUE THREAD

**Issue by qpc001** [isl-org/Open3D#4938]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Is there a cpp gui demo ?

**Comment by yuecideng** [comment]
You can find some cpp gui demo and `Open3DViewer` in `build/bin` if you build Open3D from source.
