### ISSUE TITLE
Can't install same version of Open3d 15.x on MacOS and Linux

### ISSUE THREAD

**Issue by tetterl** [isl-org/Open3D#4941]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I'm trying to install the same version of Open3d 15.x on macOS and linux (needed/enforced for consistency) via PyPi. It seems that the linux version was not released for 0.15.1 and the macOS version was not released for 0.15.2. Furthermore, the tag for 0.15.2 is missing. Would it be possible to add the tag and release the missing versions for 0.15.2?

**Comment by tetterl** [comment]
Many thanks, I’ll consider that. I’m not only worried about API changes but any changes in behavior that could get unnoticed when developing on one platform and running on another. Furthermore, if 0.15.3 has to be released I won’t have full reproducibility since I can’t be sure which version was/is picked (e.g was the env reused or rebuilt).
Nevertheless, I’ll consider it in light of the many bugfixes. Otherwise, I’ll have to wait for the next minor release.

**Comment by ssheorey** [comment]
Another option: `pip` does allow you to fix different versions based on the OS. See this example [requirements.txt](https://github.com/isl-org/Open3D-ML/blob/master/requirements-torch.txt) file. There are no algorithm behavior or API differences between 0.15.1 and 0.15.2, only a build system bug fix.

**Comment by tetterl** [comment]
I considered that but was not fully sure if there would be any differences. Thanks for clarifying this. I’ll close the issue.

**Comment by johnthagen** [comment]
@ssheorey This is still an issue for users who pin their dependencies with Poetry or `pip-tools`. There is no way to pin to a single version for both local development on macOS x86 and production usage on Linux because of the mismatch in wheels that are published. Pinning dependencies is very important to ensure that what is testing locally runs the same in production.

For now, the only solution I see if to pin to 0.14.1 until a new release is released that includes wheels for all platforms.

**Comment by johnthagen** [comment]
Duplicate of #4796
