### ISSUE TITLE
'Show axes', alter origin coordinates

### ISSUE THREAD

**Issue by RichardSnijder** [isl-org/Open3D#4944]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hello,

I am using pointcloud files which have real world coordinates (Easting and Northing). On showing the axis, it places the axis on the origin (`X=0, Y=0, Z=0`). Is there any way to alter the axis' coordinates in order to place the axis anywhere near the real world coordinates?

I use the following code for determining the center of the point cloud file:

```ruby
max_values = np.amax(cloud.points, axis=0)
min_values = np.amin(cloud.points, axis=0)
center = [(max_values[0]+min_values[0])/2,(max_values[1]+min_values[1])/2,(max_values[2]+min_values[2])/2]
````

Thanks in advance.

Richard

**Comment by yuecideng** [comment]
Did you visualize your data using Open3D GUI app or just written in script? If in script, you can change your axis by applying transformation to it, since `axis` is actually a mesh object:
```python
pose = np.identity(4)
pose[:3, :3] = rotation # rotation matrix is your pre-defined orientation
pose[:3, 3] = center
axis.transform(pose)
```

**Comment by yuecideng** [comment]
I think you can not modify the axis position in `vis_gui.py` example unless you modify the cpp source code, since the behavior of axes drawing is hard coded.

**Comment by RichardSnijder** [comment]
Thank you for your reply.

I have figured out a way: 

```ruby
axes = o3d.geometry.TriangleMesh.create_coordinate_frame()
axes = axes.translate(self.cloud.get_center())
axes.scale(20, center=axes.get_center())
self._scene.scene.add_geometry("__axes__", axes, self.settings.material)
self.settings.show_axes = show
self._apply_settings()
```
Where `cloud` equals the point cloud file I am using. This does the job perfectly.

I used the tutorial found [here](http://www.open3d.org/docs/release/tutorial/geometry/transformation.html?highlight=transformation).

Thank you for your solutions, it made a lot more sense on what to do.

Kind regards,
Richard
