### ISSUE TITLE
Cannot compile on Ubuntu 20.04: libassimp error

### ISSUE THREAD

**Issue by bennaa** [isl-org/Open3D#4945]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

#### I first cloned Open3D by:
```
git clone https://github.com/isl-org/Open3D.git
cd Open3D
util/install_deps_ubuntu.sh

```

#### Then, I build Open3D (on Ubuntu 20.04, with CUDA 11.4) with:
```
mkdir build
cd build
cmake -DBUILD_SHARED_LIBS=OFF -DBUILD_CUDA_MODULE=ON -DUSE_BLAS=ON -DBUILD_WEBRTC=OFF ..
make -j$(nproc)
```

### Error message

```shell
make[2]: *** No rule to make target 'assimp/lib/x86_64-linux-gnu/libassimp.a', needed by 'lib/Release/libOpen3D.so'.  Stop.
```

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04 
- Python version: Python 3.8.13 
- Open3D version: output from python: `print(open3d.__version__)`
- System architecture: x86
- Is this a remote workstation?: yes or no
- How did you install Open3D?: build from source
- Compiler version (if built from source): gcc 9.4
```

### Additional information

I installed it once and it was working. I had to rebuild it and I get this error. I also tried a fresh clone of the repository but the error is still there

**Comment by fmigneault** [comment]
I'm also facing a similar issue related to `libassimp` on Ubuntu 20.04. 
The library seems to be generated here: `build/assimp/src/ext_assimp-build/lib/libassimp.a`, though in my case I specified `-DBUILD_SHARED_LIBS=ON`. 

An appropriate fix or temporary workaround would be appreciated.

**Comment by bennaa** [comment]
I tried your solution but it doesn't work for me. I also tried `-DUSE_SYSTEM_ASSIMP=ON` but it returns an include error 

```
/home/andrea/Builds/Open3D/cpp/open3d/io/file_format/FileASSIMP.cpp:31:10: fatal error: assimp/GltfMaterial.h: No such file or directory
   31 | #include "assimp/GltfMaterial.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [cpp/open3d/io/CMakeFiles/io.dir/build.make:258: cpp/open3d/io/CMakeFiles/io.dir/file_format/FileASSIMP.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2439: cpp/open3d/io/CMakeFiles/io.dir/all] Error 2

```

**Comment by yuecideng** [comment]
Hi, did you run `util/install_deps_ubuntu.sh` before you `cmake ..` and `make ..` ?

**Comment by bennaa** [comment]
Yeah, all the dependencies are installed and updated

**Comment by fmigneault** [comment]
I tried `util/install_deps_ubuntu.sh` as well and all dependencies are installed.
Still fails with the following:
```
make[3]: Entering directory '/home/francis/dev/antea/exploration/open3d/build'
make[3]: *** No rule to make target 'assimp/lib/libassimp.a', needed by 'bin/ConvertPointCloud'.  Stop.
make[3]: Leaving directory '/home/francis/dev/antea/exploration/open3d/build'
make[2]: *** [CMakeFiles/Makefile2:3007: cpp/tools/CMakeFiles/ConvertPointCloud.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
make[3]: Entering directory '/home/francis/dev/antea/exploration/open3d/build'
make[3]: Entering directory '/home/francis/dev/antea/exploration/open3d/build'
make[3]: *** No rule to make target 'assimp/lib/libassimp.a', needed by 'bin/ManuallyCropGeometry'.  Stop.
make[3]: *** No rule to make target 'assimp/lib/libassimp.a', needed by 'bin/GLInfo'.  Stop.
make[3]: Leaving directory '/home/francis/dev/antea/exploration/open3d/build'
make[3]: Leaving directory '/home/francis/dev/antea/exploration/open3d/build'
make[2]: *** [CMakeFiles/Makefile2:3064: cpp/tools/CMakeFiles/GLInfo.dir/all] Error 2
make[2]: *** [CMakeFiles/Makefile2:3121: cpp/tools/CMakeFiles/ManuallyCropGeometry.dir/all] Error 2
make[3]: Entering directory '/home/francis/dev/antea/exploration/open3d/build'
make[3]: *** No rule to make target 'assimp/lib/libassimp.a', needed by 'bin/MergeMesh'.  Stop.
make[3]: Leaving directory '/home/francis/dev/antea/exploration/open3d/build'
make[2]: *** [CMakeFiles/Makefile2:3178: cpp/tools/CMakeFiles/MergeMesh.dir/all] Error 2
make[2]: Leaving directory '/home/francis/dev/antea/exploration/open3d/build'
make[1]: *** [Makefile:156: all] Error 2
```

**Comment by bchretien** [comment]
Just got the same error on Debian 10 with the 0.15.1 release, with all the dependencies installed from `install_deps_ubuntu.sh`.

**Comment by bchretien** [comment]
The problem seems to be that the libraries of 3rd party dependencies are installed into `<INSTALL_DIR>/lib` and not `<INSTALL_DIR>/${Open3D_INSTALL_LIB_DIR}` (i.e. `<INSTALL_DIR>/lib/x86_64-linux-gnu` for Debian-based systems on x86-64 architectures). This seems surprising since assimp for example does use [the proper LIBDIR](https://github.com/assimp/assimp/blob/ba6c67c328575c741ddbb066827cc1c46ca7da36/CMakeLists.txt#L421).

**Comment by bchretien** [comment]
I've got a workaround, I'll submit a PR soon.

**Comment by bchretien** [comment]
For those who experienced the error, could you test #4955?

**Comment by fmigneault** [comment]
@bchretien 
https://github.com/isl-org/Open3D/pull/4955 seem to work for resolving the lib path.
I'm still facing other undefined reference issues with assimp though, not sure if it is related.

```
/usr/bin/ld: ../../assimp/lib/libassimp.a(PostStepRegistry.cpp.o): in function `Assimp::GetPostProcessingStepInstanceList(std::vector<Assimp::BaseProcess*, std::allocator<Assimp::BaseProcess*> >&)':
PostStepRegistry.cpp:(.text+0x527): undefined reference to `Assimp::JoinVerticesProcess::JoinVerticesProcess()'
/usr/bin/ld: ../../assimp/lib/libassimp.a(ImporterRegistry.cpp.o): in function `Assimp::GetImporterInstanceList(std::vector<Assimp::BaseImporter*, std::allocator<Assimp::BaseImporter*> >&)':
ImporterRegistry.cpp:(.text+0x309): undefined reference to `Assimp::MD5Importer::MD5Importer()'
/usr/bin/ld: ImporterRegistry.cpp:(.text+0x452): undefined reference to `Assimp::OFFImporter::OFFImporter()'
/usr/bin/ld: ../../assimp/lib/libassimp.a(FBXImporter.cpp.o): in function `Assimp::FBXImporter::InternReadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, aiScene*, Assimp::IOSystem*)':
FBXImporter.cpp:(.text+0x5da): undefined reference to `Assimp::FBX::Document::Document(Assimp::FBX::Parser const&, Assimp::FBX::ImportSettings const&)'
/usr/bin/ld: FBXImporter.cpp:(.text+0x717): undefined reference to `Assimp::FBX::Document::~Document()'
/usr/bin/ld: ../../assimp/lib/libassimp.a(FBXImporter.cpp.o): in function `Assimp::FBXImporter::InternReadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, aiScene*, Assimp::IOSystem*) [clone .cold]':
FBXImporter.cpp:(.text.unlikely+0x6b): undefined reference to `Assimp::FBX::Document::~Document()'
/usr/bin/ld: ../../assimp/lib/libassimp.a(FBXConverter.cpp.o): in function `Assimp::FBX::FBXConverter::ConvertOrphanedEmbeddedTextures()':
FBXConverter.cpp:(.text+0x5c46): undefined reference to `Assimp::FBX::LazyObject::Get(bool)'
/usr/bin/ld: ../../assimp/lib/libassimp.a(FBXConverter.cpp.o): in function `Assimp::FBX::FBXConverter::ProcessMorphAnimDatas(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<long, morphKeyData*, std::less<long>, std::allocator<std::pair<long const, morphKeyData*> > >*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::map<long, morphKeyData*, std::less<long>, std::allocator<std::pair<long const, morphKeyData*> > >*> > >*, Assimp::FBX::BlendShapeChannel const*, Assimp::FBX::AnimationCurveNode const*)':
FBXConverter.cpp:(.text+0x5fe6): undefined reference to `Assimp::FBX::Document::GetConnectionsBySourceSequenced(unsigned long, char const*) const'
/usr/bin/ld: FBXConverter.cpp:(.text+0x6019): undefined reference to `Assimp::FBX::Connection::DestinationObject() const'
/usr/bin/ld: FBXConverter.cpp:(.text+0x6033): undefined reference to `typeinfo for Assimp::FBX::Object'

[...]
```

**Comment by bchretien** [comment]
@fmigneault: this is still referencing the `lib` directory, have you tried cleaning up your build directory and rebuilding from scratch?

In my case I still have:
```sh
make[2]: *** No rule to make target 'turbojpeg/lib/x86_64-linux-gnu/libturbojpeg.a', needed by 'bin/GLInfo'.  Stop.
```
I'll fix that tomorrow.

**Comment by bchretien** [comment]
@fmigneault: the `libturbojpeg` error should be fixed now, apparently the upstream code uses [an old copy of GNUInstallDirs.cmake](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/main/cmakescripts/GNUInstallDirs.cmake), which might explain why it behaved differently (the libraries were not installed in `turbojpeg/lib/x86_64-linux-gnu` as expected).

**Comment by yxlao** [comment]
This was not caught by CI since we were always using something like this:

```bash
cmake -DCMAKE_INSTALL_PREFIX=~/open3d_install ..
```

Somehow when `CMAKE_INSTALL_PREFIX` is used, this problem can be avoided.

**Comment by bchretien** [comment]
@yxlao: I'm using `CMAKE_INSTALL_PREFIX=/usr/local` (so explicitly using the default location).

**Comment by fmigneault** [comment]
@bchretien 
Using https://github.com/Outflier/Open3D/commit/f5c2c5a010bacaf595116649bd8a5e06d24840ad the full project compiles successfully. Thanks for the quick fixes.

**Comment by yxlao** [comment]
> @yxlao: I'm using `CMAKE_INSTALL_PREFIX=/usr/local` (so explicitly using the default location). This is not uncommon to use `/usr/local` when building in Docker containers for instance.

It is strange that where you set `CMAKE_INSTALL_PREFIX` can affect the build. When you change `/usr/local` to `/usr/local2` it works.

```bash
# This works
cmake -DCMAKE_INSTALL_PREFIX=~/open3d_install

# This works
cmake -DCMAKE_INSTALL_PREFIX=/usr/local2

# This does not work
cmake -DCMAKE_INSTALL_PREFIX=/usr/local
```

With #4955, all cases are working fine.

**Comment by Parv-Maheshwari** [comment]
Hello Everyone. I have used the latest master branch and while building Open3D from source I am facing this error - 'No rule to make target 'fmt/lib/x86_64-linux-gnu/libfmt.a' . Can you please help with this. I beleive this is another LIB DIR error similar to assimp and turbojpeg error.

**Comment by willat343** [comment]
I'm getting the same error as @Parv-Maheshwari. I suggest re-opening the issue.

**Comment by Parv-Maheshwari** [comment]
@willat343 I suggest you to recline the repo instead of pulling the latest version. Recloning worked for me.

**Comment by Parv-Maheshwari** [comment]
@willat343 I suggest you to recline the repo instead of pulling the latest version. Recloning worked for me.

**Comment by willat343** [comment]
Yes, I just got it working by completely wiping the `build` directory and running `make` again. Running `make clean` wasn't sufficient.

**Comment by kungkook** [comment]
> I'm using `CMAKE_INSTALL_PREFIX=/usr/local` (so explicitly using the default location). This is not uncommon to use `/usr/local` when building in Docker containers for instance.

I also had this problem when compiling open3d1.15.1 under ubuntu20.04 source code. At first, I compiled both versions 0.16.0 and 0.16.1, but my platform did not support them. How did you solve the problem?

**Comment by kungkook** [comment]
> I suggest you to recline the repo instead of pulling the latest version. Recloning worked for me.

how to completely wiping the build directory? i just : sudo rm rf /usr/local/bin/open3d
