### ISSUE TITLE
How to filter pointcloud when left mouse button was clicked , just like Open3D-Viewer?

### ISSUE THREAD

**Issue by qpc001** [isl-org/Open3D#4952]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Open3D-Viewer

left button pressed:

![image](https://user-images.githubusercontent.com/31476516/160878288-84af7778-df70-4c89-93e7-9f0d67ca316c.png)

left button released:

![image](https://user-images.githubusercontent.com/31476516/160878477-9fa25e30-174a-44d7-84cd-a19673245824.png)

**Comment by femust** [comment]
Hey @qpc001  what's the answer ? : )
