### ISSUE TITLE
How can I fix the MS Azure link error in the ...version of o3d c++ code?

### ISSUE THREAD

**Issue by youb1649** [isl-org/Open3D#4962]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I'm using the C++ code in the 0.15.2+4265ea2 version of O3D.
But It has link errors about MSAzurekinect library if even the the document says it supports Azure kinect sensor.
the error messages are like below:

1>AzureKinectViewer.obj : error LNK2001: unresolved external symbol "public: static bool __cdecl open3d::io::AzureKinectSensor::ListDevices(void)" (?ListDevices@AzureKinectSensor@io@open3d@@SA_NXZ)
1>AzureKinectViewer.obj : error LNK2001: unresolved external symbol "public: virtual class std::shared_ptr<class open3d::geometry::RGBDImage> __cdecl open3d::io::AzureKinectSensor::CaptureFrame(bool)const " (?CaptureFrame@AzureKinectSensor@io@open3d@@UEBA?AV?$shared_ptr@VRGBDImage@geometry@open3d@@@std@@_N@Z)
1>AzureKinectViewer.obj : error LNK2001: unresolved external symbol "public: virtual bool __cdecl open3d::io::AzureKinectSensor::Connect(unsigned __int64)" (?Connect@AzureKinectSensor@io@open3d@@UEAA_N_K@Z)
1>AzureKinectViewer.obj : error LNK2001: unresolved external symbol "public: virtual __cdecl open3d::io::AzureKinectSensor::~AzureKinectSensor(void)" (??1AzureKinectSensor@io@open3d@@UEAA@XZ)
1>AzureKinectViewer.obj : error LNK2001: unresolved external symbol "public: __cdecl open3d::io::AzureKinectSensor::AzureKinectSensor(class open3d::io::AzureKinectSensorConfig const &)" (??0AzureKinectSensor@io@open3d@@QEAA@AEBVAzureKinectSensorConfig@12@@Z)
1>AzureKinectViewer.obj : error LNK2001: unresolved external symbol "public: __cdecl open3d::io::AzureKinectSensorConfig::AzureKinectSensorConfig(void)" (??0AzureKinectSensorConfig@io@open3d@@QEAA@XZ)

In addition, I removed the comments in the header file of "open3d/Open3D.h" like below.
// clang-format off
#include "open3d/io/sensor/azure_kinect/AzureKinectRecorder.h"
#include "open3d/io/sensor/azure_kinect/AzureKinectSensorConfig.h"
#include "open3d/io/sensor/azure_kinect/AzureKinectSensor.h"
#include "open3d/io/sensor/azure_kinect/MKVMetadata.h"
#include "open3d/io/sensor/azure_kinect/MKVReader.h"
#include "open3d/io/sensor/azure_kinect/MKVWriter.h"
#include "open3d/io/sensor/RGBDRecorder.h"
#include "open3d/io/sensor/RGBDSensorConfig.h"
#include "open3d/io/sensor/RGBDSensor.h"

Is there any idea to fix this? thinks.

**Comment by theNded** [comment]
You need to enable this flag: https://github.com/isl-org/Open3D/blob/master/CMakeLists.txt#L112 when using cmake.
