### ISSUE TITLE
Build on intel N4200 without AVX

### ISSUE THREAD

**Issue by maxfreu** [isl-org/Open3D#4970]
Hi!

I have to use open3d on an intel N4200 processor, which apparently doesn't support AVX. Consequently I get an illegal instruction error `SIGILL` when I run the python import - and I think AVX is the cause.

I already tried various settings in `./3rdparty/embree/embree.cmake`, switching AVX to OFF. But then I get an error that at least one ISA has to be enabled. When I enable SSE2, I get following error during`make`: 
`make[2]: *** No rule to make target „embree/lib/libembree_avx.a“ needed by „bin/ConvertPointCloud“'`

Is there a way I can make it work without AVX?

**Comment by lostcontrol** [comment]
Same issue here. 0.15.1 crashes on Intel N4200 (running Ubuntu 20.04) because of SIGILL. This is a self-compiled Open3D build but I get the same result with the official 0.15.2 Python package. The issue can be reproduced with `python -c 'import open3d'`.

Here is the culprit instruction:

```
(gdb) display/i $pc
1: x/i $pc
=> 0x7ffff3b7b93e:      vmovdqa 0x2332a7a(%rip),%xmm0        # 0x7ffff5eae3c0
```

@maxfreu did you find a way to compile Open3D without AVX support?

**Comment by maxfreu** [comment]
No

**Comment by benjaminum** [comment]
Did you adapt the `ISA_LIBS` and `ISA_BUILD_BYPRODUCTS` variables?

**Comment by qpc001** [comment]
> 你好！
> 
> 我必须在英特尔 N4200 处理器上使用 open3d，它显然不支持 AVX。因此，当我运行 python 导入时出现非法指令错误`SIGILL`- 我认为 AVX 是原因。
> 
> 我已经尝试了各种设置`./3rdparty/embree/embree.cmake`，将 AVX 切换为 OFF。但随后我收到一个错误，即必须启用至少一个 ISA。当我启用 SSE2 时，出现以下错误`make`： `make[2]: *** No rule to make target „embree/lib/libembree_avx.a“ needed by „bin/ConvertPointCloud“'`
> 
> 有没有办法让它在没有 AVX 的情况下工作？

you also need to modify the 'ISA_LIBS' to 'set(ISA_LIBS embree_sse42)',

total changed config:

```bash
    set(ISA_ARGS -DEMBREE_ISA_AVX=OFF
                 -DEMBREE_ISA_AVX2=OFF
                 -DEMBREE_ISA_AVX512=OFF
                 -DEMBREE_ISA_SSE2=ON
                 -DEMBREE_ISA_SSE42=ON
    )
    # order matters. link libs with increasing ISA order.
    set(ISA_LIBS embree_sse42)
```

**Comment by maxfreu** [comment]
I played around with the ISA_ARGS, but didn't get it to work. Maybe because I have set *either* SSE2 *or* SSE42, not both. I'll try it out this or next week and let you know. Thanks in advance!

**Comment by maxfreu** [comment]
The suggested configuration works! Thank you! But beware: compiling on that CPU takes about 1 1/2 hours.
