### ISSUE TITLE
macOS - render_to_depth_image() in loop seems error

### ISSUE THREAD

**Issue by wsAndy** [isl-org/Open3D#4978]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

I test the example[ code](https://github.com/isl-org/Open3D/blob/master/examples/python/visualization/render_to_image.py) and add render_to_depth_image() function. Then the result seems bad and I think the depth buffer is not released (maybe).

There are two bug at least. As the following code shows that the 'dep0' is OK, but the 'dep1' and 'dep2' are both not right. It seems that 'dep1' and 'dep2' only draw the left-bottom half image.   Then if I comment the 'dep0', (  # dep0 = render.render_to_depth_image() ) and not save dep0, the dep1 and dep2 also not get right results.

The test code is really simple. This problem occurs in MacOS, not in windows.

### Steps to reproduce the bug

```python
import open3d as o3d
import open3d.visualization.rendering as rendering
import numpy as np
import cv2
def save_depth(dep, name):
    depImg = np.asarray(dep)
    depImg = depImg.astype(float)
    depImg = 255.0*(depImg-depImg.min())/(depImg.max()-depImg.min())
    depImg = depImg.astype(int)
    cv2.imwrite(name, depImg)


def main():
    render = rendering.OffscreenRenderer(640, 480)

    yellow = rendering.MaterialRecord()
    yellow.base_color = [1.0, 0.75, 0.0, 1.0]
    yellow.shader = "defaultLit"

    green = rendering.MaterialRecord()
    green.base_color = [0.0, 0.5, 0.0, 1.0]
    green.shader = "defaultLit"

    grey = rendering.MaterialRecord()
    grey.base_color = [0.7, 0.7, 0.7, 1.0]
    grey.shader = "defaultLit"

    white = rendering.MaterialRecord()
    white.base_color = [1.0, 1.0, 1.0, 1.0]
    white.shader = "defaultLit"

    cyl = o3d.geometry.TriangleMesh.create_cylinder(.05, 3)
    cyl.compute_vertex_normals()
    cyl.translate([-2, 0, 1.5])
    sphere = o3d.geometry.TriangleMesh.create_sphere(.2)
    sphere.compute_vertex_normals()
    sphere.translate([-2, 0, 3])

    box = o3d.geometry.TriangleMesh.create_box(2, 2, 1)
    box.compute_vertex_normals()
    box.translate([-1, -1, 0])
    solid = o3d.geometry.TriangleMesh.create_icosahedron(0.5)
    solid.compute_triangle_normals()
    solid.compute_vertex_normals()
    solid.translate([0, 0, 1.75])

    render.scene.add_geometry("cyl", cyl, green)
    render.scene.add_geometry("sphere", sphere, yellow)
    render.scene.add_geometry("box", box, grey)
    render.scene.add_geometry("solid", solid, white)
    render.setup_camera(60.0, [0, 0, 0], [0, 10, 0], [0, 0, 1])
    render.scene.scene.set_sun_light([0.707, 0.0, -.707], [1.0, 1.0, 1.0],
                                     75000)
    render.scene.scene.enable_sun_light(True)
    render.scene.show_axes(True)


    # -------------------- dep 0: OK
    dep0 = render.render_to_depth_image()
    save_depth(dep0, "./dep0.png")

    img = render.render_to_image()
    print("Saving image at test.png")
    o3d.io.write_image("test.png", img, 9)
    # -------------------- dep 1: Error
    dep1 = render.render_to_depth_image()
    save_depth(dep1, "./dep1.png")

    # -------------------- dep 2: Error
    dep2 = render.render_to_depth_image()
    save_depth(dep2, "./dep2.png")

    render.setup_camera(60.0, [0, 0, 0], [-10, 0, 0], [0, 0, 1])
    img = render.render_to_image()
    print("Saving image at test2.png")
    o3d.io.write_image("test2.png", img, 9)


if __name__ == "__main__":
    main()
```

### Error message

no any error message

### Open3D, Python and System information

```markdown
- Operating system: macOS 10.15
- Python version: Python 3.9.10
- Open3D version: 0.15.1
- How did you install Open3D?: pip
```

**Comment by nuchi** [comment]
I ran into this as well on macos 12.2 — did you ever manage to work around it? It happens for me even if I create a new `rendering.OffscreenRenderer` instance. I.e. calling `<anything>.render_to_depth_image` has the weird lower-left crop if I've ever called `<anything>.render_to_depth_image` or `<anything>.render_to_image`. Only the first call to `render_to_depth_image` in a running python process succeeds as expected.

**Comment by nuchi** [comment]
Adding the following code before the first call to `render_depth_image` allows the first _two_ calls to succeed.

Before:
```python
dep0 = render.render_to_depth_image()  # OK
dep1 = render.render_to_depth_image()  # FAIL
dep2 = render.render_to_depth_image()  # FAIL
```

After:
```diff
+ def noop_callback(_): pass
+ render.scene.scene.render_to_image(noop_callback)

  dep0 = render.render_to_depth_image()  # OK
! dep1 = render.render_to_depth_image()  # OK
  dep2 = render.render_to_depth_image()  # FAIL
```

I haven't found any way to get more than one additional call to succeed.
