### ISSUE TITLE
How to map image coordinates (x,y) to respective point cloud coordinates (x,y,z) ?

### ISSUE THREAD

**Issue by Krupal09** [isl-org/Open3D#5015]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Dear all,

Target :
I am creating point clouds from RGB and depth images using the Open3D library by referring [this](http://www.open3d.org/docs/latest/tutorial/Basic/rgbd_image.html). Each pixel (x,y) in the RGB image is labelled which I need to assign to the respective point (x,y,z) in the point cloud.

Challenge :
RGB and depth image sizes are fixed to 640x480. But, generated point clouds have different dimensions which vary from an image to image.
For example, 
_image1_ - shape of the point cloud's numpy array is _(306062, 3)_.
_image2_ - shape of the point cloud's numpy array is _(305663, 3)_.
The resulting shape in terms of height and width is lesser than that of the image _(640x480 = 307200)_.

**Now that I need to label each point in point cloud, I am not able to assign a label by referring to the RGB-D coordinates because of the size discrepancy. May I please get some help to tackle this ?**

**Comment by yuecideng** [comment]
You could use `create_from_rgbd_image` function with `project_valid_depth_only=False`, from which you can get exactly 640x480 = 307200 points. Then you can find the corresponding 3d points index by `index = y * 640 + x` (where y in [0, 479] and x in [0, 639]

**Comment by Krupal09** [comment]
Incredible ! Thank you very much for your light speed response and guidance. It worked.

I am grateful to you @yuecideng :)
