### ISSUE TITLE
Why are the pointclouds of create_from_rgbd_image and manually created differ ?

### ISSUE THREAD

**Issue by ilyak93** [isl-org/Open3D#5021]
Hi, I have a rgbd images which I create using the following parameters:

```
rgbd_image = o3d.geometry.RGBDImage.create_from_color_and_depth(
    color_raw, depth_raw, depth_scale=1000.0, depth_trunc=1000, convert_rgb_to_intensity=False)

intrinsic = o3d.camera.PinholeCameraIntrinsic(width=1280, height=720,
                                              fx=1013.03991699219,
                                              fy=1013.03991699219,
                                              cx=655.809936523438,
                                              cy=380.619934082031)

pcd = o3d.geometry.PointCloud.create_from_rgbd_image(
    rgbd_image, intrinsic)
# Flip it, otherwise the pointcloud will be upside down
pcd.transform([[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]])
#pcd.cluster_dbscan(eps=20, min_points=40, print_progress=True)
o3d.visualization.draw_geometries([pcd])
```
which looks like this:
![image](https://user-images.githubusercontent.com/50303550/164131428-b59b72b9-c224-4faa-b1d1-a65815aea242.png)

and manually in python:
```
new_points = []
new_colors = []
depthscale = 1000
depth_image = np.asarray(rgbd_image.depth, dtype=np.uint16) * 1000
color_image = np.asarray(rgbd_image.color)
for u in range(height):
    for v in range(width):
        if depth_image[u, v] == 0:
            continue
        Z = depth_image[u, v] / depthscale
        x = (u - 655.809936523438) * Z / 1013.03991699219
        y = (v - 380.619934082031) * Z / 1013.03991699219
        new_points.append([x,y,Z])
        r,g,b = color_image[u,v,:]
        new_colors.append([r,g,b])

new_pcd = o3d.geometry.PointCloud()
np_points = np.asarray(new_points)
new_pcd.points = o3d.utility.Vector3dVector(np_points)
np_colors = np.asarray(new_colors)
new_pcd.colors = o3d.utility.Vector3dVector(np_colors)


```

and looks like this (presented in matlab, because in open3d it isn't shown well, I don't know the reason):

The image is a reflection on the x axis but the same, and even my figure can be seen in the middle (dark shadow of the legs and above):

![image](https://user-images.githubusercontent.com/50303550/164131842-9f824128-88ba-473d-b875-194b4eadebc0.png)

here is the problematic open3d view of the pointcloud created manually:
`o3d.visualization.draw_geometries([new_pcd])`

![image](https://user-images.githubusercontent.com/50303550/164133150-7328a316-e970-4e64-85cd-2a42abee6b51.png)

Why there is such difference between the functionalities? 

Otherwise, how can I get the pixel locations of the pointcloud points. Am I doing something wrong ?

Thank you in advance.

**Comment by ilyak93** [comment]
If I look at the ply files, the xy numbers are different, the z's are with different sign (in the original created from the rgbd they are positive, in manually created they are negative).

**Comment by ilyak93** [comment]
If a look at the ply files of both point clouds, the numbers of the x,y differ one from another and the z's are opposite in sign, created from rgbd are positive and created manually are negative.

**Comment by ilyak93** [comment]
I saved the "problematic" manually created ply, and reopened it, I think its ok but rotated right some why.
![image](https://user-images.githubusercontent.com/50303550/164145786-d3e67476-f9fc-4907-82fe-1baba7f7fb88.png)

Maybe because of that the difference in numbers. How can I rotate it left 90 degrees ?

**Comment by theNded** [comment]
```
for u in range(height):
    for v in range(width):
```
```
        x = (u - 655.809936523438) * Z / 1013.03991699219
        y = (v - 380.619934082031) * Z / 1013.03991699219
```
This is not following the [OpenCV](https://i.stack.imgur.com/E0E6a.png) / Open3D convention. height should be corresponding the y-axis, and width is corresponding to the x-axis. Please swap u,v.

Also Open3D by default clips distance to 3.0. Please also change that accordingly if necessary.

**Comment by ilyak93** [comment]
@theNded, thanks a lot.
