### ISSUE TITLE
No source distribution available on pypi

### ISSUE THREAD

**Issue by mf-bruce** [isl-org/Open3D#5050]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Steps to reproduce the issue

I'm trying to install the open3d python package within a docker build using poetry. The image i'm basing this off is `public.ecr.aws/lambda/python:3.9`, and for some reason this platform is not satisfied by the wheels available in pypi. For many other packages this would result in a source build, for open3d this is not possible since there is no source distribution available on pypi.

I'm facing compatibility issues with sub dependencies, so am using open3d 0.14.1 in this case. However, there doesn't appear to be a source distribution for any version on pypi.

Would it be possible to add a source distribution for open3d releases to pypi?

### Error message

```shell
NA
```

### Open3D, Python and System information

```markdown
- Operating system: public.ecr.aws/lambda/python:3.9
- Python version: Python 3..9.9 / output from `import sys; print(sys.version)`
- Open3D version: 0.14.1
- System architecture: x86_64
- Is this a remote workstation?: yes
- How did you install Open3D?: poetry
- Compiler version (if built from source): NA
```

**Comment by mf-bruce** [comment]
As noted, i'm trying to install on an "Amazon Linux 2" docker container. In this case I found that renaming the wheel to add the `manylinux2010_x86_64.whl` suffix allows pip to install the package, as suggested here: https://github.com/isl-org/Open3D/issues/4470#issuecomment-997546660

Is the wheel simply misnamed?

In either case, a source distribution would be a great fall back.

**Comment by segments-tobias** [comment]
For anyone else having this issue, using `public.ecr.aws/lambda/python:3.8` worked for me

**Comment by ssheorey** [comment]
Hi @mf-bruce Open3D is a C++ package with thin Python wrappers and can take a long time to build from source.  It would not be useful to provide a source distribution. If needed, you can clone the repo, and build the python package from source.

The wheel is correctly named - it will not work on Linux released around 2010 :-) Your `pip` version is likely too old. Please upgrade it first.

**Comment by ssheorey** [comment]
Hi @mf-bruce which platform did you need the Python wheels for?

The Open3D build system is complex and there is a significant chance that the build will fail on an unsupported platform - this would not be a good experience for an average Python user.

**Comment by mf-bruce** [comment]
> The Open3D build system is complex and there is a significant chance that the build will fail on an unsupported platform - this would not be a good experience for an average Python user.

That experience is unchanged regardless of whether pip tries to build, or the user clones and tries to build themselves. However, enabling PIP to attempt to build means that we can continue to use pip to manage our dependencies otherwise. Sometimes it will "just work", those users are fortunate.

The platform I was initially looking for binaries for is `public.ecr.aws/lambda/python:3.9`

**Comment by houseofsuns** [comment]
@ssheorey I'm seconding the request for a source distribution via PyPI. My use case is packaging for [Gentoo Linux](https://www.gentoo.org/) which is a source based distribution. Large resource requirements and complex build systems are no deterrent in this environment, but missing source files are a hindrance. For manually maintained packages it's possible to hunt down the source code, but I'm working on an automated PyPI interface which programmatically makes PyPI packages available as Gentoo packages and hence suffers from the missing source distribution via PyPI.

**Comment by ssheorey** [comment]
Hi @houseofsuns we are happy to accept PRs supporting packaging for specific OSs. As an example, @roehling has submitted several PRs to support packaging for Debian.
