### ISSUE TITLE
OpenCV to open3d conversion

### ISSUE THREAD

**Issue by justin-larking-pk** [isl-org/Open3D#5051]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

How can you convert from an opencv depth image to a open3d compadible depth image? Similarly how can I convert my camera intrinsics array to be usable by open3d (its also a cv::Mat), this is in c++.

**Comment by yuecideng** [comment]
Try with the snippet code below:
```c++
open3d::geometry::Image img;
// Allocate data buffer  
img.Prepare(width, height, 1, 2);
// mat is your cv::Mat depth image
memcpy(img.data_.data(), mat.data, img.data_.size());

// mat is your cv::Mat intrinsic with shape of 3 x 3
open3d::camera::PinholeCameraIntrinsic intrinsic(width, height, mat.at<double>(0, 0), mat.at<double>(1, 1), mat.at<double>(0, 2), mat.at<double>(1, 2));
```

**Comment by justin-larking-pk** [comment]
Awesome that works, cheers.
