### ISSUE TITLE
How to do Registration between RGB-D captured point cloud and CAD-modeled point cloud

### ISSUE THREAD

**Issue by yiyangd** [isl-org/Open3D#5082]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I tried to use [ICP Registration](http://www.open3d.org/docs/release/tutorial/pipelines/icp_registration.html) to align two point cloud with very large different scale: ONE is captered by Intel D435i RGB-D camera, the Other is created by CAD model with actual physical size (e.g. 28 cm height for a bottle).

The issue of the ICP Registration Result was that I could only see the Point Cloud of CAD model, but the Point Cloud of RGBD captured was just a single blue point in the yellow point cloud.
<img width="659" alt="Screen Shot 2022-05-06 at 11 50 44 AM" src="https://user-images.githubusercontent.com/25696979/167216591-02ca3778-7a9a-4fb8-9228-566a1c10e93c.png">

After I scaled manually (increase the RGBD point cloud size by 500, and decrease the CAD point cloud size by 1000), the registration result is still not matched.
<img width="595" alt="Screen Shot 2022-05-06 at 11 59 31 AM" src="https://user-images.githubusercontent.com/25696979/167216907-b4a3aecd-df7b-439a-a291-0499c7e379f4.png">

My question is: is it possible to get point cloud information (the distance of the points) so that we could scale down the CAD model by dist_CAD/dist_RGBD rather than put the scaling number manually?

Thanks for helping!

**Comment by yuecideng** [comment]
1. If you CAD model has actual physical size, I think the scale is not the critical problem. Just make sure you have both CAD point cloud and captured point clouds in the save uint (eg. m or mm). The first time you saw a blue small point of captured bottle may be due to the different unit (CAD in cm and captured in m).
2.  ICP is mostly used for pose refine. If you get a good result of registration, you could consider use global registration (or manually select 3 corresponding points with least square) to guess the initial pose, then apply ICP to them.

**Comment by yiyangd** [comment]
> 1. If your CAD model has actual physical size, I think the scale is not the critical problem. Just make sure you have both CAD point cloud and captured point clouds in the save uint (eg. m or mm). The first time you saw a small blue point of captured bottle may be due to the different unit (CAD in cm and captured in m).
> 2. ICP is mostly used for pose refine. If you want to get a good result of registration, you could consider use global registration (or manually select 3 corresponding points with least square) to guess the initial pose, then apply ICP to them.

Thank you, Yueci @yuecideng ! The “blue point inside yellow CAD point cloud" is the result of ICP, it seems that I need to make those two same unit then do ICP. Is it possible to check the Unit of both point clouds?

**Comment by yuecideng** [comment]
To my knowledge, It is not easy to check the unit of point clouds. Normally the unit is kind of prior knowledge for the point clouds you want to process.
