### ISSUE TITLE
C++ project build fails with Image instantiation

### ISSUE THREAD

**Issue by bennaa** [isl-org/Open3D#5092]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

I am using the c++ version of the library and when I try to instantiate a `open3d::t::geometry::Image` the build of my project fails returning the following errors CUDA related.  
If I try to use the legacy image version `open3d::geometry::Image` the build succeed.

### Steps to reproduce the bug
Just declaring the image in the header file cause the error

```python
class Tsdf
    {
    private:
        ros::NodeHandle n;
        ros::NodeHandle np;

        open3d::t::geometry::VoxelBlockGrid vbg;
        open3d::t::geometry::Image img;

    public:
        Tsdf(ros::NodeHandle n, ros::NodeHandle np);
        ~Tsdf() = default;
    };
```

### Error message

/usr/bin/ld: cublasMempool.cpp:(.text+0x47f): undefined reference to `cudaStreamWaitEvent'
/usr/bin/ld: cublasMempool.cpp:(.text+0x54a): undefined reference to `cudaGetExportTable'
/usr/bin/ld: cublasMempool.cpp:(.text+0x5a6): undefined reference to `cudaGetExportTable'
/usr/bin/ld: cublasMempool.cpp:(.text+0x7f0): undefined reference to `cudaGetExportTable'
/usr/bin/ld: cublasMempool.cpp:(.text+0x838): undefined reference to `cudaGetExportTable'
/usr/bin/ld: /usr/local/cuda-11.6/lib64/libcublasLt_static.a(cublasMempool.cpp.o): in function `cublasFixedSizePool::freeAsync(void*, CUstream_st*)':
cublasMempool.cpp:(.text+0x945): undefined reference to `cudaEventRecord'
/usr/bin/ld: /usr/local/cuda-11.6/lib64/libcublasLt_static.a(cublasMempool.cpp.o): in function `cublasFixedSizePool::tearDown()':
cublasMempool.cpp:(.text+0x978): undefined reference to `cudaDeviceSynchronize'
/usr/bin/ld: cublasMempool.cpp:(.text+0x9b0): undefined reference to `cudaEventDestroy'
/usr/bin/ld: cublasMempool.cpp:(.text+0xa1b): undefined reference to `cudaFree'
/usr/bin/ld: /usr/local/cuda-11.6/lib64/libcublasLt_static.a(cublasMempoolNoEvents.cpp.o): in function `cublasDynamicSizePoolNoEvents::malloc_device_buffer(void**, unsigned long)':
cublasMempoolNoEvents.cpp:(.text+0x1f): undefined reference to `cudaThreadExchangeStreamCaptureMode'
/usr/bin/ld: cublasMempoolNoEvents.cpp:(.text+0x3f): undefined reference to `cudaMalloc'
/usr/bin/ld: cublasMempoolNoEvents.cpp:(.text+0x59): undefined reference to `cudaThreadExchangeStreamCaptureMode'
/usr/bin/ld: /usr/local/cuda-11.6/lib64/libcublasLt_static.a(cublasMempoolNoEvents.cpp.o): in function `cublasDynamicSizePoolNoEvents::init(cublasContext*, int, int, int)':
cublasMempoolNoEvents.cpp:(.text+0x315): undefined reference to `cudaFree'
/usr/bin/ld: /usr/local/cuda-11.6/lib64/libcublasLt_static.a(cublasMempoolNoEvents.cpp.o): in function `cublasDynamicSizePoolNoEvents::alloc(void**, int, CUstream_st*)':
cublasMempoolNoEvents.cpp:(.text+0x741): undefined reference to `cudaGetExportTable'
/usr/bin/ld: cublasMempoolNoEvents.cpp:(.text+0x799): undefined reference to `cudaGetExportTable'
/usr/bin/ld: /usr/local/cuda-11.6/lib64/libcublasLt_static.a(cublasMempoolNoEvents.cpp.o): in function `cublasDynamicSizePoolNoEvents::tearDown()':
cublasMempoolNoEvents.cpp:(.text+0x92a): undefined reference to `cudaDeviceSynchronize'
/usr/bin/ld: cublasMempoolNoEvents.cpp:(.text+0x964): undefined reference to `cudaFree'
/usr/bin/ld: cublasMempoolNoEvents.cpp:(.text+0x9d7): undefined reference to `cudaFree'
/usr/bin/ld: /usr/local/cuda-11.6/lib64/libnppc_static.a(npp.o): in function `nppGetStreamContext':
npp.cpp:(.text+0x83): undefined reference to `cudaGetDevice'
/usr/bin/ld: npp.cpp:(.text+0x97): undefined reference to `cudaGetDeviceProperties'
/usr/bin/ld: npp.cpp:(.text+0xa6): undefined reference to `cudaStreamGetFlags'
/usr/bin/ld: npp.cpp:(.text+0x10d): undefined reference to `cudaDeviceGetAttribute'
/usr/bin/ld: npp.cpp:(.text+0x12c): undefined reference to `cudaDeviceGetAttribute'
/usr/bin/ld: npp.cpp:(.text+0x218): undefined reference to `cudaGetDevice'
/usr/bin/ld: npp.cpp:(.text+0x22c): undefined reference to `cudaGetDeviceProperties'
/usr/bin/ld: npp.cpp:(.text+0x23f): undefined reference to `cudaStreamGetFlags'
/usr/bin/ld: npp.cpp:(.text+0x2ac): undefined reference to `cudaDeviceGetAttribute'
/usr/bin/ld: npp.cpp:(.text+0x2cb): undefined reference to `cudaDeviceGetAttribute'
/usr/bin/ld: /usr/local/cuda-11.6/lib64/libnppc_static.a(npp.o): in function `nppGetStreamNumSMs':
npp.cpp:(.text+0x35f): undefined reference to `cudaGetDevice'
/usr/bin/ld: npp.cpp:(.text+0x373): undefined reference to `cudaGetDeviceProperties'
/usr/bin/ld: npp.cpp:(.text+0x382): undefined reference to `cudaStreamGetFlags'
/usr/bin/ld: npp.cpp:(.text+0x3ef): undefined reference to `cudaDeviceGetAttribute'
/usr/bin/ld: npp.cpp:(.text+0x418): undefined reference to `cudaGetDevice'
/usr/bin/ld: npp.cpp:(.text+0x42c): undefined reference to `cudaGetDeviceProperties'
/usr/bin/ld: npp.cpp:(.text+0x43f): undefined reference to `cudaStreamGetFlags'
/usr/bin/ld: npp.cpp:(.text+0x4a4): undefined reference to `cudaDeviceGetAttribute'
/usr/bin/ld: npp.cpp:(.text+0x4c3): undefined reference to `cudaDeviceGetAttribute'
/usr/bin/ld: npp.cpp:(.text+0x513): undefined reference to `cudaDeviceGetAttribute'
/usr/bin/ld: /usr/local/cuda-11.6/lib64/libnppc_static.a(npp.o): in function `nppGetStreamMaxThreadsPerSM':
npp.cpp:(.text+0x5bf): undefined reference to `cudaGetDevice'
/usr/bin/ld: npp.cpp:(.text+0x5d3): undefined reference to `cudaGetDeviceProperties'
/usr/bin/ld: npp.cpp:(.text+0x5e2): undefined reference to `cudaStreamGetFlags'
/usr/bin/ld: npp.cpp:(.text+0x64f): undefined reference to `cudaDeviceGetAttribute'
/usr/bin/ld: npp.cpp:(.text+0x678): undefined reference to `cudaGetDevice'
/usr/bin/ld: npp.cpp:(.text+0x68c): undefined reference to `cudaGetDeviceProperties'
/usr/bin/ld: npp.cpp:(.text+0x69f): undefined reference to `cudaStreamGetFlags'
/usr/bin/ld: npp.cpp:(.text+0x704): undefined reference to `cudaDeviceGetAttribute'
/usr/bin/ld: npp.cpp:(.text+0x723): undefined reference to `cudaDeviceGetAttribute'
/usr/bin/ld: npp.cpp:(.text+0x773): undefined reference to `cudaDeviceGetAttribute'
/usr/bin/ld: /usr/local/cuda-11.6/lib64/libnppc_static.a(npp.o): in function `nppSetStream':
npp.cpp:(.text+0x815): undefined reference to `cudaGetDevice'
/usr/bin/ld: npp.cpp:(.text+0x829): undefined reference to `cudaGetDeviceProperties'
/usr/bin/ld: npp.cpp:(.text+0x838): undefined reference to `cudaStreamGetFlags'
/usr/bin/ld: npp.cpp:(.text+0x89f): undefined reference to `cudaDeviceGetAttribute'
cd /home/vicarios/Projects/tsdf/build/tsdf; catkin build --get-env tsdf | catkin env -si  /usr/bin/make --jobserver-auth=3,4; cd -

Exception in callback _UnixReadPipeTransport._read_ready()
handle: <Handle _UnixReadPipeTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.8/asyncio/unix_events.py", line 500, in _read_ready
    self._protocol.data_received(data)
  File "/usr/lib/python3/dist-packages/osrf_pycommon/process_utils/async_execute_process_asyncio/impl.py", line 109, in data_received
    protocol.on_stderr_received(data)
  File "/usr/lib/python3/dist-packages/catkin_tools/execution/io.py", line 270, in on_stderr_received
    self.log_file.write(data)
ValueError: write to closed file
.....................................
```

### Expected behavior

_No response_

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04
- Python version: Python 3.8 
- Open3D version: 0.15.2
- System architecture: x86
- Is this a remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): gcc 9.4
```

### Additional information

The error log is too long to be pasted in the section above. All the errors are from  /usr/local/cuda-11.6/lib64/

**Comment by ssheorey** [comment]
Hi @bennaa what's your linker command? Looks like you are missing some CUDA libraries while building. Please refer to the example cmake projects to link with Open3D.
http://www.open3d.org/docs/latest/cpp_project.html

**Comment by bennaa** [comment]
Hi @ssheorey, thanks for your reply. I was already following that link and that is not the problem. If I use 
`open3d::t::geometry::VoxelBlockGrid vbg;`
or 
`open3d::geometry::Image legacy_img;`
It build with no errors.

**Comment by bennaa** [comment]
This was missing in the CMakeLists.txt file (also in http://www.open3d.org/docs/latest/cpp_project.html)

find_package(CUDA 11.6 REQUIRED)
set(Open3D_DIR "/usr/local/open3d")
find_package(Open3D REQUIRED)

include_directories(
  ${Open3D_INCLUDE_DIRS}
  ${CUDA_INCLUDE_DIRS}
)
