### ISSUE TITLE
How to configure a 2D FOV for pinhole cameras

### ISSUE THREAD

**Issue by thachdo** [isl-org/Open3D#5094]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

The function [create_rays_pinhole](http://www.open3d.org/docs/release/python_api/open3d.t.geometry.RaycastingScene.html#open3d.t.geometry.RaycastingScene.create_rays_pinhole) can only take a `float` fov value. However, we may have two different values on x and y axes. How to configure that?

**Comment by yuecideng** [comment]
Maybe try to use another `create_rays_pinhole` API which takes camera intrinsic matrix as input. [This link](https://codeyarns.com/tech/2015-09-08-how-to-compute-intrinsic-camera-matrix-for-a-camera.html) might be useful for FOV to intrinsic matrix converison.
