### ISSUE TITLE
Text edit breaks scrolling in vertical layout.

### ISSUE THREAD

**Issue by SensorTom** [isl-org/Open3D#5095]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [x] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

When I add a text edit to a vertical layout which has scroling enabled, the text edit disappears as soon as you start to scroll down. Also the scrolling will continue indefinitely. This behavior does not happen with other GUI elements in a vertical layout with scrolling enabeld. Note: the same happens with a ScrollableVert object, but again also just with a Vert object.

### Steps to reproduce the bug

```python
import open3d as o3d

import open3d.visualization.gui as gui

gui.Application.instance.initialize()
window = gui.Application.instance.create_window("Bug Demo", 1000, 500)

layout = gui.Vert()

layout.add_child(gui.Button("Button 1"))
layout.add_child(gui.Button("Button 2"))
layout.add_child(gui.Button("Button 3"))
layout.add_child(gui.Button("Button 4"))
layout.add_child(gui.Button("Button 5"))
layout.add_child(gui.Button("Button 6"))

layout.add_child(gui.Label("Label 1"))
layout.add_child(gui.TextEdit())
layout.add_child(gui.Button("Button 7"))
layout.add_child(gui.Button("Button 8"))

window.add_child(layout)

gui.Application.instance.run()
while True:
    pass
```

### Expected behavior

If you run the above code, when you scroll dowon in the vert layout you will see that the text box disappears and the scrolling behavior seems broken. Comment out the text edit addition and the scrolling seems to work fine.

### Open3D, Python and System information

```markdown
- Operating system: Windows 10 64-bit
- Python version: Python 3.6
- Open3D version: 15.1
- System architecture: x86
- Is this a remote workstation?: no
- How did you install Open3D?: pip
- Compiler version (if built from source): none
```

**Comment by An-nay-marks** [comment]
Hi, I have a similar issue, that in a Vert Widget, only the TextEdit scrolls into the opposite direction. The scrolling itself works fine for me though

**Comment by SensorTom** [comment]
Interesting, could be that your scrolling is inverted by default on the device you are scrolling with? (Mouse, Trackpad)
Also, does your scrolling work, when adding text edits to the Vert Widget with scrolling enabled?

**Comment by SensorTom** [comment]
@yxlao, could you check why the scrolling breaks when adding text edits to layouts? For my project it would be really great having that fixed.

**Comment by An-nay-marks** [comment]
I am scrolling with a mouse with the standard settings (no inversion). The issue also appears for the Vert Widget, interestingly

**Comment by Vkhark** [comment]
I have the same issue. It only happens to TextEdit. All other Controls work fine. I need to be able to write Letters though. 

It seems that the TextEdit is moving with the Scrollbar. It works perfectly until there is a Scrollbar and then it dissapears behind the other controls and travels further down, the more you scroll. 

The scrolling breaks as well, since you cannot get to the bottom of the Scrollbar.

Is there an alternative to TextEdit or something i could do to fix it?

**Comment by Vkhark** [comment]
For now I will just add my TextEdits() to a seperate gui.Vert() that will never be expanded enough to need a scroll button. I added it directly to self.window. 

I use another gui.Vert(), where the scroll will work  for the other controls. It's a bit annoying, as I have to relayout and rethink the design of my application now, but at least it works. Now my TextEdits() do not dissapear.

**Comment by SensorTom** [comment]
That is a nice workaround! Is it possible to add the separate gui.Vert() containing the TextEdit to the general gui.vert() with the other buttons? So now if you scroll, the gui.Vert() containing should move correctly with the scrolling?

**Comment by cansik** [comment]
This seems to be a bug in the open3d framework. All the other UI controls subtract the `GetScrollY()` value, only the text edit does not. I have opened a pull request #5887.

[gui/TextEdit.cpp](https://github.com/isl-org/Open3D/blob/ad1c3ade70dc52e7972db85670ff07a9bb31d2e2/cpp/open3d/visualization/gui/TextEdit.cpp#L104-L105)
```cpp
Widget::DrawResult TextEdit::Draw(const DrawContext &context) {
    auto &frame = GetFrame();
    ImGui::SetCursorScreenPos(
            ImVec2(float(frame.x), float(frame.y) + ImGui::GetScrollY()));

    ImGui::PushStyleVar(ImGuiStyleVar_FrameRounding,
                        0.0);  // macOS doesn't round text editing
```

[gui/NumberEdit.cpp](https://github.com/isl-org/Open3D/blob/ad1c3ade70dc52e7972db85670ff07a9bb31d2e2/cpp/open3d/visualization/gui/NumberEdit.cpp#L138-L139)
```cpp
Widget::DrawResult NumberEdit::Draw(const DrawContext& context) {
    auto& frame = GetFrame();
    ImGui::SetCursorScreenPos(
            ImVec2(float(frame.x), float(frame.y) - ImGui::GetScrollY()));

    ImGui::PushStyleVar(ImGuiStyleVar_FrameRounding,
                        0.0);  // macOS doesn't round text edit borders
```

[gui/Label.cpp](https://github.com/isl-org/Open3D/blob/ad1c3ade70dc52e7972db85670ff07a9bb31d2e2/cpp/open3d/visualization/gui/Label.cpp#L136-L137)
```cpp
Widget::DrawResult Label::Draw(const DrawContext& context) {
    auto& frame = GetFrame();
    ImGui::SetCursorScreenPos(
            ImVec2(float(frame.x), float(frame.y) - ImGui::GetScrollY()));
    ImGui::PushItemWidth(float(frame.width));
```
