### ISSUE TITLE
Why "compute_signed_distance" return a wrong sdf value when quering a cube?

### ISSUE THREAD

**Issue by DerekGrant** [isl-org/Open3D#5105]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I initialed a cube of size 1 and then query the SDF value from [-1, -1, 0]. I think it is outside the cube, but its SDF value is negative. I am confused about it, anyone have some clues? Thanks!

```
cube   = o3d.geometry.TriangleMesh.create_box(width=1, height=1, depth=1)
cube_mesh = o3d.t.geometry.TriangleMesh.from_legacy(cube)
cube_scene = o3d.t.geometry.RaycastingScene()
_ = cube_scene.add_triangles(cube_mesh) 
```
```
cube_scene.compute_signed_distance(o3d.core.Tensor([[-1, -1, 0],[-1, -1, -1],[0.5,0.5,0.5]], dtype=o3d.core.Dtype.Float32))

[-1.41421 1.73205 -0.5]
Tensor[shape={3}, stride={1}, Float32, CPU:0, 0x7fa7c8630fc0]
```

**Comment by benjaminum** [comment]
This is probably a numerical problem. To determine the sign a ray with direction [1,1,1] is cast and we count the number of intersections to determine the sign. I think this ray just touches the cube and seems to count just one intersection.

**Comment by DerekGrant** [comment]
Thanks a lot! I think this can explain the situation. Once we scale the cube to 0.9, the sign also changes.
```
cube   = o3d.geometry.TriangleMesh.create_box(width=0.9, height=0.9, depth=0.9)
```
