### ISSUE TITLE
Argument type error with create_from_depth_image

### ISSUE THREAD

**Issue by xmenage** [isl-org/Open3D#5136]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

I am trying to use o3d.geometry.PointCloud.create_from_depth_image to create a point cloud from a o3d.geometry.Image which is itself created from a numpy uint16 array. In the code below I created a simple 480x640 array containing a single value (random)

I am getting a type error  "TypeError: create_from_depth_image(): incompatible function arguments" caused by the Image.

I just made a fresh install of https://storage.googleapis.com/open3d-releases-master/python-wheels/open3d-0.15.2+25da5cc-cp38-cp38-manylinux_2_27_x86_64.whl in its own virtual env.

### Steps to reproduce the bug

```python
import open3d as o3d
import numpy as np


if __name__ == '__main__':
    imgDepth = np.full((480,640), 7324, dtype=np.uint16)
    depth = o3d.geometry.Image(imgDepth)
    intrinsic = o3d.camera.PinholeCameraIntrinsic(640,480,535.4, 539.2, 320.1, 247.6)
    pcd = o3d.geometry.PointCloud.create_from_depth_image(depth,
                                                            intrinsic,
                                                            depth_scale=5000.0,
                                                            depth_max=10.0)
```

### Error message

Traceback (most recent call last):
  File "/home/xavier/PycharmProjects/Open3DLatestDevWheel/main.py", line 10, in <module>
    pcd = o3d.geometry.PointCloud.create_from_depth_image(depth,
TypeError: create_from_depth_image(): incompatible function arguments. The following argument types are supported:
    1. (depth: open3d::geometry::Image, intrinsic: open3d.cuda.pybind.camera.PinholeCameraIntrinsic, extrinsic: numpy.ndarray[numpy.float64[4, 4]] = array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]]), depth_scale: float = 1000.0, depth_trunc: float = 1000.0, stride: int = 1, project_valid_depth_only: bool = True) -> open3d.cuda.pybind.geometry.PointCloud

Invoked with: Image of size 640x480, with 1 channels.
Use numpy.asarray to access buffer data., PinholeCameraIntrinsic with width = 640 and height = 480.
Access intrinsics with intrinsic_matrix.; kwargs: depth_scale=5000.0, depth_max=10.0

### Expected behavior

I would expect pcd to be created so I can visualize it.

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04.4 LTS 
- Python version: Python 3.8.10 
- Open3D version: 0.15.2+25da5cc
- System architecture: x86
- Is this a remote workstation?: no
- How did you install Open3D?: pip 
- Compiler version (if built from source): gcc 7.5 / clang 7.0
```

**Comment by yuecideng** [comment]
I think you just need to change `depth_max` into `depth_trunc`.

**Comment by xmenage** [comment]
> I think you just need to change `depth_max` into `depth_trunc`.

Thank you very much, I did not see that difference with parameters between the Tensor and non Tensor version. Now it works.

**Comment by yuecideng** [comment]
Should we make args of the tensor version consistent with the legacy version? @yxlao
