### ISSUE TITLE
Pointcloud not aligned from refined trajectory

### ISSUE THREAD

**Issue by simin75simin** [isl-org/Open3D#5149]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I was trying to verify the registration process (up to refine_registration.py in reconstruction_system folder) by overlapping two pointclouds (say frame 300 and 400) after they're inversely translated. I used the [following  script](https://gist.github.com/simin75simin/b4c26de4cc54ae56431e1bc84960d6cc) for that. 

However, I got a large mismatch almost every time. A mismatch looks like the image below, even though I checked that the reconstruction is good. I tried using SLAC's trajectory as well but got similar results. Is it correct to check registration this way? If not, how can I quantify the registration results? Thanks for answering.

![2022-06-05 15-58-04 的屏幕截图](https://user-images.githubusercontent.com/50899460/172041315-1c296f21-7279-4679-b2bc-ca1b0c9ae5d6.png)
:

**Comment by yuecideng** [comment]
Hi, I think you should use the transformation matrix directly instead of using the matrix inverse.

**Comment by simin75simin** [comment]
> Hi, I think you should use the transformation matrix directly instead of using the matrix inverse.

yes thank you!
