### ISSUE TITLE
How to remove the depth image projection on the yz plane when converting the depth to point cloud

### ISSUE THREAD

**Issue by JWang-X** [isl-org/Open3D#5203]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I have a depth map in u16 format. The steps I'm taking to generate point cloud(in ply/pcd) is:
1. Load the image using` out_img = o3d.io.read_image()`
2. Generate an point cloud object using `pcd = o3d.geometry.PointCloud.create_from_depth_image(out_img, cam.intrinsic)`
3. Write to a point cloud output file using `o3d.io.write_point_cloud( file_path, pcd)`

The pcd file is generated without any issue but I noticed the depth image itself is projected on the YZ plane together with all 3D point cloud data points. Wondering if there's a way to configure and remove the depth image projection when converting the depth to point cloud. 

I'm new to this package. So any advice/suggestion would be very helpful. Thanks!

**Comment by yuecideng** [comment]
Hi, could you paste your visualized result and the code snippet here to help us debug the issue?

**Comment by JWang-X** [comment]
Thanks for your quick reply. Below is the raw depth image and code I use. The PNG image is in unsigned 16bit per pixel format
![sample_depth_16U](https://user-images.githubusercontent.com/2694072/173988845-405a5a70-9d7a-4c90-807d-53d497d2fdfd.png)
,
w = 1920
h = 1080
fx = 1453.625
fy = 1453.625
cx = 959.875
cy = 544.125
intrinsic = o3d.camera.PinholeCameraIntrinsic(w, h, fx,fy, cx, cy)
intrinsic.intrinsic_matrix = [[fx, 0, cx], [0, fy, cy], [0, 0, 1]]
cam = o3d.camera.PinholeCameraParameters()
cam.intrinsic = intrinsic
out_img = o3d.io.read_image( "input_depth_img_path.png")
pcd = o3d.geometry.PointCloud.create_from_depth_image(
    out_img, cam.intrinsic)
o3d.io.write_point_cloud( "output_path.pcd", pcd)

**Comment by yuecideng** [comment]
It is also wired for me... Actually I have tested it for my own depth image and it worked just fine. Could you share your depth image (file) for me @JWang-X ?

**Comment by JWang-X** [comment]
I'm not sure if you can access to dropbox/google drive, here's then link to the image file.  [https://drive.google.com/drive/folders/1m_2vbyzZHRTGouem7ZFFe6rhRMBBi5FF?usp=sharing](url)
I'm also sending 2 sample images to your email address associated to your account. I'll add the ticket number to the title.

**Comment by yuecideng** [comment]
Hi, somehow the `min` depth value of your image is 1136, which is the value of pixel in the `projected image`...
A workaround would be:
```python
depth_img = cv2.imread("path/to/image.png", cv2.IMREAD_UNCHANGED)
depth_img[depth_img == 1136] = 0
depth = o3d.geometry.Image(depth_img)
...
pcd = o3d.geometry.PointCloud.create_from_depth_image(
    depth, cam.intrinsic)
```
@JWang-X

**Comment by JWang-X** [comment]
Thank you and this is helpful. I checked this will also remove those points which is fine for now. One last thing question I would like to have your opinion is let's say once I have the .pcd file generated. Is there any way or built in function I can use to validate or just do a quick sanity check on if the pcd is generated successfully/correctly, without opening it up using viewer tools? Initially I was thinking about checking the number of valid points, but looks like all pixels that have depth value equal to zero will be removed from .pcd (based on the above workaround).  But any other suggestions would be appreciated!

**Comment by yuecideng** [comment]
Use `o3d.geometry.PointCloud.create_from_depth_image(depth, cam.intrinsic, project_valid_depth_only=False)` would be helpful if you want to keep all the pixels.

**Comment by JWang-X** [comment]
This works for me. Thanks again we we can close out the issue.
