### ISSUE TITLE
Allow 32 bit precision vertices in write_point_cloud and write_triangle_mesh 

### ISSUE THREAD

**Issue by hasnainv** [isl-org/Open3D#5209]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Proposed new feature or change

Open3d currently only allows saving float64 point clouds and meshes. 
64-bit precision inflates the file size and that much precision is not needed for a lot of use-cases.
Allow writing float32 precision point clouds and meshes.

**Comment by ssheorey** [comment]
32-bit float I/O support is available through the new Tensor API:

http://www.open3d.org/docs/latest/python_api/open3d.t.io.write_point_cloud.html

We are adding more functionality, including IO for triangle mesh.

**Comment by nithinpanand** [comment]
@ssheorey Do you have a approximate release date in mind for the next version of open 3d with IO for triangle mesh ?

**Comment by ssheorey** [comment]
This is implemented:

http://www.open3d.org/docs/latest/python_api/open3d.t.io.read_triangle_mesh.html
http://www.open3d.org/docs/latest/python_api/open3d.t.io.write_triangle_mesh.html
