### ISSUE TITLE
CMAKE_ISPC_COMPILER is required? What's for AMD Ryzen Threadripper 3960X 24-Core Processor?

### ISSUE THREAD

**Issue by jiapei100** [isl-org/Open3D#5214]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Is **CMAKE_ISPC_COMPILER** a must ??? What's for `AMD Ryzen Threadripper 3960X 24-Core Processor` ???

**Comment by ssheorey** [comment]
Building ISPC is optional - you can turn it off in the CMake options. Check the ISPC manual and AMD CPU docs for supported instruction sets, but x86-64 and AVX2 (avx2-i32x16) is a safe bet.
