### ISSUE TITLE
Linking error c++ 

### ISSUE THREAD

**Issue by Amayess** [isl-org/Open3D#5221]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

#### I first cloned Open3D by:
```
git clone https://github.com/isl-org/Open3D.git
cd Open3D
```

#### Then, I downloaded the c++ binaries from http://www.open3d.org/docs/release/getting_started.html and linked them to my project using the basical way.

But when i tried to compile the example : https://github.com/isl-org/Open3D/blob/master/examples/cpp/RealSenseRecorder.cpp 

I got the error below... Can anyone help me with this, please ? 

### Error message

```shell
Error	LNK2019	unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl fmt::v8::vformat(class fmt::v8::basic_string_view<char>,class fmt::v8::basic_format_args<class fmt::v8::basic_format_context<class fmt::v8::appender,char> >)" (?vformat@v8@fmt@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$basic_string_view@D@12@V?$basic_format_args@V?$basic_format_context@Vappender@v8@fmt@@D@v8@fmt@@@12@@Z) referenced in function "private: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl open3d::utility::Logger::FormatArgs(char const *,class fmt::v8::basic_format_args<class fmt::v8::basic_format_context<class fmt::v8::appender,char> >)" (?FormatArgs@Logger@utility@open3d@@CA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEBDV?$basic_format_args@V?$basic_format_context@Vappender@v8@fmt@@D@v8@fmt@@@v8@fmt@@@Z)	Open3D RealSense
```

### Open3D, Python and System information

```markdown
- Operating system:  Windows 10 64-bit
- Python version: I am using c++
- Open3D version: 
- System architecture: x86 
- Is this a remote workstation?: yes or no
- How did you install Open3D?:http://www.open3d.org/docs/release/getting_started.html
```

### Additional information

![logging](https://user-images.githubusercontent.com/105653860/174576560-89b2ca26-6eae-49da-9fe1-d1993668eca2.JPG)

**Comment by xiaohan2** [comment]
@Amayess How did you solve the problem? Thank you for your answer.
