### ISSUE TITLE
Why all the C++ examples aren't compiling well ? 

### ISSUE THREAD

**Issue by Amayess** [isl-org/Open3D#5234]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi, I am trying to compile some c++ examples that i found in the master but every time I select a program it struggles to compile, I don't understand and that even if I have installed the libraries correctly..

Who has already encountered the same problem?

**Comment by yuecideng** [comment]
How do you install open3d? Download the pre-build c++ binary or build from source?

**Comment by Amayess** [comment]
Downloaded the master from GitHub then built it with C-make with no problems as you can see in the picture below.

I did something wrong ? is there a better way to install it ? 

![project](https://user-images.githubusercontent.com/105653860/174966391-af5202dc-7d3d-4087-a432-6feac16fbef2.JPG)

**Comment by yuecideng** [comment]
When you build open3d, you can add cmake config `-DBUILD_EXAMPLES=ON` to build all the examples. Maybe you can have a try.

**Comment by Amayess** [comment]
I already did that, that's why I am confused actually. 
 
![cmake1](https://user-images.githubusercontent.com/105653860/174970439-4fd4b6e5-fd13-422a-bc95-6e194bb4dedd.JPG)

**Comment by yuecideng** [comment]
> I am trying to compile some c++ examples that i found in the master but every time I select a program it struggles to compile

What do you mean by this? If you have already compile the examples, why you try to select an example and compile it again?

**Comment by Amayess** [comment]
It's a typo, sorry. I meant that every time I try to run one of the examples to see what it does with my realsense D455 an error occurs. 

Like this one for example : 
![realsense](https://user-images.githubusercontent.com/105653860/174973307-bad78584-c0f7-4aa2-91ed-31e96cb655e0.JPG)

**Comment by yuecideng** [comment]
What is the command you used to run the program? it seems that no error occur... I think you should follow the printed info usage to select the correct `args`

**Comment by yuecideng** [comment]
I'm not familiar with VS functionality. You can find them from other resources. Or you can run the pragram in terminal like `./bin/example/RealSenseRecorder --align --record rgbd_bag.bag`
