### ISSUE TITLE
Python : Scene reconstitution examples 

### ISSUE THREAD

**Issue by Amayess** [isl-org/Open3D#5244]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I am currently trying to run the scene reconstruction example "integrate_scene.py" but I can't get them to work and get a result with the Intel RealSense D455.

I'm not sure if anyone has done this yet, so I'd like to know how it works. I'm under the impression that it needs to be given an image as input in order to run, but what I want is for it to retrieve the image directly from the intel? 

Thank you.

**Comment by Amayess** [comment]
Hi @yuecideng, sorry but i still didn't get how I can use the "integrate_scene.py" example with the Intel RealSense since in the example they are using their own dataset ( lounge - Bedroom..etc) which are pre-recorded files.

From what i understood, the example " capture your own dataset " stream the RGB and Depth camera, save the both as png file then use the [--integrate] command to reconstruct it in order to have the same results as this ones ? 

![image](https://user-images.githubusercontent.com/105653860/175257078-dcef2302-51d5-43d0-9153-7c2e54cd9e09.png)

**Comment by yuecideng** [comment]
> From what i understood, the example " capture your own dataset " stream the RGB and Depth camera, save the both as png file then use the [--integrate] command to reconstruct it in order to have the same results as this ones ?

You are right. This is legacy offline reconstruction and it can not be used with realsense camera to do the real time reconstruction. 

>  i still didn't get how I can use the "integrate_scene.py" example with the Intel RealSense
If you want to use realsense for real time reconstruction, please build open3d with CUDA enable and use cpp example `OnlineSLAMRealSense`.

**Comment by Amayess** [comment]
Okay now it's way more clear for me, Thank you for the help.

> You are right. This is legacy offline reconstruction and it can not be used with realsense camera to do the real time reconstruction.

Then I can use the OfflineSlam.cpp since it's the same one, no ?

**Comment by yuecideng** [comment]
They can potentially be used to achieve the same objective you expected I guess. But there are some differences between them:
1. The python version of offline reconstruction system is implemented with open3d legacy API (geometry, pipelines). The `OfflineSlam` is implemented with the latest open3d tensor based API (geometry, pipelines), which will be improved continuously in the future.
2. The `OfflineSlam` use different method against to python reconstruction system. You can refer to this [tutorial ](http://www.open3d.org/docs/release/tutorial/t_reconstruction_system/index.html) for more detail. 

The c++ version of offline reconstruction system is in progress. If you prefer to use c++ more than python, you could try to use it when it is merged into master

**Comment by Amayess** [comment]
Understand, thank you !

**Comment by Amayess** [comment]
Hi @yuecideng, sorry for disturbing you again. I am trying to execute the **OnlineSLAMRealSense** example as you suggested but i get an error : Operation not supported, seems that it's a memory problem but i didn't found yet a solution to avoid it. 

Do you have any idea about this problem ? Thanks in advance. 
![cuda](https://user-images.githubusercontent.com/105653860/175314577-83b2877b-8fc4-4986-9b59-4833a7ee264f.JPG)

**Comment by yuecideng** [comment]
Let me try to find somebody to help ... 
Hi @yxlao, any idea about this?

**Comment by Amayess** [comment]
I found this solution and tried it  : https://issuemode.com/issues/isl-org/Open3D/49854865 but the problem still the same, I can run the program with no memory error but I capture nothing and reconstruct nothing
