### ISSUE TITLE
Python binding "illegal instructions error" with  CUDA compilation

### ISSUE THREAD

**Issue by pinjiang** [isl-org/Open3D#5260]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

#### I first cloned Open3D by:
```
git clone https://github.com/isl-org/Open3D.git
cd Open3D
```

#### Then, I build Open3D (on Ubuntu 21.04, with CUDA 11.3) with:
```
mkdir build
cd build
cmake -DBUILD_CUDA_MODULE=ON -DGLIBCXX_USE_CXX11_ABI=OFF -DBUILD_AZURE_KINECT=ON -DPYTHON_EXECUTABLE=$(which python3) ..
make -j$(nproc)
make install-pip-package
```
[CMake.log](https://github.com/isl-org/Open3D/files/9000507/CMake.log)
[make.log](https://github.com/isl-org/Open3D/files/9000509/make.log)

### Error message

```shell
(base) xlabs@xlabs-Standard-PC-Q35-ICH9-2009:~/install/Open3D/build$ python3
Python 3.9.5 (default, Nov 18 2021, 16:00:48)
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import open3d as o3d
illegal instructions (core dumped)
(base) xlabs@xlabs-Standard-PC-Q35-ICH9-2009:~/install/Open3D/build$
```

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 21.04 
- Python version: Python 3.9.5 
  3.9.5 (default, Nov 18 2021, 16:00:48)
  [GCC 10.3.0]

- Open3D version: output from python: 
illegal instructions (core dumped) when  import open3d as o3d

- System architecture: x86 
- Is this a remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): gcc (Ubuntu 9.3.0-23ubuntu2) 9.3.0
```

### Additional information

I build open3d from source for CUDA support, cpp binary works fine, but python bindings fails. 

I used gcc 9.0 to compile open3d for compatiblitiy with CUDA 11.3. The default python is compiled with GCC 10.3.0. Is it due to gcc version match between python and open3d?

**Comment by pinjiang** [comment]
Got it fixed due to inappropriate configuration of virtual machine instruction set

**Comment by fsr-cell** [comment]
> Got it fixed due to inappropriate configuration of virtual machine instruction set


Hello, how did you fix it?
