### ISSUE TITLE
Python 3.10.

### ISSUE THREAD

**Issue by Kanfit** [isl-org/Open3D#5275]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Proposed new feature or change

Please add support for Python 3.10

**Comment by wasdee** [comment]
This might be duplicated #5275.

**Comment by ssheorey** [comment]
Duplicate of #4535
