### ISSUE TITLE
Depth information is lost after extracting from .bag file

### ISSUE THREAD

**Issue by TWang1017** [isl-org/Open3D#5276]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi, i successfully reconstructed a ply file using Reconstruction System.

I collect data with RealSense D455 as a .bag file then extracting with the pipeline.

However, i found that the point cloud is standardized since the depth map extracted from .bag file is lost.

I checked the depth file in .png format that the depth is capped to 1 which is the reason why the reconstructed scene does not contain correct scale.

Any modificaiton i could do on code to correct it and return the right scale?

Any help is appreciated. thanks

**Comment by yuecideng** [comment]
Did you collect the `.bag` data using open3d python script? How did you check the depth image, is there any converisons before your save them?

**Comment by TWang1017** [comment]
> Did you collect the `.bag` data using open3d python script? How did you check the depth image, is there any converisons before your save them?

Hi, i checked the depth map in png extracted automtically with 'reconstruction system'.py. The depth map is in array printed by numpy array. It is capped at 1 instead of the real depth value. I did not do any conversion myself.

But i found the fused ply model has the right scale and depth value in metres, so i assume the saved png printed by numpy has some conversion itself that does not affect the reconstruction model. So I would not bother to check the depth map value. haha

thanks for you reply anyway, i will close the issue

Thanks
