### ISSUE TITLE
Egl Initialization failed error while running visualization.renderer.offscreenrenderer in headless mode

### ISSUE THREAD

**Issue by prp20** [isl-org/Open3D#5292]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

We are using Open3d to performing 3d scene analysis, wherein which we need to use the function `open3d.visualization.rendering.OffscreenRenderer` to load a model and covert the 3d scene to a image.
We are using the Offscreen renderer in headless mode and inside a docker container.
While we try to run the function using ssh, we get the below error
> [Open3D INFO] EGL headless mode enabled.
> FEngine (64 bits) created at 0x7fe2e292d010 (threading is enabled)
> eglInitialize failed
> Segmentation fault (core dumped)

While the same function, when we run using a VNC or when connected to a display, works fine and gives result.

We need this function to work without any display attached to the same.

### Steps to reproduce the bug

```python
#All the above steps need to be done using ssh not connected via a display.
#Using the below Dockerfile build an image:
   FROM ubuntu:20.04
   RUN apt-get update 
   RUN apt-get install --no-install-recommends -y \
    libgl1 \
    libgomp1 \
    libglib2.0-0 \
    libusb-1.0-0 \
    libsm6 \
    libxrender1 \
    libxext6 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*
   RUN python3 -m pip install --upgrade pip
   RUN RUN python3 -m pip install --no-cache-dir --upgrade open3d

docker build -t <image_name> .

#Enter into the image built by running the docker run command
docker run -it <image_name> /bin/bash

#inside the container, run the following commands:
#open the python interpreter
   python3
#add the below instructions
>>> import open3d as o3d
>>> render = o3d.visualization.rendering.OffscreenRenderer(480,480,headless=True)
```

### Error message

We get the below error
> [Open3D INFO] EGL headless mode enabled.
> FEngine (64 bits) created at 0x7f8c149b7010 (threading is enabled)
> Could not find library libEGL.so.1
> Segmentation fault (core dumped)

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04
- Python version: Python 3.8.10
- Open3D version: 0.15.2
- System architecture: x86 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz processor
- Is this a remote workstation?: yes
- How did you install Open3D?: pip
- Docker version: Docker version 20.10.17, build 100c701
- Connected to display: No
- Pip version: 22.2
- Graphics: Mesa Intel Xe Graphics(TGL GT2)
```

### Additional information

An observation then I tried was when the same function is tried when connected to a display such as a monitor or a vnc, the initialization of the object is successful without any errors, even though it's running inside the container.
> OpenGL version: 4.6

**Comment by ssheorey** [comment]
You need to provide access to the host GPU to the docker container. See the docker tutorial
http://www.open3d.org/docs/latest/docker.html

Here is an example docker run command from the tutorial:
```sh
# Run Open3D viewer docker image with the Intel GPU
docker run --device=/dev/dri:/dev/dri \
    -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY \
    -v "$PWD":/root open3d-viewer:latest
```
