### ISSUE TITLE
o3d.io.read_triangle_mesh won't load stl

### ISSUE THREAD

**Issue by claudius-kienle** [isl-org/Open3D#5295]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

I am currently trying to load the attached `table.stl` with open3d by following command:
```python
o3d.io.read_triangle_mesh("table.stl")
```
Sadly, open3d fails to load the file and the debug message is rather sparse:
```bash
[Open3D WARNING] Unable to load file table.stl with ASSIMP
```

However, the locally installed mesh editing tool as well as other python stl packages like [numpy-stl](https://github.com/WoLpH/numpy-stl/) or [PyMesh](https://github.com/PyMesh/PyMesh) load the `table.stl` without a problem.

Consequently, I think it might be a bug with Open3D or the mentioned ASSIMP package.

[table.stl](https://nextcloud.vincentcui.de/index.php/s/bZX6oHgFqyq58Az)

Further maybe useful information: I created the `table.stl` by base64 encoding the original file, sending it over http, decoding it again and saving it as binary in python.

### Steps to reproduce the bug

```python
import open3d as o3d

o3d.io.read_triangle_mesh("table.stl")
```

### Error message

[Open3D WARNING] Unable to load file table.stl with ASSIMP

### Expected behavior

Loading the stl without a problem as other packages successfully load the stl too.

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04.4 LTS
- Python version: Python 3.9.13
- Open3D version: 0.15.2
- System architecture: x86
- Is this a remote workstation?: no
- How did you install Open3D?: pip
```

**Comment by wangguan1995** [comment]
Did u fix it?

**Comment by claudius-kienle** [comment]
Yes. The issue was that the STL file was invalid.

**Comment by zrx-explorer** [comment]
hi! I have faced the same problem, could you plz tell me how to fix the STL file?

**Comment by claudius-kienle** [comment]
In my case, I think the issue was that i wrote the data into a stl file. However, I did forget to correctly close the file before reading it again.
This made the STL file incorrect, however many editors were able to load the STL file without a warning, which made finding the issue harder.
