### ISSUE TITLE
c++ FarthestPointDownSample OCCURS CAN'T FIND INTER OF EXE

### ISSUE THREAD

**Issue by guyuezuntinggithub** [isl-org/Open3D#5324]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

when I use FarthestPointDownSample  api occurs the following erro
![image](https://user-images.githubusercontent.com/63081832/179386254-fc8eaa21-d781-4a04-bd3c-8b573b8b1d70.png)

### Steps to reproduce the bug

```python
just call " FarthestPointDownSample" api 

o3dPointCloud_source->FarthestPointDownSample(2000);
```

### Open3D, Python and System information

```markdown
- Operating system: Windows 10 64-bit
- Python version: C++
- Open3D version: 0.15.02
- System architecture: arm64
- Is this a remote workstation?: no
- How did you install Open3D?: EXE
- Compiler version (if built from source): NO
```

### Additional information

delete the api, run ok

**Comment by yuecideng** [comment]
Hi, could you give us more information related to the code you used? Did you download the pre-built open3d binary or build from source?

**Comment by guyuezuntinggithub** [comment]
> Hi, could you give us more information related to the code you used? Did you download the pre-built open3d binary or build from source?

very appreciate for your reply! 
I download the pre-built open3d binary

**Comment by yuecideng** [comment]
This function is only available on the latest version of open3d, so you should download the latest c++ binary from [here](http://www.open3d.org/docs/latest/getting_started.html).

**Comment by guyuezuntinggithub** [comment]
> This function is only available on the latest version of open3d, so you should download the latest c++ binary from [here](http://www.open3d.org/docs/latest/getting_started.html).

problem solved ! thank you very much!
