### ISSUE TITLE
ImportError: DLL load failed while importing pybind

### ISSUE THREAD

**Issue by ketai-dhr** [isl-org/Open3D#5328]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Steps to reproduce the issue

when i import open3d in python3.8,it's give me error

### Error message

```shell
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    from projector_device import PointCloudVisualizer
  File "C:\Users\10578\OAKEnvironment\depthai-experiments\gen2-pointcloud\device-pointcloud\projector_device.py", line 2, in <module>
    import open3d as o3d
  File "C:\Users\10578\OAKEnvironment\python\lib\site-packages\open3d\__init__.py", line 90, in <module>
    from open3d.cpu.pybind import (camera, data, geometry, io, pipelines,
ImportError: DLL load failed while importing pybind: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 12, in <module>
    raise ImportError(
ImportError: [1;5;31mError occured when importing PCL projector: DLL load failed while importing pybind: 找不到指定的模块。
>>> import open3d
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\10578\OAKEnvironment\python\lib\site-packages\open3d\__init__.py", line 90, in <module>
    from open3d.cpu.pybind import (camera, data, geometry, io, pipelines,
ImportError: DLL load failed while importing pybind: 找不到指定的模块。
```

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04 / macOS 10.15 / Windows 10 64-bit
windowns 10
- Python version: Python 3.8 / output from `import sys; print(sys.version)`
3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
- Open3D version: output from python: `print(open3d.__version__)`
i can find version in `pip list`,but i can't find it in `print(open3d.__version__)`
open3d                   0.15.1
- System architecture: x86 / arm64 / apple-silicon / jetson / rpi
arm64
- Is this a remote workstation?: yes or no
no
- How did you install Open3D?: pip / conda / build from source
pip install open3d
- Compiler version (if built from source): gcc 7.5 / clang 7.0
```

### Additional information

![165ec0d03b17f217542771c8ae2c9a78cd1cafd31bc1b0fad4e5c23e4225ecf7QzpcVXNlcnNcMTA1NzhcQXBwRGF0YVxSb2FtaW5nXERpbmdUYWxrXDU4Mzg3MDA4OF92MlxJbWFnZUZpbGVzXDE2NTgxMTI3NDU3MDhfNDAwMjgwRTAtQkI2QS00ZGIyLUE3RjItQURBQTkwOTA0MTRCLnBuZw==](https://user-images.githubusercontent.com/60175845/179439430-4345e5b0-44da-44e0-b158-dcc472f73ad2.png)

**Comment by Feiyuyu0503** [comment]
I got the same issue as yours. Then I tried the software 'directx repair'. After reboot windows, it works!

**Comment by whizbuzzer** [comment]
> I got the same issue as yours. According to [#4652 (comment)](https://github.com/isl-org/Open3D/issues/4652#issuecomment-1089140999) ,I tried the software 'directx repair'. After reboot windows, it works!

Could you elaborate please?

**Comment by Feiyuyu0503** [comment]
> > I got the same issue as yours. According to [#4652 (comment)](https://github.com/isl-org/Open3D/issues/4652#issuecomment-1089140999) ,I tried the software 'directx repair'. After reboot windows, it works!
> 
> Could you elaborate please?

Try to download [https://zhangyue667.lanzouh.com/DirectXRepairEnhanced](url) (or any other your trusted url) and use it to repair.

**Comment by JonatanPlantey** [comment]
After several tries, the only thing that worked for me was install CUDA (and visual studio before, because demanded by CUDA). I had forgotten that wasn't installed since my reinstallation of windows operating system...

**Comment by ssheorey** [comment]
Thanks for resolving this. Closing.
