### ISSUE TITLE
There should be a way to carry out automatic 3D Triangulation ....

### ISSUE THREAD

**Issue by jiapei-nexera** [isl-org/Open3D#5349]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

There should be a way to carry out automatic 3D Triangulation ....
Namely: auto-generate mesh from vertices....

**Comment by ssheorey** [comment]
Hi @jiapei-nexera please see here for creating a mesh from a point cloud:
http://www.open3d.org/docs/release/tutorial/geometry/surface_reconstruction.html
