### ISSUE TITLE
Setup IntelRealSense Camera D455 By JSON File

### ISSUE THREAD

**Issue by NguyenDuyDuc1491995** [isl-org/Open3D#5351]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi,

I change parameters by IntelRealSenseViewer.exe of D455 Camera then export a json setup file.
Now, I want to import this file to config the camera by Python Code. There are many parameters.
But I see json file from IntelRealSenseViewer is different than Json of Open3d.t.io.
How should I do if I want to config D455 camera in Python Code via Open3D as same as setting up in IntelRealSenseViewer?
After setting, do you have a way to check if camera with 2 setting work the same?

Thanks

**Comment by ssheorey** [comment]
Hi @NguyenDuyDuc1491995 Open3D RS only supports a subset of the full RealSense functionality. For example, recording is supported only when depth and color frame rates are the same. Many imaging related settings are not supported, only presets. See [here](http://www.open3d.org/docs/latest/tutorial/sensor/realsense.html#realsense-camera-configuration) for what is supported. So there isn't a way to configure Open3D RS with the json setup file from IntelRealSenseViewer, or to ensure that the camera settings are identical with the two software.

**Comment by NguyenDuyDuc1491995** [comment]
ok. Thank you so much.
