### ISSUE TITLE
How to use tensor asserts in open3d 015

### ISSUE THREAD

**Issue by Andyjk1406** [isl-org/Open3D#5361]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

In C++, for tensors, I used to do:

transformation.AssertShape({ 4, 4 });

and 

target.GetPointPositions().AssertDtype(dtype);
target.GetPointPositions().AssertDevice(device);

These functions have disappeared in Open3d 015 - is there a new way to do the same?

**Comment by yuecideng** [comment]
Hi, you can use functions in `TensorCheck.h`. Please see [this](https://github.com/isl-org/Open3D/blob/v0.15.1/cpp/open3d/core/TensorCheck.h) for reference.

**Comment by Andyjk1406** [comment]
great, thanks
