### ISSUE TITLE
How to get single cluster of points after running cluster_dbscan to label clusters?

### ISSUE THREAD

**Issue by EdwardoSunny** [isl-org/Open3D#5372]
### Checklist

- [x] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I'm trying to isolate a cluster out of a point cloud. I read the documentation and it explains how you can use cluster_dbscan to label the clusters, count how many there are, and colormap the original point cloud. However, I'm having trouble understanding how to use the output and how I can isolate one of these clusters and have that as a separate point cloud.

**Comment by yuecideng** [comment]
Hi, you can use `numpy.where` to find the indices of each cluster and use open3d PointCloud `select_by_index` method to get the separated point cloud.

**Comment by EdwardoSunny** [comment]
how exactly would I use numpy.where? What is the format of the label array?

**Comment by EdwardoSunny** [comment]
I see, thank you so much for your help :D
