### ISSUE TITLE
Download data script is gone

### ISSUE THREAD

**Issue by panfeng-hover** [isl-org/Open3D#5373]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

http://www.open3d.org/docs/release/tutorial/sensor/realsense.html

Reading from RealSense bag files
Sample RealSense bag files
You con download sample RealSense bag datasets with this script:

```
python examples/python/reconstruction_system/scripts/download_dataset.py L515_test
```

The `download_dataset.py` longer exists.

I do find this script from a two-years-old history commit, https://github.com/isl-org/Open3D/tree/1860e75f820f60a4c84d441720020c1e7e4237a7/examples/python/reconstruction_system/scripts

**Comment by ssheorey** [comment]
Hi @panfeng-hover we have refactored this into the new easy to use and general dataset API. This is now available as L515Sample.

http://www.open3d.org/docs/latest/python_api/open3d.data.SampleL515Bag.html?highlight=l515#open3d-data-samplel515bag

Tutorial: http://www.open3d.org/docs/latest/tutorial/data/index.html
