### ISSUE TITLE
voxel_down_sample not working

### ISSUE THREAD

**Issue by denissabramovs** [isl-org/Open3D#5374]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

It seems that `pcd.voxel_down_sample(voxel_size)` is bugged and not down sampling points, returning the same amount of points.
Even though `pcd.uniform_down_sample(every_k_points=5)` is working.

Tried to downgrade open3d version up to 0.14.0 i think. Didn't help either.
```
Downsampling point clouds:pcd_0.ply with voxel size: 0.05
[Open3D DEBUG] Pointcloud down sampled from 85424 points to 85424 points.
```

Attaching point clouds to work with.
**Points cloud 1**:
https://gist.githubusercontent.com/denissabramovs/af5fcd3a956ccddfd627994aecbf465e/raw/510d6be5531e76053937052596a012c6ca12ed14/points_cloud
**Points cloud 2**:
https://gist.githubusercontent.com/denissabramovs/c5d9d1c8749d8d3e6c76120560f57cf4/raw/4f38617afd4f60b5c17ccc533da0c649ce5cf962/points_cloud2

Possibly it is because of negative values?

### Steps to reproduce the bug

```python
Use example in `registration_ransac.py` using above provided point clouds.
```

### Error message

No error

### Expected behavior

Points cloud is downsampled.

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 22.04
- Python version: Python 3.9.7
- Open3D version: output from python: 0.15.2
- System architecture: x86
- Is this a remote workstation?: no
- How did you install Open3D?: pip
- Compiler version (if built from source): -
```

**Comment by yuecideng** [comment]
Hi, please check your point cloud data are in unit of m. Otherwise you should use voxel size of 50.

**Comment by denissabramovs** [comment]
Indeed, increasing to 500 started downsampling. Thank you.
