### ISSUE TITLE
Torchlib tensor to Open3d tensor (and image)

### ISSUE THREAD

**Issue by Andyjk1406** [isl-org/Open3D#5381]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Similar to this issue (which is closed, but I think someone posted 2 days ago) 
 https://github.com/isl-org/Open3D/issues/2645 

I am inferring in torchlib C++ and getting a tensor (float32 image 512,512 1-channel)
I can move this to the cpu and wrap an OpenCV Mat around it fine, so I know the tensor is correct.

However, I am trying to avoid the CPU copy, and create an open3d tensor, then create an open3d image (all on the GPU).
It runs but the open3d image is incorrect. I have double-checked and the opencv image from the same torch tensor is fine.

Could I be using stride wrong when creating the blob? I assume the stride is 1.

Code below:

```
auto output = model.forward(input);    // Forward the torchscript model. The returned image is Float32 512,512 1-channel
	
// Get the torch tensor		
auto disparity_tensor = output.toList().extract(0).toTensor();  // Get the output image as a torch tensor
disparity_tensor = disparity_tensor.squeeze().detach(); // Ensure it has no dims=1 (eg batch)
disparity_tensor = disparity_tensor.to(torch::kFloat32); // Ensure it is float32 (I think it already is)
disparity_tensor = disparity_tensor.contiguous(); // Ensure it is contiguous

// OPEN3D CONVERSION HERE....
std::string device_string = "CUDA:0";
open3d::core::Dtype dtype = open3d::core::Dtype::Float32;
open3d::core::Device device(device_string);
open3d::core::Blob blob(device, disparity_tensor.data_ptr(), [](void*) {});
std::shared_ptr<open3d::core::Blob> blob_ptr = std::make_shared<open3d::core::Blob>(blob);
open3d::core::Tensor o3d_tensor({ 512,512 },{ 1,1 },disparity_tensor.data_ptr(),dtype,blob_ptr);
o3d_tensor = o3d_tensor.Contiguous(); // Needs to be contiguous for image creation
open3d::t::geometry::Image im(o3d_tensor);
auto im_colour = im.ColorizeDepth(255./320., 0, 320); // I expect the range of the float image to be between 0 and 320
open3d::t::io::WriteImage("test.png", im_colour); //Saves, but image is unrecognisable
			
// OPENCV (on CPU) - this works fine
torch::Tensor disparity_tensor_cpu = disparity_tensor.cpu();
cv::Mat resultImg(left_float.rows, left_float.cols, CV_32FC1, disparity_tensor_cpu.data<float>());
cv::Mat cv_im8;
resultImg.convertTo(cv_im8, CV_8U, 255. / 320.);
imshow("test", cv_im8);
cv::waitKey();
```

**Comment by ssheorey** [comment]
Hi @Andyjk1406 can you use this Tensor ctor for externally managed memory? Note that the stride is in elements, not bytes. No blob shared_ptr is needed. Also the stride should be {512, 1}, I think. See the stride formula in the docs here:

http://www.open3d.org/docs/latest/cpp_api/classopen3d_1_1core_1_1_tensor.html#a4af85f582b74887d326e25aa154d8e3e

`open3d::core::Tensor o3d_tensor(disparity_tensor.data_ptr(), dtype, {512, 512}, {512, 1}, device);`

**Comment by Andyjk1406** [comment]
Thanks.

The stride was the issue. I think the tensor creation call is from a more recent version of Open3d so I will upgrade, but I can confirm that the rest works.
There are some nasty MKL conflicts between LibTorch and Open3d_3rdParty by the way. But you can force multiple defs and I had to set a few other build options (Visual Studio on Windows).

Problem solved!
