### ISSUE TITLE
How to deal with **OpenMP** for **Open3D** ?

### ISSUE THREAD

**Issue by jiapei100** [isl-org/Open3D#5420]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

How to deal with **OpenMP** for **Open3D** ?

```console
[ 15%] Building CXX object cpp/open3d/core/CMakeFiles/core.dir/Indexer.cpp.o
......
....../Open3D/cpp/open3d/geometry/Image.cpp:163: warning: ignoring ‘#pragma omp parallel’ [-Wunknown-pragmas]
  163 | #pragma omp parallel for collapse(2) schedule(static) \
      | 
....../Open3D/cpp/open3d/geometry/Image.cpp:196: warning: ignoring ‘#pragma omp parallel’ [-Wunknown-pragmas]
  196 | #pragma omp parallel for collapse(2) schedule(static) \
      | 
....../Open3D/cpp/open3d/geometry/Image.cpp:281: warning: ignoring ‘#pragma omp parallel’ [-Wunknown-pragmas]
  281 | #pragma omp parallel for collapse(2) schedule(static) \
      | 
....../Open3D/cpp/open3d/geometry/Image.cpp:303: warning: ignoring ‘#pragma omp parallel’ [-Wunknown-pragmas]
  303 | #pragma omp parallel for schedule(static) \
      | 
....../Open3D/cpp/open3d/geometry/Image.cpp:323: warning: ignoring ‘#pragma omp parallel’ [-Wunknown-pragmas]
  323 | #pragma omp parallel for collapse(2) schedule(static) \
      | 
....../Open3D/cpp/open3d/geometry/Image.cpp:350: warning: ignoring ‘#pragma omp parallel’ [-Wunknown-pragmas]
  350 | #pragma omp parallel for collapse(2) schedule(static) \
      | 
....../Open3D/cpp/open3d/geometry/Image.cpp:390: warning: ignoring ‘#pragma omp parallel’ [-Wunknown-pragmas]
  390 | #pragma omp parallel for collapse(2) schedule(static) \
      | 
[ 15%] Building CXX object cpp/open3d/geometry/CMakeFiles/geometry.dir/ImageFactory.cpp.o
```

Is it **Open3D**? or is it **Intel OneAPI's mpi** ???

**Comment by nigels-com** [comment]
Can you provide some information about the platform and compiler toolchain?
Snippets of the initial cmake log would likely shed some light.

**Comment by ssheorey** [comment]
This is not related to OneAPI - it is OpenMP and looks like your compiler does not support it. Everything should still build and run, but will be slower since you will not be able to use multiple CPU cores.

**Comment by ssheorey** [comment]
Closing for now - please add more information about your environment if you still need help.
