### ISSUE TITLE
How to run reconstruction system with three rgbd cameras?

### ISSUE THREAD

**Issue by zmf2022** [isl-org/Open3D#5432]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I want to reconstruct model with three rgbd images from different cameras, how can i  implement it?

**Comment by GCChen97** [comment]
You may check these tutorials: http://www.open3d.org/docs/release/tutorial/pipelines/index.html. Tutorial RGBD integration and RGBD odometry should be useful,

**Comment by zmf2022** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，已收到您的邮件，将尽快给您回复！
