### ISSUE TITLE
strange RANSAC segmentation in version 0.15.0

### ISSUE THREAD

**Issue by MughtyWinky** [isl-org/Open3D#5449]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

As I code my analysis on a different pc than running it on large datasets, i noticed that the plane segmentation in version 0.15.1 leads to bad results, compared to version 0.13.0. o3d is used to segment scanned buildings into their walls / planes:

![data](https://user-images.githubusercontent.com/26003212/185407924-59a17031-0ffc-4df5-a0be-12734a1e2e86.png)

Version 0.13.0 splits the cloud in nice segments:

![planes_0_13_0](https://user-images.githubusercontent.com/26003212/185408095-21dcbb2a-b29e-4bef-92f2-a1b3dfff1a1f.png)

as version 0.15.1 tends to find only "horizontal" planes:

![planes_0_15_1](https://user-images.githubusercontent.com/26003212/185408196-3944cfca-efd6-46f1-9325-15f7a8e72245.png)

 Obviously the results of 0.13 show a better fit than the others.

### Steps to reproduce the bug

```python
import open3d as o3d
from random import random as rnd

#adjust to your environment
#cloud: see attached zip at bug report
cloud_path = "C:/temp/points.xyz"
image_path = "C:/temp/"

# which version?
version = o3d.__version__.replace(".", "_")
print(version)

# load files
pcd = o3d.io.read_point_cloud(cloud_path)

# remove points on plane via RANSAC
# and store found planes in array
planes = []
for i in range(0, 10):
    print(i)
    normal, ids = pcd.segment_plane(0.15, 200, 1000)
    plane = pcd.select_by_index(ids, invert=False)
    plane.paint_uniform_color([rnd(), rnd(), rnd()])
    planes.append(plane)
    pcd = pcd.select_by_index(ids, invert=True)

#draw a nice image
vis = o3d.visualization.Visualizer()
vis.create_window()
for p in planes:
    vis.add_geometry(p)
vc = vis.get_view_control()
vc.set_front([ 0.22808783268620844, -0.93071051038824193, 0.28592636540439298 ])
vc.set_lookat([ -8.3400463400999989, 4.7180157606499975, 5.8314446510000009 ])
vc.set_up([ -0.17084609212109747, 0.2508526884952943, 0.95282975472097453 ])
vc.set_zoom(0.7)
vis.poll_events()
vis.update_renderer()
vis.capture_screen_image("C:/temp/planes_"+version+".png")
vis.destroy_window()
```

### Expected behavior

RANSAC segmentation should create more consistent results in all o3d versions - except some minor differences casused by the random access.

### Open3D, Python and System information

```markdown
- Operating system: Windows 10 64-bit
- Python version, o3d 0.13.0: 3.8.8rc1 (tags/v3.8.8rc1:dfd7d68, Feb 17 2021, 11:01:21) [MSC v.1928 64 bit (AMD64)]
- Python version, o3d 0.15.1: 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)]
- System architecture: x86 
- Is this a remote workstation?: o3d 0.15.1: yes  |  0.13.0 no
- How did you install Open3D?: pip
```

### Additional information

Used pointcloud
[points.zip](https://github.com/isl-org/Open3D/files/9374292/points.zip)

**Comment by yuecideng** [comment]
Hi, please see this issue https://github.com/isl-org/Open3D/pull/4418. The implemetation in `0.15.1` is slightly different from `0.13.0`. You could just change your code `pcd.segment_plane(0.15, 200, 1000)` into `pcd.segment_plane(0.15, 3, 1000)` to getthe expected result.

**Comment by MughtyWinky** [comment]
Thx. That solved the issue.
