### ISSUE TITLE
Wrong transformation when using coordinate frame transform 

### ISSUE THREAD

**Issue by awied1404** [isl-org/Open3D#5473]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

I tried to reproduce a simple coordinate frame transformation I built in blender with the transform function that is given by [this tutorial](http://www.open3d.org/docs/latest/tutorial/Basic/transformation.html).
The goal was to transform a coordinate frame into another one starting from the origin (0,0,0).
![Screenshot from 2022-08-24 17-00-51](https://user-images.githubusercontent.com/67168322/186454598-0fca9082-f099-4f55-8a30-d14ddee6081b.png)
You can see the desired transformation in the picture above.
The translation and rotation I used in Blender to get the second coordinate frame can be seen here:
![Screenshot from 2022-08-24 17-01-00](https://user-images.githubusercontent.com/67168322/186454848-28400c9d-02f6-43a1-9e39-075fab04dbad.png)

Now I wanted to put the translation and the rotation in one simple transformation matrix and the resulting coordinate frame was not correct (or at least not the same as in Blender). 
When I tried to debug it, I noticed, that simply outsourcing the rotation around z-axis and doing this in an own step solved the problem for me but I don't think this is the mathematically correct way to do this.

### Steps to reproduce the bug

```python
import open3d as o3d
import numpy as np

def main():
    origin = o3d.geometry.TriangleMesh.create_coordinate_frame(size=1, origin=(0,0,0))
    cam = o3d.geometry.TriangleMesh.create_coordinate_frame(size=1, origin=(0,0,0))

    # transformation matrix
    T = np.eye(4)

    x,y,z = (1.2890441417694092, -0.1610880047082901, 1.955739974975586)

    # translation
    T[0,3] = x
    T[1,3] = y
    T[2,3] = z

    rx, ry, rz = (-2.507345024585724, -0.0859069973230362, -1.9421099424362183)

    rot_mat = o3d.geometry.TriangleMesh.get_rotation_matrix_from_xyz((rx, ry, rz))
    T[:3,:3] = rot_mat

    # wrong transformation
    cam.transform(T)

    # visualize
    o3d.visualization.draw_geometries([origin, cam])

    rot_mat = o3d.geometry.TriangleMesh.get_rotation_matrix_from_xyz((rx, ry,0))
    z_rot_mat = o3d.geometry.TriangleMesh.get_rotation_matrix_from_xyz((0, 0, rz))
    T[:3,:3] = rot_mat

    # correct transformation
    cam = o3d.geometry.TriangleMesh.create_coordinate_frame(size=1, origin=(0,0,0))

    # transformation like seen in blender
    cam.transform(T)
    cam.rotate(z_rot_mat)

    o3d.visualization.draw_geometries([origin, cam])


if __name__ == "__main__":
    main()
```

### Expected behavior

The same resulting coordinate frame as in Blender

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04
- Python version: Python 3.8
- Open3D version: output from python: 0.15.2
- System architecture: x86
- Is this a remote workstation?: no
- How did you install Open3D?: pip
- Compiler version (if built from source):
```

**Comment by chisarie** [comment]
Hi, I also think this function is not working properly. Did you find out otherwise? Why did you close the issue?

**Comment by awied1404** [comment]
Yeah I had the math wrong. Instead of using euler I used quaternion representation.
The angles in Blender are relative to the rotated coordinate system and not relative to the world coordinate system, that's why you can't use the angles there directly in the Open3D create_rotation_matrix_from_xyz function
