### ISSUE TITLE
How to read PCD points as double using the new tensor pointcloud

### ISSUE THREAD

**Issue by fdila** [isl-org/Open3D#5476]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi,
I've been trying to read a PCD file using the new open3d.t.io.read_point_cloud function, and by default the values are read as float.
Is there a way to force the reading of the points as double, so as not to lose precision when opening PCD files?

**Comment by yuecideng** [comment]
The data type is defined by the file itself. Could you check the first few lines of pcd file, example:
```
# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS x y z normal_x normal_y normal_z rgb curvature
SIZE 8 8 8 8 8 8 4 4
TYPE F F F F F F F F
COUNT 1 1 1 1 1 1 1 1
WIDTH 196133
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 196133
DATA ascii
```
If the `SIZE` is 4, which means that you could only read float values (4 bytes) data. If `SIZE` is 8, the values will be automatically read as double.

**Comment by fdila** [comment]
Makes sense, thank you!
