### ISSUE TITLE
How I can turn on Mipmap in Open3D?

### ISSUE THREAD

**Issue by Xiaoming-Zhao** [isl-org/Open3D#5484]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi, thanks a lot for this great project.

I am using `o3d.visualization.rendering.OffscreenRenderer.render_to_image` to render images. I am wondering whether is a function or argument I can use to make sure the Mipmap turns on? 

I searched the keyword `mipmap` and find it appears in some script, e.g., [cpp/open3d/visualization/rendering/MaterialModifier.h](https://github.com/isl-org/Open3D/blob/aebdb9a4396808edece4c24156e0231dc47a5edd/cpp/open3d/visualization/rendering/MaterialModifier.h). However, I am not sure where those mipmap options are chosen and whether they are exposed to Python bindings.

Any suggestions are welcomed. Thanks a lot in advance.

**Comment by errissa** [comment]
Mipmapping is always turned on except for float and integer format textures. We do plan to expose the texture mapping modes in `MaterialModifier.h` but it may be a month or two before we do.

**Comment by Xiaoming-Zhao** [comment]
Hi @errissa , thanks a lot for your reply. May I know what you mean by `float and integer format textures`? Does it mean the `np.array` is of type `np.uint8` or `np.float32`?

**Comment by errissa** [comment]
Textures with data types of `np.float32` or `np.uint16` will not be mipmapped. Textures with data type `np.uint8` will automatically have mipmaps generated for them.
