### ISSUE TITLE
Please, update to Python 3.10

### ISSUE THREAD

**Issue by milen-prg** [isl-org/Open3D#5504]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Proposed new feature or change

Please for wheel for Python 3.10

### References

Update request

**Comment by johnthagen** [comment]
Possible duplicate of 

- #4535

**Comment by johnthagen** [comment]
Open3D 0.16.0 has been released with 3.10 wheels: https://pypi.org/project/open3d/0.16.0/

**Comment by johnthagen** [comment]
Somewhat related:

- #5612

**Comment by milen-prg** [comment]
Thank you! Successfully installed on Python 3.10.
