### ISSUE TITLE
Is it possible to somehow add key callbacks to VisualizerWithEditing?

### ISSUE THREAD

**Issue by anticdimi** [isl-org/Open3D#5517]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Proposed new feature or change

For my use case, having a visualizer with a feature of retrieving picked points and registering keypress callbacks would be helpful. Is there a possibility for that already?

**Comment by yuecideng** [comment]
Hi, please see the doc [callback function](http://www.open3d.org/docs/release/tutorial/visualization/customized_visualization.html#callback-functions) for reference.

**Comment by anticdimi** [comment]
Hi, I already went through that, but as I see it, it is not possible to register a key callback when using VisualizerWithEditing. Or am I missing something?

**Comment by yuecideng** [comment]
Sorry for missing your issue title. 

It seems that currently the `VisualizerWithEditing` and `VisualizerWithKeyCallback` (which supports key callback) are implemented separately. So we don't have function like `register_key_callback` for `VisualizerWithEditing`. You may use `VisualizerWithKeyCallback` or implement this feature to `VisualizerWithEditing`.
