### ISSUE TITLE
Conda Ubuntu 22.04 libstdc++.so.6: version `GLIBCXX_3.4.30' not found

### ISSUE THREAD

**Issue by yxlao** [isl-org/Open3D#5531]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Steps to reproduce the issue

On Ubuntu 22.04 with Conda environment, the `libstdc++.so` that comes with Conda may be older than the system's `libstdc++`. When compiling Open3D with the system's `gcc`, the compilation will work, but the import of Open3D python package may not work due to missing symbols (`GLIBCXX_3.4.30`).

This is an upstream issue with the Conda environment. The proper fix is for Conda to include a newer `libstdc++` in its distribution.

The temporary fix is to use the system's `libstdc++` inside the Conda environment. We provide the temporary fix in the comments.

### Error message

```shell
ImportError while importing test module '/home/user/repo/Open3D/python/test/data/test_data.py'.                                                       
Hint: make sure your test modules/packages have valid Python names.                                                                                     
Traceback:                                                                                                                                              
../../../miniconda3/envs/open3d/lib/python3.9/importlib/__init__.py:127: in import_module                                                               
    return _bootstrap._gcd_import(name[level:], package, level)                                                                                         
../python/test/data/test_data.py:27: in <module>                                                                                                        
    import open3d as o3d                                                                                                                                
../../../miniconda3/envs/open3d/lib/python3.9/site-packages/open3d/__init__.py:90: in <module>                                                          
    from open3d.cpu.pybind import (camera, data, geometry, io, pipelines,                                                                               
E   ImportError: /home/user/miniconda3/envs/open3d/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/user/repo/Open3D
/build/lib/RelWithDebInfo/libOpen3D.so)
```
```


### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 22.04
- Python version: Python 3.8
- System architecture: x86_64
```

**Comment by yxlao** [comment]
1. First, check your system's `libstdc++.so`'s version:
    ```bash
    ➜   strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX                                  
    GLIBCXX_3.4
    GLIBCXX_3.4.1
    GLIBCXX_3.4.2
    GLIBCXX_3.4.3
    GLIBCXX_3.4.4
    GLIBCXX_3.4.5
    GLIBCXX_3.4.6
    GLIBCXX_3.4.7
    GLIBCXX_3.4.8
    GLIBCXX_3.4.9
    GLIBCXX_3.4.10
    GLIBCXX_3.4.11
    GLIBCXX_3.4.12
    GLIBCXX_3.4.13
    GLIBCXX_3.4.14
    GLIBCXX_3.4.15
    GLIBCXX_3.4.16
    GLIBCXX_3.4.17
    GLIBCXX_3.4.18
    GLIBCXX_3.4.19
    GLIBCXX_3.4.20
    GLIBCXX_3.4.21
    GLIBCXX_3.4.22
    GLIBCXX_3.4.23
    GLIBCXX_3.4.24
    GLIBCXX_3.4.25
    GLIBCXX_3.4.26
    GLIBCXX_3.4.27
    GLIBCXX_3.4.28
    GLIBCXX_3.4.29
    GLIBCXX_3.4.30
    GLIBCXX_DEBUG_MESSAGE_LENGTH
    ```
    We can see that `GLIBCXX_3.4.30` is indeed there.
2. Activate your Conda environment. 
3. Create symbolic link to the system's `libstdc++.
    ```bash
    cd $CONDA_PREFIX/lib
    mv libstdc++.so.6 libstdc++.so.6.old
    ln -s /usr/lib/x86_64-linux-gnu/libstdc++.so.6 libstdc++.so.6
    ```
    Now, the libs should look like this:
    ```bash
    ➜ ls -alh libstdc++*
    libstdc++.so -> libstdc++.so.6.0.29
    libstdc++.so.6 -> /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    libstdc++.so.6.0.29
    libstdc++.so.6.old -> libstdc++.so.6.0.29
    ```



Reference: https://stackoverflow.com/a/73708979/1255535.

**Comment by JonathanLehner** [comment]
After changing I got a problem with undefined symbol: cusolverDnSetStream

**Comment by VsWilson** [comment]
thanks, it works for me

**Comment by wb666greene** [comment]
Thanks, worked for me too.  Ubuntu 24.04, Anaconda 4.14.0

**Comment by cangcn** [comment]
> 1. First, check your system's `libstdc++.so` version:
>    ```shell
>    ➜   strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX                                  
>    GLIBCXX_3.4
>    GLIBCXX_3.4.1
>    GLIBCXX_3.4.2
>    GLIBCXX_3.4.3
>    GLIBCXX_3.4.4
>    GLIBCXX_3.4.5
>    GLIBCXX_3.4.6
>    GLIBCXX_3.4.7
>    GLIBCXX_3.4.8
>    GLIBCXX_3.4.9
>    GLIBCXX_3.4.10
>    GLIBCXX_3.4.11
>    GLIBCXX_3.4.12
>    GLIBCXX_3.4.13
>    GLIBCXX_3.4.14
>    GLIBCXX_3.4.15
>    GLIBCXX_3.4.16
>    GLIBCXX_3.4.17
>    GLIBCXX_3.4.18
>    GLIBCXX_3.4.19
>    GLIBCXX_3.4.20
>    GLIBCXX_3.4.21
>    GLIBCXX_3.4.22
>    GLIBCXX_3.4.23
>    GLIBCXX_3.4.24
>    GLIBCXX_3.4.25
>    GLIBCXX_3.4.26
>    GLIBCXX_3.4.27
>    GLIBCXX_3.4.28
>    GLIBCXX_3.4.29
>    GLIBCXX_3.4.30
>    GLIBCXX_DEBUG_MESSAGE_LENGTH
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    We can see that `GLIBCXX_3.4.30` is indeed there.
> 2. Activate your Conda environment.
> 3. Create symbolic link to the system's `libstdc++.so`.
>    ```shell
>    ➜ cd $CONDA_PREFIX/lib
>    ➜ mv libstdc++.so.6 libstdc++.so.6.old
>    ➜ ln -s /usr/lib/x86_64-linux-gnu/libstdc++.so.6 libstdc++.so.6
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Now, the libs should look like this:
>    ```shell
>    ➜ cd $CONDA_PREFIX/lib
>    ➜ ls -alh libstdc++*
>    libstdc++.so -> libstdc++.so.6.0.29
>    libstdc++.so.6 -> /usr/lib/x86_64-linux-gnu/libstdc++.so.6
>    libstdc++.so.6.0.29
>    libstdc++.so.6.old -> libstdc++.so.6.0.29
>    ```
> 
> Reference: https://stackoverflow.com/a/73708979/1255535.

Thanks, this works!

One thing worth noticed is that don't forget to install **_`six`_** for mujoco-based environments

**Comment by 55aalina** [comment]
Thanks, it works for me!
