### ISSUE TITLE
WARNING: Skipping open3d as it is not installed.

### ISSUE THREAD

**Issue by enginksz** [isl-org/Open3D#5539]
I don't want to pip install open3d on installation. because it doesn't run some code in example/python.

How can we edit this step?

Which version is the wheel package in version 15.2?

mkdir build
cd build
cmake..

make -j$(nproc)
make install

//Install pip package in the current python environment
make install-pip-package

[100%] Built-in target pip-package
WARNING: Skipping open3d as it is not installed.
**ERROR: open3d-0.15.2+998464c4-cp38-cp38-manylinux_2_31_x86_64.whl is not a supported wheel on this platform.**
[100%] Built target install-pip-package

I am installing open3d by following the steps below.

But I am getting error for wheel package.

wheel version; wheel 0.37.1

computer ;
Ubuntu 20.04.4 LTS
gcc version 8.4.0
clang version 10.0.0

**Comment by enginksz** [comment]
I fixed.

thanks

**Comment by maxim0815** [comment]
I've the same problem since today. How did you fixed it @enginksz ?

**Comment by enginksz** [comment]
Hi, yes I have solved the problem.

git clone https://github.com/isl-org/Open3D

git checkout v1.15.01

Then you can do other steps.

mkdir build
cd build 
cmake ..

...

**Comment by maxim0815** [comment]
I believe you meant v0.15.1
Seems to work again. Thanks a lot
