### ISSUE TITLE
Request to add the function that saves the windows into image

### ISSUE THREAD

**Issue by GANWANSHUI** [isl-org/Open3D#5584]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Proposed new feature or change

Hi, It would be great if you can provide the feature to save the whole window as an image. Thanks a lot!

**Comment by happikin** [comment]
I ran this example '/build/bin/Draw' and that window has a button to save current display as an image. So maybe if you look into that example code, you could get the point where it has been implemented.
![run-1](https://user-images.githubusercontent.com/64748455/196349977-6b26c243-131b-4329-8179-1dcbf71765a8.png)

and for the in-code api approach, I think just like read_image there is another function called write_image() maybe that can help.
Please let me know if what Im saying is correct from the perspective of finding a solution.
Thanks!

**Comment by ssheorey** [comment]
You are probably looking for this: 

http://www.open3d.org/docs/latest/python_api/open3d.visualization.O3DVisualizer.html#open3d.visualization.O3DVisualizer.export_current_image

**Comment by RuiqiW** [comment]
Could you please provide an example for using the export_current_image,  I can save the image from GUI, but I wasn't able to save it with code. I tried both
```
func_partial = functools.partial(o3d.visualization.O3DVisualizer.export_current_image, arg0="a.png")
o3d.visualization.draw(geoms, show_skybox = False, 
                                        field_of_view = 0., 
                                        lookat=[0.5, 0., 0.], 
                                        eye=[0.5, 0.2, 1.], 
                                        up=[-np.pi / 6, 0., -np.pi / 3],
                                        actions=[["save", func_partial]])
```
and 
`o3d.visualization.O3DVisualizer.export_current_image("a.png")`

But got 

```
TypeError: export_current_image(): incompatible function arguments. The following argument types are supported:
    1. (self: open3d.cuda.pybind.visualization.O3DVisualizer, arg0: str) -> None

Invoked with: <open3d.cuda.pybind.visualization.O3DVisualizer object at 0x7f86de2cf970>; kwargs: self=<class 'open3d.cuda.pybind.visualization.O3DVisualizer'>, arg0='a.png'
```

**Comment by ssheorey** [comment]
export_current_image() is a normal function of the class O3DVIsualizer. You'll have to instantiate O3DVIsualizer, draw into it and then use export_current_image(). Do now use a separate draw().
See this example:
https://github.com/isl-org/Open3D/blob/master/examples/python/visualization/non_blocking_visualization.py

You can add `vis.export_current_image("a.png")` at line 52, after `vis.add_geometry(target)`

**Comment by RuiqiW** [comment]
Thanks for the answer! But how can I set the material for the mesh if I use `vis.add_geometry(target)`? I can use `geoms = [{'name': 'box', 'geometry': plane_mesh, 'material': mat}]` when calling the draw() function, but I didn't find a way to add material with the functions in the example.

**Comment by ssheorey** [comment]
See this example:

https://github.com/isl-org/Open3D/blob/master/examples/python/visualization/textured_mesh.py

You can set the material of the geometry before giving it to O3DVisualizer / draw.

**Comment by GANWANSHUI** [comment]
Hi, @ssheorey @happikin, Thanks a lot for the information. I am wondering if it would be more convenient to set up the **save** function directly in the class.

> gui.Application.instance

For example, I have developed a customized window by `gui.Application.instance.create_window("Vis3D", 1920, 1080),` and I just want to save this window into an image. May I ask the best way to do this? Thanks a lot!

![1670443353303](https://user-images.githubusercontent.com/43164272/206283792-b3a91e34-f263-40aa-81fa-a092a92105c5.png)

**Comment by ssheorey** [comment]
`gui.Application` is a singleton instance for all windows, so this doesn't look like the right place. You can use this instead of `create_window()`:
```py
win = O3DVisualizer("Vis3D", 1920, 1080)
# ..work with win...
win.export_current_image("filename.png")
```
O3DVisualizer is a higher level class for a window, so its easier to use.
