### ISSUE TITLE
Destroy OffScreenRenderer (Filament engine) in python API

### ISSUE THREAD

**Issue by MartinPedersenpp** [isl-org/Open3D#5596]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I have a script where I need to run in an infinite loop.
Throughout each iteration I need to render some depth images using the OffScreenRenderer.
Even though I reassign the object holding the renderer, some traces of the Filament engine is still left behind, causing a memory leak, which in turn will cause the script to freeze.
It looks to me like in the cpp files, that there is code available to fully destroy the PyOffScreenRenderer, but this has not been implemented in the python API?
Any ideas to how I can perform some cleanup after each time I render my depth images?

**Comment by MartinPedersenpp** [comment]
I can see in the pybind files that the destructor is actually defined:

```
class PyOffscreenRenderer {
public:
    PyOffscreenRenderer(int width,
                        int height,
                        const std::string &resource_path) {
        gui::InitializeForPython(resource_path, true);
        width_ = width;
        height_ = height;
        // NOTE: OffscreenRenderer now always uses headless so that a window
        // system is never required
        EngineInstance::EnableHeadless();
        renderer_ = new FilamentRenderer(EngineInstance::GetInstance(), width,
                                         height,
                                         EngineInstance::GetResourceManager());
        scene_ = new Open3DScene(*renderer_);
    }


    ~PyOffscreenRenderer() {
        delete scene_;
        delete renderer_;
        // Destroy Filament Engine here so OffscreenRenderer can be reused
        EngineInstance::DestroyInstance();
    }

But no matter what I do, I can't seem to call the destructor from within python.
When I do print(dir(OffscreenRenderer)) if does not have a __del__ function.

```

**Comment by dancergraham** [comment]
I think I have the same problem, intermittently crashing the main thread when I call the same rendering function multiple times.  My workaround so far has been to always run in a subprocess using the `multiprocessing` module.
