### ISSUE TITLE
open3d 0.16.0: arm64 conda python unable to import due to '_quadmath_snprintf' not found

### ISSUE THREAD

**Issue by jbotsch-fy** [isl-org/Open3D#5607]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Steps to reproduce the issue

This is likely the same issue as in [https://github.com/isl-org/Open3D/issues/5482](https://github.com/isl-org/Open3D/issues/5482) but using a pre-built wheel

When installing open3d on a MacBook M1 arm using python 3.9 from the wheel at [open3d-0.16.0-cp39-cp39-macosx_12_0_arm64.whl](https://github.com/isl-org/Open3D/releases/download/v0.16.0/open3d-0.16.0-cp39-cp39-macosx_12_0_arm64.whl) the following error pops up if one uses `import open3D`:

### Error message

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Caskroom/miniforge/base/envs/test_env/lib/python3.9/site-packages/open3d/__init__.py", line 97, in <module>
    from open3d.cpu.pybind import (camera, data, geometry, io, pipelines,
ImportError: dlopen(/opt/homebrew/Caskroom/miniforge/base/envs/test_env/lib/python3.9/site-packages/open3d/cpu/pybind.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_quadmath_snprintf'`
```

### Open3D, Python and System information

```markdown
- Operating system: macOS 12.3 / 
- Python version: Python 3.9.13 / output from `import sys; print(sys.version)`
- Open3D version: output from python: `print(open3d.__version__)`
- System architecture: apple-silicon
- Is this a remote workstation?: no
- How did you install Open3D?: pip open3d-0.16.0-cp39-cp39-macosx_12_0_arm64.whl
```

**Comment by jbotsch-fy** [comment]
this is likely the same as [https://github.com/isl-org/Open3D/issues/5482](https://github.com/isl-org/Open3D/issues/5482)

**Comment by jbotsch-fy** [comment]
This is likely the same issue as in [https://github.com/isl-org/Open3D/issues/5482](https://github.com/isl-org/Open3D/issues/5482)

**Comment by jbotsch-fy** [comment]
The PR [https://github.com/isl-org/Open3D/pull/5613](https://github.com/isl-org/Open3D/pull/5613) seems to address this.

**Comment by jbotsch-fy** [comment]
Not sure who is the right person to address, but e.g. @yxlao or @ssheorey would it be possible to release new builds of open3D 0.16 for apple silicon after https://github.com/isl-org/Open3D/pull/5613 was merged.
The current wheels are broken without https://github.com/isl-org/Open3D/pull/5613.

**Comment by mcdenhoed** [comment]
I have also run into this issue on an M1 mac using `homebrew`'s python, with `open3d 0.16` installed via `poetry`.

**Comment by johnthagen** [comment]
I'd like to second @jbotsch-fy's request that new Mac ARM wheels be uploaded for 0.16.0 as they are currently unusable because of this issue.

Thank you ❤️ !

**Comment by ianZzzzzz** [comment]
I meet this issue on py39 and py38 ,by using "pip install open3d"and install whl file.

**Comment by connorf25** [comment]
While we wait for the new Mac ARM wheels to be uploaded, I managed to get it working by installing the previous release:
`pip install open3d==0.15.1`

**Comment by johnthagen** [comment]
> I managed to get it working by installing the previous release

One unfortunate trade off with using 0.15.1 is that there is no Python 3.10 support, if that's something that is important for a particular project.

**Comment by johnthagen** [comment]
It looks like 0.16.1 was released with only Mac ARM wheels to solve this:

- https://pypi.org/project/open3d/0.16.1/#files

This does still make it tricky to pin versions, however, as a different version is needed for every other platform.

**Comment by johnthagen** [comment]
@ssheorey Would you consider adding wheels for all other platforms to the 0.16.1 release on PyPI:

- https://pypi.org/project/open3d/0.16.1/#files

This would make it much easier for users of Open3D target multiple operating systems and architectures. Thanks.

**Comment by johnthagen** [comment]
Until either all wheels are added to 0.16.1, or the next release is published, here is a workaround snippet that can be used with [Poetry](https://python-poetry.org/) to lock and install the correct wheel based on the platform:

```toml
[tool.poetry.dependencies]
open3d = [
    { version = "0.16.0", markers = "sys_platform != 'darwin' or (sys_platform == 'darwin' and platform_machine == 'x86_64')" },
    { version = "0.16.1", markers = "sys_platform == 'darwin' and platform_machine == 'arm64'" },
]
```

**Comment by ssheorey** [comment]
v0.16.1 wheels are now available for both arm64 and x86_64 for macOS only. We do not plan to release v0.16.1 wheels for other platforms, since the bug does not affect them. Thanks @johnthagen for sharing the lockfile - the platform_machine check should be skipped, since v0.16.1 is a bug fix for x86_64 as well (for a different bug). If you use a requirements.txt file instead, you can use this to lock to v0.16:

```
open3d==0.16.0; sys_platform != 'darwin'
open3d==0.16.1; sys_platform == 'darwin'
```

**Comment by johnthagen** [comment]
I wanted to point out, for those using Poetry, using 0.16.1 for x86 Mac will lead to missing dependencies during lock/installation. See this issue for more details:

- #5747
