### ISSUE TITLE
Request to add Python 3.11 support?

### ISSUE THREAD

**Issue by hiyyg** [isl-org/Open3D#5620]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Proposed new feature or change

It might be much faster with the support of Python 3.11.

**Comment by dancergraham** [comment]
The upgrade to Python 3.10 was blocked by Tensorflow and Pytorch. I don't know whether other dependencies will block Open3D but here are links to the Python 3.11 issues on those two : 

Tensorflow: https://github.com/tensorflow/tensorflow/issues/52324
Pytorch: https://github.com/pytorch/pytorch/issues/86566

**Comment by johnthagen** [comment]
The correct Tensorflow 3.11 upstream issue is:

- https://github.com/tensorflow/tensorflow/issues/58032

**Comment by dancergraham** [comment]
> The correct Tensorflow 3.11 upstream issue is:
> 
> * [Support Python 3.11 tensorflow/tensorflow#58032](https://github.com/tensorflow/tensorflow/issues/58032)

Good catch! updated...

**Comment by chibai** [comment]
https://pypi.org/project/torch/1.13.1/#files

There's official pytoch1.31 on Linux python3.11
Hope it will work for open3d python3.11

**Comment by avielTevel** [comment]
any update? thanks!

**Comment by johnthagen** [comment]
Still waiting for upstream dependencies to add support.

- https://github.com/tensorflow/tensorflow/issues/58032
- https://github.com/pytorch/pytorch/issues/86566

**Comment by johnthagen** [comment]
### Update

- [Tensorflow `2.12.0rc1` has been released to PyPI with 3.11 wheels](https://pypi.org/project/tensorflow/2.12.0rc1/#files)
- [PyTorch `2.0.0` has been released to PyPI with 3.11 wheels](https://pypi.org/project/torch/2.0.0/#files)

**Comment by sungminlee114** [comment]
Any updates?

**Comment by jackjansen** [comment]
Chiming in with a request for updates, specifically at ETA for an official pypi release that supports 3.11.

(Note that I am most definitely **not** complaining: many heartfelt kudos for the Open3D maintainers from my side!!)

But. Now that many of the CI/CD hosts (specifically GitHub Actions from Mac) have progressed to Python 3.11, and `brew` has progressed to Python 3.11, and `cmake` makes it incredibly difficult to select a specific Python life is becoming very difficult again. 

And it's only half a year since I removed all the cruft in my build scripts because Python 3.10 wasn't supported by open3d....

**Comment by samypr100** [comment]
Some notes from my attempted upgrades of TF (no CUDA)
* TF 2.9 and 2.10 upgrades seemed ok at a glance...
* Upgrading to TF 2.11 would cause some minor fixable issues on the Open3D side e.g. moving `Status::OK()` to using `OkStatus()`.
* TF 2.12 is the first one with Python 3.11 support, but it would now require a C++17 build, in addition to some other minor fixes.
* TF/TF-macos 2.13 seems to be the first one to support Python 3.11 ARM OSX support, so we'd have to wait on that one first or use tf-nightly 2.13 for macos arm which might be acceptable (tensorflow/tensorflow#60209) 

The biggest issue I saw is that the new tensorflow would now require `-DGLIBCXX_USE_CXX11_ABI=ON` where as pytorch still needs `-DGLIBCXX_USE_CXX11_ABI=OFF`, so there's a conflict if we want to build both modules at the same time. Building pytorch from source seems to fix it, but can add extra hours to the build. (pytorch/pytorch#51039)

**Comment by johnthagen** [comment]
@ssheorey @samypr100 

`tensorflow-macos` uploaded Python 3.11 wheels today for 2.12.0

- https://github.com/tensorflow/tensorflow/issues/60209#issuecomment-1548539324
- https://pypi.org/project/tensorflow-macos/2.12.0/#files

**Comment by Rheinwalt** [comment]
is there a working pip pkg for linux with python 3.11 and if yes where can I get it?

**Comment by johnthagen** [comment]
@Rheinwalt No, Open3D doesn't support Python 3.11 yet. @ssheorey self assigned and all the needed dependencies support 3.11, but Open3D itself needs updates to support it.

**Comment by OlivierLDff** [comment]
I've locally updated to pybind11 v2.11.1 and it compiles locally.

**Comment by johnthagen** [comment]
3.11 wheels have been published with 0.18:

- https://github.com/isl-org/Open3D/pull/6288#issuecomment-1878030429

**Comment by chibai** [comment]
Great Job！
Now we can look forward to python3.12 support. Since Ubuntu 24.04 LTS will release next year, and it's default python3 version is supposed to be python 3.12

**Comment by johnthagen** [comment]
@chibai See

- #6433
