### ISSUE TITLE
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by Wangyao1997-sdu** [isl-org/Open3D#5627]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

I have been try to start open3d, but I stopped here.

python 3.8

### Steps to reproduce the bug

```python
import open3d as o3d
mesh = o3d.io.read_triangle_mesh("test.off") # Cannot find reference 'io' in '__init__.py'
```

### Error message

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### Open3D, Python and System information

```markdown
- Operating system:macOS 13
- Python version: Python 3.8 
- Open3D version: 0.16.0
- How did you install Open3D?: pip
```

**Comment by Wangyao1997-sdu** [comment]
I solved this problem when I reinstall open3d with vision 0.15.1!

**Comment by mingyangpeng** [comment]
I have the same problem，even if the example code
"Open3D/examples/python/visualization/mouse_and_point_coord.py"
error as below when quit window:

```
(o3d) jhon@mbp visualization % python mouse_and_point_coord.py 
FEngine (64 bits) created at 0x156400000 (threading is enabled)
FEngine resolved backend: OpenGL
[error] GLFW error: Cocoa: Failed to find service port for display
zsh: segmentation fault  python mouse_and_point_coord.py

```

my env is clean , open3d build from source:
'''
name: o3d
channels:
  - robostack
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h3422bc3_4
  - ca-certificates=2022.9.24=h4653dfc_0
  - libffi=3.4.2=h3422bc3_5
  - libsqlite=3.39.4=h76d750c_0
  - libzlib=1.2.13=h03a7124_4
  - ncurses=6.3=h07bb92c_1
  - openssl=3.0.5=h03a7124_2
  - pip=22.3=pyhd8ed1ab_0
  - python=3.9.13=h96fcbfb_0_cpython
  - readline=8.1.2=h46ed386_0
  - setuptools=65.5.0=pyhd8ed1ab_0
  - sqlite=3.39.4=h2229b38_0
  - tk=8.6.12=he1e0b03_0
  - tzdata=2022e=h191b570_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.6=h57fd34a_0
  - yaml=0.2.5=h3422bc3_2
  - pip:
    - attrs==22.1.0
    - brotli==1.0.9
    - click==8.1.3
    - configargparse==1.5.3
    - dash==2.6.2
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - fastjsonschema==2.16.2
    - flask==2.2.2
    - flask-compress==1.13
    - importlib-metadata==5.0.0
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - jsonschema==4.16.0
    - jupyter-core==4.11.2
    - markupsafe==2.1.1
    - nbformat==5.5.0
    - numpy==1.23.4
    - open3d==0.16.0+2c9f85b9
    - opencv-contrib-python==4.6.0.66
    - opencv-python==4.6.0.66
    - plotly==5.11.0
    - pyrsistent==0.18.1
    - pyyaml==6.0
    - tenacity==8.1.0
    - traitlets==5.5.0
    - werkzeug==2.2.2
    - zipp==3.10.0
prefix: /Users/jhon/dev/miniconda3/envs/o3d
'''
