### ISSUE TITLE
How can one set the line thickness of geometry.OrientedBoundingBox?

### ISSUE THREAD

**Issue by gc625** [isl-org/Open3D#5637]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I'm using open3d to visualize bounding box predictions of an point-based object detection model. The issue is that I have no matter what I try, seems like I cannot change the line thickness of the boxes I draw with geometry.OrientedBoundingBox. Attempting to directly modify the `LineSet` attribute yields the error 
```
AttributeError: 'open3d.cpu.pybind.geometry.OrientedBoundingBox' object attribute 'LineSet' is read-only
```

trying to change the line width property of the render options via
```
    opt = vis.get_render_option()
    opt.line_width = 5
```

also does not work.  So how can I adjust the line width of bounding box objects?

**Comment by ZoangX** [comment]
Recently, I met the same problem as you. Have you solved it?

**Comment by YuYuCodeNoob** [comment]
Use the O3DVisualizer
```
import numpy as np
import open3d as o3d
import open3d.visualization.gui as gui
print("Let's draw a box using o3d.geometry.LineSet.")
points = [
[0, 0, 0],
[1, 0, 0],
[0, 1, 0],
[1, 1, 0],
[0, 0, 1],
[1, 0, 1],
[0, 1, 1],
[1, 1, 1],
]
lines = [
[0, 1],
[0, 2],
[1, 3],
[2, 3],
[4, 5],
[4, 6],
[5, 7],
[6, 7],
[0, 4],
[1, 5],
[2, 6],
[3, 7],
]
colors = [[1, 0, 0] for i in range(len(lines))]
line_set = o3d.geometry.LineSet(
points=o3d.utility.Vector3dVector(points),
lines=o3d.utility.Vector2iVector(lines),
)
line_set.colors = o3d.utility.Vector3dVector(colors)
point_cloud2 = o3d.geometry.PointCloud()
point_cloud2.points = o3d.utility.Vector3dVector(points)
point_cloud2.paint_uniform_color([0, 1, 0])
geometries = [line_set, point_cloud2]
gui.Application.instance.initialize()
vis = o3d.visualization.O3DVisualizer("03DVisualizer",1920,1080)
vis.line_width = 5 # set line width
# set the background color
bg_color = np.array([0.0, 0.0, 0.0, 1.0], dtype=np.float32)
vis.set_background(bg_color=bg_color, bg_image = None)
for i,geom in enumerate(geometries):
    vis.add_geometry(f"geom{i}",geom)
vis.show_skybox(False)
gui.Application.instance.add_window(vis)
gui.Application.instance.run()
vis.destroy()
```
