### ISSUE TITLE
Open3D 0.16 uses private Embree headers

### ISSUE THREAD

**Issue by roehling** [isl-org/Open3D#5642]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Steps to reproduce the issue

N/A

### Error message

```shell
N/A
```

### Open3D, Python and System information

```markdown
N/A
```

### Additional information

While packaging Open3D 0.16 for Debian, I realized I cannot link against the packaged Embree library, because RaycastingScene.cpp includes tutorial code which is not part of the official API.

**Comment by benjaminum** [comment]
Can you give some more details? Are headers missing or are there missing symbols?

**Comment by roehling** [comment]
https://github.com/isl-org/Open3D/blob/61276a05ebfe8522c1225cd81c9971928a3e5316/cpp/open3d/t/geometry/RaycastingScene.cpp#L36

The tutorial code is not part of the official API, so  `RaycastingScene.cpp` can be built only if Embree is also built from source.

**Comment by benjaminum** [comment]
I see, so for debian we have to build using the embree debian package if I understand it correctly.
I think we will then just include that code directly. The embree license should allow this.

**Comment by roehling** [comment]
That would be awesome. Thank you!

**Comment by benjaminum** [comment]
@roehling Can you check the if the issue is solved now?

**Comment by roehling** [comment]
Yes, the issue is solved and I have just uploaded an Embree-enabled Open3D to Debian. Thanks!
