### ISSUE TITLE
*** AttributeError: 'open3d.cpu.pybind.geometry.TriangleMesh' object has no attribute 'fill_holes'

### ISSUE THREAD

**Issue by unimusic** [isl-org/Open3D#5662]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

I am trying to fill holes in a mesh. The example given is much simpler than the actual mesh I am trying to fill. I keep getting the error that fill_holes is not an attribute of TriangleMesh.

### Steps to reproduce the bug

```python
import open3d
import numpy as np

def create_open3d(inds):
    pcd = open3d.geometry.PointCloud()
    pcd.points = open3d.utility.Vector3dVector(inds.astype(np.int32))
    pcd.estimate_normals()
    return pcd

inds = np.array([[3,4,5],[5,6,7],[1,3,5]])
pcd = create_open3d(inds)
radii = [5]
mesh = open3d.geometry.TriangleMesh.create_from_point_cloud_ball_pivoting(pcd, 
                                                                open3d.utility.DoubleVector(radii))
mesh.fill_holes()
```

### Error message

*** AttributeError: 'open3d.cpu.pybind.geometry.TriangleMesh' object has no attribute 'fill_holes'

### Expected behavior

For a mesh to be returned.

### Open3D, Python and System information

```markdown
- Operating system: Windows 10 64-bit
- Python version: Python 3.9
- Open3D version: 0.16.0+ace17cf
- System architecture: x86
- Is this a remote workstation?: no
- How did you install Open3D?: pip
```

**Comment by ssheorey** [comment]
Hi @unimusic, the `fill_holes()` function is present in the new Tensor API (`open3d.t.geometry.TriangleMesh` namespace). This should work:

```py
...
mesh = open3d.geometry.TriangleMesh.create_from_point_cloud_ball_pivoting(pcd, 
                                                                open3d.utility.DoubleVector(radii))
tmesh = open3d.geometry.TriangleMesh.from_legacy(mesh)
tmesh.fill_holes()
```

**Comment by unimusic** [comment]
Hi there,

When I do what you recommended, I get the following error:

`AttributeError: type object 'open3d.cpu.pybind.geometry.TriangleMesh' has no attribute 'from_legacy'`

Please advise. Thanks!

**Comment by unimusic** [comment]
I figured it out, needs to be

```
...
mesh = open3d.geometry.TriangleMesh.create_from_point_cloud_ball_pivoting(pcd, 
                                                                open3d.utility.DoubleVector(radii))
tmesh = open3d.t.geometry.TriangleMesh.from_legacy(mesh)
tmesh.fill_holes()
```

Are there any examples of creating a new tensor mesh from point cloud, and doing similar operations to it that are available in the 'legacy' mesh? Thanks.

**Comment by ssheorey** [comment]
Hi @unimusic please check the documentation for the available functionality - we are continuing to add more functionality with each release. The APIs (e.g. function names) are very similar - if you have code that uses the old API, you should be able to switch to the new API very easily.

Some examples are here: `examples/python/t_reconstruction_system`.
