### ISSUE TITLE
Signed distance artifacts

### ISSUE THREAD

**Issue by ekhahniii** [isl-org/Open3D#5669]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

Artifacts are observable in signed distance computations with a sphere.

### Steps to reproduce the bug

```python
mesh = o3d.geometry.TriangleMesh.create_sphere(0.8)
mesh = o3d.t.geometry.TriangleMesh.from_legacy(mesh)

mesh.compute_vertex_normals()
mesh.compute_triangle_normals()

scene = o3d.t.geometry.RaycastingScene()
scene.add_triangles(mesh)

min_bound = mesh.vertex.positions.min(0).numpy() * 1.1
max_bound = mesh.vertex.positions.max(0).numpy() * 1.1
xyz_range = np.linspace(min_bound, max_bound, num=64)
query_points = np.stack(np.meshgrid(*xyz_range.T), axis=-1).astype(np.float32)

signed_distance = scene.compute_signed_distance(query_points)

plt.imshow(signed_distance.numpy()[:, :, 31])
plt.show()
```

![image](https://user-images.githubusercontent.com/49728874/200952356-ab8dfa2a-03bd-44d5-84ea-970208d086f3.png)

### Expected behavior

No artifacts.

### Open3D, Python and System information

```markdown
- Operating system: Windows 10 64-bit
- Python version: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:51:29) [MSC v.1929 64 bit (AMD64)]
- Open3D version: output from python: 0.16.1+30789aa
- System architecture: x86
- Is this a remote workstation?: no
- How did you install Open3D?: pip
- Compiler version (if built from source): n/a
```

**Comment by benjaminum** [comment]
The inside outside is determined by counting the number of intersections. If a ray hits an edge or a vertex this count is sometimes producing the problem you see in your example. We added some changes like adding jitter to the ray directions and support for multiple samples to make this more accurate in the master branch.
