### ISSUE TITLE
Using OffscreenRenderer on headless Jetson/Ubuntu device

### ISSUE THREAD

**Issue by MartinPedersenpp** [isl-org/Open3D#5674]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I have a program that I am running on my Laptop (PC with windows and monitor)

At one point of the program I have to render some depth images of a 3D object so I use
`render = o3d.visualization.rendering.OffscreenRenderer(256, 256)`

This works fine, but I now want to move my program to a Nvidia Jetson device.

At first I had build my Open3D from source enabling only CUDA, so I got met with the error stating that "o3d.visualization does not have a module named rendering".
I then rebuild with the CUDA and BUILD_GUI FLAG and then I got this error.

> [Open3D INFO] EGL headless mode enabled.
> FEngine (64 bits) created at 0x7f662d9010 (threading is enabled)
> eglInitialize failed
> Segmentation fault (core dumped)
I searched around and found that there is an issue with OpenGL having some issues initializing in headless mode, but I haven't found a solution to that.

I then thought that maybe I had to build with the ENABLE_HEADLESS_RENDERING flag, but this requires BUILD_GUI to be disabled, so that puts me back to square one where I don't have the "rendering" module.

Any help to how I can make the offscreenrender work on a headless Jetson would be appreciated.

Edit: It seems to be an issue with OpenGL and Mesa, but I can't seem to find any instructions on how to build Mesa from source on a ARM processor.

**Comment by kungkook** [comment]
> 

i mean the same  question, The code works in my windows environment, but it appears in ubuntu: EGL headless mode enabled. 
Have you solved it yet?

**Comment by lichangW** [comment]
same question.....
