### ISSUE TITLE
cuda.pybind.geometry.OrientedBoundingBox support

### ISSUE THREAD

**Issue by orgicus** [isl-org/Open3D#5703]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Proposed new feature or change

Currently OrientedBoundingBox is supported only on the CPU.

It would be great to crop a (CUDA) point cloud using a `OrientedBoundingBox` (also on CUDA).
One workaround I can think of is rotating the pointcloud with the inverse `OrientedBoundingBox` transform (as if it were a `AxisAlignedBoundingBox`), crop, then rotate the point cloud back to it's original transform, however this feels hacky.

OrientedBoundingBox CUDA bindings would make the implementation much more straight forward and neat (unless there's an even simpler solution ?)

### References

http://www.open3d.org/docs/release/python_api/open3d.geometry.OrientedBoundingBox.html#open3d.geometry.OrientedBoundingBox

http://www.open3d.org/docs/release/python_api/open3d.geometry.AxisAlignedBoundingBox.html

https://github.com/isl-org/Open3D/blob/bcb4b38a1eb6aff4d675fccf5e9b52df98c5e2b9/cpp/open3d/geometry/BoundingVolume.cpp

**Comment by yuecideng** [comment]
Hi @orgicus , the tensor based OBB (CUDA supported) is in progress #5389. We will make it available in master soon.

**Comment by yuecideng** [comment]
The PR has been merged into master now.

**Comment by orgicus** [comment]
Amazing! Thank you so much !

(Would you be able to advise with https://github.com/isl-org/Open3D/issues/5734 ?)
