### ISSUE TITLE
Precision issue in VoxelGrid.create_from_triangle_mesh()

### ISSUE THREAD

**Issue by Blubberblub** [isl-org/Open3D#5704]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [x] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

I tested the voxelization functionality of o3d.geometry.VoxelGrid.create_from_triangle_mesh_within_bounds() with a simple cube that i imported through a gltf file and found some unexpected behavior. The function created some voxels inside the cube that are incorrect. The gltf file that i can't upload here consists of a simple 4x4x4 cube with pivot at 0,0,0 and sitting on z = 0 (y in gltf coordinate system). You can see the dimensions in  the print statements.

### Steps to reproduce the bug

```python
import open3d as o3d
import numpy as np
from PIL import Image

print("Testing IO for meshes ...")
mesh = o3d.io.read_triangle_mesh("Cube_mod.glb")
mesh_bb = mesh.get_axis_aligned_bounding_box()

print('voxelization')

voxel_size = 1
print("voxel_size:", voxel_size)

print("mesh bb min:", mesh_bb.get_min_bound())
print("mesh bb max:", mesh_bb.get_max_bound())

floor = np.floor(mesh_bb.get_min_bound()) - voxel_size/2
ceil = np.ceil(mesh_bb.get_max_bound()) + voxel_size/2
print("shifted min:", floor)
print("shifted max:", ceil)

voxel_grid = o3d.geometry.VoxelGrid.create_from_triangle_mesh_within_bounds(
    mesh,
    voxel_size=voxel_size,
    min_bound=floor,
    max_bound=ceil)

grid_bb_min = voxel_grid.get_min_bound()
grid_bb_max = voxel_grid.get_max_bound()
print("grid bb min:", grid_bb_min)
print("grid bb max:", grid_bb_max)

shape_values = (grid_bb_max - grid_bb_min)/voxel_size
print("shape_values:", shape_values)

# out array with zeros
out_data = np.zeros(
    (
        int(shape_values[0]),
        int(shape_values[1]),
        int(shape_values[2])
    ), dtype=np.uint8)

print("shape of out_data:", out_data.shape)

# list of all voxels
voxels = voxel_grid.get_voxels()
print("num voxels:", len(voxels))

# calculate the number of voxels the geometry should actually have
# full volume voxel number
# adding one since we shifted the voxels
num_volume_voxels = np.prod(mesh_bb.get_max_bound() - mesh_bb.get_min_bound() + 1)
# inside volume voxel number
num_inside_voxel = np.prod(mesh_bb.get_max_bound() - mesh_bb.get_min_bound() - 1)
# number of hull voxels
num_hull_voxels = num_volume_voxels- num_inside_voxel
# print("calculated volume voxels:", num_volume_voxels)
# print("calculated inside voxels:", num_inside_voxel)
print("supposed num voxels:", num_hull_voxels)

# set numpy array items to 255 at voxels
for voxel in voxels:
    grid_idx = voxel.grid_index
    # for checking the voxel center points:
    # print(voxel_grid.get_voxel_center_coordinate(grid_idx))
    out_data[grid_idx[0], grid_idx[1], grid_idx[2]] = 1

for i in range(out_data.shape[1]):
    # transpose since we are in WebGL coordinates
    cut = np.transpose(out_data[:,i,:])
    print(cut)
```

### Error message

Testing IO for meshes ...
voxelization
voxel_size: 1
mesh bb min: [-2.  0. -2.]
mesh bb max: [2. 4. 2.]
shifted min: [-2.5 -0.5 -2.5]
shifted max: [2.5 4.5 2.5]
grid bb min: [-2.5 -0.5 -2.5]
grid bb max: [2.5 4.5 2.5]
shape_values: [5. 5. 5.]
shape of out_data: (5, 5, 5)
num voxels: 117
supposed num voxels: 98.0
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 0 0 1]
 [1 1 0 0 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 0 0 1]
 [1 1 0 0 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

### Expected behavior

The voxels inside the cube are supposed to be empty since there is no triangle intersecting them.

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 22.04 WSL
- Python version: Python 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0] on linux
- Open3D version: 0.16.0
- System architecture: x86_64
- Is this a remote workstation?: no
- How did you install Open3D?: pip
```

### Additional information

<img width="354" alt="image" src="https://user-images.githubusercontent.com/9118119/202689600-07d598c4-de13-4ac5-8710-d15ef406a445.png">

**Comment by benjaminum** [comment]
@faberno Thanks for testing the master branch!
