### ISSUE TITLE
How to make o3d.core.cuda.is_available()  True, I got a Nvidia GPU

### ISSUE THREAD

**Issue by forlinchow** [isl-org/Open3D#5705]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

How to make o3d.core.cuda.is_available()  True, I got a Nvidia GPU

now False

**Comment by ssheorey** [comment]
This happens because of CUDA driver / runtime misconfiguration. Make sure the CUDA driver and runtime are the same version (check that `nvidia-smi` works). Rebooting often helps.

**Comment by forlinchow** [comment]
> This happens because of CUDA driver / runtime misconfiguration. Make sure the CUDA driver and runtime are the same version (check that `nvidia-smi` works). Rebooting often helps.

![image](https://user-images.githubusercontent.com/19525409/218046965-2fff88f2-44b9-4716-8183-a30bea214706.png)
![image](https://user-images.githubusercontent.com/19525409/218047059-165d55f1-ad21-4c52-8c97-11e69287c9a0.png)
I checked the nvidia-smi command in cmd is ok, but in pycharm console, it still returns False

Please help！ 
Thanks

**Comment by ssheorey** [comment]
You are on Windows. Windows Python wheels are built without CUDA. Please build from source if you want CUDA support.

**Comment by forlinchow** [comment]
Thankyou！




.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "isl-org/Open3D"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月9日(星期四) 上午10:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [isl-org/Open3D] How to make o3d.core.cuda.is_available()  True, I got a Nvidia GPU (Issue #5705)





 
You are on Windows. Windows Python wheels are built without CUDA. Please build from source if you want CUDA support.
