### ISSUE TITLE
ImportError: DLL initialization routine failed while importing pybind 

### ISSUE THREAD

**Issue by dwjulian** [isl-org/Open3D#5710]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

When importing open3d i keep getting the DDL error below, I already tried multiple python versions and even an anaconda installation but to no advance. Its probably a windows issue but I  have no idea on how to fix it.
I've been suck with this issue for around a week now and I really need help,

### Steps to reproduce the bug

python
1 create virtual environment with pyvenv in python 3.10.0.
2 activate the environment
3 > pip install open3d
4 >python -c "import open3d"

I don't know if this will be enough to reproduce the bug but it does on my device

### Error message

```
(.venv)❯ py -c "import open3d"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File \.venv\lib\site-packages\open3d\__init__.py", line 97, in <module>
    from open3d.cpu.pybind import (camera, data, geometry, io, pipelines,
ImportError: DLL load failed while importing pybind: A dynamic link library (DLL) initialization routine failed. 
```

### Open3D, Python and System information

```markdown
- Operating system: Windows 11 64-bit
- Python version: Python 3.10.0.
- Open3D version: open3d 0.16.0
- System architecture: x64
- Is this a remote workstation?: no
- How did you install Open3D?: pip and conda
```

**Comment by ssheorey** [comment]
Hi @dwjulian there was a recent PR merged for a similar issue. #5259 

Please try with the latest development Python wheel from here:
http://www.open3d.org/docs/latest/getting_started.html#development-version-pip
and let us know if you still have this issue.

**Comment by ssheorey** [comment]
Please reopen if you still have this issue.
