### ISSUE TITLE
Poisson Disk Sample uses Beta=0.5 Instead of 0.65

### ISSUE THREAD

**Issue by adam-grant-hendry** [isl-org/Open3D#5712]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

The algorithm in `TriangleMesh::SamplePointsPoissonDisk` uses a beta value of `0.5`, but the paper defines this as `0.65`:

https://github.com/isl-org/Open3D/blob/653a135f90d4e7c81841af22bda77c79565191d3/cpp/open3d/geometry/TriangleMesh.cpp#L578

From [the paper](http://www.cemyuksel.com/research/sampleelimination/sampleelimination.pdf):

![image](https://user-images.githubusercontent.com/59346180/202938396-dd8fc5a1-63fd-4587-a3b2-0d9aa7afdae1.png)

The comment in the source claims the algorithm uses the beta value from the paper, which it does not. If the algorithm veers from the paper, it would be nice if it explained why.

Those expecting results consistent with the paper might be surprised.

### Steps to reproduce the bug

```python
N/A
```

### Error message

N/A

### Expected behavior

The algorithm uses the value from the paper or explains in the comments or documentation why a different value was used.

### Open3D, Python and System information

```markdown
N/A
```

### Additional information

N/A

**Comment by benjaminum** [comment]
This looks like a mistake. Thanks for reporting this.

**Comment by benjaminum** [comment]
Closing because the PR addressing the issue was merged
