### ISSUE TITLE
How build Open3D with CPU and GPU support on Windows ?

### ISSUE THREAD

**Issue by orgicus** [isl-org/Open3D#5734]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I've followed @yxlao 's advice in [this comment](https://github.com/isl-org/Open3D/issues/4371#issuecomment-985943887):

> Essentially, you'll need to compile twice:
> 
> config with CUDA ON
> build
> don't delete the build directory, config again with CUDA OFF.
> build

However I'm encountering this error:
```
RuntimeError: [Open3D Error] (class std::shared_ptr<class open3d::core::MemoryManagerDevice> __cdecl open3d::core::MemoryManager::GetMemoryManagerDevice(const class open3d::core::Device &)) C:\Users\george.profenza\Documents\code\Open3D\cpp\open3d\core\MemoryManager.cpp:142: Unsupported device "CUDA:0". Set BUILD_CUDA_MODULE=ON to compile for CUDA support and BUILD_SYCL_MODULE=ON to compile for SYCL support.
```

I'm experiencing this with Open3D 0.15.2 on Windows 11 (21H2) and Python 3.10.8.

After a CUDA ON, then CUDA OFF, I've tried enabling CUDA again, but the problem persists.

cmake gui outputs:
```
================================================================================
Open3D 0.15.2 Configuration Summary
================================================================================
Enabled Features:
  OpenMP .................................. ON
  Headless Rendering ...................... OFF
  Azure Kinect Support .................... OFF
  Intel RealSense Support ................. OFF
  CUDA Support ............................ ON
  CUDA cached memory manager .............. ON
  SYCL Support ............................ OFF
  ISPC Support ............................ ON
  Build GUI ............................... ON
  Build WebRTC visualizer ................. ON
  Build Shared Library .................... OFF
  Use Windows Static Runtime .............. ON
  Build Unit Tests ........................ OFF
  Build Examples .......................... ON
  Build Python Module ..................... ON
  Build Jupyter Extension ................. ON
  Build TensorFlow Ops .................... OFF
  Build PyTorch Ops ....................... OFF
  Build Benchmarks ........................ OFF
  Bundle Open3D-ML ........................ OFF
  Force GLIBCXX_USE_CXX11_ABI= ............ 0
================================================================================
Third-Party Dependencies:
  Assimp .................................. yes (build from source)
  BLAS .................................... yes
  Eigen3 .................................. yes (build from source)
  filament ................................ yes (build from source)
  fmt ..................................... yes (build from source)
  GLEW .................................... yes (build from source)
  GLFW .................................... yes (build from source)
  googletest .............................. no
  imgui ................................... yes (build from source)
  ippicv .................................. yes (build from source)
  JPEG .................................... yes (build from source)
  jsoncpp ................................. yes (build from source)
  liblzf .................................. yes (build from source)
  msgpack ................................. yes (build from source)
  nanoflann ............................... yes (build from source)
  OpenGL .................................. yes
  PNG ..................................... yes (build from source)
  qhullcpp ................................ yes (build from source)
  librealsense ............................ no
  TBB ..................................... yes (build from source)
  tinyfiledialogs ......................... yes (build from source)
  TinyGLTF ................................ yes (build from source)
  tinyobjloader ........................... yes (build from source)
  WebRTC .................................. yes (build from source)
  ZeroMQ .................................. yes (build from source)
================================================================================
Configuring done
Generating done
```

I can confirm the .whl archive contains both cuda and cpu .pyd files in the open3d folder.
(I have uploaded the whl [here](https://sensori.al/o3d/open3d-0.15.2+e1c485b4-cp310-cp310-win_amd64.whl))

I've looked at https://github.com/isl-org/Open3D/blob/ea252499eca8a36321abbcf01a095bbc28fa9eba/util/ci_utils.sh#L151 as advised. If understand correctly:
- the [CPU bindings are build first](https://github.com/isl-org/Open3D/blob/ea252499eca8a36321abbcf01a095bbc28fa9eba/util/ci_utils.sh#L212)
- it [removes cpu build files](https://github.com/isl-org/Open3D/blob/ea252499eca8a36321abbcf01a095bbc28fa9eba/util/ci_utils.sh#L226) 
- it [sets CUDA ON](https://github.com/isl-org/Open3D/blob/ea252499eca8a36321abbcf01a095bbc28fa9eba/util/ci_utils.sh#L228)

I feel I'm missing a detail when building, but I'm not sure what.

How do you advise building Open3D with cpu and gpu support ?

**Comment by yuecideng** [comment]
Hi @orgicus , could you check the `_build_config.py` file with the `BUILD_CUDA_MODULE` option? This file would be in the path of 
`.../site-packages/open3d`.

**Comment by orgicus** [comment]
@yuecideng Thank you for the advice.

I had a look and the value is set to `true`.

I've also tried rebuilding from scratch and enabling `BUILD_COMMON_CUDA_ARCHS` but without building the cpu module I still get the error regarding open3d.cpu missing at import. I've tried loading the cuda .pyd file as a test, but it seems to complain about a missing depdencency:

```
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes import CDLL
>>> CDLL("C:\\Users\\george.profenza\\Documents\\gp\\code\\Open3D\\build-py-3.10.8-with-cuda\\lib\\python_package\\open3d\\cuda\\pybind.cp310-win_amd64.pyd"
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\george.profenza\.pyenv\pyenv-win\versions\3.10.8\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\george.profenza\Documents\gp\code\Open3D\build-py-3.10.8-with-cuda\lib\python_package\open3d\cuda\pybind.cp310-win_amd64.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
```

The file is there:
```
>>> import os
>>> os.path.exists("C:\\Users\\george.profenza\\Documents\\gp\\code\\Open3D\\build-py-3.10.8-with-cuda\\lib\\python_package\\open3d\\cuda\\pybind.cp310-win_amd64.pyd")
True
```

I've looked at dependencies and nothing looks too strange to me (image attached):
![2022-12-04 05_11_29-Dependencies (x64)](https://user-images.githubusercontent.com/189031/205476373-f6575876-97a2-4fe0-9ed8-a0ce1f49bc40.png)
(python310.dll is not in `%PATH%` (which is why is suspect is read) as I use a virtual environment).

I've re-read the [open3d build documentation](http://www.open3d.org/docs/release/compilation.html#windows), but haven't spotted the quirk @yxlao mentioned (regarding building the GPU enabled bindings, then the CPU bindings).

Reading [__init__.py](https://github.com/isl-org/Open3D/blob/master/python/open3d/__init__.py#L60) I understand the order is this:
- if `BUILD_CUDA_MODULE` is enabled, the cpu pyd is loaded first, but not accessed yet
- cuda pyd is loaded
- the relevant modules are imported 
- `__DEVICE_API__` is set to  `"cuda"` (which ensures `core, camera, data, geometry, io, pipelines, utility, t` are imported only form the cuda pyd and not from the cpu pyd)
                                   
Does anything I might be doing wrong so far standup ?

Thank you so much,
George
