### ISSUE TITLE
How to callback viewpoint in real-time when use mouse to move the viewpoints ?

### ISSUE THREAD

**Issue by liubonan123** [isl-org/Open3D#5737]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

When I use vis.run to start a gui window and move the viewpoint by mouse, I can not get the viewpoint in real time.

**Comment by ssheorey** [comment]
You can add a callback for [mouse movement](http://www.open3d.org/docs/latest/python_api/open3d.visualization.gui.MouseEvent.html#open3d.visualization.gui.MouseEvent), see the example callbacks here:
https://github.com/isl-org/Open3D/blob/master/examples/python/visualization/vis_gui.py
