### ISSUE TITLE
How to render image with mesh true colors using OffScreenRenderer

### ISSUE THREAD

**Issue by drapado** [isl-org/Open3D#5760]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi, I would like to know how to render a color image whose colors are the same as in the mesh. Asked also in this unsolved issue: [https://github.com/isl-org/Open3D/issues/5215](https://github.com/isl-org/Open3D/issues/5215)

Thanks!

**Comment by gobanana520** [comment]
Hi, I also meet same issue, my workround is to disable the post_processing and use 'defaultUnlit' shader as below:

```
o3d_renderer = rendering.OffscreenRenderer(width, height)
o3d_renderer.scene.set_background([0.0, 0.0, 0.0, 1.0])
o3d_renderer.scene.view.set_post_processing(False)
# material for TriangleMesh
mat_mesh = rendering.MaterialRecord()
mat_mesh.shader = "defaultUnlit"
# add geometry
o3d_renderer.scene.clear_geometry()
o3d_renderer.scene.add_geometry("mesh", mesh, mat_mesh, True)
# setup camera
o3d_renderer.setup_camera(intrinsic, extrinsic, height)
# rgb image
rgb_img = o3d_renderer.render_to_image()
```

**Comment by drapado** [comment]
It seems to work just fine, thanks for sharing!
Interesting that you need to use the shader "defaultUnlit" instead of "unlitSolidColor".

**Comment by gobanana520** [comment]
> It seems to work just fine, thanks for sharing! Interesting that you need to use the shader "defaultUnlit" instead of "unlitSolidColor".

Oh, that's because when set_post_processing=False, the shader "unlitSolidColor" won't use the mesh's colors, it will use the default color set for the Material, however, "defaultUnlit" will use the mesh's colors for rendering.
