### ISSUE TITLE
Why use ~ requirement for jupyter-packaging?

### ISSUE THREAD

**Issue by ashnair1** [isl-org/Open3D#5766]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Currently open3d pins `jupyter-packaging~=0.10.0`. Why was this done? Why couldn't have been set to `jupyter-packaging>=0.10.0`. Was there anything specific in `0.11.0+` that proved a problem for open3d?

**Comment by ssheorey** [comment]
Hi @ashnair1 pinning dependencies to specific versions is standard SW Engg practice - future dependency versions may have unknown API changes that may cause unpredictable errors in the future.
