### ISSUE TITLE
o3d.visualization.rendering.OffscreenRenderer, TypeError: __init__(): incompatible constructor arguments.

### ISSUE THREAD

**Issue by kungkook** [isl-org/Open3D#5776]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

RUN code: self.render = o3d.visualization.rendering.OffscreenRenderer(width=img_w, height=img_h, headless=True)
ERROR: TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. open3d.cpu.pybind.visualization.rendering.OffscreenRenderer(width: int, height: int, resource_path: str = '')

Invoked with: kwargs: width=1440, height=1080, headless=True
Under: windows11_x86
            open3d 0.16.0(pip install)

**Comment by errissa** [comment]
With 0.16 the `OffscreenRenderer` no longer has the `headless` initialization parameter. It was renders true headless. So, simply remove `headless=True` from your call to `OffscreenRenderer`

**Comment by TE-KazukiYoshiyama** [comment]
On windows 10 and Open3D=0.16.0, I still get the error even if deleting the headless option. The error msg (`"EGL Headless is not supported on this platform."`) comes from [here](https://github.com/isl-org/Open3D/blob/v0.16.0/cpp/open3d/visualization/rendering/filament/FilamentEngine.cpp#L119-L125). 

This error did not happen in 0.15.1, so it would be really appreciated if v0.16+ supports the OffscreenRender on windows again.

**Comment by imbinwang** [comment]
> On windows 10 and Open3D=0.16.0, I still get the error even if deleting the headless option. The error msg (`"EGL Headless is not supported on this platform."`) comes from [here](https://github.com/isl-org/Open3D/blob/v0.16.0/cpp/open3d/visualization/rendering/filament/FilamentEngine.cpp#L119-L125).
> 
> This error did not happen in 0.15.1, so it would be really appreciated if v0.16+ supports the OffscreenRender on windows again.

Same problem! Have you found a solution?

**Comment by KazukiYoshiyama-sony** [comment]
@imbinwang Not yet. I was using v0.15.1 in Windows. I do not try v0.17.0, recently released, yet.

**Comment by w3ichen** [comment]
> @imbinwang Not yet. I was using v0.15.1 in Windows. I do not try v0.17.0, recently released, yet.

I tried v0.17.0 and it still doesn't work

**Comment by prerakmody** [comment]
On MacOS (Ventura 13.4) with open3d==0.17.0, I am unable to even instantiate the `o3d.visualization.rendering.OffscreenRenderer()` class.


I get the following error
```
*** RuntimeError: [Open3D Error] (open3d::visualization::rendering::EngineInstance::EngineInstance()) /Users/renes/development/open3d_work/Open3D/cpp/open3d/visualization/rendering/filament/FilamentEngine.cpp:104: EGL Headless is not supported on this platform.
```

**Comment by xuzhuang1996** [comment]
> On MacOS (Ventura 13.4) with open3d==0.17.0, I am unable to even instantiate the `o3d.visualization.rendering.OffscreenRenderer()` class.
> 
> I get the following error
> 
> ```
> *** RuntimeError: [Open3D Error] (open3d::visualization::rendering::EngineInstance::EngineInstance()) /Users/renes/development/open3d_work/Open3D/cpp/open3d/visualization/rendering/filament/FilamentEngine.cpp:104: EGL Headless is not supported on this platform.
> ```

I have the same error,did you fix it ?
