### ISSUE TITLE
Ray Cast Precision

### ISSUE THREAD

**Issue by Ludwig-Graef** [isl-org/Open3D#5777]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

Hey,
I am working with `scene.cast_rays()` in Open3D. What I don't understand is why the ray intersection accuracy with the mesh has an error of ~3e-05. Is there an option or other solution to increase the precision?

### Steps to reproduce the bug

```python
import numpy as np
import open3d as o3d
import trimesh


def test_plane_mesh_raycast_precision(mesh: trimesh.Trimesh, ray_origins: np.ndarray, ray_directions: np.ndarray):
    scene = o3d.t.geometry.RaycastingScene()
    scene.add_triangles(o3d.t.geometry.TriangleMesh.from_legacy(mesh.as_open3d))
    normal, point_on_plane = mesh.face_normals[0], vertices[1]
    plane_coeffs = np.append(normal, -point_on_plane.dot(normal))

    rays = np.concatenate([ray_origins, ray_directions], axis=1).astype(np.float32)
    distances = scene.cast_rays(rays)['t_hit'].numpy()
    pts_xyz = ray_origins + distances[..., np.newaxis] * ray_directions

    residuals = plane_coeffs[:3].dot(pts_xyz.T) + plane_coeffs[3]
    assert np.allclose(residuals, 0), f"An error of: {residuals} between plane coefficients and ray."


ray_origins = np.array([[0.0, 1 / 3, 1000.0]])
ray_directions = np.array([[0.0, 0.0, -1.0]])

vertices = np.array([[0.0, 0.0, 0.0], [1.0, 0.0, 1 / 3], [0.0, 1.0, 1 / 3]])
indices = np.array([[0, 1, 2]])
mesh = trimesh.Trimesh(vertices=vertices, faces=indices)

test_plane_mesh_raycast_precision(mesh, ray_origins, ray_directions)
```

### Open3D, Python and System information

```markdown
Versions:
- Ubuntu 22.04
- Python 3.8.13
- Open3D 0.15.2
```

**Comment by benjaminum** [comment]
RaycastingScene uses float32 as datatype. The inaccuracy you get probably stems from the precision limits of that datatype. Unfortunately, the this cannot be changed to float64.

**Comment by benjaminum** [comment]
Closing this issue because we cannot change the datatype. Please comment if this should be reopened.
