### ISSUE TITLE
How to call 'open3d.cuda.pybind.visualization.Visualizer' in Windows10?

### ISSUE THREAD

**Issue by TangToy** [isl-org/Open3D#5780]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I have installed open3d 0.15.1 on both windows10 and ubuntu 18.04. And pytorch and cuda have been both installed. When I call the following codes:

```python
vis = o3d.visualization.Visualizer()
...
vis.add_geometry(points)
```
I found in Ubuntu, the `o3d.visualization.Visualizer() `is an `open3d.cuda.pybind.visualization.Visualizer`, while in windows 10,  the `o3d.visualization.Visualizer() `is an `open3d.cpu.pybind.visualization.Visualizer`.
How could I use the `open3d.cuda.pybind.visualization.Visualizer` in windows 10? Thanks.

**Comment by dancergraham** [comment]
Hello, 
It looks like cuda is supported on Linux - by implication it is not supported on Windows.
With another library I recently succeeded in enabling cuda on Windows by first creating a fresh virtual environment, then installing PyTorch, following these instructions https://pytorch.org/get-started/locally/ and then installing the library - maybe that could work for you ?

**Comment by TangToy** [comment]
> Hello, It looks like cuda is supported on Linux - by implication it is not supported on Windows. With another library I recently succeeded in enabling cuda on Windows by first creating a fresh virtual environment, then installing PyTorch, following these instructions https://pytorch.org/get-started/locally/ and then installing the library - maybe that could work for you ?

Thanks. In fact pytorch has been installed in my Windows virtual environment, but the open3d cannot be run on Windows. So you mean that open3d cannot be run using cuda on Windows now?

**Comment by dancergraham** [comment]
Yes maybe - I don't know, but the installation instructions do not say that it works on Windows

**Comment by WildGrass3389** [comment]
Thanks.

**Comment by TangToy** [comment]
Thanks.
