### ISSUE TITLE
How to run Open3DWebRTC with differently bind ip and port (Win10+Python3.7)

### ISSUE THREAD

**Issue by leehuoshi** [isl-org/Open3D#5785]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Thank you for providing WebRTC API, when i want to bind different ip or port, the fact i can't modify ip and port, the complie result still http://localhost:8888. 

I try to use WEBRTC_IP=127.0.0.1  WEBRTC_PORT=8889 python draw_webrtc.py in conda env or cmd python, still can't modify specificly ip or port. 

Would somebody know how to resolve this isuee.

below code is visualization/draw_webrtc.py 
import open3d as o3d

WEBRTC_IP='127.0.0.1' 
WEBRTC_PORT=8889 

if __name__ == "__main__":
    WEBRTC_IP='127.0.0.1' 
    WEBRTC_PORT=8889 
    o3d.visualization.webrtc_server.enable_webrtc()

    cube_red = o3d.geometry.TriangleMesh.create_box(1, 2, 4)
    cube_red.compute_vertex_normals()
    cube_red.paint_uniform_color((1.0, 0.0, 0.0))
    o3d.visualization.draw(cube_red)

this is my reference: http://www.open3d.org/docs/release/tutorial/visualization/web_visualizer.html#ip-port-binding

**Comment by ssheorey** [comment]
Hi @leehuoshi WEBRTC_IP and WEBRTC_PORT are environment variables. They can be set with

`os.environ["WEBRTC_PORT"]="8889"` in Python, or 

`set WEBRTC_PORT=8889`   from cmd.exe

**Comment by leehuoshi** [comment]
@ssheorey 
Thank you for your reply!! 
but still can't modify specificly ip or port. 
Maybe I have misunderstood the way you provided, the following is the method I tested.
i try to use:
1. append to draw_webrtc.py os.environ["WEBRTC_PORT"]="8889" and cmd set WEBRTC_PORT=8889.

this is my modify code 
-------------- code context -------------- 
import open3d as o3d
import os
os.environ["WEBRTC_PORT"]="8889"

if __name__ == "__main__":
    os.environ["WEBRTC_PORT"]="8889"
    o3d.visualization.webrtc_server.enable_webrtc()
    os.environ["WEBRTC_PORT"]="8889"
    cube_red = o3d.geometry.TriangleMesh.create_box(1, 2, 4)
    cube_red.compute_vertex_normals()
    cube_red.paint_uniform_color((1.0, 0.0, 0.0))
    o3d.visualization.draw(cube_red)
-------------- code context -------------- 

-------------- cmd command -------------- 
WEBRTC_IP=127.0.0.1 WEBRTC_PORT=8889 python ./draw_webrtc.py
--------------  cmd command -------------- 

Final_result==> 
[Open3D INFO] Set WEBRTC_STUN_SERVER environment variable add a customized WebRTC STUN server.
[Open3D INFO] WebRTC HTTP server handshake mode enabled.
[Open3D INFO] Open3D WebVisualizer is serving at http://localhost:8888.
[Open3D INFO] Set WEBRTC_IP and WEBRTC_PORT environment variable to customize the HTTP server address.

**Comment by ssheorey** [comment]
Hi @leehuoshi please set the environment variables **before** importing Open3D.

**Comment by leehuoshi** [comment]
> Hi @leehuoshi please set the environment variables **before** importing Open3D.

I'm very much obliged to you!! effective method!

**Comment by FishWoWater** [comment]
@ssheorey Hi, if the client and server are in the same LAN, is there any way to get rid of the STUN server? Seems that the default STUN server is very slow and the client lags. If I can use my local machine, even the server itself, as the STUN server it would be very efficient.
