### ISSUE TITLE
Windows devel release zips lack all Open3D resources

### ISSUE THREAD

**Issue by apriori** [isl-org/Open3D#5790]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Download https://github.com/isl-org/Open3D/releases/download/v0.16.0/open3d-devel-windows-amd64-0.16.0.zip

- Investigate Sources
- No 'resources' subdirectory found anywhere

### Error message

If you write a sample app using `open3d::visualization::gui::Application::GetInstance().Initialize()` you will encounter "Resource directory does not have Open3D resources" error. The [source](https://github.com/isl-org/Open3D/blob/c3dfcbdc8d7cdf5603367b783b6d4a43fc934bd5/cpp/open3d/visualization/gui/Application.cpp#L292) reveals that a bunch of files are expected inside the resources directory, none of which are part of the mentioned zip.

### Open3D, Python and System information

```markdown
Windows 10, with Visual Studio 2022
```

### Additional information

It seems that all essential filament resources are missing in the devel release packages for windows.

**Comment by ssheorey** [comment]
Resources are not packaged as part of devel packages on any platform currently. @errissa any thoughts on what's a good way to do this?

**Comment by Kin-Zhang** [comment]
`Resource directory does not have Open3D resources`

I also met this issue,

platform:
- Ubuntu 20.04
- Open3D 0.16.0
- C++
