### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [isl-org/Open3D#5795]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

💭 Would you like to [wrap any pointers](https://github.com/isl-org/Open3D/blob/c52ce0aa7ba379b332bbe373a2eee80d429f1c1f/cpp/pybind/visualization/rendering/rendering.cpp#L49 "Update candidate: PyOffscreenRenderer class") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

### Steps to reproduce the bug

```python
Allocate memory in special ways
```

### Expected behavior

Releasing resources in proper ways

### Open3D, Python and System information

```markdown
See also the referenced source code.
```

**Comment by ssheorey** [comment]
HI @elfring please provide code that results in unwanted behavior, or advice from code analysis tools. The linked code looks good, with resources being released properly in the destructor. Re-open issue if required.

**Comment by elfring** [comment]
:thought_balloon: Would you become interested to [apply C++ Core Guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r11-avoid-calling-new-and-delete-explicitly "R.11: Avoid calling new and delete explicitly") for any more software components?

**Comment by ssheorey** [comment]
Hi @elfring please submit a PR for review with the specific change you would like.
