### ISSUE TITLE
Convert Uint8 image to float32 get all 0 array data.

### ISSUE THREAD

**Issue by zhixiongzuo** [isl-org/Open3D#5830]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I want to convert uint8 image to float32 image for tsdf, I use following code for converting ,but it didn't work. 
```
I = o3d.t.io.read_image("./0000.jpg")
I2 = I.to(o3d.core.Dtype.Float32)
I : Image[size={2160,3840}, channels=3, UInt8, CPU:0]
I2 : Image[size={2160,3840}, channels=3, Float32, CPU:0]
np.unique(I2) == 0
```
In I2 image data array, there are all zeros.
I have tested on windowds/ubuntu 、cpu/cuda、open3d version 0.15.1/0.15.2 ，so it's my callback probem or IPP/kenel failed to copy data？

**Comment by yxlao** [comment]
@zhixiongzuo , could you share the `.jpg` file?

**Comment by zhixiongzuo** [comment]
Actually it's not the problem with jpg file, I test on "open3d_data/extract/JuneauImage/JuneauImage.jpg" with the same problem, which download on my pc from "o3d.data.JuneauImage()".
