### ISSUE TITLE
o3d.visualisation.draw_geometries not working with docker 

### ISSUE THREAD

**Issue by chwu-rwth** [isl-org/Open3D#5839]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I am using flask framework to allow the user to input parameters into the functions and used draw_geometries to visualize the outcome, everything works fine when i run the flask app. 
However, when i build the docker image and run the container, the visualization window doesn't appear. 
Any idea on how to solve this issue? 

```
@app.route('/run', methods=['GET', 'POST']) \\
def run():
    if request.method == "POST":
        input_path="pointclouds/"
        dataname="cst1_segm.pcd"
        pcd = o3d.io.read_point_cloud(input_path+dataname)
        #some code
        o3d.visualization.draw_geometries([pcd], width=1800, height=900, left = 50, top =100)
        return render_template("run.html")
```

**Comment by ssheorey** [comment]
HI @chwu-rwth please follow the docker documentation - note that the container needs access to the GPU, or you have to use CPU rendering. Both need configuration. Also, please use the new API (draw function).

http://www.open3d.org/docs/latest/docker.html
