### ISSUE TITLE
argument problem with enable_sun_light 

### ISSUE THREAD

**Issue by larszod** [isl-org/Open3D#5850]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

Function "enable_sun_light" does not accept boolean input

Version is 1.6.0

### Steps to reproduce the bug

```python
import open3d as o3d

o3d.visualization.rendering.Scene.enable_sun_light(True)
```

### Error message

Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.1.1 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 8.1.1
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32

    o3d.visualization.rendering.Scene.enable_sun_light(True)
TypeError: enable_sun_light(): incompatible function arguments. The following argument types are supported:
    1. (self: open3d.cpu.pybind.visualization.rendering.Scene, arg0: bool) -> None
Invoked with: True

### Expected behavior

enable_sun_light should return None

### Open3D, Python and System information

```markdown
- Operating system:  Windows 10 64-bit
- Python version: Python 3.9.5 / output from `import sys; print(sys.version)` 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
- Open3D version: output from python: `print(open3d.__version__)` 0.16.0
- System architecture: Not sure x86 / arm64 / apple-silicon / jetson / rpi
- Is this a remote workstation?: no
- How did you install Open3D?: pip /pycharm
- Compiler version (if built from source):
```

**Comment by ssheorey** [comment]
We need an object of the `o3d.visualization.rendering.Scene` class to be created before calling it's function. It is not a static function that can be called on a class. See examples of use here:

https://github.com/isl-org/Open3D/blob/5efea1ed1482055a9babb2c746f5cea7cf4473bf/examples/python/visualization/add_geometry.py#L58-L67
