### ISSUE TITLE
Request for minimal oriented bounding box for a given point cloud

### ISSUE THREAD

**Issue by ligerlac** [isl-org/Open3D#5856]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Proposed new feature or change

There are currently two functions that calculate a bounding box for a given point cloud:
`PointCloud.get_axis_aligned_bounding_box()` calculates the minimum axis-aligned bounding box w.r.t. to the lab frame, and `PointCloud.get_oriented_bounding_box()` calculates the minimum axis-aligned-bounding box w.r.t. to the coordinate system of the point cloud. Here, the coordinate system of the point cloud is determined via PCA. However, this is not necessarily the smallest bounding box of the point cloud. Other libraries already provide the smallest bounding box of a point cloud and it seems some Open3D users request it as well.

### References

previous discussion: [https://github.com/isl-org/Open3D/issues/5417](https://github.com/isl-org/Open3D/issues/5417)
Wikipedia about bounding boxes: [https://en.wikipedia.org/wiki/Minimum_bounding_box](https://en.wikipedia.org/wiki/Minimum_bounding_box)
implementation in different library: [https://github.com/compas-dev/compas/blob/main/src/compas/geometry/bbox/bbox_numpy.py](https://github.com/compas-dev/compas/blob/main/src/compas/geometry/bbox/bbox_numpy.py)

**Comment by ssheorey** [comment]
Closed by PR #5857 
Thanks @ligerlac !

**Comment by elun15** [comment]
Thanks so much @ligerlac !!! I tried the new version of o3d with the new feature and it works perfectly :D
