### ISSUE TITLE
RayCasting: How to get absolute coordinates from barycentric coordinates

### ISSUE THREAD

**Issue by GasparPizarro** [isl-org/Open3D#5858]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

The documentation on [ray casting](http://www.open3d.org/docs/latest/tutorial/geometry/ray_casting.html) says the `primitive_uvs` key from [cast_rays](http://www.open3d.org/docs/latest/python_api/open3d.t.geometry.RaycastingScene.html?highlight=raycastingscene#open3d.t.geometry.RaycastingScene.cast_rays) is of `{.., 2} shape. However, according to [Wikipedia](https://en.wikipedia.org/wiki/Barycentric_coordinate_system) you need 3 weights to get the absolute coordinates of the intersection point. How, then, can I get the absolute coordinates of the intersection point of the rays?

**Comment by benjaminum** [comment]
You need to convert the uv coordinates to barycentric coordinates.
`X_hit = (1-u-v) X_1 + u X_2 + v X_3`.

cast_rays also gives you the hit distance `t_hit`, which gives you the hit point as `X_hit = ray_origin + t_hit ray_dir`

**Comment by charlesmelby** [comment]
@GasparPizarro 
This is a convention and it would be helpful if this were included in the documentation!
http://www.open3d.org/docs/latest/python_api/open3d.t.geometry.RaycastingScene.html#open3d.t.geometry.RaycastingScene.cast_rays
