### ISSUE TITLE
Color info lost if read a PCD file(with rgb) and then save it

### ISSUE THREAD

**Issue by LeoWang014** [isl-org/Open3D#5860]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

I use Opend3D(for Python) to visualize PCD file. The file is colored point cloud. 
I read the file by calling open3d.io.read_point_cloud. And then i save the file by calling open3d.io.write_point_cloud. Then I find the RGB info is lost (e.g. origin is 774, now is 0).

### Steps to reproduce the bug

```python
import open3d as o3d


pcd = o3d.io.read_point_cloud("./1.pcd")
o3d.io.write_point_cloud("2.pcd", pcd, write_ascii=True)
```

### Error message

No errors

### Expected behavior

RGB values are lost(almost 0 for all).

### Open3D, Python and System information

```markdown
- Operating system: Windows 10 64-bit
- Python version: Python 3.7.6
- Open3D version: 0.16.0
- System architecture: x86
- Is this a remote workstation?: no
- How did you install Open3D?: pip
- Compiler version (if built from source): gcc 7.5
```

### Additional information

I debug the library code. The bug is due to function "ConvertRGBToFloat" called in WritePCDData.
"
     float value;
    memcpy(&value, rgba, 4);
"
"float value" should be replaced by "int value"

**Comment by ssheorey** [comment]
Hi @LeoWang014 can you provide test data (pcd with color)? I cannot reproduce this with the Open3D test pcd point cloud `fragment.pcd`.

**Comment by ssheorey** [comment]
Please reopen if you have test data for us to reproduce this issue.
