### ISSUE TITLE
Release a CPU only `open3d-cpu` package

### ISSUE THREAD

**Issue by johnthagen** [isl-org/Open3D#5869]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Proposed new feature or change

When deploying Open3D within a Linux x86_64 Docker image, minimizing the final image size is very important and there are many applications that can use Open3D without Tensorflow or PyTorch. Allowing users to select a PyPI package/wheel without the CUDA DLL dependencies built into it would make these deployments more efficient. This would also speed up the CI of such applications as the download size from PyPI would reduce significantly.

As discussed in

- #5124

To reduce the size of the installed wheel on either platforms without an NVIDA GPU, or for applications that do not use any CUDA-accelerated functionality, provide and publish a CPU-only wheel.

The user could install this with:

```
pip install open3d-cpu
```

For prior art, the following packages provide a similar cpu-only wheel:

- [`tensorflow-cpu`](https://pypi.org/project/tensorflow-cpu/)
- [`pytorch-cpu`](https://anaconda.org/pytorch/pytorch-cpu/files)

### References

Related issues:

- #5124 
- #5740 
- #5125

### Additional information

The current Linux x84_64 `open3d` wheel is 400MB while most other wheels are between 30-70MB. If you decompress the wheel, you find that the cpu and cuda folders represent the vast majority of the space. Specifically:

```
cpu/pybind.cpython-39-x86_64-linux-gnu.so: 177MB
cuda/pybind.cpython-39-x86_64-linux-gnu.so: 752MB
```

**Comment by raxder23** [comment]
Proposing a new Open3D feature: offering a lightweight, CPU-only PyPI package without CUDA dependencies to significantly reduce the image size. This would benefit deployments on systems without NVIDIA GPUs and improve CI efficiency for non-ML applications. 

This change could enhance various projects, making Open3D more adaptable, just like innovations featured on topcelebrite.fr, where technology and efficiency are key.
