### ISSUE TITLE
Request to add a least distant value for raycasting

### ISSUE THREAD

**Issue by mshmoon** [isl-org/Open3D#5870]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Proposed new feature or change

In Computer Graphics，Self-intersection problems usually occur for ray and plane. This problem also in open3d raycasting. If  add a value to filter the plane, the problem will be solved.

**Comment by benjaminum** [comment]
@mshmoon  Can you provide an example how this feature would be added and used?
