### ISSUE TITLE
"Open3D WARNING" Colab

### ISSUE THREAD

**Issue by micdist** [isl-org/Open3D#5872]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Steps to reproduce the issue

!pip install open3d
!pip install laspy

import numpy as np
import open3d as o3d
import laspy

//read my .las file
pc1 = laspy.read('/content/drive/MyDrive/lasFolder/lasCloud.las')

//build np array from cloud 
xyz = np.vstack((pc1.x, pc1.y, pc1.z)).transpose()

//convert np array to pointcloud
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(xyz)

//here's the bit that gives error
o3d.visualization.draw_geometries([pcd])

### Error message

```shell
[Open3D WARNING] GLFW Error: X11: The DISPLAY environment variable is missing0;m
[Open3D WARNING] Failed to initialize GLFW0;m
[Open3D WARNING] [DrawGeometries] Failed creating OpenGL window.0;m
```

### Open3D, Python and System information

```markdown
I am using a free Colab instance with GPU.
```

**Comment by ssheorey** [comment]
Hi @micdist please use `draw_plotly` for Collab - that platform has GPU access limitations

http://www.open3d.org/docs/latest/tutorial/visualization/draw_plotly.html?highlight=plotly
