### ISSUE TITLE
Is it possible to do 3d reconstruction from a Monocular camera input?

### ISSUE THREAD

**Issue by danielj-genesis** [isl-org/Open3D#5891]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

My goal is to do 3d reconstruction with any regular camera, ORB-SLAM [https://github.com/raulmur/ORB_SLAM2](url) produces a point cloud without the use of depth. Is this something I can do with Open3D or is RGBD a strict requirement for single camera based reconstruction?

ORB-SLAM2 seems to be able to do it but I doesn't look like the dense reconstruction is avaible 
![image](https://user-images.githubusercontent.com/96253918/216787013-cf0cf9ea-a30b-4bd7-aa02-7c298f0e3a1a.png)

**Comment by ssheorey** [comment]
Hi @danielj-genesis this feature is out of scope for Open3D - please check out the excellent COLMAP and AliceVision / Meshroom libraries.
