### ISSUE TITLE
Python Merging open3d.cpu.pybind.t.geometry.TriangleMesh Objects TypeError

### ISSUE THREAD

**Issue by halil-karabacak** [isl-org/Open3D#5895]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

Hi,

I am simply trying to merge two TriangleMesh objects using open3d. My code flow is as:

In a for loop, I am reading a TriangleMesh in each iteration. I am making the first iteration's TriangleMesh object base, like I am trying to add all other TriangleMesh objects over the base. Also added a simple version of my script. 
I am using o3d.t.geometry.TriangleMesh(), not o3d.geometry.TriangleMesh() because I am testing Multi-Scale ICP.

How can I mergte these two objects? 

Thanks.

### Steps to reproduce the bug

```python
triangle_msh_generalized_icp = o3d.t.io.read_triangle_mesh(".../alignment-tests-python/only_ransac/orig_mesh" + str(i) + ".ply")

base = o3d.t.geometry.TriangleMesh()
  

if i == 0:
    base = triangle_msh_generalized_icp 

else:
    # some operations to find alignment
    # transforming the TriangleMesh
    # trying to merge new mesh to the model

    base += triangle_msh_generalized_icp
```

### Error message

Traceback (most recent call last):
  File "...\alignment-tests-python\alignment-test-copy.py", line 342, in <module>
    base += triangle_msh_generalized_icp
TypeError: unsupported operand type(s) for +=: 'open3d.cpu.pybind.t.geometry.TriangleMesh' and 'open3d.cpu.pybind.t.geometry.TriangleMesh'

### Expected behavior

I expeceted += operation to merge 2 TriangleMesh objects.

### Open3D, Python and System information

```markdown
- Operating system: Windows 10 64-bit
- Python version: Python 3.8
- Open3D version: 0.16.0
- System architecture: x86
- Is this a remote workstation?: no
- How did you install Open3D?: pip
```

**Comment by ssheorey** [comment]
You are looking for `boolean_union`

http://www.open3d.org/docs/latest/python_api/open3d.t.geometry.TriangleMesh.html#open3d.t.geometry.TriangleMesh.boolean_union

**Comment by halil-karabacak** [comment]
Thanks!

**Comment by halil-karabacak** [comment]
May I ask what is the expected time for merging process for `boolean_union` to mesh almost 1M faced 2 TriangleMesh objects, it either stuck or takes too long in my pc.
