### ISSUE TITLE
How to retrieve the extrinsic camera parameters?

### ISSUE THREAD

**Issue by domattioli** [isl-org/Open3D#5899]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I've read this [documentation ](http://www.open3d.org/docs/release/python_api/open3d.visualization.rendering.Camera.html?highlight=camera#open3d.visualization.rendering.Camera)and to my novice eye, it appears that only the intrinsic parameters are get-able via `get_projection_matrix`. Do any of the other methods produce the extrinsic parameters? If not, which Open3D documentation should I be looking at?

None of the parameters listed [here](http://www.open3d.org/docs/release/python_api/open3d.camera.html) work for my object:
```
<class 'open3d.cpu.pybind.visualization.rendering.Camera'>
'open3d.cpu.pybind.visualization.rendering.Camera' object has no attribute 'PinholeCameraIntrinsicParameters'
```

**Comment by ssheorey** [comment]
You are looking for `get_model_matrix()`
http://www.open3d.org/docs/release/python_api/open3d.visualization.rendering.Camera.html?highlight=camera#open3d.visualization.rendering.Camera.get_model_matrix

**Comment by ted8201** [comment]
See this demo [load and save view point](https://github.com/isl-org/Open3D/blob/master/examples/python/visualization/load_save_viewpoint.py). And this tutorial would help you to understand how to customize visualization in Open3d's way.
