### ISSUE TITLE
Request to make Open3D be compatible with Ceres-solver

### ISSUE THREAD

**Issue by gitouni** [isl-org/Open3D#5905]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Proposed new feature or change

Incompatible with Ceres-solver.
Dear Contributors of Open3D:

Please note the issue https://github.com/ceres-solver/ceres-solver/issues/945. Compiling Open3D and ceres-solver together causes compilation errors. I know this is not a problem with Open3D itself, but I sincerely hope you can solve it. The problem may be that some CMake settings conflict with Ceres-solver, but I'm not sure as a beginner.

### Additional information

# Environment
Ubuntu 20.04
ceres 2.1.0
Open3D 0.16.0
CMake 3.25.0
gcc 9.4.0

**Comment by ssheorey** [comment]
Hi @gitouni Please add information on how you built Open3D (or which binary archive you used).

A quick google search for the problem in the linked issue leads to this:
https://kumasento.github.io/2020-06-12-glog-gflags-and-c-abi/

i.e. please make sure all your libraries use the same cxx11_abi. Open3D can be built with / is distributed with either.

**Comment by gitouni** [comment]
I'm truly grateful for your instant reply.

I downloaded Open3D through git clone and installed it using CMake:
```sh
cd Open3D
mkdir build && cd build 
cmake \
    -DBUILD_SHARED_LIBS=ON \
    -DPYTHON_EXECUTABLE=$(which python3) \
    -DBUILD_CUDA_MODULE=ON \
    -DGLIBCXX_USE_CXX11_ABI=ON \
    -DBUILD_LIBREALSENSE=ON  \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr/local \
    -DBUILD_PYTORCH_OPS=OFF \
    -DBUILD_TENSORFLOW_OPS=OFF \
    -DBUNDLE_OPEN3D_ML=OFF \
    -DOPEN3D_ML_ROOT=${replace with own Open3D-ML path} \
    ../
make -j4
sudo make install 
```
I have checked the web you showed but there isn't a `-D_GLIBCXX_USE_CXX11_ABI=0` option among glog CMake configs.

> Hi @gitouni Please add information on how you built Open3D (or which binary archive you used).
> 
> A quick google search for the problem in the linked issue leads to this: https://kumasento.github.io/2020-06-12-glog-gflags-and-c-abi/
> 
> i.e. please make sure all your libraries use the same cxx11_abi. Open3D can be built with / is distributed with either.

In fact, after I reinstalled Open3D and ceres-solver, the issue disappeared. It is really confusing, I would like to close this issue until I can reproduce it.
