### ISSUE TITLE
For TriangleMesh triangle_material_ids_ do not relate to the materials_

### ISSUE THREAD

**Issue by dbs4261** [isl-org/Open3D#5924]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

The triangle_material_ids_ vector contain indices for which texture should be applied. However because materials are stored in an unordered_map, the indices cannot be used to access the corresponding material. It would be better to store a vector<pair<string, Material>> that way it is indexable, but materials could still be accessed by name using find with a lambda comparing names.

### Steps to reproduce the bug

```python
`class TriangleMesh {
    ...
    std::unordered_map<std::string, Material> materials_;
    /// List of material ids.
    std::vector<int> triangle_material_ids_;
    /// Textures of the image.
    std::vector<Image> textures_;
}`
By examining the values with a debugger, the triangle_material_ids_ match up with the textures_ but there is no mechanism for accessing the material associated with it.
```

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 22.04
- Python version: Python 3.11
- Open3D version: bbae9e31fefac1c2fe04759d30b81c30d927dbeb
- System architecture: x86
- Is this a remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): gcc 11.3
```

**Comment by johnthagen** [comment]
For the Python 3.11 support part, track

- #5620

**Comment by errissa** [comment]
@dbs4261 Thank for both reporting this issue and for the PR to fix it!
