### ISSUE TITLE
Allow multiple simultaneous queries on kdtree

### ISSUE THREAD

**Issue by apriori** [isl-org/Open3D#5941]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Proposed new feature or change

Given general looping is really slow in python, I wonder why the flann api exported does not allow querying for entire point sets in one go. E.g. [search_hybrid_vector_3d](http://www.open3d.org/docs/latest/python_api/open3d.geometry.KDTreeFlann.html#open3d.geometry.KDTreeFlann.search_hybrid_vector_3d) should be extended to not only accept a single point, but a nx3 or 3xn directly. For each query point one could also then return appropriately sized ndarrays for the return values.

**Comment by elientumba2019** [comment]
Hello, Is there any hope that this feature will be implemented in the near future? Thank you

**Comment by benjaminum** [comment]
The neighbor search module can do that.

```python
import open3d as o3d
import numpy as np

points = np.random.rand(1000,3)
nns = o3d.core.nns.NearestNeighborSearch(points)
nns.hybrid_index()
ans = nns.hybrid_search(np.random.rand(10,3), radius=0.1, max_knn=10)
```
Unfortunately, it is not documented.

**Comment by elientumba2019** [comment]
Thank you @benjaminum . In terms of performance, how does this one compare to the kdtree search ?

**Comment by benjaminum** [comment]
This should be definitely faster than querying one by one.
