### ISSUE TITLE
filter_smooth_laplacian and simplify_vertex_clustering function losing texture

### ISSUE THREAD

**Issue by pangchunhei** [isl-org/Open3D#5944]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I have some obj file with texture, and I would like to simplify the mesh by using filter_smooth_laplacian and simplify_vertex_clustering function, but after I used the above function. It cannot show the texture of the file, but the mesh is optimized correctly. May I know how I should correct the code?

----------------------------------------------------------------------
import open3d as o3d

mesh_in = o3d.io.read_triangle_mesh('Tile_+5571_+5480.obj', True)

mesh_in.compute_vertex_normals()

voxel_size = max(mesh_in.get_max_bound() - mesh_in.get_min_bound()) / 320

print(f'voxel_size = {voxel_size:e}')

mesh_smp = mesh_in.simplify_vertex_clustering(
    voxel_size=voxel_size,
    contraction=o3d.geometry.SimplificationContraction.Average)

print(
    f'Simplified mesh has {len(mesh_smp.vertices)} vertices and {len(mesh_smp.triangles)} triangles'
)

mesh_out = mesh_smp.filter_smooth_laplacian(number_of_iterations=10)
mesh_out.compute_vertex_normals()

o3d.visualization.draw_geometries([mesh_out])

o3d.io.write_triangle_mesh("copy_of_crate.obj", mesh_out, write_triangle_uvs=True)

**Comment by guyuezuntinggithub** [comment]
because the number of face and vertex is already changed ,so the Correspondence of the mesh and the texture of obj has changed too. you need recompute the correspondence

**Comment by pangchunhei** [comment]
Understood, may i know how to do it. As i am new to 3D programming, may i know any example?

My current obj file structure have a obj, mtl, and a jpg texture file.
