### ISSUE TITLE
ModuleNotFoundError: No module named 'open3d.geometry'

### ISSUE THREAD

**Issue by Astroworld97** [isl-org/Open3D#5949]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

I am trying to use Open3d for the Azure Kinect SDK. There are some example Python files I want to run from https://github.com/ibaiGorordo/pyKinectAzure and they require Open3d. I get the following error: ModuleNotFoundError: No module named 'open3d.geometry', even though Python imports Open3d. I checked the latest version of the repo and it doesn't seem to have the libraries! All of them, including geometry, are present in the cpp version but not in the python version. It's as if they were erased. Any help would be appreciated.

### Steps to reproduce the bug

```python
import numpy as np
import cv2
import open3d as o3d
import open3d.geometry as geometry
```

### Error message

  File "examplePointCloud.py", line 3, in <module>
    import pykinect_azure as pykinect
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python38\lib\site-packages\pykinect_azure\__init__.py", line 1, in <module>
    from .pykinect import *
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python38\lib\site-packages\pykinect_azure\pykinect.py", line 3, in <module>
    from pykinect_azure.k4a import _k4a, Device, default_configuration
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python38\lib\site-packages\pykinect_azure\k4a\__init__.py", line 2, in <module>
    from .capture import Capture
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python38\lib\site-packages\pykinect_azure\k4a\capture.py", line 6, in <module>
    from pykinect_azure.utils.postProcessing import smooth_depth_image
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python38\lib\site-packages\pykinect_azure\utils\__init__.py", line 3, in <module>
    from .plot3dUtils import Open3dVisualizer
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python38\lib\site-packages\pykinect_azure\utils\plot3dUtils.py", line 4, in <module>
    import open3d.geometry as geometry
ModuleNotFoundError: No module named 'open3d.geometry'

### Expected behavior

For it to keep running, and find open3d.geometry

### Open3D, Python and System information

```markdown
- Operating system: Windows 10 64-bit
- Python version: Python 3.8 
- Open3D version: output from python: AttributeError: module 'open3d' has no attribute '__version__' (although it does import open3d)
- System architecture: x64
- Is this a remote workstation?:  no
- How did you install Open3D?: pip
- Compiler version (if built from source): gcc 7.5 / clang 7.0
```

**Comment by ssheorey** [comment]
What version did you install? What was the install command?
`import open3d.geometry as geometry` will only work in master / latest. (v0.17+) For older versions you have to do:
```
import open3d as o3d
pcd = o3d.geometry.PointCloud()
...
```

Note that most of Open3D is in C++ with Python wrappers, so you won't find Python files for geometry.
