### ISSUE TITLE
How to clear geometry when non blocking visualize?

### ISSUE THREAD

**Issue by jinfagang** [isl-org/Open3D#5956]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

How to clear geometry when non blocking visualize?

I don;t have add_geometry in the first frame ,every single frame is different mesh, how to clear previous one?

**Comment by ssheorey** [comment]
[remove_geometry()](http://www.open3d.org/docs/latest/python_api/open3d.visualization.Visualizer.html?highlight=remove_geometry#open3d.visualization.Visualizer.remove_geometry)
