### ISSUE TITLE
ICP in global registration fails because of missing normal vectors

### ISSUE THREAD

**Issue by kartikanrp** [isl-org/Open3D#5958]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hello, 

**Describe the bug**
I am using the [global registration](http://www.open3d.org/docs/release/tutorial/pipelines/global_registration.html) from your documentation. I have done everything as it is described in the documentation. Everything was running normal unti the ICP registration stage. I always receive the following error message:

`result_icp = refine_registration(source, target, source_fpfh, target_fpfh,
                                 voxel_size)
print(result_icp)
draw_registration_result(source, target, result_icp.transformation)`

> :: Point-to-plane ICP registration is applied on original point
>    clouds to refine the alignment. This time we use a strict
>    distance threshold 0.020.
> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> ~\AppData\Local\Temp\ipykernel_14020\901390885.py in <module>
> ----> 1 result_icp = refine_registration(source, target, source_fpfh, target_fpfh,
>       2                                  voxel_size)
>       3 print(result_icp)
>       4 draw_registration_result(source, target, result_icp.transformation)
> 
> ~\AppData\Local\Temp\ipykernel_14020\4130089198.py in refine_registration(source, target, source_fpfh, target_fpfh, voxel_size)
>       4     print("   clouds to refine the alignment. This time we use a strict")
>       5     print("   distance threshold %.3f." % distance_threshold)
> ----> 6     result = o3d.pipelines.registration.registration_icp(
>       7         source, target, distance_threshold, result_ransac.transformation,
>       8         o3d.pipelines.registration.TransformationEstimationPointToPlane())
> 
> RuntimeError: [Open3D Error] (class open3d::pipelines::registration::RegistrationResult __cdecl open3d::pipelines::registration::RegistrationICP(const class open3d::geometry::PointCloud &,const class open3d::geometry::PointCloud &,double,const class Eigen::Matrix<double,4,4,0,4,4> &,const class open3d::pipelines::registration::TransformationEstimation &,const class open3d::pipelines::registration::ICPConvergenceCriteria &)) D:\a\Open3D\Open3D\cpp\open3d\pipelines\registration\Registration.cpp:147: TransformationEstimationPointToPlane and TransformationEstimationColoredICP require pre-computed normal vectors for target PointCloud.

**Environment (please complete the following information):**

Operating system: Windows 11 64-bit
Python version: Python 3.10.10
Open3D version: 0.16.0
Is this remote workstation?: no
How did you install Open3D?: pip (via package management in Jupyter)

Thank you in advance for your help.
Yours sincerely,

**Comment by kartikanrp** [comment]
<img width="313" alt="image" src="https://user-images.githubusercontent.com/55693085/222037032-d117cf3e-2d97-488d-983d-4fb3e9eaf428.png">

This is the result after global registration and RANSAC. The source point cloud (pipe in yellow) has been registered with the target point cloud (pipes in blue).

**Comment by Risingabhi** [comment]
to solve this try 
pcd.estimate_normals() above the line where you are passing source , target

**Comment by kartikanrp** [comment]
Thank you, it is solved now
