### ISSUE TITLE
how to reduce the area of gray pixels in the capturing frames got by depth camera.

### ISSUE THREAD

**Issue by MysteryNull** [isl-org/Open3D#5960]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Capturing frames without too many gray pixels is recommended for the good reconstruction quality.So how to reduce the area of gray pixels in the capturing frames got by depth camera.

**Comment by ssheorey** [comment]
That's a question for the camera manufacturer :-)

Generally, stay within the depth camera range limits (e.g. ~50cm to 3m for Intel RealSense D400 series) and avoid reflective or transparent surfaces.
