### ISSUE TITLE
Where can I get the source code of the function "get_oriented_bounding_box"? 

### ISSUE THREAD

**Issue by MysteryNull** [isl-org/Open3D#5974]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Where can I get the source code of the function "get_oriented_bounding_box"? Thank you!

**Comment by ssheorey** [comment]
Functionality us implemented in C++ - switch from _ to CamelCase to get the C++ function name, then search in the C++ docs, or on github itself for the source code. e.g. here are the search results for [GetOrientedBoundingBox](https://github.com/search?q=repo%3Aisl-org%2FOpen3D%20GetOrientedBoundingBox&type=code).
