### ISSUE TITLE
How to check if Open3d is using cuda/gpu

### ISSUE THREAD

**Issue by koliber31** [isl-org/Open3D#5976]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hello everyone
I have used this tutorial http://www.open3d.org/docs/latest/tutorial/Advanced/multiway_registration.html to merge multiple point clouds. It works but take a lot of time to merge (6h in case of 150 pcds). I have seen that Open3d supports cuda and gpu acceleration but i don't know how to check if I'm using it. I tried 
```
import open3d as o3d
o3d.cuda.is_available()
```
But i get an error AttributeError: module 'open3d.cuda' has no attribute 'is_available'. 
I'm using open3d 0.16.0 and cuda version 12.1 and i have output from commands nvidia-smi and nvcc -V.

**Comment by gobanana520** [comment]
use `o3d.core.cuda.is_available()` to check if cuda is available.

**Comment by koliber31** [comment]
> use `o3d.core.cuda.is_available()` to check if cuda is available.
Thank you!
When i did `print(o3d.core.cuda.is_available())` i got True so I assume that it's available. I have one more question, does it work "out of the box" or do i have to initialize it somehow?

**Comment by gobanana520** [comment]
> > use `o3d.core.cuda.is_available()` to check if cuda is available.
> 
> Thank you! When i did `print(o3d.core.cuda.is_available())` i got True so I assume that it's available. I have one more question, does it work "out of the box" or do i have to initialize it somehow?

I installed the Open3D with `pip install open3d`, and this package is compiled with CUDA support, but if you want to compile it mannually, be sure to compile with cuda support. I don't think we need to initialize the cuda functions. Just similar as pytorch, we need to use o3d.t.xxxx to create 'tensor' objects, and they are created in CPU by default, remember to specify which 'device' to use (`device_o3d = o3d.core.Device("cuda:0")`). You could find more examples in the [Tutorial](http://www.open3d.org/docs/release/tutorial/t_pipelines/index.html).
