### ISSUE TITLE
Summarize the question. (e.g., "How to run reconstruction system with RealSense D435i? ")

### ISSUE THREAD

**Issue by hjy94wo777** [isl-org/Open3D#5979]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi,
    I want to rotate the 3D point cloud and project it to rgbd image but I find that they use 2 different types of point cloud. One is open3d.cuda.pybind.geometry.PointCloud' which has no attribute 'project_to_rgbd_image' and the another is 'open3d.cuda.pybind.t.geometry.PointCloud' which has no attribute 'get_rotation_matrix_from_xyz'. So my question is how can I use both rotation transformation and projection to rgbd image function usnig open3d

**Comment by ssheorey** [comment]
You can convert between tensor (t namespace) and legacy (Eigen based) data types. Each Tensor based data type has `to_legacy()` and `from_legacy()` methods.
