### ISSUE TITLE
Error importing open3d in apple M1

### ISSUE THREAD

**Issue by pratt3000** [isl-org/Open3D#5986]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

#### I first installed open3d:
```
pip install open3d
```

I am running python 3.9 in a conda environment. I get the following error.

### Error message

```shell
from open3d.cpu.pybind import (camera, data, geometry, io, pipelines,
ImportError: dlopen(/Users/pratt/anaconda3/envs/debug/lib/python3.9/site-packages/open3d/cpu/pybind.cpython-39-darwin.so, 0x0002): Library not loaded: /opt/homebrew/opt/libomp/lib/libomp.dylib
  Referenced from: <0718BFA0-280F-3029-A780-D45CF6BB9F0D> /Users/pratt/anaconda3/envs/debug/lib/python3.9/site-packages/open3d/cpu/pybind.cpython-39-darwin.so
  Reason: tried: '/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file, not in dyld cache)
```

### Open3D, Python and System information

```markdown
- Operating system: macOS 13.2.1
- Python version: Python 3.9
- System architecture: apple M1
- Is this a remote workstation?: no
- How did you install Open3D?: pip
```

**Comment by pratt3000** [comment]
Okay so I managed to resolve it after much deliberation. 

I reverted it back to an older version of open3d (0.14.1) and things are working now. Rest of my config is same as described above.

**Comment by MenxLi** [comment]
just install openmp: `brew install libomp`

**Comment by cwreynolds** [comment]
I ran into the same issue when I first installed Open3D on my Mac in March. It is an annoying “speed bump” since the rest of Open3D's installation process is so simple and streamlined. 

Is it a packaging bug that `libomp` is not included in the installation? At least on macOS?
