### ISSUE TITLE
Pointcloud to 2D image projection issue

### ISSUE THREAD

**Issue by tan-may16** [isl-org/Open3D#5987]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi,

I am trying to project a pointcloud into an image plane using 'project_to_depth_image' and/or 'project_to_rgbd_image' method.
But I am getting the following error for some reason.

Error:
AttributeError: 'open3d.cuda.pybind.t.geometry.PointCloud' object has no attribute 'project_to_depth_image'

I am using open3d 0.14.1 on Ubuntu 18.04.
I tried to run the sample example provided in the examples/python/geometry but I am facing the same issue. The only change from the example is that I am loading my own color and depth image. (I am able to visualize pointcoud).

Here's the code that I am using:

import open3d as o3d
import numpy as np
import matplotlib.pyplot as plt

if __name__ == '__main__':
    device = o3d.core.Device('CPU:0')
    # tum_data = o3d.data.SampleTUMRGBDImage()
    depth = o3d.t.io.read_image("depth.png").to(device)
    color = o3d.t.io.read_image("color.png").to(device)

    intrinsic = o3d.core.Tensor([[535.4, 0, 320.1], [0, 539.2, 247.6],
                                 [0, 0, 1]])
    rgbd = o3d.t.geometry.RGBDImage(color, depth)

    pcd = o3d.t.geometry.PointCloud.create_from_rgbd_image(rgbd,
                                                           intrinsic,
                                                           depth_scale=5000.0,
                                                           depth_max=10.0)
    o3d.visualization.draw([pcd])
    rgbd_reproj = pcd.project_to_depth_image(640,
                                            480,
                                            intrinsic,
                                            depth_scale=5000.0,
                                            depth_max=10.0)

    fig, axs = plt.subplots(1, 2)
    axs[0].imshow(np.asarray(rgbd_reproj.color.to_legacy()))
    axs[1].imshow(np.asarray(rgbd_reproj.depth.to_legacy()))
    plt.show()

Thank you

**Comment by ssheorey** [comment]
Hi @tan-may16 your Open3D version is tool old for this function. Please use the latest Open3D (v0.17) and reopen if you still have this issue.
