### ISSUE TITLE
an example about how to change geometry::pointcloud to t::geometry::pointcloud based on C++?

### ISSUE THREAD

**Issue by guyuezuntinggithub** [isl-org/Open3D#5988]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Proposed new feature or change

hi guys! thanks for this great library!
Can you offer an example about how to change geometry::pointcloud to t::geometry::pointcloud based on C++?
thnks very much!

**Comment by ssheorey** [comment]
You can just use this function (`t::geometry::PointCloud::FromLegacy()`):
http://www.open3d.org/docs/latest/cpp_api/classopen3d_1_1t_1_1geometry_1_1_point_cloud.html#ac5ba5f301a1dab6a56d9a528f2d8107e

I don't see an example in the code, but it should be straightforward to use.

**Comment by guyuezuntinggithub** [comment]
> You can just use this function (`t::geometry::PointCloud::FromLegacy()`): http://www.open3d.org/docs/latest/cpp_api/classopen3d_1_1t_1_1geometry_1_1_point_cloud.html#ac5ba5f301a1dab6a56d9a528f2d8107e
> 
> I don't see an example in the code, but it should be straightforward to use.

very appreciate for your reply! I will try it soon.
