### ISSUE TITLE
Functions segment_plane  cluster_dbscan are too slow

### ISSUE THREAD

**Issue by mcmingchang** [isl-org/Open3D#5992]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Proposed new feature or change

Can these two functions support multi-cpu computing?
![微信图片_20230315105853](https://user-images.githubusercontent.com/37234299/225193845-a9c6ab25-c505-4494-99a8-ceb230a19453.png)

### References

none

### Additional information

none

**Comment by yuecideng** [comment]
Hi @mcmingchang , what is the version of Open3D? since 0.16.0, the `segment_plane` function is multi-threading. `cluster_dbscan` is not fully multi-threading currently in Open3D, but you can refer to this implementation: https://github.com/wangyiqiu/dbscan-python
