### ISSUE TITLE
How to combine couple point clouds using cuda

### ISSUE THREAD

**Issue by koliber31** [isl-org/Open3D#6002]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi
I want to merge couple point clouds using cuda. I found this tutorial http://www.open3d.org/docs/latest/tutorial/Advanced/multiway_registration.html which does something like that but is using CPU and works slow.
I found this tutorial http://www.open3d.org/docs/release/tutorial/t_pipelines/t_icp_registration.html#Point-to-Plane-ICP-Registration but author there is using only two pcds, so i changed it little bit but effect is just awful. There is my code: 

```
for i in range(1,30):
    
    source = o3d.t.io.read_point_cloud(f"/home/wze/Desktop/pcd_test_temp/new{i+1}.pcd")
    target = o3d.t.io.read_point_cloud(f"/home/wze/Desktop/pcd_test_temp/new{i}.pcd")


    source_cuda = source.cuda(0)
    target_cuda = target.cuda(0)

    target_cuda.estimate_normals()
    source_cuda.estimate_normals()


    registration_ms_icp = treg.multi_scale_icp(source_cuda, target_cuda,
                                            voxel_sizes, criteria_list,
                                            max_correspondence_distances,
                                            init_source_to_target, estimation)


    source_temp = source_cuda.clone()
    target_temp = target_cuda.clone()

    source_temp.transform(registration_ms_icp.transformation)
    pcds.append(source_temp.cpu().to_legacy())

o3d.visualization.draw_geometries(pcds[25:39],
                                zoom=0.4459,
                                front=[0.9288, -0.2951, -0.2242],
                                lookat=[1.6784, 2.0612, 1.4451],
                                up=[-0.3402, -0.9189, -0.1996])
```

When i do this on just two point clouds as author intended it works fine, but with more pcds it's just one big mess. I thought that if i will use source from previous step as target in next step it will work fine but it doesn't. There is effect of code above 

![Screenshot from 2023-03-16 14-20-56](https://user-images.githubusercontent.com/42122590/225629878-bab04dbe-3393-4f26-9d8c-e324b074c193.png)

It looks like it was starting to draw every next point cloud in the same place.

And there is one made with tutorial i mentioned:
![pcd_1z5](https://user-images.githubusercontent.com/42122590/225630329-144e524c-d49e-4b99-b702-f7c02118aec5.png)

This one is much better.

**Comment by ssheorey** [comment]
Hi @reyanshsolis can you take a look at this?

**Comment by reyanshsolis** [comment]
Hi @koliber31,
The transformation multiplication might be wrong, you may follow this example: https://github.com/isl-org/Open3D/blob/master/examples/cpp/TICPSequential.cpp [This is the implementation of this part of the release video https://youtu.be/pLCVCH7ypI4?t=57] In this example, a sequence of point-cloud data are combined by finding transformation using ICP. 
Now, direct ICP registration for combining output is not the best solution, but if you use multi-scale ICP, with decent parameters, it should do they job. 

Transformation Calculation from the above example for reference:
```cpp

            // Reads the pre-fetched and pre-processed pointcloud frames.
            auto source = pointclouds_device_[i].To(device_);
            auto target = pointclouds_device_[i + 1].To(device_);

            // Computes the transformation from pcd_[i] to pcd_[i + 1], for
            // `Frame to Frame Odometry`.
            auto result = MultiScaleICP(source, target, voxel_sizes_,
                                        criterias_, search_radius_,
                                        initial_transform, *estimation_);

            // `cumulative_transform` before update is from `i to 0`.
            // `result.transformation_` is from i to i + 1.
            // so, `cumulative_transform @ (result.transformation_).Inverse`
            // gives `transformation of [i + 1]th frame to 0` [reference or
            // initial] frame. So, pose of the ego-vehicle / sensor
            // till this frame w.r.t. the initial frame, or `global_pose`
            // or `frame to model transform` is given by `cumulative_transform.`
            cumulative_transform = cumulative_transform.Matmul(
                    t::geometry::InverseTransformation(
                            result.transformation_.Contiguous()));
                         
             cumulative_point_cloud += target.Transform(cumulative_transform);
```
Please feel free to continue the discussion if any doubt. 
Thanks

**Comment by gachiemchiep** [comment]
Hello @koliber31 

I am using similar api as you, but everytime I combined pointcloud an *Segmentation fault (core dumped)* error appeared. 
Which version of open3d are you using ? And how did you compile your open3d?
