### ISSUE TITLE
please add java bindings

### ISSUE THREAD

**Issue by sendreams** [isl-org/Open3D#6004]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Proposed new feature or change

only python bindings, please add the java bindings

### References

/

### Additional information

/

**Comment by ssheorey** [comment]
Hi @sendreams we don't have the expertise or bandwidth for this. If you or someone else is interested, I would suggest creating a new repo that uses Open3D as a dependency, builds the Open3D DLL and wraps it in Java bindings.
