### ISSUE TITLE
How to get surface/boundary points of pointcloud generated from a voxel grid ?

### ISSUE THREAD

**Issue by AmrElsersy** [isl-org/Open3D#6011]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi, 

I did voxel carving to generate a voxel grid of a specific shape, and I convert it to pointcloud by getting the origin of each voxel
the pointcloud:

https://user-images.githubusercontent.com/35613645/226154430-102a65e9-9026-40c4-ab0b-2dc46054a6e3.mp4

I want to get the surface points of the pointcloud, I tried "compute_boundary_points" function but didn't work, how can I get the surface/boundary points of the pointcloud ? I can do it with PCL concave functions to generate this:

![Screenshot from 2023-03-19 06-52-29](https://user-images.githubusercontent.com/35613645/226154422-d7420abe-6961-4941-9404-c750aed3d6ee.png)

But I need to do it using Open3D

**Comment by yuecideng** [comment]
Hi @AmrElsersy , I think you should use surface reconstruction algorithm to generate mesh for your point cloud, then using sampling functions like `sample_points_uniformly` or `sample_points_poisson_disk` to retrieve the surface point cloud.

**Comment by AmrElsersy** [comment]
Hi, @yuecideng , you mean functions like (`create_from_point_cloud_poisson`, `create_from_point_cloud_ball_pivoting`) ??? They assume that the pointcloud I have is a surface pointcloud, I get a mesh of vertices that is inside the mesh object and it was very wrong

Another way I tried is to get the convex hull of the pointcloud then using `sample_points_poisson_disk` .. It worked but giving me a convex surface not the exact surface, So I did the same way in PCL but to get the concave and it worked, but I need to do it without PCL

**Comment by yuecideng** [comment]
> Another way I tried is to get the convex hull of the pointcloud then using sample_points_poisson_disk .. It worked but giving me a convex surface not the exact surface, So I did the same way in PCL but to get the concave and it worked, but I need to do it without PCL

That's true. Open3D only implement the convex hull function based on qhull library (pcl also use qhull as well). So you may create a feature request issue for concave function adding, or contribute it to Open3D with reference of PCL's implementation.

**Comment by AmrElsersy** [comment]
My problem is that python pcl is hard to installed on any other PC

Is there any way to get the surface pointcloud other than python PCL ?? in python
I searched for python bindings for QHull but didn't found info about concave, only convex that I found... some people says to do something called marching cubes

@yuecideng  do you know any other way to do that in python ?

**Comment by yuecideng** [comment]
You can try the `trimesh` library with [`trimesh.voxel.ops.points_to_marching_cubes`](https://trimsh.org/trimesh.voxel.ops.html#trimesh.voxel.ops.points_to_marching_cubes).

**Comment by AmrElsersy** [comment]
Thanks :D

I also tried siket-image marching cubes and it worked !
https://gis.stackexchange.com/questions/143821/how-to-find-the-concave-hull-for-a-cloud-of-points-in-3d-space/338794#338794

**Comment by AmrElsersy** [comment]
Thanks :D

I also tried siket-image marching cubes and it worked !
https://gis.stackexchange.com/questions/143821/how-to-find-the-concave-hull-for-a-cloud-of-points-in-3d-space/338794#338794
