### ISSUE TITLE
How to live stream point clouds?

### ISSUE THREAD

**Issue by WenTheProgrammer** [isl-org/Open3D#6028]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I have been searching for how to live stream point clouds using Open3D, or essentially updating point clouds in a window without closing the window, and have not found a working solution. The following code works when I read point clouds from files but doesn't work when I try to use it directly with point cloud generating sensors like lidar for some reason. I have to use `vis.add_geometry` for the first frame to make the code work.

```
vis = o3d.visualization.Visualizer()
vis.create_window()

geometry = o3d.io.read_point_cloud('pc.ply')
vis.add_geometry(geometry)

for i in range(1,100):
        geometry.points = o3d.io.read_point_cloud(str(i+1)+'.ply').points
        vis.update_geometry(geometry)
        vis.poll_events()
        vis.update_renderer()
```
Is there a more elegant, concise way to live stream point clouds?

**Comment by shubhamJain1203** [comment]
So the workaround I did and would suggest you is:-

vis = o3d.visualization.Visualizer()
vis.create_window()

geometry = o3d.io.read_point_cloud('pc.ply')


for i in range(1,100):
        geometry.points = o3d.io.read_point_cloud(str(i+1)+'.ply').points
        vis.add_geometry(geometry)
        vis.poll_events()
        vis.update_renderer()
        vis.remove_geometry()

**Comment by WenTheProgrammer** [comment]
I have finally figure out why my code wasn't working for lidar live streaming. I was initializing a new pc object in my loop by doing `geometry = o3d.geometry.PointCloud()` before updating `geometry.points` and `geometry.colors`. As long as I don't reinitialize the point cloud, the code worked perfectly.
