### ISSUE TITLE
call t::geometry::PointCloud::FromLegacy occurs error.

### ISSUE THREAD

**Issue by guyuezuntinggithub** [isl-org/Open3D#6033]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi guys!  when I t::geometry::PointCloud::FromLegacy in my code, it occurs memory error. I don't know what's wrong with my code.

code is following:
void func(std::vector<std::shared_ptr<geometry::PointCloud>> o3dPointsHighacuPsrt4Rec)
{
    auto o3d_tensor_L = 
		t::geometry::PointCloud::FromLegacy(*o3dPointsHighacuPsrt4Rec[0], core::Float64, open3d::core::Device("CUDA:0"));
auto o3d_tensor_M = 
		t::geometry::PointCloud::FromLegacy(*o3dPointsHighacuPsrt4Rec[1], core::Float64, open3d::core::Device("CUDA:0"));
auto o3d_tensor_R = 
		t::geometry::PointCloud::FromLegacy(*o3dPointsHighacuPsrt4Rec[2], core::Float64, open3d::core::Device("CUDA:0"));
}
when it run out of this function. It occurs memory error.
any reply will be appreciate!

**Comment by guyuezuntinggithub** [comment]
the debug infomation shows that code is dump when run t::geometry::pointcloud::~PointCloud() .
free memory dump. but I still don't know how to solve this problem

**Comment by pimientofrito** [comment]
hello! i almost went crazy looking for where a memory error was occurring. Is there any news about this issue?

**Comment by guyuezuntinggithub** [comment]
> hello! i almost went crazy looking for where a memory error was occurring. Is there any news about this issue?

I use v0.18.0 ,build form source ,resolved this problem!
