### ISSUE TITLE
Build Open3D failed on Ubuntu 20.04 with system VTK

### ISSUE THREAD

**Issue by manhha1402** [isl-org/Open3D#6037]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

#### I first cloned Open3D by:
```
git clone https://github.com/isl-org/Open3D.git
cd Open3D
```

#### Then, I build Open3D (on Ubuntu 20.04, with CUDA 11.4) with:
```
mkdir build
cd build
cmake -DBUILD_CUDA_MODULE=ON -DGLIBCXX_USE_CXX11_ABI=ON -DPYTHON_EXECUTABLE=/usr/bin/python3 -DUSE_SYSTEM_VTK=ON -DBUILD_VTK_FROM_SOURCE=OFF -DUSE_SYSTEM_JPEG=ON ..
make -j$(nproc)
```
![image](https://user-images.githubusercontent.com/20105284/228223959-6f4e91a2-3775-4265-9bea-3937df34d3e6.png)

### Error message

```shell
I build Open3D (on Ubuntu 20.04, with CUDA 11.4
I build Open3d with system VTK and got the build error. Could you please check?
 Thank you

![image](https://user-images.githubusercontent.com/20105284/228224541-bf27236c-fd20-47b8-802e-15e4961d5354.png)
```

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04 / macOS 10.15 / Windows 10 64-bit
- Python version: Python 3.8 / output from `import sys; print(sys.version)`
- Open3D version: output from python: `print(open3d.__version__)`
- System architecture: x86 / arm64 / apple-silicon / jetson / rpi
- Is this a remote workstation?: yes or no
- How did you install Open3D?: pip / conda / build from source
- Compiler version (if built from source): gcc 7.5 / clang 7.0
```

### Additional information

I build Open3D (on Ubuntu 20.04, with CUDA 11.4
I build Open3d with system VTK and got the build error. Could you please check?
 Thank you

![image](https://user-images.githubusercontent.com/20105284/228224541-bf27236c-fd20-47b8-802e-15e4961d5354.png)

**Comment by ssheorey** [comment]
Hi @manhha1402 VTK 9.1+ is required for building Open3D - the Ubuntu 20.04 system version is too old. Will update cmake to flag an error in this case.
