### ISSUE TITLE
color per triangle?

### ISSUE THREAD

**Issue by cwreynolds** [isl-org/Open3D#6060]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

_(I may not understand the second question above, but I think I am running the most recent released version: Open3D 0.17.0, Python 3.10.10, macOS 12.6.3)_

For a diagram-like rendering, I would like to use color per triangle instead of interpolated color per vertex (via `open3d.geometry.TriangleMesh.vertex_colors`). But this [comment](https://github.com/isl-org/Open3D/issues/1087#issuecomment-1222782733) suggests per-triangle support was added to Open3D by December 2021. If so, I am unable to get it to run. This Python test code:

    import open3d as o3d
    import numpy as np

    def face_color_test():
        mesh = o3d.geometry.TriangleMesh.create_octahedron()
        rgb = [[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]]
        # face_colors = o3d.utility.Vector3dVector(np.array(rgb, np.float32))
        face_colors = o3d.utility.Vector3iVector(np.array(rgb, np.int32))
        mesh.triangles["colors"] = face_colors
        vis = o3d.visualization.Visualizer()
        vis.create_window()
        vis.add_geometry(mesh)
        vis.run()
        vis.destroy_window()

gets an error on `mesh.triangles["colors"] = face_colors`:

    Traceback (most recent call last):
      File "/Users/cwr/Documents/code/flock/flock.py", line 158, in <module>
        face_color_test()
      File "/Users/cwr/Documents/code/flock/flock.py", line 133, in face_color_test
        mesh.triangles["colors"] = face_colors
    TypeError: __setitem__(): incompatible function arguments. The following argument types are supported:
        1. (self: open3d.cpu.pybind.utility.Vector3iVector, arg0: int, arg1: numpy.ndarray[numpy.int32[3, 1]]) -> None
        2. (self: open3d.cpu.pybind.utility.Vector3iVector, arg0: slice, arg1: open3d.cpu.pybind.utility.Vector3iVector) -> None

I am currently using one of the workarounds discussed on that earlier Issue. But if there is a supported way to apply face colors directly I would prefer to use that. Any suggestions? Is this feature mentioned in the documentation? I have failed to find it, and the keywords (triangles, colors) are too common for searching.

(I would expect the color data to be rgb triples of floats, but changed it from `Vector3dVector` to `Vector3iVector` based on the error message. I also tried `o3d.core.Tensor(...)` as suggested in the previous Issue, but got the same error.)

**Comment by cwreynolds** [comment]
Since all I know about this feature is from a comment by @errissa I tag them here in case they want to comment.

**Comment by lucagrementieri** [comment]
The property `triangle` cited in the comment exists for the object `open3d.t.geometry.TriangleMesh` based on tensors, see http://www.open3d.org/docs/release/python_api/open3d.t.geometry.TriangleMesh.html#open3d.t.geometry.TriangleMesh

In you example, you are using the legacy TriangleMesh that has no support for colors on faces.

**Comment by cwreynolds** [comment]
Thanks @lucagrementieri — just a few days ago I discovered the “t”/“tensor” subworld of Open3D, via experimenting with `o3d.visualization.draw()`. I made the connection with this question, thinking I should update/close it. Thanks for the reminder.

I would suggest that there is a bigger problem in the docs and sample code. After I started to understand the “t”/“legacy” distinction I looked for a description of that distinction and failed. (Similarly the doc for `o3d.visualization.draw()` is almost nonexistent, as mentioned here: https://github.com/isl-org/Open3D/issues/6094 ) As you indicate there is doc on (say)
[open3d.geometry.TriangleMesh](http://www.open3d.org/docs/release/python_api/open3d.geometry.TriangleMesh.html) and [open3d.t.geometry.TriangleMesh](http://www.open3d.org/docs/release/python_api/open3d.t.geometry.TriangleMesh.html#open3d.t.geometry.TriangleMesh) but no “narrative” on why both exist, nor when you should use either.

My intuition is that the “legacy” code is deprecated and that all new development has been on `o3d.visualization.draw()` and the tensor classes. However, all of the “getting started” docs and sample code talk about the legacy API. This steers new users astray and leads to the sort of confusion seen in this issue (#6060).

**Comment by cwreynolds** [comment]
(This issue of legacy-vs-tensor confusion came up a day later here: https://github.com/isl-org/Open3D/discussions/6130)
