### ISSUE TITLE
ImportError: generic_type: type "Vector3dVector" is already registered!

### ISSUE THREAD

**Issue by saurabheights** [isl-org/Open3D#6061]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

I am using internal class `RGBDVideoMetadata`. However, importing it causes ImportError.

### Steps to reproduce the bug

```python
$ python3
Python 3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from open3d.cuda.pybind.t.io import RGBDVideoMetadata
```

### Error message

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: generic_type: type "Vector3dVector" is already registered!
```

### Expected behavior

Import should be successful.

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 22.04.2 LTS
- Python version: Python 3.10.9
- Open3D version: output from python: `0.17.0+a5be78c`
- System architecture: x86
- Is this a remote workstation?: no
- How did you install Open3D?: pip
- Compiler version (if built from source): NA
```

**Comment by saurabheights** [comment]
Update - Just rebooting system fixed the issue. Is it possible that the library is importing same `Vector3dVector` twice as cpu module instead of cuda module if cuda load fails. (Hypothesis only, I havent yet dived deep enough of how pybind is being used).

**Comment by BenSpex** [comment]
I am encountering the same problem with `import open3d.cpu.pybind.camera as cam` unfortunately a reboot did not help. 
Using python 3.10

**Comment by saurabheights** [comment]
@BenSpex Were you able to resolve this issue?

**Comment by ssheorey** [comment]
Hi @saurabheights  @BenSpex the correct way to import names is:
```py
from open3d.t.io import RGBDVideoMetadata
import open3d.camera as cam
```

the cpu / cuda and pybind names are internal details - please exclude them while importing.
