### ISSUE TITLE
How to make 3D objects appear shaded

### ISSUE THREAD

**Issue by caijillx** [isl-org/Open3D#6068]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

The image provided in the official document appears shaded after coloring
<img width="664" alt="image" src="https://user-images.githubusercontent.com/43942421/230535346-ad1d2f49-7677-49e7-b823-7e06d4edfe78.png">
 I colored the point cloud, the result was only color, not light or dark. How can I make the display result have the effect shown in the above picture
<img width="960" alt="image" src="https://user-images.githubusercontent.com/43942421/230535438-c60da194-e41f-407d-8ae1-c46ac813846f.png">

**Comment by theNded** [comment]
> A lot of the shading, lighting techniques require surface (or in this case point) **normal** data to work. Normals can be calculated by a lot of modeling software or with Open3D you can try to **estimate** them. If you do that it should probably look better. You can simply call: `your_pointcloud.estimate_normals()`
> 
> See [official documentation](http://www.open3d.org/docs/release/tutorial/geometry/pointcloud.html#Vertex-normal-estimation) for details.

Correct answer, computing normals will result in shading.
