### ISSUE TITLE
Fix seed for registration RANSAC python binding

### ISSUE THREAD

**Issue by emil-peters** [isl-org/Open3D#6073]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

While testing with my registration pipeline I found that RANSAC is quite random resulting in bad global registrations from time to time. Would it be possible to fix the seed while using RANSAC registration algorithm using the python binding?

**Comment by yuecideng** [comment]
Yes, please try add the following code before your function:
```
o3d.utility.random.seed(0)
```

**Comment by emil-peters** [comment]
Thanks! I had to update my open3d version to get it to work!
