### ISSUE TITLE
tutorial code snippets “out of sync” with example Python code

### ISSUE THREAD

**Issue by cwreynolds** [isl-org/Open3D#6077]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

There appears to be an “out of sync”(?) problem with code examples in the **Customized visualization** tutorial which may exist in other parts of the doc. The problem is in both the [released](http://www.open3d.org/docs/release/tutorial/visualization/customized_visualization.html#geometries-with-visualizer-class) and [latest](http://www.open3d.org/docs/latest/tutorial/visualization/customized_visualization.html#geometries-with-visualizer-class) versions of the tutorial. The code box under **Mimic draw_geometries() with Visualizer class** shows:

    37
    38
    39    def custom_draw_geometry_with_rotation(pcd):
    40
    41        def rotate_view(vis):
    42            ctr = vis.get_view_control()
    43            ctr.rotate(10.0, 0.0)
    44            return False

Which appears to show a window (lines 37-44) into: [customized_visualization.py](https://github.com/isl-org/Open3D/blob/master/examples/python/visualization/customized_visualization.py#L39) in the master/latest source code. But in that Python file, this function (custom_draw_geometry_with_rotation()) actually spans lines 39-47. So a key bit of the function: 

              o3d.visualization.draw_geometries_with_animation_callback([pcd],
                                                                        rotate_view)

is **not shown in the tutorial**.

### Steps to reproduce the bug

```python
doc
```

### Error message

none

### Open3D, Python and System information

```markdown
- Operating system: macOS 12.6.4
- Python version: Python 3.10.10 (main, Mar 21 2023, 13:41:05) [Clang 14.0.6 ]
- Open3D version: Open3D 0.17.0
- System architecture: apple-silicon
- Is this a remote workstation?: no
- How did you install Open3D?: pip over a conda env
- Compiler version
```

**Comment by cwreynolds** [comment]
Thanks @dancergraham! I appreciate you looking into this.

I hope eventually to know enough about Open3D to submit my own pull requests. Right now I'm too much of a noob.

**Comment by dancergraham** [comment]
Well you're definitely on the right track - your detailed issue notes made it fantastically easy for me to submit my first PR here on the repo!
