### ISSUE TITLE
Unable to perform alpha surface reconstruction on Apple Silicon

### ISSUE THREAD

**Issue by Piflyer** [isl-org/Open3D#6086]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

I am trying to run alpha surface reconstruction on my M2 Max Macbook Pro, but it keeps on crashing. I am currently using a Conda environment that is configured for ARM. I am currently using Open3D version 17.0 and it is installed from pip.

### Steps to reproduce the bug

```python
import open3d as o3d
armadillo_mesh = o3d.data.ArmadilloMesh()
mesh = o3d.io.read_triangle_mesh(armadillo_mesh.path)
pcd = mesh.sample_points_poisson_disk(900)
alpha = 0.03
mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_alpha_shape(pcd, alpha)
```

### Error message

[Open3D WARNING] Creating from empty legacy TriangleMesh.
libc++abi: terminating with uncaught exception of type std::out_of_range: unordered_map::at: key not found

### Expected behavior

Being able to successfully do alpha reconstruction

### Open3D, Python and System information

```markdown
- Operating system: macOS 13.2.1
- Python version: Python 3.10.0
- Open3D version: 0.17
- System architecture: arm64 / apple-silicon
- Is this a remote workstation?: no
- How did you install Open3D?: pip
```

**Comment by yosho27** [comment]
Reproduced with a slightly different error message
`- Operating system: Windows 10 Pro
- Python version: Python 3.9.13
- Open3D version: 0.18.0
- System architecture: x64-based PC
- Is this a remote workstation?: no
- How did you install Open3D?: pip`

`[Open3D WARNING] Creating from empty legacy TriangleMesh.`

`IndexError: invalid unordered_map<K, T> key`

Additionally, this can be reproduced with a point cloud at least as small as 6 points 
[[4,1,0],[0,0,0],[2,0,0],[0,0,1],[3,1,1],[-2,0,1]] and alpha=1

**Comment by hsellik** [comment]
```
 - Operating system: macOS Sonoma Version 14.2.1 
 - Python version: Python 3.9.18
 - Open3D version: 0.18.0
 - System architecture: arm64 / apple-silicon / M3
 - Is this a remote workstation?: no
 - How did you install Open3D?: pip
```
Encountering the same issue on M3 Mac.

**Comment by kongbai-account** [comment]
- Operating system: win10
 - Python version: Python 3.8.0
 - Open3D version: 0.18.0
 - System architecture: x64-based PC
 - Is this a remote workstation?: no
 - How did you install Open3D?: pip
 
[Open3D WARNING] [CreateFromPointCloudAlphaShape] invalid tetra in TetraMesh
[Open3D WARNING] Creating from empty legacy TriangleMesh.
IndexError: invalid unordered_map<K, T> key

**Comment by rxba** [comment]
This is a point scale issue, i.e. max_bound (Armadillo) is [62.1 96.4 56.8] and max_bound (Bunny) is [0.061 0.187 0.058]. If the alpha is large enough (e.g. 10), it works again for the Armadillo.

The unordered_map key error is caused when the reconstructed mesh becomes empty internally, e.g. because of the aforementioned scale issue. This is a bug and I've opened a PR to fix the error, warn the user and return the empty mesh instead.
