### ISSUE TITLE
Scene reconstruction for moving object (D457)

### ISSUE THREAD

**Issue by jrecasens** [isl-org/Open3D#6093]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hello guys,
Im trying to reconstruct a moving object but Im getting very poor results. I have a fixed IntelRealsense D457 recording the top section of a moving  vehicle:

![moving object](https://user-images.githubusercontent.com/14880780/233196320-4535282c-94a5-4bcb-a230-a244961c4668.PNG)

[info.txt](https://github.com/isl-org/Open3D/files/11277447/info.txt)

I am running the RealSense scene reconstruction pipeline from a .bag file as explained [here](http://www.open3d.org/docs/release/tutorial/sensor/realsense.html#reading-from-realsense-bag-files).
but even after changing parameters both for the camera and the `realsense.json` configuration file, the results are always far from optimal. It is not even close to capturing the entire vehicle, even though individual frame point clouds are capturing sections of the moving object.

I would appreciate any guidance, not sure what else to test. All experiment details, original .bag file and results can be found [here](https://1drv.ms/f/s!ApFP03_iPLLTjPorYOUVCffQHXPYcg?e=VXdFsU)

**Comment by theNded** [comment]
Unfortunately this pipeline is designed for static scenes. More advanced methods like D-NERF (https://github.com/albertpumarola/D-NeRF) might be able to do this, but I'm not sure.
