### ISSUE TITLE
get_view_control() return not a reference in python version (0.17.0 doesn't work, but v0.16.0 and v0.15.2 works)

### ISSUE THREAD

**Issue by Jianghanxiao** [isl-org/Open3D#6107]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

The bug is tested in v0.17.0, which works normally in v0.16.0 and v0.15.2 (I also test this). For Visualizer Class, the get_view_control() will not return a reference in v0.17.0, which means no matter how you change the intrinsic or extrinsic of the ViewControl, it doesn't work. Below code the setZoom doesn't work. And if you try calling this function twice, and change one ViewControl, another one will not change.

### Steps to reproduce the bug

```python
vis = o3d.visualization.Visualizer()
vis.create_window()
vis.add_geometry(mesh)
view_control = vis.get_view_control()

# This doesn't work
view_control.set_zoom(4)


vis.poll_events()
vis.update_renderer()  
vis.capture_screen_image("test1.png")

vis.destroy_window()
```

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04
- Python version: Python 3.8 
- Open3D version: 0.17.0
- System architecture: x86
- Is this a remote workstation?: no
- How did you install Open3D?: pip
```

**Comment by cwreynolds** [comment]
Right. See for example: https://github.com/isl-org/Open3D/issues/6009

**Comment by Jianghanxiao** [comment]
The same issue as mentioned in [#6009](https://github.com/isl-org/Open3D/issues/6009)
