### ISSUE TITLE
copy cuda device Image to cpu raise `CUDA runtime error: an illegal memory access was encountered`

### ISSUE THREAD

**Issue by JunLeecus** [isl-org/Open3D#6108]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

I create a cuda.t.geometry.pointcloud on cuda device and it is normal on `transform`, `crop` operator. Then I project the pointclouds to depth using `project_to_depth_image` and need to copy the result depth `Image` to numpy `NDArray`. If I directly call `np.asarray(depth)`, it raise errors and suggest me to use `.cpu()` to copy data first. But when I use `depth.cpu()`, it will raise `CUDA runtime error: an illegal memory access was encountered`.

Why it will access illegal memory? How can I solve it?

Thanks.

### Steps to reproduce the bug

```python
import open3d as o3d
import numpy as np

points = np.ones((5, 3), dtype=np.float32)
k_np = np.array([[433.9951 ,   0.     , 419.95712],
       [  0.     , 433.9951 , 480.     ],
       [  0.     ,   0.     ,   1.     ]], dtype=np.float32)

pcd = o3d.t.geometry.PointCloud(o3d.core.Device("CUDA:0"))
pcd.point.positions = o3d.core.Tensor(points)

depth = pcd.project_to_depth_image(
        848,
        480,
        k_np,
        depth_scale=1,
        depth_max=5.5)
# depth_array = np.asarray(depth)
ndepth = depth.cpu()
```

### Error message

RuntimeError: [Open3D Error] (void open3d::core::__OPEN3D_CUDA_CHECK(cudaError_t, const char*, int)) /*/Open3D/cpp/open3d/core/CUDAUtils.cpp:288: /*/Open3D/cpp/open3d/core/MemoryManagerCUDA.cpp:70 CUDA runtime error: an illegal memory access was encountered

terminate called after throwing an instance of 'std::runtime_error'
  what():  [Open3D Error] (void open3d::core::__OPEN3D_CUDA_CHECK(cudaError_t, const char*, int)) /*/Open3D/cpp/open3d/core/CUDAUtils.cpp:288: /*/Open3D/cpp/open3d/core/MemoryManagerCUDA.cpp:41 CUDA runtime error: an illegal memory access was encountered

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04
- Python version: Python 3.8
- Open3D version: 0.17.0+a5be78cfe
- System architecture: x86
- Is this a remote workstation? no
- How did you install Open3D?: pip & build from source
- Compiler version: gcc 7.5
```

**Comment by theNded** [comment]
The points tensor need to be sent to cuda before assigned to positions.
