### ISSUE TITLE
ValueError: setting an array element with a sequence. The requested array would exceed the maximum number of dimension of 1.

### ISSUE THREAD

**Issue by jayanthd26** [isl-org/Open3D#6119]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

#### I first cloned Open3D by:
```
git clone https://github.com/isl-org/Open3D.git
cd Open3D
```

#### Then, I went to reconstruction_system/sensors for creating custom datset:
```
cd examples\python\reconstruction_system
```
#### Then, I ran  commands to create Dataset
```
python realsense_recorder.py --record_imgs
python realsense_recorder.py --record_rosbag
```
#### Then, came back to reconstruction_system
```
cd ..
```

#### Then, I ran below cmd to create point cloud of custom dataset
```
cd examples/python/reconstruction_system/
python run_system.py config/realsense.json [--make] [--register] [--refine] [--integrate]
```

### Error message

```shell
Transform_good[:3, 3] = [t_approx[0], t_approx[1], t_approx[2]]
ValueError: setting an array element with a sequence. The requested array would exceed the maximum number of dimension of 1.
```

### Open3D, Python and System information

```markdown
- Operating system:  Windows 10 64-bit
- Python version: Python 3.9.16
- Open3D version: 0.17.0
- Is this a remote workstation?: no
- How did you install Open3D?:  conda
```

**Comment by akash02ita** [comment]
I have same problem. Wonder what could be the issue.

**Comment by ostepan2006** [comment]
Hello! I have same problem now. I have:

Operating system:  Windows 10 64-bit
- Python version: Python 3.10
- Open3D version: 0.17.0
- Is this a remote workstation?: no
- How did you install Open3D?:  pycharm

As I understand this problem is resovled. But I had met this problem again. What do you recommed? Thanks

**Comment by QXY618qxy** [comment]
> I had the same problem. Thank you @jayanthd26 for the bug fix! It solved the issue :]

Hello, how did you solve this problem? I had the same problem and never found a solution!
