### ISSUE TITLE
segment_plane computes incorrect result

### ISSUE THREAD

**Issue by themightyoarfish** [isl-org/Open3D#6122]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

I have a point cloud to fit a plane into.
The cloud is basically in the XY plane. I visualize the computed plane approximately, by using just the fourth plane parameter giving the offset. There are some outlier points, but the overwhelming majority form a clear plane.

The plane parameters appear incorrect – the plane is offset on z and does not represent the optimal fit through the cloud.

This can be seen by making the viewer orthographic and inspecting the scene.

### Steps to reproduce the bug

```python
import open3d as o3d

cloud = o3d.io.read_point_cloud("plane.pcd")
plane_model, inliers = cloud.segment_plane(
    distance_threshold=0.1, ransac_n=3, num_iterations=100
)
ground_mesh_size = 20
ground_mesh = o3d.geometry.TriangleMesh.create_box(
    width=ground_mesh_size, height=ground_mesh_size, depth=1e-7
)
ground_mesh.translate([0, 0, -plane_model[-1]])
o3d.visualization.draw_geometries([ground_mesh, cloud])
```

### Error message

n/a

### Expected behavior

The plane goes right through the cloud and is not offset

### Open3D, Python and System information

```markdown
- Operating system: macOS 12.5.1
- Python version: Python 3.10.11
- Open3D version: output from python: 0.17.0
- System architecture: apple-silicon
- Is this a remote workstation?: no
- How did you install Open3D?: pip
```

### Additional information

<img width="1840" alt="Screenshot 2023-04-27 at 13 20 11" src="https://user-images.githubusercontent.com/11613312/234848581-08b16bd3-6159-4fb3-a9cf-25f4991cda42.png">
<img width="1840" alt="Screenshot 2023-04-27 at 13 20 15" src="https://user-images.githubusercontent.com/11613312/234848587-ab798256-c28f-4eac-b2fc-9b273be9e390.png">
<img width="1840" alt="Screenshot 2023-04-27 at 13 20 18" src="https://user-images.githubusercontent.com/11613312/234848590-8f6f1da5-6deb-4eda-9c74-937511f90029.png">

[plane.pcd.zip](https://github.com/isl-org/Open3D/files/11342881/plane.pcd.zip)

**Comment by themightyoarfish** [comment]
anything i can do to help here? seems important.

**Comment by satej1210** [comment]
You'll need to use the other 3 plane model parameters as well to rotate the plane (in addition to translating it) so that it fits correctly with the point cloud.

From your data, there is a slight rotation as seen from the output of the plane model ([ 0.00324395 -0.00175188  0.9999932   0.00555351]).

Once the rotation is applied, the plane fits perfectly.
<img width="1074" alt="Screenshot 2023-06-07 at 15 10 24" src="https://github.com/isl-org/Open3D/assets/6539210/849bb080-b0ef-4adb-8196-42aa521108ff">
