### ISSUE TITLE
Points' order different for triangle mesh saved in .STL format

### ISSUE THREAD

**Issue by ShaoxiongYao** [isl-org/Open3D#6139]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I am using Open3d 0.17.0 on Ubuntu 20.04. When I save a triangle mesh in .STL format, for example:

```
import open3d as o3d

rest_mesh = o3d.geometry.TriangleMesh()
rest_mesh.vertices = o3d.utility.Vector3dVector(points)
rest_mesh.triangles = o3d.utility.Vector3iVector(triangles)
rest_mesh.compute_vertex_normals()
o3d.io.write_triangle_mesh("base_meshes/rest_mesh.stl", rest_mesh)
```
when I load the mesh again **the order of the points is different**. 

```
rest_mesh = o3d.io.read_triangle_mesh("base_meshes/rest_mesh.stl")
print("rest_o3d_mesh points:", np.array(rest_mesh.vertices))
```

This behavior only happens to .STL format and is fine for .ply format. I wonder if there is an expected behavior for .STL files. I am looking forward to your help.

**Comment by hernot** [comment]
Looking at the [`io,TriangleMesh.cpp`](https://github.com/isl-org/Open3D/blob/master/cpp/open3d/io/TriangleMeshIO.cpp) code than stl files are read using [`libassimp`](https://github.com/assimp/assimp) like `.obj` files (lines 26-34).

```
 file_extension_to_trianglemesh_read_function{
                {"ply", ReadTriangleMeshFromPLY},
                {"stl", ReadTriangleMeshUsingASSIMP},
                {"obj", ReadTriangleMeshUsingASSIMP},
                {"off", ReadTriangleMeshFromOFF},
                {"gltf", ReadTriangleMeshUsingASSIMP},
                {"glb", ReadTriangleMeshUsingASSIMP},
                {"fbx", ReadTriangleMeshUsingASSIMP},
        };

```

Consequently you are affected by the same odd [`libassimp`](https://github.com/assimp/assimp) file loading strategy as reported in #6137 and #2614. 
The only temporary fix i found is not using open3d for reading any file for which open3d delegates reading to lib `assimp`, until `libassimp` either changes their rather odd intermediate representation of mesh files or open3d team has decided to drop `libassimp` and resort to another library with tinkers less with input files.

>> ps.: consider upvoting https://github.com/assimp/assimp/issues/5091 and motivating other to upvote in order to make libassimp team aware of the problems their loading approach causes to others.

**Comment by hernot** [comment]
The `.ply`  is or at least was  not an option in the past for me. As far as i remember i had issues to that it is not capable of representing surfaces with uvs and texture image.
Therefore i switched to .obj and store everything in .obj to not get too much mess.
The .off i do not remember likely i did never test as listed after .obj which is capable of storing textured meshes.
