### ISSUE TITLE
TriangleMesh::SamplePointsUniformly doesn't sample triangles uniformly

### ISSUE THREAD

**Issue by rsandzimier-machina** [isl-org/Open3D#6144]
### Checklist

- [x] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

When using TriangleMesh::SamplePointsUniformly(), the function does not actually sample the triangles uniform randomly. It calculates the number of points per triangle based on the surface area and the number of points. And then for each triangle, the corresponding number of points is sampled uniformly from the triangle. So before even doing any random sampling, the number of points per triangle is deterministically calculated based on surface area (and the ordering of triangles in the mesh). This means that with repeated calls to SamplePointsUniformly(), the same number of points will be sampled on each triangle every time, which is inherently non-random. For a larger enough number of sampled points, this is an okay approximation. But for a small number of points it becomes problematic. One major consequence of this is that if the number of points is too small, certain triangles can never be sampled. But the general problem is that triangles do not actually get sampled exactly proportional to their area, and this is amplified significantly for a small number of sample points. 

Is this the intended behavior? 

### Steps to reproduce the bug

```c++
auto sphere = open3d::geometry::TriangleMesh::CreateSphere();
    sphere->ComputeTriangleNormals();
    bool use_triangle_normals = true;
    for (int i = 0; i != 10; i++){
        auto sampled_pts = sphere->SamplePointsUniformly(1, use_triangle_normals);
        for (int j = 0; j != sampled_pts->points_.size(); j++){
            std::cout << "Pt: " << sampled_pts->points_[j].transpose() << " normal: " << sampled_pts->normals_[j].transpose() << std::endl;
        }   
    }
```
Sample output:

Pt:  0.881371 -0.464317  0.035942 normal:  0.850028 -0.520898 0.0782187
Pt:  0.825666 -0.558827 0.0119147 normal:  0.850028 -0.520898 0.0782187
Pt:  0.836437 -0.534213 0.0587785 normal:  0.850028 -0.520898 0.0782187
Pt:  0.886223 -0.453663 0.0541698 normal:  0.850028 -0.520898 0.0782187
Pt:  0.887608 -0.454505 0.0335078 normal:  0.850028 -0.520898 0.0782187
Pt:  0.852025 -0.514956 0.0176215 normal:  0.850028 -0.520898 0.0782187
Pt:  0.873439 -0.475443 0.0480524 normal:  0.850028 -0.520898 0.0782187
Pt:  0.877829 -0.462695 0.0852355 normal:  0.850028 -0.520898 0.0782187
Pt:   0.86169 -0.487152 0.0977552 normal:  0.850028 -0.520898 0.0782187
Pt:  0.879574 -0.460373 0.0817351 normal:  0.850028 -0.520898 0.0782187

### Expected behavior

The above code sample is the extreme example where only 1 point is sampled with each call to SamplePointsUniformly(). I would expect to see different triangles sampled each time SamplePointsUniformly() is called (i.e. the normal direction should change with each call). But what is happening is that the exact same triangle is sampled each time (so the normal direction is the same each time). Basically the cdf for the triangles is calculated deterministically and as a result the only triangle ever sampled will be the first triangle with a cdf > 0.5. And all other triangles will never be sampled. 

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 22.04
- Python version: N/A (C++)
- Open3D version: v0.17
- System architecture: x86
- Is this a remote workstation?: no
- How did you install Open3D?: released binary v0.17
- Compiler version (if built from source): N/A
```
### Additional information

If this is not the intended behavior, my proposal would be to sample a triangle for each point according to the cdf instead of calculating the number of points for each triangle deterministically. The downside of doing it this way is that instead of it being O(N+M) like it is now, it would be O(NlogM+M). Where N is the number of points and M is the number of triangles in the mesh. If this is not desirable, another option would be to shuffle the triangle surface areas (keeping track of the shuffled indices) before calculating the cdf. This would not be exactly "uniform" proportional to the triangle surface areas, but it would certainly be closer to uniform random than doing it deterministically. Shuffling the triangle surface areas would keep the complexity O(N+M), which is a benefit over the "correct" way which would be O(NlogM+M).

**Comment by Alef-gabriel** [comment]
I can take this?

**Comment by johannes-graeter** [comment]
Same problem here

**Comment by iyadahmed** [comment]
I'm an outsider but this seems like intended behavior to me, I'm working on the same problem at the moment, and the solution you described was indeed an option, weighted sampling would gave same results, the smaller the triangles the less of a chance it will get picked,

there's actually another method, but it has the exact opposite issue, bigger triangles **visually** appear to have less samples,
because if there's an equal chance of choosing the triangle, we can assume they will have the same number of points at the limit, and the same number of points on a bigger triangle will look less dense than the same number of points on a small triangle, thus the sampling will not look uniform, in other words it will be not uniform in terms of density (number of points per area unit on the mesh)

pseduo code
```python
points = []
for _ in range(num_desired_points):
    triangle = pick_random_triangle()
    points.append(sample_random_point(triangle))
```

**Comment by iyadahmed** [comment]
@benjaminum 
can I work on this?
I've just pushed the code for my work-in-progress program for the same feature
https://github.com/iyadahmed/geobox/commit/539603f64c8466f84babb87e483d03c752c108be

the heavy lifting is done by [`std::discrete_distribution`](https://en.cppreference.com/w/cpp/numeric/random/discrete_distribution/discrete_distribution) (since C++11), which accepts a numeric value iterator begin and end (for example floats or doubles), passing an iterator of triangle areas fixes the issue described above while still incorporating the idea behind the existing implementation (aka uniform sampling in terms of area unit on mesh)

as you see here, here is a mesh with non uniform triangle sizes (the base of the statue has very large triangles compared to other triangles)
100K points
![image](https://github.com/isl-org/Open3D/assets/25552173/6f59b704-c903-4393-aac0-bf806d3e29f8)

10K points
![image](https://github.com/isl-org/Open3D/assets/25552173/c7856e0f-b578-4435-a4ee-159da78f54b0)

1K points
![image](https://github.com/isl-org/Open3D/assets/25552173/900c4949-3cee-40f2-9ebc-4970eee2df22)

**Comment by benjaminum** [comment]
> @benjaminum can I work on this? I've just pushed the code for my work-in-progress program for the same feature [iyadahmed/geobox@539603f](https://github.com/iyadahmed/geobox/commit/539603f64c8466f84babb87e483d03c752c108be)

@iyadahmed of course! Let me know when you create the PR and mention this issue.

**Comment by iyadahmed** [comment]
Awesome will do asap 🙏

**Comment by iyadahmed** [comment]
about to finish, here's the output of the code provided by issue author with the new local modifications
```
Pt: -0.643155   -0.5143    0.5607 normal: -0.648898 -0.554211  0.521326
Pt:  0.613348 -0.783479 0.0359056 normal:  0.647458 -0.758076 0.0782187
Pt:  0.785933  0.454903 -0.406661 normal:  0.788092  0.482943 -0.381676
Pt:   0.759766 -0.0684343  -0.639144 normal:   0.759048 -0.0597384  -0.648288
Pt: -0.706693  -0.20519  0.671707 normal: -0.740358 -0.177744  0.648288
Pt: 0.283229 0.133719 0.949072 normal: 0.354486 0.146833 0.923461
Pt: -0.00406476    0.816619    0.574857 normal: -0.0669537   0.850727   0.521326
Pt: -0.253326 -0.791642 -0.551146 normal: -0.199212 -0.829779 -0.521326
Pt:  0.536542 -0.374171   0.75161 normal:  0.554734 -0.339941  0.759415
Pt: -0.858788  0.159791  0.480014 normal: -0.829779  0.199212  0.521326
```

I also ran tests

and here's full code that generates the above output

main.cpp
```cpp
#include <iostream>

#include <open3d/Open3D.h>

int main() {
  auto sphere = open3d::geometry::TriangleMesh::CreateSphere();
  sphere->ComputeTriangleNormals();
  bool use_triangle_normals = true;
  for (int i = 0; i != 10; i++) {
    auto sampled_pts = sphere->SamplePointsUniformly(1, use_triangle_normals);
    for (int j = 0; j != sampled_pts->points_.size(); j++) {
      std::cout << "Pt: " << sampled_pts->points_[j].transpose()
                << " normal: " << sampled_pts->normals_[j].transpose()
                << std::endl;
    }
  }

  return 0;
}
```

CMakeLists.txt
```cmake
cmake_minimum_required(VERSION 3.16)
project(Open3D_example_cmake_project)

set(BUILD_SHARED_LIBS OFF)
set(BUILD_PYTHON_MODULE OFF)
set(BUILD_EXAMPLES OFF)
add_subdirectory(Open3D)

add_executable(main main.cpp)
target_link_libraries(main PRIVATE Open3D)
```

**Comment by iyadahmed** [comment]
> > @benjaminum can I work on this? I've just pushed the code for my work-in-progress program for the same feature [iyadahmed/geobox@539603f](https://github.com/iyadahmed/geobox/commit/539603f64c8466f84babb87e483d03c752c108be)
> 
> @iyadahmed of course! Let me know when you create the PR and mention this issue.

Created PR: #6653

**Comment by benjaminum** [comment]
See https://github.com/isl-org/Open3D/pull/6653#issuecomment-1943473909 for a comparison before and after applying #6653

**Comment by iyadahmed** [comment]
> See [#6653 (comment)](https://github.com/isl-org/Open3D/pull/6653#issuecomment-1943473909) for a comparison before and after applying #6653

btw what about changelog.md and also about sharing random engine in large meshes?

**Comment by iyadahmed** [comment]
> See [#6653 (comment)](https://github.com/isl-org/Open3D/pull/6653#issuecomment-1943473909) for a comparison before and after applying #6653

I updated CHANGELOG.md here:
https://github.com/isl-org/Open3D/pull/6655
