### ISSUE TITLE
Build raise require python >= 3.6, but requirements already satisfied.

### ISSUE THREAD

**Issue by JunLeecus** [isl-org/Open3D#6154]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

#### I first cloned Open3D by:
```
git clone https://github.com/isl-org/Open3D.git
cd Open3D
```

#### Then, I build Open3D (on Ubuntu 20.04, with CUDA 11.4) with:
```
mkdir build
cd build
cmake -DBUILD_CUDA_MODULE=ON -DCMAKE_INSTALL_PREFIX=$PWD/open3d_install -DCMAKE_CUDA_ARCHITECTURES=80 -DCMAKE_CUDA_COMPILER=/usr/local/cuda-11.4/bin/nvcc -DBUILD_EXAMPLES=OFF -DBUILD_GUI=OFF ..
make -j$(nproc)
```

### Error message

```shell
-- Open3D 0.17.0
-- Could NOT find Python3 (missing: Development Development.Module Development.Embed) (found suitable version "3.9.5", minimum required is "3.6")
CMake Error at CmakeList.txt:330 (message):
  BUILD_PYTHON_MODULE=ON requires Python >= 3.6. Please ensure it is in PATH. 
```
```


### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04
- Python version: Python 3.8
- Open3D version: 0.17.0
- System architecture: arm64
- Is this a remote workstation?: yes
- How did you install Open3D?: build from source
```

### Additional information

![img_v2_d66b6b48-542b-4436-9cf7-d45104aa73eg](https://github.com/isl-org/Open3D/assets/47651397/791a8b5d-d4c6-4a9b-8e06-e3e9af53fc5a)

And
`-DPython3_ROOT=/path/to/python ` as suggest in http://www.open3d.org/docs/latest/compilation.html#setup-python-environments is also not work

**Comment by quantaji** [comment]
How do you solve this ? Thanks!

**Comment by MsMandelbrot** [comment]
@JunLeecus Hello! Could you please provide the solution? I have the same problem.

**Comment by quantaji** [comment]
Seems like it is a bug of cmake? I solve this by replacing detecting module with `True`
``sh
sed -i 's/Python3_FOUND/True/g' ./Open3D-0.17.0/CMakeLists.txt
``

**Comment by saurabheights** [comment]
If you notice the error, it says 
> Could NOT find Python3 (missing: Development Development.Module Development.Embed) (found suitable version "3.9.5", minimum required is "3.6")
CMake Error at CmakeList.txt:330 (message):

Open3D requires both python interpreter and development modules.
Here, error says `missing: Development`, which means besides `python3`, you need `python3-dev` package.
