### ISSUE TITLE
o3d.geometry.TriangleMesh VS o3d.t.geometry.TriangleMesh

### ISSUE THREAD

**Issue by domef** [isl-org/Open3D#6168]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

What is the difference between `o3d.geometry.TriangleMesh` and `o3d.t.geometry.TriangleMesh`? I see that the first uses Vectors and the second uses Tensors. I also see that the second has 2 methods to convert between the 2 (`from_legacy` and `to_legacy`), so I think that the second is newer and I should use it. But why do they have completely different methods? For example, I need the method `cluster_connected_triangles` but only `o3d.geometry.TriangleMesh` have it.

**Comment by cwreynolds** [comment]
That is an excellent question! 

I am still learning Open3D. Like almost everyone here, my focus now is the project that lead me to find Open3D. I hope eventually to help maintain Open3D.

As a start of an answer to your question, see: https://github.com/isl-org/Open3D/discussions/6130#discussioncomment-5796071
