### ISSUE TITLE
voxel_down_sample() of t.geometry.PointCloud produces incorrect results

### ISSUE THREAD

**Issue by Alex-Dee** [isl-org/Open3D#6172]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

I have tried switching from the legacy PointCloud to the new tensor based in open3d.t.geometry but encountered unexpected behavior of the voxel_down_sample() method. Instead of averaging the point coordinates in every voxel the method seems to just move them at the voxel's center. This obviously leads to information loss and renders the result unusable for further processing like plane detection etc. On the other hand the voxel_down_sample() method of the legacy PointCloud works fine and as expected.
![Bildschirmfoto vom 2023-05-25 10-13-57](https://github.com/isl-org/Open3D/assets/27917875/e55269be-3956-42d1-9456-04aa28992870)

### Steps to reproduce the bug

```python
import open3d as o3d

path = "<path/to/pointcloud>"
pcd = o3d.io.read_point_cloud(path)
pcd = o3d.t.geometry.PointCloud.from_legacy(pcd)

pcd_down = pcd.voxel_down_sample(0.05)

o3d.visualization.gui.Application.instance.initialize()
window = o3d.visualization.gui.Application.instance.create_window(
        "Open3d", 2560, 1200
)
scene_widget = o3d.visualization.gui.SceneWidget()
scene_widget.scene = o3d.visualization.rendering.Open3DScene(window.renderer)
scene_widget.enable_scene_caching(True)
scene_widget.scene.set_background([0.3, 0.3, 0.3, 1])

window.add_child(scene_widget)

mat = o3d.visualization.rendering.MaterialRecord()
mat.shader = "defaultUnlit"
scene_widget.scene.add_geometry("pcd", pcd_down, mat)
o3d.visualization.gui.Application.instance.run()
```

### Error message

None

### Expected behavior

voxel_down_sample() should average all coordinates in each voxel to get an accurate representation of the original point cloud.

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 22.04 
- Python version: Python 3.9 
- Open3D version: 0.17.0
- System architecture: x86 
- Is this a remote workstation?: no
- How did you install Open3D?: pip
```

**Comment by ssheorey** [comment]
Closing as completed.
