### ISSUE TITLE
Reading of JPG and PNG files fails due to "unsupported file format".

### ISSUE THREAD

**Issue by kianheus** [isl-org/Open3D#6183]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi, I'm trying to follow a tutorial on [betterprogramming](https://betterprogramming.pub/introduction-to-point-cloud-processing-dbda9b167534) about recreating point clouds from rgb and depth images. In their tutorial they use an "rgb.jpg" file and a "depth.png" file. I have downloaded the files from [here](https://github.com/Chim-SO/pointcloudprocessing/tree/main/data). 
**The important part of my code looks as follows:** 

```
22. color_raw = o3d.io.read_image("rgb.jpg")
23. depth_raw = o3d.io.read_image("depth.png")
24. 
25. # create an rgbd image object:
26. rgbd_image = o3d.geometry.RGBDImage.create_from_color_and_depth(
27.     color_raw, depth_raw, convert_rgb_to_intensity=False)
28. # use the rgbd image to create point cloud:
29. pcd = o3d.geometry.PointCloud.create_from_rgbd_image(
30.     rgbd_image,
31.     o3d.camera.PinholeCameraIntrinsic(
32.         o3d.camera.PinholeCameraIntrinsicParameters.PrimeSenseDefault))
```

**When I try to run the code, I get the following errors:**

[Open3D WARNING] Read JPG failed: unable to open file: rgb.jpg
[Open3D WARNING] Read PNG failed: unable to parse header.
Traceback (most recent call last):
  File "/home/kian/catkin_ws/src/samxl_mdp/samxl_mdp/scripts/pointcloud/pcl_practice.py", line 29, in <module>
    pcd = o3d.geometry.PointCloud.create_from_rgbd_image(
RuntimeError: [Open3D Error] (static std::shared_ptr<open3d::geometry::PointCloud> open3d::geometry::PointCloud::CreateFromRGBDImage(const open3d::geometry::RGBDImage&, const open3d::camera::PinholeCameraIntrinsic&, const Matrix4d&, bool)) /home/runner/work/Open3D/Open3D/cpp/open3d/geometry/PointCloudFactory.cpp:197: [CreatePointCloudFromRGBDImage] Unsupported image format.

**Comment by saurabheights** [comment]
Please check the logs. It clearly says `Read JPG failed: unable to open file: rgb.jpg`

You have to correct path to image. Rest of code works fine.

![Screenshot from 2023-06-14 15-02-45](https://github.com/isl-org/Open3D/assets/11634769/47d30451-507b-4f16-aede-c669d6facfc9)

**Comment by theNded** [comment]
Could be related to #6236.
