### ISSUE TITLE
Example files for the tutorials missing

### ISSUE THREAD

**Issue by shrinivas96** [isl-org/Open3D#6185]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Came across open3d through this [ICP Registration tutorial](http://www.open3d.org/docs/0.7.0/tutorial/Basic/icp_registration.html) provided in the docs. I would like to try the examples to see how I can make use of this library for my use. But how do you expect someone to follow along with your tutorial series if there is no straight forward way to even get the example files that is in the code. 

Just to be clear this is the lines I am talking about in the tutorial:
```
source = o3d.io.read_point_cloud("../../TestData/ICP/cloud_bin_0.pcd")
target = o3d.io.read_point_cloud("../../TestData/ICP/cloud_bin_1.pcd")
```

Additionally, `open3d` also does not import by just following your getting started tutorials, as noted in this [`_Py_ZeroStruct`](https://github.com/isl-org/Open3D/issues/488) issue. 

People discussed in that thread and came up with solutions, with nearly no help from the developers. A little help would be really appreciated.

**Comment by cwreynolds** [comment]
@shrinivas96:

Hi, I certainly agree that Open3D can be difficult to approach. I’ve been working with it for a few months and am just beginning to know my way around. As for lack of help from developers, my impression is that these days this is a purely community-driven open source project. I’m looking forward to knowing the library well enough to help fix the problems I see.

About your specific issue I can be of no help. But I will point out that the [ICP Registration tutorial](http://www.open3d.org/docs/0.7.0/tutorial/Basic/icp_registration.html) you mention is from Open3D release 0.7.0 (it says so in the upper left corner of that page) while the current release is 0.17.0. I have not used Open3D’s ICP facilities, but I see that there is a _different_ [ICP registration tutorial](http://www.open3d.org/docs/release/tutorial/pipelines/icp_registration.html) in the release doc. You might make more progress following that one.

**Comment by shrinivas96** [comment]
@cwreynolds, thanks a lot, this tip actually helped a lot. You're right initially it took a minute to understand what is going on. But now I sort of get a hang of it. Thanks for your time :D
