### ISSUE TITLE
What measurement unit is used for `compute_point_cloud_distance()`?

### ISSUE THREAD

**Issue by cameronSlupeiks** [isl-org/Open3D#6192]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I understand that this function outputs a double vector that contains the distances (floating point numbers) between every matching source/target point, but what actual measurement unit is being used here? Is it euclidean distance that's being calculated between matching points? Thanks in advance :)

**Comment by ssheorey** [comment]
The unit will be the same as tat in your point cloud coordinates. If 3D points are in mm / inches / miles, distance will be in mm / inches / miles.....
