### ISSUE TITLE
How to Calculate the Fitness and RMSE of Two Point Clouds Without Registration

### ISSUE THREAD

**Issue by 1215232494** [isl-org/Open3D#6193]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I have two files that have already been registered, and I do not need to perform any other registration operations.
How to Calculate the fitness and inlier_rmse of Two Point Clouds Without 'o3d.pipelines.registration.registration_icp'?
Can it be achieved to read two .pcd files and directly calculate them?

**Comment by yuecideng** [comment]
Hi @1215232494 , you can use `o3d.pipelines.registration.evaluate_registration` to achieve this.

**Comment by 1215232494** [comment]
> Hi @1215232494 , you can use `o3d.pipelines.registration.evaluate_registration` to achieve this.

It works, thanks!
