### ISSUE TITLE
How to check if a point cloud is on a bounding box ?

### ISSUE THREAD

**Issue by Myraun** [isl-org/Open3D#6212]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hello !
For a project, I need to automaticaly check if a point cloud is fully enclosed in a existing bounding box, and have the answer "True" if it is.
How Can I do that ?
Thank you

**Comment by yuecideng** [comment]
Hi @Myraun , open3d does not provides a direct function to check whether a point is inside a `aabb` or `obb`, but you can use `get_point_indices_within_bounding_box` and check the return indice list length to achieve the same purpose.
