### ISSUE TITLE
Misspelled 'voxel_szie' in MultiScaleICP will cause bug

### ISSUE THREAD

**Issue by gt0327e** [isl-org/Open3D#6213]
https://github.com/isl-org/Open3D/blob/ff22900c958d0216c85305ee8b3841e5699f9d57/cpp/apps/OfflineReconstruction/LegacyReconstructionUtil.h#L1028

One the line above 'voxel_szie' should be 'voxel_size'.  This issue likely causes the C++ implementation to differ from the Python implementation.

**Comment by yuecideng** [comment]
Hi @gt0327e , thanks for pointing out this issue. I will fix this soon.
