### ISSUE TITLE
Object Open3D considered as lists

### ISSUE THREAD

**Issue by Myraun** [isl-org/Open3D#6217]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hello !

For a project I am creating point cloud and bounding box lists. 
I need to then use this data, but it is considered as lists and not points cloud (example below).
![image](https://github.com/isl-org/Open3D/assets/134513928/e1ec3a4e-90a6-4c3d-b652-a08a6dd6f5bd)
![image](https://github.com/isl-org/Open3D/assets/134513928/be469006-d8af-4de1-b76b-1661bbc2d733)
How should I do so that Open3D recognizes them as Open3D objects and not lists? Knowing that I will have to call them in sequence in "for" loops.

Thank

**Comment by theNded** [comment]
Thank you @MostafaFiroozi for the answer! 
I will close the issue now.
