### ISSUE TITLE
How define a correct coordinates for trans_init in ICP registration ?

### ISSUE THREAD

**Issue by HripsimeS** [isl-org/Open3D#6218]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

@reyanshsolis @theNded @syncle @qianyizh 
Hello. I was checking the notebook for ICP registation 
https://github.com/isl-org/Open3D/blob/master/docs/jupyter/pipelines/icp_registration.ipynb

By using the initial coordinates in the notebook, I get bad results on my data.

trans_init = np.asarray([[0.862, 0.011, -0.507, 0.5],
                         [-0.139, 0.967, -0.215, 0.7],
                         [0.487, 0.255, 0.835, -1.4], [0.0, 0.0, 0.0, 1.0]])

Here https://we.tl/t-F9OrqigDzB you can download my two point clouds (source and target) 
How to write correctly **trans_init** to get nice results with my source and target point clouds. Thanks in advance!

**Comment by wzm2256** [comment]
Hi, ICP requires a good initial pose for each pair of data.
> By using the initial coordinates in the notebook, I get bad results on my data.

Of course the initial pose used for one point clouds is not suitable for another pair. To get a nice initial pose, my suggestion is to use a global registration algorithm such as RANSAC, or to provide correspondence mannually.

**Comment by theNded** [comment]
@wzm2256 thanks for the answer! Yes, global registration approaches such as RANSAC will help. The default transformation was cherrypicked for the specific example.
