### ISSUE TITLE
How do I view the real-time Open3D point cloud from Intel Realsense D405

### ISSUE THREAD

**Issue by leets0429** [isl-org/Open3D#6221]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I'm not sure what I did wrong, but in the Open3D viewer the point cloud doesn't get updated. It shows only the initial pcd that it captured. My script is written in Python

[3_D405_pcd.txt](https://github.com/isl-org/Open3D/files/11798128/3_D405_pcd.txt)

**Comment by saurabheights** [comment]
@leets0429 I believe this is happening due to change in memory held by pcd variable. You have to make sure you add new pointcloud directly into the memory of original pcd variable used in add_geometry.


For testing my theory, display first pcd and then for each next frame you read, don't generate a new pcd but shift the oldpcd by unit vector in any direction and then call update.

**Comment by saurabheights** [comment]
See this - https://github.com/isl-org/Open3D/issues/609#issuecomment-1604900339

**Comment by leets0429** [comment]
@saurabheights it turns out you are correct. Thank you very much

My solution is instead of calling the following to update my pointcloud
``` python
pcd = o3d.t.geometry.PointCloud.create_from_rgbd_image().to_legacy()
```

I would save the new pointcloud in another variable first, then transfer only the points and colors to the old variable
``` python
# new pointcloud variable        
new_pcd = o3d.t.geometry.PointCloud.create_from_rgbd_image().to_legacy() 
# transfer the points and colors to the old variable
pcd.points = new_pcd.points  
pcd.colors = new_pcd.colors
```

Here's my working code for other to refer
``` python
'''
View Intel Realsense D405 pointcloud in Open3D viewer
'''

import numpy as np
import open3d as o3d
import traceback
import time

depth_cam = o3d.t.io.RealSenseSensor()
depth_cam.start_capture()

device = 'cuda:0' if o3d.core.cuda.is_available() else 'cpu:0'
o3d_device = o3d.core.Device(device)
intrinsic_matrix = o3d.core.Tensor(depth_cam.get_metadata().intrinsics.intrinsic_matrix, dtype=o3d.core.Dtype.Float32, device=o3d_device) 

# Initialize the pointcloud viewer
pcd = o3d.geometry.PointCloud()
vis = o3d.visualization.Visualizer()
vis.create_window(window_name="Point Cloud")
vis.add_geometry(pcd)
origin = o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.3, origin=[0, 0, 0])
vis.add_geometry(origin)
view_control = vis.get_view_control()
view_control.set_constant_z_far(1000)

while True:
    
    try:

        im_rgbd = depth_cam.capture_frame(True, True)
        new_pcd = o3d.t.geometry.PointCloud.create_from_rgbd_image(im_rgbd, intrinsic_matrix, depth_scale=depth_cam.get_metadata().depth_scale).to_legacy()
        R_camera_to_world = np.array([[1, 0, 0], [0, -1, 0], [0, 0, -1]]).astype(np.float64)
        new_pcd.rotate(R_camera_to_world, center=np.array([0,0,0],dtype=np.float64))
        pcd.points = new_pcd.points
        pcd.colors = new_pcd.colors

        # Update the visualizer
        vis.update_geometry(pcd)
        vis.poll_events()
        vis.update_renderer()

    except KeyboardInterrupt:
        depth_cam.stop_capture()
        vis.destroy_window()
        break
    
    except:
        print(traceback.format_exc())
```
