### ISSUE TITLE
I HAVE X Y Z COORDINATES FROM OPEN3D AND WANT X Y COORDINATES IN THE IMAGE 

### ISSUE THREAD

**Issue by BIGINCHI** [isl-org/Open3D#6223]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Im running a point cloud data and taking coordinates through segmentation
![image](https://github.com/isl-org/Open3D/assets/61373881/1336be84-850c-433d-bfe0-540038169235)

after getting the coordinates im overlaying the points in realsense cloud data i dont want it to be accurate but approximately its in the same position height and lengthwise
lets assume the red dot is the blue segment coordinates which is on the left top side
![image](https://github.com/isl-org/Open3D/assets/61373881/b1ee1ecc-576d-4151-8ab8-fed53629906b)

now im saving a picture at every frame using open cv i want to mark the x, y coordinates from the x y z approximately 
![image](https://github.com/isl-org/Open3D/assets/61373881/a379a626-125c-4996-b70d-8f9cd83b9ac2)

**_in other tems i want to know about projection of coordinates in open3d._**

### This is my code for reading realsense data and ang saving images every frame
import pyrealsense2 as rs
import numpy as np
import cv2
import open3d as o3d
import time

align = rs.align(rs.stream.color)
config = rs.config()

olorizer = rs.colorizer()
config.enable_device_from_file("C:\\Users\\tsaya\\Downloads\\OneDrive_1_3-21-2023\\bag\\20230321_083006.bag")

pipeline = rs.pipeline()
profile = pipeline.start(config)
intr = profile.get_stream(
    rs.stream.color).as_video_stream_profile().get_intrinsics()
pinhole_camera_intrinsic = o3d.camera.PinholeCameraIntrinsic(
    intr.width, intr.height, intr.fx, intr.fy, intr.ppx, intr.ppy)
extrinsic = [[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]]

def convert_rs_frames_to_pointcloud(rs_frames):
    aligned_frames = align.process(rs_frames)
    rs_depth_frame = aligned_frames.get_depth_frame()
    np_depth = np.asanyarray(rs_depth_frame.get_data())
    o3d_depth = o3d.geometry.Image(np_depth)
    rs_color_frame = aligned_frames.get_color_frame()
    np_color = np.asanyarray(rs_color_frame.get_data())
    o3d_color = o3d.geometry.Image(np_color)

    rgbd = o3d.geometry.RGBDImage.create_from_color_and_depth(
        o3d_color, o3d_depth, depth_scale=1500.0, convert_rgb_to_intensity=False)

    pcd = o3d.geometry.PointCloud.create_from_rgbd_image(
        rgbd, pinhole_camera_intrinsic, extrinsic)
    return pcd

def main():
    rs_frames = pipeline.wait_for_frames()
    pcd = convert_rs_frames_to_pointcloud(rs_frames)
    vis = o3d.visualization.Visualizer()
    vis.create_window(window_name="Point Cloud Visualizer",
                      width=800, height=800)
    vis.add_geometry(pcd)
    render_opt = vis.get_render_option()
    render_opt.point_size = 2.0

    sphere1 = o3d.geometry.TriangleMesh.create_sphere(radius=0.07)
    sphere1.compute_vertex_normals()
    sphere1.paint_uniform_color([1, 0, 0])
    sphere1.translate([-1.32131983 , 1.20482343 , 0.95097112])
    vis.add_geometry(sphere1)
    
    while True:
        rs_frames = pipeline.wait_for_frames()

        depth_frame = rs_frames.get_depth_frame()
        color_frame = rs_frames.get_color_frame()
    
        depth_image = np.asanyarray(depth_frame.get_data())
        color_image = np.asanyarray(color_frame.get_data())
        
        pcd_new = convert_rs_frames_to_pointcloud(rs_frames)
        pcd.points = pcd_new.points
        pcd.colors = pcd_new.colors
        cv2.imwrite('./out.png', color_image)
        vis.update_geometry(pcd)
        if vis.poll_events():
            vis.update_renderer()
        else:
            break

    vis.destroy_window()
    pipeline.stop()

if __name__ == "__main__":
    main()

**Comment by theNded** [comment]
If you already know xyz, you can use the camera intrinsics to do the projection, see https://www.cs.cmu.edu/~16385/s17/Slides/11.1_Camera_matrix.pdf

If you do not know xyz and want to do it interactively, try to play with our examples:
https://github.com/isl-org/Open3D/blob/master/examples/python/visualization/interactive_visualization.py
