### ISSUE TITLE
Visualizing point clouds and meshes together is very buggy

### ISSUE THREAD

**Issue by aurelien-m** [isl-org/Open3D#6237]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

I'm trying to visualize point clouds and meshes together (`o3d.geometry.TriangleMesh.create_coordinate_frame`) but the visualizer focuses the mesh, and if the mesh is too far away from the point clouds, the point clouds disappear. In the picture below, a part of the point cloud is hidden.

![Screenshot from 2023-06-29 12-17-03](https://github.com/isl-org/Open3D/assets/29719028/5125a068-1efa-4904-ae01-5f432a100375)

### Steps to reproduce the bug

```python
import open3d as o3d

pcl = o3d.geometry.PointCloud()
points = []

for x in range(0, 100):
    for y in range(0, 100):
        points.append([x, y, 0])

pcl.points = o3d.utility.Vector3dVector(points)

mesh_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(
    size=10, origin=[0, 0, 30]
)

o3d.visualization.draw_geometries([pcl, mesh_frame])
```

### Expected behavior

Be able to navigate through the point cloud and the mesh.

### Open3D, Python and System information

```markdown
- Operating system: Pop OS 22.04
- Python version: Python 3.10.6
- Open3D version: 0.17.0
- System architecture: x86
- Is this a remote workstation?: no
- How did you install Open3D?: pip (poetry)
```

**Comment by PurplePegasuss** [comment]
Good afternoon!

I tried to investigate the behaiviour behind this issue. It seems like open3d code has limitations on the visualization of the points that located too far from our FOV. Changing the FOV of  Visualizer instance helps in some cases, but generally not. 

The solution which I would like to propose for now, is to add additional coordinate frame located in the center of the point cloud. In that case everything works perfectly - no points are missing. 


```
import open3d as o3d

pcl = o3d.geometry.PointCloud()
points = []

for x in range(0, 100):
    for y in range(0, 100):
        points.append([x, y, 0])

pcl.points = o3d.utility.Vector3dVector(points)

mesh_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(
    size=10, origin=[0, 0, 30]
)

mesh_frame_2 = o3d.geometry.TriangleMesh.create_coordinate_frame(
    size=1, origin=[50, 50, 30]
)

o3d.visualization.draw_geometries([pcl, mesh_frame, mesh_frame_2])
```

![image](https://github.com/isl-org/Open3D/assets/56448851/66289cf8-55f5-4779-9f61-3b4e929f930d)


Best wishes,
Kirill

**Comment by theNded** [comment]
@PurplePegasuss thanks for the answer!
@aurelien-m are you satisfied with the answer? I'm closing the issue now but feel free to reopen if necessary.
