### ISSUE TITLE
Request(or suggest) to change ray cast output dictionary naming convention.

### ISSUE THREAD

**Issue by diskhkme** [isl-org/Open3D#6238]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Proposed new feature or change

Returned dict from `open3d.t.geometry.RaycastingScene.cast_rays()` or `open3d.t.geometry.RaycastingScene.compute_closest_points()` has `primitive_uvs` key.

Although it is informed in the document that the value corresponding to the key is uv of "barycentric coordinate", it is prone to be misread. 

Especially because in the `open3d.geometry.TriangleMesh`, the `triangle_uvs` property indicated texture coordinate, I think it's easy for users to misunderstand `primitive_uvs` as interpolated texture coordinates.

In my opinion, there would be no harm if `primitive_uvs` has been changed to `primitive_barycentric_uvs` or etc, to clarify the meaning.

**Comment by benjaminum** [comment]
Thanks for this suggestion @diskhkme .
We decided to change the name of `triangle_uvs`.
The new `open3d.t.geometry.TriangleMesh` class uses the name `texture_uvs` instead and will eventually replace the old `TriangleMesh` class.
