### ISSUE TITLE
How to directly obtain the depth value of a certain point from the depth map, so as to obtain the z-axis coordinates of the point cloud

### ISSUE THREAD

**Issue by MysteryNull** [isl-org/Open3D#6240]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

How to directly obtain the depth value of a certain point just from the depth image, so as to obtain the z-axis coordinates of the point cloud,thank you!

**Comment by theNded** [comment]
By convention, it is simply the pixel value, see http://www.open3d.org/docs/release/tutorial/geometry/rgbd_image.html#Redwood-dataset.

There are differences in units, so you may want to study your data spec to get a better understanding.
