### ISSUE TITLE
How to find the voxel_index of a specific point in space (x,y,z)? (VoxelBlockGrid)

### ISSUE THREAD

**Issue by natesimon** [isl-org/Open3D#6244]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Question
For a specific point in 3D space (e.g. robot position in x,y,z meters), is it possible for find the voxel_index of the nearest voxel?
The voxel_index would then be used to look up the TSDF value:
`distance = tsdf[voxel_index]`  

If some clarity could be provided as to how one gets from world_coordinates to voxel_coordinates to voxel_index, that would be very helpful. For example, in [andyzeng/tsdf-fusion-python/](https://github.com/andyzeng/tsdf-fusion-python/), we can find the transformation from [voxel_index -> world_coordinates](https://github.com/andyzeng/tsdf-fusion-python/blob/3f22a940d90f684145b1f29b1feaa92e09eb1db6/fusion.py#L88C1-L96C57).

### Attempts
I can find all `voxel_coordinates` and `voxel_indices` from particular `buf_indices` using the function:
```
voxel_coords, voxel_indices = vbg.voxel_coordinates_and_flattened_indices(buf_indices)

```
Still, there are many blocks in the grid, and each block contains 512 voxels, so it is not clear how to convert: x,y,z position -> block index -> voxel_index.  

Articles consulted:
- [Reconstruction system (Tensor)](http://www.open3d.org/docs/latest/tutorial/t_reconstruction_system/index.html)
- [TSDF Integration](http://www.open3d.org/docs/latest/tutorial/t_reconstruction_system/integration.html)
- [Hashmap](http://www.open3d.org/docs/latest/tutorial/core/hashmap.html)
- [integrate_custom.py](https://github.com/isl-org/Open3D/blob/6370a58b98173c5f27c23d55bc31ddd0cf796ea0/examples/python/t_reconstruction_system/integrate_custom.py)  

Thank you!

**Comment by natesimon** [comment]
I have answered my own question. I determined that the hashmap keys are scaled to the block's spatial coordinates.
I was able to verify this by visualizing the blocks on top of the pointcloud.
```
voxel_resolution = 3.0 / 512 # default
block_resolution = 8 # default
vbg = o3d.t.geometry.VoxelBlockGrid.load("path/to/.npz").cpu()
hashmap = vbg.hashmap()
keys = hashmap.key_tensor()
keys_numpy = keys.numpy()

# scale block index to spatial coordinates
block_pos = keys_numpy * (voxel_resolution * block_resolution)
```
Here is a visualization with 1/10th of the blocks shown in blue, against their pointcloud:
<img src="https://github.com/isl-org/Open3D/assets/71222791/8ac87faf-b147-4064-9b49-34d459a1f5d7" width="300">

Instead of using the `tsdf`, I can use `cdist` to find the nearest block to my query point.
```
from scipy.spatial import distance

query_point = np.array([0,0,0]).reshape(1,3) # m, example
tmp = distance.cdist(block_pos, query_point, "sqeuclidean") # m, example
```
If I wish to find the nearest voxel to my query point, knowing the nearest block (and therefore the nearest key), I can readily do that by:
```
min_idx = np.argmin(tmp)
buf_indices, masks = hashmap.find(keys[min_idx].reshape((1,3)))
voxel_coords, voxel_indices = vbg.voxel_coordinates_and_flattened_indices(buf_indices)
voxel_coords_numpy = voxel_coords.numpy()
tmp_voxel = distance.cdist(voxel_coords_numpy, query_coordinate, "sqeuclidean")
min_voxel_idx = np.argmin(tmp_voxel)
```

If there is a more efficient way to do this with open3d, please let me know! Additionally, I am still not able to find the nearest _occupied_ voxel using this method. If there is a way to do that, I would be very interested.

**Comment by humanbeingZ** [comment]
Here's a piece of code I wrote.
I use VoxelBlockGrid to do weighted average of several point clouds.
You might find it helpful.

```python
import numpy as np
import open3d as o3d
import open3d.core as o3c


def integrate(
    vbg: o3d.t.geometry.VoxelBlockGrid,
    pointcloud: o3d.t.geometry.PointCloud
):
    # convert to numpy array
    pts = pointcloud.point['positions'].numpy()

    # point -> block coords, block_offset, voxel_coords
    block_coords = np.floor(pts / block_size).astype(np.int32)
    block_offset = pts - block_coords * block_size
    voxel_coords = np.floor(block_offset / voxel_size).astype(np.int32)

    # activate
    vbg.hashmap().activate(o3c.Tensor.from_numpy(block_coords))

    # attributes of voxel block grid
    coord = vbg.attribute('coord').numpy()
    weight = vbg.attribute('weight').numpy()

    # integration
    buf_indices, mask = vbg.hashmap().find(o3c.Tensor.from_numpy(block_coords))
    coord[buf_indices.numpy(), voxel_coords[:, 0], voxel_coords[:, 1], voxel_coords[:, 2]] += pts
    weight[buf_indices.numpy(), voxel_coords[:, 0], voxel_coords[:, 1], voxel_coords[:, 2]] += 1.


def extract_point_cloud(
    vbg: o3d.t.geometry.VoxelBlockGrid
):
    # attributes of voxel block grid
    coord = vbg.attribute('coord').numpy().reshape(-1, 3)
    weight = vbg.attribute('weight').numpy().reshape(-1)

    # only voxel with weight greater than 0 counts
    mask = weight > 0

    # centroid of each voxel
    pts = coord[mask] / weight[mask].reshape(-1, 1)

    pcd = o3d.t.geometry.PointCloud()
    pcd.point['positions'] = o3c.Tensor.from_numpy(pts)
    return pcd


if __name__ == '__main__':
    # parameters for integration
    voxel_size = 0.05
    block_resolution = 8
    block_size = voxel_size * block_resolution

    # initialize voxel block grid
    vbg = o3d.t.geometry.VoxelBlockGrid(
        attr_names=['coord', 'weight'],
        attr_dtypes=[o3c.float32, o3c.float32],
        attr_channels=[(3), (1)],
        voxel_size=voxel_size,
        block_resolution=block_resolution,
        block_count=1000,
    )

    # generate point cloud data
    # pcd = o3d.t.io.read_point_cloud('')
    pts = np.array([
        [0.1, 0.1, 0.1],
        [1.,  0.,  1. ],
    ])
    pcd = o3d.t.geometry.PointCloud()
    pcd.point['positions'] = o3c.Tensor.from_numpy(pts)

    # here you can call integrate more than once
    integrate(vbg, pcd)

    res = extract_point_cloud(vbg)

    o3d.t.io.write_point_cloud('./centroid.ply', res)
    # print(res.point['positions'].numpy())
```
