### ISSUE TITLE
Open3D pointcloud from D405 can't sense object further than 15cm

### ISSUE THREAD

**Issue by leets0429** [isl-org/Open3D#6246]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

----------------------------------------------------------------------------------------------------

| Required Info                         |                                                                |
|---------------------------------|------------------------------------------- |
| Camera Model                       | Intel Realsense D405 | 
| Firmware Version                   | 2.53.1 | 
| Operating System & Version |   Ubuntu 20.04  | 
| Kernel Version (Linux Only)    |  5.15.0-76-generic                                         | 
| Platform                                 | PC |
| SDK Version                            |  pyrealsense2 2.53.1.4623, open3d  0.16.0| 
| Language                            |  python | 
| Segment			|  robot | 

### Issue Description
I'm able to get pointcloud in Open3D format, however if objects are further than around 15cm, they no longer appear in the pointcloud. This doesn't make sense as I tried the example script with opencv viewer, it could sense object much further away. I'm not sure is this a Open3D or Intel Realsense issue. Hence I will post at both places. Below is my code:

    import open3d as o3d
    
    depth_cam = o3d.t.io.RealSenseSensor()
    depth_cam.start_capture()
    device = 'cuda:0' if o3d.core.cuda.is_available() else 'cpu:0'
    o3d_device = o3d.core.Device(device)
    intrinsic_matrix = o3d.core.Tensor(depth_cam.get_metadata().intrinsics.intrinsic_matrix, dtype=o3d.core.Dtype.Float32, device=o3d_device) 
    im_rgbd = depth_cam.capture_frame(True, True)
    pcd = o3d.t.geometry.PointCloud.create_from_rgbd_image(im_rgbd, intrinsic_matrix).to_legacy()
    
    try:
        while True:
  
            im_rgbd = depth_cam.capture_frame(True, True)
            pcd = o3d.t.geometry.PointCloud.create_from_rgbd_image(im_rgbd, intrinsic_matrix).to_legacy()
            o3d.visualization.draw_geometries([pcd])
    
    finally:
        pass

**Comment by ellingro** [comment]
Check the depth_cam.get_metadata().depth_scale value. I think it is around 10 000 for the D405 while the default depth_scale for create_from_rgbd_image is 1000. Setting the depth_scale while calling create_from_rgbd_image shouldfix this. Also be aware that the default depth_max is 3.0, but I dont think that should be a problem since the output after applying the correct depth_scale should result in mm output.

`pcd = o3d.t.geometry.PointCloud.create_from_rgbd_image(im_rgbd, intrinsic_matrix, depth_scale= depth_cam.get_metadata().depth_scale).to_legacy()`

**Comment by leets0429** [comment]
It works! Thank you very much.
