### ISSUE TITLE
How to set the camera instrinsics in `hidden_point_removal`

### ISSUE THREAD

**Issue by s-suraj-08** [isl-org/Open3D#6256]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [ ] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

For hidden point remove, how do we set the camera instrinsics? I have searched for similar issues Issue:[5046](https://github.com/isl-org/Open3D/issues/5046). Could not find an answer

**Comment by bisalgt** [comment]
Hi @s-suraj-08 . Were you able to figure out this ?

**Comment by s-suraj-08** [comment]
@bisalgt No, Open3D does not seem to provide a way to input camera intrinsics for this algorithm. After going through the paper for the original algorithm, as per my current understanding, the visibility criteria does not depend on the camera intrinsics. Instead it provides the points that would be visible from a given perspective (irrespective of the camera intrinsics). The work around I used was to use this algorithm and apply frustum culling (manually) to get the points that are visible to my camera.

**Comment by bisalgt** [comment]
Thanks for your reply @s-suraj-08 . For me, I just plan to look at shadow casting so I think tweaking the sphere radius and light source origin might be good for me.

Regards,
Bishal
