### ISSUE TITLE
Cannot compile on Windows x64, VS 2022 for C++

### ISSUE THREAD

**Issue by malatindez** [isl-org/Open3D#6257]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

#### I first cloned Open3D by:
```
git clone --recursive https://github.com/intel-isl/Open3D
cd Open3D
```
```
mkdir build
cd build
cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_INSTALL_PREFIX="../../Open3D_install" ..
```

### Error message

```shell
C:\Users\malatindez\Open3D\build\fmt\include\fmt\core.h(1711,42): error C4996: 'fmt::v9::detail::arg_mapper<Context>::map': was declared deprecated [C:\Users
\malatindez\Open3D\build\cpp\open3d\visualization\webrtc_server\webrtc_server.vcxproj]
```

### Open3D, Python and System information

```markdown
- Tried master branch, v0.17.0
- Windows 10 64-bit
- Python version: Python 3.10.1
- System architecture: x86
- Is this a remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): MSVC 1936
```

**Comment by carlos-lee123** [comment]
I solved this problem by adding compile option:
```make
if(WIN32)
    add_compile_options("/wd4996")
endif()
```
you can find more details and compile problems here [https://blog.csdn.net/qq_41102371/article/details/131891820](https://blog.csdn.net/qq_41102371/article/details/131891820)
