### ISSUE TITLE
o3d.t.io.write_point_cloud()  save timestamp with int but nop float64

### ISSUE THREAD

**Issue by Anutlet** [isl-org/Open3D#6258]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

In the development process, I used the pcd_ori = o3d.t.io.read_point_cloud function to read a PCD file. The pcd_ori object contains timestamps of type float64. 
![image](https://github.com/isl-org/Open3D/assets/15341892/6be0d847-6f27-409c-b3ce-7e4b7b45e09b)

After processing, the point array also contains timestamps of type float64. However, when I use o3d.t.io.write_point_cloud to save the processed point cloud to a new PCD file, the decimal part of the timestamps is removed, making it impossible to locate specific timestamps.
![image](https://github.com/isl-org/Open3D/assets/15341892/4f8ecb9a-86e9-4e46-9ccb-5507280a3367)

 How can I preserve the decimal part of the timestamps when saving the PCD file?

**Comment by Anutlet** [comment]
help

**Comment by AdrianMTZVazquez** [comment]
Could you share parts of your code where you write your pcd file?

**Comment by Anutlet** [comment]
> 
Thank you very much for your reply ! Below is the code I use to write pcd file:
 pcd0 = o3d.t.geometry.PointCloud.remove_non_finite_points( pcd0_ori, remove_nan = True, remove_infinite = False)
some process without processcing timestamp
o3d.t.io.write_point_cloud(fusion_lidar_filename,pcd0[0],write_ascii=True,compressed=True)

**Comment by theNded** [comment]
Writing to binary will give you back the decimals.

**Comment by Anutlet** [comment]
> @AdrianMTZVazquez thanks for engaging the conversation. @Anutlet thanks for the detailed information.
> 
> Writing to binary will give you back the decimals. Please specify `write_ascii=False`.
> 
> FYI, to avoid too large ascii file size, we use a certain floating point precision format, see https://github.com/isl-org/Open3D/blob/f8fbef1d87973f6558f9bf1f940d58d58fbf8391/cpp/open3d/t/io/file_format/FilePCD.cpp#L932C29-L932C32

Thank you very much!!!
