### ISSUE TITLE
Cannot download latest development version

### ISSUE THREAD

**Issue by BiRedMobile1** [isl-org/Open3D#6259]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

I cannot download the development version to file a bug report on another issue.  All the links here do not work: http://www.open3d.org/docs/latest/getting_started.html#development-version-pip

### Steps to reproduce the bug

```python
http://www.open3d.org/docs/latest/getting_started.html#development-version-pip

All the links say "The Specified Key does not exist."
```

### Open3D, Python and System information

```markdown
- Operating system: Windows 10 64-bit
- System architecture: x86
```

**Comment by ssheorey** [comment]
This was a CI issue that is now fixed. The links work again now.
