### ISSUE TITLE
Use rendering.TriangleMeshModel

### ISSUE THREAD

**Issue by HDesclos** [isl-org/Open3D#6274]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [x] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [x] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Use rendering.TriangleMeshModel
Hi, 
i'm trying to use a **OffscreenRenderer** to take picture of a scene where two meshes are add.
I started to make it work with simple trianglemesh and used scene.add_geometry. But now, i want to **load the texture**, so i've found that I should use add_model instead of add_geometry in the renderer and use trianglemodel. Because add_geometry only load the simple texture. Which is strange because in the visualizer, the textured mesh ( .obj) is load even using io.read_triangle_mesh without any texture definition with geometry.Image. 
Therefore, I need to read the mesh with io.read_triangle_mesh and not io.read_triangle_model because I need to translate and rotate those meshes.
So i've found that I could use the class **rendering.TriangleMeshModel** which according to the documentation is : " A list of geometry.TriangleMesh and Material that can describe a complex model with multiple meshes" 
But i compelled to init it and to list my two meshes in the attributes meshes of the class (http://www.open3d.org/docs/0.12.0/python_api/open3d.visualization.rendering.TriangleMeshModel.html). I've also found nowhere someone using this class.

I'm using the version 0.17.0 of open3d and python 3.8

**here what i was doing first :** 
```ruby
import open3d as o3d 
import open3d.visualization.rendering as rendering
meshback = o3d.io.read_triangle_mesh(path_mesh_background + filename_mesh_background, enable_post_processing = True , print_progress=True)
meshback.translate(-meshback.get_center())
mesh = o3d.io.read_triangle_mesh(path_mesh + filename_mesh,enable_post_processing = True , print_progress=True)
mesh.translate(-mesh.get_center())

h_im = 3072 
w_im = 4096 
render_offscreen = rendering.OffscreenRenderer(w_im, h_im)
mtl = rendering.MaterialRecord()
render_offscreen.scene.add_geometry("mesh", mesh, mtl)
render_offscreen.scene.add_geometry("meshback", meshback, mtl)
render_offscreen.scene.view.set_post_processing(True)

```
the following of the script is just the setting of the camera.

I want to use something like this :
TMM = o3d.visualization.rendering.TriangleMeshModel()
then add my two triangleMesh to the TriangleMeshModel (i don't know how to do it)
and then use render_offscreen.scene.add_model

thanks for your time

**Comment by HDesclos** [comment]
Make it work, only problem of memory now yhen i'm adding the model to the renderer

**Comment by alan355** [comment]
Please tell me how you solved this problem. I'm trying to use `add_mode`l to add a mesh read by `o3d.io.read_triangle_mesh`. But `add_model` requires the `TriangleMeshModel` format, and `o3d.io.read_triangle_mesh` reads the `TriangleMesh` format. I have not found a way to convert the two formats.

**Comment by HDesclos** [comment]
‌

Hi,
I'm defining a model with :
        # model = o3d.visualization.rendering.TriangleMeshModel()

then i'm adding the meshes to the model
        # mesh_infos = []
        # mesh2_info = o3d.visualization.rendering.TriangleMeshModel.MeshInfo(meshback,"mesh2",0)
        # mesh1_info = o3d.visualization.rendering.TriangleMeshModel.MeshInfo(mesh,"mesh",1)
        # mesh_infos.append(mesh2_info)
        # mesh_infos.append(mesh1_info)
        # model.meshes = mesh_info

then, I can add use add_model in the renderer offscreen
        #render_offscreen.scene.add_model("model", model)

However, i meet memory issues when i add the model and in the end i didn't use TriangleModel for my work and only Triangleesh because i couldn't translate et rotate the model if i remember correctly.

I'm not completely sure for the way to add TriangleMesh to the Model, the doc is not very clear about open3d.visualization.rendering.TriangleMeshModel

You can try open3d.io.read_triangle_model directly also.

Have a nice day


‌
 

De : "alan355"
A : "isl-org/Open3D" ,"HDesclos" ,"State change"
Envoyé: mercredi 10 Janvier 2024 15:58
Objet : Re: [isl-org/Open3D] Use rendering.TriangleMeshModel (Issue #6274)
 

 

Please tell me how you solved this problem. I'm trying to use add_model to add a mesh read by o3d.io.read_triangle_mesh. But add_model requires the TriangleMeshModel format, and o3d.io.read_triangle_mesh reads the TriangleMesh format. I have not found a way to convert the two formats.

**Comment by jez-moxmo** [comment]
I'm trying to solve an issue with memory leaks for this as offscreen renderer won't allow two models to be added. I think you have to make everything all in the one model.
