### ISSUE TITLE
load-save-viewpoint

### ISSUE THREAD

**Issue by hmatrixh** [isl-org/Open3D#6276]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

python: 3.8
open3d: 0.17.0
Official python examples is not useful：http://www.open3d.org/docs/release/python_example/visualization/index.html#load-save-viewpoint-py

**Comment by jiaxi-jiang** [comment]
same issue for me, any solution?

**Comment by hmatrixh** [comment]
i use open3d: 0.16.0 solve it

**Comment by hmatrixh** [comment]
i use open3d: 0.16.0 solve it

**Comment by Jackiezhou233** [comment]
same for me using python3.8 and open3d:0.17.0

**Comment by Jackiezhou233** [comment]
also the customized_visualization_key_action.py example doesn't work using python3.8 and open3d:0.17.0

**Comment by hmatrixh** [comment]
> also the customized_visualization_key_action.py example doesn't work using python3.8 and open3d:0.17.0
i use open3d: 0.16.0 solve it. i guess AMD is not suit for open3d
