### ISSUE TITLE
How to generate image dataset of a geometry using custom camera extrinsics and intrinsics.

### ISSUE THREAD

**Issue by SarthakGupta22** [isl-org/Open3D#6280]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi, I am trying to generate RGB image data from a  3d geometry defines in open3d. I have tried the `capture_screen_float_buffer` function but that only captures the image with the default camera parameters. Is there a way to change the intrinsics and extrinsics of the visualizer before capturing the data?

**Comment by theNded** [comment]
You may want to look at this example:
https://github.com/isl-org/Open3D/blob/master/examples/python/visualization/render_to_image.py
It does support specifying intrinsics and extrinsics: http://www.open3d.org/docs/latest/python_api/open3d.visualization.rendering.OffscreenRenderer.html#open3d.visualization.rendering.OffscreenRenderer.setup_camera

Hope it helps!
