### ISSUE TITLE
How to Configure General Parameters for Estimating Normal Vectors

### ISSUE THREAD

**Issue by molimoli2585** [isl-org/Open3D#6283]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I have several box shaped point clouds aligned to the coordinate axis, and because the point cloud is aligned to the coordinate axis, the majority of the normal vectors of the point cloud are along the XYZ axis. Therefore, I use the estimate of the point cloud_ Normal method is used to estimate the normal vector. After the estimation, the normal vector is normalized and accurate to one place after the Decimal separator.
![image](https://github.com/isl-org/Open3D/assets/57432062/f146ad30-053f-4382-826b-f8d630d59fcc)
At this point, most point clouds always have a normal vector of ± 1.0, ± 0.9, or ± 0.8, so I segment them based on the normal vector. However, the remaining point clouds after segmentation still have some normal vectors of points in a plane that do not meet the above conditions and are retained.
So I suspected that the problem was the inaccurate estimation of the normal vector. By configuring the parameters, I found that when radius=10, max_nn=30, the point cloud had the best segmentation effect, and the remaining point cloud did not contain too many points that should have been on the plane.
![image](https://github.com/isl-org/Open3D/assets/57432062/975883a9-20fb-4b22-8b4f-c2803fcc0f9f)
![image](https://github.com/isl-org/Open3D/assets/57432062/37d68ccd-218f-4dfe-bb45-96c139415422)
But when I applied this parameter to another point cloud, the segmentation effect of the point cloud was relatively poor, and the point whose normal vector should be along the Y axis was calculated as along the Z axis. After testing, the point cloud estimation normal vector only needs knn=30 to achieve good segmentation results.
![image](https://github.com/isl-org/Open3D/assets/57432062/4dee93da-35f8-44de-b91a-e4992dade0f7)

![image](https://github.com/isl-org/Open3D/assets/57432062/7849da20-2411-46e5-a935-eb15cf440f28)
I would like to know if there is any way to achieve a set of parameters that can be adapted to the estimated normal vectors of different point clouds (with a total number of points of around 1 million and a majority of point cloud sizes ranging from 1.0 * 1.0 * 10-20), or if there are any methods that can be automatically configured.

**Comment by theNded** [comment]
Thanks for the detailed analysis! I think it is still a classical but relatively open problem.
Our current approach only analyzes the (local) nearest neighbors; but to obtain a higher level of insight in adjusting parameters, we have to understand the global properties of the point cloud. There are recent papers that work on such properties, e.g. winding number field https://arxiv.org/pdf/2304.11605.pdf, but I believe a really concrete approach to real-world data is still not present.
Right now we do not have the bandwidth for such experimental extensions, so you may have to stick to manual tuning for a while :-(

**Comment by theNded** [comment]
I will close the issue now, but feel free to reopen if you have new observations/thoughts. Thank you!
