### ISSUE TITLE
VoxelDownSample generates "weird" pattern 

### ISSUE THREAD

**Issue by halil-karabacak** [isl-org/Open3D#6289]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

Hi. I am using open3d for 3D alignment purposes and it came to my attention that sometimes voxel down sample method creates something i didn't expect to be. I added the photo of the result, but since github doesn't support i can't upload .ply file. The point cloud is a simple pcl of a straight paper.

![image_720](https://github.com/isl-org/Open3D/assets/73756179/70d679f1-9dad-406d-91fe-b0a3d36c2bb8)

### Steps to reproduce the bug

```python
pcd = o3d.io.read_point_cloud("path/Mesh.ply")
mesh_ds = copy.deepcopy(pcd).voxel_down_sample(voxel_size=1)
o3d.io.write_point_cloud("saved.ply", mesh_ds)
```

### Open3D, Python and System information

```markdown
- Operating system: Windows 10 64-bit
- Python version: Python 3.8
- Open3D version: output from python: `print(open3d.__version__)`
- System architecture: x86
- Is this a remote workstation?: no
- How did you install Open3D?: pip
```

**Comment by theNded** [comment]
I believe they are normal patterns that happen during sampling. I see them every day! 
They happen both in 2D and 3D; and in 3D they usually look more apparent. 
For your reference: https://en.wikipedia.org/wiki/Moir%C3%A9_pattern
