### ISSUE TITLE
RMSE Calculation in EvaluateRANSACBasedOnDistance Method

### ISSUE THREAD

**Issue by pherrusa7** [isl-org/Open3D#6291]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hello everyone,

First of all, thank you for your contributions to this great library!

This question might or might not turn into a minor bug. I was reading the code for [EvaluateRANSACBasedOnDistance](https://github.com/isl-org/Open3D/blob/179886dfd57797b2b0d379062387c60313a58b2b/cpp/open3d/geometry/PointCloudSegmentation.cpp#L69) and I found the following formula:
`result.inlier_rmse_ = error / std::sqrt((double)inlier_num);`

However, `error` is collected by adding absolute values (as opposed to squared):
```
double distance = std::abs(plane_model.dot(point));
...
error += distance;
```

Given how the error is accumulated I was expecting to find a mean absolute error. Is there any reason for the denominator to be the square root of the sample size rather than just the sample size? I might be missing something (or maybe it is indeed a minor bug) so any ideas are welcome.

Thank you for your time :)

**Comment by theNded** [comment]
This is a good catch! I think it is a bug. I will mark it on my TODO list and fix it.

**Comment by pherrusa7** [comment]
Glad to be helpful! I'd be happy to assist further with some guidance. Specifically, do you think the error should be squared during accumulation or averaged later by the number of samples? Also, is there a reference paper based on which this routine was implemented?

**Comment by theNded** [comment]
They should be squared. I think it is relatively a trivial problem now and can be traced back to 2000s. MATLAB has a reference list: https://www.mathworks.com/help/vision/ref/pcfitplane.html

**Comment by pherrusa7** [comment]
Yes, that makes sense. I see that you already made the changes so it is done. Thank you!
