### ISSUE TITLE
I want to compile all dependencies from scratch, how to find all dependencies of Open3D?

### ISSUE THREAD

**Issue by xshen053** [isl-org/Open3D#6296]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I want to compile all dependencies from scratch, how to find all dependencies of Open3D? 
3rd party folder includes all the dependency of Open3D, but they are the children of Open3D, I want to find other dependencies whose parent are depndency of Open3D, could you tell me how to figure out such thing?

**Comment by ssheorey** [comment]
As you noticed, all dependencies (with versions) are listed in the folders in 3rdparty in cmake files. If these dependencies themselves have any dependencies, they are built at the same time. A list of those isn't present directly and you have to search in the 3rdparty dependencies individually.
