### ISSUE TITLE
Pointcloud from depth map is incorrect

### ISSUE THREAD

**Issue by thve25** [isl-org/Open3D#6303]
### Issue Description
I'm trying to create a pointcloud from a depth map from a realsense camera in open3d.

The pointcloud created using pyrealsense and the Open3d pointcloud differ a lot. The one from pyrealsense looks correct
(I applied filters to the depth map to make the difference easier to see):

![Screenshot from 2023-08-09 21-28-32](https://github.com/isl-org/Open3D/assets/35802960/8ea05e50-23de-475c-ac27-fd7b12528197)

```
pc = rs.pointcloud()
points = pc.calculate(depth_frame)
v = points.get_vertices()
verts = np.asanyarray(v).view(np.float32).reshape(-1, 3)  # xyz

pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(verts)

# Get stream profile and camera intrinsics
profile = pipeline.get_active_profile()
depth_profile = rs.video_stream_profile(profile.get_stream(rs.stream.depth))
depth_intrinsics = depth_profile.get_intrinsics()

# Convert the depth frame to a numpy array
depth_scale = device.query_sensors()[0].get_option(rs.option.depth_units)
depth_image_np = np.asanyarray(depth_frame.get_data()) * depth_scale

# Convert the numpy array to an open3d depth image
depth_image_o3d = o3d.geometry.Image(depth_image_np.astype(np.float32))

# Create an open3d camera intrinsics object from pyrealsense2 intrinsics
o3d_camera_intrinsic = o3d.camera.PinholeCameraIntrinsic(depth_intrinsics.width, depth_intrinsics.height, 
                                                          depth_intrinsics.fx, depth_intrinsics.fy, 
                                                          depth_intrinsics.ppx, depth_intrinsics.ppy)

# Create the point cloud from the open3d depth image
pcd2 = o3d.geometry.PointCloud.create_from_depth_image(depth_image_o3d, o3d_camera_intrinsic)

vis = o3d.visualization.Visualizer()
vis.create_window(window_name='pointcloud', width=3000, height=2000)
vis.add_geometry(pcd)
vis.add_geometry(pcd2)
vis.run()
vis.destroy_window()
pipeline.stop()
```
The intrinsics of the camera look correct:
```
print(depth_intrinsics.width, depth_intrinsics.height, 
           depth_intrinsics.fx, depth_intrinsics.fy, 
           depth_intrinsics.ppx, depth_intrinsics.ppy)
1280 720 889.8737182617188 889.8737182617188 633.4789428710938 344.9337158203125
```

What could be the problem?

**Comment by Polymere** [comment]
I have a hard time seeing the two different point clouds on the image, but I might have an idea.
Did you try specifying the depth scale when projecting the point cloud ?
```pcd2 = o3d.geometry.PointCloud.create_from_depth_image(depth_image_o3d, o3d_camera_intrinsic,depth_scale=1.0)```
I think the default value is 1000, which is might not be correct if you apply the scaling from the sensor

**Comment by thve25** [comment]
> I have a hard time seeing the two different point clouds on the image

I made it a bit more clear in my original post. The large rectangle is the pyrealsense pointcloud.
The Open3D pointcloud is stretched in z, but narrower in x and y 

> I Did you try specifying the depth scale when projecting the point cloud ? `pcd2 = o3d.geometry.PointCloud.create_from_depth_image(depth_image_o3d, o3d_camera_intrinsic,depth_scale=1.0)` I think the default value is 1000, which might not be correct if you apply the scaling from the sensor

I did scale it:
```
depth_scale = device.query_sensors()[0].get_option(rs.option.depth_units)
depth_image_np = np.asanyarray(depth_frame.get_data()) * depth_scale
```

**Comment by theNded** [comment]
You should either not scale it manually and provide the scale factor in `create_from_depth_image`; or scale it manually and specify `depth_scale=1.0` as suggested by @Polymere . 
The default scale is 1000.0, meaning that you may have double scaled which results in the distortion.

**Comment by thve25** [comment]
I've solved it. I used the wrong intrinsics.

This is correct:
```
frames = pipeline.wait_for_frames()
frames = align.process(frames)
profile = frames.get_profile()
intrinsics = profile.as_video_stream_profile().get_intrinsics()
```

This is not correct:
```
depth_profile = rs.video_stream_profile(profile.get_stream(rs.stream.depth))
depth_intrinsics = depth_profile.get_intrinsics()
```

**Comment by theNded** [comment]
Thanks for the clarification! I will close the issue now.
