### ISSUE TITLE
Fast depth to pointcloud

### ISSUE THREAD

**Issue by bumbastic** [isl-org/Open3D#6317]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I convert depth images to pointclouds up to 300 times pr. second. Is there any faster way than this:

auto pointcloud = geometry::PointCloud::CreateFromDepthImage(depth_, intrinsic_, extrinsic_, 1000.0, 10.0, 1,true);

or this:

auto pointcloud_t = t::geometry::PointCloud::CreateFromDepthImage(depth_t, intrinsic_t, extrinsic_t, 1000.0, 10.0, 1,false);

Is there anyway to do this more efficiently, e.g. on GPU using Open3d?

**Comment by theNded** [comment]
The latter one uses calls Unproject (https://github.com/isl-org/Open3D/blob/master/cpp/open3d/t/geometry/PointCloud.cpp#L942), which uses a GPU kernel (https://github.com/isl-org/Open3D/blob/master/cpp/open3d/t/geometry/kernel/PointCloudImpl.h#L41). 
It should be very fast already, so I think the bottleneck would probably be the IO of depth and its lifting from CPU to GPU. If you are unable to buffer all the depths into GPU memory, I think 300FPS would be hard to reach.

**Comment by bumbastic** [comment]
thanks for the tip!

by doing this:
        // Create an open3d::t::geometry::Image from camera frame data
        open3d::core::Tensor tensor(depth_frame->data(), open3d::core::Dtype::UInt16, { height, width, 1 }, {});
        open3d::t::geometry::Image open3d_image(tensor.To(open3d::core::Device("CUDA:0")));
        
        // Create pointcloud
        auto pointcloud_t = t::geometry::PointCloud::CreateFromDepthImage(open3d_image, intrinsic_t, extrinsic_t, 1000.0, 10.0, 1,false);

I can now create 1000+ clouds pr. second
