### ISSUE TITLE
How do use Open3D headless rendering in Ubuntu 22.04

### ISSUE THREAD

**Issue by jevonmao** [isl-org/Open3D#6322]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I am following http://www.open3d.org/docs/latest/tutorial/Advanced/headless_rendering.html for instructions for headless rendering. Because I installed Open3D in my Anaconda environment, I navigated to my `/mnt/NAS/home/jevonmao/anaconda3/envs/pytorch3d/lib/python3.9/site-packages/open3d` folder and did `mkdir build`, however, no cmakelist.txt file was generated, and the cmake command does not work. Anyone know what am I doing wrong?

**Comment by saurabheights** [comment]
Hi, you dont do mkdir build in conda.
```
Start with cloning repo.  # See this http://www.open3d.org/docs/latest/compilation.html
Next make a directory called build (name doesnt matter) inside Open3d repo. # Not inside conda
cd build
Run cmake .. # here you will have to add headless rendering flags as given in http://www.open3d.org/docs/latest/tutorial/Advanced/headless_rendering.html
Run make -j$(nproc)  # j$(nproc) is to run make on all cores. its just goes faster
Run make install-pip-package # to make pip package and install in your environment
```
[Wrote in hurry, quite late here]

**Comment by jevonmao** [comment]
@saurabheights Thank you so much for the fast response. Do I need to run `Run make install-pip-package` with a conda environment activated if I wish to install it into that?

**Comment by saurabheights** [comment]
@jevonmao yes. It will make a wheel package i think and will install it to conda environment (make sure the conda environment is activated first).

**Comment by ssheorey** [comment]
Hi @jevonmao I think you found an older method for headless rendering. We have added an easier to use method since then. Please give that a try. Here is an example:

http://www.open3d.org/docs/latest/python_example/visualization/index.html#render-to-image-py

**Comment by jevonmao** [comment]
@ssheorey I tried running that file, but got this error:
```
[Open3D INFO] EGL headless mode enabled.                                                                                                                                                                                                                                          
WARNING: Using soft CircularBuffer (6144 KiB)                                                                                                                                                                                                                                     
FEngine (64 bits) created at 0x7f4286b17010 (threading is enabled)                                                                                                                                                                                                                
eglInitialize failed                                                                                                                                                                                                                                                              
Segmentation fault (core dumped) 
```

Python 3.9.16; Open3D 0.17.0

**Comment by jevonmao** [comment]
@saurabheights I got this error when running `make -j$(nproc)`

```
make[3]: Leaving directory '/mnt/NAS/home/jevonmao/Open3D/build/embree/src/ext_embree-build'                                                                                                                                                                                      
cd /mnt/NAS/home/jevonmao/Open3D/build/embree/src/ext_embree-build && /usr/bin/cmake -E touch /mnt/NAS/home/jevonmao/Open3D/build/embree/src/ext_embree-stamp/ext_embree-install                                                                                                  
[ 25%] Completed 'ext_embree'                                                                                                                                                                                                                                                     
/usr/bin/cmake -E make_directory /mnt/NAS/home/jevonmao/Open3D/build/CMakeFiles                                                                                                                                                                                                   
/usr/bin/cmake -E touch /mnt/NAS/home/jevonmao/Open3D/build/CMakeFiles/ext_embree-complete                                                                                                                                                                                        
/usr/bin/cmake -E touch /mnt/NAS/home/jevonmao/Open3D/build/embree/src/ext_embree-stamp/ext_embree-done                                                                                                                                                                           
make[2]: Leaving directory '/mnt/NAS/home/jevonmao/Open3D/build'                                                                                                                                                                                                                  
[ 25%] Built target ext_embree                                                                                                                                                                                                                                                    
make[1]: Leaving directory '/mnt/NAS/home/jevonmao/Open3D/build'                                                                                                                                                                                                                  
make: *** [Makefile:156: all] Error 2     
```

**Comment by saurabheights** [comment]
@jevonmao You did not show the error log during the build.

Also, as ssheorey mentioned, it might be easier to try the new `OffscreenRenderer`. Try with latest development wheels, lets hope the bug you are facing `eglInitialize failed` is fixed there.

Just tested this, it worked in my system :-
```
conda create --name 6322 python=3.9 -y
conda activate 6322
pip install --trusted-host www.open3d.org -f http://www.open3d.org/docs/latest/getting_started.html open3d
cd examples/python/visualization/
python3 render_to_image.py 
```

**Comment by jevonmao** [comment]
@saurabheights I get same segmentation fault when using version 0.17.0+59792c2 in a new created conda environment. Let me know if there are other information I should provide, maybe something with my Ubunutu version can cause this?

**Comment by saurabheights** [comment]
I dont know what else I can do here. Minor suggestion - Try to build in docker. If the issue is from your system, it might help. Also, it will be easier for us to reproduce the issue using your dockerfile.

**Comment by jevonmao** [comment]
I was able to fix the issue with  conda install -c conda-forge gcc=12.1.0

**Comment by saurabheights** [comment]
My bad, I missed the first picture. I recently faced this issue as well. Posting for new users.

The library when compiled using cmake/make, uses your default C/C++ compiler, but when in conda, conda installs its own libgcc package. This was the cause of the error.

Since my conda environment was complete new, I just copied libstdC++ to conda environment instead of search for right package. but installing latest gcc package should solve the issue.

My quick hack -
```
# Note - I am using miniconda.
cp /usr/lib/x86_64-linux-gnu/libstdc++.so.6 ~/miniconda3/envs/test/bin/../lib/libstdc++.so.6
```

Also, you can use below command to see which versions are available.

```
strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep "GLIBCXX_3."
strings ~/miniconda3/envs/test/bin/../lib/libstdc++.so.6 | grep "GLIBCXX_3."
```
