### ISSUE TITLE
get_box_points gives only extent and center

### ISSUE THREAD

**Issue by LethargicDemigod** [isl-org/Open3D#6323]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

For an oriented bounding box the method get_box_points returns extent and center instead of the coordinates of the 8 points. 
I am unable to calculate  the points using the these two as it requires a 3x3 matrix to get the points. How do I get the matrix?

**Comment by saurabheights** [comment]
```
import numpy as np
import open3d as o3d

arr = np.random.rand(100,3)
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(arr[:, :3])

ob_box = pcd.get_oriented_bounding_box()
ob_box.color = [1.0, 0.0, 0.0]
print(np.asarray(ob_box.get_box_points()))

coordinate_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=1)
o3d.visualization.draw_geometries([coordinate_frame, pcd, ob_box])
```
This prints all 8 corners

```
[[ 1.03060319 -0.57130003  0.80234242]
 [ 1.75607099  0.49916865  0.49750028]
 [ 0.25757501 -0.35539826 -0.27917133]
 [ 0.09613423  0.30184522  1.64457345]
 [ 0.04857386  1.58821568  0.25821755]
 [-0.67689395  0.51774699  0.5630597 ]
 [ 0.82160203  1.37231391  1.33973131]
 [ 0.98304281  0.71507042 -0.58401347]]
 ```
 
 Also, could you edit title of the issue

**Comment by LethargicDemigod** [comment]
I am unable to get points in my program.
I have a stl file of a cylinder which i have converted to pointcloud format. On using the function(get_box_points) I am unable to get the points.
`import` open3d as o3d
import numpy as np
screw1=o3d.io.read_triangle_mesh('screw1.stl')
pcd1=screw1.sample_points_uniformly(number_of_points=5000)
box1 = pcd1.get_oriented_bounding_box()
box1.color = (1, 0, 0)
print(np.asarray(box1.get_box_points))
o3d.visualization.draw_geometries([pcd1,box1])
` 
it gives the result
<bound method PyCapsule.get_box_points of OrientedBoundingBox: center: (13.1851, -45.0987, -416.012), extent: 44.7982, 6.63329, 6.59058)>

**Comment by saurabheights** [comment]
You are not calling the function but just referring to bound method. 

`print(np.asarray(box1.get_box_points))` is missing paranetheses.

Change to 

`print(np.asarray(box1.get_box_points()))`
