### ISSUE TITLE
How to create a vector of KDTreeFlann in C++

### ISSUE THREAD

**Issue by PhuongNDVN** [isl-org/Open3D#6329]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

How to create a vector of KDTreeFlann in C++. I tried 

```
std::vector<open3d::geometry::KDTreeFlann> kdTrees;
for (int k = 0; k < num_geometries; k++) {
	auto geometry = geometries[k];
	open3d::geometry::KDTreeFlann kdTree(geometry);
	kdTrees.push_back(kdTree);
}
```

And then I got this error when compiling:
'open3d::geometry::KDTreeFlann::KDTreeFlann(const open3d::geometry::KDTreeFlann &)': attempting to reference a deleted function

**Comment by theNded** [comment]
KDTree does not support copy construction to avoid massive memory transferring, see the [implementation](https://github.com/isl-org/Open3D/blob/0f12276eb313456756425f3fbb00ad734bb88aed/cpp/open3d/geometry/KDTreeFlann.h#L50).
You can create a vector of `std::shared_ptr<KDTreeFlann>` instead.
