### ISSUE TITLE
WebRTC multiple windows in browser

### ISSUE THREAD

**Issue by chetan95** [isl-org/Open3D#6341]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

In the documentation shown [here](http://www.open3d.org/docs/release/tutorial/visualization/web_visualizer.html), the web browser animation shows two windows(window_1 at top and window_0 at bottom). How to achieve that? I tried using `o3d.visualization.draw(cube1)` and `o3d.visualization.draw(cube2)` to draw but it didn't worked. How can I create multiple windows at given position. Thanks in advance!

**Comment by saurabheights** [comment]
@chetan95 - The documentation is for jupyter/web based visualizer and it uses `from open3d.web_visualizer import draw` which is not the same as what you are using `o3d.visualization.draw`. Please can you provide full information (OS info, what you expect, what actually happened, etc.) on what you are trying to do?

**Comment by saurabheights** [comment]
![Screenshot from 2023-08-31 22-53-39](https://github.com/isl-org/Open3D/assets/11634769/add58b06-28f2-438a-bd56-db86b2577ff5)

**Comment by chetan95** [comment]
@saurabheights , I am on win10, and open3d version is 0.17.0. I am following [this](https://github.com/isl-org/Open3D/blob/master/examples/python/visualization/draw_webrtc.py) and trying to visualise in two windows. As shown in this image on the documentation page. 
![Screenshot 2023-09-01 110521](https://github.com/isl-org/Open3D/assets/22351363/18f57817-7756-4fd0-8013-8606ba12888e)
How to achieve this?
```
import open3d as o3d

if __name__ == "__main__":
    o3d.visualization.webrtc_server.enable_webrtc()
    cube_red = o3d.geometry.TriangleMesh.create_box(1, 2, 4)
    cube_red.compute_vertex_normals()
    cube_red.paint_uniform_color((1.0, 0.0, 0.0))
    o3d.visualization.draw(cube_red)

    # o3d.visualization.webrtc_server.enable_webrtc()
    cube_red1 = o3d.geometry.TriangleMesh.create_box(1, 2, 4)
    cube_red1.compute_vertex_normals()
    cube_red1.paint_uniform_color((0.0, 1.0, 0.0))
    o3d.visualization.draw(cube_red1)
```

I am getting only one window (titled-"window_0). How to get the other window as shown in the image on the documentation page.

**Comment by saurabheights** [comment]
@chetan95 

1. You are confusing usage of `o3d.visualization.draw` with `from open3d.web_visualizer import draw`. The two `draw` function are different.  If I am not wrong, `o3d.visualization.draw` is a blocking call, i.e. the code will wait for window to close (window created by `o3d.visualization.draw(cube_red)`).
2. I believe you only need to call enable_rtc once.

Try this:

```
import open3d as o3d
# o3d.visualization.webrtc_server.enable_webrtc()
from open3d.web_visualizer import draw
cube_red = o3d.geometry.TriangleMesh.create_box(1, 2, 4)
cube_red.compute_vertex_normals()
cube_red.paint_uniform_color((1.0, 0.0, 0.0))
draw(cube_red)
cube_blue = o3d.geometry.TriangleMesh.create_box(1, 2, 4)
cube_blue.compute_vertex_normals()
cube_blue.paint_uniform_color((0.0, 0.0, 1.0))
draw(cube_blue)
```
![Screenshot from 2023-09-01 15-33-03](https://github.com/isl-org/Open3D/assets/11634769/983dcb14-9d54-4d80-9a0d-e6974054a1a8)


Regarding blocking nature of `o3d.visualization.draw`, run below code:-

```
import open3d as o3d

if __name__ == "__main__":
    o3d.visualization.webrtc_server.enable_webrtc()
    cube_red = o3d.geometry.TriangleMesh.create_box(1, 2, 4)
    cube_red.compute_vertex_normals()
    cube_red.paint_uniform_color((1.0, 0.0, 0.0))
    o3d.visualization.draw(cube_red)

    print("Did I got printed? If not, the code below me has not yet executed.")  # <=== Your code will never reach here.
    # o3d.visualization.webrtc_server.enable_webrtc()
    cube_red1 = o3d.geometry.TriangleMesh.create_box(1, 2, 4)
    cube_red1.compute_vertex_normals()
    cube_red1.paint_uniform_color((0.0, 1.0, 0.0))
    o3d.visualization.draw(cube_red1)
```

**Comment by chetan95** [comment]
@saurabheights, thanks for the support and clarification.
