### ISSUE TITLE
Add pathlib support to IO methods in Python

### ISSUE THREAD

**Issue by evbernardes** [isl-org/Open3D#6344]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Proposed new feature or change

According to my tests with `Open3D 0.17` with `Python 3.10`, this is not yet implemented.

It would be nice if the reading/writing methods in Open3D supported `pathlib` as inputs, since this is the preferred way of dealing with system paths for many people. This way, instead of having to transform the path to a string:
```Python
from pathlib import Path
import open3d as o3d
path = Path('./Data/CAD/example.stl')
mesh = o3d.io.read_triangle_mesh(path.as_posix())
```
Or equivalently:
```Python
mesh = o3d.io.read_triangle_mesh(str(path))
```
We could just directly enter the `Path` object:
```Python
from pathlib import Path
import open3d as o3d
path = Path('./Data/CAD/example.stl')
mesh = o3d.io.read_triangle_mesh(path)
```
This is, of course, very minor and would just add a little convenience to the code. But this would also be pretty straightforward to implement, which is why I think it is worth it.

**Comment by ssheorey** [comment]
Definitely a good convenience feature and we would welcome community PRs for this.

**Comment by evbernardes** [comment]
@ssheorey I'm glad you agree! Do you think this is possible given the use of `pybind`? 

I have never used `pybind` so I'm not sure where to even start coding a PR for this, but maybe someone else will :)
