### ISSUE TITLE
Cant install the library.

### ISSUE THREAD

**Issue by MYusufY** [isl-org/Open3D#6346]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [ ] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

When im trying to install it with pip, pip3 I get this error:

ERROR: Could not find a version that satisfies the requirement open3d (from versions: none)
ERROR: No matching distribution found for open3d

Im trying to install it with wheel, but I cant find the correct wheel for my computer. My computer is MacOS 12, x64. But when I say most similar ones, like:
open3d-0.17.0-1fix6008-cp39-cp39-macosx_12_0_arm64.whl
open3d-0.17.0-cp39-cp39-macosx_12_0_arm64.whl
open3d-0.17.0-cp310-cp310-macosx_11_0_x86_64.whl
I got this error:
ERROR: xxxxxxx.whl is not a supported wheel on this platform.

Am I missing something? 
Is there a .whl file for MacOS 12 x64?

(Python 3.11.4)

Can anyone help? Thanks!

**Comment by johnthagen** [comment]
Please follow/ 👍: 

- #5620

Open3D does not yet support Python 3.11 and as such has not published 3.11 wheels onto PyPI.

I would recommend installing and using Python 3.10. A macOS 3.10 installer is available at [python.org](https://www.python.org/downloads/release/python-31011/).

**Comment by johnthagen** [comment]
3.11 wheels have been published with 0.18:

- https://github.com/isl-org/Open3D/pull/6288#issuecomment-1878030429

This issue can be closed.
