### ISSUE TITLE
Segmentation Fault when using open3d::t::io::ReadImageFromPNG

### ISSUE THREAD

**Issue by feendres** [isl-org/Open3D#6363]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi everybody,

I have written some c++ code using Open3d. And i encounter a problem when i use open3d::t::io::ReadImageFromPNG to read in a depth image. The important code snippet is:
```

open3d::core::Device device;
            if (use_gpu)
            {
                device = open3d::core::Device("CUDA:0");
            }
            else
            {
                device = open3d::core::Device("CPU:0");
            }

            open3d::t::geometry::Image depth_img(img_rgb.rows, img_rgb.cols, 1, open3d::core::UInt16, device);

            if (!open3d::t::io::ReadImageFromPNG(depthImagePath, depth_img))
            {
                std::cout << "Failed to read depth image: " << depthImagePath << endl;
                continue;
            }
```

When the device is CPU:0 everything is working fine. When i want to use the GPU i get an Segmentation Fault error. The Call Stack is:

libc.so.6!__memmove_avx_unaligned_erms() (/build/glibc-SzIz7B/glibc-2.31/sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:262)
libOpen3D.so!png_combine_row (Unknown Source:0)
libOpen3D.so!png_image_read_direct (Unknown Source:0)
libOpen3D.so!png_safe_execute (Unknown Source:0)
libOpen3D.so!png_image_finish_read (Unknown Source:0)
libOpen3D.so!open3d::t::io::ReadImageFromPNG(const std::string & filename, open3d::t::geometry::Image & image) (/home/fe/sourcecode/Open3D_debug/cpp/open3d/t/io/file_format/FilePNG.cpp:62)
main(int argc, char ** argv) (/home/fe/sourcecode/grass_dataset/topview_script/src/topview.cpp:186)

I built open3d from source with CUDA_MODULE and i had no problems while building. My first idea was that the GPU RAM (4 GB) was too small for the big depth image (4096x3072) but i tried a smaller image and i had the same problem. 

If you need additional information, let me know and i try to provide it.

Thanks in advance!

**Comment by saurabheights** [comment]
@feendres Open3d uses libpng to read and write png. The code doesnt support reading to an Image on gpu right now. See [here](https://github.com/saurabheights/Open3D/blob/master/cpp/open3d/io/file_format/FilePNG.cpp#L62) where decompressed image data is copied to tensor data. Ideally there should be a check here to see if tensor is in gpu and then transfer data to gpu, but it wont provide any benefits compared to reading png to CPU image and then transferring to [gpu](http://www.open3d.org/docs/release/python_api/open3d.t.geometry.Image.html#open3d.t.geometry.Image.cuda).

**Comment by feendres** [comment]
Thank you a lot. This was the information i needed.
