### ISSUE TITLE
How to get color image when using ray casting?

### ISSUE THREAD

**Issue by zhanghua7099** [isl-org/Open3D#6367]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi! Thanks for building this amazing project. I have some questions about the ray casting module.

http://www.open3d.org/docs/release/python_example/geometry/ray_casting/index.html#ray-casting-to-image-py

This demo gives a method to access the depth image. I also want to get the RGB image when using ray casting. Could you please give me some suggestions?

**Comment by benjaminum** [comment]
`cast_rays` returns information about the triangle that was hit (`primitive_ids`) and the uv coordinates of the hit within the triangle (`primitive_uvs`). You can use these to interpolate vertex colors or look up color values in a texture.
http://www.open3d.org/docs/release/python_api/open3d.t.geometry.RaycastingScene.html#open3d.t.geometry.RaycastingScene.cast_rays

An alternative of writing a renderer with `RaycastingScene` is to use the visualization module. Here is an example http://www.open3d.org/docs/release/python_example/visualization/index.html#render-to-image-py

**Comment by zhanghua7099** [comment]
Thank you very much!
