### ISSUE TITLE
How delete coordinate axes from visualization 

### ISSUE THREAD

**Issue by ostepan2006** [isl-org/Open3D#6368]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hello Team.

The code like this 
```
vis = o3d.visualization.Visualizer()
vis.create_window(window_name="Point Cloud")
vis.add_geometry(self.pcl)
origin = o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.3, origin=[0, 0, 0])  
vis.add_geometry(origin)
```

 create open3d window with huge coordinate axes (see picture below).

![image](https://github.com/isl-org/Open3D/assets/50662491/ca7544cf-7df6-474d-8a62-d3c3b04746f4)

How make this coordinate axes invisible? Thanks

**Comment by saurabheights** [comment]
@ostepan2006 When you do `vis.add_geometry(origin)`, it adds the coordinate system axes to visualizer. Just use remove_geometry to remove it.

`vis.remove_geometry(origin)`

**Comment by ostepan2006** [comment]
> @ostepan2006 When you do `vis.add_geometry(origin)`, it adds the coordinate system axes to visualizer. Just use remove_geometry to remove it.
> 
> `vis.remove_geometry(origin)`

Thank for your answer. Yes, using your code the axes had disapeared but a point cloud had disapeared also! This is not what I want.

**Comment by saurabheights** [comment]
@ostepan2006 If possible, create a reproducible code so we can see what issue you are facing.

You can also try passing `reset_bounding_box=False`, i.e. `vis.remove_geometry(origin, reset_bounding_box=False)` to prevent any window viewport adjustment when object is removed.

**Comment by benjaminum** [comment]
@ostepan2006 Removing `origin` or not adding it as suggested by @saurabheights will give the result you expect.
Closing this issue but don't hesitate to comment if there are still problems.
