### ISSUE TITLE
Difference between `open3d.visualization.draw_geometries()` and `open3d.visualization.draw()`?

### ISSUE THREAD

**Issue by ssh98son** [isl-org/Open3D#6375]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [x] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi, I found a function `open3d.visualization.draw()` which is not shown in the official [documentation](http://www.open3d.org/docs/release/python_api/open3d.visualization.html) from this example [to_mitsuba](http://www.open3d.org/docs/release/python_example/visualization/index.html#to-mitsuba-pyl) and found out that it results in the different rendering style.

I was not able to find any documentation for this. Where can I find the documentation for `open3d.visualization.draw()` function?
![draw()](https://github.com/isl-org/Open3D/assets/50664072/beae5087-0501-41e1-8306-11886fa12055)
![draw_geometries()](https://github.com/isl-org/Open3D/assets/50664072/10d45880-799c-4169-bbd6-e541f16dd667)

**Comment by saurabheights** [comment]
The documentation is available in latest release of documentation - http://www.open3d.org/docs/latest/python_api/open3d.visualization.html
