### ISSUE TITLE
Why the number of point clouds is not the same with image resolution?

### ISSUE THREAD

**Issue by Matthew-CQ** [isl-org/Open3D#6379]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi, 

There is one RGB image and one depth image whose resolution is 1920 and 1080. I got `PointCloud on CPU:0 [1797402 points (Float32)].` instead of  1920\*1080 = 2073600 even set `depth_max` to a max number. 

The version of my open3d is 0.17.0. Code shows below,

```python
rgb_image = o3d.t.io.read_image('./rgb.png')
depth_image = o3d.t.io.read_image('./depth.png')
rgbd_image = o3d.t.geometry.RGBDImage(rgb_image, depth_image,aligned=False)
intrinsic = o3d.camera.PinholeCameraIntrinsic()
intrinsic.set_intrinsics(1920, 1080, 1359.1513671875, 1359.3175048828125, 975.1362915039062, 536.2861328125)
intrinsic_t = o3d.core.Tensor(intrinsic.intrinsic_matrix)
point_cloud = o3d.t.geometry.PointCloud.create_from_rgbd_image(rgbd_image, intrinsic_t,depth_max=100000000000000)
```

Looking forward to your answers, thank you.

**Comment by yuecideng** [comment]
HI @Matthew-CQ , the `create_from_rgbd_image ` API of the tensor based pointcloud will only return the valid value, which means the nan or inf value will be removed. Please see `UnprojectCUDA` kernel in https://github.com/isl-org/Open3D/blob/master/cpp/open3d/t/geometry/kernel/PointCloudImpl.h.
