### ISSUE TITLE
Erroneous cone TriangleMesh following translation

### ISSUE THREAD

**Issue by PhilNad** [isl-org/Open3D#6390]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

When translating a TriangleMesh cone made with o3d.geometry.TriangleMesh.create_cone(), the shape is not correctly translated with TriangleMesh.translate().

### Steps to reproduce the bug

```python
Python 3.8.10 (default, May 26 2023, 14:05:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import open3d as o3d
>>> import numpy as np
>>> o3d.__version__
'0.17.0'
>>> cone = o3d.geometry.TriangleMesh.create_cone(radius=0.5, height=1.0)
>>> cone.translate((0, 0, 0.5))
TriangleMesh with 22 points and 40 triangles.
>>> np.asarray(cone.vertices)[:,2]
array([0.45454545, 1.45454545, 0.45454545, 0.45454545, 0.45454545,
       0.45454545, 0.45454545, 0.45454545, 0.45454545, 0.45454545,
       0.45454545, 0.45454545, 0.45454545, 0.45454545, 0.45454545,
       0.45454545, 0.45454545, 0.45454545, 0.45454545, 0.45454545,
       0.45454545, 0.45454545])
>>>
```

### Expected behavior

The height of the vertices should be between 0.5 and 1.5, but they are significantly off (i.e. between 0.45454545 and 1.45454545) as shown in the example above.

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04
- Python version: Python 3.8.10
- Open3D version: 0.17.0
- System architecture: x86
- Is this a remote workstation?: no
- How did you install Open3D?: pip
```

**Comment by saurabheights** [comment]
@PhilNad Use `cone.translate((0, 0, 0.5), relative=True)`. 

I am not sure why you are facing this issue though. The default value for relative is `True` since 3 years ago. Try installing latest version from http://www.open3d.org/docs/latest/getting_started.html#development-version-pip

```
cone = o3d.geometry.TriangleMesh.create_cone(radius=0.5, height=1.0)
cone.translate((0, 0, 0.5), relative=True)
Out[24]: TriangleMesh with 22 points and 40 triangles.
np.asarray(cone.vertices)[:,2]
Out[25]: 
array([0.5, 1.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5])
cone = o3d.geometry.TriangleMesh.create_cone(radius=0.5, height=1.0)
cone.translate((0, 0, 0.5), relative=False)
Out[27]: TriangleMesh with 22 points and 40 triangles.
np.asarray(cone.vertices)[:,2]
Out[28]: 
array([0.45454545, 1.45454545, 0.45454545, 0.45454545, 0.45454545,
       0.45454545, 0.45454545, 0.45454545, 0.45454545, 0.45454545,
       0.45454545, 0.45454545, 0.45454545, 0.45454545, 0.45454545,
       0.45454545, 0.45454545, 0.45454545, 0.45454545, 0.45454545,
       0.45454545, 0.45454545])
cone = o3d.geometry.TriangleMesh.create_cone(radius=0.5, height=1.0)
cone.translate((0, 0, 0.5))  # Default value for relative is True
Out[30]: TriangleMesh with 22 points and 40 triangles.
np.asarray(cone.vertices)[:,2]
Out[31]: 
array([0.5, 1.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5])
```

**Comment by PhilNad** [comment]
Specifying `relative=True` fixed the issue. Not sure why I was getting this as it is the default option, closing this for now.
