### ISSUE TITLE
How to customise Open3D web visualizer?

### ISSUE THREAD

**Issue by joshuatjy** [isl-org/Open3D#6393]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

This is the Python code (draw_webrtc.py) I used to launch the web visualiser:
```
import open3d as o3d
import webbrowser

if __name__ == "__main__":
    o3d.visualization.webrtc_server.enable_webrtc()
    webbrowser.open("http://localhost:8888")
    cube_red = o3d.geometry.TriangleMesh.create_box(1, 2, 4)
    cube_red.compute_vertex_normals()
    cube_red.paint_uniform_color((1.0, 0.0, 0.0))
    o3d.visualization.draw(cube_red)
```

This is what the web visualiser looks like:
![image](https://github.com/isl-org/Open3D/assets/122354647/c50fe3d3-4148-4ca3-8d20-5516ec9e26e9)

I want to customise the web visualiser interface such that the user can perform processing to the 3D object within the webpage without needing to edit the Python code (I want to create a user-friendly interface for 3D point cloud processing). For example, I want to change the PointSize slider functionality, whereby it could change the colour or rotation of the box by passing the PointSize variable to the Python code.

However, I could not find the source code for the embedded GUI of the web visualiser in my Open3D directory, even though I found the HTML source code in "..\Lib\site-packages\open3d\resources\html". How can I find the web visualiser GUI's source code so that I can pass the data to the Python file for processing?

**Comment by saurabheights** [comment]
See https://github.com/isl-org/Open3D/blob/master/cpp/pybind/visualization/webrtc_server/webrtc_window_system.cpp

This code generates python binding. The actual code is in C++ here - https://github.com/isl-org/Open3D/tree/master/cpp/open3d/visualization/webrtc_server

**Comment by joshuatjy** [comment]
Hi @saurabheights, from what I could understand from the code, the JavaScript would communicate to the C++ file by sending a message to `webrtc_window_system.cpp`, which then uses Python binding to pass it to the Python file.

I could not locate the `PointSize` label in the C++ file. Do I need to compile the .cpp file into .exe? (Any tutorials, if so?)

**Comment by joshuatjy** [comment]
I can customize the web visualizer by including `o3d.visualization.webrtc_server.enable_webrtc()` in the Python code with the Visualization object.

**Comment by joshuatjy** [comment]
I can customize the web visualizer by including o3d.visualization.webrtc_server.enable_webrtc() in the Python code with the Visualization object.
