### ISSUE TITLE
Are there any differences in the implementation of segment_plane between different versions of Open3d?

### ISSUE THREAD

**Issue by RyoKageyama** [isl-org/Open3D#6398]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

In a program that uses segment_plane to extract a plane from a point cloud using RANSAC, the results vary greatly between Open3d version 0.13.0 and the latest version, even though the same point cloud data and parameters are given. The difference is more than a small error due to randomness in the process of plane estimation. Is there anything you have changed in your implementation?

**Comment by yuecideng** [comment]
Hi @RyoKageyama , did you check the latest docs? 
link: http://www.open3d.org/docs/release/tutorial/t_geometry/pointcloud.html#Plane-segmentation

**Comment by yuecideng** [comment]
Close due to lack of discuss. Welcome to reopen if any problem you have.
