### ISSUE TITLE
Weird visualization of Oriented Bounding Box

### ISSUE THREAD

**Issue by suptimq** [isl-org/Open3D#6401]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Question
I am very confused as to why the `min_bound` and `max_bound` from the `oriented_bounding_box` are neither in the bounding box nor in the point cloud.

### Code
```python
import open3d as o3d

bunny = o3d.data.BunnyMesh()
mesh = o3d.io.read_triangle_mesh(bunny.path)
mesh.compute_vertex_normals()

pcl = mesh.sample_points_poisson_disk(number_of_points=2000)

oriented_bounding_box = pcl.get_oriented_bounding_box()
min_bound = oriented_bounding_box .get_min_bound()
max_bound = oriented_bounding_box .get_max_bound()

# Create a visualization window
vis = o3d.visualization.Visualizer()
vis.create_window()

vis.add_geometry(pcl)

# Create a bounding box visualization
bbox_line_set = o3d.geometry.LineSet.create_from_oriented_bounding_box(oriented_bounding_box)
bbox_line_set.paint_uniform_color([1, 0, 0])  # Set bounding box color to red
vis.add_geometry(bbox_line_set)

sphere = o3d.geometry.TriangleMesh.create_sphere(radius=0.002)
sphere.paint_uniform_color([0, 1, 0])  # Set the color of the spheres
sphere.translate(min_bound)
vis.add_geometry(sphere)

sphere = o3d.geometry.TriangleMesh.create_sphere(radius=0.002)
sphere.paint_uniform_color([0, 1, 0])  # Set the color of the spheres
sphere.translate(max_bound)
vis.add_geometry(sphere)

# Set the view control (optional)
view_control = vis.get_view_control()
view_control.rotate(0.0, 500.0)

# Run the visualization
vis.run()

# Close the visualization window when done
vis.destroy_window()
```

### Result

The green dots are `min_bound` and `max_bound`.

![image](https://github.com/isl-org/Open3D/assets/29498118/d685b909-cca1-4873-8500-64999872b268)

**Comment by saurabheights** [comment]
@suptimq The idea of min bound (and similarly for maximum bound) is to find smallest value of x, y, z such that the **cuboid** made from min_bound and max_bound as the corners, will contain the geometry (oriented_bounding_box).

```

# Your code
oriented_bounding_box = pcl.get_oriented_bounding_box()
min_bound = oriented_bounding_box.get_min_bound()
max_bound = oriented_bounding_box.get_max_bound()

print(min_bound)
print(max_bound)

# My Code
print(np.asarray(oriented_bounding_box.get_box_points()))

print(np.min(np.asarray(oriented_bounding_box.get_box_points()), axis=0))
print(np.max(np.asarray(oriented_bounding_box.get_box_points()), axis=0))
```


![Screenshot from 2023-10-03 16-49-12](https://github.com/isl-org/Open3D/assets/11634769/721d068a-4f54-4c98-a302-48ce8941e714)

**Comment by suptimq** [comment]
Thanks! Is there any way I can get the coordinates of the corners of the oriented bounding box? Especially, when using `get_minimal_oriented_bounding_box`. I guess what I meant is to get the corners that "intersect" with the objects if that makes sense.

**Comment by saurabheights** [comment]
@suptimq If I understood correctly, `get_minimal_oriented_bounding_box` also returns `OrientedBoundingBox` just like `get_oriented_bounding_box`, so you can use `print(np.asarray(oriented_bounding_box.get_box_points()))` to get all corners. Regarding which corner is on the pointcloud, for that you should check distance of each corner with whole pointcloud.

**Comment by suptimq** [comment]
@saurabheights Thanks so much! That makes sense! Close it for now.
