### ISSUE TITLE
Why the cropped rgb and the cropped depth produce weird pointcloud? Amazing...

### ISSUE THREAD

**Issue by myalos** [isl-org/Open3D#6403]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Recently, i wrote a simple program to display the pointcloud of one color-depth image pair getting from depth camera, and it worked as expected.
![ScreenCapture_2023-10-02-17-43-30](https://github.com/isl-org/Open3D/assets/77491386/05503952-3b4f-4be9-ac89-60fa06d7dd32)
Then i wanted to crop the image to 1024*1024 and see the pointcloud of the cropped version. I used the code below
```python
def cloudcrop():
	original_img = cv2.imread('save/img3.png', -1)
	original_depth = cv2.imread('save/depth3.png', -1)
        # crop the image from 1920x1080 to 1024x1024
	crop_img = original_img[56:, 448:-448, :]
	crop_depth = original_depth[56:, 448:-448]
	crop_img_rgb = cv2.cvtColor(crop_img, cv2.COLOR_BGR2RGB)
	_display_pointcloud(crop_img_rgb, crop_depth, width = 1024, height = 1024, offsety = 56, offsetx=448)


def _display_pointcloud(color_image, depth_image, width=1920, height=1080, 
	fx=901.84, fy=901.56, cx=957.18, cy=549.10, offsetx = 0, offsety = 0):
	intrinsic = o3d.camera.PinholeCameraIntrinsic()
        # change the camera_intrinsics accordingly
	intrinsic.set_intrinsics(width, height, fx, fy, cx-offsetx, cy-offsety)
	depth_o3d = o3d.geometry.Image(depth_image)
	color_o3d = o3d.geometry.Image(color_image)
	rgbd_image = o3d.geometry.RGBDImage.create_from_color_and_depth(
			color_o3d, 
			depth_o3d, 
			depth_scale=1000, 
			depth_trunc=3.0, 
			convert_rgb_to_intensity=False)
	pcd = o3d.geometry.PointCloud.create_from_rgbd_image(rgbd_image, intrinsic)
	pcd.transform([[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0],
                    [0, 0, 0, 1]])
	o3d.visualization.draw_geometries([pcd])
```
And it produced the following point cloud
![ScreenCapture_2023-10-02-17-48-18](https://github.com/isl-org/Open3D/assets/77491386/7c711f08-3812-470a-92d2-681ab29ee3e4)
The change made to intrinsics is supposed to correct, and i cannot figure out why the pointcloud made from cropped image-depth pair perform so badly.

**Comment by saurabheights** [comment]
@myalos please share the full reproducible code with sample data, it helps to quickly check the issue on our end

**Comment by myalos** [comment]
@saurabheights Thanks for reply, and the full reproducible code is as follows.
```python
import os
import numpy as np
import open3d as o3d
import cv2


def _display_pointcloud(color_image, depth_image, width=1920, height=1080, 
	fx=901.84, fy=901.56, cx=957.18, cy=549.10, offsetx = 0, offsety = 0):
    intrinsic = o3d.camera.PinholeCameraIntrinsic()
    # change the camera_intrinsics accordingly
    intrinsic.set_intrinsics(width, height, fx, fy, cx-offsetx, cy-offsety)
    depth_o3d = o3d.geometry.Image(depth_image)
    color_o3d = o3d.geometry.Image(color_image)
    rgbd_image = o3d.geometry.RGBDImage.create_from_color_and_depth(
	    color_o3d, 
	    depth_o3d, 
	    depth_scale=1000, 
	    depth_trunc=3.0, 
	    convert_rgb_to_intensity=False)
    pcd = o3d.geometry.PointCloud.create_from_rgbd_image(rgbd_image, intrinsic)
    pcd.transform([[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0],
                      [0, 0, 0, 1]])
    o3d.visualization.draw_geometries([pcd])


def cloud(): # works as expected
    original_img = cv2.imread('save/img3.png', -1)
    original_depth = cv2.imread('save/depth3.png', -1)
    original_img_rgb = cv2.cvtColor(original_img, cv2.COLOR_BGR2RGB)
    _display_pointcloud(original_img_rgb, original_depth)


# performs weried
def cloudcrop():
    original_img = cv2.imread('save/img3.png', -1)
    original_depth = cv2.imread('save/depth3.png', -1)
    # crop the image from 1920x1080 to 1024x1024
    crop_img = original_img[56:, 448:-448, :]
    crop_depth = original_depth[56:, 448:-448]
    crop_img_rgb = cv2.cvtColor(crop_img, cv2.COLOR_BGR2RGB)
    _display_pointcloud(crop_img_rgb, crop_depth, width = 1024, height = 1024, offsety = 56, offsetx=448)


if __name__ == '__main__':
    cloud()
    cloudcrop()
```

![img3](https://github.com/isl-org/Open3D/assets/77491386/4e9c8760-ed2a-4e73-b9b8-e92ffe5aab14)
![depth3](https://github.com/isl-org/Open3D/assets/77491386/fe1d93ee-6119-4e8d-9df5-fd502a0e8a46)

**Comment by myalos** [comment]
i find the answer!!! if i add `crop_depth = np.ascontiguousarray(crop_depth)` then the pointcloud looks as expected. OwO

**Comment by saurabheights** [comment]
@myalos Thanks for sending the images and code to reproduce the error.

The issue is not in computing intrinsic matrix but due to cropping of image which is done via slicing of numpy array. In numpy, slicing does not create a copy of the underlying data, which means the new cropped image stores its data in a **non-contiguous memory**. 

Add the below two lines  to your method `_display_pointcloud`
```
    depth_image = np.ascontiguousarray(depth_image)
    color_image = np.ascontiguousarray(color_image)
```

**Comment by saurabheights** [comment]
@ssheorey Shouldnt non-contiguous memory be internally handled via Open3d? If so, can you add bug label and leave the issue open.

**Comment by ssheorey** [comment]
Hi @saurabheights yes this does look like a bug. The Eigen based API does not handle non-contiguous images. In the new Tensor API, for example, trying to initialize an Image with a non-contiguous array results in this error:

```py
    depth_o3d = o3d.t.geometry.Image(depth_image)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: [Open3D Error] (open3d::t::geometry::Image::Image(const core::Tensor &)) /Users/ssheorey/Documents/Open3D/Code/Open3D/cpp/open3d/t/geometry/Image.cpp:42: Input tensor must be contiguous.
```
Added an error message in PR #6406 for consistency with Tensor API.
