### ISSUE TITLE
Convert current o3d camera to Mitsuba

### ISSUE THREAD

**Issue by SamTov** [isl-org/Open3D#6418]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I have a conversion between o3d and mitsuba, but I want to use it to render videos. However, before the rendering starts, I would like to be able to rotate my scene to find the right angle and then port this camera view to mitsuba. However, I have been having the problem that when I try to set the Mitsuba view_matrix using the view_matrix from open3d I see nothing. I guess this is due to a sign convention but I can't seem to solve it. 

Does anyone have a good method for converting o3d camera views into mitsuba camera views?

**Comment by SamTov** [comment]
Trial and error seemed to work:

```python
camera_position = view_matrix[:3, 3]
        forward_direction = view_matrix[:3, 2]
        camera_target = -1 * camera_position + forward_direction
        up_direction = view_matrix[:3, 1]

        view_matrix = mi.ScalarTransform4f.look_at(
            origin=camera_position, target=camera_target, up=up_direction
            )
        self.scene_dict['sensor']['to_world'] = view_matrix
```
The trick was the negation of the camera position.

**Comment by ajktym94** [comment]
How can I use a `view_matrix` to change the camera position using `look_at`? Everything looks fine except for the `camera` vector. How can I obtain the camera vector from the view_matrix returned from `widget3d.scene.camera.get_view_matrix()` ?

**Comment by SamTov** [comment]
It would be really nice to get some feedback from the Open3D team here.  It is great that you have a plugin to Mitsuba but as it currently stands, you can't be sure of what you are rendering when you use it as the cameras are not the same. This makes the feature, in many ways, unusable.

**Comment by SamTov** [comment]
After a long time, ChatGPT has been improved enough that it could mostly solve this question. The conversion is below:

```python
def _update_camera(self, view_matrix: np.ndarray) -> None:
        """
        Update the camera to look at the mesh center.

        Parameters
        ----------
        view_matrix : np.ndarray
            View matrix for the camera from open3d.

        Notes
        -----
        This function updates the camera in the scene_dict.
        It should be called before rendering.
        """
        to_world_matrix = np.linalg.inv(view_matrix)

        # Step 2: Adjust the coordinate system by flipping the Z-axis
        z_flip_matrix = np.array(
            [[-1, 0, 0, 0], [0, 1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]]
        )
        adjusted_to_world_matrix = np.dot(to_world_matrix, z_flip_matrix)

        self.scene_dict["sensor"]["to_world"] = mi.ScalarTransform4f(
            adjusted_to_world_matrix
        )
```

@ajktym94 might be helpful although not a look at transform.
