### ISSUE TITLE
Is it possible to create a depth image with no visualization window? 

### ISSUE THREAD

**Issue by DrewScatterday** [isl-org/Open3D#6423]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

## Question: 
Is it possible to create a depth image with no visualization window? I want to create a depth image from a ply mesh and then save it as a numpy array. 

## My code: 
```python
import open3d as o3d
import numpy as np
import matplotlib.pyplot as plt

pcd = o3d.io.read_triangle_mesh("C:/Users/dre11620/Downloads/data/merged/floor1crop_mesh.ply")
vis = o3d.visualization.Visualizer()
vis.create_window()
vis.add_geometry(pcd)
vis.run()
depth = vis.capture_depth_float_buffer()
vis.destroy_window()
plt.imshow(np.asarray(depth))
plt.show() 
```
![Screen Shot 2023-10-10 at 3 20 41 PM](https://github.com/isl-org/Open3D/assets/28267620/ebaedf2c-9318-457b-a2d9-d6b60be7d9bb)

This works great! But requires me to manually close out of the visualizer window for the script to continue executing. I'd like this to just run and not have to manually interact with a window. It would be great if no window gets rendered or I can write some code to automatically close out of the window after it opens

## What I've tried: 
- `vis.create_window(visible=False)` - this did not work, the shell just runs forever since the window is open in the background and needs to be closed out 
-  I've seen this page [here](https://open3d.org/docs/release/tutorial/visualization/headless_rendering.html) and this page [here](https://stackoverflow.com/questions/69696354/capture-depth-image-without-opening-visualizer-in-open3d) which both use headless rendering but this seems to be only supported on ubuntu? I'm on a Windows and would prefer to use that. I do have docker and WSL installed but would prefer to use Windows since there are other things in my environment that depend on Windows 
- `vis.close()` - tried to manually close out of the window so the script would continue executing but this did not work either

**Comment by DrewScatterday** [comment]
I figured out a workaround using this response https://stackoverflow.com/questions/62599095/how-can-i-extract-picture-from-open3d

It seems to auto close out of the visualizer window by using the `vis.update_geometry(pcd)`, `vis.poll_events()`, and `vis.update_renderer()`

Is there a better way to do this? For now my code is this: 

```python 
pcd = o3d.io.read_triangle_mesh("C:/Users/dre11620/Downloads/Meta/data/merged/floor1crop_mesh.ply")
vis = o3d.visualization.Visualizer()
vis.create_window()
vis.add_geometry(pcd)
vis.update_geometry(pcd)
vis.poll_events()
vis.update_renderer()
depth = vis.capture_depth_float_buffer()
vis.destroy_window()
plt.imshow(np.asarray(depth))
plt.show()
```

**Comment by benjaminum** [comment]
Please check the example for headless rendering
http://www.open3d.org/docs/latest/tutorial/visualization/headless_rendering.html
https://github.com/isl-org/Open3D/blob/master/examples/python/visualization/headless_rendering.py

Another option is to use the RaycastingScene class
http://www.open3d.org/docs/latest/tutorial/geometry/ray_casting.html

**Comment by DrewScatterday** [comment]
Thanks for the reply! Headless is only supported on linux correct? 

The workaround above works for me but I'll take a look at the raycasting scene class as well

**Comment by errissa** [comment]
@DrewScatterday The new visualization API has support for true headless rendering (hardware accelerated and CPU-based) of both color and depth images. [This](https://github.com/isl-org/Open3D/blob/master/examples/python/visualization/render_to_image.py) example shows the basics and you can read more [here](http://www.open3d.org/docs/release/tutorial/visualization/cpu_rendering.html).

**Comment by ajzhai** [comment]
Hi @errissa the links you posted are only for CPU rendering right? For GPU should we follow @benjaminum 's links?

**Comment by DrewScatterday** [comment]
@errissa Thanks for taking the time to reply! 

That looks like what I'm looking for but unfortunately I have some dependencies that rely on Windows and that looks like its only for linux unless I'm missing something

**Comment by errissa** [comment]
@ajzhai Actually, no. If you use the new visualizer on a headless system with a GPU the rendering will happen on the GPU.

@DrewScatterday Unfortunately, you are correct - the headless rendering for the new visualizer is Linux only.

**Comment by ajzhai** [comment]
@errissa Thanks for the clarification! One more question: the `OffscreenRenderer.render_to_depth_image()` returns values from 0 (near plane) to 1 (far plane). How can I scale this to absolute metric depth?

**Comment by jerome-godbout-lychens** [comment]
Side info, I get the same error message for Mac OS, so this is Linux only, maybe the doc should specify this.
