### ISSUE TITLE
How to keep drawing geometry independant on view point ? 

### ISSUE THREAD

**Issue by ClementLeBihan** [isl-org/Open3D#6427]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi all,

I've tried to use O3DVisualizer with LineSet but the geometry disapear regarding the view point. Is there a way to force drawing every geometries ? 

Thanks by advance,
Clément

![open3d](https://github.com/isl-org/Open3D/assets/12940019/1697d838-265b-4c12-849b-59371032cc7e)

**Comment by errissa** [comment]
That looks like a bug - the line sets should render as long as they are in view. In the C++ API there is a way to disable culling for an individual object which would workaround this issue but it appears it's not exposed in Python.
