### ISSUE TITLE
when updating from 0.15.2 to 0.17.0 the view_control isnt working as intended

### ISSUE THREAD

**Issue by MeyerBuaharon** [isl-org/Open3D#6441]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

When i use the functions set_zoom, set_front, set_lookat and set_up the visualizer doesnt updated

### Steps to reproduce the bug

```python
import open3d as o3d

vis = o3d.visualization.Visualizer()
vis.create_window()
pcd = o3d.io.read_point_cloud("./plys/ply_1686820302372493_1686820302391192.ply")
vis.add_geometry(pcd)
view_control = vis.get_view_control()
view_control.set_front([-0.97416365542348959, -0.14587173476779827, -0.17241406395006686])
view_control.set_lookat([122.89483259200497, 20.648749189081677, 14.268473987450873])
view_control.set_up([0.19796650538250629, -0.18412268554588415, -0.96276066569735264])
view_control.set_zoom(0.35999999999999965)
vis.run()
```

### Error message

no error

### Expected behavior

to move the camera to the written coordinates. works fine in 0.15.2, doesnt work at 0.17.0

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04 
- Python version: Python 3.8`
- Open3D version: output from python:0.17.0
- System architecture: x86
- Is this a remote workstation?: no
- How did you install Open3D?: pip
```

**Comment by saurabheights** [comment]
@MeyerBuaharon The bug has been fixed and the issue is resolved if you install latest development wheels.
