### ISSUE TITLE
How to compute Vertex UVs?

### ISSUE THREAD

**Issue by chisarie** [isl-org/Open3D#6465]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi, I need to compute vertex uvs. I have seen the `compute_uvatlas()` function, but it seems that it computes *triangles uvs*. Is there a way to get vertex uvs instead? This is the snippet I am using right now:

```python
# Get UV Atlas (only available for tensor mesh)
o3d_mesh = o3d.t.io.read_triangle_mesh(str(mesh_path))
o3d_mesh.compute_uvatlas()
vertices = o3d.core.Tensor.numpy(o3d_mesh.vertex.positions)  # shape: (200, 3)
triangles = o3d.core.Tensor.numpy(o3d_mesh.triangle.indices)  # shape: (396, 3)
triangle_uvs = o3d.core.Tensor.numpy(o3d_mesh.triangle.texture_uvs)  # shape: (396, 3, 2)

vertex_uvs = ???  # shape: (200, 2)
```

Thank you very much

**Comment by yuecideng** [comment]
Hi @chisarie , try the following code:

```python
ids, _ = np.unique(triangles.numpy(), return_index=True)
flatten_uvs = triangle_uvs.numpy().reshape(-1, 2)
vertex_uvs  = flatten_uvs[ids]
```

**Comment by chisarie** [comment]
Thank you very much, it works! 
Just as a note, it required a small change: 

```python
_, ids = np.unique(triangles, return_index=True)
```
