### ISSUE TITLE
o3d.t.geometry.RaycastingScene.create_rays_pinhole produces NaN from nadir view

### ISSUE THREAD

**Issue by qiyang77** [isl-org/Open3D#6471]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

Function create_rays_pinhole() produces NaN rays from nadir view, so the rendering will fail.
A example to duplicate this bug is as follows,
```import open3d as o3d
import matplotlib.pyplot as plt

cube = o3d.t.geometry.TriangleMesh.from_legacy(
                                    o3d.geometry.TriangleMesh.create_box())

# Create scene and add the cube mesh
scene = o3d.t.geometry.RaycastingScene()
scene.add_triangles(cube)

# Rays are 6D vectors with origin and ray direction.
# Here we use a helper function to create rays for a pinhole camera.
rays = scene.create_rays_pinhole(fov_deg=60,
                                 center=[0.5,0.5,0.5],
                                 eye=[0.5,0.5,2],
                                 up=[0,0,1],
                                 width_px=320,
                                 height_px=240)
# Numpy ray array
rays_n = rays.numpy()

# Compute the ray intersections.
ans = scene.cast_rays(rays)

# Visualize the hit distance (depth)
plt.imshow(ans['t_hit'].numpy())```
Here we can see the rays_n is NaN

### Steps to reproduce the bug

```python
import open3d as o3d
import matplotlib.pyplot as plt

cube = o3d.t.geometry.TriangleMesh.from_legacy(
                                    o3d.geometry.TriangleMesh.create_box())

# Create scene and add the cube mesh
scene = o3d.t.geometry.RaycastingScene()
scene.add_triangles(cube)

# Rays are 6D vectors with origin and ray direction.
# Here we use a helper function to create rays for a pinhole camera.
rays = scene.create_rays_pinhole(fov_deg=60,
                                 center=[0.5,0.5,0.5],
                                 eye=[0.5,0.5,2],
                                 up=[0,0,1],
                                 width_px=320,
                                 height_px=240)
# Numpy ray array
rays_n = rays.numpy()

# Compute the ray intersections.
ans = scene.cast_rays(rays)

# Visualize the hit distance (depth)
plt.imshow(ans['t_hit'].numpy())
```

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04 / macOS 10.15 / Windows 10 64-bit
- Python version: Python 3.8 / output from `import sys; print(sys.version)`
- Open3D version: output from python: `print(open3d.__version__)`
- System architecture: x86 / arm64 / apple-silicon / jetson / rpi
- Is this a remote workstation?: yes or no
- How did you install Open3D?: pip / conda / build from source
- Compiler version (if built from source): gcc 7.5 / clang 7.0
```

**Comment by benjaminum** [comment]
Hi @qiyang77, the viewing direction and the up vector may not be parallel. You have to provide a different up vector for your case

**Comment by qiyang77** [comment]
> Hi @qiyang77, the viewing direction and the up vector may not be parallel. You have to provide a different up vector for your case

Hi @benjaminum, thanks for your reply! I see, the up vector represents the up of the camera. I have another concern: the up vector of the camera should be orthogonal with the vector of viewing direction (the vector from eye to center), right? If so, why we can freely set the up vector instead of setting the Yaw angle of the camera?

**Comment by benjaminum** [comment]
The method will recompute an orthogonal up vector. It is just for convenience that you can pass an upvector that is roughly correct. If you want to use Euler angles you need to create the 4x4 world to camera transform and the 3x3 camera intrinsic matrix manually and pass it to create_rays_pinhole.
