### ISSUE TITLE
Missing argument description in the documentation for open3d.visualization.rendering.Camera.set_projection()

### ISSUE THREAD

**Issue by ajktym94** [isl-org/Open3D#6478]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

In the first way of overloading open3d.visualization.rendering.Camera.set_projection(), it takes 5 floating point arguments while the [documentation ](http://www.open3d.org/docs/latest/python_api/open3d.visualization.rendering.Camera.html#open3d.visualization.rendering.Camera.set_projection) mentions about only 4 floating point arguments. Which and what should be the 5th argument?

> set_projection(self: open3d.cpu.pybind.visualization.rendering.Camera, arg0: float, arg1: float, arg2: float, arg3: float, arg4: open3d.cpu.pybind.visualization.rendering.Camera.FovType) -> None
> 
> Sets a perspective projection. set_projection(field_of_view, aspect_ratio, far_plane, field_of_view_type)

![afbeelding](https://github.com/isl-org/Open3D/assets/8183201/65822f66-ddc0-4fa6-8a7a-85d109385922)

**Comment by ajktym94** [comment]
From [open3d::visualization::rendering::Camera Class Reference](http://www.open3d.org/docs/0.12.0/cpp_api/classopen3d_1_1visualization_1_1rendering_1_1_camera.html), I assume `arg2` should be `near_plane`. Can somebody confirm?

**Comment by saurabheights** [comment]
@ajktym94 
There are three definitions of set_projection - 
https://github.com/isl-org/Open3D/blob/master/cpp/pybind/visualization/rendering/rendering.cpp#L213C5-L232

Also, you can compare python definitions with their C++ counterpart here - http://www.open3d.org/docs/latest/cpp_api/classopen3d_1_1visualization_1_1rendering_1_1_camera.html#a74f1f79e0167da3a44b874054c3c9043


Also, make sure you use same version for C++ and python docs. For python, you used latest (check url) and for C++, its 0.12.0.

**Comment by ajktym94** [comment]
Thank you. I see from the C++ definition that the third argument should be `near_plane`.
