### ISSUE TITLE
How to perform PointCloud clusterization based on color instead of position?

### ISSUE THREAD

**Issue by JaviLaplaza** [isl-org/Open3D#6479]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I was wondering if there is a way to perform point cloud clusterization based on color property instead of position.

As far as I know, [DBSCAN function](http://www.open3d.org/docs/release/tutorial/geometry/pointcloud.html#DBSCAN-clustering) is a density based clustering algorithm. But I would like to be able to cluster my pointcloud based on color property, or even maybe desnity + color.

Any ideas?

**Comment by saurabheights** [comment]
Create a new pointcloud where vertices are not at XYZ, but at HSV values (dont use RGB). Do clustering on HSV locations.

**Comment by saurabheights** [comment]
P.s. check https://en.m.wikipedia.org/wiki/Color_difference

**Comment by JaviLaplaza** [comment]
That's a very clever approach, I will try it when I can.

Thank you!
