### ISSUE TITLE
Enable HTTPS on open3d.org

### ISSUE THREAD

**Issue by PieroV** [isl-org/Open3D#6538]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `main` branch).

### Proposed new feature or change

open3d.org doesn't have a HTTPS version, but it could probably have one.
It feels quite strange when a site works only on plain text HTTP nowadays.
Also, all major browsers can be set to raise warnings for sites requiring HTTP, and your site is one of the few exceptions that trigger them in my everyday web usage.

### References

https://letsencrypt.org/
https://support.mozilla.org/en-US/kb/https-only-prefs
https://www.cloudflare.com/learning/ssl/why-use-https/

**Comment by ssheorey** [comment]
The open3d website is now available through https!

https://www.open3d.org/

**Comment by PieroV** [comment]
Thanks :+1: !
