### ISSUE TITLE
Crash on close if using Tensor on CUDA device

### ISSUE THREAD

**Issue by kadeb** [isl-org/Open3D#6555]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `main` branch).

### Describe the issue

Everytime I close the software after initializing a Tensor on the CUDA device, it crashes.
You will find below a picture of the call stack
![Screenshot 2023-12-28 230911](https://github.com/isl-org/Open3D/assets/35126488/ffb24789-fce4-4dd5-9815-eb609f86c7ae)

### Steps to reproduce the bug

```python
Run the following lines in the main:

"""
open3d::core::Tensor tensor = open3d::core::Tensor::Eye(4, open3d::core::Float64, open3d::core::Device("CUDA:0"));
return 1;
"""
```

### Error message

[Open3D Error] (void __cdecl open3d::core::__OPEN3D_CUDA_CHECK(enum cudaError,const char *,const int)) C:\Users\Kevin\Desktop\work\sdk\open3d-0.17.0\cpp\open3d\core\CUDAUtils.cpp:289: C:\Users\Kevin\Desktop\work\sdk\open3d-0.17.0\cpp\open3d\core\CUDAUtils.cpp:114 CUDA runtime error: driver shutting down

### Expected behavior

I would expect the software to close smoothly and free the memory without any issues

### Open3D, Python and System information

```markdown
- Operating system: Windows 11 64-bit
- Open3D version: 0.17.0
- System architecture: x64
- Is this a remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): msvc2019_64
```

**Comment by yuecideng** [comment]
Hi @kadeb, add `-DENABLE_CACHED_CUDA_MANAGER=OFF` to your cmake config and re-built the library. I also encountered this problem and this workaround solves the issue.

**Comment by kadeb** [comment]
Thank you for the help, it does look like it fixed my issue for this specific line of code!
