### ISSUE TITLE
open3d-app-0.18.0-Ubuntu.deb link is dead

### ISSUE THREAD

**Issue by doisyg** [isl-org/Open3D#6573]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

### Describe the issue

See:
https://github.com/isl-org/Open3D/releases/download/v0.18.0/open3d-app-0.18.0-Ubuntu.deb

### Steps to reproduce the bug

```python
Try do download open3d-app-0.18.0-Ubuntu.deb
```

### Error message

Dead link

### Expected behavior

Downloading the newest version

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04
```

**Comment by ssheorey** [comment]
Fixed. Links should work from both github releases page and www.open3d.org home page:

https://github.com/isl-org/Open3D/releases/download/v0.18.0/open3d-viewer-0.18.0-Linux.deb
