### ISSUE TITLE
Pybind issue

### ISSUE THREAD

**Issue by syncle** [isl-org/Open3D#66]
I notice that cmake 3.6 tool-chain generates `py3d` instead of `py3d.so` after compilation.
This affects python scripts. They don't recognize `py3d` library.

For example:
```
> python
>>> from py3d import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named py3d
```

But if I change the name, it works
```
> mv py3d py3d.so
> python
>>> from py3d import *
(no error)
```

This issue comes with MacOSX Sierra, Cmake 3.6, Mac Native Python 2.7. 
Windows + VisualStudio2015 seems to fine.
We may need to change CMakeList.txt file or get some information from Pybind to fix this issue.

**Comment by qianyizh** [comment]
May worth adding

```
cmake -DPYTHON_EXECUTABLE:FILEPATH=/home/account_id/anaconda3/bin/python 
-DPYTHON_LIBRARY='/home/account_id/anaconda3/lib/libpython3.so' ../src
```

To our document though.

**Comment by qianyizh** [comment]
This is the command I eventually used to make anaconda with customized env work:

```
cmake -DPYTHON_LIBRARY=/Users/qianyizh/anaconda/envs/py36/lib/libpython3.6m.dylib
-DPYTHON_INCLUDE_DIR=/Users/qianyizh/anaconda/envs/py36/include/python3.6m
-DPYTHON_EXECUTABLE:FILEPATH=/Users/qianyizh/anaconda/envs/py36/bin/python3.6m
../src
```
