### ISSUE TITLE
project_to_depth_image ERROR Open3D version 0.18

### ISSUE THREAD

**Issue by jjpatino-byte** [isl-org/Open3D#6651]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

### Describe the issue

When trying to project a pointcloud to rgbd image, I get this error "IndexError: invalid unordered_map<K, T> key".

### Steps to reproduce the bug

```python
import open3d as o3d
import numpy as np
device = o3d.core.Device("CPU:0")
dtype = o3d.core.float32

pcd = o3d.t.geometry.PointCloud()
test = o3d.io.read_point_cloud("pcdFinal.pcd") #use any pointcloud
pcd.from_legacy(test)
pcd.point.colors = o3d.core.Tensor(np.asarray(test.colors), dtype, device)

intr = o3d.core.Tensor([[924.2759399414062, 0.0, 640], [0.0, 924.2759399414062, 360],
                                 [0, 0, 1]])
pcd.project_to_depth_image(width = 1280, height = 720,  intrinsics = intr )
```

### Error message

pcd.project_to_depth_image(width = 1280, height = 720,  intrinsics = intr )
IndexError: invalid unordered_map<K, T> key

### Open3D, Python and System information

```markdown
- Operating system:  Windows 10 64-bit
- Python version: Python 3.9.4 / output from `import sys; print(sys.version)`
- Open3D version: 0.18.0
- System architecture: x64
- Is this a remote workstation?: no
- How did you install Open3D?: pip
```

**Comment by rxba** [comment]
The issue here is that `pcd.from_legacy(test)` does not change `pcd` in-place, and thus `project_to_depth_image` is called with a point cloud that has no `positions` attribute, which results in the error.

I've opened a PR to return an empty image and to provide a warning to the user if the function is called like this.

In your case, the correct way to use `from_legacy` would be to change it to 
```python
pcd = o3d.t.geometry.PointCloud.from_legacy(test)
```
