### ISSUE TITLE
Cannot install open3d==0.11.2 as sklearn is deprecated 

### ISSUE THREAD

**Issue by Jiang0903** [isl-org/Open3D#6678]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

#### Firstly, I install it by:

```
pip install open3d==0.11.2
```

However, it reports the `error message` below as open3d==0.11.2 seems to treat sklearn as a dependency.

#### Then, I download the [open3d-0.11.2-cp38-cp38-manylinux1_x86_64.whl](https://github.com/isl-org/Open3D/releases/download/v0.11.2/open3d-0.11.2-cp38-cp38-manylinux1_x86_64.whl) and try to install it by
```
pip install open3d-0.11.2-cp38-cp38-manylinux1_x86_64.whl
```

But it still reports the same `error message` when trying to install sklearn.

How can I install open3d==0.11.2 successfully? 
Is there any methods that can install `open3d==0.11.2` and avoid installing `sklearn` at the same time? 

### Error message

```shell
Collecting sklearn
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/46/1c/395a83ee7b2d2ad7a05b453872053d41449564477c81dc356f720b16eac4/sklearn-0.0.post12.tar.gz (2.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
      
      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
      
      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04
- Python version: Python 3.8
- Open3D version: 0.11.2 (can not install)
- System architecture: x86
- Is this a remote workstation?: yes
- How did you install Open3D?: pip install open3d==0.11.2 && pip install '.whl' file
```

**Comment by ssheorey** [comment]
Hi @Jiang0903 please upgrade to the latest Open3D (v0.18 at the moment). We cannot support older versions.

PS: In this case, you can ask pip to ignore dependencies, if you do not need the sklearn dependency.

`pip install --no-deps open3d==0.11.2`

You'll need to install other dependencies manually.
