### ISSUE TITLE
Enhanced Support for Character Abilities and Capacities

### ISSUE THREAD

**Issue by ZielIhu** [isl-org/Open3D#6696]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

### Proposed new feature or change

I propose the implementation of a robust system for managing character abilities and capacities within Open3D. This feature would enhance the engine's capabilities, allowing developers to create more complex and dynamic gameplay experiences akin to Unreal Engine's Gameplay Ability System.

### References

Unreal Engine's Gameplay Ability System documentation: [link](https://github.com/tranek/GASDocumentation)

### Additional information

Implementing such a feature would greatly benefit game developers using Open3D Engine by providing them with powerful tools to handle character abilities efficiently. 

I look forward to hearing your thoughts on this feature request. Thank you for considering it.

**Comment by ssheorey** [comment]
Hi @ZielIhu are you looking for the Open 3D game engine? https://o3de.org/ 
That is unrelated to the Open3D library (not a game engine!). Please file this issue in their repo.
