### ISSUE TITLE
The url of development pip package is invalid for Linux system

### ISSUE THREAD

**Issue by ErvinZzz** [isl-org/Open3D#6699]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

#### I install Open3D by:
```
pip install -U -f https://www.open3d.org/docs/latest/getting_started.html open3d
```

### Error message

```shell
Collecting open3d
  ERROR: HTTP error 404 while getting https://storage.googleapis.com/open3d-releases/python-wheels/open3d-0.18.0%2B0cf605f-cp39-cp39-manylinux_2_27_x86_64.whl (from https://www.open3d.org/docs/latest/getting_started.html)
ERROR: Could not install requirement open3d from https://storage.googleapis.com/open3d-releases/python-wheels/open3d-0.18.0%2B0cf605f-cp39-cp39-manylinux_2_27_x86_64.whl because of HTTP error 404 Client Error: Not Found for url: https://storage.googleapis.com/open3d-releases/python-wheels/open3d-0.18.0%2B0cf605f-cp39-cp39-manylinux_2_27_x86_64.whl for URL https://storage.googleapis.com/open3d-releases/python-wheels/open3d-0.18.0%2B0cf605f-cp39-cp39-manylinux_2_27_x86_64.whl (from https://www.open3d.org/docs/latest/getting_started.html)
```

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 22.04
- Python version: Python 3.9 / output from `import sys; print(sys.version)`
- Open3D version: 0.18
- System architecture: x86
- Is this a remote workstation?: no
- How did you install Open3D?: pip
- Compiler version (if built from source): gcc 7.5
```

**Comment by rossng** [comment]
I also encountered this when trying to manually download the latest development wheel from https://www.open3d.org/docs/latest/getting_started.html#development-version-pip

**Comment by ssheorey** [comment]
Should be fixed by #6716

**Comment by ssheorey** [comment]
Docs are updated and devel downloads work again.

**Comment by FishWoWater** [comment]
@ssheorey wheel urls seem invalid again, pls have a look
