### ISSUE TITLE
Display text on a open3d window

### ISSUE THREAD

**Issue by eyabesbes** [isl-org/Open3D#6723]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

### My Question

Hi,

I am currently using Open3D to visualize real-time point cloud data from a moving vehicle. My goal now is to display the vehicle's real-time location data on the Open3D window along with the point clouds.

I have already stored the real-time location data in a certain variable, but I'm unsure how to visualize both the point clouds and the location text simultaneously.

Does anyone know how to print text on an Open3D window?

**Comment by ssheorey** [comment]
See these Python examples (there are C++ ones as well  / the API is very similar)

- Text at a 3D location: https://www.open3d.org/docs/latest/python_example/visualization/index.html#text3d-py
- Text labels: See the all_widgets.py example and take your pick. It looks like this:

<img width="403" alt="Screenshot 2024-03-27 at 10 59 31 PM" src="https://github.com/isl-org/Open3D/assets/41028320/c11b12f2-d6d1-4bca-a50a-9983015887ef">
