### ISSUE TITLE
module 'open3d.cpu.pybind.t.geometry' has no attribute 'vtkutils'(using open3d version 0.18.0+5c982c7)

### ISSUE THREAD

**Issue by chann7h** [isl-org/Open3D#6786]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

#### I first cloned Open3D by:
```
i have pip installation using 
>pip install -U -f https://www.open3d.org/docs/latest/getting_started.html open3d

when try to create mesh using vtkPolydata writer
dataset ='C:\\Users\\ic002317\\Downloads\\1.0\\data\\908ac523-2dd3-4c1b-bff3-8c32816860fb'
vtk_path=os.path.join(dataset,'908ac523data00006_out.vtk')
reader= vtkPolyDataReader()
reader.SetFileName(vtk_path)
reader.Update()
polyData= reader.GetOutput()
mesh = o3d.t.geometry.vtkutils.CreateTriangleMeshFromVtkPolyData(polyData)

open3d API shows there is method
https://www.open3d.org/docs/latest/cpp_api/namespaceopen3d_1_1t_1_1geometry_1_1vtkutils.html

### Error message

```shell
could not find the API
```

### Open3D, Python and System information

```markdown
windows OS
```

### Additional information

none

**Comment by ssheorey** [comment]
Hi @chann7h vtk is used internally by Open3D and is not available for use by Open3D users. If you need VTK, please use it directly.
