### ISSUE TITLE
TransformationEstimationPointToPlane::ComputeRMSE

### ISSUE THREAD

**Issue by jwm111** [isl-org/Open3D#679]
it seems a bug in funciton "TransformationEstimationPointToPlane::ComputeRMSE". 
![image](https://user-images.githubusercontent.com/19990848/48341752-d6f3db80-e6a8-11e8-8cf4-e4defabb1bd6.png)

I think the variable "err"  is accumulative ，so "err = r * r" should  be instead by "err += r * r".

**Comment by syncle** [comment]
That's great point. Thanks! Could you submit PR for this?
