### ISSUE TITLE
compute_vertex_normals produces wrong results when mesh previous has incorrect normals

### ISSUE THREAD

**Issue by JunzheJosephZhu** [isl-org/Open3D#6848]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

### Describe the issue

When I call compute_vertex normals() on a mesh already with incorrect normals, the result would be wrong:
![image](https://github.com/isl-org/Open3D/assets/24391451/9731b762-6b40-4a5a-86c3-51db0e3a1af4)

However, if I set the existing normals to zeros and call compute_vertex_normals(), the result is correct. I think this is due to the code here not zeroing out previous normals here before accumulating:
https://github.com/isl-org/Open3D/pull/4224/commits/19551b189a82060b4cd44cc80faaccd9e4bfcb63
![image](https://github.com/isl-org/Open3D/assets/24391451/754e7269-fdc8-4a85-8077-db91b5f424f4)

### Steps to reproduce the bug

```python
# load any mesh
mesh = mesh.compute_triangle_normals(normalized=False)
if reproduce_error:
    mesh.vertex_normals = o3d.utility.Vector3dVector(np.random.randn(len(mesh.vertices), 3))
else:   
    mesh.vertex_normals = o3d.utility.Vector3dVector(np.zeros_like(np.asarray(mesh.vertices)))
mesh.compute_vertex_normals()

# make a point cloud with vertices and vertex normals to show
pcd = o3d.geometry.PointCloud()
pcd.points = mesh.vertices
pcd.normals = mesh.vertex_normals
o3d.visualization.draw_geometries([pcd], point_show_normal=True)
```

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04 
- Python version: Python 3.9
- Open3D version: 0.18.0
- System architecture: x86 
- Is this a remote workstation?: no
- How did you install Open3D?: pip
```

**Comment by benjaminum** [comment]
@JunzheJosephZhu Thanks a lot for finding this bug. Since you already identified where the problematic code is could you create a PR fixing the bug?

**Comment by JunzheJosephZhu** [comment]
I haven't really compiled open3d and dont intend to do it in the short
term. Ideally, someone can just add a line that zeros out vertex normals
here
https://github.com/isl-org/Open3D/commit/19551b189a82060b4cd44cc80faaccd9e4bfcb63#diff-ace2240cda6c6014f5a91df75ff46050c6ba940dd076810a18f2e1d3d73b61a3R148
next time they work on the codebase.
Joseph Zhu

**Comment by benjaminum** [comment]
Missed opportunity to become a contributor 😉    
Thanks again for reporting the bug @JunzheJosephZhu !
