### ISSUE TITLE
how to set VerbosityContextManager in c++

### ISSUE THREAD

**Issue by songhc8** [isl-org/Open3D#6875]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

### My Question

In c++, how to set VerbosityContextManager to view the logs.

**Comment by rxba** [comment]
Hey @songhc8 , you can find information on how to use different verbosity levels in C++ in the examples, e.g. in [Logs.cpp](https://github.com/isl-org/Open3D/blob/main/examples/cpp/Log.cpp):
```
using namespace open3d;
utility::SetVerbosityLevel(utility::VerbosityLevel::Debug);
// ...
utility::SetVerbosityLevel(utility::VerbosityLevel::Info);
```
