### ISSUE TITLE
"Segmentation fault (core dumped)" when using o3d.visualization.rendering.OffscreenRenderer

### ISSUE THREAD

**Issue by MnKnight1** [isl-org/Open3D#6929]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

### Steps to reproduce the issue

```
conda create -n open3d python==3.11
conda activate open3d
pip install numpy==1.26.4
pip install open3d
 python -c "import open3d as o3d; \
        box_render = o3d.visualization.rendering.OffscreenRenderer(512, 512)"
```

### Error message

```shell
[Open3D INFO] EGL headless mode enabled.
FEngine (64 bits) created at 0x7f1396ceb010 (threading is enabled)
eglInitialize failed
Segmentation fault (core dumped)

Is egl causing the error?
I have tried "sudo apt install libegl1 libegl1-mesa libegl1-mesa-dev"
```

### Open3D, Python and System information

```markdown
- Operating system:  Ubuntu 20.04.6 LTS
- Python version: 3.11.0 (main, Mar  1 2023, 18:26:19) [GCC 11.2.0]
- numpy version:1.26.4
- Open3D version: 0.18.0+18a47ef
- System architecture: x86 
- Is this a remote workstation?: yes 
- How did you install Open3D?: pip
```

**Comment by Salieri0515** [comment]
same error

**Comment by MnKnight1** [comment]
我通过重新安装驱动解决了这个问题，安装时不要取消安装OpenGL文件

**Comment by shaoqiwu** [comment]
Hello, I encountered the same problem as you. I would like to ask what you mean by "reinstalling the driver" here?

**Comment by shaoqiwu** [comment]
> 我通过重新安装驱动解决了这个问题，安装时不要取消安装OpenGL文件

Hello, I encountered the same problem as you. I would like to ask what you mean by "reinstalling the driver" here?

**Comment by MnKnight1** [comment]
you can install nVidia driver through command like this，i did not add `–no-opengl-files`this parameter
```
sudo chmod 777 NVIDIA-Linux-x86_64-525.53.run  
sudo ./NVIDIA-Linux-x86_64-525.53.run –no-opengl-files -no-x-check 
```
