### ISSUE TITLE
`VoxelGrid.create_from_point_cloud` should allow for choosing color reduction method other than avg

### ISSUE THREAD

**Issue by IDoCodingStuffs** [isl-org/Open3D#6934]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

### Proposed new feature or change

Currently, voxel grid from point cloud defaults to averaging colors per the docs: https://www.open3d.org/docs/release/python_api/open3d.geometry.VoxelGrid.html#open3d.geometry.VoxelGrid.create_from_point_cloud

The problem is, that is not always desirable behavior. I am trying to reconstruct a voxel grid from MRI slices with different orientations where I am feeding different modalities as their own channels:

![image](https://github.com/user-attachments/assets/4f26b86b-957b-45d4-a592-dd1c947a7202)

When I convert this to a voxel grid, this leads to artifacts where these slices intersect due to averaging:
![image](https://github.com/user-attachments/assets/2525f103-8458-43d2-8ce3-9a0e421bc9e0)
![image](https://github.com/user-attachments/assets/1143823f-3c0b-46f8-9e59-8dc0075cbfc2)

Ideally, I should be able to reduce by sum or max per channel instead of average.

**Comment by rxba** [comment]
Hey @IDoCodingStuffs , I've added the feature to select between average, min, max and sum color mode for VoxelGrid creation from PointCloud and opened a PR for this.
