### ISSUE TITLE
Viewpoint change does not take effect without run()

### ISSUE THREAD

**Issue by yusufguleray** [isl-org/Open3D#6990]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

### Describe the issue

I was loading a viewpoint.json for a specific view angle with:
```
param = o3d.io.read_pinhole_camera_parameters(viewpoint_file)
vis.get_view_control().convert_from_pinhole_camera_parameters(param, True)
```
and after I ran the visualization window as usual with:
`vis.run() `

Which worked perfectly.

But now I need to save the visualizations without creating a windows and to do that I got rid of the `run()` command and used the:
`vis.capture_screen_image(f"livox-horizon/output/{frame_id}.png", True)`

But the save images are with the default viewpoint and not the one I am loading with the `viewpoint.json`.

What causes this unexpected behavior and how could it be fixed?

### Steps to reproduce the bug

```python
param = o3d.io.read_pinhole_camera_parameters(viewpoint_file)
vis.get_view_control().convert_from_pinhole_camera_parameters(param, True)
vis.capture_screen_image("output.png", True)
```

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04
- Python version: Python 3.10.12
- Open3D version: 0.18.0
```

**Comment by ChihaoZhang** [comment]
There are two points I think you should figure out:
- `capture_screen_image()` just captures what your window or screen is displaying by calling OpenGL APIs, which means, if you do not visualize your geometries or point cloud explictly, then it just works like you press the PrintScreen key on your keyboard.
- In your case, when the viewpoint is changed by view control, Open3D will render a new image automatically for displaying with the geometries added unmodified and this is what `run()` does exactly (see the source code snippet below though updating geometry is also necessary if the geometry has been changed). 
  ```c++
  void Visualizer::Run() {
        BuildUtilities();
        UpdateWindowTitle();
        while (bool(animation_callback_func_) ? PollEvents() : WaitEvents()) {
            if (bool(animation_callback_func_in_loop_)) {
                if (animation_callback_func_in_loop_(this)) {
                    UpdateGeometry();
                }
                // Set render flag as dirty anyways, because when we use callback
                // functions, we assume something has been changed in the callback
                // and the redraw event should be triggered.
                UpdateRender();
            }
        }
  }
  ```
So if you want to take the screenshot with changed viewpoint but without `run()`, you should do the rendering yourself by `poll_events()` and `update_renderer()`. Below is a demo:

```python
import open3d as o3d


data_path = '/home/admin17/vision3d/data/examples/ArmadilloMesh.ply'
pcd = o3d.io.read_triangle_mesh(data_path).sample_points_poisson_disk(5000)

vis = o3d.visualization.Visualizer()
vis.create_window(width=1920, height=1080, visible=True)
vis.add_geometry(pcd)

# Set view control
# replace the following with 'vis.get_view_control().convert_from_pinhole_camera_parameters(param, True)' in your test
view_ctrl = vis.get_view_control()
view_ctrl.set_lookat([0, 0, 0])
view_ctrl.set_up([0, -1, 0])
view_ctrl.set_front([0, 0, 1])
view_ctrl.set_zoom(0.1)

vis.poll_events()
vis.update_renderer()
vis.capture_screen_image('test.png')
```
Note the visibility of the window is necessary, or you will only get a screenshot but no point cloud involved.

Above is based on my understanding on Open3D visualization and hope it helps. I'm not sure if there is any more convenient way, but if you are more interested in depth image, `poll_events()` and `update_renderer()` can be replaced by `capture_depth_float_buffer(True)`.

**Comment by yusufguleray** [comment]
Dear @ChihaoZhang,

thanks a lot for your answer. It is quite helpful and insightful.

After changing reading your answer i updated my code with:

```python
    view_ctrl = vis.get_view_control()
    param = o3d.io.read_pinhole_camera_parameters(viewpoint_file)
    view_ctrl.convert_from_pinhole_camera_parameters(param,True)
    vis.poll_events()
    vis.update_renderer()
    vis.capture_screen_image()
```

And now it seems to work. Thanks again and this issue is closed.
