### ISSUE TITLE
"select_by_index" to work with the class "open3d.pipelines.registration.Feature"

### ISSUE THREAD

**Issue by RubensBenevides** [isl-org/Open3D#7004]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

### Proposed new feature or change

Suppose that I have a list of indexes
`indexes = o3d.utility.IntVector( [10,20,30] )`
and I want to select these indexes from the FPFH descriptors:
`FPFH = o3d.pipelines.registration.compute_fpfh_feature(cloud, kd_tree_descriptor)`
I could do
`FPFH.select_by_index(indexes)` but:

`'open3d.cpu.pybind.pipelines.registration.Feature' object has no attribute 'select_by_index'`

I can convert the FPFH features to numpy arrays:
`FPFH = np.asarray(FPFH.data)`
`FPFH = FPFH.transpose()`

and then select only the rows that I want
`FPFH = FPFH[indexes]`

But now, there is no way to convert the FPFH numpy array back to a feature object. 

### References

(https://www.open3d.org/docs/release/python_api/open3d.pipelines.registration.Feature.html#open3d.pipelines.registration.Feature)

**Comment by nicolaloi** [comment]
I'll open a PR for this.

**Comment by RubensBenevides** [comment]
Thanks for your attention, Nicolaloi. I wanted this function to select only FPFH features calculated at keypoints. 
One problem with Open3D is that it calculates the FPFH for all the points in the cloud, which is not at all efficient. 
In my case, I work with the registration of clouds from Topographic/Terrestrial Laser Scanners, and ideally there should be a way of calculating the FPFH only for certain indices, such as the keypoints of the ISS detector.

Translated with DeepL.com (free version)

**Comment by nicolaloi** [comment]
I have opened a PR for the original feature request of the `select_by_index` method. What you describe in your comment is a different feature request. Can you open a new issue?
