### ISSUE TITLE
What's the reference of distance queries?

### ISSUE THREAD

**Issue by Buffyqsf** [isl-org/Open3D#7038]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

### My Question

I came across a tutorial on distance queries (https://www.open3d.org/docs/release/tutorial/geometry/distance_queries.html), but it seems there is no reference for the method, particularly on how to compute the signed distance from a point to a triangular mesh. Do you have any references?
Thanks!

**Comment by amabilee** [comment]
Have you tried `ray-casting` with `compute_signed_distance()` method in Open3D?

1. Calculate the shortest distance between the given point and the surface of the mesh. This gives the unsigned distance.
2. Then cast a ray from the point in any direction and Count how many times the ray intersects with the mesh:
`Odd number` of intersections means the point is **inside** the mesh.
`Even number` of intersections means the point is **outside** the mesh.
3. Assign the Sign:
If the point is `inside` the mesh, the distance is **negative**. 
If the point is `outside` the mesh, the distance is **positive**.

The signed distance tells you how far the point is from the surface and whether it’s inside (negative) or outside (positive) the mesh.

**Comment by Buffyqsf** [comment]
@amabilee Hahaha! Thank you for your reply! Sorry, maybe my expression is ambiguous. What I want to know is are there any references for these methods? It's not how to use it.

**Comment by amabilee** [comment]
Sure, here is the references that I know of:

[**Example Codes**](https://www.open3d.org/docs/0.17.0/python_example/geometry/ray_casting/index.html)
[**Documentation**](https://www.open3d.org/docs/latest/tutorial/geometry/distance_queries.html)

I hope this helps!

**Comment by Buffyqsf** [comment]
@amabilee Thanks a lot! And one more thing, do you know any published articles or papers related to this?

**Comment by amabilee** [comment]
Have a look on this article:
[NVIDIA Article](https://jcgt.org/published/0011/03/06/)
and this:
[Alex Benton, University of Cambridge](https://www.cl.cam.ac.uk/teaching/1819/FGraphics/1.%20Ray%20Marching%20and%20Signed%20Distance%20Fields.pdf)

One of the best writers on the subject is Inigo Quilez.

**Comment by cwreynolds** [comment]
@Buffyqsf — if you are looking for a published journal paper to cite in your own draft paper, [scholar.google.com](https://scholar.google.com) is a great place to start. I don't know a lot about this topic, but I went there today and searched for [signed distance function](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=signed+distance+function&oq=signed+distance). It found 3.6 million citations. Near the top of the list was:

Stanley J. Osher and Ronald P. Fedkiw (2003). Constructing Signed Distance Functions. In Level Set Methods and Dynamic Implicit Surfaces. Pages 63–74. Springer. ISBN 9780387227467. https://link.springer.com/chapter/10.1007/0-387-22746-6_7

**Comment by Buffyqsf** [comment]
@cwreynolds @amabilee  Thank you guys! That helps a lot!
