### ISSUE TITLE
registration_icp threshold

### ISSUE THREAD

**Issue by MulinYu** [isl-org/Open3D#723]
hello，i have a question. What is the mean of parameter "threshold" in method "registration_icp" of "point to point". Waiting ur reponse. merci.

**Comment by syncle** [comment]
Hi @MulinYu. It is used for finding correspondence set given current transformation matrix estimation. Specifically, in step 1) in[ this document](http://open3d.org/docs/tutorial/Basic/icp_registration.html#point-to-point-icp), only the point within the distance of the given threshold is considered as a correspondence, and added to the set K.
