### ISSUE TITLE
Custom visualization by giving points as input. 

### ISSUE THREAD

**Issue by rishikeshck** [isl-org/Open3D#740]
**Is your feature request related to a problem? Please describe.**
I'm trying to do a custom visualization of the point cloud input given as some points in the point cloud. 
for eg. I have a huge terrain forest dataset with a road through a forest. I want to navigate along the road(by having the road x,y,z points with me). Is there any way to do that. 

I have explored custom visualization but unfortunately, I could make use of it. 
Please suggest any approach to do it.

**Comment by syncle** [comment]
> I have a huge terrain forest dataset with a road through a forest. I want to navigate along the road(by having the road x,y,z points with me).
I cannot fully understand the use case. Could you elaborate it more?

**Comment by rishikeshck** [comment]
sure, I have a lidar point cloud data of a large area. I have the location points along a path where the data is captured a .kml file. 
I want to visualize the point cloud in a similar manner how it was captured. Just like an animation or a video you see while you are moving along the same path. 
for eg please refer the video 
https://www.youtube.com/watch?v=Ml61-GHjZHg 
Will I be to do a similar visualization in open3d?

**Comment by syncle** [comment]
Sorry @rishikeshck for the late reply. The video is really awesome and shall be good application using Open3D. Regarding the question, I am pretty sure you can. What you will need is to camera pose and camera intrinsics, and update camera poses. Please check ``examples/Python/Advanced/customized_visualization.py``. You will need to tweak camera poses as you wanted and save image sequences. If there is an issue, and you are able to share minimal code and data, I would be glad to have a look.

**Comment by tfy14esa** [comment]
Dear @syncle 
My goal is similar to @rishikeshck. Consider a real-time SLAM system that takes as input an RGBD stream and updates the mesh or pointcloud is updated as the algorithm runs. For a concrete example, see e.g. [this video](https://www.youtube.com/watch?v=C6-xwSOOdqQ&feature=emb_title).

Is this possible to do in Open3D?

Cheers,
Erik

**Comment by germanros1987** [comment]
The new scriptable rendering API should provide a solution for this problem.

**Comment by germanros1987** [comment]
@errissa feel free to close this issue once we have rolled out the new "scriptable rendering API".
