### ISSUE TITLE
Zoom in from python API

### ISSUE THREAD

**Issue by ajayrfhp** [isl-org/Open3D#828]
How to zoom in on a rendered mesh using python code. I want to save a zoomed(zoom in) view point. 
At the moment I am doing,
```
    vis = open3d.Visualizer()
    vis.create_window()
    vis.add_geometry(mesh)
    ctr = vis.get_view_control()

    # ctr.scale(1000) is zooming out 
    # Does ctr.scale(0.0001) zoom in ?

    vis.update_geometry()
    vis.poll_events()
    vis.update_renderer()
    vis.capture_screen_image(file_name)
```
I would like to zoom in before doing vis.capture_screen_image

**Comment by yxlao** [comment]
One way to do it is to set the camera parameter for the visualizer.

See: 
https://github.com/IntelVCL/Open3D/blob/master/examples/Python/Advanced/load_save_viewpoint.py

The key lines:
```python
# get
param = vis.get_view_control().convert_to_pinhole_camera_parameters()

# modify
# ... do something with params, e.g. zoom with changing the intrinsics

# set
ctr.convert_from_pinhole_camera_parameters(param)
```

**Comment by germanros1987** [comment]
@errissa this issue should be addressed by the new scriptable rendering API. Please, feel free to close the issue after the feature is rolled out.
