### ISSUE TITLE
Jupyter visualizer is not showing the point cloud test fragment

### ISSUE THREAD

**Issue by dhorka** [isl-org/Open3D#879]
**Describe the bug**
Jupyter visualizer is not showing the point cloud test fragment. Only an empty figure appears

**To Reproduce**
1. Open jupyter notebook
2. use this piece of code:
```
import open3d
fragment_path = '/work/tools/libs/Open3D/examples/TestData/fragment.ply'
fragment = open3d.read_point_cloud(fragment_path)
visualizer = open3d.JVisualizer()
visualizer.add_geometry(fragment)
visualizer.show()
```
3. See error

**Expected behavior**
See the point cloud displayed in the jupyter notebook

**Screenshots**
![image](https://user-images.githubusercontent.com/39189267/54907358-92ddd680-4ee5-11e9-98a6-cbcefb96924d.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04
 - Python version: 3.5.2
 - Open3D version: master commit [a3e0cfe]
 - Is this remote workstation?: no
 - How did you install Open3D?build_from_source following the ubuntu tutorial

**Additional context**
node version: v11.12.0
npm version: 6.7.0

**Comment by qianyizh** [comment]
@yxlao can you take a look at this?

**Comment by ethanjyx** [comment]
Any updates? I'm having the same issue :)

**Comment by AidasLiaudanskas** [comment]
Same issue here!

**Comment by alanhzh** [comment]
I am working on Jupyterlab and  any call to ipyvolume gives the following error:
Error displaying widget

**Comment by ahyunSeo** [comment]
Any update?

**Comment by JayLIU0911** [comment]
Same issue here!

**Comment by triple-tam** [comment]
I'm working on Google Colab and the point cloud is also not showing

**Comment by xiaobaishu0097** [comment]
I run the jupyter notebook on the remote server and also has no response

**Comment by rjsgml5698** [comment]
> 
> 
> I'm working on Google Colab and the point cloud is also not showing

Did you find a solution?

**Comment by chronbird** [comment]
empty canvas from remote server too

**Comment by TimZaman** [comment]
still an issue

**Comment by walup** [comment]
i'm having the exact same issue

**Comment by qshzh** [comment]
> I am working on Jupyterlab and any call to ipyvolume gives the following error:
> Error displaying widget

It seems there is nbextention for jupyter notebook. There is no labextention support. I have the same error in jupyterlab but no error in jupyter notebook.

**Comment by jousefm** [comment]
Still persisting, any workarounds?

**Comment by albertotono** [comment]
Any idea?

**Comment by yuehaowang** [comment]
Met the same problem in JupyterLab, and an error *"Error displaying widget: model not found"* will be raised.

I take the workaround posted by @UnaNancyOwen in https://github.com/intel-isl/Open3D/issues/1026#issuecomment-788703191, and it works. 

Also, you need to enable the JupyterLab extension of *Poltly* after installing it:

```bash
# JupyterLab renderer support
jupyter labextension install jupyterlab-plotly@4.14.3

# OPTIONAL: Jupyter widgets extension
jupyter labextension install @jupyter-widgets/jupyterlab-manager plotlywidget@4.14.3
```

**Comment by reyanshsolis** [comment]
Hi, Please try our new WebRTC Jupyter Visualizer http://www.open3d.org/docs/release/tutorial/visualization/web_visualizer.html.

Thanks
