### ISSUE TITLE
How can i get the coordinate of the points in a point cloud?

### ISSUE THREAD

**Issue by Keith-Wangg** [isl-org/Open3D#943]
umm, i am interested in some featuer points in a point cloud, so how can i get the coordinate of them? Does this coordinates are in the camera coordinate system?  I find this function in PCL, so i guess open3d may have the similar function, but i just can't find it. If anyone know that, please reply me, thanks!

**Comment by Keith-Wangg** [comment]
In the 'Interactive visualization' example , it shows the coordinates of points just like this:
Picked point #58481 (2.14, 1.56, 1.53) to add in queue.
Picked point #77321 (2.86, 1.92, 1.09) to add in queue.
Picked point #42639 (3.28, 1.53, 1.45) to add in queue.

But when i run the example by myself, i only get the result like this:
 1) Please pick at least three correspondences using [shift + left click]
   Press [shift + right click] to undo point picking
2) Afther picking points, press q for close the window

1) Please pick at least three correspondences using [shift + left click]
   Press [shift + right click] to undo point picking
2) Afther picking points, press q for close the window

and there is nothing to show. Also, i try to print （vis.get_picked_points()），and it shows this:
1) Please pick at least three correspondences using [shift + left click]
   Press [shift + right click] to undo point picking
2) Afther picking points, press q for close the window
[806141, 470261, 338820].
so i can't get the coordinate like the example shows.

**Comment by Keith-Wangg** [comment]
umm, so sorry to bother, when i run the example in the terminal , it shows the coordinate!!
now i want to ensure that this "coordinate" is the coordinate in the camera coordinate system.

**Comment by germanros1987** [comment]
@Keith-Wangg is this issue still bothering you?

**Comment by TangToy** [comment]
http://www.open3d.org/docs/release/tutorial/visualization/interactive_visualization.html
